### ISSUE TITLE
Verification Grid - Recorder Experience Tab error

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1]
http://www.brc.ac.uk/irecord/node/3747

Currently the facility to see "Records of Species X" or "Records for the whole verification group" for individual records is not working.   If I click on any of the numbers displayed in the various tables I am taken to a blank "Explore all records" page each time.  It looks like somewhere along the line data is not being added to a filter to select out the appropriate records.

Matt Smith

**Comment by johnvanbreda** [comment]
I'm not seeing this behaviour - when I click on the numbers I get a correctly populated Explore page relevant to the number I clicked on, even when masquerading as Matt and using the ambphibians filter (since he is up to date with aculeates!). Are you able to repdroduce this?

**Comment by kitenetter** [comment]
This issue assumed to have gone away.
