### ISSUE TITLE
Better handling of verifier querying records - additional record status?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#10]
Some verifiers are unhappy that they can’t mark a record as queried without emailing or publically commenting on the record, and vice versa some want to be able to email the recorder without setting the record to queried. 
JvB response:
Queried is a flag indicating a question has been asked by email or comment, so it doesn’t make sense to use this flag without doing so. Maybe what they want is a new status that sits between plausible and considered incorrect? You can email the recorder by copying their email address from the details panel?

**Comment by johnvanbreda** [comment]
Does this need further consultation?

**Comment by kitenetter** [comment]
I _think_ what people want is the ability to flag a record as "needing further consideration", without having to make a public commitment to its verification status. As you say, verifiers are able to copy email addresses from the details panel, so they can contact people without making a public comment on the record, but if they do that they have no way of filtering out that record to review following an emailed response outside iRecord.

It's possible to argue that this is essentially duplicating the existing "Queried" procedure but doing it outside of iRecord's procedures. I can see that it is useful to be able to contact a recorder without publicly adding any comment to their record (e.g. to avoid any perception of criticism in public), but I don't know how big a deal this is for verifiers in general, and it would come with the usual cost of added complexity..

Let's put this to one side for now, and I will put out some feelers and try to find out how great a demand there is for it.

**Comment by johnvanbreda** [comment]
Just one note to add then - If you use the Query button you can select the alternative of emailing rather than commenting. In this case the only comment added to the log is "I emailed this record to the recorder for checking". This is no more or less likely to be perceived as criticism as changing the record status to "needing further consideration" I think. A simpler solution might be a change to the wording of this comment.

**Comment by kitenetter** [comment]
I have had no further requests for this functionality to change, so am marking it closed for now.
