### ISSUE TITLE
Deleting an activity

### ISSUE THREAD

**Issue by MAMS-2002** [BiologicalRecordsCentre/iRecord#1000]
I set up an activity but entered wrong details.  I tried to delete it but only afterwards realized that I had clicked the button to leave the activity and not deleted it.  The activity now has no administrator and I cant get rid of it.  This is causing confusion with a similar activity that was set up by my company.  How do I get rid of it?

**Comment by kitenetter** [comment]
Can you let me know the name of the activity you wish to remove?

It's not possible to delete activites, but you can set them to expire, and they are then hidden from public view.

(No problem with contacting us via this route, but general user enquiries are best sent to irecord@ceh.ac.uk)

**Comment by MAMS-2002** [comment]
Ok thank you, wasn’t sure how to contact someone.

The activity I want to remove is:

Borders Forest Trust Wildlife Recording

Recording Wildlife in our Community Woodlands

Its the one that has 3 members.

I would set It to expire but I am no longer the admin as I left the activity mistakenly thinking I was deleting it so now it has no admins

Michelle




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kitenetter** [comment]
No problem, that's all done.
