### ISSUE TITLE
Inconsistent handling of data in attrs_json

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1001]
I'm working on the data for PoMS and it has become apparent that for a very small proportion of records the "attr.json" field in cache_samples_nonfunctional has not been populated, even though there are sample attributes visible via the samples table.

This is worrying in that we may be missing out on valid PoMS results (I use attr.json to export the attributes for analysis).

Is there any reason why a particular sample would not get its attributes included in attr.json?

Is there anything I can do about this in the short-term other than manually transcribing the data?

Example sample_ids with empty attr.json:
11298871
11298990
9430465
9405520

**Comment by johnvanbreda** [comment]
I'm not sure why this has happened, but a quick fix was to run this query which re-queues any samples were the attrs_json was not filled in but probably should have been:
```
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_attrs_sample', 'sample', s.id, 30, 2, now() 
from cache_samples_nonfunctional s
join sample_attribute_values v on v.sample_id=s.id and v.deleted=false
where s.id<12704000 and s.attrs_json is null 
```
The sample ID filter is to avoid queueing today's records which are probably just not yet processed. This fixed the 4 examples given along with ~14K others.

**Comment by kitenetter** [comment]
Thanks John. It would be really good if we can find any ways of avoiding this happening in future. Having downloaded the PoMS data and spent two days (so far) on cleaning it for analysis, it is not a trivial matter to have to download the missing attributes and bring them back in to the cleaned dataset.

I will make a note to check for missing attributes at the start of the cleaning process for next year.

Closing.

**Comment by kitenetter** [comment]
(P.S. the two days of 'cleaning' is not caused by problems in Indicia, it is mostly a result incorporating corrections, edits and additions to the tables that PoMS wishes to use.)

**Comment by johnvanbreda** [comment]
Fixing it will be a lot easier if we can spot the pattern as to when this happens - e.g. are they in batches, or is it related to a certain survey, or use of a certain attribute.

**Comment by kitenetter** [comment]
Have hit a similar problem with cache_occurrences_functional, where attrs_json is empty. These are all PoMS records from survey ID 481, but there is no obvious pattern. It has affected 13 occurrences out of the set of 5,863 that I am working with. Some were entered in winter 2019-20 for records in year 2019, some in late 2020 for records in 2020. Two people were involved in entering the records.

Occurrence IDs:
`(o.id = 18275220 OR o.id = 12633333 OR o.id = 12633332 OR o.id = 12633327 OR o.id = 12633363 OR o.id = 12633364 OR o.id = 12633365 OR o.id = 18275221 OR o.id = 12633331 OR o.id = 12633330 OR o.id = 12633334 OR o.id = 12633328 OR o.id = 12633329)`

**Comment by kitenetter** [comment]
Have now hit a similar problem with occurrences from survey ID 467, and again for just a few occurrences with no obvious pattern.

**Comment by kitenetter** [comment]
This problem has affected all the PoMS surveys, and has consumed a lot of hours to manually edit the missing data. It is no longer urgent, but will be needed for PoMS next winter.

More generally, I'm worried that inconsistencies in attrs_json may be causing problems for other data in iRecord - but I don't know how widely this attribute is used (I only make use of in the custom queries I run in pgAdmin).

**Comment by kitenetter** [comment]
Some more examples of attrs_json being null in table cache_samples_nonfunctional for the PoMS data.

In May from an app count:
sample ID 14449624

Earlier in June from a website count:
sample ID 14693362

Today from app counts:
sample IDs
14701358
14701200
14700527
14700525
14700489

**Comment by kitenetter** [comment]
The counts from today have now become populated, so I assume that I just looked at them before the system had caught up.

The two older ones are still missing.

**Comment by kitenetter** [comment]
This issue continues to arise but as yet with no clear pattern. To be investigated further when resources allow.

**Comment by kitenetter** [comment]
Suspect this is an ongoing problem but haven't seen it recently. Closing for now.
