### ISSUE TITLE
Limit needed on the grid Column widths

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1002]
If the Occurrence Comment field is shown as grid column and any of the records shown contain a large amount of text, the other column header widths become unusably small:
![image](https://user-images.githubusercontent.com/24915271/106754012-5c665c00-6624-11eb-8cbe-aba0cecfd98a.png)

(This example comes from Training Mode.)
I suggest applying a max. width limit to all grid columns to avoid this situation.

**Comment by kitenetter** [comment]
Agree a limit would be helpful. Need to assess scale of work required to implement this.

**Comment by johnvanbreda** [comment]
I think a bugfix was applied in this area a few weeks ago. @DavidHepper are you still seeing this problem?

**Comment by kitenetter** [comment]
Closing
