### ISSUE TITLE
Can't find user account

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1003]
One of the LERCs (NEYEDC) is listed as having a user account on iRecord. I can find their account on iRecord:
https://www.brc.ac.uk/irecord/user/25773

and they were set up as a regional collator. The irecord account gives the warehouse ID as 120918.

However, when I try to set up a new download filter for them, their name does not appear in the "For who?" lookup box.

And if I search for them in the warehouse interface I can't find any account for that user ID, name or email address.

**Comment by johnvanbreda** [comment]
I think this area of code is now due a review. There is a deleted user account 120918, associated with Simon Pickles. Presumably it can be undeleted @kitenetter?
When people edit an existing account to "repurpose" it like this it causes lots of issues.
