### ISSUE TITLE
Workflow for mammal records

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1007]
Requirement to apply the following workflow actions to blur mammal records from Mammal Mapper (website id = 120) and Mammal Atlas (website id = 14).

Can ignore the record type restriction as functionality for that does not yet exist

@johnvanbreda can you provide some documentation for the process for future requirements

Species | Record type | Resolution
-- | -- | --
Brown hare | All | 10km
Otter | All | 2km
Harbour seal | Breeding specifically | 10km
Grey seal | Breeding specifically | 10km
Red fox | All | 2km
Badger | All | 10km
Wild boar | Alive only | 2km
Mountain hare | All | 2km

**Comment by kitenetter** [comment]
Mammal Soc would also also like to blur beaver records, to 2km.

@johnvanbreda regarding documentation, I think I understand how to add rules via the workflow events in the warehouse, but I don't know how to see the settings for the various workflow groups, and how to set up a new workflow group.

**Comment by johnvanbreda** [comment]
@kitenetter A description of the configuration file required to do this is in the workflow module documentation  - see https://indicia-docs.readthedocs.io/en/latest/administrating/warehouse/modules/workflow.html. 

Please let me know if this does not make sense. If you want, feel free to propose the changes you want by sending them to me I can double check that the PHP syntax is correct.

@DavidRoy note that the workflow system doesn't currently have a way of limiting to custom attribute values (alive, dead etc).

**Comment by kitenetter** [comment]
@johnvanbreda I think I can see what we need to add to the configuration, but I don't know if I can, or should, be editing the configuration file myself (i.e. to "create additional groups simply by adding them to the array in the configuration file").

Is this what we need to add?:

`'MAMMALSOCSENSITIVE' => [
    'owner_website_id' => 23,
    'member_website_ids' => [14,120],
  ],`

Is it correct to specify iRecord (website id 23) as the owner_website_id?

I assume that the two Mammal Soc website ids should be listed in the member_website_ids?

**Comment by johnvanbreda** [comment]
@kitenetter that looks fine - would you like me to add it just so I can check the syntax is correct?

I think I'd suggest making the owner website ID either 14 or 120, as although at the moment it doesn't work this way I could imagine there being an expectation that the "owner" is part of the "club", so a future code change along these lines would mean iRecord's mammals changing their sensitivity behaviour.

**Comment by kitenetter** [comment]
Thanks - I'd suggest making id 14 the owner in that case.

Yes please to you adding it (I don't know how to access the configuration file).

**Comment by johnvanbreda** [comment]
I've done that.

**Comment by kitenetter** [comment]
Just had another go at setting up a blur for Brown Hare, and it appears there is still something I am misunderstanding:

![image](https://user-images.githubusercontent.com/16039111/113738433-cb306600-96f6-11eb-89af-eefa82593a37.png)

**Comment by johnvanbreda** [comment]
@kitenetter the Linked taxon box should be a normal species search autocomplete - although a key gets stored internally, when you use the form you can lookup against species names. However I just managed to reproduce a problem with this - if you log into the website using http://warehouse1.indicia.org.uk then the taxon search code uses https, which causes the browser to block the request as it thinks it might be from a different server. If you log in via http then it works.

@BirenRathod should we force the warehouse UI to use https?

**Comment by BirenRathod** [comment]
@johnvanbreda Yes, of course. We should not use http in any case. So no harm to use https it.

**Comment by DavidRoy** [comment]
@kitenetter if you login via https you should be able to complete this task and then close if possible

**Comment by kitenetter** [comment]
I've had problems with the http addres before, so have been using the https links, but I'm still getting the same error message as shown above.

@johnvanbreda in readthedocs it says "Linked taxon - the taxon that will trigger the event", but I'm still uncertain as to what I should type in to the "Linked taxon" box - does it need the TVK, the actual name string, or something else?

**Comment by kitenetter** [comment]
@johnvanbreda I've now found that it does work if I type in the taxon name string, and use the autocomplete lookup. Obvious when you know how! Maybe worth making this explicit in the readthedocs info, but probably it is just me who has strugged with it!

**Comment by kitenetter** [comment]
Workflow events now created for the eight species in the table at the head of this thread, plus for beaver that was subsequently added.

@johnvanbreda I assume this will take effect for records that come into the system from this point on, but is there any additional action required to apply the blurs to existing records (which I think is what Mammal Soc wish to achieve)?

**Comment by johnvanbreda** [comment]
Regarding the taxon name string, I've added extra help text to the form to explain that you are searching by taxon name. I think that's easier than having to cross-refer to documentation.

Yes, we'll have to run a query on the warehouse to change old records. Shall I do this @kitenetter?

**Comment by kitenetter** [comment]
Yes please to running the query.

**Comment by kitenetter** [comment]
@johnvanbreda are you able to run the update query in the next week or so? Mammal Soc are keen to send their records to NBN Atlas but want to ensure the blurring is in place beforehand. The next deadline for Atlas supply is the beginning of May, but if we can't achieve that one I'll let them know we will aim for June.

**Comment by johnvanbreda** [comment]
This should now be done @kitenetter.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 

Unfortunately Mammal Soc have just got in touch to requst three more additions, which I've set up in the warehouse, but these will also need a database update:
Wild cat - 10km
Pine Marten - 2km
Hazel dormouse - 2km

**Comment by johnvanbreda** [comment]
The records for these species now have their sensitivity flag updated.

**Comment by kitenetter** [comment]
@johnvanbreda are these updates still making their way through the system? For most species I'm still only seeing a blur on the newly added records. No problem if it's still working its way through, just wanted to check that it hadn't stalled somewhere. I will delay NBN export until next month.

For Brown Hare, most (all?) records are now marked as sensitive, but many/most are still showing the full grid ref and map location via the Explore pages.

**Comment by johnvanbreda** [comment]
I think I only applied the updates to website 14, not 120. Now applying the updates so it should trickle through this morning.

**Comment by kitenetter** [comment]
@johnvanbreda the ones that I'm seeing on the Explore pages with detailed grid refs are from website 14, e.g. this for Fox:

![image](https://user-images.githubusercontent.com/16039111/116720410-0f501700-a9d4-11eb-9bd2-c2f533ecec72.png)

**Comment by johnvanbreda** [comment]
I've refreshed all sensitive data from website 14 on Elasticsearch, is that OK now @kitenetter?

**Comment by kitenetter** [comment]
@johnvanbreda I'm looking at Explore - all records, and setting a filter for source = Mammal Society (website ID 14). This is what I'm seeing:
- Fox: all records seem to be marked as sensitive, and the latest few records appear to be blurred to tetrad as I would expect, but everything else is still being displayed with a full-precision grid ref
- Badger: : all records seem to be marked as sensitive, and the latest record is blurred to 1okm as I would expect, but everything else is still being displayed with 1km grid ref, which I think is the generic blur applied to other surveys in iRecord?
- Wild Boar: all records seem to be marked as sensitive, but all seem to be displaying with the full grid ref

I'm seeing similar displays on the old Explore page so I assume it isn't an issue with the Elastic dataset.

**Comment by kitenetter** [comment]
The blurring does now seem to be working. Closing.
