### ISSUE TITLE
Reinstate a top-level date filter on the ES download page.

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1008]
One of our verifiers is very unhappy with having to use the "Create a filter" option to set a date filter on their downloads, and has put in a very firm request for date filtering to be directly at the top of the page as it was before.

@burkmarr what are your thoughts - I assume we can do this, but are there any downsides?

**Comment by johnvanbreda** [comment]
The main issue would be without a custom control, the filter could clash with the filter in the filter builder. I guess that's minor though.

**Comment by burkmarr** [comment]
It would be useful to know what actual problem this is creating. I can see that it requires an extra couple of mouse clicks, but does the problem go beyond that?

**Comment by kitenetter** [comment]
This issue seems to have gone away for now at least - closing
