### ISSUE TITLE
Import hangs in mysterious circumstances [file ext casing!]

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1009]
I'm being cautious and testing a one-row Import in Training Mode. It has hung this morning on "Preparing to upload." This also happened on ?Tuesday and is tiresome. I have not tried importing in live mode for some while so can't say whether this would also fail.)
CSV file (changed to .txt to allow attachment here)

[BTO BirdTrack - iR format - 2nd row only.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/5971150/BTO.BirdTrack.-.iR.format.-.2nd.row.only.txt)

**Comment by johnvanbreda** [comment]
@DavidHepper thanks for the example file - I've tried this in training mode logged in as both myself and you and they both imported OK, using Edge. Please can you let me know:
* Which browser you are using.
* Can you recreate the problem then let me know the time so I can check the logs.
* If you have the developer tools installed in your browser, are you able to check the contents of the Network tab to see if there are any errors?

@kitenetter can you reproduce this?

**Comment by kitenetter** [comment]
Just imported into the iRecord support account, in training mode, using Firefox, with no problems. I did not import the attribute "Date Last BTO Edit".

**Comment by DavidHepper** [comment]
Yes, Firefox. 
I also set 'Date Last BTO Edit' to \<not imported\>.
'Location name' col heading has unexpectedly started matching automatically to field 'Locality'. 
I've just checked 'Verify - old' and see what I take to be John's import of that record while masquerading as me (which confused me!) at 14:13.

**Developer Tools results**

**Firefox**
www.brc.ac.uk is excluded from AdBlock Plus.
Errors during the hang just now in FF:
- too many arguments provided for a function call 2 extension_worker.js:268
- Promise rejected while context is inactive: sender.tab is undefined
- 2 content.js:128
- [Exception... "Favicon at "https://theme.zdassets.com/favicon.ico" failed to load: Forbidden."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 253"  data: no] FaviconLoader.jsm:253:22
- SecurityError: Permission denied to access property "windowGlobalChild" on cross-origin object ExtensionUtils.jsm:114
- SecurityError: Permission denied to access property "removeEventListener" on cross-origin object ExtensionCommon.jsm:414
- Promise rejected while context is inactive: sender.tab is undefined
- content.js:128
- Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
- 2 content.js:128
- Failed to fetch https://spocs.getpocket.com/spocs: NetworkError when attempting to fetch resource. DiscoveryStreamFeed.jsm:303
- No response for spocs_endpoint prop DiscoveryStreamFeed.jsm:825
- Failed to fetch https://getpocket.cdn.mozilla.net/v3/firefox/global-recs?version=3&consumer_key=40249-e88c401e1b1f2242d9e441c4&locale_lang=en-GB&region=GB&count=30: NetworkError when attempting to fetch resource. DiscoveryStreamFeed.jsm:303
- No response for feed DiscoveryStreamFeed.jsm:1192
- Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
- content.js:128
- Promise resolved while context is inactive
- content.js:128
- Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
- content.js:128

Exactly the same hang is happening in **Edge**:
Malwarebytes Browser Guard extension shows 'Nothing to block':
![image](https://user-images.githubusercontent.com/24915271/107795595-c7184580-6d50-11eb-8d72-9f5e8f81d9fe.png)
Rapport extension is Disabled.
DevTools > Network tab shows no requests blocked and only one warning on the page refresh at about 16:46:
- jquery.min.js?v=1.8.3:2 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://warehouse1.indicia.org.uk/index.php/services/import/upload?offset=0&limit=50&filepos=0&uploaded_csv=1613148402942.CSV&model=occurrence&allow_commit_to_db=1&callback=jQuery183047993605361537117_1613148503647&_=1613148503964 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

I'm trusting that the above means more to you than to me...  
Happy to help further.

**Comment by DavidHepper** [comment]
I have tried the same test import this morning from another PC at the same location, using Edge. The result is the same hang. This PC has Acronis ATI installed but not MBAM or ABP.

**Comment by DavidHepper** [comment]
"Testing mode" may be a red herring. The CSV also fails to upload in live mode.

**Comment by DavidHepper** [comment]
Tried again from a PC at another location using a different browser (Chrome). Same result.
One warning:
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://warehouse1.indicia.org.uk/index.php/services/import/upload?offset=0&limit=50&filepos=0&uploaded_csv=1613383916214.CSV&model=occurrence&allow_commit_to_db=1&callback=jQuery18308133953735569766_1613383998077&_=1613383998265 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
send @ jquery.min.js?v=1.8.3:2
ajax @ jquery.min.js?v=1.8.3:2
uploadChunk @ import:158
(anonymous) @ import:195
(anonymous) @ import:203
each @ jquery.min.js?v=1.8.3:2
window.onload @ import:202
load (async)
(anonymous) @ import:198
(anonymous) @ import:209

**Comment by johnvanbreda** [comment]
@DavidHepper - thanks for the info. I had a hunch that it was location specific with something blocking the AJAX but your last test disproves that. I'm looking into it now.

**Comment by DavidHepper** [comment]
Removing the superfluous 'Date Last BTO Edit' column from the CSV made no difference.

**Comment by johnvanbreda** [comment]
@DavidHepper I've been completely unable to reproduce this, on several browser/machine combinations. But, in the info you gave there was a clue about the structure of the response which may explain why it was being blocked. I've changed the response from the warehouse accordingly as a temporary measure to test this - can you try again please when you get a chance and let me know what happens?

**Comment by DavidHepper** [comment]
On this now...

**Comment by DavidHepper** [comment]
Could it be relevant that iRecord's domain seems to be part-way through the process of moving from www.brc.ac.uk to brc.ac.uk ? Are these being treated as separate sites by CORB? Just a thought.

**Comment by DavidHepper** [comment]
Just tried at 12:07:30 in Training mode. Same hang.

**Comment by DavidHepper** [comment]
Would it help to screen-share? It must be something I'm doing.

**Comment by BirenRathod** [comment]
It should not be like that. if you just type brc.ac.uk, it will be redirected to www.brc.ac.uk or vice versa.

**Comment by johnvanbreda** [comment]
@DavidHepper I just in the middle of another import myself which will take an hour I think. But, looking at my own import which is working, I can see that the thing I thought I had changed on the server to fix it hasn't actually changed for some reason. So, I'll wait for my import, then will fix the response and double check it, before letting you know so you can try again. Finally, if that doesn't work, we can screen share this afternoon if that's OK?

**Comment by DavidHepper** [comment]
Sure. Back at 2pm.

The site used to keep the www prefix but now most of the public links on Google have the prefix but once you're there it gets dropped after the login. (We found when the BDS public website was hosted at BRC that the two versions of british-dragonflies.org.uk were not redirecting and this caused trouble for Google Analytics, which treated them as different sites.)

**Comment by BirenRathod** [comment]
@DavidHepper BDS was on the old server, so it is not a ideal example. It hasn't got even properly https setup. This is not a same case on BRC now. 

I have checked on different browsers this many times and I have not experienced any problem.

**Comment by johnvanbreda** [comment]
@DavidHepper I've now made the change on the warehouse so please try again when you are ready. If that fails can you send me the details of the "Cross-Origin Read Blocking (CORB) blocked cross-origin response" as you did before please.

**Comment by DavidHepper** [comment]
Same hang at about 14:33. 
**Console shows:** 
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://warehouse1.indicia.org.uk/index.php/services/import/upload?offset=0&limit=50&filepos=0&uploaded_csv=1613399542622.CSV&model=occurrence&allow_commit_to_db=1&callback=jQuery183001668220710700319_1613399581331&_=1613399581538 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
send @ js_wKyFX46tVKJtPKN12qNjRfS4aubW4G2u7LK22vlDiKo.js:2
ajax @ js_wKyFX46tVKJtPKN12qNjRfS4aubW4G2u7LK22vlDiKo.js:2
uploadChunk @ import:248
(anonymous) @ import:285
(anonymous) @ import:293
each @ js_wKyFX46tVKJtPKN12qNjRfS4aubW4G2u7LK22vlDiKo.js:2
window.onload @ import:292
load (async)
(anonymous) @ import:288
(anonymous) @ import:299

**and the right-hand edge shows:** 
js_wKyFX46tVKJtPKN12qNjRfS4aubW4G2u7LK22vlDiKo.js:2

**Comment by johnvanbreda** [comment]
Thanks again - though it's weird as your error says the mime type is text/html, whereas for me it shows as application/javascript.

One more thing to try - on the network tab, there is a button to "Export as HAR file" - can you recreate the error and then use that button to send me the HAR file please @DavidHepper.

**Comment by DavidHepper** [comment]
Here's the file from the event above. Let me know if it needs to be redone.
[iR import hang.har.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/5982592/iR.import.hang.har.txt)

**Comment by johnvanbreda** [comment]
Thanks @DavidHepper. In your HAR file it confirms what you've shown in the messages above - your request to the /import/upload  web service on the warehouse, which is supposed to process the next batch of records, is returning a reponse that is "text/html". That means it is not being allowed by the security policy that blocks requests from one server to another unless the server deliberately accepts the cross-origin request. There are a couple of techniques for doing this - JSONP is the one our warehouse is using here, the other approach is by setting CORS headers in the response. To qualify as a JSONP response, the response has to be marked as application/javascript and the change I made earlier on the warehouse was to force the header to application/javascript. Without this header the request & response are not a valid JSONP transaction so your browser blocks the request. 

I've just installed a fresh copy of Chrome on a clean laptop and debugged the request & response and could confirm that I am getting an application/javascript response. Your HAR file however shows you are getting text/html. So I then repeated my test but set the content type returned by the warehosue to text/html and I could see that it had changed when the response came back - however iRecord successfully imported the record!

The only thing I can suggest is some caching getting in the way. If you try again then, on the mappings page, go to the Network tab of your developer tools and try ticking "disable cache" before proceeding. Sorry to keep asking you to repeat the test but I'm a bit flummoxed! Or try clearing your browser cache completely.

**Comment by DavidHepper** [comment]
Nightmare. It'll have to be later. Thanks for looking.

**Comment by DavidHepper** [comment]
- W10 (fully updated)
- Edge (Chromium-based; patched)
- Browser cache fully cleared (everything except bookmarks)
- 2021-02-15 22:16:00 ish
- One row plus column headers. (Extra .txt extension only to allow upload to GitHub):
[BTO BirdTrack - iR format - 2nd row only.CSV.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/5984363/BTO.BirdTrack.-.iR.format.-.2nd.row.only.CSV.txt)

- Training mode.
- Mappings page does not appear, now that the 'Date Last BTO Edit' column has been deleted.
- 'Disable cache' ticked in Network.
- Dataset = 'DRN dragonfly imports'.
- Species list = 'UK Master List'
- Sample method = 'Defined in file' (although it isn't)
- Hangs as before:
[www.brc.ac.uk.har.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/5984389/www.brc.ac.uk.har.txt)

**Comment by johnvanbreda** [comment]
@DavidHepper I'm not sure what has changed but this morning I've managed to reproduce it. That should make it much easier to diagnose - I'll report back when I've worked out what's going on.

**Comment by johnvanbreda** [comment]
Got it! 
* There were recent code changes to add support for Excel file format imports.
* These changes introduced a bug where if the file extension was in uppercase, an error was generated.
* The error response didn't go through the correct path through the code, so the headers required to prevent the CORBS blocking from occurring didn't get added to the response.
* When I downloaded your original test file, it had a *.txt extension so I just renamed it to *.csv, hence it was OK.
* When I downloaded the latest test file, it had a *.CSV.txt extension so I removed the .txt and ended up with uppercase, hence it started failing.

Thanks for your patience @DavidHepper - hopefully it's all sorted now. Once you've had a chance to test it please close this issue, assuming it works of course.

**Comment by DavidHepper** [comment]
Importing happily now...
It had to be something silly. Fancy Excel causing anyone any trouble? LOWER( ), Lcase( ) and strtolower( ) make life so much easier! And thank you for your persistence.

**Comment by DavidHepper** [comment]
I probably shouldn't have closed it. Essential to make the file handling case-insensitive.

**Comment by johnvanbreda** [comment]
Sorry @DavidHepper - I didn't make myself clear - I had made the file handling case-insensitive and have been importing files with CSV extensions. If you get it to fail again though please let me know.

**Comment by DavidHepper** [comment]
Yes, thanks. Retested OK with upper case .CSV
