### ISSUE TITLE
Activity invitations not working?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#101]
The Bringsty Common group report an error message when trying to invite someone to join the activity:

> The emails could not be sent due to a server configuration issue. Please contact the site admin. The list below gives the emails and the links you need to send to each invitee which they need to click on in order to join the group. 
> Send link http://www.brc.ac.uk/irecord/activities/accept-invite?token=58185bf0e185b0 to ...

I haven't tried to replicate this, let me know if you want me to do so.

**Comment by johnvanbreda** [comment]
This applies to all activity invites. The response from SMTP mail is in the Drupal log (see https://www.drupal.org/node/1231284). One for @BirenRathod to look at I think?

**Comment by kitenetter** [comment]
@BirenRathod This issue has just been reported by another user, do we have a fix for it?

**Comment by BirenRathod** [comment]
Is noreply@brc.ac.uk a valid email address? This is the email address used by Drupal. so if this is not a valid email, there may be possibility, that it doesn't send email.

**Comment by johnvanbreda** [comment]
Its not valid, but I'm pretty sure it doesn't need to be and it never has been.

**Comment by BirenRathod** [comment]
what does happen when new user register with iRecord website? who does get the email? If Drupal sends the email at the time of the registration of new user that means there is not problem in SMTP setting. In fact I just checked the forgot password for my accounts and I got email from noreply@brc.ac.uk, that means nothing wrong with SMTP settings or email address.

**Comment by johnvanbreda** [comment]
Presumably Drupal has slightly different code when it sends a mail than Indicia. The code is in client_helpers/prebuilt_forms/group_send_invites.php. I am pretty sure this used to work, at least until the PHP 7 upgrade.
The mail() function just returns false but I have found this error in the Drupal log:
```
Warning: mail(): SMTP server response: 553 5.0.0 " in iform_group_send_invites::sendInvites() (line 200 of D:\web sites\irecord\sites\all\modules\iform\client_helpers\prebuilt_forms\group_send_invites.php).
```
I have tested a few things and found that if we don't set "Reply-to" in the header then this email send works. The error implies that non-local mail cannot be relayed so I think that the SMPT settings are preventing the setting of Reply-to.

**Comment by BirenRathod** [comment]
I found from this link https://technet.microsoft.com/en-us/library/dd277329.aspx, that if you set "Reply-to", that means relaying will not work for non registered email address. Seems like changes have been made to our SMTP server which has got nothing to do with PHP.

**Comment by BirenRathod** [comment]
Is it possible to test relaying with email address like brc@ceh.ac.uk?

**Comment by johnvanbreda** [comment]
brc@ceh.ac.uk didn't work. However I found some similar code elsewhere for sending the verification query emails and used the exact same formatting etc in the group invites and it works, so this now fixed.
There must have been a change to SMTP that made it more strict and something minor in the email format was causing an error.
