### ISSUE TITLE
Records not being checked or indexed?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1011]
I noticed that on my soldieflies verification page, records added up to 11 Feb are being checked and allocated to vice-counties, but records added from 12 Feb onwards are not.

Is the system just running slowly or has something gone wrong?

A quick check of the explore page seems to show that it is a general issue for all records since sometime on 12 Feb.

**Comment by johnvanbreda** [comment]
The notification emails system seems to be running out of PHP memory. I've disabled it temporarily to allow other tasks to complete, then will debug why later. Possibly some operation has caused a particularly large email to be generated.

**Comment by johnvanbreda** [comment]
There was a batch of 831000 imported UKBMS records that were linked to @DavidRoy's user account and had been recently verified. It was trying to send a digest email to notify him of them all.
David - I hope it's OK with you but I marked all your notifications as acknowledged in order to get the notification system going again. 
Martin - possibly worth considering some work on this to act more intelligently when thousands of records are verified. E.g. just send a link to a report?

**Comment by DavidRoy** [comment]
@johnvanbreda I have more UKBMS data to load, will email you separately about the best way to do this

**Comment by kitenetter** [comment]
Don't know if this is related, but I've just had an email from a verifier and recorder where a record has been notified as having been edited (and therefore needs re-verifying), but no edit appears to have happened for at least six months.

Might some old notifications have bcome unblocked or is this just a coincidence?

**Comment by kitenetter** [comment]
Ignore the previous comment, it turned out to be the result of an edit the user had made to another species in a sample list.

**Comment by DavidHepper** [comment]
It is particularly worrying to the importer when nothing appears in Verify after 30 minutes. Verifiers with geographical restrictions on what they can see (e.g. to one VC) cannot see new, unprocessed records until they have been matched to a VC, so they don't know whether their own import or the background processing went wrong.
Is there a watchdog function that could notify admins when the background check or the allocation to VC process has hung or crashed? The last failure (above) wasn't spotted for two days.
