### ISSUE TITLE
Query - Can we select records by Photo Licence?

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#1013]
Is it possible to select records based on the Photo Licence for the record?

I would like to develop some training materials for my recording schemes / iRecord contributors and iRecord is probably the best place to find "good, bad and ugly" examples for training purposes.  Can we select records with photos where these are "free to use" so we can choose some for this purpose?

Thanks.

**Comment by kitenetter** [comment]
@MNSmith as far as I'm aware there isn't a way of filtering for these within iRecord itself. We might be able to send you a list of links for your projects - can you email me with exactly which groups or species you need.

**Comment by johnvanbreda** [comment]
@kitenetter - although the photo licence isn't supported by the standard filter builder tool, it is a field in the Elasticsearch data. So we could make a version of the Explore page or some other report output which has a photo licence selector.

**Comment by MNSmith** [comment]
I'm mostly after Aculeate Hymenoptera / Asian Hornets and possibly some Tachinid flies.  Ideally, if there were a page available similar to the standard grid where records could be selected by the usual means plus a Photo-licence field as suggested by John that would be ideal for my needs.

**Bonus feature request**  If there were such a page, I would not need to see the standard map of the records as is usual on the Verification grid.  Could we replace the Map window with a Photo window of the same size, much easier to evalutate phoos that way rather than clicking through all the thumbnails?

**Comment by MNSmith** [comment]
Any progress with this please?

**Comment by kitenetter** [comment]
Licence filters now available. Closing.
