### ISSUE TITLE
Blank notifications of Records to Verify - no records listed - for Training Mode records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1014]
iRecord appears to be trying to issue Notifications of records to verify whenever I add Training Mode records. It then lists nothing in the email body.

_Originally posted by @DavidHepper in https://github.com/BiologicalRecordsCentre/iRecord/issues/446#issuecomment-439194534_

**Comment by kitenetter** [comment]
@DavidHepper we've made some changes to the notification emails since you posted this issue. Are you still seeing notifications from training records?

**Comment by kitenetter** [comment]
Being addressed under #108 - closing this one.
