### ISSUE TITLE
Question about time taken to log on

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1015]
A verifier says:

> We have a 40mb connection service but have a problem with iRecord logon in that it takes an inordinate amount of time to happen. Today sunday 14/02 it took only 60 seconds, but normally takes several minutes - we even start logon and go and do something else while it happens!
> Is it because the system scans through the whole database to pick out recent records to display on the opening logon page? Surely this is completely un-necessary.
> In the past, it has taken masses of time to get into verification but today was acceptably quick.

Is there anything I can suggest that might speed up their log-in process, e.g. is clearing cookies likely to have any impact? (But maybe they are clearing cookies, otherwise they wouldn't need to log on afresh every time?)

**Comment by DavidHepper** [comment]
We're not seeing login times this slow but I've raised before that if verifiers have a slow login followed by other problems they are likely to give up for a few days > https://github.com/BiologicalRecordsCentre/iRecord/issues/506#issuecomment-469251439

**Comment by BirenRathod** [comment]
@kitenetter Clearing cookie will certainly help to get new updates made in the code. In general if people access site and particularly verification page on wi-fi will take longer. In this case, I can suggest they should connect router via ethernet cable which works faster than wi-fi. 
The reason I mentioned to use ethernet cable is because most of the time wi-fi has compromised with other connection, so 40mb certainly not enough to use for verification page. 
I just did login using my user ID & password and it takes about 4 seconds to load home page and 13 seconds to load verify page.

**Comment by johnvanbreda** [comment]
Login is fast when the cache has already loaded the data to show on the home page. It can be slow if the data needs to be rebuilt and the server is at a busy time.
Switching all home page queries to Elasticsearch is the way to solve this.

**Comment by johnvanbreda** [comment]
@BirenRathod I managed to reproduce this - the report that failed was "projects/irecord/occurrences/filterable_explore_list_for_home.xml", which is used to populate the list of records and the map. 
There is code in the Elasticsearch_event_reports extension class now that could be used to generate suitable outputs for the home page - currently with an activity filter, but this could be replaced by a filter based on the user vice county and taxon group preferences.

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda. 
@kitenetter & @DavidHepper see if that make any difference.

**Comment by johnvanbreda** [comment]
@BirenRathod just so you are aware - I didn't actually make any changes, I just suggested a way forward.

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda for the clarification.

**Comment by kitenetter** [comment]
It looks like we should update the home page to use ES queries.
@johnvanbreda how big a job is this?

**Comment by johnvanbreda** [comment]
There has already been work done on this ready for Drupal 9 - though the layout is a bit different. See http://test.brc.ac.uk/irecord/.

**Comment by DavidHepper** [comment]
Logging on has been reliably quick for me recently and I've received no complaints from others. I do have an unusually fast internet connection but doubt this is the reason. Maybe Drupal 9 really helped. Unless others still have problems I suggest this ticket may be closed.
