### ISSUE TITLE
Imported records can generate a Sample containing several Species

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1016]
I confess to being unaware that setting the 'Recorded all species?' flag on rows of a spreadsheet imported with form 'DRN dragonfly imports' causes separate Occurrence rows to be bundled into a Sample. I must document this useful feature.

**Questions:** 
- I am guessing that the restrictions on the imported values are for consistent Recorder Name, Date, Location, Map ref. and 'Recorded all species?' flag but are any other requirements?
- Do the records have to be contiguous rows of the spreadsheet for this to happen? 

**Example:** 
Imported records 18385637 & 18385638 are of two species but (to my surprise) within the same Sample.

**Comment by johnvanbreda** [comment]
@DavidHepper if they are specified, then the vice county code and survey reference code must also match as they are attributes of the sample. Yes, the rows need to be contiguous for this to work.

**Comment by DavidHepper** [comment]
Neat. Thanks.
