### ISSUE TITLE
Verification page map not always filtering for the current species correctly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1018]
On my verification page I have the map set to show records of the currently selected species. For robberfly Laphria flava it is showing me an incorrect distribution:

![image](https://user-images.githubusercontent.com/16039111/108608901-046c7b00-73c2-11eb-81f4-a7da387ff3f0.png)

If I filter for the same species on Eplore - All records, the map displays correctly:

![image](https://user-images.githubusercontent.com/16039111/108608919-19490e80-73c2-11eb-8ca5-3b2e45e35881.png)

**Comment by johnvanbreda** [comment]
If I masquerade as you and go to Explore all records, set the quality filter to all records, search for the species using the grid filter, then click on a row, the species map looks like the one on your Explore All Records page for both verification and the Explore All Records page. Can you explain exactly how to generate the map above via your verification page please @kitenetter.

**Comment by kitenetter** [comment]
I can't reproduce the issue at the moment. Maybe it arose after I'd been verifying for an extended period of time. What I did notice at the time was that the correct dots for Laphria flava were shown on the map for a very short instance, and then it immediately flipped to an incorrect set of dots.

Closing for now, will re-open and document if it happens again.
