### ISSUE TITLE
Make the import errors link more noticeable

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1023]
When an import partially succeeds the banner is unmistakeable but the link to collect the errors file is too subtle (the same font as the rest of the paragraph and not underlined) and some of my verifiers are missing it. Once you navigate away from the page the link is lost and cannot be recovered. IMO this is important, especially if a few rows of a large import failed. Please make the link more obvious, preferably a button.
![image](https://user-images.githubusercontent.com/24915271/109421587-e9a49280-79cf-11eb-9615-c0766dedee47.png)

**Comment by kitenetter** [comment]
Agreed.
