### ISSUE TITLE
The 'Import Errors' sheet isn't documented

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1024]
The 'Import Errors' sheet is undocumented in the current version (3.2) of 'Importing records to iRecord from a spreadsheet' but could usefully be explained in section '2. Doing a test import'.

**Comment by DavidHepper** [comment]
And the text of the link to the import errors sheet is very small and not underlined, hence easily overlooked. The link can't be recovered once I've navigated elsewhere so this really matters.

**Comment by kitenetter** [comment]
Agreed.

@kitenetter to update documentation

@johnvanbreda to make the import errors link more obvious, or to convert it to an action button

**Comment by johnvanbreda** [comment]
Button done in develop branch of code.
