### ISSUE TITLE
Verification interface

### ISSUE THREAD

**Issue by davidmorris1989** [BiologicalRecordsCentre/iRecord#1026]
I like the new verification user interface but it is very congested on laptop screens at 100% with the text above the verification area, squashed column headings, filters and the map and record details (see screenshot attached). Would you be able to improve the layout? I would find it useful if the map and record details were in a collapsible side panel and if the photos appeared in the panel instead of over the verification area. Obviously, I can zoom out but it would be good to have a layout that worked at 100%.

The full screen mode is useful but then when I click on the photo thumbnails the enlarged image does not appear, which I assume is a bug. And of course the record details are not visible in full screen.

![image](https://user-images.githubusercontent.com/71990684/110122713-df134000-7db7-11eb-8032-c6be9bca0b25.png)

**Comment by DavidRoy** [comment]
@davidmorris1989 thanks for feedback on the layout.  One quick comment in reply to 'and if the photos appeared in the panel instead of over the verification area'.  If you click on the spanner icon, you can choose which columns to display in the data grid - you can remove display of media for example.  Or have I misunderstood what you are asking?

**Comment by DavidHepper** [comment]
I generally agree. See also **Responsive displays** #37.
But I don't think iRecord should ever be used on a display smaller than 1680 x 1050. If either dimension of your laptop display is smaller than this I'd insist on connecting an external display such as the BenQ BL2420PT (£200) which, having 1,440 pixels vertically, does not require use of the outer vertical scroll bar in Verify, only the inner one for the grid.

**Comment by johnvanbreda** [comment]
@davidmorris1989 I've made a tweak to the column widths - is that any better?

**Comment by davidmorris1989** [comment]
Aha! I did not realise I could change the columns displayed. Should have read the documentation.

It would be good though if the photos appeared at the side - clicking to enlarge a photo, clicking off it and then verifying it is a bit awkward. If I could just click the record and the photo appeared at the side large enough that I could see it then it would be easier to verify.

The enlarged photos don't appear at all in full screen mode.

**Comment by johnvanbreda** [comment]
@davidmorris1989 I can't promise when it will be ready but I am working on updates to the verification tool which will include ensuring that you can do the main tasks using the keyboard. That will include opening and closing the image and verifying the record - though I think the image will still be in an overlay. I'll double check it all works from the fullscreen mode.

**Comment by kitenetter** [comment]
I think we can close this issue, since work on the photo display is already in hand.
