### ISSUE TITLE
Recorder names to follow "forename surname" wherever possible

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1027]
It is desirable to have the iRecord website and the iRecord app to handle recoder names in as consistent a way as possible.

Currently:
- for logged-in users, the iRecord website pre-populates the recorder name with `surname, forename`
- the iRecord app pre-populates the recorder name with `forename surname`

Following discussions with @DavidRoy and @sacrevert we have concluded that we should standardise wherever possible on `forename surname` (in other words the app remains as it is, and the website needs to change).

I'm not sure how many changes are required to implement this, but they include:
- recording forms should default to `forename surname` (not sure if this is controlled on each form or if here is an overall setting that can be used to change multiple forms)
- notifications should present names as `forename surname` if they are not already doing so

At a later stage we may need to review:
- whether we can provide users (or verifiers) with tools for making bulk changes to existing records in order to bring thenames into `forename surname` format
- how to deal with name changes and the mismatches we sometimes have between what is in the Drupal accounts and what is in the warehouse
- how to deal with middle initials (which still seem to be handled erratically but this may be linked to the previous point)

**Comment by DavidHepper** [comment]
Not just Recorder but also Determiner and Verifier names.

**Comment by kitenetter** [comment]
As far as I can tell, app records are now being displayed with the recorder name formatted as "surname, forename", so the issue that initially prompted this thread no longer applies.

I still think there is an argument to be made for changing both app and website to "forename surname", but I'm not proposing to revisit that at the moment, and am happy that things are consistent. Closing this issue.
