### ISSUE TITLE
Group activity without an administrator

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#103]
@johnvanbreda 
I've not checked all groups/activities, but a specific issue has been reported.  For the 'Inner Forth' activity (group_id = 105), a query on the warehouse shows that the group has no administrator setup.  Can you assign administrator = Y to Scott Shanks (user_id = 7796) so he can enable App submission and summary reports.

I think I can see how to do this in the database but would rather not update live!

**Comment by johnvanbreda** [comment]
I've done this as follows:
```
-- first check the output of these 2 queries to be certain the IDs are correct:
select * from list_users where id=7796;
select * from list_groups where id=105;

-- update Scott to admin
update groups_users set administrator=true where group_id=105 and user_id=7796;
```
