### ISSUE TITLE
Unnecessary "Under 16" tick box on registration form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1030]
The registration form asks you to confirm that you are over 13 (which is needed) and also asks you to say if you are under 16 (which is not needed).

Remove the "Under 16" tick box.

https://www.brc.ac.uk/irecord/user/register

**Comment by johnvanbreda** [comment]
I've fixed this by removing the field and the associated (hidden) dob field. I also made the over 13 field required so you are forced to tick it.

On the registration page, the question about vague dates seems a bit too much at this stage - the user won't understand this until they have some experience of the system.
