### ISSUE TITLE
ElasticSearch timeout

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1031]
I'm seeing an error connecting to **Verify**:
Page load failed: An error occurred whilst connecting to Elasticsearch. "Failed to connect to 192.171.199.233 port 9200: Timed out"
whereas **Verify - old** is still working.

**Comment by burkmarr** [comment]
Hi David. Apologies - Elasticsearch service was down. I have restarted it now.
