### ISSUE TITLE
ES error message when using Microsoft Edge?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1032]
As far as I'm aware this has only been reported by one person sp far. They were getting an "Elasticsearch query failed" message from the Explore pages when using Edge. They've now switch to Chrome and it's working fine for them there.

Flagging this up just in case there is a general issue with Edge.

**Comment by johnvanbreda** [comment]
I don't think this is a general Edge problem as I'm using Edge. The older versions of Edge are significantly different though as now Chromium based so it might have been an old version.

**Comment by kitenetter** [comment]
Thanks for the info, and this doesn't seem to be a widespread problem. Closing.
