### ISSUE TITLE
Some imported records have missed Auto-Checks

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1034]
It appears that a block or scattering of records from my large import on 15/03 have been correctly assigned to VC but are still showing the cogwheel icon indicating that the automated checks have not yet been carried out.
They are causing puzzlement among my verifiers, perhaps because the cogwheel isn't defined in the (very useful) help document v5.1.
I've not found anything odd about these records but haven't looked in detail.
Examples:
![image](https://user-images.githubusercontent.com/24915271/112224450-32dcb080-8c23-11eb-8831-b4f6fb5c4176.png)

**Comment by kitenetter** [comment]
Thanks for highlighting that the 'cog' icon isn't in the guidance documentation, I will get that added.

My understanding is that the time taken for rules to be applied to incoming records does depend to some extent on what else is happening in the system, and that application the rules can be slowed down if there are other operations in progress.

@johnvanbreda two questions:
- Is it possible to give the rule application operations higher priority in the workflows?
- Am I correct in thinking that there is no downside to verifiers continuing to verify records in advance of the rules being applied? (I've never noticed this causing a problem)

**Comment by DavidHepper** [comment]
@kitenetter I agree that verifiers are able to accept or reject without waiting for the cogwheel to go. The surprise to me is that the rules and the assignment to VC are separate processes. They've always seemed to occur at the same time previously.

**Comment by johnvanbreda** [comment]
@kitenetter - 
* yes it's certainly a possibility that we could change the priorities of various tasks. 
* correct, the rule flags are just a tool to aid the verifier, but without them verification can proceed as normal.

@DavidHepper -
The rule application and the VS assignment are indeed 2 separate processes, but having said that they are triggered by the same "master" process. If everything has caught up, then they will run within a few minutes of each other on the same batch of records. However, when things are delayed, e.g. after a large import, the rate at which they catch up may differ so they will be out of step at that point.

**Comment by kitenetter** [comment]
I think the only action we can take forward is for me to update the verifers' guidance.
