### ISSUE TITLE
change of common name in UKSI - Mountain Ringlet

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1035]
Change common name to 'Mountain Ringlet' for tttl.id = 134500
id | preferred | taxon_rank | taxon_rank_sort_order | taxon_list_id | taxon | preferred_taxon | default_common_name
-- | -- | -- | -- | -- | -- | -- | --
134500 | TRUE | Species | 300 | 15 | Erebia epiphron | Erebia epiphron | Small Mountain Ringlet
-- | -- | -- | -- | -- | -- | -- | --

**Comment by DavidRoy** [comment]
Since we use Mountain Ringlet within the iRecord butterflies app, I confirm that we would like this changed within UKSI to then trigger an update in Indicia.
@kitenetter can you liaise with Chris Raper for this change please

**Comment by kitenetter** [comment]
UKSI already has "Mountain Ringlet" as the accepted vernacular:
![image](https://user-images.githubusercontent.com/16039111/146397176-7404b49a-90b6-44cd-89e9-e317a0030d9b.png)
![image](https://user-images.githubusercontent.com/16039111/146397233-6d017aff-f9fd-403f-b714-afa07ee4c043.png)

So I think this is an issue with the way we import or handle vernaculars within Indicia

**Comment by johnvanbreda** [comment]
@kitenetter looking at the data imported from Access last April, I think that these names have been swapped and Small Mountain Ringlet was the accepted name until recently. Taxon_version_status=R is the recommended (accepted) name I think.

![image](https://user-images.githubusercontent.com/2392594/146404483-67eae8f5-669d-4e69-91d8-69fca525c685.png)

**Comment by kitenetter** [comment]
This appears to be working correctly following the UKSI update. If you enter Erebia epiphron it is linked to "Mountain Ringlet", and "Small Mountain Ringlet" is available for data entry but is not being displayed as the main name.

This hasn't yet fed through to the ES view, so will double-check next week before closing.
