### ISSUE TITLE
Exclude all imported records from Recorder Experience stats?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1036]
Since the Recorder name in imported records is usually not the CMS User doing the import, the Recorder Experience stats for imported records are misleading and causing consternation for my verifiers. My stats are quite wacky as a result!
May I suggest that _all_ imported records should be excluded from the Recorder Experience stats? It would also reduce the load on the system slightly.
(In theory, it would be possible to match the Recorder name against the CMS User and include only the matches but due to name inconsistencies this would not be fully reliable.)

**Comment by kitenetter** [comment]
I don't know if it is true that "the Recorder name in imported records is usually not the CMS User doing the import", many individual recorders do import their own records from spreadsheets. So I can't see a solution to this that will please everyone.

A workaround for county recorders and others who need to import records from multiple recorders is to set up a second iRecord account, separate from their personal account, and use that second account to do such imports.
