### ISSUE TITLE
Problems getting automatic grid reference from map

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/iRecord#1037]
When I click on the map to get the grid reference for my records nothing happens and I have to type in my gridreference manually. This issue also occurred when entering the data through the irecord app

**Comment by kitenetter** [comment]
Not aware of this being a general problem. Which web browser are you using @marcbotham ?

**Comment by marcbotham** [comment]
I checked again this morning and still doing same thing. I took a video if helpful though it’s exactly as I described – when I click in the gridreference entry box and then go to map, I click on map and nothing appears in gridreference box no matter how many times I click. Have to enter manually as I said. Very odd

**Comment by kitenetter** [comment]
I can't reproduce this @marcbotham - when I use Chrome it is working as expected. Might be worth clearing cookies in your browser?

@johnvanbreda do you know of any reason why clicking on the map would not produce a grid ref?

**Comment by johnvanbreda** [comment]
@marcbotham did this happen at home as well last night? I have a recollection of some similar problems occurring on the RIS-Ky website but it turned out to be something to do with the network blocking messages rather than a problem with the website.

**Comment by marcbotham** [comment]
Hi,

I have deleted cookies, refreshed, restarted and tried umpteen times but this issue still persists. I have also tried through network and outside of network and still it persists. I don’t know what’s going on but it is incredibly frustrating

BW, Marc

**Comment by johnvanbreda** [comment]
@marcbotham please can you send me the video you took?

**Comment by kitenetter** [comment]
@marcbotham is this still causing problems?
