### ISSUE TITLE
Create a filter - Sources pane UI improvements

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#1043]
As usage of the system has grown, the increasing number of websites, survey datasets and input forms available for selection under the Create a Filter -> Source panel means the current user interface is quite difficult to use. Addition of a search option would help.

**Comment by kitenetter** [comment]
Agreed, and having the lists sorted alphabetically would also help, along with rationalising the survey names if we can (e.g. whether or not to include "iRecord" as part of the name - it appears twice for some).

**Comment by kitenetter** [comment]
Search option now available. Closing.
