### ISSUE TITLE
Map symbol obscures record location

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1045]
Reported by a butterfly verifier.  The solid blue map symbol obscures the point location.

<img width="934" alt="iRecord bug" src="https://user-images.githubusercontent.com/2699478/114152769-900c7d80-9916-11eb-8e3e-e4a8f413deb7.png">

**Comment by DavidHepper** [comment]
The opacity of these circles is too high. See also related issue #421.

**Comment by johnvanbreda** [comment]
I've changed the map to show full precision data as you zoom in, plus tweaked the opacity. Hopefully OK now - please close if acceptable @DavidHepper @DavidRoy

**Comment by kitenetter** [comment]
I'm assuming that this has been found acceptable - closing.
