### ISSUE TITLE
Update code for compatibility with PHP8

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#1047]
_PHP 7.3_ is approaching end of life in Dec 21. 
The most recent release is _PHP 8.0_. 
There is also _PHP 7.4_ with EOL in Nov 22.

To future-proof iRecord, we must ensure our code is compatible with _PHP 8.0_.
This affects various components we have developed for which separate issues will be raised.

_Drupal 7.79_, released 7/4/2021, "is the first where D7 core's test suite passes tests in PHP 8.0. However, there may be remaining problems with PHP 8 in core, and it's very likely that there are problems in contrib."
_Drupal 8_, which reaches end of life before _Drupal 7_ (Nov 21 and Nov 22 respectively), does not support _PHP 8.0_
_Drupal 9.1_ and upwards supports _PHP 8.0_

A move to _PHP 8.0_ therefore implies a move to _Drupal 9_.
There is already an issue for this, https://github.com/BiologicalRecordsCentre/iRecord/issues/980 

In order not to force other users of Indicia to upgrade to _Drupal 9_, while adding compatibility with _PHP 8.0_, backwards compatibility with _PHP 7.3_ and _PHP 7.4_ should be maintained.

**Comment by JimBacon** [comment]
There is a tool for running checks on PHP compatibility which may be helpful, https://github.com/PHPCompatibility/PHPCompatibility

To test it out I performed the following steps on my Linux development system (which already had PHP installed) as follows.

1. Installed Composer
    1. `php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"`
    2. `HASH=756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3`
    2. `php -r "if (hash_file('sha384', 'composer-setup.php') === '$HASH''') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"`
    3. `sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer`
1. Installed the xmlwriter extension for PHP as required by CodeSniffer. `sudo apt-get install php-xml`
2. Installed PHP CodeSniffer 3.6.0 globally. `composer global require "squizlabs/php_codesniffer=*"`
3. Installed PHP Compatibility 9.3.5 globally. `composer global require "phpcompatibility/php-compatibility=*"`
4. Added `~/.config/composer/vendor/bin` to PATH in `~/.bashrc` so the CodeSniffer executable can be found.
5. Told CodeSniffer about PHP Compatability `phpcs --config-set installed_paths ~/.config/composer/vendor/phpcompatibility/php-compatibility`
6. Confirmed that PHP Compatibility was present in CodeSniffer using `phpcs -i`
7. Tested the current directory for compatibility with PHP 7.3 and up with `phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 7.3-`

**Comment by BirenRathod** [comment]
https://github.com/Indicia-Team/warehouse/issues/431
