### ISSUE TITLE
Species name request

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#105]
Apparently, the marine species "Laminaria ochroleuca" was accidently tagged as 'Redundant' in the UKSI during an 'exotic' species removal process. However, it has now been un-tagged. MBA have asked if we can make it available again on iRecord.

TVK: NHMSYS0021058678

NBN link: https://data.nbn.org.uk/Taxa/NHMSYS0021058678

**Comment by johnvanbreda** [comment]
I've updated the underlying database and it should reappear in the search index tables in the next 15 minutes or so.

**Comment by johnvanbreda** [comment]
I've updated the underlying database and it should reappear in the search index tables in the next 15 minutes or so.

**Comment by johnvanbreda** [comment]
I've updated the underlying database and it should reappear in the search index tables in the next 15 minutes or so.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda
