### ISSUE TITLE
Binomial name unavailable

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1050]
For Orange-tip butterfly, if I record it under the English name, it appears to be treated as the binomial Anthocharis cardamines. However, I am unable to enter Anthocharis cardamines as a scientific name - the only options offered are trinomial subspecies names.

Can we resurrect the binomial as the first choice when entering this species?

**Comment by kitenetter** [comment]
Seems to have been fixed via #1061 - closing.

**Comment by johnvanbreda** [comment]
Yes, this would have been the same issue.

**Comment by kitenetter** [comment]
This continues to cause problems, bumping it up and hoping that it is an easy fix!

**Comment by johnvanbreda** [comment]
I've ran the following query which should regenerate the missing searchterm entries:
```sql

update taxa_taxon_lists set updated_on=now(), updated_by_id=3 where id in (
select cttl.id from cache_taxa_taxon_lists cttl
left join cache_taxon_searchterms cts on cts.taxa_taxon_list_id=cttl.id
where cts.id is null
and cttl.allow_data_entry = true
	)
```

**Comment by johnvanbreda** [comment]
Anthocharis cardamines is now available again.
