### ISSUE TITLE
Renaming a survey?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1051]
The website "York University" has a survey called "All records". 

![image](https://user-images.githubusercontent.com/16039111/116421541-d62e7000-a836-11eb-898f-9403357c05af.png)

This name has led at least one person to assume that they are required to select "All records" from the "Download single survey" dropdown on the Download records page.

Can I edit the survey name to "York University records" or could that cause problems elsewhere?

Do we know who the contact is for this website?

**Comment by johnvanbreda** [comment]
If you update this survey's title using the warehouse UI, it will trigger an update of all contained samples in the reporting tables. As this might be slow, I suggest I do this via the backend. Shall I proceed @kitenetter? Other than the change of the label in reports I can't foresee any other consequences.

**Comment by kitenetter** [comment]
Yes please @johnvanbreda as long as it isn't a big job for you.

@kitenetter to edit the label on the "Download records" page to make it clearer what the survey choice does.

**Comment by johnvanbreda** [comment]
@kitenetter Done

**Comment by kitenetter** [comment]
Thanks - closing.
