### ISSUE TITLE
Develop new mechanism for handling exports to NBN Atlas

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1052]
Our current export routines for NBN Atlas work well for smaller datasets, but larger ones fail, see #477 

Today there are 17 large files that have failed and that will require manual export via pgAdmin. That is do-able but time-consuming.

This is an issue that we are all aware of but it would be good to assess the size of the task and prioritise it when we can.

**Comment by johnvanbreda** [comment]
Current status of this was described in an email on 06/01/21:

> Since I have a PO from last year that covers publishing RIS-Ky data to the IPT which has some time left on it, I’ve had a go at getting some automated extraction from Elasticsearch. It struck me that the same tool could be used to generate both NBN Atlas extraction files as well as update the files sitting on our IPT, since they are nearly identical apart from the need to zip one and add the NBN specific gridReference field.
> 
> I’ve had some success with this and I’ve copied the script to the Drupal live server (see email for exact location) so you can compare it with the current extracts. In the test subfolder there is a *.bat file which you can run to kick this off. If you open it in a text editor you will see it just runs the PHP executable with a parameter that is the filename of a configuration file. You could add extra lines to this file to add extra exports to run in the batch.
> 
> The configuration file format is described in the readme file in the ipt-dev folder (alongside the test folder). In the test folder I’ve created an example config which matches the Sawfly extraction. In practice when you make new extractions, apart from tweaking the output file name, you’ll need a new subfolder to hole the eml and metadata files to include in the extraction, plus will want a different filter on the higher taxon IDs in the config. Of course, because it is Elasticsearch and because it builds the output up in small chunks, there should be no timeouts or other resource limits when exporting large datasets.
> 
> Anyway, I thought I’d show it to you in case you wanted to have a play or feedback any thoughts. The same tool should be able to run on the IPT to periodically update the CSV files held for each dataset using a Windows scheduled task.
> 
> Of course once this code is tested we can configure it to output RIS-Ky and other datasets to GBIF via the IPT, as well as UK datasets to the NBN Atlas. I could envisage coding the ability to send a file direct to the NBN via an FTP connection as well.
>

**Comment by kitenetter** [comment]
@johnvanbreda I can't find the email you mention, so don't have the server link.

One of the current manual exports (a large dataset of vascular plants) no longer runs via pgAdmin so we do need to resolve this, and I have added it to the July milestone. We can discuss at the June review meeting.

**Comment by kitenetter** [comment]
I've found the email which had gone to my home address, but I don't know how to find and make use of the server link.

**Comment by johnvanbreda** [comment]
@kitenetter do you have access to the folder where iRecord places the data exports currently?

I've just experimented with the Sawfly extraction and created a file, then compared it with the one that iRecord generated a few weeks ago. I found the following differences:
1. More records in the Elasticsearch version, partly because it's newer, but also possibly because the iRecord file is extracted using a scratchpad list of taxa, whereas I'm filtering Elasticsearch taxonomically on Sawflies.
2. The iRecord file defaults the "identifiedBy" field to the recorder name, if there is no other determiner or identifier field in the data. The ES version leaves these blank.

I think that it's pretty close. Would you like to nominate one of the exports for me to recreate, then I can set it up and provide an iRecord plus an ES version of the dataset for you to check?

Once that's done we need to write config files for each export (basically to copy the filter to an Elasticsearch filter syntax). Then we can schedule the batch file to run periodically.

**Comment by kitenetter** [comment]
@johnvanbreda I do have access to the folder for data exports. I can't see your ES version of the sawflies in there, do you want me to have a look at that one? I would like to check what the taxonomic filtering is doing.

And I guess the easiest one for me to check would be for soldierflies and allies (could just user one family for checking purposes: Stratiomyidae, but happy to include all 11 families to be a full comparison).

For point 2, I hadn't realised that we were populating the "identifiedBy" field in that way. I don't have any strong feelings about leaving it blank if the record doesn't state a determiner (and in fact I think I prefer that approach since it is a more faithfu l representation of what was originally recorded).

**Comment by johnvanbreda** [comment]
@kitenetter you can find both the Sawfly and Soldierflies outputs from the new process in D:\Drupal_Backup\dwc-extract-automation\test, as well as a JSON file for each which defines the query used. Hopefully it is not too hard to read but let me know if you have questions.

**Comment by kitenetter** [comment]
@johnvanbreda that file location is different to the one I have access to I think.

The one that I have access is is where the NBN export zip files get stored:
exports (\\192.171.199.203) (mapped to drive A: on my computer)

@BirenRathod are you able to give me access to the folder John is using:
D:\Drupal_Backup\dwc-extract-automation\test

**Comment by BirenRathod** [comment]
@kitenetter I have shared the folder with your user id. Here is the path  (//CEHWLBRCWEB1/test). you need to map this from your machine. Also don't forget to turn on VPN.

**Comment by kitenetter** [comment]
@BirenRathod I tried mapping to that path but am getting an error message:

![image](https://user-images.githubusercontent.com/16039111/131849878-31dc8fd7-62f7-48f3-9b93-1827d4bc9ac5.png)

I tried again with back-slashes instead of forward-slashes but got the same error.

**Comment by BirenRathod** [comment]
@kitenetter Sorry, I should not put the server name. it is \\192.171.199.203\test

**Comment by kitenetter** [comment]
Thanks @BirenRathod that has worked

**Comment by kitenetter** [comment]
@johnvanbreda for each of sawflies and soldierflies I can see a folder containing eml.xml and meta.xml files, and I can see a json file and a bat file, but I can't see any data.

**Comment by johnvanbreda** [comment]
I just regenerated those files for you @kitenetter. 

As it stands, the *.bat files call the PHP executable and need the correct path to PHP.exe in them. But, if there is a PHP upgrade, the path changes since the version number is in the path. @BirenRathod is there a way to call the latest PHP.exe via a path that won't change?

**Comment by BirenRathod** [comment]
@johnvanbreda Is it on warehouse server or irecord website?

**Comment by johnvanbreda** [comment]
@BirenRathod it's the old Drupal live webserver. But, it could be moved to another server as long as kitenetter can access it.

**Comment by BirenRathod** [comment]
@johnvanbreda When every time I upgrade, I create different folder name with that PHP version number under C:/php folder, so path changes. But I will create another folder and copy into so it won't be impacted with this. I will let you know about it.

**Comment by BirenRathod** [comment]
@johnvanbreda I created "vall" folder in C:\PHP folder. This is using latest version PHP 7.x

**Comment by kitenetter** [comment]
Moving conversation to #1301 - closing.
