### ISSUE TITLE
Verified records remining in pending list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1053]
One of our verifiers reports that records previously verified are re-appearing in his pending list on the verification page. The example given is occurrence ID 20224991. The dates shown against the record are:
- Submitted on 15/04/2021 14:22
- Last updated on 15/04/2021 14:22

But there is a verifier's comment saying that it has been accepted as correct, with the comment dated 2021-04-15 20:05:07, subsequent to the last updated timing.

The other example he gives is record ID 17747158. This has been verified twice, although I can't rule out human error (the second verifier could conceivably have re-verified an already-accepted record). The odd thing about this one is that the same occurrence ID appears twice in the verification grid, one showing as sensitive and the other not:

![image](https://user-images.githubusercontent.com/16039111/116711193-85e81700-a9ca-11eb-8e14-e9547e30891d.png)

**Comment by kitenetter** [comment]
It's possible that some of these records are still being verified on the old verification page, but I wouldn't expect that to cause problems with them appearing on the new page.

**Comment by johnvanbreda** [comment]
@kitenetter both these examples are verified so would only appear in the pending list if they change their filter to all records, surely?

There does seem to be an issue with sensitive records that are then changed to not sensitive, in that the full precision copy of the record that was created in Elasticsearch will persist in an "orphaned" state. This will need resolving.

**Comment by kitenetter** [comment]
That's the point @johnvanbreda - record ID 20224991 is showing in the pending list:

![image](https://user-images.githubusercontent.com/16039111/116716935-3c9ac600-a9d0-11eb-9e81-00e6a769cf43.png)

The second example has been verified twice, and it is claimed that it too came back into the pending list following the initial verification, but that's from longer ago and I'm not certain of the sequence of events.

**Comment by kitenetter** [comment]
Not sure what is happening with this one - occurrence id 20224991 has now been deleted. Closing for now, will re-open if verifiers report similar issues in future.
