### ISSUE TITLE
For record entry, switch 'vague date' option to off by default

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1056]
I think this a recent change on the add records pages. If you click in the date box, the calendar date-picker only opens up if the "vague date mode" is switched to "off". However, the choice of "vague date mode" resets itself on "on" every time you go back to add another record, making it difficult to use the date-picker.

Can we:
1. Switch the "vague date mode" to "off" by default.
2. If the user changes switches it to "on", remeber that choice for the current session.

**Comment by johnvanbreda** [comment]
I'll do this now as it's recently changed functionality.

**Comment by johnvanbreda** [comment]
Now done. The current state lasts as long as the cookie is saved (not just current session).
