### ISSUE TITLE
Delete Bloomin Algae Test Records

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#1058]
Request from Laurence Carvalho and Gemma Nash to delete test records prior to launch of  new version of Bloomin Algae. Record IDs: 

20380986, 20333721, 20329858, 20312280, 20257916, 20256730, 20254491, 20254489, 20252825, 20249893, 20249880, 20249561, 20245442, 20229668, 20227644, 20151169, 20119791, 20119758, 20105041, 20104624, 20097105, 20097102, 20097101, 20096989, 20096982, 20096306, 20096305, 20096304, 20095900, 20094898, 20094062, 20094056, 20092309, 20092268, 20092169, 20091861, 20091751, 20091694, 20091630, 20091626, 20091624, 20091623, 20091621, 20091618, 20084309, 19799023, 19798858, 19444290, 19444288, 18817191, 18817190, 18817189, 18817188, 18807905, 18807904, 18807903, 18793430, 18793369, 13291711, 7449674, 5903154

**Comment by burkmarr** [comment]
Deleted in Indicia. I think it will take a little while to propogate to the ES index.

**Comment by kitenetter** [comment]
Closing.
