### ISSUE TITLE
Taxonomic hierarchy error?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#106]
The taxon "Scutellina" is a fungus (Eyelash Fungus), but on iRecord it is shown as being within the marine Echinoderms, so it looks like there are some incorrect links in the taxonomic hierarchy.

Scutellina on iRecord:
http://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=146056

Scutellina on NBN:
https://data.nbn.org.uk/Taxa/NHMSYS0001497350

**Comment by johnvanbreda** [comment]
Took me a while to spot this! 

- Scutellin**_i_**a is a fungus: https://data.nbn.org.uk/Taxa/NHMSYS0001497350.
- Scutellina is an echinoderm: https://data.nbn.org.uk/Taxa/NHMSYS0021054296.

**Comment by kitenetter** [comment]
Well-spotted @johnvanbreda, and apologies for not realising that myself. The record that prompted this query had a photo attached of a fungus, hence was confusing to the marine verifier who got the record for verification, but neither of us had realised that it was just down to the original recorder choosing Scutellina rather than Scutellinia.
