### ISSUE TITLE
Odd behaviour in record list view - from iRecord butterfly submissions

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1061]
For user https://www.brc.ac.uk/irecord/user/89967/edit

When attempting to edit a record after submission, e.g. 
https://www.brc.ac.uk/irecord/record-details?occurrence_id=20402017

When clicking on the edit icon in the record row, user is taken to a list of records screen containing just the additional other  records, but not the original record (e.g. occurrence_id=20402017 is missing)

Is there an issue with how the data is being submitted via the app?

@johnvanbreda and @kazlauskis.  Can you liaise over this?

**Comment by kazlauskis** [comment]
At the moment, the Butterfly app is not attaching any particular edit forms (`input_form`) to the uploaded samples. I can change this to point to any iRecord form for the two surveys it hosts (sample+occurrence and sample+multi-occurrences). As an idea, maybe the website could detect the structure of the uploaded samples without the `input_form` and show the most suitable edit form instead.

**Comment by johnvanbreda** [comment]
Not an app problem, but a problem in the names index for Orange Tip. I've repaired it (plus 18 other taxa with similar issue). Difficult to say if this was a bug at some point, but it's isolated to these few taxa.

**Comment by kitenetter** [comment]
@johnvanbreda will this have fixed #1050 as well?
