### ISSUE TITLE
Record query function displays "double pop up" windows

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#1062]
When verifying records, if I use the "Query" radio button, I am getting two pop-up windows appearing overlaid on top of each other.  The first window to appear is the expected window, the second one appears to offer both options - either comment or e-ail recorder.  This is appearing about 90% of the time I use the query function.

![Image1](https://user-images.githubusercontent.com/18451743/119027715-945c9980-b99e-11eb-881a-3b751cd7c3bd.jpg)

**Comment by johnvanbreda** [comment]
I think this happens if you double click - I'll fix that.
