### ISSUE TITLE
Performance when saving a list of records

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#1064]
The performance when saving multiple occurrences could be improved by responding to the user as soon as the core sample, attribute and occurrences data are saved. Currently the main delay is population of the cache_* tables due to the large number of indexes so we should explore whether this could be asynchronous and processed after the user receives a response.

**Comment by kitenetter** [comment]
@johnvanbreda can we close this?

**Comment by johnvanbreda** [comment]
Yes, I think so as the proposed change has been implemented for very large samples as a requirement for EBMS.
