### ISSUE TITLE
Unknown warehouse_user_id (146641)

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1066]
From David Weaver by email to David Hepper, 06/05/2021 and I can provide his plus.com email address if useful. This looks like a problem with his iRecord vs. indicia user account: 

"Despite being able to log in successfully with my email address and user name - this is David Weaver (though I have also used Dave Weaver in the past), and entering casual records this year which appear to have been acknowledged upon submit, my records do not appear in the lists for MY RECORDS or ALL RECORDS. 
However upon logging in an error message does appear - 
> Unknown warehouse_user_id (146641)
... Recent casual records ... include:
- Large red damselfly 23 Apr and 2 May
- Small Tortoiseshell 29 Mar
- Speckled Wood 27 Apr

**Comment by kitenetter** [comment]
@JimBacon would you be able to look into this please

David Weaver's iRecord account page is at:
https://www.brc.ac.uk/irecord/user/38095

That gives a warehouse user ID of 146641.

However, that ID is showing as "deleted" in the users table.

There is a David Weaver who is linked to the BDS with user ID 80478, and has the same email address as the iRecord account, but that user has no link to iRecord in the warehouse.

See:
`SELECT * FROM indicia.users WHERE id IN (80478,146641)`

It looks like we need to merge these two users?

**Comment by BirenRathod** [comment]
@kitenetter Did you check in people table?

**Comment by kitenetter** [comment]
@BirenRathod 
There is no entry in the people table for David Weaver's email address, nor for his name as far as I can see.

**Comment by kitenetter** [comment]
@BirenRathod ignore my previous message, there was a space in the email address when I searched for it. There are in fact two entries in the people table for David's email address, one of which is deleted, see:
`SELECT * FROM indicia.people WHERE id IN (80630,146940)`

**Comment by BirenRathod** [comment]
@kitenetter There are two records in indicia.people table. Here is the query ->
SELECT * FROM indicia.people WHERE id in (80630,146940);

**Comment by kitenetter** [comment]
@BirenRathod let me know if you can see a solution to this (Jim is on leave this week).

**Comment by BirenRathod** [comment]
@kitenetter you can replace iRecord warehouse id with BDS id. This is the same problem occurred bit while ago for another user.

**Comment by kitenetter** [comment]
@BirenRathod sorry, I don't know how to do that. Do you mean an edit from within the iRecord website, or from within the warehouse interface?

**Comment by BirenRathod** [comment]
@kitenetter yes, by editing that user.

**Comment by BirenRathod** [comment]
@kitenetter let me know if you can't edit that also pass me the indicia warehouse id which you want to replace with.

**Comment by kitenetter** [comment]
@BirenRathod the user ID in the warerhouse is 80478
 Using https://warehouse1.indicia.org.uk/index.php/user/edit_from_person/80630 I have set that user to be linked to iRecord:

![image](https://user-images.githubusercontent.com/16039111/119384113-1d841100-bcbc-11eb-9e95-3fb86fe6ba24.png)

But I don't think I am able to change the warehouse ID for the user account on iRecord:
https://www.brc.ac.uk/irecord/user/38095

**Comment by BirenRathod** [comment]
@kitenetter I have replaced 146641 with 80478 which has linked to 80630. Do you know what are going to do with 146641?

**Comment by kitenetter** [comment]
What do we need to do with it? It is showing as deleted, so is that okay or does it cause problems if it remains in the table?

**Comment by BirenRathod** [comment]
@kitenetter Yes, sorry, I just noticed that. Although account created back in 2017, so may be account might link to back dated records. who has deleted?

**Comment by kitenetter** [comment]
User ID 80478 (David Weaver) now has 187 records showing via Explore - My records.

However, there are 14 occurrences, linked to 14 samples, that are attached to the deleted user ID 146641.

So I think those 14 occurrences and samples need to be transferred to user ID 80478. However, I don't know what needs to be done - presumably the occurrences and samples both need to have an update applied to created_by_id, but are there any implications for locations or recoder names or anything else?

The IDs affected are:
- Sample IDs IN (14289472, 14289459, 14289402, 14289363, 14289341, 14289323, 14289307, 14289297, 14289274, 14289269, 14289252, 14289246, 14289240, 14263919)
- Occurrence IDs IN (20329303, 20329213, 20329137, 20329080, 20329053, 20328958, 20328925, 20328842, 20328829, 20328806, 20328798, 20328791, 20328759, 20308484)

**Comment by BirenRathod** [comment]
@kitenetter Very unlikely if user have used the same location as for other records but if it has then we could revert it back by using 146641 again.
No harm for updating the created_by_id & updated_by_id

**Comment by DavidHepper** [comment]
I can't remember how I got involved with this issue. Closing.
