### ISSUE TITLE
Keyboard controls on verification page stop working in some circumstances

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1068]
Every so often the grid loses the focus, and the "i" key stops working. Sometimes this follows a click into the "recorder experience" tab, but at other times the focus just seems to get lost even when no other clicking has occurred. After I had been verifying for a while yesterday I found that I always had to click back into the grid before the "i" control would work at all.

Let me know if you need a HAR file for this.

**Comment by johnvanbreda** [comment]
I've changed this so it is more tolerant of the grid not being focused.
