### ISSUE TITLE
Search box not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#107]
Just tried to search for a user name using the main search box on the home page, and am getting an error message:

![image](https://cloud.githubusercontent.com/assets/16039111/19971819/1f6f08b6-a1d8-11e6-9df5-a9ae58c21c32.png)

**Comment by BirenRathod** [comment]
I don't see any problem. please send me an error details.

**Comment by kitenetter** [comment]
It's working fine again for me now, so presumably just a temporary glitch.
