### ISSUE TITLE
Should adding a photo to a record cause it to be move from queried to pending?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1072]
I marked several records as "queried" and asked the recorder to add photos to them. They did so, but the records have not reappeared in my "pending" view, nor in the "answered" view, they are still showing as queried.

I was expecting/hoping that they would reappear in the pending view, is that what should happen?

Example occurrence IDs:
20477601
20477598
20477116

**Comment by johnvanbreda** [comment]
No, as it stands it requires the addition of a record comment to answer a query.

**Comment by kitenetter** [comment]
@johnvanbreda that makes sense, but I was surprised that the addition of a photo did not cause the record to be seen as edited, and for is to therefore re-appear in the main pending grid.

**Comment by johnvanbreda** [comment]
The Query flag is separate to the main record status. Your verification grid shows all pending records where they are not queried by default.

When a record comes in it has the following attributes:
Status = pending, Query = null.

When you queried it, it becomes:
Status = pending, Query = queried.

When you add a photo or change a record, it resets the Status to pending, but it was already pending. This action does not change the Query flag - only an answering comment will do that. Therefore the record remains obscured from your default verification filter view. So, the remaining question is, should a record edit (including photo addition) reset both the Status flag to pending and the Query flag to null?

**Comment by kitenetter** [comment]
Thinking about this, I agree that the behaviour of the status and query flags is correct as descirbed above. However, I would like to propose that adding a photo to a queried record should trigger it to become "answered", even if no comment is added.

**Comment by kitenetter** [comment]
Further to this, a verifier has requested that we add some means of flagging that a record has been edited by the original recorder following a query by the verifier (see [forum post](https://www.brc.ac.uk/irecord/node/8372)).

One possibility would be for a record to be moved from "queried" to "answered" following **_any_** edit. That would alert the verifier that the recod had been changed (but the edit may or may not actually have addressed the query).

Does that sound like a sensible proposal, or do we need to think of another way to handle this?

**Comment by kitenetter** [comment]
There are pros and cons to the above suggestions, and this hasn't been raised as a problem recently. Closing for now.
