### ISSUE TITLE
Field locking for the stage term

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1075]
On the "Enter a casual record" form, a user has asked why the field locking no longer works for the State term. Am I correct in thinking that the introduction of the dynamic term lists means that we cannot enable field locking for stage any more?

If so, I will remove the locking option from this attribute on the main form.

**Comment by DavidHepper** [comment]
The Stage value is also cleared if the Species name is changed. Perhaps this is related to Stage being a required field.
