### ISSUE TITLE
Enable tetrad grid refs in ES views of the data

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1076]
A verifier has queried the fact the records entered at tetrad level seem to be given only a 10 km square grid reference in the ES grids. This does seem to be the case for the examples I've looked at.

Is is possible for tetrad grid refs to be displayed in the ES dataset? Does the correct tetrad reference get output in the downloads (let me know if you don't know and I will check).

**Comment by johnvanbreda** [comment]
@kitenetter we've never had support for DINTY tetrads in the code which blurs a spatial reference. This needs to be implemented so please prioritise as you see fit.

**Comment by kitenetter** [comment]
@johnvanbreda as far as I'm aware this is a problem for all tetrad records, not just ones that have been blurred. An example is:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=18088456

**Comment by johnvanbreda** [comment]
Yes, but the output_sref always runs through the blurring algorithm as this is also responsible for standardising the grid ref notation according to where on the planet the record is.

**Comment by kitenetter** [comment]
Okay, thanks. This doesn't feel like a high priority but I will leave the issue open.

**Comment by kitenetter** [comment]
As far as I can see tetrads are now being displayed as expected on the ES pages - closing.
