### ISSUE TITLE
Email notifications for training records

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#108]
Not sure if there is a need to receive cleaner/other notifications for training records, but I think I would like to have an option to turn it off for training ones.

**Comment by johnvanbreda** [comment]
@kitenetter - we need to decide if training mode records should be included at all? If so, then we can either separate them in the notifications email, explaining that they are training mode records and the links will only work if in training mode. Or, we can make the record-details form work for training mode records, but display a warning.

**Comment by kitenetter** [comment]
@johnvanbreda personally I am in favour of excluding training records from notifications, although I realise that is different from David H's view. I think we have enough complexity in the notification system without adding training records into the mix, certainly where verification notifications are concerned.

**Comment by kitenetter** [comment]
As part of our tidying up of the notifications process under Supporting Science I would like to see the training notifications switched off, as I feel they add unnecessary complexity to our notifications.

**Comment by johnvanbreda** [comment]
@kitenetter can I remove the notifications entirely for training records, or just the emails? One thing to bear in mind is that if we can remove training notifications entirely then it simplifies the query which loads the count of notifications on the home page, speeding things up a little.

**Comment by johnvanbreda** [comment]
Have committed code to the develop branch which skips counting of notifications on the home page when in training mode, as this makes it much faster. This is independent of the above question about whether to generate training notifications in the first place, or just to block the emails.

**Comment by kitenetter** [comment]
@johnvanbreda our Help page for training mode says "Any records you add while in training mode will be stored but not made visible to any verifiers, and will be hidden from view for all users of iRecord unless they are also in training mode. You can see them and download them while you are in training mode yourself, but as soon as you come out of training mode they will be hidden."

I don't think we should issue any notifications for training mode records. And in fact I also think that we should hide the training records from verifiers altogether, as per the Help text, but that is probably a separate issue that we can revisit if needed.

**Comment by kitenetter** [comment]
Noted @DavidHepper and will update the Help page accordingly to allow for the possibility of using training records in that way. Will raise a new issue for the background colour.
