### ISSUE TITLE
Possible problem with entering stage into list forms

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1080]
A user reports:

> Several times now when sending a 'list' I get an error message saying validation error and data could not be saved.
> If I send again it goes through.... but, any info I have put in on its status as adult/larva or gender is wiped out, and had to be put in again, so it means potentially that data is being lost.
> 
> The warning said 
> 
>     The data could not be saved.
>     Validation errors occurred when this form was submitted to the server. The form configuration may be incorrect as it appears the controls associated with these messages are missing from the form.
>         The value is required.
>            (related to attribute [occAttr:829])

I've not been able to reproduce this. WIll suggest user clears cache and see if the problem persists.

**Comment by kitenetter** [comment]
The same user is continuing to experience difficulties entering data. They use iRecord extensively and have not had similar problems in the past, so I can't see how user error could be causing this, but I'm not sure what is going on. 

The example in the screenshot is from a list of records for sveral different taxon groups, and my understading is that the stage terms were all entered but then got reset to "not recorded" when the user tried to save the list:

![image](https://user-images.githubusercontent.com/16039111/120304251-87f20e00-c2c7-11eb-8065-61c42f67063c.png)

**Comment by kitenetter** [comment]
Another occurrence of this issue from the same user. It appears that they entered a species list a few days ago, and then tried to add a species to that list, but it resulted in the stage terms being removed from the existing records, and thus the record failed to save.

![image](https://user-images.githubusercontent.com/16039111/123173859-27de2a00-d477-11eb-8a9b-ac2c1fa56255.png)

They abandoned the attempt to add a new record to this list so I don't think any data was lost on this occasion.

**Comment by kitenetter** [comment]
I didn't spot the year in the last screenshot! It wasn't a recently entered list, it was entered in 2020, so the problem arises when trying to add a new record to a list that was created before we implemented the dynamic termlists.

**Comment by johnvanbreda** [comment]
@kitenetter I've spent a while this morning trying to reproduce these issues but can't. Can we find out more about exactly what they did?

**Comment by kitenetter** [comment]
Difficult to know for certain. I've just tried masquerading and then going to edit the list shown in the above screenshot, via this link:
https://www.brc.ac.uk/irecord/enter-record-list?occurrence_id=14374674

Of the existing records in that list, the verified ones do have a stage term, but the unverified ones do not.

I haven't tried adding a new species to this list, but I assume that if I were to do so the list would fail to save unless I also filled in the missing stage terms.

I'm not sure why **_all_** the stage terms appear to be missing in the screenshot above, maybe that is because it is a shot of the screen **_after_** there has been an attempt to edit the list???

I know that you set this so that verified records would not have their stage terms changed and would thus avoid being presented for re-verification. So perhaps the system is working as intended. But I wonder if we should set it so that no existing record has a stage change unless the user explicitly edits that record?

Alternatively, can we make the error message more meaningful, so that it asks users to add the missing stage terms if they want to save their list? We could also advise that if a user wants to add to an existing list it might be simpler to create a new list rathr than editing an existing one.

**Comment by kitenetter** [comment]
This is another rather vague report I'm afraid, but another user says that they are getting a similar error message when trying to add new records. From what I can in their screenshot the stage details are being filled in so I'm not sure what is happening.

![image](https://user-images.githubusercontent.com/16039111/123463412-65f85c80-d5e3-11eb-9693-ed83a676cff9.png)

**Comment by johnvanbreda** [comment]
@kitenetter I've found and fixed a problem which caused the validation rules associated with dynamic attributes to be missed out on the browser, but then applied on the server which results in messages like the above. You can't see in the screenshot but it's likely one of the rows doesn't have the stage filled in. Now - this would be caught in the browser with a normal validation message.

It's possible this improvement will help with several of the above scenarios.

**Comment by kitenetter** [comment]
@johnvanbreda I'm still experiencing 'drop-outs' where the stage stops auto-filling into the subsequent row. Sometimes this seems to happen at random, but one particular case where it always seems to happen is if I add a photo to an occurrence, The subsequent occurrence does not have the stage copied down, even if the next occurrence is for the same taxon group.

**Comment by johnvanbreda** [comment]
Fixed the problem with image rows getting in the way. Please re-open if you find other ways of reproducing this.
