### ISSUE TITLE
Enter casual record: stage term is lost if sex term entered after stage

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1082]
Sequence is:
Go to:
https://www.brc.ac.uk/irecord/enter-casual-record
Add a taxon
Add a stage
Add a sex

Once you click out of the sex box, the stage term gets nulled.

Maybe related to #1075?

**Comment by DavidHepper** [comment]
The Stage value is also cleared if the Species name is changed. Perhaps this is related to Stage being a required field.

**Comment by kitenetter** [comment]
@DavidHepper regarding changing the species name, I think that probably does have to force the stage to be cleared, as an edit from one taxon group to another may need to link to a different set of stage terms,

**Comment by johnvanbreda** [comment]
Fixed in the develop branch - when you change the species or sex, it can affect the potential list of stage terms. So the control is reloaded - it now remembers the last value.
