### ISSUE TITLE
Problem with importing records based on vernacular names

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1083]
I've just realised that if a user imports a csv file that contains records of the Uncertain moth, and uses the English names to do the import, at least some of the records are getting matched to a UKSI taxon labelled "Uncertain" that applies to an unidentified chironomid midge.

The incorrect taxon is:
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/504317

It is already flagged as a Redundant taxon in UKSI, and is flagged as not for data entry in Indicia. But our csv import process is still making use of it.

Consequently, the records are not available to moth verifiers, but are getting included in one of the Diptera datasets we send to NBN Atlas.

Can we prevent this happening? Would it help to exclude "not for data entry" taxa when matching csv imports?

**Comment by johnvanbreda** [comment]
Was fixed by https://github.com/Indicia-Team/warehouse/commit/6734bd8d97b158d188d72617c113a837d6dc0d0a. Note that the allow data entry flag is used to prioritise names, not exclude them, as they are often needed for historic data imports.
