### ISSUE TITLE
Investigate name change request

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1085]
User request:
Amanda Forde nee Brown has tried changing her name in iRecord but records are still coming out as her maiden name: https://twitter.com/mandy_forde/status/1399747374143229955

I think this may have been on the issues list before but I can't remember where it got to - will review.

Relates to #869

**Comment by kitenetter** [comment]
A second similar request, from the Wesh LERCs (as is the one above):

> I’m just wondering if you got anywhere with this re Anna Georgiou App records being listed as bis employee (we have another dated 31/05/2021). Anna’s Wired records are assigned to Anna so no problem there.
> 
> Could it be due to Anna making some records using a survey? We have some pre issue records made using iRecord App General Survey.
> 
> To confirm there is no user listed on Wired as bis employee. It seems to be a default when there is an issue with app records made by previous BIS employees who have used their @bis email to register Wired / the App.

**Comment by johnvanbreda** [comment]
For the latter @kitenetter, I've just run the following query (since Dave had asked me to look at it):
```sql

update people set first_name='Anna', surname='Georgiou', updated_on=now(), updated_by_id=3 where id=81932

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, 100, 2, now()
from cache_occurrences_functional where created_by_id=81780;
```

Let me know if you need me to look at the first issue.

**Comment by johnvanbreda** [comment]
The first issue here is covered under #1520 so closing.
