### ISSUE TITLE
Report that species alert notifications are not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1086]
Verifiers associated with the Bloomin Algae app have reported:

> (Verifier 1) I seem to have stopped receiving notifications of records – I’ve checked in iRecord and I have no notifications to acknowledge – but records have come in.
> (Verifier 2) I've had some records alerted to me by email BUT some were already verified whereas others said they weren’t but were. Strange? I've looked in the iRecord and think alert settings are ok

I can't see any obvious problem with the settings. Verifier 1 has a species alert set up for Cyanobacteria, haven't yet checked verifier 2.

**Comment by kitenetter** [comment]
Yesterday I set up a species notification for myself, just to get more familiar with the process, and I have just received the first notification. So in that case at least it seems to be working fine.

**Comment by johnvanbreda** [comment]
Closing as I'm pretty sure notifications are being generated.
