### ISSUE TITLE
Notifications of Training Mode records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1089]
Is it by design that records submitted in Training Mode are reported, to the submitter CMS User at least, within email notifications in the usual way and without any flag indicating that they are only for testing? Might this cause consternation or annoyance, especially when testing improbable scenarios?
Examples: 20556696, 20556878, 20556696

**Comment by kitenetter** [comment]
This has been discussed (but not yet resolved) under #108 - I think we should not be sending notifications for training records. Closing.
