### ISSUE TITLE
Bug in vague date handling

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#109]
We have an activity form that allows samples with vague dates to be entered:
http://www.brc.ac.uk/irecord/enter-records-vague-date

An error arose when the form was used to enter a non-standard vague date:
06/1992-1996

The resulting error message was:

> cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
> URL:http://warehouse1.indicia.org.uk/index.php/services/report/requestReport?report=library/occurrences/explore_list_using_spatial_index_builder.xml&reportSource=local&mode=json&nonce=8cc315450374a542118d9ba668611d5bb2cad347&auth_token=42e9f7555027beb3cec45b86f971c7f6dac9463c&limit=10&offset=0&wantColumns=1&wantParameters=1¶msFormExcludes=["survey_id","taxon_group_id","smpattrs","occattrs","searchArea","idlist","exclude_sensitive","currentUser","ownData","location_id","ownLocality","taxon_groups","ownGroups","user_id"]&&survey_id=&taxon_group_id=&smpattrs=&occattrs=&searchArea=&idlist=&exclude_sensitive=1¤tUser=0&ownData=0&location_id=0&ownLocality=0&taxon_groups=&ownGroups=0&user_id=102855
> Server response
> {"error":"general_errors.Year ranges should be represented by the first day of the first year to the last day of the last year. Start was 01\/06\/1992, end was 31\/12\/1996.","code":0,"file":"D:\\web sites\\warehouse1\\application\\helpers\\vague_date.php","line":811,"trace":[]}
> general_errors.Year ranges should be represented by the first day of the first year to the last day of the last year. Start was 01/06/1992, end was 31/12/1996.
> 

The underlying bug should ideally be fixed to avoid future errors if anyone tries to enter a non-standard date.

**Comment by johnvanbreda** [comment]
Now fixed. 06/1992-1996 is now caught as a validation failure and even if a different date format caused a similar problem the reports would now display "Invalid" in the date field rather than crash the whole report.
