### ISSUE TITLE
Location type support in Species Alerts page

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#1090]
The species alerts page on iRecord currently allows the user to select from a small number of location types to define a boundary for their alert. This needs to be expanded to allows selection of NUTS level 2 and 3 boundaries for Bloomin' Algae. 

As NUTS 3 in particular contains a large number of locations, the prebuilt form will need an additional optional location type selector which causes the locations available for selection to change appropriately. 

Also due to the large number of locations, an option to convert the location select to a location search is desirable.

**Comment by LaurenceCarvalho** [comment]
Hi John
Yes for NUTS2 and NUTS3 - I don't know ehether you can have 2 selection boxes - first being "Country" that selects UK (ideally with Scotland, NI, Wales and England separate), Ireland, Belgium, Netherlands and then a second layer that selects the list of NUTS 2 or NUTS3 regions within these countries
Laurence

**Comment by johnvanbreda** [comment]
Updated version of species alerts page now ready at https://www.brc.ac.uk/irecord/node/8381. Just need @kitenetter to confirm this configuration can replace the original species alerts page.

**Comment by kitenetter** [comment]
I agree with @DavidRoy that this should be fine to implement, as long as there are no implications for alerts set up under the old configuration. Will they carry on working? If not we will need to inform users, but if they will continue that should be fine.

**Comment by LaurenceCarvalho** [comment]
Hi folks - we're sending out a newsletter to recorders this week and hope to add the new instructions for setting up notifications by country/NUTS regions - but want to make sure we provide the correct URL.

Has the new configuration replaced the original species alert page? Or is it best we give them this link https://www.brc.ac.uk/irecord/node/8381

**Comment by kitenetter** [comment]
My expectation is that the URL will remain the same:
https://www.brc.ac.uk/irecord/species-alert-notifications

The new page will replace the page that is currently there.

@johnvanbreda please let us know if this is not the case.

**Comment by johnvanbreda** [comment]
That's correct. I plan to do this tomorrow.

**Comment by johnvanbreda** [comment]
I've done that. @LaurenceCarvalho is it OK if I delete https://www.brc.ac.uk/irecord/node/8381 or have you given this link out?

**Comment by LaurenceCarvalho** [comment]
That's great John - you can delete the 8381 link - we'll send out the newslwtter today with the original (updated) link. Thanks!
