### ISSUE TITLE
Error message with glow-worm form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1092]
A verifier has been trying to add a record to the glow-worm form at:
https://www.brc.ac.uk/irecord/glow-worm

Last night and this morning he is seeing this error message when he tries to submit the record:

> An error occurred when the data was submitted
> array_key_exists() expects paramater 2 to be array, null given
> Error occurred in D:\websites\warehouse\modules\indicia_svc_data\controllers\services\data.php at line 1497
> Array
> (
> )

I submitted a record just now and did not get an error message.

**Comment by kitenetter** [comment]
Have managed to repduce this. It seems to be related to the comment text that the user is trying to add, which includes a number of symbols:

> Start 22:30. Dry. Temp 9 deg. Wind BFS 0-1, Cloud <5%. 12 Lures used. Nothing found. One female seen on trail below on return to car park . Given low temp inconclusive nil return and worth another look as habitat good. Wye Valley SSSI unit 23. End 23:05

If I enter that text and try to save a record I get the same error message as shown at the top of this issue.

The user also reports that if they enter the record without the comment, it does save correctly. They then tried to add the comment as an edit after the record had been created. This time it saved part of the comment but truncated it and added what appears to be a Google map reference:

> Start 22:30. Dry. Temp 9 deg. Wind BFS 0-1, Cloud <5%. 12 Lures used. Nothing found. > *Google Satellite*)

This record can be seen at:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=20678986

If I save a record with the full comment, but replace "<" with "below", it saves okay. So I assume that iRecord cannot handle a less-than symbol in its comments.

**Action required:**
Either enable "<" and ">" to be used in comments, or disallow them and provide a more informative error message for people who try to use them.

**Comment by kitenetter** [comment]
The above issue appears to be specific to the glow-worm form. If I add the same comment, with the "<" symbol, to the casual record form it saves with no error message.

Is there a setting in the form that could be changed?

**Comment by johnvanbreda** [comment]
@kitenetter this should now work. It was the presence of the < and the word "on" which was triggering some security code that strips out attempt to insert potentially dangerous script code into any content. I've tightened the check for this so that this example will no longer trigger the issue, but any real attempts to insert active scripts will still get stripped.
