### ISSUE TITLE
Asian Hornet records not appearing for verification

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1093]
Verification filters for the Asian Hornet Watch survey are not showing any records since 6 or 7 June.

I can't see any problems in the filter settings.

**Comment by kitenetter** [comment]
Records are appearing on the old verification page, but not the ES page.

**Comment by johnvanbreda** [comment]
The sensitive records feed into Elasticsearch was blocked as the system thought it was still running. I've unblocked it.

**Comment by johnvanbreda** [comment]
This should be working now @kitenetter

**Comment by kitenetter** [comment]
The Asian Hornet records are now appearing on the verification grid for me, so this appears to be fixed, thanks. Closing.
