### ISSUE TITLE
Deleted user account problem

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1094]
User ID 166416 has reported that none of their records added since 6 June have appeared in iRecord. I can see the records prior to 6 June if I masquerade and use the ES "My records" page. But if I go to the old "My records" page no records are visible.

The user appears to have been deleted from the warehouse:
- deleted = true
- updated_by = 1
- updated_on = 2018-07-22 11:28:39

So the user needs to be reinstated in the warehouse. 

What will have happened to the records they have added recently?

And can we find out how the delete occurred?

**Comment by johnvanbreda** [comment]
I've undeleted this user and triggered a re-build of their occurrences data in the cache tables just in case. Unfortunately I don't have any way of determining why the account was deleted as we don't have auditing enabled for the users table.

**Comment by DavidRoy** [comment]
Thanks.  Can you run a query to summarise the number of users who have deleted accounts.  Date of deletion and a count of number of occurrences.  This might inform if this is wider issue, if it's a recent phenomenon etc.

**Comment by kitenetter** [comment]
There is still something odd happening here. User id 166416 is still showing in the users table, and is not visible in the warehouse interface. So if they were undeleted they seem to have been deleted again.

The user has tried adding records recently and they are not showing in his My records view on iRecord. I added a test record this morning while masquerading as the user, which is occurrence ID 20726805. That record doesn't appear to be visible within iRecord.

This set of records has created_by_id = **166416**, but the records are only visible on the user's **old** "My records" page (and all originate from SEWBReCord):
`SELECT * 
FROM indicia.cache_occurrences_functional
WHERE id IN (10866354,10866353,10866352,10866351,10866350,10866349)
ORDER BY id DESC`

This set of records (this is a subset of the total set of records) has created_by_id = **166889**, but the records are only visible on the user's **new** "My records" page (and all originate from iRecord or from one of the apps):
`SELECT * 
FROM indicia.cache_occurrences_functional
WHERE id IN (20580543,20573185,20516662,20516656,20516651,20516636,20516590,20516072,20516036,20516030,20515520,20515387,20515368,20515361,20515351,20515343,20512845,20512208,20511848,7396998,7396997,7396996,7396995,7396994,7396993,7396992,7396991,7396990,7396989,7396988,7396987,7396986,7396985,7396984,7396983,7396982,7396981,7396979,7396978,7386476,7364454,7364394,7364205,7364040,7364007)
ORDER BY id DESC`

User id 166889 is also showing as deleted in the users table.

In the people table there are two entries for this user's email address, and both are showing as deleted:
`SELECT * FROM people
WHERE id IN (167314,166841)`

So we seem to still be at square one with this. As far as I can see, this is what needs to happen:
- people id 167314 needs to be undeleted and linked to user id 166416
- user id 166416 needs to be undeleted and linked to people id 167314
- occurrences attributed to user id 166889 need to be moved to user id 166416

As usual, I'm not sure if there are implications for other parts of the data structure in making these changes.

For reference, the Drupal account is:
https://www.brc.ac.uk/irecord/user/46260

**Comment by johnvanbreda** [comment]
I suspect that the deletion occurs when the system detects a duplicate account issue and asks the user to resolve it buy merging users. The problem may have been triggered by the combination of 2 accounts across iRecord, SEWBrecord and BeeWalk which I hadn't spotted before. I've added code to the warehouse so that if a deletion occurs again, we'll know when and by who. I've also tidied all the records into account 166416 which I've undeleted, and made sure all 3 Drupal users point to the correct warehouse user. User 1666889 is still deleted.

**Comment by kitenetter** [comment]
@johnvanbreda this one still isn't resolved, but I can't see what the problem is.

User ID 166416 entered 19 records which seem to be present and correct in table occurrences, but are not visible in table cache_occurrences_functional, nor on iRecord itself.

The occurrence IDs are:
20726805,20723499,20662906,20662829,20662817,20662785,20662751,20662685,20634583,20632203,20632165,20631544,20631513,20624704,20605225,20596944,20596934,20596922,20590209

Is there some re-indexing required?
