### ISSUE TITLE
Verifier unable to send email queries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1098]
A verifier reports that they get an error message if they try to query a record via email:

![image](https://user-images.githubusercontent.com/16039111/122550800-08d13980-d02c-11eb-8dfb-da70d8745a1d.png)

I have just sent an email from the iRecord support account with no problems, so not sure if this is specific to the particular verifier.

**Comment by DavidHepper** [comment]
Even if the error is warranted, the text isn't grammatical: "Please send the following email usual your email client"

**Comment by kitenetter** [comment]
Have not had any further reports of this problem. Closing.
