### ISSUE TITLE
Record submit button not working?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1101]
I've now seen reports from three different people that when they click on the submit button nothing is happening. I haven't been able to reproduce this myself.

**Comment by kitenetter** [comment]
Removing the "urgent" label because the issue is still quite vague at the moment. Nobody seems to be getting error messages, and it seems to be a very small minority of people who are affected. But it's an important issue for those who are affected!

Any suggestions for how we can track this down would be welcome.

**Comment by johnvanbreda** [comment]
@kitenetter if we can get details of the browser, the input form used and the exact data values they input in the form then we can try to reproduce it.
My only thought is whether this is something to do with the date control as that's the only significant data entry control which has changed recently.

**Comment by kitenetter** [comment]
User 1 cleared their cookies and the submit button has been working fine since then.

User 2 was still experiencing problems yesterday - awaiting more details.

**Comment by kitenetter** [comment]
Just had a zoom call with User 2 - things are working fine for him now, no idea what the problem was.

Closing.
