### ISSUE TITLE
Record details not displaying on verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1102]
This evening, if I go to my verification page and click on a record in the grid, the record details are not being displayed. I can only see the default "Select a row to view details" button. The map display is updating correctly, it is just the record details that are refusing to display.

Using Firefox. I just tried clearing cookies and going back in but there was no change.

**Comment by kitenetter** [comment]
Same behaviour in Edge.

**Comment by kitenetter** [comment]
Just realised that I've also lost the map layer for "currently selected species".

**Comment by johnvanbreda** [comment]
Fixed - a mistake in an earlier bugfix.

**Comment by DavidHepper** [comment]
Working for me now.
