### ISSUE TITLE
iNaturalist data: filtering options

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1104]
Geographical scope: add Isle of Man to UK if not already included.

Type of observation: exclude observations that are tagged as “Captive / Cultivated”

@kitenetter to liaise with Channel Islands recorders regarding iNat data

**Comment by johnvanbreda** [comment]
I've added the IOM place_id to the configuration of our API request. I've also added captive=false but note that there are zero captive/cultivated and research_grade observations in the UK+IOM.

**Comment by kitenetter** [comment]
Jersey BRC confirm that they would like Channel Islands records from iNat to be brought into iRecord alongside the UK ones.

**Comment by johnvanbreda** [comment]
Do you know if there is an iNaturalist place that covers the Channel Islands accurately? These ones for example doesn't seem to accurately reflect the territorial waters - https://www.inaturalist.org/places/vc-113-channel-islands, https://www.inaturalist.org/places/guernsey, https://www.inaturalist.org/places/guernsey, https://www.inaturalist.org/places/jersey.

**Comment by kitenetter** [comment]
I suggest we use https://www.inaturalist.org/places/vc-113-channel-islands for now at least. The same issue about extent of the marine boundary arises for the UK and IoM places as well. Maybe we need to get a new boundary added to iNat that encompasses a wider area, especially considering the need for marine records to be included.

I'm not sure what is involved with adding a place to iNat, will investigate.

**Comment by johnvanbreda** [comment]
I've added that polygon to our filter.
