### ISSUE TITLE
iNaturalist data: additional attributes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1105]
iNat project IDs: add a custom attribute to the iNat survey structure in Indicia to capture associated project IDs (no immediate use case for this but will add future-proofing). This attribute will presumably need to allow for concatenating multiple IDs where an observation is linked to more than one project.

If possible, use iNat's standard annotations for "Life Stage" and "Sex" to populate the equivalent attributes in iRecord.

If possible, capture the iNat quality_grade attribute (casual; needs_id; research) as an additional custom attribute in Indicia (no immediate use case for this as we are initially proposing only to bring in research grade records, but there may be a need in future for other grades to be made available).

**Comment by johnvanbreda** [comment]
Code (develop branch) and config all done so can be merged to master and deployed when you are ready for it to be turned back on @kitenetter.

**Comment by kitenetter** [comment]
@johnvanbreda I've discussed with @DavidRoy and we would now like to re-start the iNat import process, as long as this will not result in the iNat records appearing in the standard verification view.

I will ask a small number of people to test the new iNat verification page. If all goes well we can make that page visible in the menus at the end of July.

**Comment by kitenetter** [comment]
We are now intending to re-start the iNat data imports in September, to link in with wider communications from NBN around the UK iNaturalist project.

**Comment by johnvanbreda** [comment]
@kitenetter, OK, are there any of the original requirements which are still considered key that I need to ensure are done first? Bearing in mind that a lot of the early ideas could not actually be implemented due to technical constraints.

**Comment by kitenetter** [comment]
@johnvanbreda as far as I'm aware we have implemented the things that were possible within the constraints.

**Comment by DavidHepper** [comment]
'casual' grade records, e.g. ID  are being imported. I thought we were sticking with importing 'research' grade only as the initial issue report at the top. This gives more time for the record details to stabilise before reaching 'research' grade and only then being imported.

**Comment by johnvanbreda** [comment]
As far as I can see, we are sending a parameter "'quality_grade=research" in the request to iNaturalist.

**Comment by DavidHepper** [comment]
Example: 22453680 
There may not be many but it's the existence of any that is surprising.
Incidentally, Search in Explore fails to find the word 'casual' in any iNat records so can't be used to identify them.

**Comment by johnvanbreda** [comment]
We don't store the research grade attribute, since they are all supposed to be once they reach iRecord. But, record 22453680 (https://www.brc.ac.uk/irecord/record-details?occurrence_id=22453680) is this record in iNaturalist - https://www.inaturalist.org/observations/60128950. I don't see a problem here as it's flagged as Research?

**Comment by DavidHepper** [comment]
That's less worrying but I'm seeing this in iR: 
![image](https://user-images.githubusercontent.com/24915271/141446445-da8e6f3d-4470-4d31-867b-92131d7234bb.png)

It seems to me unlikely that the Grade has changed in iNat since the record arrived in iR on 5 Oct or was updated on 5 Nov.

**Comment by johnvanbreda** [comment]
Looking at the audit trail for this record it seems that a verified edited it on 3rd November and added a stage and comment, then changed the research grade to casual.

**Comment by DavidHepper** [comment]
I'll ask Mike A. what he did and whether he meant to do it...

**Comment by DavidHepper** [comment]
I've checked with the verifier and he says he didn't mean to change its grade to 'casual' but did have a poke around to see what options were available, so it was probably accidental. Can you think of a way to check for others?

**Comment by kitenetter** [comment]
Given that the quality should always be research grade, is there an argument for not displaying this attribute to verifiers, since it just takes up space and doesn't add any useful additional information?

If we do continue to display, there is also an argument for making it non-editable, since it is something that should only be chaged within the iNat context.

**Comment by DavidHepper** [comment]
The _real_ problem with this record is the location: iR shows a Record Details grid ref of SO86523754: 
![image](https://user-images.githubusercontent.com/24915271/141463771-031bd453-2087-481d-a8fb-c32acd75a6c0.png)
but the computed grid ref shown in the iR Grid is only SO83, due to the accompanying Uncertainty value of a whopping 650 m, making this record when exported pretty well useless. 
Looking back into iNat, the geolocation was a sensible lat-long with Uncertainty 650 m. I'll ask iNat whether the uncertainty value was generated by the GPS on their iPhone App (likely) or tweaked by the observer. If the observer had stood still for longer would it have refined the lat-long and reduced the uncertainty?
As discussed previously, we really don't want records with a map ref vaguer than Monad, or possibly Tetrad.

**Comment by johnvanbreda** [comment]
The data we imported into iRecord was "a sensible lat-long with Uncertainty 650 m" as per iNaturalist but the grid square was added later by the verifier. 
@kitenetter to confirm if any records should be skipped if too large a coordinate uncertainty.

**Comment by DavidHepper** [comment]
@kitenetter - Please prevent import of Odonata records from iNaturalist with positional Uncertainty greater than 500 m. This seems to be a reasonable balance.

**Comment by DavidHepper** [comment]
Incidentally, I notice that iRecord (and iNat?) on one hand and NBN Atlas on the other have different ideas ways of computing Uncertainty from grid refs. iRecord computes half the side of the square whereas NBN Atlas computes half the diagonal of the square. For a 100 m square these come to 50 m and 70.7 m respectively.
