### ISSUE TITLE
Drupal 9 testing feedback

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1106]
Not sure how you want to receive feedback - here is an initial list but I can split it up into separate issues if needed.

**1 Home page**
I'm getting an "ES query failed" message (relating to the map I think)

The "recent sightings" block is empty.

**2 Add casual record**
The Recorder name is defaulting to "Harvey, ". On current iRecord it would be "Harvey, Martin C." (but we want to change this behaviour, see #1027 )

The Recorder name and Species boxes are too wide.

**3 My records**
I got a timed out error, and the page did not load.

**4 Verification**
The map is too wide, and the records grid is not wide enough nor deep enough

The Query and Redet buttons are not visible (they appear if you hover over them but are not visible unless you hover).

When accepting or rejecting a record, the comment box that opens up has a very large font size for its heading. Not a major problems but looks a bit odd.

**Comment by BirenRathod** [comment]
@kitenetter 
1. This happens in your account. I don't see that problem if I masquerade as iRecord support or Biren (my account) account. 
    Also, Box sizes of Recorder name and Species should be like that, so it will resize automatically when page land on mobile device. 
2. I will transfer user data including first name and last name from current irecord site.

3. I don't see this problem on iRecord support or Biren account, but this could be due to minimum setting used on dev/test site. it should be fine for live.
4. We could change the way display use on all pages, @johnvanbreda can you do 65 35 display settings for map & record display on this or shall I change that in the theme's css? 
Those buttons now visible and text size has been decreased in the comment box.

**Comment by johnvanbreda** [comment]
@BirenRathod the first issue (Elasticsearch error on home page) relates to the code which applies the taxon group filter in Martin's user profile to the Recent Records block. It wasn't coded correctly in Drupal 8 hence the error. I've applied a code fix but the current Drupal 9 site does not show the taxon groups on the user's profile so this needs to be looked into.

**Comment by BirenRathod** [comment]
@johnvanbreda Do I need to update the repository or is it the bug in the code?

**Comment by johnvanbreda** [comment]
I updated the repository (Github develop branch, plus Pantheon's iRecord repo)

**Comment by BirenRathod** [comment]
thanks for that.

**Comment by kitenetter** [comment]
I'm finding it almost impossible to use the verification page with the grid being so narrow, so can't do much testing at the moment.

**Comment by BirenRathod** [comment]
@kitenetter I missed to comment about verification page but the page is no longer using narrow width. I don't know whether you noticed or doing further testing of this.

**Comment by kitenetter** [comment]
@BirenRathod I'm still struggling to use the Drupal 9 version of the verification page. On Firefox, the layout looks like this:

![image](https://user-images.githubusercontent.com/16039111/128196119-a4916fb3-26dc-4494-89ce-c6a9bea69f46.png)

The current live iRecord verification page looks like this:

![image](https://user-images.githubusercontent.com/16039111/128196232-0e5c90b4-e014-4742-b932-823a4173f935.png)

The main problems with the Drupal 9 page are:
- The font size in the grid is larger, so the information gets more squashed up, and only about 5 records can be seen without scrolling (it's about ten records on the live page)
- The map takes up too much space
- If you click on a record in the grid, it is hard to see the record details associated with it, and lots more scrolling is needed

**Comment by BirenRathod** [comment]
@kitenetter one basic problem with new layout is that @johnvanbreda has divided the page into 50:50, so he needs to amend that. Once that's done then we could sort out the font problem & other display bit.

**Comment by johnvanbreda** [comment]
Hi @BirenRathod - I don't think I've been assigned responsibility for the Drupal 9 migration, other than to migrate code modules to Drupal 9 as required. So you should be able to apply a CSS file to the verification page to change the column widths?

**Comment by BirenRathod** [comment]
@johnvanbreda Further investigate, I found one more thing that you used $indicia_templates['two-col-50'] which has got col-md-6 class. you can replace that with col-md-8 for left side view and for right side view col-md-4. If you implement that, the verification page will display same as current live iRecord verification page. I will then add require CSS implementation. 

I mentioned implementation but you can add one more class in templates.bootstrap.php, so the page will divide into 80:20 display.  This is where code implementation needed.

**Comment by DavidRoy** [comment]
@BirenRathod please taken on as much update/design work as you can for the new drupal 9 site.  Thanks

**Comment by BirenRathod** [comment]
@DavidRoy  That is not a problem but I need an input from @johnvanbreda on this verification page which divide using bootstrap theme. Bootstrap theme works differently then other theme and since indicia code implemented using that it would be good if code comes from repository.

**Comment by johnvanbreda** [comment]
@BirenRathod It's not really different. The old code and the new Bootstrap based code both have a simple way of creating a 2 column layout on any dynamic form, using the | character. This defaults to 50|50. On the verification form, there is a custom css file node.7614.css which applies CSS changes to change the column widths, but these have not been changed to work with Bootstrap or the new theme. So, for example, you could add this to the CSS file to change the column widths:
```css
.col-md-6:first-child {
    width: 65%;
}
.col-md-6:last-child {
    width: 35%;
}
```
Although it might be nice to support alternative column widths without custom CSS directly inside the Iform code, this is very rarely needed so I don't think it's worth the extra complexity.

Also in the custom CSS file there is code to hide the header and footer etc which has not been altered to match the new template.

**Comment by BirenRathod** [comment]
@johnvanbreda As I mentioned I could do that in CSS but as bootstrap theme provide for each of this different style, it would be good idea to add those code in the repository which will be beneficial for other pages on iRecord.  You don't need to add all of them but some would be nice. Like for e.g $indicia_templates['two-col-50'], $indicia_templates['two-col-80'], $indicia_templates['two-col-20']
Thanks for your suggestion anyway. 

I will implement those CSS for header and footer as I'm doing for other pages.

**Comment by BirenRathod** [comment]
@johnvanbreda  I have implemented the footer, header code in CSS. 
@kitenetter I have implemented the code, so it looks exactly like current site.

**Comment by kitenetter** [comment]
New issue: if you click on one of the buttons to verify a record, or to query a record, there is no close or cancel option. You can cancel it by pressing "Esc" on the keyboard, but we used to have a red cross in the corner of the dialogue box that would allow you to come away from it without saving it.

The Redet dialogue box has a cancel button, so we probably need to implement something similar for the verification and query boxes.

**Comment by kitenetter** [comment]
I'm going to close this one, which has got quite long, and start a new one.
