### ISSUE TITLE
Drupal 8

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#111]
Hi, any plans on migrating to DP8?

**Comment by johnvanbreda** [comment]
Current status of Indicia code is that the core functionality does work (and is being used live by ERCCIS) but there are still some aspects of functionality (less frequently used forms and edge cases) which are not ported properly. 
Another thing to consider is that many Drupal modules are still in the early stages with respect to D8 - some are not ported, some are still not stable.

**Comment by kazlauskis** [comment]
OK, thanks, I guess that means we will have to wait until all the modules are ported first.
