### ISSUE TITLE
Verification page - record details not displaying for first record in grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1111]
Frequently, but not always, I find that if I click on the top row in the verification grid, the record details are not displayed.

If I click on the second row the details appear for that one, and I can then go back to the first row and see its details. But clicking just on the first row often fails.

**Comment by johnvanbreda** [comment]
@kitenetter I couldn't reproduce this in Edge or Chrome. Do you just open the verification page then click on the top row? Or have you done something else first?

**Comment by kitenetter** [comment]
I'm using Firefox, but I can't replicate it either at the moment. It has been a persistent issue over the last few weeks, but I will try to keep note of what has happened if I see it again.

**Comment by kitenetter** [comment]
This just happened again, and a small HAR file is below, but I don't think it will have captured the full sequence. I had opened up the verification page and had filtered the records in various ways, ending up with a column0head filter for occurrence ID 12545801. At first this was fine and the record details were available, but after the page had been open a while, and following some filter changes to force it to update (e.g. I switched from "all" to "no photos" and then to "photos"), the record is displaying in the grid but not in the record details.

Because the column-head filter is restricting the display to a single record there is no way of retreiving the details by clicking onto a second record and then back again.

[www.brc.ac.uk_Archive [21-07-12 16-43-43].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/6802712/www.brc.ac.uk_Archive.21-07-12.16-43-43.zip)

**Comment by kitenetter** [comment]
Here's another HAR file. This is a minor but persistent irritation.

[irecord.org.uk_Archive [22-04-16 12-39-32].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/8499839/irecord.org.uk_Archive.22-04-16.12-39-32.zip)

**Comment by johnvanbreda** [comment]
Now fixed. There was an attempt to only load a row if not already loaded, but when the grid re-populates after a filter it did not clear the last loaded row info so assumed it was already loaded if you clicked on the same row ID again.
