### ISSUE TITLE
Missing date values are not being highlighted

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1116]
If you try to enter a record but forget to fill in the date, the message pops up to say that values are missing, and that the missing ones are highlighted. However, if the date box is not filled in, it does **_not_** get highlighted (at least not for me using Firefox) and this seems to have misled at least one or two other users in the last few days.

**Comment by johnvanbreda** [comment]
Due to the extra complexity of vague & non-vague date control interaction. Should now be sorted.
