### ISSUE TITLE
UKBMS records linked to wrong account

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1117]
This relates to UKBMS transects from 2013 and it may be impossible to find out what originally happened, but a user reports that a set of occurrences are showing as part of his account, even though he had nothing to do with them.

The occurrences have ID numbers 637000 to 637006 and are for the Butterfly Lane (Trewartha, St Ives) - S1 transect, dated 27/09/2013. The recorder name is provide, but that name is not the name of the user account to which they are linked, and also the parent sample is linked to a different user than the occurrences are linked to.

So something appears to have got scrambled here.

The parent sample has ID 306425 - there are several child samples.

The parent sample was originally entered by user ID 20277, and subsequently edited by Ian Middlebrook at BC, user ID 18532.

The occurrences are showing as having been created by user ID 235, but that user has no connection to these occurrences.

It's presumably best to link the occurrences and samples back to user ID 20277.

**Comment by johnvanbreda** [comment]
I've updated the created_by_id field on the occurrences and inserted work queue tasks to update the report tables. The samples looked OK.

Unfortunately these records predate our audit logging module so I have no way of seeing what happened.
