### ISSUE TITLE
Cookie popup

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#112]
It would be nice to disable the second cookie popup confirmation banner. Both the first and the second banner fade out **very** slowly.

![image](https://cloud.githubusercontent.com/assets/7383162/20304793/0efd3fec-ab2a-11e6-8167-a9d9fe6ab063.png)

**Comment by kitenetter** [comment]
I haven't experienced this recently so am assuming that it is no longer an issue, but let me know if it is - closing.
