### ISSUE TITLE
Change to website agreement does not remove records from verification view

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1120]
For website 118, updated the website agreement to remove sharing with iRecord for verification/data flow etc.  update ~13th July.

but records still appearing for verifiers.  Confirmed by masquerading as user = https://www.brc.ac.uk/irecord/user/68 and viewing all records.  Some records showing from ~23rd July.

**Comment by johnvanbreda** [comment]
iRecord still uses the method of Elasticsearch authentication where an alias is configured on Elasticsearch that contains a hard coded list of website IDs. I've updated this alias to fix this issue.

In the longer term we can switch to a newer way of doing this that uses the warehouse REST API to apply the appropriate list of website IDs to the request. I can switch at any time but would prefer to save this for a quieter point in time in case any support requests arise from it.
