### ISSUE TITLE
Problems with notifications for Bloomin Algae

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1122]
User ID 68593 reports:

"For some reason, some records repeatedly email me with notifications like the ones below. These are happening roughly every hour and they are filling up my inbox! The records seem to start doing these after they have been verified by someone and it seems to be a particular issue when they are considered ‘plausible’. Please could you take a look and see if there is an incorrect setting on my account or something else causing this – it’s driving me a bit crazy!"

Example of multiple notificatons:

You have the following new notifications.

From | Record ID | Message | Record status |  
iRecord | 21160554 | A record of Cyanobacteria at 54.546N, 3.073W on 2021/07/23 has been entered. | Awaiting review |  
iRecord | 21160554 | A record of Cyanobacteria at 54.546N, 3.073W on 2021/07/23 has been entered. | Awaiting review |  
iRecord | 21160554 | A record of Cyanobacteria at 54.546N, 3.073W on 2021/07/23 has been entered. | Awaiting review |  
iRecord | 21160554 | A record of Cyanobacteria at 54.546N, 3.073W on 2021/07/23 has been entered. | Awaiting review |

**Comment by johnvanbreda** [comment]
@kitenetter can you confirm this issue is now fixed? If so you can close the issue.

**Comment by kitenetter** [comment]
The user reports "All looks good so far, no notifications from that record today!" - closing.
