### ISSUE TITLE
Moth is not linked to correct dynamic attributes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1124]
When entering records of the Horse-chestnut Leaf-miner, Cameraria ohridella, the dynamic stage terms for arthropods are not displayed, so that leaf-mines have to be recorded as "pre-adult".

I can't see any reason why this particular taxon has not got linked properly.

**Comment by johnvanbreda** [comment]
Fixed. There was a redundant version of this name in UKSI which had not been flagged as redundant. The attribute was linked to the correct version, but the search was finding the wrong version first. 

I've also mapped existing occurrences to the correct version of the name.
