### ISSUE TITLE
Map zoom not remembered when adding records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1125]
For some time now, when using Firefox to add records, if I add a record or list at a particular location and then save it, and then go to add another record or list, the map retains the location (i.e. the map is centred on the location of the previous record) but it zooms right out to global level, making it hard to re-locate the next record if I want to choose a nearby location.

I guess there may not be an ideal solution to this, since some users may prefer to have the map zoom out rather than to stay in the same small area, but the zoom right out to global level does seem unhelpful, and I don't think this used to happen.

**Comment by DavidHepper** [comment]
I agree and would go further. My preferred zoom level when entering multi-species records with 100 m grid refs is the most detailed OS map, before it zooms in to aerial photo views. If it would stay on this level I'd be very happy. As it is now I have to wait for the map to display, then zoom out two levels. Example: 
![image](https://user-images.githubusercontent.com/24915271/127868437-25f5006c-6779-4af7-8971-d74594faee0e.png)

**Comment by johnvanbreda** [comment]
Should now be fixed on iRecord.
