### ISSUE TITLE
Does Chrome autofill a location name?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1128]
Some users have said that Chrome is autofilling their home postcode into the Locaton box, even when the record grid ref is correctly specified as being away from home. I can't reproduce this behaviour.

Is anyone aware of any browser settings in Chrome that might result in the location being autofilled?

**Comment by johnvanbreda** [comment]
Do you mean the location input on the casual or list of records forms? I can't see why it would do that and it doesn't do it for me. Also, does it get filled when they initially load the form, or is it offered as a suggestion when they start typing?

**Comment by kitenetter** [comment]
Not sure John, it was an issue that was passed on 'second-hand' by one of the verifiers. I will close this for now, but if it gets raised again I will try to get more detail.
