### ISSUE TITLE
Incorrect tool tip on species filter in explore pages

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#113]
Go to, e.g. Explore > My Reocrds.

Hover over the species filter box at the head of the results table.

A tool tip pops up saying "Type here to filter. Species search. Either enter an exact number, use >, >=, <, or <= before the number to filter for Species more or less than your search value, or enter a range such as 1000-2000."

The tip is inappropriate for the field.

**Comment by johnvanbreda** [comment]
No longer occurs.
