### ISSUE TITLE
CSV import process failing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1130]
A verifier reports:

"The import seems to freeze and you don't know whether the upload has occurred or not. On investigation sometimes the records appear after quite a while, sometimes just some of them upload, and at times none of them upload."

Only one report so far. iRecord in general has been running quite slowly at times in recent days. Are we aware of any specific problems that could be affecting the csv import?

**Comment by johnvanbreda** [comment]
Likely to be caused by a performance issue in the handling of the way that UKBMS saves occurrence data. Now fixed, so please close if OK @kitenetter.

**Comment by kitenetter** [comment]
The verifier who raised the issue has apparently been continuing to import files throughout the day and reports a dramatic improvement from 6pm onwards! So it sounds like this is sorted, thanks. Closing.
