### ISSUE TITLE
Request to merge user accounts between UKBMS and iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1134]
A user of the UKBMS website also has an iRecord account but they were originally set up with different emails. The user has edited their email on the UKBMS website but the accounts are separate in the warehouse.

The UKBMS account has warehouse ID 301088, and on the website is:
https://ukbms.org/user/29593

The email address in the warehouse for the above user is the INCORRECT address, and the user would like all records associated with the UKBMS account to be linked to their iRecord account.

The iRecord account has warehouse ID 170107, and on the website is:
https://www.brc.ac.uk/irecord/user/47244

The email address in the warehouse for the above user is the CORRECT address.

**Comment by johnvanbreda** [comment]
Done. Both accounts now point to 170107 and the records have been combined into this account. It will take a few minutes for Elasticsearch to update.
