### ISSUE TITLE
Digitised site boundary has moved!

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1138]
A few weeks ago I set up an Activity, using a "My sites" boundary that I had digitised for a small site in north-east London. That boundary has been moved and now appears off the west coast of Africa.

Do we know what might have caused this?

**Comment by kitenetter** [comment]
The boundary is listed in my "My sites" as location_id=267892

**Comment by johnvanbreda** [comment]
According to the audit trail and save metadata:
1. You created the location at 11:34pm.
2. You created the associated activity at 11:38pm.
3. You re-saved the location at 11:43pm with a modified boundary, which is the one it has now.

Do you know what you attempted to do in this third step?

**Comment by kitenetter** [comment]
Sorry, can't remember. I may have edited the boundary in an attempt to make it more acurate, but I certainly don't recall shifting it to a different continent! Maybe it's just a one-off glitch, feel free to close if there is no obvious underlying issue.

**Comment by johnvanbreda** [comment]
I've had a quick go at editing sites to see if this happens, but it didn't so will close.

**Comment by robin-hutchinson** [comment]
This seems to have happened again: https://irecord.org.uk/forum/feedback-and-suggestions/problem-site-boundary-georeferencing

**Comment by kitenetter** [comment]
Unable to reproduce. Closing, but please re-open if it occurs again.
