### ISSUE TITLE
Filter by genus not working

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#114]
Refer to http://www.brc.ac.uk/irecord/node/4140
In explore all records, restricting records in the species table using species = Mycena * lists records of this genus indicating they are present in the database. Now use filter on species and lower taxa with a value of Mycena. No records are shown. Add a second genus of Bulgaria and an error is generated saying "Report did not load correctly."

**Comment by johnvanbreda** [comment]
Working now - must have been fixed in a previous commit.
