### ISSUE TITLE
NBN export files not producing SQL alternative

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1142]
In this month's batch of NBN export files there are five that have failed to produce a valid export. Normally I would open the zip files to see the SQL that is needed to generate the data via pgAdmin, but this time round I am unable to open the zip files in order to extract the SQL needed. I get an error message that the compressed folder is invalid.

The five datasets affected are:
![image](https://user-images.githubusercontent.com/16039111/131535516-f017ff73-eec7-4df7-8481-1cbd468d03f4.png)

Marking this one as urgent as I hoped to send the data in time for a deadline of 3 September, but if it isn't possible to fix by then it can wait till next month.

**Comment by johnvanbreda** [comment]
Looking at this now...

**Comment by johnvanbreda** [comment]
@kitenetter the size of these datasets is causing a memory error on the warehouse. Options:
1. We could temporarily ask @BirenRathod to increase the PHP memory limit on warehouse 1, generate the files, then reset the memory limit. 
2. I can see a potential way of removing this memory issue in the code, by switching from using an array to build the results set, to using a pg result object. Although not a huge change, this would impact the core code around reporting in Indicia so I would not want to rush it.
3. I can use the new Elasticsearch export tool to generate the files. 

I have started on approach 3, and the first 2 files are now in the folder D:\Drupal_Backup\dwc-extract-automation\test. If you can spend a bit of effort checking these outputs it would be very useful.

**Comment by BirenRathod** [comment]
@johnvanbreda I have increased that now. Although that is not recommended but server has already equipped with higher memory, so should be fine now. 
If server performance gets compromise, do let me know. In that case I will decrease that to minimum.

**Comment by johnvanbreda** [comment]
@BirenRathod I think you've actually reduced the memory limit from 512MB down to 2MB. The warehouse PHP error log is full of errors like "Allowed memory size of 2097152 bytes exhausted". Earlier in the day the limit was 536870912 bytes.

**Comment by BirenRathod** [comment]
@johnvanbreda Actually I increased with gb instead of just g. I removed b now. so should be fine by now.

**Comment by johnvanbreda** [comment]
Thanks @BirenRathod.

@kitenetter, now that the memory limit has been increased, I've managed to generate all those files OK now. There are also some extractions from Elasticsearch for you to compare when you get a chance.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 

@BirenRathod if needed, we can reduce the memory limit again, as I have now downloaded the files John saved for me.

**Comment by BirenRathod** [comment]
@kitenetter I'm keeping this as it is. This needed for ukbms' people to download their report.
@johnvanbreda If you find any problem or compromise performance, do let me and I will decrease it.

**Comment by johnvanbreda** [comment]
@BirenRathod I will do. I guess it will only make a difference when people are doing huge downloads.
