### ISSUE TITLE
unable to edit user account

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1146]
e.g. https://www.brc.ac.uk/irecord/user/111375/edit
![error](https://user-images.githubusercontent.com/2699478/132989800-8bf9b4e9-364b-4afa-a6e5-532145274974.png)

**Comment by BirenRathod** [comment]
@DavidRoy I just edit & saved details on my user account and found no problem.  This could be one of problem. I checked log and not found any obvious error. If you get problem, let me know.
