### ISSUE TITLE
Problem with records entered via UKBMS WCBS

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1147]
A recorder has been in touch to say that they have entered records for 2021 onto the UKBMS system, as part of the WCBS-BC survey (survey ID 306). In previous years their records have come through to iRecord as expected, but none of the 2021 records have appeared.

In the warehouse, if I look at the cache_occurrences tables, the only odd thing I can see is that all of the 2021 records have a null in location_name, and about half of them have a null in location_id. Both of these attributes are non-null for the earlier years.

Records passing the checks have been auto-verified, but records that don't pass the checks are unavailable to the verification page (just as they are unavaialble in the Explore pages).

The set of records I am looking at is:
`SELECT onf.verifier, onf.output_sref, onf.attrs_json, o.*
FROM cache_occurrences_functional o
JOIN cache_occurrences_nonfunctional onf ON o.id = onf.id
WHERE survey_id = 306 AND created_by_id = 142914
ORDER BY id DESC`

As well as fixing this set of records it would be good to know if the problem is more widespread - I can see records from other users that are also missing their location_name and are not visible on iRecord.

@DavidRoy who should this be assigned to?

**Comment by DavidHepper** [comment]
(Location name is very import to my verifiers of UKBMS dragonfly records. It's a good cross-check for the grid ref.)

**Comment by kitenetter** [comment]
Transferred to https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/251

Closing.
