### ISSUE TITLE
Error reporting when date format incorrect in imported data

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#1149]
If a CSV file is imported using the format "01-Aug-21" for the date format, then there are 2 problems with the way the error reporting occurs:
1. The error is reported as if a required field is missing, rather than a format wrong, e.g. "Please supply a date for your observation.".
2. The error is associated with the sample.date_type field even though that wasn't specifically in the import. The user is unaware that the date type field is implicitly created when they have a date field mapping.

It might be worth supporting this as a date format, as well as fixing these issues.

**Comment by kitenetter** [comment]
Presumably this has been superseded by v2. Closing.
