### ISSUE TITLE
iNaturalist taxon-match problem

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1154]
This has arisen in relation to records of slugs, but may have wider implications for iNat observations that are at subgenus level.

The example is this iNat observation of a slug identified as "Ater-group Arion Slugs - Subgenus Arion - a member of Arion Slugs Genus Arion)":
https://www.inaturalist.org/observations/34374835

On import to iRecord it is getting matched to genus Arion, with no mention of the subgenus:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=22094677

So it is being matched to:
https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0020528104

when the better match would be:
https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0020528105

This causes difficulties for the verifier who does not want to accept the record at genus level but would do so at subgenus level.

Is it possible to link this subgenus name correctly? Is there a wider issue with iNat identifications at subgeneric level?

**Comment by johnvanbreda** [comment]
This record is provided via the iNaturalist API with taxon.name=Arion. The common name is given as "ater-group Arion Slugs" but we don't use that when matching for obvious reasons. But, iNaturalist does include the rank as subgenus in the info provided, so I think we can use that to improve the match. 

We almost certainly need to do a review of the matching behaviour, as iNaturalist doesn't use UKSI it's going to be a bit fiddly I suspect.

**Comment by kitenetter** [comment]
Relates to #1222

**Comment by kitenetter** [comment]
being dealt with under #1222
