### ISSUE TITLE
iNat verification page - map pane does not display well for tablets

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1155]
A verifier reports that when using an iPad, the main verification page displays the map in a shallow but useable window:

![image](https://user-images.githubusercontent.com/16039111/135467233-4b80bb1e-0150-491d-a980-d66641721a5e.png)

However, the iNat verification page squeezes the map pane into an unusably shallow window:

![image](https://user-images.githubusercontent.com/16039111/135467172-c0ed6698-37c0-4157-b033-65f46dd319b0.png)

Is it possible to make the iNat page display in the same way as the main page?

**Comment by johnvanbreda** [comment]
I don't think there is a difference between the 2 pages, its just that there are more unverified records in the iNat grid for this verifier so the grid occupies more space. Maybe we need to plan a better layout for iPad use if we are going to support it properly?

**Comment by BirenRathod** [comment]
I agree @johnvanbreda. This needed once migrated on Drupal 9 as some of them are not comply in it.

**Comment by kitenetter** [comment]
I wondered about that, but the person concerned was sure it was a difference that was specific to the iNat page. I will ask again, But it sounds like something to address when we move to Drupal 9.
