### ISSUE TITLE
Drupal 9 testing feedback part 2

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1156]
This picks up from #1106 and repeats some issues from there that are not resolved (so far as I'm aware).

**General**
- [x] I find the smaller fonts and extensive use of grey (either for fonts or for background shading) hard to read.

**Home page**
- [x] ES failed error on home page - I'm still getting this if I log in as me, but not if I log in as "iRecord support"

- [x] On the home page the "recent sightings" block is empty.

**Default recording forms**
- [x] The Recorder name is defaulting to "Harvey, ". On current iRecord it would be "Harvey, Martin C." (but we want to change this behaviour, see #1027 )

- [x] On the "add a list of records" page, the button for "Remember site details" is blank or nearly so, presumably just a style issue for font colour?:
![image](https://user-images.githubusercontent.com/16039111/135489350-cd0ca90d-2442-49ef-8080-06141acdc0e4.png)

- [ ] I know that @BirenRathod [explained](https://github.com/BiologicalRecordsCentre/iRecord/issues/1106#issuecomment-871382644) that we need to enable wide boxes for use on moblie devices, but I find it very unhelpful for use on a computer:, including the Recorder name and Species boxes on the casual record form, and the Grid ref box on the add a list form.

**Verification**
- [x] if you click on one of the buttons to verify a record, or to query a record, there close or cancel option is not visible unless you hover over it.

**Admin**
- [x] on the [filter set-up page](https://test-brc-irecord.pantheonsite.io/filters/admin-list), there are boxes at the top of the grid to allow you to filter the gird, and if you type in to the boxes it seems to work, but the text that is typed in is not visible

**Comment by DavidRoy** [comment]
@BirenRathod can you look through the other issues that Martin has raised.
@kitenetter can you flag those that are critical to resolve before we complete the migration

**Comment by BirenRathod** [comment]
@DavidRoy I'm already working on it. I have resolved some issues which @kitenetter suggested in top part.

**Comment by BirenRathod** [comment]
@kitenetter I have resolved most of above problems.  Also, at present on verification page, I haven't decreased the font but we will leave that issue based on user review. 

Also, I haven't done anything to submenu bit as I need to think about, how best way to implement that.

**Comment by BirenRathod** [comment]
@johnvanbreda I found one more small problem on below form which is all users attributes display when logged in.
https://test-brc-irecord.pantheonsite.io/species-alert-notifications

![image](https://user-images.githubusercontent.com/5941255/142592273-f92f2ef7-d98b-4c4c-8f5f-3984e058e981.png)

**Comment by johnvanbreda** [comment]
I've fixed that @BirenRathod

**Comment by BirenRathod** [comment]
Thanks, @johnvanbreda.

**Comment by johnvanbreda** [comment]
@BirenRathod were there any items left on this list you needed me to look at?

**Comment by BirenRathod** [comment]
@johnvanbreda No. all sorted.

**Comment by kitenetter** [comment]
I think we can close this one. The only remaining issue that I can see is to do with spacing on the verification page, and I'l add that as a new issue.
