### ISSUE TITLE
Training Mode banner text duplicated and takes too much room

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1158]
I'm seeing the Training Mode banner with the warning text duplicated. The banner box is overly tall anyway due to its large borders and now it takes even more of my precious screen space.
![image](https://user-images.githubusercontent.com/24915271/136910506-8bff50e6-568d-4ad9-a1bf-17952c509ad2.png)

**Comment by johnvanbreda** [comment]
I've fixed the double message, but probably not worth changing the alert styling as the transition to Drupal 9 (with new theme) is pending.
