### ISSUE TITLE
Suppress iNat import of Odonata with any licence more restrictive than CC BY 

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1159]
Please do not import further records from iNaturalist with a licence other than CC0 or CC BY.

Having discussed with my verifiers, we take the view that it's a waste of time verifying records that cannot be used by LERCs and other 'commercial' organisations, as discussed here > https://forums.nbn.org.uk/viewtopic.php?id=7734

(We will make efforts to get the original iNat recorders to make their preferred licence more open than the CC BY-NC default.)

**Comment by DavidRoy** [comment]
What about the BDS' own use of the records, e.g. for trend assessments, 'State of' reports that I would consider non-commercial?  Also, research use is considered non-commercial as far as I'm aware.  So for these uses/users, why not include CC-BY-NC?

(But I agree with the other point of trying to influence license choice at source)

**Comment by DavidHepper** [comment]
Yes, you have a point @DavidRoy but I don't want to burden my verifiers with a load of work that fails to make it to NBN-A within our dataset, even if it can be used for research purposes. We are resolutely **CC BY**. 
Besides, although iNat observations are licenced per-record, in iRecord's **Verify - iNaturalist** page the **Licence** attribute can't be selected as a column so can't readily be filtered on. 
I have a separate issue #1170 requesting a per-record Licence field for observations in iRecord.

**Comment by kitenetter** [comment]
@DavidHepper the datasets that go to NBN Atlas can include individual records with a CC BY-NC licence even when the dataset as a whole has been given a CC BY licence - in such cases, records are flagged by NBN as CC BY unless there is a different licence attached to any individual record within the set. This is what we do with many of the datasets we send direct from iRecord to the Atlas. So BDS could still supply a dataset that is very largely CC BY but includes the NC records as well, which would make them available for use in appropriate contexts.

**Comment by DavidHepper** [comment]
We remain resolutely CC BY. I am advising my verifiers that they have a free choice as to whether they verify all, any or none of the iNat records. For this, it is helpful having them on their own Verify page. 
It would even more helpful to be able to select attribute 'Licence', currently visible only in Record Details, in the **Column configuration** pop-up of **Verify - iNaturalist**, allowing verifiers to select only true open data records to review, if they wish. I assume this shows the iNat Observation License, not the Photo License. We are not bothered about the Photo Licence since no media reaches NBN Atlas.

**Comment by kitenetter** [comment]
Filtering by micence type now available. Closing.
