### ISSUE TITLE
Search for species names beginning Ae

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#116]
Because of the way the species name simplification works, searching for names beginning Ae does not work, for example Aesculus hippocastanum. They are not found unless you search for *sculus hippocastanum.

**Comment by kitenetter** [comment]
Additional info from @JimBacon -

When searching for a species with name beginning 'Ae' the request is being mangled and the 'Ae' is being rewritten as 'E'. Thus, if I type 'Aepo' the list of suggestions are actually for letters 'epo'. This then fails to match the desired entry in the database.

In cache_taxon_searchterms there are 771 entries meeting the criteria

original like 'Ae%' 
and searchterm not like 'e%'
and taxon_list_id = 15
and preferred = true
which will not be found. (On the other hand, there are 9 which do have a searchterm beginning with 'e' which could be found.)

Refer to http://forums.nbn.org.uk/viewtopic.php?pid=26093

**Comment by JimBacon** [comment]
Thanks. I've posted in the NBN forum to say that this has been fixed.

**Comment by kitenetter** [comment]
This issue seems to have arisen again - searches for names starting with or including "ae" mostly fail, at least when done via the '2+3' abbreviated names.

**Comment by johnvanbreda** [comment]
Just tested after deploying fix for #231 and this seems OK to me now.
