### ISSUE TITLE
Red 'x' icon ambiguity in 'Edit record' 

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1163]
If a Rejected record that is part of a multi-species list (sample) is opened in Edit mode, two red 'x' icons are shown beneath 'Species'. The left one is a button whereas the right one is an indicator that the record has already been rejected. 
![image](https://user-images.githubusercontent.com/24915271/137002824-6c8fe671-20b2-4d8b-805b-16ba3f5013ab.png)

Could the 'button' icon be made to look more like a clickable button? And/or given a slightly different icon.

**Comment by kitenetter** [comment]
Agreed - I think the trash can icon is a good choice for the delete button.
