### ISSUE TITLE
Verifiers receiving multiple notifications of records to verify

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1164]
A couple of verifiers have reported that they are receiving regular notifications of records awaiting verification, but when they log on they are not seeing any.

Can @johnvanbreda let me know how these notifications behave for the iNaturalist records - if a verifier has recording comning in frm iNat will they be notified as awaiting verification? In other words, do we treat the iNat records any differently in the notifications, or will any incoming record trigger a notification?

We may need to change the wording and links in the notification email (the link currently goes to the main verification page, which could be misleading if the notification arises from the iNat records).

**Comment by DavidHepper** [comment]
Just to be clear: the empty notifications issue has been around far longer than iNat imports. I had an idea that it could be due to Training Mode records but can't remember whether this was investigated.

Is it really necessary for iNat to have its own verify page? Won't this continue to throw up anomalies elsewhere in iRecord?

**Comment by johnvanbreda** [comment]
@kitenetter I can configure it to also send a verification notification to the correct iNaturalist page, but this won't stop it also sending the iRecord notification incorrectly. There will be 2 notifications for an iNaturalist record, only one of which is to the correct page. Therefore we need to do a bit more work on the underlying code to properly separate the notifications to the respective pages - a few hours I think.

**Comment by kitenetter** [comment]
I agree that we do need to separate these out so that the notifications are clearer.
