### ISSUE TITLE
Some border-straddler records only assigned to one VC

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1167]
Record 20545240 has a map ref of SU790624 which is ambiguous between N. Hampshire and Berkshire (due to the complexities of the border) but has only been assigned to N. Hampshire. It was originally entered in the App, apparently by grid ref, not lat-long. The map shows a blob on the Berkshire side of the river. 
Are records from the App treated differently to those from Desktop iRecord? To test this I entered Training Mode record 22823162 for the same square and it was assigned to both VCs, as expected.
Have I misdiagnosed something about the original record?

**Comment by DavidHepper** [comment]
I don't follow the implications of these two options and am happy to leave it to your choice, so long as this obs, for example, would be assigned either to the 'correct' VC (Berks) or to both. Whichever you chose, and please say which, it is readily explained to my verifiers.

**Comment by kitenetter** [comment]
@DavidHepper I don't think we know that Berkshire is the correct county do we? The precise point of the record (if we ignore the uncertainty) is in North Hants, albeit by a very short distance. So I think it makes sense to link the records to both VCs. 

We will review John's options for handling the app records and find a solution.

**Comment by DavidHepper** [comment]
Agreed.
