### ISSUE TITLE
Set of records to be marked as "Unable to verify"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1169]
A set of records from the "Capturing Our Coast" project is being supplied direct from iRecord to NBN Atlas. On the Atlas, 104 records of the taxon _Patella depressa_ have been queried, and Jane Delany of CoCoast has agreed that they are incorrect. However, she has not updated their verification status, and I am unable to do anything since this project only shares for dataflow, not for verification.

So the request is to do a database update on the 104 records in the attached file. Updates required:
1. Verification status to be set to "Not accepted: Unable to verify"
2. Verification comment to be added: "Outside the known range for this species."

This is probably best done using the iRecord support account if possible, but that isn't essential, and any admin account would do.

I've assigned John but let me know if this is outside your remit (not sure if you still have any work with the CoCoast project?).

[patella_depressa_delete.zip](https://github.com/BiologicalRecordsCentre/iRecord/files/7443365/patella_depressa_delete.zip)

**Comment by johnvanbreda** [comment]
I don't support the project anymore, but it was only a small job so I've done it.
