### ISSUE TITLE
Records not appearing in verification grids

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#117]
Initial report by email from Matt Smith.
> Is there a problem with the iRecord verification grids at present?  While Stuart and I can see aculeate records arriving via the home page, when we look at our verifcation grids they are all blank, with no records visible.  This applies to all the various iRecord defined filters at my end.  I can see some historical data by using some of my "find old stuff" filters, but even that seems somewhat truncated with nothing recent showing.
> Can you have a look into this for us please.  I noticed it on Friday and have had empty grids ever since.

Additional information from David Roy
> I setup some test verification filters (for both my account and Matt’s) where I knew there was some data that should appear. All were blank.  I looked at an account with a single verification filter (i.e. no ‘contexts’) – Nick Adams – and this worked as expected. I wonder if that is  clue.  It may be a problem for users with multiple verification filters and therefore use a drop-down list of ‘contexts’ in the verification system.

Additional information from Martin Harvey
> If I log on as me and go to my verification page I can see all my Berkshire moth records okay, but if I use the Context box to switch to soldierflies it tells me there is no data.

> This may be entirely unrelated, but at the weekend I was doing demos of iRecord and we had a few problems when using “Explore – All Records”. What seemed to be happening was that having chosen a county filter (or having accepted the default county filter in the user profile), if we tried to change the filter to a different county the new county boundary would be displayed, but the dots for records remained filtered by the old county.

**Comment by JimBacon** [comment]
To relieve this problem in the short term, the media submodule has been reverted from v1.20.1 to v1.18.1 and the client_helpers submodule has been reverted from v1.20.2 to 1.19.1

**Comment by JimBacon** [comment]
After capturing some of the queries and looking at the parameters in the ajax requests to populate the grids it is apparent that the problem stems from filter settings from the first-loaded context being preserved and applied on top of settings from subsequently chosen contexts.

For example, when Martin loads the verification page a context filter limits records to the taxonomic group, insect- moths. After switching to the soldierflies context filter, records are limited to a number of fly families but the filter on moths also persists. No records are shown as none can ever satisfy both criteria.

**Comment by JimBacon** [comment]
The commit https://github.com/Indicia-Team/client_helpers/commit/2d10f916739cb28389aff58e29c822bee6c3ebb6 is the cause of this problem. It adds any initial context parameters to the extraParams of the grid.

When the context is subsequently changed applyContextLimits() in reportFilters.js adds the new parameters (that are not empty) to indiciaData.filter.def in an array with keys `param +'_context'`.

applyFilterToReports() in reportFilters.js merges the new context with a copy of the extraParams set by the commit above.

There are two problems perceived.
1. The context filters stored in extraParams by PHP do not have the '_context' suffix so they are not overwritten by the new context.
2. Since only the new context parameters that have a value get added, original values that are not present in the new context will be left behind.

**Comment by johnvanbreda** [comment]
@JimBacon I've applied the 2 above fixes. Are you happy with them before I apply to live?

**Comment by JimBacon** [comment]
That is the sort of thing I would have done except that, in the JavaScript, since the comment on the preceding lines is 
>  store a copy of the original params before any reset, so we can revert.

I would not have felt I could then delete items in origParams.
Is this safe in all cases?

**Comment by JimBacon** [comment]
If I masquerade as Martin Harvey and go to the verification page I get an unexpected report parameters form appearing with the revised client_helpers code. That suggests these parameters were previously supplied but are not any longer. The records returned in the grid are different too.

![image](https://cloud.githubusercontent.com/assets/2545390/21144331/204f03e2-c142-11e6-8136-cb3c5c6268d0.png)

**Comment by JimBacon** [comment]
Is there ever a case where a context filter is loaded with a page but there is no drop-down list allowing the user to select another? That could be a case when you would not want the context to be deleted from the origParams.

**Comment by johnvanbreda** [comment]
Yes, it is safe to delete the context parameters because when call the applyFilterToReports() method it always calls applyContextLimits to the filter definition. Therefore it always applies a fresh context filter if there is one. I agree though that the code is a bit confusing so I'll refactor and recomment a bit to make it clearer and neater.

When there is only 1 context filter, although there is no drop down for choosing a context filter, the single context filter still exists as a hidden and still gets applied to the filter definition. So I think that is OK.

Was your test on Martin's verification page which resulted in the additional report params done on the live iRecord or dev? On my local development environment I can't see this behaviour.

**Comment by JimBacon** [comment]
My test of Martin's page was on my local copy of iRecord connecting to the live warehouse.
Using Git to switch between client_helpers 1.20.3 and 1.19.1 caused the report params to appear and disappear. Let me look a bit closer in case it is a local issue.

**Comment by JimBacon** [comment]
I'm getting a bit bleary from trying to read code. I think we may have revealed a bug in the warehouse code.

What I have done is to visit the verification page and capture the ajax request for the table of data. It looks like the following, edited slightly.

```
http://warehouse1.indicia.org.uk/index.php/services/report/requestReport?report=library/occurrences/filterable_explore_list.xml
&reportSource=local
&mode=json
&view=list
&location_list_context=
&indexed_location_list_context=
&smpattrs=&
occattrs=&
default_input_form=enter-record-list
&expertise_location=
&expertise_taxon_groups=
&expertise_surveys=
&user_id=50
&quality=P
&knownCount=39176
&sharing=verification
&quality_context=all
&taxon_group_list_context=114
&site-type_context=15
&imp-location_context=733
&sref_system_context=OSGB
&indexed_location_id_context=733
&remembered_location_name_context=Berkshire
&offset=0
&limit=31
```

If I request that in my browser I can get a JSON response which I can examine.

If I now edit the request and change `&indexed_location_id_context=733` to `&indexed_location_id_context=733` I am thinking I might get the same response, having only changed a context filter in to a normal filter. The results are different. If I capture the queries the where clause includes `o.location_id_vice_county in (733)` in the latter case only.

I.e. An indexed_location_id_context parameter seems to go unhandled.

A certain amount of guesswork on my part there as to how I think it works.

**Comment by johnvanbreda** [comment]
I think the problem with the above is that you are using the indexed_location_id and indexed_location_id_context parameters which are legacy parameter names provided for backwards compatibility. They are internally converted to indexed_location_list(_context) which is the same parameter but it uses an in (*) clause to allow multiples. In your request, you have &indexed_location_list_context= which will be preventing the legacy parameter from working.
I am therefore more interested in why your query has both the legacy and the updated version of this parameter.

**Comment by JimBacon** [comment]
It seems to be taking me forever to make sense of this. 

It is the call in get_form() of verification_5.php to report_helper::report_grid() which results in the report parameters being requested.

- The report_helper::get_report_grid_options() wraps the $filterParamsToApply in to the extraParams. These are the untranslated parameters read out of the database.
- In report_helper::request_report(), everything in extraParams is added to paramsFormExcludes to indicate to the warehouse that none of these parameters need to feature in a parameter request.
- When there are paramsFormExcludes the parameter request is for the expectedParams minus those excluded (see ReportEngine::complileReport())
- The expectedParams uses the new parameter names.
- The outcome is that the new parameters appear not to have been provided so they are requested.

It is the presence of the report parameters form which results in the incorrect Ajax request.

The Ajax request is composed of 
 - parameters passed in from the extraParams in php which use the untranslated names read out of the database.
- parameters passed in from the requested parameters input form.
(See jquery.reportgrid.js getUrlParamsForAllRecords())

If the initial problem is fixed the latter problem will go away.

**Comment by johnvanbreda** [comment]
@JimBacon I can see your reasoning behind the issue relating to untranslated vs translated parameter names. Therefore Martin's verification account shows the problem because it contains a filter based on the legacy parameter names which explains in part why I couldn't see the problem. 
However I am still at a loss as to why you are getting the parameters form at all. The code shows that both parameters you are seeing on the params form have in fact got empty defaults (https://github.com/Indicia-Team/warehouse/blob/master/application/helpers/report_standard_params_occurrences.php#117) which means they should never be requested as parameters, no matter what you supply in the request.

**Comment by JimBacon** [comment]
We might be nearly there. As you say, both those parameters have empty defaults but those default values are never merged in to the list of defaultParamValues.

This could happen in XMLReportReader_Core::loadStandardParams() by looping through $params or, as has been done for the OperationParams, the defaults could be duplicated in to report_standard_params_occurrences::getDefaultParameterValues().

Never too happy to see the same information duplicated in case they become inconsistent copies.

We mustn't forget samples in the solution.

**Comment by johnvanbreda** [comment]
Ok, I think I've got an understanding of this now. I suspect this is pretty much what you were trying to explain but I've rewritten it in my words to help me understand it.

1. Martin's context filter contains location_id="" and indexed_location_id=733. These are legacy versions of the parameter names - the current version would be location_list="" and indexed_location_list=733.
2. In XmlReportReader.php, around line 827, you can see that if one of the standard parameters has a value provided in the request, that parameter gets added to the reportReader->params. Note that these are the translated names, i.e. location_list and indexed_location_list.
3. reportReader->params forms the basis of the $expectedParams variable. 
4. When the ReportEngine.php file fills in the providedParams, it uses the supplied untranslated parameter names. Therefore when comparing the expected params with provided params there is a mismatch.
5. There is a second issue here - the default parameter values which get loaded into the providedParams before the comparison come from the defaults supplied in the report files, but ignore the defaults supplied in the standard params defined in code.

Fixing either 4 or 5 will prevent the issue - I'll work on a hotfix for both.

**Comment by JimBacon** [comment]
In my most recent debug session I'm not so sure I saw a problem arising  out of points 2-4 but can't say why not without diving in again.

The overwhelming problem was around line 286 in ReportEngine.php
```
      $includedParams = array_diff_key($this->expectedParams,
          array_fill_keys(json_decode($this->providedParams['paramsFormExcludes']), ''),
          // never ask for params with defaults in the params form.
          $this->reportReader->defaultParamValues);
```
Here, from memory, expectedParams is in translated names, providedParams['paramsFormExcludes'] is in legacy names so there is a mismatch, and defaultParamValues does not save the day because it does not contain the default values of the standard params.

**Comment by johnvanbreda** [comment]
Thanks Jim. After further trudging through the code I think you are right. I've submitted a patch with a pull request for your consideration.

**Comment by JimBacon** [comment]
Good work. I have accepted the pull request and merged in to master and develop. Will now update warehouse.
