### ISSUE TITLE
Request to store Licence type with each record

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1170]
I've just had a run-in with a well known LERC records manager over iRecord. Most of his complaints are spurious but one to be considered is that iRecord does not store a licence type with each record. I appreciate that adding it now would be troublesome but otherwise we may have to request deletion and loss of blocks of records imported from third party sources. We could discuss further offline if you prefer.

**Comment by johnvanbreda** [comment]
Just to note that the Indicia toolkit does support licencing at either record or media level. We could enable licence as a field available when importing and could apply a licence retrospectively to any particular datasets. We could also consider allowing users to select their records licence.

**Comment by kitenetter** [comment]
We could do all this, but personally I think it is fraught with unintended consequences. @DavidHepper please could you email me with some more info, e.g. examples of why datasets might need to be deleted.

**Comment by DavidHepper** [comment]
Will do.

**Comment by DavidHepper** [comment]
We intend to review with the verifiers and trustees our whole approach to 3rd party data. This could take some time. I'll try to avoid proposing again the need for per-record licencing.
