### ISSUE TITLE
"Finer grid ref" field missing from vascular plants form

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#1171]
See here for screenshot of how it used to be: https://bsbi.org/wp-content/uploads/dlm_uploads/iRecord_BSBI_poster_v2_A1.pdf

Page affected: https://www.brc.ac.uk/irecord/enter-vascular-plants

**Comment by sacrevert** [comment]
Not sure how realistic it is to fix this, but presumably it is a small job? Would be good if we could, as we are currently advertising the Species forms on the front of iRecord, and this is an essential feature for plant grid recording @kitenetter @johnvanbreda @DavidRoy

**Comment by kitenetter** [comment]
The grid ref column is still present in the grid on the dev version of iRecord, and in the Drupal 9 test version. I don't know why it has gone mising from the live site. And I don't know how to get it back, so I think this will need input from John.

**Comment by johnvanbreda** [comment]
@sacrevert This should now be fixed.

**Comment by sacrevert** [comment]
Many thanks @johnvanbreda !
