### ISSUE TITLE
Odd multiplication of records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1174]
User ID 234964 has added a record of Phytomyza ilicis, with record ID 23093654.

However, in the verification view there are now 221 further copies of what appears to be the identical record. All 221 are showing as having been entered by a user who was not logged in, but they all link to the same user's email address. That user was not aware of having done anything that could lead to this duplication.

Does this indicate a wider problem?

Are there any questions I need to ask the user in order to investigate further?

**Comment by johnvanbreda** [comment]
This seems very odd. The first record  was entered by user ID 234964 at 2021-11-11 11:40:19. Then, a few seconds later, records started being added every 2 seconds or so, with identical details, for a few minutes. The only difference is the created_by_id was set to 1 (the admin account) and the input_form was set to cairngorms/bgwg (the first record was enter-casual-record). Do you know what this input form path relates to? I've never heard of it and can't access the relevant page.

**Comment by kitenetter** [comment]
I've had two further reports of these duplication issues, another from the same verifier as above, and then from a second verifier in a different taxon group, but all relating to user ID 234964 (but the duplicates continue to appear as non-logged-in records).

I don't yet have the record IDs for the second instance, For the third instance it is:
"The records are 23161623 to 23161794 inclusive. I have rejected them all except for '794."

**Comment by kitenetter** [comment]
@johnvanbreda should we investigate this further, or is it best to proceed to deleting the duplicates and monitoring to see if it happens again?

I will define which records need to be deleted.

**Comment by johnvanbreda** [comment]
@kitenetter it would be good to try and reproduce this error, but unless we can reproduce it I'm not sure where to start. I wonder if, as all the problems stem from one user, they might have malware or a rogue plugin in their browser that is causing re-submission of form data. That's a long shot I know, but I can't think of any other reason.
