### ISSUE TITLE
Enable importing of record-level licences

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1177]
We have an attribute "sample:fk_licence" for a licence to be attached to records. However, at the moment this is failing to import some of the text-string licence names (in part due to incorrect handling of quote marks).

Following discussion with @johnvanbreda I think the best option would be to enable the import of the standard abbreviations for the licences, so that the import process would accept any one of these values:
- CC0 [Creative Commons "No Rights Reserved"]
- CC BY [Creative Commons Attribution]
- CC BY-NC [Creative Commons Attribution-NonCommercial]
- OGL [Open Government licence (UK)]

Note the use of a hyphen in "BY-NC" but not anywhere else!

We also have the following options that can be applied to photos, but these are not relevant to records and should ideally not be allowed as an option for importing into the record licence attribute:
- Creative Commons Attribution-ShareAlike
- Creative Commons Attribution-NoDerivatives
- Creative Commons Attribution-NonCommercial-NoDerivs
- Creative Commons Attribution-NonCommercial-ShareAlike
- ARR [All Rights Reserved]

**Comment by johnvanbreda** [comment]
Done in develop branch

**Comment by DavidHepper** [comment]
Am I right that we should encourage importers to add a licence holder name, in addition to the licence type? I don't think just adding the type would satisfy some of the organisations whose records we import. The name could go into 'Survey Reference Code' that already exists in the 'DRN dragonfly imports' survey definition, alongside the record identifier from the source system in 'External Reference' (if available).

**Comment by kitenetter** [comment]
@DavidHepper if it helps for your purposes to use the 'Survey Reference Code' then that is fine. However, the current Indicia data model treats each licence as a record-level licence. If a particular organisation needs to control a dataset-level licence that needs to be done by them setting up a new 'website' partition within the data warehouse, which will give them control over the way in which records are licenced and shared throught the system.
