### ISSUE TITLE
iRecord down for all users?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1179]
iRecord is showing "The requested page "/irecord/verification" could not be found. " for all users since at least 17:30 this evening.
Could this be related to the Pantheon problems being logged elsewhere?

**Comment by kitenetter** [comment]
@DavidHepper My understanding is that this is a temporary issue while the new site gets properly linked to the original URL.

**Comment by DavidHepper** [comment]
Sorry. Did I miss a Scheduled Outage notice? I've not told my verifiers. Do you have an ETA for the new site?

**Comment by kitenetter** [comment]
No need for apologies on your part David, but there is a need for apology on my part - I had not realised that today's update was going to result in the site being unavailable for so long, and thus had not sent out a notice. The URL updates are being applied but I don't have a precise estimate for when that process will complete.
