### ISSUE TITLE
Mobile apps are not working

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#1180]
Due to a website redirect, the apps connected to the old BRC domain name can't communicate with the website due to CORS request redirects. This affects numerous apps that use Indicia API and the old Mobile Auth modules.

Looks like CORS doesn't allow a redirect: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSExternalRedirectNotAllowed

Affected apps:
- [X] ~~iRecord App~~
- [X] ~~LERC Wales~~
- [x] ~~Bloomin' Algae~~
- [X] ~~iRecord Butterflies~~
- [x] Asian Hornet Watch
- [ ] + all the old ones linked to iRecord site

**Comment by kazlauskis** [comment]
@BirenRathod when I have originally tested the apps agains the irecord.org.uk, it was redirecting requests to the test-brc-irecord.Pantheonsite.io, is that right?

**Comment by BirenRathod** [comment]
@kazlauskis There was no redirection from test-brc-irecord.Pantheonsite.io.

**Comment by BirenRathod** [comment]
Also, no redirection added on irecord.org.uk which was on BRC server to test.

**Comment by kazlauskis** [comment]
Can we install a proxy with the old BRC domain to forward the requests to the new site?

**Comment by BirenRathod** [comment]
What is old BRC domain? you means brc.ac.uk/irecord?

**Comment by kazlauskis** [comment]
Yes

**Comment by BirenRathod** [comment]
@kazlauskis That was just a virtual directory. Is this your temporary solution until you make changes in the app? If it is just to let you know that very soon we are going to migrate BRC site to pantheon too.

**Comment by kazlauskis** [comment]
A proxy should be available for all the old apps and to the projects I am not involved in. So we should set up a basic (NGINX?) proxy that would allow these clients to communicate with the new site.

This very moment I am also fixing the apps I maintain so that there will be an update coming out over the next few days when app stores approve it.

**Comment by DavidHepper** [comment]
Please advise recording groups if you're intending to change the domain or path for any part of iRecord. There must be hundreds of links out on the internet and published in user documentation similar to ours, either not working or redirecting to **irecord.org.uk** 
Examples:
https://www.brc.ac.uk/irecord/enter-dragonfly-record?group_id=149&implicit=t
https://www.brc.ac.uk/irecord/import   (this one isn't in the menu system so has to be a full path)
https://www.brc.ac.uk/irecord/verification

**Comment by kitenetter** [comment]
@DavidHepper those web addresses are all correctly redirecting for me. Do they not work for you?

**Comment by DavidHepper** [comment]
Maybe. Let me know when it's safe (including a visual indication of being in Training Mode) and I'll do a more thorough test.

**Comment by kazlauskis** [comment]
I have now released these app updates that should fix the issues:

- iRecord App v5.4.2 
- iRecord Butterflies v2.2.1 
- LERC Wales v5.4.2
- Bloomin' Algae v2.0.7 

The updates are available now on Android but it might take up to a few days for Apple to approve the changes. The app should update automatically for most of the users. @BirenRathod it might be useful to add a note to the website so that users know they should update the apps.

@DavidRoy all the old apps inc. the Asian Hornet Watch will not work until there is some proxy on the website.

**Comment by BirenRathod** [comment]
Thanks @kazlauskis. 

@kazlauskis About porxy bit, what do you want me to set up?

**Comment by DavidRoy** [comment]
Thanks @BirenRathod @kazlauskis

The Asian Hornet Watch app is important to get up and running

**Comment by kazlauskis** [comment]
@BirenRathod for old apps we would need a proxy to that provides the brc.ac.uk/irecord/api routes without any redirects.

**Comment by BirenRathod** [comment]
@kazlauskis close this if it resolved.
