### ISSUE TITLE
Rules Checker and assignment to VC not running

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1183]
Large numbers of records imported imported yesterday are still sitting in the grid with cogwheel status: 'Record not yet checked against rules.' 
Example: 23194257

**Comment by johnvanbreda** [comment]
I've fixed a problem that was blocking things - the records should start to get checked now, but it will take a few hours to catch up.

**Comment by johnvanbreda** [comment]
Closing as this seems to be OK now.
