### ISSUE TITLE
D9 setting up verification filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1184]
On this page:
https://irecord.org.uk/filters/admin-edit

Can we make the "Save filter as" box wider:

![image](https://user-images.githubusercontent.com/16039111/143894003-bbcacc2f-287b-4eb5-9bbf-264be1da5609.png)

It can also be wider on the equivalent filter blocks elsewhere, e.g. on the Explore pages.

**Comment by johnvanbreda** [comment]
Fixed .
