### ISSUE TITLE
D9 button within filter boxes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1185]
When setting up filters several of the parameter boxes use an "Add" button. It is currently displaying as a small blue button within what appears to be a larger grey button. To make the button work you have to clck on the small blue area, which is potentially confusing and the text is very squahsed into the blue box:
![image](https://user-images.githubusercontent.com/16039111/143899488-8c87a2ce-ce97-40dc-b719-4865a50b7adc.png)

Can we make the blue area larger, and perhaps remove the grey box in which it sits?

**Comment by johnvanbreda** [comment]
Fixed. I had to remove some of the theme's styling applied to all buttons as it seemed to conflict with the module styles, so let me know if you spot problems with other buttons.
