### ISSUE TITLE
Error message when saving user accounts

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1186]
I've added the verification role to two user accounts this afternoon, and when I click "Save" I am seeing this error message:

- Array ( [error] => Validation error [code] => 2003 [errors] => Array ( [user_email_notification_setting:notification_frequency] => form_error_messages.notification_frequency.default ) ) 

Do we need to take any action over this?

**Comment by BirenRathod** [comment]
@johnvanbreda I seen this too and David received duplicated notification, see below screenshot. Any connection between them?
![image](https://user-images.githubusercontent.com/5941255/143900761-f9420d7b-a388-4290-a989-89a0cd3658c5.png)

**Comment by BirenRathod** [comment]
@johnvanbreda The error generated from notification_emails module in warehouse when "Administrator" or "verifier"  role activated. 
In my user case when "Administrator" role activated, I got above error but not for "verifier". In most users case, it happens when "verifier" role activated.
While debugging code I found that notification_frequency value is null when permission for mentoring or moderator. due to that user_email_notification_setting.php generate error.

Not sure why is that? so you need to look at it.

**Comment by johnvanbreda** [comment]
On line 97 in the module, there is this:
```php
if (!($value === '' && empty($_notification_emails_existing_data[$sourceType]))) {
```

Are you saying that at this point in the code, if you are adding a new role to the user (therefore there are more options being added to the list of notification types), the $value will be null? If so, then where this code checks for an empty value (`$value === ''`) it could be replaced with `empty($value)`? This line of code might be more logical as:

```php
if (!empty($value) || !empty($_notification_emails_existing_data[$sourceType]))) {
```

Also line 107:
```php
if ($value === '') {
```

should be
```php
if (empty($value)) {
```

**Comment by BirenRathod** [comment]
@johnvanbreda Yes, that's the one. I have updated that code on Pantheon.

**Comment by BirenRathod** [comment]
@kitenetter This has resolved now. please close if that is resolved.

**Comment by kitenetter** [comment]
@BirenRathod I just got the same error message again, as a result of giving the verifier role to a user account:

> Array ( [error] => Validation error [code] => 2003 [errors] => Array ( [user_email_notification_setting:notification_frequency] => form_error_messages.notification_frequency.default ) )

Do we need a further code update?

**Comment by BirenRathod** [comment]
@kitenetter I just did with my admin account masquerade as 'iRecord support' account and I haven't found any error. which user is this?

**Comment by kitenetter** [comment]
It was one of these two Drupal accounts, not sure which:
https://irecord.org.uk/user/48227
https://irecord.org.uk/user/79848

As far as I can tell the verifier role has been applied correctly, I just wanted to check whether the error message was highlighting something wrong with the notification settings.

**Comment by BirenRathod** [comment]
@kitenetter Are you expecting me to check anything?

**Comment by kitenetter** [comment]
@BirenRathod I don't know! When this error message happened before (at the top of this issue) it seemed to trigger a response from you and John, so I was just checking whether a similar response was needed now that the error has reappeared.

But as far as I'm aware no actual problem has been reported by anyone, so if you have no concerns we can close this.

**Comment by johnvanbreda** [comment]
The problem here was that the proposed fixes from 30th November 2021 were applied to iRecord on Pantheon, not the GitHub code. So when the code was refreshed, it overwrote the changes. I've now applied the changes to both GitHub and iRecord on Pantheon so the issue should be fixed.
