### ISSUE TITLE
Problems with accessing the Download page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1187]
This may be related to the way that D9 handles roles and permissions, see https://github.com/BiologicalRecordsCentre/iRecord/issues/1182#issuecomment-981126177

We have a number of roles set up to allow people access to particular downloads for particular projects. If a user has one of these download roles, the download link appears as a submenu under the Explore menu. However, at the moment they are unable to access the main doanload page.

For example, user with warehouse ID = 700 and Drupal ID = 2101 has a role for "Download Gatwick Biodievrsity records". The user can access the submenu for that download role, but is not able to access the main download page from the menu.

![image](https://user-images.githubusercontent.com/16039111/143923388-d56531cd-c7c7-4f69-9114-d280eaa9209b.png)

I'm not sure if this is a problem with the roles, or with the menu behaviour - probably the latter?

**Comment by kitenetter** [comment]
@BirenRathod I know that there are lots of priorities at the moment, but this menu issue is causing problems. Is there an easy fix?

**Comment by BirenRathod** [comment]
@kitenetter I can able to access as Rachel Bicker, see below screenshot.
![image](https://user-images.githubusercontent.com/5941255/144465773-6da9d1b7-20de-4f0c-9b79-3fca21ff9ed2.png)

**Comment by kitenetter** [comment]
The page we need to get to is:
https://irecord.org.uk/downloads

not:
https://irecord.org.uk/download/gatwick-biodiversity

Users need to be able to click on the initial menu to go to "Download records", regardless of whether there is a further submenu item.

**Comment by BirenRathod** [comment]
@kitenetter Permission has been amended, see if you find any problem.

**Comment by kitenetter** [comment]
@BirenRathod that hasn't changed anything, if I click on "Download records" nothing happens.

**Comment by BirenRathod** [comment]
@kitenetter Actually that has changed permission to access actual downloads page. 
And another problem was menu links was not functioning properly which has been fixed now.
