### ISSUE TITLE
View records when not logged in

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1188]
Not sure if I'm remembering this correctly, but I thought that it used to be possible to view the basic details of a record without having to log in, e.g. if you wanted to send a link for an occurrence to someone who isn't an iRecord user.

However, if I try to view a record when not logged in I'm getting an "Access denied" message.

Has this changed with D9, and if so can we change it back?

**Comment by BirenRathod** [comment]
@kitenetter Permission have been implemented now for this. The records is available to view for any users.

**Comment by BirenRathod** [comment]
@kitenetter I reverted it back due to problem seeing home page for not logged in users.

**Comment by johnvanbreda** [comment]
@BirenRathod can you set the Test site up so that it demonstrates this problem?

**Comment by BirenRathod** [comment]
@johnvanbreda Ok I will do that. I'm going to clone test site from live test in five minutes. I hope that is ok with you.

**Comment by BirenRathod** [comment]
@johnvanbreda I have done this, see issue [1193](https://github.com/BiologicalRecordsCentre/iRecord/issues/1193)

**Comment by kitenetter** [comment]
I think I'm correct in saying that the home page issue is now resolved, but it is still the case that records cannot be viewed by users who are not logged in.

**Comment by BirenRathod** [comment]
@kitenetter this porblem records cannot be viewed by users who are not logged in has now been resolved. please close if you are happy.
