### ISSUE TITLE
Add captcha/reCaptcha to iRecord

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#119]
Spam forum posts have become a daily occurrence.  These can be removed, but preventing at source is preferable.

Can the approach now used on UKBMS (www.ukbms.org/mydata) be applied:
- add captcha and reCaptcha modules to the site: this will add the “I am not a robot” checkboxes. 
- add them to are anything the anonymous users can post – user registration (and forum posts?) are the priorities, and omit them for logged in users.

**Comment by kitenetter** [comment]
As far as I can tell there, if I'm logged in as "iRecord Support" any posts that have been marked as spam are still visible (presumably only to admin accounts). The problem being that I can't tell if the user has already been reported as a spammer, and I quite often find that I go through the process to flag them as spammers and only at the end of the process do I get informed that they have already been flagged.

Is there any way of flagging messages or users to indicate that they have already been banned (e.g. by displaying them in a different colour)? Or does a flag already exist and I'm missing it?

**Comment by JimBacon** [comment]
My practise, which I recommend, is to
a. report the spammer
b. delete all their content
c. cancel their account.
You can do all of that from the spam tab on their user page.

**Comment by JimBacon** [comment]
Check these options
![capture](https://cloud.githubusercontent.com/assets/2545390/21433446/be849212-c867-11e6-9dcd-73a1dca42758.png)
Tell it again when prompted
![capture2](https://cloud.githubusercontent.com/assets/2545390/21433454/c4eff79a-c867-11e6-9a05-f411f03e738f.png)

**Comment by kitenetter** [comment]
Jim, if we delete (rather than block) does that open up the possibility that the spammer could re-register?

**Comment by JimBacon** [comment]
When a user registers they are checked against www.stopforumspam.com. If they have been reported enough to hit the threshold they will be barred. Given that likelihood, and the infinite number of emails addresses, I should think they would be unlikely to use the same email twice. Plus it brings some small measure of satisfaction to delete the bastard.

**Comment by JimBacon** [comment]
And I just checked our threshold at http://www.brc.ac.uk/irecord/admin/config/system/spambot
![capture](https://cloud.githubusercontent.com/assets/2545390/21434301/afabe39a-c86b-11e6-822c-879aed59cd71.png)
They don't get a second chance.

**Comment by kazlauskis** [comment]
I would second the reCaptcha. Today most of the forum threads had at least a few spam messages to buy ambien. Haha, iRecord the drug dealers.

**Comment by kitenetter** [comment]
As far as I'm aware we are not currently getting unmanageable amounts of spam in the forums, which I assume means that our current procedures are working well. Closing for now.
