### ISSUE TITLE
Odd behaviour when querying record

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1190]
This has happened a couple of times now. I'm trying to query a record by adding a comment, but while I'm typing the comment a second query window opens up in front of the one I'm typing into:

![image](https://user-images.githubusercontent.com/16039111/144140195-997bcecc-3e30-48ca-ad61-a76d748c3d0a.png)

**Comment by johnvanbreda** [comment]
I've managed to get this to happen once, but can't reproduce it. Is it possible that you double clicked on the query button, or clicked it twice since it took a while to show the popup?

**Comment by kitenetter** [comment]
No, it was definitely a single click. Will try to generate a HAR file next time I'm doing verification.

**Comment by kitenetter** [comment]
Have not seen this again. Closing.

**Comment by Sam-Amy** [comment]
Looks like the examples so far are only when trying to query ones own records. I have managed to both email and comment on the record @robin-hutchinson just had the problem with (which was their own record), and I can see from @kitenetter your example above that this was also your own record.

**Comment by robin-hutchinson** [comment]
I don't think its querying my own records - I was using my iRecord Support account (work email) to query a record made with my personal account (personal email), so iRecord shouldn't know I'm the same person.

**Comment by johnvanbreda** [comment]
I've definitely just reproduced this on live iRecord, when querying other people's records. I think it might relate to navigating through other records in the grid just before landing on a record then clicking the query button, but I'm not sure.

**Comment by robin-hutchinson** [comment]
I think you are right - I created the error for the HAR file by clicking each record in the list, and clicking query, until one record produced the error when I clicked query

**Comment by johnvanbreda** [comment]
Hopefully now sorted.
