### ISSUE TITLE
Difficulties logging in

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1191]
We've had several reports, some from long-term site users, of people struggling to log in since the upgrade. Most of these seem to involve using the "request new password" option, and that failing to work.

None of these accounts are showing as blocked. I'll see if I can get more information about exactly hat is going wrong, but if anyone has any suggestions for how we can investigate this that would be helpful.

**Comment by johnvanbreda** [comment]
I think @BirenRathod has some knowledge of these types of problems, and clearing cookies is a suggested fix?

**Comment by BirenRathod** [comment]
Yes, mostly related to clearing cache from their browser and using a most up to date version of browser should resolve this problem.

**Comment by kitenetter** [comment]
The latest issue was as a result of a user misunderstanding our password reset process. I've added a help page to address this:
https://irecord.org.uk/resetting-your-irecord-password

This leads to a further issue with the reset process that I will add as new. Closing this one.
