### ISSUE TITLE
Annoying cookie agreements

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1192]
Some frustration is being expressed with the messages about accepting cookies. I realise that we have to have a message, but do we have to click on a second message that simply tells you you have agreed to the first one?

**Comment by johnvanbreda** [comment]
There are settings for this module at https://irecord.org.uk/admin/config/system/eu-cookie-compliance/settings. Potentially the thank you banner can be just turned off but there are other potentially useful settings.

**Comment by kitenetter** [comment]
Thanks John. I have turned off the thank you banner - if anyone sees a need to reinstate it please let me know.

Closing.
