### ISSUE TITLE
Site is not appearing mainly home page

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#1193]
@johnvanbreda I found below message from Drupal logs.
Exception: Control ID src-IndiciaEsRecentRecordsBlock is duplicated in the page configuration in ElasticsearchReportHelper::checkOptions() (line 1719 of /code/web/modules/custom/iform/client_helpers/ElasticsearchReportHelper.php).

**Comment by BirenRathod** [comment]
@johnvanbreda This has happened when allowing permission for "anonymous" user. I was trying to resolve this [issue](https://github.com/BiologicalRecordsCentre/iRecord/issues/1188)

**Comment by johnvanbreda** [comment]
Is it possible there is a page somewhere which has a duplicate recent records block on it? I thought this block was only on the home page.

**Comment by BirenRathod** [comment]
@johnvanbreda Some info about "Recent records" on home page.

I have used "recent records" block twice. one for "anonymous" user and one using view permission "online recording". Now, to resolve #1188 issue, I amended the permission to allow "anonymous" user for "online recording". by doing so "recent records" block for none logged-in user produce above error.

**Comment by BirenRathod** [comment]
@johnvanbreda I have now cloned the test site and changed the permission of "online recording" for anonymous users. That means people can see this page https://test-brc-irecord.pantheonsite.io/record-details?occurrence_id=23244301 but not home page.

**Comment by johnvanbreda** [comment]
@BirenRathod you definitely cannot grant the "online recording" permission to the anonymous role - that permission is the main permission used by Indicia code to determine that you are logged in. So, what is happening here is that the Indicia code ends up thinking you are logged in when you aren't, so the 2 copies of the recent records block (left is shown when logged out, right it shown when logged in) both appear at once, causing the crash.

Instead, you should remove the "View access control" and "Permission name for view access control" settings from a page to make it visible to anonymous users.

BUT, if you check the original iRecord, you will see that anonymous users get redirected to a different version of the record details page with slightly less details visible (/record-details/logged-out) and the addition of a login block. So I presume the D9 version should also be implemented this way.

**Comment by BirenRathod** [comment]
@johnvanbreda I changed permission on test site because l checked that permission on /record-details page and not realised that there is another page for logged out users as well. 

About /record-details/logged-out page has got some bug. see below for more details.
Notice: Undefined index: block in iform_record_details_2::get_control_block() (line 836 of /code/web/modules/custom/iform/client_helpers/prebuilt_forms/record_details_2.php) 

& 
TypeError: Argument 2 passed to Drupal\Component\Plugin\PluginManagerBase::createInstance() must be of the type array, string given, called in /code/web/modules/custom/iform/client_helpers/prebuilt_forms/record_details_2.php on line 836 in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 71 of /code/web/core/lib/Drupal/Component/Plugin/PluginManagerBase.php)

**Comment by johnvanbreda** [comment]
Configuration on record-details/logged-out has been fixed.

**Comment by BirenRathod** [comment]
@kitenetter This has resolved now.
