### ISSUE TITLE
Species alert notifications page location not working

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#1194]
On the following page ,the Select Location drop-down no longer works. I haven't used this in a while, but about 6 months ago it was fine, so I can only assume it relates to the Drupal 9 upgrade (but I can't be certain of that)

https://irecord.org.uk/species-alert-notifications

**Comment by BirenRathod** [comment]
@andrewvanbreda do you know which PHP file is it?

**Comment by BirenRathod** [comment]
@andrewvanbreda  & @johnvanbreda I found below error from Drupal log.
Notice: Undefined index: q in Drupal\iform\Controller\IformController->joinGroupCallback() (line 218 of /code/web/modules/custom/iform/src/Controller/IformController.php)

**Comment by BirenRathod** [comment]
@johnvanbreda Sorry my mistake above error is not related the species location popup problem. that is for something else but needs to look at it if find any bug in it.

@andrewvanbreda if I select second option where I got list eventually but taking long to wait about 2 minutes. See below screen.
![image](https://user-images.githubusercontent.com/5941255/144225568-e0b2b747-9c11-4534-9c84-02b01846d2e9.png)

**Comment by andrewvanbreda** [comment]
@johnvanbreda @BirenRathod 
I am pretty sure this page never used to have a location type drop-down actually looking at it again.
I can get the locations to only load if the type is selected first, but then it is showing far more locations than it used to, it seems to be showing every single location on the system.

I think I might at least be able to setup the alert I need knowing this, but something has definitely gone wrong here.

**Comment by johnvanbreda** [comment]
The location type drop-down was a recent addition, but is working on the old iRecord IP address. Looking at the difference between the 2, the old version is loading the locations drop down using an AJAX request with a parameter that just filters location_type_id in (value), whereas the iRecord version has location_type_id in (null, value).

@BirenRathod this seems to originate from line 6184 of the iRecord version of data_entry_helper.php which has an out of date bit of code. Isn't the code supposed to be the latest master branch (plus a few recent patches)?

**Comment by BirenRathod** [comment]
@johnvanbreda As per last communication just week ago, you mentioned that you are going to release new version including all latest changes made in develop branch too. So that is left for you to do it. About branch, I have used the latest release instead of master branch, is it not a the same?

**Comment by BirenRathod** [comment]
@johnvanbreda Sorry my mistake, Just to let you know that I use only master branch.

**Comment by BirenRathod** [comment]
@johnvanbreda Having said that I have now updated code from [drupal 8](https://github.com/Indicia-Team/drupal-8-module-iform) master branch. Strange thing is that I checked every time by running this "git pull" command, it says it has already updated.

**Comment by BirenRathod** [comment]
@andrewvanbreda Select location drop down now works fine.

**Comment by johnvanbreda** [comment]
@BirenRathod 

> Having said that I have now updated code from drupal 8 master branch. Strange thing is that I checked every time by running this "git pull" command, it says it has already updated.

Git lens told me that the line of code in question was not changed for 8 months, so something must have gone wrong when you updated to the latest release the last time, as there are releases of the iform module much later than that. Also - now that you've reverted to master the patches we've been applying are no longer on the server. I will have to go through all the recent changes and re-apply them (I'll make sure they are in develop, then will merge to master).

**Comment by BirenRathod** [comment]
@johnvanbreda yes, please. 
Also, there are two changes made are you going to do that. I can just send you both files, so they should not miss in next release.

**Comment by BirenRathod** [comment]
> @BirenRathod
> 
> > Having said that I have now updated code from drupal 8 master branch. Strange thing is that I checked every time by running this "git pull" command, it says it has already updated.
> 
> Git lens told me that the line of code in question was not changed for 8 months, so something must have gone wrong when you updated to the latest release the last time, as there are releases of the iform module much later than that. Also - now that you've reverted to master the patches we've been applying are no longer on the server. I will have to go through all the recent changes and re-apply them (I'll make sure they are in develop, then will merge to master).

@johnvanbreda  There is no server involve, so which server are you talking about?

**Comment by BirenRathod** [comment]
@johnvanbreda Ahh, ok. Sorry about that. This is bit tricky to keep synchronized with recent changes and indicia Github repo.
I recon please do not change anything on iRecord of Pantheon repo otherwise this problem always be there. 
If you change first on GitHub [here](https://github.com/Indicia-Team/drupal-8-module-iform)], We can pull code from there and add it onto iRecord pantheon repository.

**Comment by johnvanbreda** [comment]
@BirenRathod ah, OK, I've not had that explained to me before. So - this morning I will make sure the latest release of the iform D8 module is fully updated, then let you know.

I think the last few days it was beneficial to be able to quickly push changes, but hopefully that won't be so necessary in future.

**Comment by andrewvanbreda** [comment]
Working now
