### ISSUE TITLE
Species alert notification subscriptions can no longer be seen on My Account page (and can't be removed from user account page either)

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#1195]
iRecord used to show species alert signup subscriptions on the user account page, as far as I can tell this is no longer the case.
This also prevents removal of alerts.

**Comment by BirenRathod** [comment]
@johnvanbreda this is because global $user has got null value in subscribe_species_alert.php

**Comment by BirenRathod** [comment]
@andrewvanbreda I amended code now see if you can see notification on your account page.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Have sent you an email about this with details

**Comment by BirenRathod** [comment]
Thanks, @andrewvanbreda. yes, I have seen that. please ask @johnvanbreda about this. This could be a problem what he might have done or doing for next release.

**Comment by johnvanbreda** [comment]
I'm working on a complete release of the iform module - when ready this should be fixed.

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda

**Comment by johnvanbreda** [comment]
Hi @BirenRathod the iform Drupal 8 module has now got a release 6.12.0. Please can you apply this to dev and test so we can check it before it goes live.

**Comment by BirenRathod** [comment]
@johnvanbreda I will do that. Just to make sure with you that did you get a chance to look the problem of /record-details/logged-out page which I mentioned in this [issue](https://github.com/BiologicalRecordsCentre/iRecord/issues/1193)

**Comment by johnvanbreda** [comment]
@BirenRathod I've fixed the logged out record details page - the configuration had not been upgraded for the AddToAny block. Can you please re-instate the redirection to this page if the user accesses record-details whilst logged out?

**Comment by BirenRathod** [comment]
@johnvanbreda The 6.12.0release has been rolled out on dev and test but not yet on live. Please check it if everything is ok.

**Comment by BirenRathod** [comment]
> @BirenRathod I've fixed the logged out record details page - the configuration had not been upgraded for the AddToAny block. Can you please re-instate the redirection to this page if the user accesses record-details whilst logged out?

@johnvanbreda  what redirection do you want?

**Comment by johnvanbreda** [comment]
@BirenRathod yes, I've given it a quick check and it seems fine to apply to live. Please clear the Drupal cache after (as I've found Pantheon's option to automatically do this is unreliable).

But, the bug in the species alert subscription page that is now fixed is not the same issue that Andrew mentioned. This is because there is a piece of code in the Drupal 7 version of the Easy Login module that has not been converted to the Drupal 8 version (search for species_alert and you will find it in the module file). This code needs to be converted.

**Comment by BirenRathod** [comment]
@johnvanbreda I have released now on live and clear the cache too.

**Comment by BirenRathod** [comment]
> @BirenRathod yes, I've given it a quick check and it seems fine to apply to live. Please clear the Drupal cache after (as I've found Pantheon's option to automatically do this is unreliable).
> 
> But, the bug in the species alert subscription page that is now fixed is not the same issue that Andrew mentioned. This is because there is a piece of code in the Drupal 7 version of the Easy Login module that has not been converted to the Drupal 8 version (search for species_alert and you will find it in the module file). This code needs to be converted.

@johnvanbreda Sorry I can't find species_alert module, Which module list do I need to search?

**Comment by johnvanbreda** [comment]
Not the species alert module - the Easy Login module.

**Comment by johnvanbreda** [comment]
> what redirection do you want?

If you are logged out and you visit record-details?occurrence_id=..., then you need to be redirected to record-details/logged-out?occurrence_id=...,

**Comment by kitenetter** [comment]
Logged-out behaviour is working correctly for occurrence pages - closing.
