### ISSUE TITLE
Minor issue with menu display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1196]
Using Firefox, if I open the Help menu from the Home page, a small part of it is obscured behind the +/- map zoom control:

![image](https://user-images.githubusercontent.com/16039111/144248444-7464b3ae-8d75-4d6e-872f-4de7c669cace.png)

**Comment by BirenRathod** [comment]
@kitenetter This has resolved now. I found similar issues on other indicia pages too where map displays.
