### ISSUE TITLE
Can we simplify the password reset process?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1197]
When resetting a password, users are taken to their user account page, in order to enter a new password. At least one user has found this confusing - they thought they were being asked to re-enter the complete set of user details. Also, the Save button is a long scroll down from the password boxes.

Would it be possible to have a reset page that focused just on the password, with a Save button immediately below?

**Comment by BirenRathod** [comment]
@kitenetter Password reset process made simple. see if find any problem.

**Comment by kitenetter** [comment]
Thanks @BirenRathod that is much easier to use. It has all worked smoothly on my initial test.

I guess we could add the eye button to this as well?

**Comment by kitenetter** [comment]
@kitenetter to update the Help page to reflect this change.

**Comment by BirenRathod** [comment]
@kitenetter it has already added. where ever you see password field on the website, it comes with that icon.

**Comment by kitenetter** [comment]
It didn't appear (in Chrome) when I tested the password reset.
