### ISSUE TITLE
Please add a banner that "iRecord is currently unstable"

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1198]
Please add a homepage banner ASAP explaining that iRecord is unstable because the underlying CMS is being upgraded. 

I'm being contacted by worried recorders asking what _they've_ done to damage the system. Although I've informed my verifiers to go carefully, I can't contact their rank & file recorders. That's your job.

IMO, Drupal major release upgrades never go to plan. There's always downtime and then glitches. A banner announcement seems to me the best way to fess up.

Sorry to gripe. I've held off for a while.

**Comment by kitenetter** [comment]
@DavidHepper thanks for this, and we have added a banner message.

The only reports I've had today are from people who are struggling to log in. Are you seeing other issues being reported? If so, and if you have time, could you let me know, or if you prefer forward the emails to the irecord address.

**Comment by BirenRathod** [comment]
@kitenetter do you need to "Maintenance" title visible?

**Comment by kitenetter** [comment]
@BirenRathod thanks - I don't think it is necessary, and I have removed it.
