### ISSUE TITLE
Verification view becomes messy on smaller screens

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1199]
A verifier who is working on a screen approx. 30 x 20 cm reports that the verification page has become much more messy, with the various windows overlapping each other (similar behaviour in both Chrome and Edge). I also see this if I try to verify on my laptop. Presenting the verification view on a smaller screen is always going to be a challenge, but are we able to improve on this overlapping scenario?

![image](https://user-images.githubusercontent.com/16039111/144296389-cff83bb2-4c13-4554-bfed-1c8f4c2d6e3d.png)

**Comment by BirenRathod** [comment]
@kitenetter Overlapping only happens when you shrink screen and not refresh it.

**Comment by kitenetter** [comment]
Will keep this under review, but hopefully #1203 will help. Closing for now.
