### ISSUE TITLE
Editing a record in iRecord shouldn't change the survey id

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#120]
I submitted a record,
http://www.brc.ac.uk/irecord/record-details?occurrence_id=4375252
through the NYPH app. The record was correctly labelled with 'iRecord | Plant Hunt 2017'

Having edited the record in iRecord (which uses the iRecord App edit form) the re-saved record is now attached to the 'iRecord | App' survey.

This means that NYPH participants can't edit their records on iRecord (as the record is then withdrawn from the Plant Hunt survey).

I think that similar problems also apply to some of the other specialist app related surveys - which also get changed to 'iRecord | App' once edited.

Possibly, as a short term fix, this requires that each app needs it's own survey form in iRecord (even if the forms are otherwise identical apart from survey id) - but ideally it should be impossible to change the survey id of any record, once created.

**Comment by DavidHepper** [comment]
This is really troublesome for Dragonflies, too. If anyone edits a record belonging to a 'special' survey such as 'DRN dragonfly imports', perhaps to adjust the grid ref or edit the comments, the record is reassigned to survey 'iRecord general data'. This either loses or clears the custom fields of the original survey and causes the record to disappear from the grid if the filter specifies the original survey. Data are actually being corrupted! 
Example of a record to which this has happened: 4487115 (originally  'DRN dragonfly imports').
**Fix:** The missing forms are urgently needed.
**Workaround:** As an interim fix, if the original survey form is unavailable, the Edit button should either not be offered or generate a pop-up warning. The record should not be editable with a 'general' form.

**Comment by johnvanbreda** [comment]
I've fixed this so that editing a record will never change it's survey ID.
The forms are still needed of course.

**Comment by DavidHepper** [comment]
Thank you. Do you mean the fix is live now or in a release queue?

**Comment by johnvanbreda** [comment]
I should have linked the commit to this issue so you can check the status of it. Here's the commit:
https://github.com/Indicia-Team/client_helpers/commit/6ee3a16c90736171f7a62bd9567f55bc4eebfd9a
If you follow that link you can see that it has been committed into the master branch which means it has gone live.
