### ISSUE TITLE
Query over website certificate status

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1202]
This comes from a user who is using a Mac running OS 10.11.6 and Safari 11.1.2 and Chrome Version 96.0.4664.55. They say that when they go to iRecord:

> my browsers give me a security warning that "This connection is not private" and "Certificate is not valid"

They have had similar issues with other websites, and have been advised that the problem "requires updates to the OS or firmware (not browser)". The user says that they are unable to update without having to purchase a new computer.

So I don't think there is anything we can do to help, but I just wanted to ask an case anyone is aware of a solution or workaround.

![image](https://user-images.githubusercontent.com/16039111/144472967-12db3f38-b436-4b4a-af5d-731018cfd797.png)

**Comment by johnvanbreda** [comment]
Try clearing cookies @kitenetter?

**Comment by kitenetter** [comment]
Yes, they've been round that loop several times.

**Comment by japonicus** [comment]
This is a widespread problem. A root certificate used by Lets Encrypt has expired and not been updated on various old OS platforms. More info here: https://eclecticlight.co/2021/09/21/el-capitan-and-older-mac-os-x-are-about-to-have-a-security-certificate-problem/

There doesn't look to be an easy work-around for affected users (other than upgrading to a more recent OS version that still receives certificate updates).

It might still be possible to use an old version of FireFox (even though it's unsupported on iOS 10.11) which uses its own up-to-date root certificate store.

**Comment by kitenetter** [comment]
Thanks @japonicus, that lines up with what the user has told me. I will pass on your suggestion regarding Firefox. I doubt there is anything else we can, so am closing the issue.

**Comment by DavidHepper** [comment]
(This is the Mac equivalent to trying to run a browser on Windows XP.)
