### ISSUE TITLE
Use of space on the verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1203]
The D9 verification page uses a larger font and has more white space generally, and we've had several emails from verifiers who are struggling to use it on smaller screens.

As noted previously, on the old site page the distance from the top of the page to the first record was 7cm, and on the D9 page it is now 9cm. If we can lose some of the white space that will help. Can we prevent either of these two rows from being displayed?:

![image](https://user-images.githubusercontent.com/16039111/144478001-8d7b6ec7-647e-4d20-a11a-fcbb8bd8135a.png)

**Comment by johnvanbreda** [comment]
I've optimised the space used quite a bit - removing the breadcrumbs, compressing the menu and header, plus removing some space in the grid and reducing the font. Please close if OK.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda that looks a lot better to me. Closing.
