### ISSUE TITLE
Request to enable password to be visible when typing in

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1204]
A user has asked if we can add an "eye button" that would enable the password to be shown to the user typing it in, to help with accessibility and to make it easier to avoid mistyping.

**Comment by johnvanbreda** [comment]
Maybe https://www.drupal.org/project/password_eye?

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda for your suggestion. I just enabled on my local machine and it doesn't work in general. And I looked at issue and I found this ->https://www.drupal.org/project/password_eye/issues/3154865

So I' testing another module, may view_password?

**Comment by BirenRathod** [comment]
@kitenetter "eye button" added now to password field.

**Comment by kitenetter** [comment]
Thanks - closing.
