### ISSUE TITLE
Unable to add members to an Activity

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1206]
User with Drupal ID 24797 and warehouse ID 117607 is an admin for the Activity "Jesus College Cambridge Wildlife Recording" (group ID 1863). Their activity list is showing a request to join the Activity:

![image](https://user-images.githubusercontent.com/16039111/144604092-564f0f96-0919-4669-bed8-d087906bbb4b.png)

If I masquerade as that user and click on the link for the new member, I get redirected to the Home page.

The user also reports that they  "tried sending a link to join but the person requesting access just gets linked to their home page."

I can replicate this issue when logged in as Martin C., Harvey.

**Comment by BirenRathod** [comment]
@kitenetter The path has got extra subfolder name /irecord which was from old website. I removed it now. so should be working fine.

**Comment by kitenetter** [comment]
Thanks @BirenRathod that is working.

I think there is a similar problem with the "Share a link" button that each Activity has:

![image](https://user-images.githubusercontent.com/16039111/144614827-386a4a11-8250-4578-b229-f3e6bfea27b8.png)

That button calls up another path that has the subfolder name in it:

![image](https://user-images.githubusercontent.com/16039111/144614717-b87c6576-2698-4882-b9ca-91327e0c2d52.png)

**Comment by BirenRathod** [comment]
@kitenetter That has implemented now.

**Comment by kitenetter** [comment]
Great, thanks - closing.
