### ISSUE TITLE
What causes this error message?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1207]
A verifier has encountered this error message:

![image](https://user-images.githubusercontent.com/16039111/144836005-78bddd86-9a83-4367-b7df-78824632008b.png)

I'm not sure which page they were trying to access.

The user has switched to a different browser and things are working okay now, but if there is anything in particular that would trigger the above message it would be good to know.

**Comment by DavidHepper** [comment]
That screenshot is from MS Internet Explorer, which shouldn't be supported, IMO.

**Comment by kitenetter** [comment]
Thanks @DavidHepper that makes sense.

**Comment by BirenRathod** [comment]
@kitenetter This message is from antibot to stop spam submissions. After I migrated site, I noticed some spam submitted in forum. so antibot will stop submitting automatic submission happened via javascript. 
I'm not suggesting this user has submitted spam. but I can see user is using outdated IE which deprecated by Microsoft for security reason. All IE should be on Microsoft Edge.
