### ISSUE TITLE
Where does the People table csv download get saved?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1208]
Biren added a csv download button for the People table here:
https://irecord.org.uk/admin/people

It appears to be functioning, but I don't know where the csv file is being saved. Can anyone tell me?

**Comment by BirenRathod** [comment]
@kitenetter After pressing "CSV" button, you will see progress bar where you need to wait to download data. The process takes about 10 to 15 minutes depends upon internet speed. It doesn't download on the server or Pantheon. It will only download on your machine, once data being prepared in batches.

**Comment by kitenetter** [comment]
I've tried filtering the People table to those with role "regional collator". I then click on the csv download button. A progress bar quickly goes to 100% and then I am returned to the home page. I can't find any downloaded file anywhere on my C drive.

**Comment by kitenetter** [comment]
Tried again today, and this time I got a download link presented to me on the home page, which is fine.

@BirenRathod is it possible to filter the People list so that it only includes people who have a role of some sort? I don't need to download people without a role.

**Comment by BirenRathod** [comment]
@kitenetter I implemented the download now, so you should able to download filtered data.

**Comment by kitenetter** [comment]
This is working for me, thanks - closing
