### ISSUE TITLE
Make message clearer for logged out users

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1209]
This has been raised by several verifiers but may affect other users as well. In most cases the problem arises when a verifier receives a notification email telling that there are records awaiting verification. They click on the link, but then arrive at the "Access denied" page, probably because they have been logged out following the update to D9.

There is a button at the top-right to allow users to log in, but it is not obvious, and is a long way away from the "Access denied" message (at least when using a large screen):

![image](https://user-images.githubusercontent.com/16039111/145592085-67bf6f6f-7794-48c3-a6e0-c67668c3f55d.png)

Is it possible to add a "Log in here" button or link directly under the "Access denied" message?

**Comment by kitenetter** [comment]
This is continuing to cause distress for several of our verifiers.

As a first step, can we adjust the wording, and add a hyperlink, so that it says:
Access denied
Please [log in](https://irecord.org.uk/user/login) to iRecord to access this page

It would also be good if the page redirected back to the verification page following log in.

**Comment by BirenRathod** [comment]
@kitenetter for access denied, I have changed the configuration, so it should not display "access denied" page. instead it will take to user login page where they can logged-in using their username and password. once logged-in, the page will redirected to their desired page.

**Comment by kitenetter** [comment]
Thanks for resolving this one Biren - closing.
