### ISSUE TITLE
Update links in notification emails

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1210]
The notification emails are linking to the old URLs, e.g. the one for verifiers goes to:
http://www.brc.ac.uk/irecord/verification

but should now go to:
https://irecord.org.uk/verification

The ULR should get automatically redirected, and I think this is happening, but it is still causing confusion for users. It would be good to update the email links.

**Comment by kitenetter** [comment]
The most recent query about this arose from a link in an old email, so I'm certain if this remains an issue or not - I will check.

**Comment by johnvanbreda** [comment]
@kitenetter I've changed the URLs in the verifier notifications module's config file on the warehouse.
