### ISSUE TITLE
Maps in 'Verify > Edit record' only show aerial photo at one resolution

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1211]
The OSM map adjacent to the grid can be zoomed happily but in **Edit record** the default 'map' shows an aerial photo with the base layer defaulting to 'Dynamic'. If I zoom using the controls at the top left the broken link symbols appear on the map at all levels except the top three until I zoom back in again. 
![image](https://user-images.githubusercontent.com/24915271/145609910-a2169563-7549-4b0b-be96-3f5be8758bce.png)
Is only one resolution of aerial photo available to iRecord? This may be a problem with 'Ordnance Survey Leisure'.

Example: I'm trying to correct the grid ref of record 23054696 (and ...97) to NM917020 (W. Scotland).

**Comment by johnvanbreda** [comment]
Fixed - standardised map layers were not being applied across the site by the iform_user_ui_options module.
