### ISSUE TITLE
Embedded iFrame activity pages not displaying

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1214]
We're getting reports that iFrame-embedded activity pages are no longer displaying. For instance, if I go to this page:
https://dipterists.org.uk/bee-fly-watch

there should be an iFrame showing the Activity summary for the bee-fly watch project, which is at:
https://irecord.org.uk/external/bee-fly-watch

but it is being blocked:

> Firefox Can’t Open This Page
> To protect your security, irecord.org.uk will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

That message implies that the blocking in being done at the iRecord end of things. Is there anything we can do about this?

**Comment by johnvanbreda** [comment]
Drupal is, by default, protected against using it in iframes for security reasons. This is discussed at https://www.drupal.org/node/2735873. I'm not sure what is the best approach to fixing this on a Pantheon site, maybe Jim might have ideas in Biren's absence?

**Comment by kitenetter** [comment]
Thanks John. @JimBacon let us know if you can see a solution to this.

**Comment by JimBacon** [comment]
The article John has linked to sets out possible solutions. I've no reason to think we couldn't get one to work.

I see the question as more to do with the security issue. If Drupal think it is insecure to allow the embedding of one site in another, are we wise to go against that?

**Comment by johnvanbreda** [comment]
@JimBacon I've sent you an email thread about this issue from a couple of years back.

**Comment by JimBacon** [comment]
Thanks John. Impressive feat of memory to recall that thread.

Additional information from John via email:
https://www.caringforgodsacre.org.uk/get-involved/recording-2/share-your-records/share-multiple-records/ is also affected.

This was reported in September 2019.  That is before the move to Pantheon and Drupal 9. It was attributed to 'a recent server change' without any further elaboration.

**Comment by johnvanbreda** [comment]
"Recent server change" was probably upgrade to the version of Drupal that introduced this security measure.

**Comment by JimBacon** [comment]
I doubt it. It was introduced in version 7.50 which was released on 7th July 2016.

**Comment by kitenetter** [comment]
At least some iFrame embeds have continued to work until very recently (i.e. the bee-fly one linked above was certainly working for most of 2021).

**Comment by JimBacon** [comment]
Perhaps it was fixed back then and has just resurfaced with the move to D9 in that case.

**Comment by JimBacon** [comment]
What next then? If urgent, I guess I am the suitable candidate to try the proposed fix but I am not in the Pantheon team with permissions to the irecord site. @johnvanbreda might be able to add me as he is a team member.

**Comment by BirenRathod** [comment]
@JimBacon I have added now on Pantheon for iRecord.

**Comment by kitenetter** [comment]
@JimBacon I've been asked if we can urgently fix the iFrames on this page, because a BBC feature wants to link to it:
https://www.coleoptera.org.uk/meloidae/home

Is there any chance, or is it going to take longer (in which case I'll remove the iFrames and replace them with links to iRecord)?

**Comment by JimBacon** [comment]
I'll test out the proposed solution in the Pantheon dev environment now and see how it looks.

**Comment by BirenRathod** [comment]
@JimBacon Security kit module available to enable on dev, test & live site now.

**Comment by JimBacon** [comment]
@kitenetter, I have 

- enabled and configured the Security Kit module on the Pantheon iRecord dev site. 
- edited https://www.coleoptera.org.uk/meloidae/home and pointed the iframes at the dev site.

Thoughts

- The iframes appear now and I have not observed any adverse effect on iRecord.
- I don't think the Summary of Oil Beetle Records is showing what you want.
- I don't much like the way the summary includes the iRecord menu - I'd rather it just showed the content rather than the whole page.
- I don't like how you have to scroll up and down the recording form within the iframe.
- I don't like how long the page is.

The proposed solution resolves the issue though. If you are happy then I can propagate this to the live iRecord site.

**Comment by kitenetter** [comment]
Thanks @JimBacon 

It appears we have a wider problem with the "simple summary" form. It is not being correctly filtered, and when I went to check the set-up for this activity it becomes apparent that the simple summary option has gone missing:

![image](https://user-images.githubusercontent.com/16039111/149936471-44a0c9ba-806f-4c18-aca3-a7e38e9e3bc3.png)

There used to be a longer list of options in the dropdown list for adding forms to the activity. This is likely to be affecting other activity users.

If needed the activity settings are at:
https://irecord.org.uk/activities/edit?group_id=1887

I agree with your other points but I assume that the only way to address them would be to prioritise a wider review of how the activity displays work, at least when embedded.

Actions:
- @kitenetter to edit the Coleoptera page to show the full summary rather than the simple summary
- @JimBacon to investigate the missing items from the activity forms dropdown, or else to reassign to Biren

**Comment by JimBacon** [comment]
Editing https://irecord.org.uk/simple-activity-summary and checking 'This page is going to be used by recording groups' has made the simple summary available when editing the group activity and has made the results for https://irecord.org.uk/simple-activity-summary?group_id=1887 look sensible.
<img width="383" alt="Capture" src="https://user-images.githubusercontent.com/2545390/149939807-f89580aa-59f4-4181-a9e1-8175a708c091.PNG">

I don't really know what I'm doing there or whether it has repercussions somewhere else.

**Comment by johnvanbreda** [comment]
That sounds correct to me @JimBacon

**Comment by JimBacon** [comment]
I've propagated the Security Kit set up to the live iRecord site and pointed the iframes to it.

The module, https://www.drupal.org/project/iframe_resizer could get rid of the scroll bars in the iframes if iframes are the best solution. Actually, the activity summary has scroll bars disabled so is truncating content which is possibly even worse!

We could move the summary and the recording form on to their own pages within the Oil Beetle section of the site if that would improve the organisation. 

I suggest we either remove or fix the checklist page as well.

**Comment by JimBacon** [comment]
If other sites are embedding iRecord in iframes then go to https://irecord.org.uk/admin/config/system/seckit and add their urls as illustrated.
<img width="357" alt="Capture" src="https://user-images.githubusercontent.com/2545390/149947101-b9fb9b0f-4aa0-4c4c-8c7e-5e4756411446.PNG">

**Comment by kitenetter** [comment]
Does anyone know if there is a way to find out which other sites are embedding iFrames from iRecord? I can think of a few but there are probably more than I'm aware of.

**Comment by JimBacon** [comment]
I don't think you can. You might just be able to infer something by looking through server logs for urls containing 'external' and  seeing if you can identify the referring site. I wouldn't bother.

I suggest deciding which is the bigger risk to us:

1. Having sites with missing iframes which are so little used no one has reported them or
2. Disabling this security feature and allowing anyone to embed iRecord (which is how it used to be in old versions of Drupal).

BTW, I now realise I have used X-Frame-Options, which is intended to be obsoleted by the Content Security Policy frame-ancestors setting which is also offered by the Security Kit module.

**Comment by kitenetter** [comment]
The original reason for this issue is now resolved (I have removed the iFrames on the Coleoptera website, just in case the BBC link produces a lot of traffic and something goes wrong).

There are a number of glitches still to resolve around the activity pages, which I will get back to when I can.

@JimBacon please close this issue unless there is anything that you are still following up. Will open new issues as needed.

**Comment by JimBacon** [comment]
I note the iframes have also gone from the page at https://www.caringforgodsacre.org.uk/, mentioned above, so nothing more to do here.
