### ISSUE TITLE
"My sites" not functioning

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1215]
The "My sites" part of iRecord is not allowing any records to be viewed for exsiting or new sites.

Also, the map view is showing as a blank pink area if trying to add a new site.

**Comment by johnvanbreda** [comment]
I thought the problem with OS map layers had been fixed, but it seems we've just switched to using the dynamic layer that goes from OSM to Google Satellite, skipping the OS Leisure layer out completely. This wasn't done on the My Sites section so I've applied the same change, but at some point the OS Leisure layer needs to be fixed properly. 

I can't see what you mean by the first sentence about not being allowed to view records though.

**Comment by DavidHepper** [comment]
Pink map probably the same issue as #1211, so not restricted to My Sites or even to 'Edit record'.

**Comment by johnvanbreda** [comment]
@kitenetter I've implemented a general fix for the map layers not being standardised across the site, which includes My Sites. Closing as I think it now behaves as per previous version.

**Comment by kitenetter** [comment]
Thanks John, and you can ignore the first sentence, I was getting confused between display of "My records" and "All records".
