### ISSUE TITLE
Downloads now don't include BDS custom fields, even for a single Survey

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1217]
I'm passing on these comments from Pat Batty, Scotland CDR, regarding downloads but have _not_ myself double-checked the download process since the recent Drupal update: 

> ... I have been downloading separate surveys like I usually do from iRecord. Now you can only choose the standard format and if you download records for iRecord Dragonflies you don't now seem to get all the information on life stages as you could in the past; the only information on species numbers is what is in the comments.
> Also not all the details for the iRecord App data which i again tried to download separately but a few adult numbers are available but also blanks. There doesn't seem to be any life stage [abundance] columns now even when downloading separate surveys.
> Is there a way to get the full format like you could in the past?

_My reply to Pat:_ 
... I'm not supporting downloading from iRecord. It has never been satisfactory. The push for verifications now is in order to update NBN Atlas, from which reliable downloads can easily be made. The download is _so simple_, mostly because the data sent to NBN have been reorganised into a single consistent format. I'm sorry to make you wait.

**Comment by johnvanbreda** [comment]
@DavidHepper I've fixed a configuration error so please can you try the single species download again.

**Comment by DavidHepper** [comment]
Thank for the quick fix, John. I confirm that today a 'Standard download format' download of single survey 'iRecord Dragonflies' includes all the BDS custom fields.
