### ISSUE TITLE
Users unable to access verirfication/explore records

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#1218]
Have just had a report from Ireland of a user who cannot access verification or explore records.

Examining iRecord I notice the "online recording" permission isn't assigned to any roles (there may be other issues)

**Comment by andrewvanbreda** [comment]
(noting although I can see the problem, iRecord isn't a system I normally adjust unless instructed to do so. Also I do not know if there was a reason the permissions have been altered that I am not party to)

**Comment by kitenetter** [comment]
@andrewvanbreda I'm not aware of this being a general problem. Can you let me know the user ID?

**Comment by andrewvanbreda** [comment]
@kitenetter 
This is the user in question, Rose
https://irecord.org.uk/user/19160/edit

My examination of the system would suggest it is widespread amongst non-admin users.
There is no role assigned to the "online recording" permissions.
Also my attempts to masquerade have suggested to me that the issue is widespread.

Maybe I am wrong, but that is what I found.

**Comment by johnvanbreda** [comment]
@kitenetter @andrewvanbreda you are correct - something is wrong here. I masqueraded as someone with verification and no other permissions and they have no explore menu access, and the verification menu items are missing. Will take a look.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - I agree this is a new issue.

**Comment by johnvanbreda** [comment]
I have re-instated the permission "online recording" for authenticated users, and "verification" for verifiers. That has fixed the immediately obvious problems, but as Andrew says, there may be others. Do we know when this issue was likely to have occurred or have any idea why? Are we sure that the permissions were correct after the Drupal 9 migration?

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
So far I only got this message 
"I do not seem to be able to access verify or explore on iRecord this morning, any ideas?"
I will check with Rose if it was working yesterday.

 I THINK I have used Explore Records since Drupal 9 migration....although don't quote me on that.

**Comment by DavidHepper** [comment]
My access seems fine this afternoon but I received this regarding Exports from David Clarke (VCs 69 & 70) this morning at 10:34 - 
"Thanks, I’ll do that as soon as the system is behaving - which it isn’t at present!"

**Comment by kitenetter** [comment]
This is definitely a new issue since yesterday. Explore and verification have been working fine for me (and others as far as I know) since the move to D9. It's working again for mw now, following John's fix an hour ago.

**Comment by kitenetter** [comment]
As far as I'm aware this issue is now fixed. Closing.
