### ISSUE TITLE
Notifications numbers not adding up

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#122]
My home page is currently telling me I have 49 notifications unread, but when I go to Explore - My notifications there is only one visible. Another user had reported that their notifications were showing an old list and weren't updating, but I haven't been able to replicate that.

**Comment by johnvanbreda** [comment]
Count was not respecting training mode. Fixed by https://github.com/Indicia-Team/warehouse/commit/7897f78dae410cdf777cbf3155a6c2ceb2e682f8
