### ISSUE TITLE
Verification filter missing from admin page list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1223]
User Scott Shanks (Drupal ID 1638, warehouse ID 7796) has a role as a verifier. If I masquerade as Scott, the correct set of records is being filtered:

![image](https://user-images.githubusercontent.com/16039111/146359416-96fe2f27-4095-4f17-847a-a0e70f61a0c2.png)

However, he is no longer listed on the filters admin page:
https://irecord.org.uk/filters/admin-list

This led me to think that his role had been lost somehow, but his verification page does seem to be functioning, and the filter can be found in the warehouse, with filter ID 6911.

Why is that filter not showing on the filter admin page?

**Comment by johnvanbreda** [comment]
I don't know why but for some reason Scott's users table entry was marked as deleted. I've undeleted it. This filter now appears in the list.
