### ISSUE TITLE
Question: adding taxon hierarchy to warehouse

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1224]
I need to add genus Anisonema to the warehouse, but this requires adding several levels of the taxon hierarchy above the genus, as they are all new to UKSI:

![image](https://user-images.githubusercontent.com/16039111/146403897-37fce7b8-cc04-4708-839e-d3bac471cfef.png)

Question: should I add all the higher taxa including subclass, linking them via the parent taxa to create the full hierarchy?

**Comment by kitenetter** [comment]
Also, I see there is a new attribute in the warehouse species dictionary: "Organism unique identifier (organism key)". Should I be populating that from the UKSI "ORGANISM" key?

**Comment by johnvanbreda** [comment]
Yes please @kitenetter

**Comment by kitenetter** [comment]
Done for the current batch of additions. Closing.
