### ISSUE TITLE
The irecord.org.uk/app doesn't work

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#1226]
For some reason the app home page doesn't open up and shows the iRecord site.

**Comment by johnvanbreda** [comment]
@kazlauskis are you sure this page ever existed? I can't find it on the snapshot I have available of iRecord from just before the Drupal 9 migration.

**Comment by kazlauskis** [comment]
Yes, the page wasn't part of the Drupal though. https://web.archive.org/web/20211022073657/https://irecord.org.uk/app/

**Comment by BirenRathod** [comment]
@johnvanbreda & @kazlauskis This page was existed in old irecord site but not part of Drupal. Pantheon doesn't support external folder apart from Drupal, so it needs to create new one on Drupal.

**Comment by johnvanbreda** [comment]
Will you be doing this @BirenRathod?

**Comment by BirenRathod** [comment]
@johnvanbreda I will do it but it is not priority at the moment.

**Comment by kazlauskis** [comment]
Does the old page still exist on the old server? Maybe we can do a redirect for this path until this is fixed?

**Comment by BirenRathod** [comment]
@kazlauskis See comments on https://github.com/NERC-CEH/irecord-app/issues/234
