### ISSUE TITLE
Unable to add more than three forms to an Activity

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1227]
On the edit page for new or existing activities, there are three rows that come as standard in the "Group pages" table, with an option to add further forms via the "Add another" button. However, the dropdown list of forms is only available to the three default rows - if you try to add a fourth row the dropdown list is empty.

![image](https://user-images.githubusercontent.com/16039111/148241644-17b31d44-b6b6-460f-adf0-260d37639358.png)

**Comment by BirenRathod** [comment]
@johnvanbreda I found below error when loading edit page.
Notice: Undefined index: termlist_id in data_entry_helper::complex_attr_grid() (line 382 of /code/web/modules/custom/iform/client_helpers/data_entry_helper.php)

**Comment by johnvanbreda** [comment]
@BirenRathod I've fixed both the PHP error and the original problem in the master branch (needs iform module, client_helpers and media sub-modules). Please can you update these onto iRecord?

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda. I have updated code on live iRecord now. Checked everything, works fine.
