### ISSUE TITLE
Incorrect handling of tetrad grid references

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1229]
This has been raised by one of our plant verifiers. The issue appears to affect all tetrad records. An example is this record:
https://irecord.org.uk/record-details?occurrence_id=18088454

The record has been entered with a tetrad grid reference of NU10X. That tetrad is being displayed correctly on the above record page, and being mapped correctly on the map at the above page.

In the verifiers' view of the record (on their main verification page), the grid reference is given as the 10 km square only: NU10. However, the map still shows it correctly as a tetrad:

![image](https://user-images.githubusercontent.com/16039111/148372332-fc671e25-2222-4d37-af9d-fde9aa82a4bf.png)

In the downloaded version of the record, the input grid ref is correctly given as NU10X, but the associated precision is incorrectly given as 10000, and the output grid ref is incorrectly given as NU10.

What do we need to do to ensure that tetrad references are handled correctly?

**Comment by johnvanbreda** [comment]
I've updated the get_output_sref so that it handles tetrads for OSGB references so this should be OK now.
