### ISSUE TITLE
Verification - recorder experience data no longer clickable

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#123]
On the Verify page, in the right-hand panel, there is a tab for "Experience" that shows numbers of records accepted or rejected for the currently highlighted recorder. It used to be possible to click on these numbers and see the records in each category, but that functionality has been lost and the numbers are no longer clickable.

**Comment by kitenetter** [comment]
Not only are these numbers no longer clickable, but they now seem to be summing incorrectly as well:

![image](https://cloud.githubusercontent.com/assets/16039111/22653625/e4e78642-ec81-11e6-95fc-2ca09c8490be.png)

**Comment by MNSmith** [comment]
Could I "bump" this issue please.  When it works it is very helpful in assessing recorder expertise and the lack of this facility is slowing down verification.

**Comment by johnvanbreda** [comment]
Fixed.
