### ISSUE TITLE
Downloads failing for large datasets and/or complex filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1232]
A county butterfly recorder is trying to download records for year 2021, and is getting error messages:

![image](https://user-images.githubusercontent.com/16039111/148555306-5be51e99-9dbf-417c-a09f-c8d8074993b3.png)

I've tried to do the same download via various routes and am encountering the same error.

The download has a filter applied to limit it to 2021 and to exclude UKBMS records. I'm not sure if it is failing due to the size of the download, or to the complexity of the filtering.

I guess this could be related to #1230

**Comment by BirenRathod** [comment]
@kitenetter yes, this could be one reason especially if there are large amount of data associate with it.

**Comment by kitenetter** [comment]
I've only had one report of the download failing, where the verifier is trying to download butterflies in Dorset for 2021, so it may not be a general issue. However, I have tried masquerading as this verifier, and also downloading from the iRecord support account, and it fails every time.

Are we likely to be able to resolve this, or shall I run a database query and send them the records that way?

@johnvanbreda  do you have suggestions as to whether something else could be going wrong, other than general site performance issues?

**Comment by BirenRathod** [comment]
@kitenetter What are the steps to generate this download?

**Comment by johnvanbreda** [comment]
@kitenetter I've managed to reproduce this and identify a data structure issue in the cache tables which I'll fix with a query this morning. It looks like the underlying bug that caused it was fixed mid last year.

**Comment by johnvanbreda** [comment]
I've applied the fix - please try again in an hour or so once Elasticsearch has had a chance to update.

**Comment by johnvanbreda** [comment]
Can this be closed @kitenetter?

**Comment by kitenetter** [comment]
No recent reports of this issue. Closing.
