### ISSUE TITLE
User with two accounts linked to one email cannot access records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1234]
We seem to have a user who has two user accounts in the warehouse, both with the same identifier and both linked to iRecord, This issue has come to light because when the user logs on to iRecord they cannot see the records they entered during 2021, although the records exist in the database.

On iRecord, the Drupal user account is:
- https://irecord.org.uk/user/1638

That links to this user in the warehouse:
- user ID 7796, linked to BBCT; iRecord; Pantheon

The user entry has an identifier given as <email address 1> and in the people entry there is a different <email address 2>.

The other warehouse user is:
- user ID 68198, linked to BBCT; FIT Count; iRecord; Pantheon; Pollinator Monitoring Scheme; UKBMS

This user entry also has the identifier given as the same <email address 1>, and again in the people entry it is also <email address 1>.

Ideally both these accounts need to be combined and linked to <email address 1>, so that all the records from the two existing accounts become linked to a single account.

**Comment by kitenetter** [comment]
This user is keen to retrieve their records, so moving this into the current milestone. @johnvanbreda let me know if you need me to send the actual email addresses.

I note that there are no longer any "identifiers" shown in the warehouse user entries, so presumably something has changed since January.

This entry has the correct email address:
https://warehouse1.indicia.org.uk/index.php/person/edit/68350

This one has the incorrect email address:
https://warehouse1.indicia.org.uk/index.php/person/edit/7876

The Drupal account is:
https://irecord.org.uk/user/1638

**Comment by johnvanbreda** [comment]
That's done. We should allocate some time to review the processes behind sorting these issues out.
