### ISSUE TITLE
Filtering by survey - make ordering alphabetical

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1237]
In the "Source" filter options, please can the list of surveys be ordered alphabetically. It is almost impossible to find the survey you are looking for at the moment.

**Comment by DavidHepper** [comment]
Please implement this. Even when only a single Website is selected the Surveys list isn't alphabetical!
![image](https://user-images.githubusercontent.com/24915271/221553637-016dc125-e643-4d22-b3ac-afc80deb6561.png)

**Comment by kitenetter** [comment]
Search box now available for flitering. Closing.
