### ISSUE TITLE
Forms missing from the dropdown list in activities

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1239]
When adding forms for the "Group pages" section of an activity admin page, there is a dropdown under the "Please select" button.

The list of forms available seems to be considerably shorter than it used to be, and some activity admins are reporting that forms that used to be part of their activity have gone missing.

I have a vague memory of discussing this with @JimBacon recently but I can't find any issues or emails relating to it.

The example I've been asked about most recently is the activity "FSC Discovering iRecord Course Records" (group ID 1735). This was originally set up as an "Events & biobltzes" activity, and used to have forms for earthworm recording  and for the RHS Cellar Slug Survey, but those are no longer options in the list. I tried changing the activity type to "National groups" but the list of forms is the same.

**Comment by kitenetter** [comment]
Thanks @JimBacon - so the problem is with the forms, not with the activity. Which raises the queston of why the form settings have changed. I guess I'll just have to re-enable them whenevr someone tells me they've gone missing.

Closing.

**Comment by BirenRathod** [comment]
@kitenetter Can you elaborate bit more which settings do i need to look at it? I just compared this irecord.org.uk/activities/edit?group_id=1735 with old website and it shows more forms in the list.
![image](https://user-images.githubusercontent.com/5941255/151023496-8b74b370-9da4-4aa1-9c0b-f37a80fbb0fd.png)

**Comment by kitenetter** [comment]
@BirenRathod For the forms that are in the old list, but not in the new list, we need to edit the form and go to the "Form selection" settings, and then tick the box for "This page is going to be used by recording groups". In most cases we don't need to specify which group:

![image](https://user-images.githubusercontent.com/16039111/151027640-c4884d45-de4a-4817-8804-89082b14c8ba.png)

We probably don't need to update all of the forms, but it's difficult to define which ones should be updated, so it's probably easiest just to update all of them. I have now done the Big Garden Sawfly Survey.

Once the forms themselves have been updated, the next problem is that they will need to be relinked to the activities that were using them on the old site, and I don't know how we can findout which forms are now missing.

**Comment by kitenetter** [comment]
Are we able to run a query to see which forms were linked to which activities on the old site?

**Comment by JimBacon** [comment]
My experience was that, as soon as I ticked the box to allow the form to be used by recording groups, the activity in question seemed to have the form restored, as if the linkage was still there. Maybe you found differently with the Sawfly survey or it was not as I thought.

**Comment by kitenetter** [comment]
That has not been my experience today, the forms have needed to be manually added to the activities.

**Comment by johnvanbreda** [comment]
Is it possible this setting was not migrated when moving to Drupal 9?

This query finds all the group page paths that are linked to groups on iRecord:
```sql
select distinct gp.path
from groups g
join group_pages gp on gp.group_id=g.id and gp.deleted=false
where g.deleted=false
and g.website_id=23
```

I've attached the list
[groups.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/7939918/groups.txt)
.

**Comment by BirenRathod** [comment]
@johnvanbreda Yes, that is the list but where does this settings go?

**Comment by johnvanbreda** [comment]
These are all the paths to Drupal Indicia pages on iRecord where the "available for groups" option needs to be ticked. In some cases, the option should be restricted to the specific group that is using the page.

**Comment by BirenRathod** [comment]
@johnvanbreda I checked on old irecord website and it is showing all those options which I posted the screenshot above. those option not showing for this (e.g. activities/edit?group_id=1735) on new irecord site. So something is missing on Drupal 9 site.

**Comment by BirenRathod** [comment]
@johnvanbreda I just found one bug which could be relate to above problem too.

See this error -> Warning: Use of undefined constant arg - assumed 'arg' (this will throw an Error in a future version of PHP) in extension_group_hierarchies::set_page_title() (line 63 of /code/web/modules/custom/iform/client_helpers/prebuilt_forms/extensions/group_hierarchies.php)

**Comment by kitenetter** [comment]
Is it possible to say whether we will be able to provide an automated fix that will update all the missing form-activity links? If not I will need to continue making manual edits, but it would be good to know if we have a more general solution before I start doing that.

**Comment by kitenetter** [comment]
Actually I have made a few manual edits to some of the species group recording forms, and following that they do seem to be getting linked correctly to the activities, so perhaps an automated approach is unnecessary. I will continue to make manual edits as requests arise. Closing this issue.
