### ISSUE TITLE
Investigate why records added to BLS activity form are not editable

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#124]
See:
http://www.brc.ac.uk/irecord/node/4176

**Comment by kitenetter** [comment]
@JimBacon :

The data entry form in question is this one:
http://www.brc.ac.uk/irecord/node/3668/edit

It is set up to be used by members of an Activity:
http://www.brc.ac.uk/irecord/activities/edit?group_id=438

and the form is set to be available only to group members.

User AliCullaloe is a member of this activity, and has added records using the activity data entry form, but if they subsequently try to edit one of their records they are told they do not have permission to use the form.

Question: is this behaviour the result of the way the activity has been set up, or is it the result of the way the form has been set up?

**Comment by johnvanbreda** [comment]
Fixed as long as you browse to the record via the group's explore page - the group ID needed to be added to the link generated for editing in order to make the page accessible, as the page is locked to this group.
