### ISSUE TITLE
Photo Licence Not Saving

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1242]
Hello,

We have had a couple of emails from users whose media licences are not saving. They have specified a licence and clicked save, but when they next visit the page the change has not saved (no licence is selected).

Best wishes,

Robin

**Comment by BirenRathod** [comment]
@johnvanbreda This field_iform_licence_media variable value not matched in iform_licences.module. What is your suggestion to resolve this? It gets variable like field_iform_licence_, so messing media word at the end.

**Comment by kitenetter** [comment]
Hi @johnvanbreda we're continuing to get emails about this, is it something that we can resolve?

**Comment by johnvanbreda** [comment]
@kitenetter this should now be fixed. Applying the change also included a significant update to the iform module code which I tested on the test site but please let me know if you spot any issues.

**Comment by robin-hutchinson** [comment]
Thank you, John, I just managed to save a license on the iRecord Support 2 account so the fix appears to be working!
