### ISSUE TITLE
Notification "Comment here" link broken?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1243]
At least some notifications are going out with the "Comment here" link showing as:
[http://?user_id=68134&occurrence_id=23370110&warehouse_url=]Comment here

**Comment by BirenRathod** [comment]
@kitenetter Seems like hasn't been implemented on notification page. can you send me the url of the page please?

**Comment by kitenetter** [comment]
Sorry Biren, not sure what url you are referring to.

The example above came from a notification email that had been sent in relation to this record:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=23370110

**Comment by kitenetter** [comment]
In another version of the same notification email there is a link to click on, which goes to an error message:

> Redirect Notice
>  The page you were on is trying to send you to an invalid URL (http://?user_id=68134&occurrence_id=23370110&warehouse_url=).
> 
>  If you do not want to visit that page, you can return to the previous page.

**Comment by BirenRathod** [comment]
@kitenetter When you mentioned another version, what is that another version?

**Comment by kitenetter** [comment]
To clarify, I have been sent two copies of the same notification email, one via my home address into a googlemail inbox, and one via the irecord address via the web version of outlook.

In googlemail the notification displays with a link to "Comment here":

![image](https://user-images.githubusercontent.com/16039111/151776939-ed56d2c5-e124-4894-b3fd-68ed443cdcbd.png)

If I click on that link I get taken to the error message shown in my previous comment.

In outlook the notification displays with text:

![image](https://user-images.githubusercontent.com/16039111/151777177-02c44a5c-4987-425a-ba85-2270d94fa817.png)

In both cases it is not possible for the user to add a comment via the "Comment here" link.

**Comment by BirenRathod** [comment]
> Sorry Biren, not sure what url you are referring to.
> 
> The example above came from a notification email that had been sent in relation to this record: http://www.brc.ac.uk/irecord/record-details?occurrence_id=23370110

@kitenetter Do you see any problem if I change above URL to this -> https://www.irecord.org.uk/record-details?occurrence_id=23370110 ?

**Comment by kitenetter** [comment]
I've been looking back at previous notifications and I am very confused. What used to happen was the for most comments we did not give a "Comment here" link at all, and instead asked people to use the link from the record ID number. But every so often we did include a "Comment here" link, and I can't work out why this appears against some records but not others:

![image](https://user-images.githubusercontent.com/16039111/151784551-8bf970cc-395c-4afb-ba1c-b1ce00ec261c.png)

This seems to have been causing problems since December 2020 if not before.

If not, then I suggest we could remove it from the emails altogether.

However, there is an issue for notifications that refer to records added to other websites, where it may not be possible to view or add comments from the iRecord record ID link. I wonder if the "Comment here" option is supposed to deal with non-iRecord websites? If so it is not working correctly, as the current broken links are for normal records on iRecord.

I think we need more information from @johnvanbreda - is there a logic to the "Comment here" link that I'm not understanding?

**Comment by johnvanbreda** [comment]
The Comment Here links are only shown for Query comments. It would be clearer if we changed the link to "Reply to query"?

It looks to me like the links are broken because we've lost a bit of server configuration. I'm looking into it now.

**Comment by BirenRathod** [comment]
@johnvanbreda I supposed to not change URL in warehouse\modules\notification_emails\config\notification_emails.php to this -> https://www.irecord.org.uk/record-details?occurrence_id=. I should have to change first that in the repository, but if you are doing that please consider to do so.

**Comment by johnvanbreda** [comment]
@BirenRathod no, that's not the right solution - there is a page occurrence_comment_quick_reply_page.php in the warehouse root folder which the link should go to. There is another issue in that the auth token is not added to the link properly.

**Comment by BirenRathod** [comment]
@johnvanbreda Yes, I know that is not right solution but would be appreciate if you can change that in repository please. 
Thanks for letting me know the problem in php file.

**Comment by johnvanbreda** [comment]
@BirenRathod @kitenetter as a temporary measure I've commented out the code that generates the link. Although the URL the link goes to can be fixed with configuration, there is a missing authorisation token in the link so it won't work anyway. I don't have time currently to do a proper fix unfortunately.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 
That will prevent people reporting this as an error, and the text in the notification still suggests using the record ID link to add comments, so I think this is fine until we're able to develop a full fix. I'll leave it open but no need to do more at the moment.

**Comment by kitenetter** [comment]
Have added new issue #1707 that may be related. Closing this one.
