### ISSUE TITLE
How to report spam in D9

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1244]
We used to have a module that allowed spam users to be reported:

![image](https://user-images.githubusercontent.com/16039111/152057704-cb0c8160-c0d2-4d84-b7c7-b33b1bd77432.png)

Do we have anything similar in D9, or should I just delete the account and its content?

**Comment by kitenetter** [comment]
In fact I have now deleted the account in question, as I needed to remove the content they had posted in the forums, but it would be useful to know if we have the anti-spam options for future reference.

**Comment by BirenRathod** [comment]
@kitenetter Antibot module is already enabled but that is not stopping spam forum, so I think we need another module called spamicide for this which I will make available soon.

**Comment by BirenRathod** [comment]
@kitenetter  I have installed spam master module and enabled. This should send alert on registered email, so you should be able to see.
