### ISSUE TITLE
Record to be undeleted

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1245]
Occurrence ID 23645601 was deleted in error. I'm not aware of any mechanism for myself or the original recorder to undelete. Can it be reinstated - thanks.

**Comment by BirenRathod** [comment]
@kitenetter This record is undeleted now. Also I checked samples associated with this and it is not deleted.

**Comment by kitenetter** [comment]
I can see the record again in the warehouse, but it isn't visible on iRecord:
https://irecord.org.uk/record-details?occurrence_id=23645601

Is there something else we need to do?

**Comment by BirenRathod** [comment]
@kitenetter I think that should done by scheduled_task.

**Comment by kitenetter** [comment]
Okay, thanks

**Comment by johnvanbreda** [comment]
@BirenRathod did you add it to the work_queue so it gets recreated in the cache tables?

**Comment by BirenRathod** [comment]
@johnvanbreda  No. What shall I do in order to do that?

**Comment by BirenRathod** [comment]
@johnvanbreda Is this a correct query to add that?
INSERT INTO work_queue (task,entity,record_id,cost_estimate,priority)
VALUES('task_cache_builder_attrs_occurrence','occurrence',23645601,30,2);

**Comment by johnvanbreda** [comment]
Yes, but also:
```sql
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
from occurrences where id=xxxx;
```
See https://indicia-docs.readthedocs.io/en/latest/administrating/warehouse/scheduled-tasks.html

**Comment by BirenRathod** [comment]
@johnvanbreda Done. 
@kitenetter It should be updated when next scheduled_tasks run.

**Comment by kitenetter** [comment]
Record now showing, thanks - closing.
