### ISSUE TITLE
New survey and recording form for RSPB farm surveys

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1246]
Specification:
- Set up a new survey (linked to the iRecord website); this survey needs to be a clone of the "iRecord general data" structure, with the addition of occurrence attribute 823 "Breeding evidence (birds)"
- I think the survey can be called "RSPB farmland wildlife survey" (awaiting confirmation of this)
- Set up a new recording form on iRecord, which can be a clone of https://irecord.org.uk/enter-record-list but with the extra occurrence attribute added. Suggested URL alias: rspb-farmland-survey

@BirenRathod are you able to work on this over the next few weeks? We don't have a specified deadline but RSPB wish to have it up and running for the bird breeding season, which is not far off.

Let me know if you need any further information. Once the form is created I will liaise with RSPB to link it to an activity.

**Comment by kitenetter** [comment]
Update: RSPB have requested that we call the survey and the recording form:
- VMFW Farmland Bird Survey

**Comment by kitenetter** [comment]
RSPB have also requested that we set up a single-record form, i.e. a clone of https://irecord.org.uk/enter-casual-record with the breeding evidence attribute added.

**Comment by BirenRathod** [comment]
@kitenetter I have created survey & recording form for VMFW. Here is a link https://irecord.org.uk/vmfw-farmland-survey

Also, check stage & breeding evidence attributes added correctly or not. one more thing the recording form hasn't added in submenu of "Species group forms".

**Comment by kitenetter** [comment]
Thanks Biren, I have forwarded to RSPB for checking.

**Comment by kitenetter** [comment]
@BirenRathod following feedback from RSPB I've made some changes: removed the habitat field (from both the form and the warehouse survey), made some additional fields mandatory; removed the bird-specific stage terms and replaced them with the generic terms; made the quantity an integer-only field; re-ordered some of the attributes.

There is some further re-ordering that they'd like but I'm not sure how easy it is to do - please can you set the form so that the attributes are in this order:
1. Recorder name
2. Identified by
3. Date
4. Species

and then the rest are fine as they are.

Can you then set up an "add a list" type form that uses the same survey structure.

**Comment by BirenRathod** [comment]
@kitenetter I have moved Date attributes below recorder name. Also, identified by is the part of species attributes, so I can't move just that field above date field. In fact, as per your requirement of "add a list" type structure , it doesn't need to. 

Let me know if this is ok for you.

**Comment by kitenetter** [comment]
@BirenRathod it is fine to have Identified by lower down the list if needed.

However, we have misunderstood each other! What we need is one recording form for a single record, and then a separate recording form for entering a list. So that the VMFW project has an equivalent of one form for "enter a casual record" and another form for "enter a list of records".

The VMFW "enter a list" form can have the same tabbed structure as the main iRecord "enter a list" form.

Can we go back to a single record form for this link:
https://irecord.org.uk/vmfw-farmland-survey

And the for the list form give it this URL:
https://irecord.org.uk/vmfw-farmland-survey-list

**Comment by BirenRathod** [comment]
@kitenetter I have amended the form now.

Also I have added new form to add list of records.

**Comment by kitenetter** [comment]
Thanks @BirenRathod 

This should now be complete apart from any minor text edits that RSPB may need. Closing.
