### ISSUE TITLE
Request for addition and edit to species dictionary

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#125]
**Addition: new fly**
We've been asked to add a new species for the Agrmomyzidae (leaf-mining flies) Recording Scheme - Chris Raper has added it to the UKSI as follows:
organism parent NBNORG0000025361
Agromyza viciae Kaltenbach, 1872
tvk NHMSYS0021164797

**Edit: unhelpful English name**
We've also been asked by the Mayfly Recording Scheme if we can remove the English name "Mayfly" that is currently associated with family "Ephemeridae" (Ephemeridae is a very small family within the larger Order of mayflies, and the use of the English name is leading to lots of Order-level records being erroneously attached to the family).

Can we just delete the English name, or are there other dependencies to consider? It is:
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/141921

This will mean that we no longer have a way for people to enter unidentified mayflies, and I'm not sure whether that is a good thing or a bad thing. But we could add "Mayfly" as an English name for the Order Ephemeroptera, and there is a UKSI name that allows for this:

NBNSYS0000168769
Mayfly [although I would be tempted to edit this to "a mayfly"]

which links to this recommended name:
NHMSYS0000841056
Ephemeroptera

**Comment by kitenetter** [comment]
@johnvanbreda the additional fly mentioned above has been dealt with.

For the mayfly issue, is the simplest solution for me to edit http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/141921 so that is say "a mayfly" rather than "Mayfly"?

**Comment by johnvanbreda** [comment]
The taxon search picks up words within the taxon name, so "a mayfly" will still be found if you search for Mayfly. You could tick the "Not for data entry" box?

**Comment by kitenetter** [comment]
@johnvanbreda I did mark it as not for data entry, thanks. Have let Chris know.

It appears that I created a new entry in the taxon table:
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/431296

I don't know how that happened, I thought I was just editing an existing entry. Have I done something daft?

**Comment by kitenetter** [comment]
I am still unclear about some aspects of editing and controlling English names where we wish to avoid them being used in the wrong context, but the particular issue mentioned above is no longer current. Closing.
