### ISSUE TITLE
Add NMRS website to ES list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1251]
Earlier this evening I added the sharing agreements for the NMRS website (id = 135), @johnvanbreda please can you add it to the ES view of the data.

**Comment by johnvanbreda** [comment]
Done

**Comment by kitenetter** [comment]
@johnvanbreda I'm now seeing the NMRS records via the ES Explore pages, but they still aren't showing on my verification page.

**Comment by johnvanbreda** [comment]
Now done.
