### ISSUE TITLE
English names dissassociated from scientific names for moths

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#126]
For some moth species, if you enter them by scientific name you appear to get a different taxon concept to entering by English name. And the record cleaner rules seem to be attached to the English name version only. Example:

![image](https://cloud.githubusercontent.com/assets/16039111/21487378/7b6fafb0-cbbf-11e6-88fb-8de377f44de2.png)

Have we got some incorrect links in the species dictionary?

In the example above, entering either "Peribatodes rhomboidaria" or "Willow Beauty" leads to a record in the downloaded data that is linked to TVK NHMSYS0021144226 but with no associated English name.

Presumably this change came in with the update to the UKSI, but it has now retrospectively changed all records of the species concerned - e.g. all of my Willow Beauty records from previous years have now lost their English names.

It would be great if we can fix this, as it leading to another data-cleaning job that has to be done outside iRecord following download of records, and is also preventing the record cleaner rules from being applied to this set of species.

**Comment by johnvanbreda** [comment]
The UKSI importer seems to have got muddled by the moth names which were imported for moth night this year. I've cleaned up this bit of code and applied the changes - looks OK now.
