### ISSUE TITLE
Problem with species name when uploading from csv

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1260]
A user reports:
"When entering Ectopsocus briggsi [a bark louse] onto iRecord via a spreadsheet import, it automatically changes the determination to an aggregate. There was no alert / notification of this change so it would not been detected it if the determiner hadn’t been the same person as the verifier!"

In UKSI the name "Ectopsocus briggsi" is linked to "Ectopsocus briggsi agg.", and the segegate species needs to be specified by "Ectopsocus briggsi sensu stricto". There is also an "Ectopsocus briggsi sensu lato" which is linked to "Ectopsocus briggsi agg.".

@johnvanbreda I don't know if this sort of issue will be handled by the current round of improvements to the upload process. If not we should put it on the list for the next round, and/or provide user guidance for aggregate taxa.

**Comment by johnvanbreda** [comment]
I've just tested the new code. Because there is an exact match to _Ectopsocus briggsi_ which is a synonym of _Ectopsocus briggsi_ agg., it maps to the synonym _Ectopsocus briggsi_. That seems correct to me - it's not changing the determination to an aggregate, but the name chosen does have an aggregate as the accepted name.

**Comment by kitenetter** [comment]
But that means that a recorder who has identified "Ectopsocus briggsi" has to be aware that UKSI wants "Ectopsocus briggsi sensu stricto". I'm not sure what we can do about this - is it possible for there to be some sort of flag when an entered name is treated as a synonym? Or a way of reviewing synonymised names following an upload?

I realise that this is probably asking for new features that can't be addressed in the short term, but this particular example does seem like unhelpful behaviour in that a change is being made to the recorder's meaning without the recorder being alerted.

**Comment by johnvanbreda** [comment]
The nice thing about the new importer code is the data sit in a pending area before the actual upload, allowing both automated and manual processes to tidy the data first. So, it's going to be much easier to resolve these sorts of issues. 

I propose the following:
1. If there are several possibilities for a matched name which differ only in terms of their attributes (s.l., agg, s.s. etc), then the uploader should fail to automatically match and allow the user to sort it out.
2. When this happens, there should be a list of suggestions for the user to make it easier to select from one of the possibilities.
3. Any names matched to synonyms should be shown to the user, allowing them to see that they are matching to a synonym, what the accepted name is, and giving them a chance to correct the matches.

I'll leave this open for now so we can come back to it after other priorities are done.

**Comment by kitenetter** [comment]
Importer v2 handles this well. Closing.
