### ISSUE TITLE
CSV import process freezing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1261]
A user who is doing test imports at the moment, and only uploading a few records at a time, says that he can get as far as the page with the import progress bar, and it then freezes - the import does not complete, and there is no error message.

He says:
"progress bar is present, but just sits there, I was only uploading 2 lines should happen in a flash. As usual I'm on my iMAC, safari is the browser, everything else working fine and good internet connection."

I've seen an example of one of his previous csv files and I could not see anything in the file that would cause problems, The user has successfully imported datasets previously, although a week or so ago he reported problems where he was seeing messages that thousands of records were being imported even though he only had a few in his file (which did go through successfully).

This is all very odd and seems to be specific to this user - e.g. I've been using the importer quite a lot over the last week or two and it has been fine.

I guess one answer will be to wait for the new importer, but the user would like to make progress before then if possible.

**Comment by kitenetter** [comment]
The user reports that the records are appearing eventually, after many hours.

I'm fairly sure this problem stems from the csv file that the user is generating. I get the same apparent freezing when I try to do a test import of the same file. Currently waiting for the test import to complete before investigating further.

**Comment by BirenRathod** [comment]
@kitenetter This CSV imports , do you do on warehouse website or irecord website?

**Comment by kitenetter** [comment]
This is using the iRecord importer. The test that I am currently running is still showing no progress:

![image](https://user-images.githubusercontent.com/16039111/157861903-dd8ff2ef-2165-4126-b81f-513605b32227.png)

However, it has in fact imported the two records, which I can see on the old Explore My records page (they haven't yet fed through to the ES page but presumably they will).

The csv file has empty columns and rows which may be the problem?

![image](https://user-images.githubusercontent.com/16039111/157862148-5a56845e-1865-4fd1-9cb4-6184ae2897a4.png)

**Comment by kitenetter** [comment]
If I remove the extraneous commas from the end of the two record rows, and then delete all the empty rows, the data imports quickly and easily. So it does seem the the extraneous columns are causing iRecord to fail to complete the import progress bar (although the records do get imported).

I've asked the user if they can find a way of generating files that don't have unnecessary commas, so I don't think further action is needed on this at the moment, but ideally the import progress page should be able to handle empty rows without hanging up completely. Tagging @johnvanbreda in case this has any bearing on the new importer.

**Comment by kitenetter** [comment]
I'm getting an increasing number of reports that the csv upload process is freezing on the progress bar page, and never arrives at a finish point. It appears that some records are getting through, but not all, leading to uncertainty about what has uploaded and what needs to be done again.

This does seem to be a sporadic issue, with some people experiencing a mix of successful and unsuccesful uploads.

How close are we to being able to implement the new importer? If we get too many partial uploads we are likely to get requests to tidy up imports that have gone wrong.

**Comment by johnvanbreda** [comment]
Although not ready for public consumption, there is an initial version of the new version of the importer at https://test-brc-irecord.pantheonsite.io/import-v2. Note, it is connected to the live database and as yet does not have any way of finding rows that error during the import (though when it does, it should be much better than the old way).

**Comment by DavidHepper** [comment]
I've just fallen foul of the "Preparing to upload.." freeze while testing Vague Dates in Training Mode.
In my case the selected file is of type XLSX. It has a header row and 5 data rows on the first worksheet of the workbook, which also has two further worksheets.
Additionally, the current reference to documentation is to v3.2, which doesn't mention Excel uploads at all.
(The same workbook imports fine if saved as CSV and imported with the same selections.)

**Comment by DavidRoy** [comment]
Suggest we close this and raise any new issues with the new importer?
