### ISSUE TITLE
Vernacular for Homo sapiens

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1262]
UKSI provides two vernaculars for Homo sapiens: "Human" and "Man". Unfortunately iRecord has chosen to use "Man":

![image](https://user-images.githubusercontent.com/16039111/157996355-156efb5e-b311-4e44-b8f5-6f9904dd4bc8.png)

This has been picked up via Twitter and we've been asked (very understandably) to do something about it. I've requested that UKSI deprecate "Man", and in the warehouse I have set the vernacular "Man" to be "not for data entry". I have also removed "Man" from the synonyms of Homo sapiens. However, "Man" is still coming up as the vernacular for Homo sapiens when doing data entry. How do we change it to "Human"?

(And yes I did point out to the person raising this issue that we don't actually want people to add records of Homo sapiens to iRecord.)

**Comment by johnvanbreda** [comment]
Now fixed. The field taxa_taxon_lists.common_taxon_id needed updating as well (possibly we should enhance the UI to automatically do this).
