### ISSUE TITLE
CSV download issue - line breaks in comments causing records to be split across rows

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1263]
This has been reported by an LERC that has recently downlaoded data from their area. Some of the records have ended up being split across multiple rows. The first example I've checked is for sample ID 17766028, occurrence ID 24495013. The Record Comment is:

> Hefyd allan yn y safleoedd picnic arferol, Glasdir SH737225 a Tŷ’n y Groes SH729233
> Also flying at their usual picnic sites, grid refs above

Other occurrence IDs with similar problems:
24490746 (LERC Wales - record comment)
24490749 (LERC Wales - record comment)
24307719 (iRecord general - sample comment) - as an example, this record gets split across three lines in the csv download:

![image](https://user-images.githubusercontent.com/16039111/159684957-d762d277-74a1-4df9-aaf2-d08dad54544a.png)

The common factor in the examples I've checked is that there appear to be line breaks in the comment attributes. However, I'm sure this happens widely in iRecord and I don't recall this being reported as an issue before when downloading data.

Has something changed to prevent line breaks in comments being handled correctly for download?

Flagging as urgent because this could cause widespread problems for verifiers and others.

**Comment by BirenRathod** [comment]
@kitenetter Not that I'm aware of. Where can I check this?

**Comment by BirenRathod** [comment]
@kitenetter did you download it from irecord website?

**Comment by kitenetter** [comment]
The original download was done by Cofnod records centre, using the normal LERC download from iRecord. They have sent me the zip file that they downloaded, which is what I used to check the records. I have also done a verifier's download from iRecord for a subset of the same records, and I get the same problem with line breaks.

**Comment by BirenRathod** [comment]
ok, so it is from irecord website. now where can I go and download from iRecord? is it on verification page?

**Comment by BirenRathod** [comment]
@kitenetter if they have downloaded using this downloads page from irecord website and it is not a problem from irecord website. The data download format been created from the warehouse. So not aware if anything change on there. 
I think best person to answer this is @johnvanbreda.

**Comment by johnvanbreda** [comment]
I don't recall changes in the download, only the upload. I'll take a look though.

**Comment by johnvanbreda** [comment]
@kitenetter looking at the examples you give, what's actually wrong with the CSV? The field has a double-quote delimiter around it so the line-breaks are correctly contained within the delimiters and should be OK.

The CSV output generated by our Elasticsearch API uses the standard PHP fputcsv function and the code hasn't changed for over a year.

**Comment by DavidRoy** [comment]
I thought the same. It's a problem their end in how they are viewing the file

**Comment by kitenetter** [comment]
In which case I'm probably panicking unnecessarily. Having opened it into Notepad I was expecting not to see the extra line breaks, but I'm wrong about that aren't I. They said they were opening into Excel (not sure if via double-click or via import) and also into their PowerBi system, and got the smae problem each time. I will go back to them.

**Comment by kitenetter** [comment]
One more question @johnvanbreda - if I open the csv file into Excel by double-clicking it handles the comments correctly. However, if I use the text file import wizard, specifying a comme delimiter and a double-quote text qualifier, the comments get split across multiple rows. What am I doing wrong? The import wizard assume the file origin to be "65001 : Unicode (UTF-8)".

**Comment by johnvanbreda** [comment]
To be honest, Excel's handling of CSV files leaves a lot to be desired so it wouldn't surprise me to find quirks like this. I found a description of the same problem here https://techcommunity.microsoft.com/t5/excel/how-to-import-csv-with-line-breaks-in-cells-and-numbers-in-text/m-p/142045 but no solution.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda and apologies all for unnecessary prioritisation. Closing.
