### ISSUE TITLE
Problem with indexing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1264]
We appear not to have had any record cleaner rules nor VC/Country links applied to any records since sometime early this morning. Getting enquiries from country/county specific verifiers as to why no records are appearing.

Are things just slow or is there a problem?

**Comment by johnvanbreda** [comment]
It looks OK this morning @kitenetter - are you still seeing a problem?

**Comment by kitenetter** [comment]
It seems to have caught up again this morning. I think the alarm was caused because it was taking longer than usual and one verifier in particular was worried because it appeared no records had been added yesterday, at what is usually a busy time of year. Closing.

**Comment by johnvanbreda** [comment]
@kitenetter I think this relates to #1265 due to the number of edits trickling through. It will likely also get delayed today until things catch up whilst the butterfly common names are repaired.
