### ISSUE TITLE
Butterfly English names missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1265]
This has just been reported and I am able to reproduce it. On the main enter records forms, we seem to have lost most of the English names for butterflies. E.g. "Peacock" does not produce Aglais io, and if you enter "Aglais io" no English name is given.

For some taxa, English names are still availabel for subspecies but not for species.

Marking as urgent because lots of butterfly records are being added at the moment.

**Comment by johnvanbreda** [comment]
I think there is some problem with the attribute editing tool on Pantheon. I've re-instated the common names but it will take a little while to trickle through and will look into Pantheon's editor now.
