### ISSUE TITLE
Allow inclusion of iNat Licence type in the Grid

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1266]
Feature Request: Please allow selection of attribute 'Licence', currently visible only in Record Details, in the **Column configuration** pop-up of **Verify - iNaturalist**, allowing verifiers to view and filter between CC BY and CC BY-NC records to review.
I assume this shows the iNat Observation License, not the Photo License. We are not bothered about the Photo Licence since no media reaches NBN Atlas.

This issue is split off from #1159.

**Comment by kitenetter** [comment]
This is a generic issue, not just for iNat, and I agree it would be useful to have the record licence available as a column configuration option.

**Comment by kitenetter** [comment]
Now available in filters. Closing.
