### ISSUE TITLE
Taxon inherited from a Locked Control is not accepted

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1267]
Locking the Species (taxon) field shows the same species as the last one entered but submitting this results in an error banner "The data could not be saved" and the Species field is highlighted: 

![image](https://user-images.githubusercontent.com/24915271/159906993-1175bd06-a21c-445f-9efb-202da9121074.png)

The field (data-entry control) has to be unlocked and the same taxon reselected. Only then is it accepted.

Examples, using _Anax parthenope_ and _A. imperator_ respectively (in Training Mode): 
- initial records with taxon picked manually: 24531457, 24531505
- records that could only be submitted after unlocking the field and reselecting the taxon: 24531477, 24531557

Environment: Firefox; iR Training Mode.

**Comment by kitenetter** [comment]
Perhaps this is a side-effect of the dynamic termlists for the stage term, which needs to be recalculated for a new record in case the taxon has changed? But it would be preferable to enable taxon-lock ing if we can. Failing that we should remove the locking option to avoid confusion.

**Comment by kitenetter** [comment]
Locking option no longer available for taxon names, so as to allow dynamic termlist for stage. See also #1289 

Closing.
