### ISSUE TITLE
BTO BirdTrack data unavailable in Verify?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1272]
I can see imported 'BirdTrack non-avian taxa' records of Odonata in Explore but not in Verify. BDS never agreed that BTO could import Odonata records pre-accepted and I'm sure this wasn't intentional. It seems we're currently locked out even of querying them! Please mark them Pending (unreviewed) and make them visible in Verify. 
(Does this apply to other taxa such as mammals?)
Example:
Record ID
    23765776
Record external key
    BTOOBS226935507
Recommended name
    Ceriagrion tenellum (de Villers, 1789)
Common name
    Small Red Damselfly
Name as entered
    Ceriagrion tenellum
Taxonomy
    Animalia :: Odonata :: Coenagrionidae
Survey
    BirdTrack non-avian taxa
Recorder
    Pete Jeavons
Input by
    admin, core
Record status
    Accepted as considered correct
Date
    31/05/2016
Grid ref
    54.994N, 4.510W
Site name
    Barclye RSPB - Mill Hill Walk
Licence
    [CC BY](https://creativecommons.org/licenses/by/4.0)
Submission date
    Entered on 14th February 2022 at 18:13
Individual count
    1
Life stage
    Ad:1
Collection code
    BTO BirdTrack
Site grid ref
    NX3969

**Comment by kitenetter** [comment]
Hi David, this is on our radar and the intention was not to bring the records in as already verified, so we need to reset them. Once we've done that we'll make them avaiable to verifiers. @johnvanbreda is aware.

**Comment by johnvanbreda** [comment]
I've reset the verification status on imported records using the following script: 
```
sql
drop table if exists to_fix;
select o.id, o.record_status, o.record_substatus
into temporary to_fix
from occurrences o
left join occurrence_comments oc on oc.occurrence_id=o.id and oc.record_status is not null
where o.website_id=142 
and (o.record_status<>'C' or o.record_substatus is not null)
and oc.id is null;

update occurrences o
set record_status='C', record_substatus=null, verified_on=null, verified_by_id=null,
  comment = coalesce(o.comment || '. Birdtrack status: ', 'Birdtrack status: ') || 
    case tf.record_status || coalesce(tf.record_substatus::text, '')
	  when 'V1' then 'verified as correct'
	  when 'V2' then 'verified as considered correct'
	  when 'R4' then 'rejected as unable to verify'
	  when 'R5' then 'rejected as incorrect'
	end
from to_fix tf
where tf.id=o.id;

insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
from to_fix;
```

**Comment by DavidHepper** [comment]
They are still not appearing in Verify this morning. Does ElasticSearch need to be nudged specifically for these records?

**Comment by johnvanbreda** [comment]
@kitenetter are you happy with the agreement to share for verification being enabled now?

**Comment by kitenetter** [comment]
Yes, that's fine.

**Comment by johnvanbreda** [comment]
Now done.

**Comment by DavidHepper** [comment]
Only a few of the 50,000 Odonata records have now been assigned a VC. 
Only a very few, and not necessarily the same ones, have been checked against the Automated Rules - the others have the cogwheel symbol. Is the Rule Checker process still running or has it got indigestion?

I think this Issue should be reopened, please.
