### ISSUE TITLE
Duplicate Odonata records imported from BTO

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1276]
@kitenetter - urgent:
A tranche of older Odonata records that have already been imported (by me) to iRecord have been duplicated in the recent import. On 24/08/2021 I asked that only records with a **BTO external key** (RECORDKEY) higher than **OBS290186151** (formatted as BTOOBS290186151 in iRecord) should be imported. It appears that this criterion hasn't been observed, resulting in thousands of duplicates. Unfortunately, it is still not possible to select External Key as a grid column, so it isn't easy to tell just how many.
Please bulk-delete (regardless of verification status) all Odonata records containing BTOOBS290186151 or below.

Example: 
- New iR ID 23866679 from year 2013, containing BTOOBS194898261.
- This is a dupe of iR ID 8837955, containing OBS194898261.

**Comment by kitenetter** [comment]
Apologies @DavidHepper that shouldn't have happened.

@johnvanbreda could you apply the necessary delete please?

**Comment by johnvanbreda** [comment]
@kitenetter will do. I think this stems from some confusion over how the BTO ids were formatted, so the code that filtered them out didn't work correctly.

**Comment by johnvanbreda** [comment]
Done. Here's the script:

```sql
drop table if exists occs_to_fix;

select o.id, o.sample_id
into temporary occs_to_fix
from cache_occurrences_functional o
join cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id
where o.website_id=142
and regexp_replace(o.external_key, '[^0-9]', '', 'g')::integer<=290186151
and cttl.order_taxon='Odonata';

drop table if exists samples_to_fix;

select distinct otf.sample_id
into temporary samples_to_fix
from occs_to_fix otf
left join occurrences o on o.sample_id=otf.sample_id and o.id<>otf.id
where o.id is null;


delete from cache_occurrences_functional where id in (select id from occs_to_fix);
delete from cache_occurrences_nonfunctional where id in (select id from occs_to_fix);
update occurrences set deleted=true, updated_by_id=3, updated_on=now() where id in (select id from occs_to_fix);


delete from cache_samples_functional where id in (select sample_id from samples_to_fix);
delete from cache_samples_nonfunctional where id in (select sample_id from samples_to_fix);
update samples set deleted=true, updated_by_id=3, updated_on=now() where id in (select sample_id from samples_to_fix);
```
