### ISSUE TITLE
Request for update to species dictionary

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1278]
We currently have the mollusc aggregate "Polycera quadrilineata/norvegica" in iRecord, which refers to:
https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021316692

In the UKSI, that aggregate taxon now points to a recommended aggregate, "Polycera quadrilineata/capitata":
https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021494705

The Conchological Society is keen to get this updated in iRecord as their verifiers are having to provide explanations to confused recorders. I can add the new aggregate in the usual way, but I don't know what further steps are required to make the new name the preferred one and to link the old name to the new one.

If this can be done from the warehouse interface let me know what I need to do, otherwise please make the required changes in the database tables.

**Comment by DavidHepper** [comment]
May I make a general point? IMO it would be useful to concentrate dev effort into ensuring that iR always reflects UKSI. That way Societies such as Conchological (and us at Br. Dragonfly) can be told to put UKSI in order if anything needs to be changed in iR. We've had a recurring problem with _Sympetrum striolatum_ disappearing on each reload of UKSI and I'm still not sure that the underlying reason for this was ever found or whether the name was tweaked manually afterwards.

**Comment by johnvanbreda** [comment]
Done. I agree with the point about automating the updates - note that the process is actually developed, it's just that we need to prioritise the testing.

**Comment by kitenetter** [comment]
We're due to discuss prioritising at next month's meeting. Closing this one.
