### ISSUE TITLE
Recording form page not available

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1281]
This website:
https://curlewcountry.org/birdform/

has an iFrame that should display this page:
https://irecord.org.uk/external/stiperstones-ground-nesting-birds

However, the page returns "The website encountered an unexpected error. Please try again later."

The edit link is:
https://irecord.org.uk/node/3732/edit?destination=/admin/content%3Ftitle%3Dstiperstones%26type%3DAll%26status%3DAll%26langcode%3DAll

I believe the form was set up by @andrewvanbreda but not sure if Andy or @BirenRathod is best place to look into this.

**Comment by johnvanbreda** [comment]
Fixed - a bugfix that had not yet been deployed to iRecord.
