### ISSUE TITLE
review of the use of D3 visualisations within existing Verification page 

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1285]
Following our discussion via zoom (20.4.22) around the new data visualisation tools being developed by Rich Burkmar, re: exploring further the specific use requirements by verifiers.

In particular I thought it would be helpful to ascertain whether they would want to zoom in to areas for more contextual mapping, as I noted there is no function to zoom in Rich's maps as they stand, whereas on the current iRecord and BSBI maps this seems to me it could be a potentially very useful function. David suggested opening an issue for this here as a suggestion to review of the use of D3 visualizations within the existing verification page.

**Comment by kitenetter** [comment]
See also #974 #749 #422

**Comment by burkmarr** [comment]
@Sam-Amy and @kitenetter - the current interactive map on the verification page provides contextual mapping referenced in the description (unless I misunderstand what you mean Sam) and the other issues linked here all involve enhancements to the existing verification page mapping. So I'm not seeing anything which involves the used of D3 visualisations with the existing verification page. So is this about tweaking the existing verification page or adding new features?

**Comment by Sam-Amy** [comment]
Hi Rich,

Sorry for the confusion. My original thought was around exploring the potential for a zoomable function, similar to that on the explore records/verification pages on iRecord or the BSBI distribution maps, particularly on the verification page and/or VC Atlas page, but perhaps this is beyond the scope of these pages?

Thanks

Sam

**Comment by burkmarr** [comment]
@Sam-Amy - I'm still a little confused! This issue is about enhancing the existing verification page but you're suggesting a:

> zoomable function, similar to that on the explore records/verification pages on iRecord

So I'm not sure what, if any changes, you're proposing to the existing zoomable functionality on the verification pages. I did demonstrate some static VC Atlas pages but there's currently no proposal to take those forward. (If  that is required, then we can open another issue for it.)

**Comment by Sam-Amy** [comment]
Sorry Rich, I was referring to this page https://irecord.org.uk/brcvis-2 , as opposed to the current iRecord verification page

**Comment by kitenetter** [comment]
I don't think we have any current requirement to use the D3 maps on the existing verification page.

It would be good to make use of the additional tools from the brcvis test pages, but I don't think we yet have a clear plan for how they should be set up on the site, and my expectation was that they were intended for enabling recording schemes to visualise their data for feedback and analysis purposes, not for verification as such.

Which means that I can't remember why we felt the need to open up this particular issue! I'm sure there was a reason but I cannot recall it. So I think we can close this issue as far as verification goes, but we do need to revisit the visualisation question more broadly when we can.

I will close but if I've got this wrong please re-open or start a new issue.
