### ISSUE TITLE
Old iRecord links no longer redirecting?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1288]
When we first moved to the https://irecord.org.uk/ domain I thought that links to the previous https://www.brc.ac.uk/irecord/ domain were being automatically redirected. This no longer appears to be working.

Is it possible to reinstate the redirection, or do we need to go through and edit as many of the old URLs as we can find?

**Comment by BirenRathod** [comment]
@kitenetter It works but seems like forward slash at the is not recognising by my latest redirection. Where do we have that link in irecord website?

**Comment by BirenRathod** [comment]
@kitenetter can you send me one example where the link has been posted on the website with /irecord/ only? Not the one with for e.g. /irecord/enter...

**Comment by kitenetter** [comment]
Example 1:

On this page:
https://sites.google.com/site/berksmoths/Home/recording

There is a link to https://www.brc.ac.uk/irecord/ which opens into a blank page. There are also links to activities that produce blank pages, e.g.:
https://www.brc.ac.uk/irecord/activities/summary?group_id=45&implicit=

Example 2:
On this page:
https://www.nhsn.org.uk/using-irecord/

There is another link to "Join the North East Bee Hunt" which goes to:
https://www.brc.ac.uk/irecord/join/the-north-east-bee-hunt

and also results in a blank page.

Example 3:
The DECIDE project links to iRecord from this page:
https://decide.ceh.ac.uk/info/faq_recording

going to:
https://www.brc.ac.uk/irecord/

which is another blank page.

**Comment by BirenRathod** [comment]
@kitenetter & @DavidRoy The redirection of irecord added, it has been removed by-mistake in response to resolve proxy.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - closing.
