### ISSUE TITLE
Question: if a stage term is added to an iNat observation, will that cause the record to be re-imported?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1291]
iNat records are often missing a stage term. It is possible for a verifier to log in to iNat and add a stage. If a verifier did that, would the record get reimported with the stage included, or do reimports only get triggered if the identification changes?

**Comment by johnvanbreda** [comment]
If iNat considers the record has changed, it should be included in the feed. So, I think the answer to this is yes, the record will get reimported.
