### ISSUE TITLE
Replace species details pages using D3 visualisations

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1292]
The existing species detail pages are in need of maintenance, and will benefit from the new visualisation approaches. Example of existing page:
https://irecord.org.uk/species-details?taxon_meaning_id=89659

Need to agree what will be included and tidy up the presentation.

**Comment by burkmarr** [comment]
@kitenetter - I'm looking first at tidying up the existing page before thinking about adding further visualisations. You can follow progress on it under this issue: https://github.com/BiologicalRecordsCentre/iRecord/issues/1286
