### ISSUE TITLE
Records being slow to get indexed?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1295]
Three verifiers from our busier recording schemes have been in touch to say that records seem to have stopped appearing. I'm not sure if this was just a temporary issue (it seems to have been so in at least one case), but here is an example of a record entered yesterday morning that has not yet been indexed to vice-county, and has therefore not appeared for the county verifier (who in this case is the same as the recorder):
https://irecord.org.uk/record-details?occurrence_id=25394186

Maybe we've just hit a busy patch? Will continue to monitor.

**Comment by kitenetter** [comment]
Another example from the same user but entered on Sunday 15 May:
https://irecord.org.uk/record-details?occurrence_id=25384667

**Comment by johnvanbreda** [comment]
The scheduled tasks are not completing, possibly related to recent upgrades to PHP 8. Looking into it now.

**Comment by BirenRathod** [comment]
I checked scheduled_task this morning and it runs fine. Not found any error there but not checked the log yet, so please do so.

**Comment by johnvanbreda** [comment]
@BirenRathod it does seem to have fixed it actually. Still waiting for it to complete, but before it failed after 7 minutes, now it has run for 1 hour already.

The difference between PHP7.4 and 8 is that in 7.4 this style of syntax was deprecated, so generated a warning but still worked. In PHP8 it raises an error and doesn't work.

**Comment by BirenRathod** [comment]
@johnvanbreda  another reason to use PHP 8.1!
