### ISSUE TITLE
Activity membership invitation emails not being sent?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1298]
This has arisen with activity ID 2005, "RSPB Farmland Volunteer Butterfly Survey".

The activity is set up to be membership by invitation only. The option for sending invitations appears to work from the iRecord end of things, but a user has reported not receiving the email. I've just tested this by sending myself an invitation to join and I have also not received the invitation (and it does not appear to have been trapped as spam).

Can we check that the invitation emails are actually being sent? The page that sends them is:
https://irecord.org.uk/activities/invite?group_id=2005

**Comment by johnvanbreda** [comment]
@BirenRathod did you actually manage to get an invite email to work? I've just tried and nothing came through to my mailbox or spam folder.

**Comment by BirenRathod** [comment]
@johnvanbreda No I haven't. I seen you made changes on irecord, so @kitenetter should test this.

**Comment by BirenRathod** [comment]
@johnvanbreda After I post above message, I have tested by myself and it works fine. see below screenshot. @kitenetter can you test and close this please.
![image](https://user-images.githubusercontent.com/5941255/173546915-92571406-04c5-4eb0-a982-e843b0240505.png)

**Comment by johnvanbreda** [comment]
I'm not sure what changes you mean Biren - I don't think I've changed this area of code on iRecord recently? Isn't the problem that the site email address is still on the brc.ac.uk domain, but the domain is now irecord.org.uk, causing the email to be blocked as spam?

**Comment by BirenRathod** [comment]
@johnvanbreda Well, I may have seen something else if I find then let you know but this is working at present.
Domain is not a problem and site was on brc server before, so that is not a problem either.  Regarding email address it is thrid party service, so as long as it spproves our email address then that is sufficient. In our case it is @brc.ac.uk

**Comment by johnvanbreda** [comment]
@BirenRathod domain absolutely is a problem when sending emails. Our code sets the email's From header to the site's mail address (on the Basic Site Settings configuration page). So, when it sends the email, the mail comes from irecord.org.uk (as it is sent by Drupal, not the warehouse), but with a conflicting header. This is a red flag for any spam checker but presumably your own email server doesn't check this, though a large number do.

I've changed the site mail to noreply@irecord.org.uk which I believe has fixed this. @kitenetter please confirm and close if OK.

**Comment by BirenRathod** [comment]
@johnvanbreda you didn't see my scrrenshot above. it has used @brc.ac.uk. 

And see below screenshot, that is after you changed site email address. As I mentioned the third party email service only use on Pantheon not on BRC server, so thai why it doesn't matter the domain name.
![image](https://user-images.githubusercontent.com/5941255/173560559-00141133-1cc8-4a53-af20-01b2748f82cd.png)

**Comment by BirenRathod** [comment]
@johnvanbreda must be cache which have prevented this to get an email in your inbox.

**Comment by kitenetter** [comment]
I will test if this is now working.

**Comment by Sam-Amy** [comment]
We have had another query about how to invite people to activities, and as far as I can tell this email function is still not working. Does anyone know what the next step in resolving this is please?

**Comment by BirenRathod** [comment]
@kitenetter & @Sam-Amy Just to confirm with you both that the email system works on the iRecord website. I just did the test see below. But for some reason not from the warehouse indicia server. 
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/5941255/4f2a3002-f269-49d9-bf8e-d405bc3c0510)

**Comment by BirenRathod** [comment]
@kitenetter & @Sam-Amy you have not received any emails from the warehouse or just from activities?

**Comment by Sam-Amy** [comment]
When I tested seding an email to a recorder via the verification page, this also did not arrive (though it appeared as though it had sent) @kitenetter are you aware of this function working at all?

**Comment by kitenetter** [comment]
As yet I haven't seen any evidence of any emails or notifications getting through. I'm intending to do some more testing on this later today, as we need to inform the verifiers.

**Comment by BirenRathod** [comment]
@kitenetter & @Sam-Amy just to let you know that I just checked with IT and they mentioned that there are 10000+ queued emails already. That means if a user sends a new request, it will not be received until this backlog clears. At present, they can't do anything as this email system is managed by NERC. So I asked them for an alternative solution to this.

**Comment by Sam-Amy** [comment]
Does this only relate to emails from verifiers and invites to activities, or does this also include e.g. notifications? Are there any other ways that we could reduce the number of emails being sent (i.e. limit certain notification options to weekly?).

**Comment by BirenRathod** [comment]
@Sam-Amy any emails sent through the warehouse server. As I mentioned it is not in UKCEH IT control.

**Comment by Sam-Amy** [comment]
Thanks @biren, I'm just not 100% clear on which emails are sent through the warehouse server versus not, but presumably anything related directly to a record (as opposed to just the website user)?

**Comment by BirenRathod** [comment]
@Sam-Amy you can ask @johnvanbreda about which emails are sent through the warehouse.

**Comment by johnvanbreda** [comment]
@Sam-Amy Any email sent in the background will be a warehouse email. Any email sent as a result of a direct request through the user interface, such as a verifier query, will be sent via Drupal.

I guess that reviewing how many emails are being sent at the highest priority which could actually be demoted to daily or weekly would be a possible way to improve the situation.

**Comment by kitenetter** [comment]
@johnvanbreda I just tried to use the "send to expert" button from the verification page and got an error message:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/4a1451b4-fd32-4591-9e6f-fce3cc08d4d0)

I can't see any evidence that emails sent via the warehouse or via Drupal are getting through.

Based on the information Biren circulated from IT the UKCEH email systems are changing again next week in any case, so maybe we'll have to live with this for now and revisit it when the new system is in place. I'm intending to email the verifiers today and let them know that emails are not getting through. Notifications and queries remain visible via the website "My notifications" page.

**Comment by BirenRathod** [comment]
@kitenetter The evidence of sending email through Drupal has been posted above by me. Another way to check if you receive "Reset password" link to your account.

**Comment by Sam-Amy** [comment]
@johnvanbreda re: "reviewing how many emails are being sent at the highest priority which could actually be demoted to daily or weekly would be a possible way to improve the situation" - how can we do this?

**Comment by johnvanbreda** [comment]
@Sam-Amy I think we need to agree (checking with @kitenetter) that it's OK to reduce the frequency of user emails without asking them and, if so, what we are willing to change. For example it seems OK to me to reduce user's verified record notifications to daily if they are currently max priority. Once we've agreed the changes we think are OK I will then have a look at the data to try and assess the likely impact - it may not make enough difference considering we are way over the threshold. But if it looks like it's worth doing I'll run a query to update the user settings.

**Comment by kitenetter** [comment]
@Sam-Amy @johnvanbreda I wonder if we should wait until we see what happens when UKCEH change their email system next week, but if there is a potential benefit to be gained from changing the settings now I have no problem with that. It's fine to change the hourly priority emails to daily.

If we need to go further I'd be less comfortable about changing the daily to weekly without some user communications to explain what is happening. However, a weekly notification is better than no notification at all, so I'd support doing this if it looks like it will get back within the threshold.

The password reset email is being sent, so that's fine. As far as I can see, the following emails are not being sent:
- general system notifications e.g. record cleaner
- notifications of verification decisions
- notifications of queried records (i.e. when done via notification rather than via email)
- the "contact an expert" option produces an error as shown above
- querying a record via email does not produce an error message, but the emails are not getting through at the moment as far as I can tell

**Comment by Sam-Amy** [comment]
I was wondering whether in the first instance whether there is a way to report on how many of each type of emails are being sent? Looking at your list @kitenetter I also wonder if we know how much people use/value the record cleaner notifications, and whether the record cleaner flags are more important at the verification side?

**Comment by johnvanbreda** [comment]
Have sent an email regarding the main cause of notification emails.

@andrewvanbreda did you do some work recently because the Pantheon websites don't work if you use the PHP mail function and you had to use the Drupal facilities for mailing instead? I think that is the cause of the problems sending emails from the verification tool which is completely separate from the issue with the warehouse going over the threshold.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
I did look into it, but the problem is the the Drupal email functions won't send html emails without a plugin.

@BirenRathod was going to look into fixing the mail() function and Pantheon, but not sure how far he has got with that.

Details are in here,
https://github.com/BiologicalRecordsCentre/iRecord/issues/1522

**Comment by kitenetter** [comment]
Being tackled in #1522 and #1571 - closing this issue.
