### ISSUE TITLE
Performance: make it possible to cancel a query in Explore > All records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#130]
There doesn't seem to be a way to cancel a query that it likely to return (tens of) thousands of records.
**Background**: I recently changed a filter-by-Record-ID criterion from 'is' to 'is at most' before getting round to setting other filter criteria. This would not have mattered in **Verify** but in **Explore all records** it tried to include all records below 3314031 for all taxa. If the query does indeed continue running after the 'Back' button is selected, the strain on the server could be considerable.
**Suggested Fix**: implement buttons on the form for 'start query' and 'cancel query'.

**Comment by kitenetter** [comment]
Hopefully being resolved as ES filtering is implemented. Closing.
