### ISSUE TITLE
Record indexed to two VCs unexpectedly

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1300]
This (and other) records are being assigned to Cambridgeshire when the grid ref is uniquely in Bedfordshire. Is there some invisible blurring or positional uncertainty? The species is not Sensitive.
ID|status|checks	25506942 
Accepted name	Pyrrhosoma nymphula (Sulzer, 1776)
Common name (as entered)	Large Red Damselfly
Location	Myers Farm, Potton, Bedfordshire
Vice County	**Cambridgeshire | Bedfordshire**
Grid ref	TL225505
Date seen	26/05/22

The outer circle on the map does touch Cambridgeshire but the square specified does not:
![image](https://user-images.githubusercontent.com/24915271/170464369-3a878eba-77f3-4503-9e9c-9bbcd2a5953c.png)

**Comment by johnvanbreda** [comment]
The reason here is that the record was part of a larger sample and there is a sensitive record in the sample. Since sample IDs are public, the presence of the senstive record causes all the records in the sample to be blurred, otherwise it's possible to infer the precise location of the sensitive record from the others in the sample.

**Comment by DavidHepper** [comment]
I don't think the current status quo is helpful. To avoid this occurrence, I suggest that it should only be possible to set the Sensitive flag on single records, not a sample. If records of some species are made Sensitive by the system without the recorder's choice then this would require either excluding these Sensitive species from the selection lists on multi-species forms or failing the submission of the form with an error message until the offending species has been removed.

**Comment by DavidHepper** [comment]
Further to the above, the current scheme is failing to protect the badger location. I simply find the Sample ID and put it into the Search field in Explore > All records. The unblurred ref appears: 
![image](https://user-images.githubusercontent.com/24915271/171206873-cd2d8181-7303-4e6a-98fd-780beaa5f2e0.png)

**Comment by kitenetter** [comment]
The badger record is being blurred by the system to 1 km square level (a blanket operation applied to all iRecord-entered badger records), having been entered by the recorder at 100 m square level. As John says this results in the whole sample being blurred to 1 km square level. Current practice on iRecord is that if one record in a sample is blurred the whole sample has to be blurred to protect the location sensitivity.

There is room for debate over whether this is the correct approach, and that debate is ongoing for various reasons at the moment, but for now the situation is what it is. I'll close this one but will circulate any further proposals for handling sensitive records.
