### ISSUE TITLE
Enable display and download of multiple recorder names for vascular plants in iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1303]
The form here:
https://irecord.org.uk/enter-vascular-plants

allows multiple recorder names to be linked in a one-to-many relationship, but on the verification page verifiers can only see the last name entered, and in the standard download only the last name is given as the recorder.

Do we have any options for outputting all the names?

If not, should we go back to having a single one-to-one attribute for this form, in which multiple names can be entered as a text string?

Any views @sacrevert ?

**Comment by sacrevert** [comment]
Given that there is a sync in place with the BSBI DDb, I assume that it would be better to leave this as it is now and ultimately enhance the iRecord verification and download places to deal with it.

**Comment by kitenetter** [comment]
@sacrevert Do we know that the multple recorder names are visible in the DDb? If so I can let the person who queried this know (they are part of the BSBI county recorder team), and I agree with you that the ideal solution would be to enable the download process to handle multiple names.

**Comment by sacrevert** [comment]
@japonicus can you confirm?

**Comment by kitenetter** [comment]
Thanks @japonicus 

I agree that having multiple names is beneficial for the reasons you give, I just have an 'in principle' dislike of data systems that take data in which they are then unable to include in their outputs. But in this case the DDb output does include it so that is fine.

Will leave this issue open as a feature request for multiple name handling within iRecord in future.

**Comment by kitenetter** [comment]
Closing but "deferred" label indicates that we will review if needed.

**Comment by kitenetter** [comment]
Now picked up under #1848
