### ISSUE TITLE
Enable shoresearch website in ES dataset

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1304]
I've added a website agreement for website ID 121, Wildlife Trusts Shoresearch. Please add to the ES set of websites so that records are available for verification etc.

**Comment by johnvanbreda** [comment]
I've done 2 things:
1. On the https://test-brc-irecord.pantheonsite.io/ instance, I've switched the authentication method on the Explore All Records, Explore My Records, Verification - main, Verification - iNaturalist and the main download page to use a newer approach which automatically applies the correct website filter according to the website agreements. Please can you test these at some point and if they are OK we can switch iRecord over at some point.
2. Refreshed the ES aliases for reporting, verification and data flow to include the latest agreements, including website ID 121.

**Comment by robin-hutchinson** [comment]
For the pantheon site, my iRecord email and password are not working (I have typed them in manually), do I need to set up a new account for the pantheon site?

**Comment by robin-hutchinson** [comment]
Yes, that is the account

**Comment by BirenRathod** [comment]
@robin-hutchinson you need to re-register on it as these two sites (live & test) treat seperately.

**Comment by robin-hutchinson** [comment]
Ah ok, thank you Biren I will do that.

**Comment by johnvanbreda** [comment]
Apologies for rushing ahead on this, but I needed to enable the new method of authorising the verification page in order to deploy some other changes on the verification tool. So, this is now done.
