### ISSUE TITLE
Download only outputs a limited set of custom attributes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1305]
The Open University have downloaded the set of records that were imported some years ago from iSpot, using the "Download single survey" option to output the custom attributes:

![image](https://user-images.githubusercontent.com/16039111/171193301-4dc926aa-6de7-46ff-970d-19c659877640.png)

The resulting download file contains 48,906 rows, but the custom attributes are only included on the first 5,000 of those rows.

Is there a limit of some sort being applied to the download, and if so can it be removed or increased?

**Comment by kitenetter** [comment]
Hi @johnvanbreda I'm being chased on this - can you see a reason for the custom attributes to be limited in the output as described above?

**Comment by johnvanbreda** [comment]
Should now be fixed @kitenetter.
