### ISSUE TITLE
Unable to set up species alert notifications

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1307]
This was reported by one of the local govt users of the Bloomin Algae records. They have tried to set up a notification fror records of Cyanobacteria in Northern Ireland, but are unable to save the alert settings. I've just tried to do this (in Firefox) and I also get an error message:

![image](https://user-images.githubusercontent.com/16039111/171270948-bbd76f6b-3acd-4be7-921e-d1cc983d4c22.png)

Assigning to Biren but please pass on to John if needed.

High priority due to importance of species alerts for the monitoring of Cyanobacteria (and non-native species).

**Comment by BirenRathod** [comment]
@kitenetter Where can I find this settings?

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda. I found that value of alert_on_entry supply with 't' or 'f'. It should be 0 or 1. Or you can change in service to identify value if it is 't' or 'f'.
See below error ..
"{"error":"alert_on_entry has been supplied to the Species Alert service and it has not been supplied as a boolean.","code":0,"file":"D:\\websites\\warehouse\\modules\\species_alerts\\controllers\\services\\species_alerts.php","line":174,"trace":[]}"

**Comment by johnvanbreda** [comment]
Thanks @BirenRathod . The only thing that confuses me is the code always seems to have been like this so I'm not sure why it has changed. Let me know if you have any thoughts.

**Comment by BirenRathod** [comment]
@johnvanbreda The only thing changed is that I upgraded PHP 7.4 to 8.0 on the live warehouse. Has this been tested on dev warehouse?

**Comment by johnvanbreda** [comment]
The old code works on my development machine on PHP 7.4 so I think it might be that PHP 8 actually fixes a bug in the in_array() function which causes the bug in our code to start causing problems. I'll fix the warehouse...

**Comment by BirenRathod** [comment]
@johnvanbreda Thanks. there may be some other places in_array() used too.

**Comment by BirenRathod** [comment]
Thanks, @johnvanbreda.
