### ISSUE TITLE
Link to Sustrans recording form is missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1308]
The Sustrans project uses a custom recording form:
https://irecord.org.uk/sustrans-enter-record

That form is listed in the "Source" options when filtering, and the project organisers have a download filter set up to allow them to download all records entered on that form.

However, the download produces an empty file, and if you filter on this source via the Explore pages no records are shown in the ES view, although there are recent records showing in the old non-ES Explore page.

I assume that a link is missing from the ES dataset, but I'm not sure which link.

Marked as a priority because the project needs to access its data.

**Comment by johnvanbreda** [comment]
Fixed - a problem in the construction of the Elasticsearch filter.
