### ISSUE TITLE
Prevent auto-emails being sent when records are auto-verified

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#131]
For surveys that are using auto-verification (e.g. NPMS, New Year Plant Hunt) it appears that at least some records are triggering a "Verification of your records" automated email, following automated verification.

This is misleading (as the auto email says the record "was examined by an expert"), and is presumably producing large amounts of email traffic in relation to uncontroversial records of common species.

Suggest that for now we prevent auto-emails being generated in response to auto-verification.

In the longer term there might be an argument for allowing auto-emails to show that the records have been accepted by the survey concerned, but to do this we should use different text so that people aren't misled into thinking the record has been checked by an expert.

**Comment by johnvanbreda** [comment]
Closed by https://github.com/Indicia-Team/warehouse/pull/243/commits/59be552943393874188b07436d68615c265c09b8
