### ISSUE TITLE
Extend NBN Atlas exports to include Channel Islands

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1310]
NBN are keen to include Channel Islands data, and can accept it with lat/long coords. (They may be able to accept CI grid refs in future but this is not currently possible.)

Can we extend the filtering used for the exports so that any record in or near to the Channel Islands gets included, and has lat/long rather than grid ref in the output file?

For reference @johnvanbreda said:

> The filtering on the output data is based on the output_grid_ref field (see https://github.com/Indicia-Team/warehouse/blob/master/reports/library/occurrences/filterable_dwc_nbn_occurrences.xml) – if the best grid reference format selected for the record is OSGB or OSIE then it gets included. The format chosen for the output_grid_ref field is based on the following logic:
> 1. If the centre point of the record falls inside a rough bounding box covering the island of Ireland, then convert it to EPSG: 29901 (Irish National Grid). Then do a more precise check for a bounding box covering Ireland, with a corner cut off in the top right roughly half-way to Scotland. If inside this box, it’s given OSIE.
> 2. Otherwise, if it falls inside the range of the British National Grid it’s OSGB. Note that this bounding box clips part of Northern France, but doesn’t make it to the Channel Islands.
> 3. Else it will be something else…
> 
> Details of the code for selecting the output grid ref are in this function: https://github.com/Indicia-Team/warehouse/blob/master/modules/indicia_setup/db/version_4_1_1/202006231056_reduce_precision.sql
>

**Comment by johnvanbreda** [comment]
I've now altered the filter on all the new Elasticsearch exports to include records where UTM30ED50 is selected for the output system (WA/WV grid references). Is that enough @kitenetter or do we need to change the old style export as well.

The Exports folder on Elasticsearch now contains 10 freshly generated exports which include CI data.

**Comment by kitenetter** [comment]
@johnvanbreda I would say the priority is to get the ES export process fully implemented, and I don't think we need to spend time on further development of the older exports. So I think this can be closed.
