### ISSUE TITLE
Verification - Navigating to Record Details page is showing incorrect information

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#1311]
Hi @BirenRathod 

There is a problem with iRecord's verification page.
If a logged in user uses the "View this record's details page"  link to go to the page, they are incorrectly shown a reduced version of the page with a URL like this.

https://irecord.org.uk/record-details/logged-out?occurrence_id=25821863

I have had a report of this occurring with a logged in user, and I have been able to reproduce the issue.

**Comment by BirenRathod** [comment]
@andrewvanbreda I'm adding @johnvanbreda to comment on this. But when I checked logged in & logged out page, they show different results. Do you which user is this? 

See below screenshot for logged-in user.
![image](https://user-images.githubusercontent.com/5941255/174110140-a0f4e4b4-c5f3-41a4-b05e-82b4e774f608.png)

See below screenshot non-logged in user which redirected to record-details/logged-out page.
![image](https://user-images.githubusercontent.com/5941255/174110510-26f03d0a-2bfd-4390-a979-45b1f013838d.png)

**Comment by BirenRathod** [comment]
@andrewvanbreda This has resolved now. This is just the permission issue of Verifier role.

**Comment by andrewvanbreda** [comment]
@BirenRathod Thanks, that is great :)
