### ISSUE TITLE
Deleted user (causing odd behaviour with verification filter?)

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1312]
I started documenting the issue below, but I suspect that the problem is that the verifier is marked as a deleted user in the warehouse (user ID 17819). Their account is still showing as active on iRecord (/user/2038).

I don't understand how this delete can have happened. I'm hoping that if we undelete the account the links to the verification filter and comments will be reinstated.

Below is the rest of the documenation, which may not be needed if the delete is the problem:
_Last December I set up a verification filter with filter ID 16091, called "Butterflies; BRERC; Corner, Tim". I can see that filter via pgAdmin, but it has vanished from the list here:
https://irecord.org.uk/filters/admin-list

Alongside this, the verifier has reported that records are not reflecting the decisions that he thought he had applied. Also, where he has added comments these are being displayed as anonymous comments. For example, the comments added here:
https://irecord.org.uk/record-details?occurrence_id=7513352
https://irecord.org.uk/record-details?occurrence_id=11596223

On the second of those records, the auto-acceptance comment is also showing as anonymous, rather than "admin, core".

The user ID for this verifier is 17819.

I can't work out what is happening here, but it does seem very odd that the filter has disappeared from the list at the same time as the comments losing their named author._

**Comment by johnvanbreda** [comment]
Fixed. I think what has happened here is that Tim had originally registered with his own email, then changed the email to info@ and set up another account with his personal email. When he did this, the system recognised that the emails implied he was the same user and asked if he wanted to merge the accounts which he did. This left the filter orphaned. 
I've undone the deletion and correctly separated the accounts.
