### ISSUE TITLE
Can 'Vane Trap' be added to the list of sample methods?

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1314]
A user who is uploading records via a spreadsheet has asked if we could add 'Vane Trap' to the list of sample methods on iRecord - I believe this relates to the termlist for sample methods?

**Comment by kitenetter** [comment]
This could be done but raises questions about whether "vane trap" is the best term - other people use "window trap" or the more generic "flight interception trap" to mean much the same thing. There is a potentially very long list of specific method terms that could be requested, and I'm not sure how far we should try to accommodate these. The alternative for doing csv imports is to use the "Method (free text)" option, which of course allows any method text string to be imported.

Assuming this is the same query we discussed a week or two ago I suggest we contact the person who raised it and find out if they can use the free text version instead.
