### ISSUE TITLE
Reduce number of layers shown by default on verifier map

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1318]
Having logged out of iRecord and cleared cookies, I logged back in and the default map view on the verification page has three data layers ticked:

![image](https://user-images.githubusercontent.com/16039111/178765010-21cc2aa0-b32d-48e1-856c-e1d9c346a20a.png)

To help with performance, I suggest we reduce this to one layer, and my choice would be to retain the "Grid map of currently selected species". (Verifiers can of course change this selection, it is just the default option that we are talking about).

**Comment by johnvanbreda** [comment]
Done
