### ISSUE TITLE
Error in taxon name

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1325]
Indicia has the taxon "Xorides  filiformis" with two spaces between the genus name and the species name:
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/519633

This is of course incorrect. Is there any reason why I can't just edit this taxon via the warehouse to remove the extraneous space?

**Comment by johnvanbreda** [comment]
No reason, but I will need to update the lookup tables used by Elasticsearch and trigger an update for any associated records. I can do that now, independently of your change to the warehouse.

**Comment by johnvanbreda** [comment]
This problem is a little more widespread. I ran this query to check just UKSI:
```sql
select id, taxon, authority, search_code as tvk , taxon like '%  %' as taxon_wrong, authority like '%  %' as auth_wrong
from cache_taxa_taxon_lists 
where taxon_list_id=15 and (taxon like '%  %' or authority like '%  %')
```

Here's the output:
```
id	taxon				authority			tvk			taxon_wrong	auth_wrong
469177	"Microdispus  obovatus"		"(Paoli, 1911)"			"NHMSYS0021292639"	true		false
469505	"Leiobunum sp.  A"						"NHMSYS0021276176"	true		false
474285	"Siphona  lichtwardtiana"	"(Villeneuve, 1931)"		"NHMSYS0021321680"	true		false
521689	"Siphona  abdominalis"		"(Robineau-Desvoidy, 1830)"	"NHMSYS0021321675"	true		false
519633	"Xorides  filiformis"		"(Gravenhorst, 1829)"		"NHMSYS0021304983"	true		false
487890	"Siphona  verralli"		"(Wainwright, 1928)"		"NHMSYS0021321665"	true		false
510434	"Siphona  tristella"		"Herting, 1966"			"NHMSYS0021321690"	true		false
496996	"Siphona  tenuipalpis"		"(Villeneuve, 1921)"		"NHMSYS0021321685"	true		false
```

I'll fix these in Elasticsearch and assume you'll do the warehouse unless I hear otherwise.

**Comment by johnvanbreda** [comment]
The Elasticsearch aspect of this is done.

**Comment by kitenetter** [comment]
Warehouse also updated - closing.

**Comment by johnvanbreda** [comment]
@kitenetter just checking - will you let Chris Raper know about the others?

**Comment by kitenetter** [comment]
@johnvanbreda as far as I'm aware these names are all correct in UKSI, so either we introduced an extra space when importing them to Indicia, or possibly they've been corrected in UKSI since we did the last import.
