### ISSUE TITLE
Exit button needs to be pressed multiple times for images in a list of species

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1329]
I have so far replicated this issue a user is having for the entering lists of bat records and moth records:

Go to the "Enter a list" page.

Enter a list of species (there must be more than one record).
Add a photo to each record
Click on a photo you have added to view it
Try to click out of viewing the image (either through clicking the cross in the top right corner, or through clicking the grey background)
Error: you will need to click the same number of times as records with photos you have in the list in order to exit the photo viewing page.

This error is not found if multiple photos are added to the same photo in the list, but once you have added more records with photos, removing them does not decrease the number of times you need to click to exit.

**Comment by johnvanbreda** [comment]
@BirenRathod I've fixed this in the code and pushed to Pantheon dev, but when I try to deploy to the test environment the after whirring for a minute or so it just resets to where it was and the change hasn't been deployed. Any thoughts?

**Comment by BirenRathod** [comment]
@johnvanbreda this could be a implecation of @burkmarr's env created. He needs to merge those changes (including your commit and drupal update too) first on dev and then test.

**Comment by BirenRathod** [comment]
@burkmarr if you could merge those 8 commits from your branch which should allow further commit to test.

See this link -> https://dashboard.pantheon.io/sites/31e5e3d2-b700-4373-85c0-9a9fbc898fbb#burkmar

**Comment by johnvanbreda** [comment]
I thought the point of the multidev was that it allowed separate testing without blocking other changes?

**Comment by burkmarr** [comment]
I don't think it can be anything to do with my branch - surely it's completely isolated?

**Comment by BirenRathod** [comment]
> I thought the point of the multidev was that it allowed separate testing without blocking other changes?

@johnvanbreda  it certainly allows seperate testing but it should stream line with committed code. I didn't find anywhere about not pushing code on test env or seperate document of pushing code on test will cause but found workflows which suggest if you we follow that it should work.
![image](https://user-images.githubusercontent.com/5941255/182764088-af128e31-b2f6-49a8-836e-a7c7943bce82.png)

**Comment by BirenRathod** [comment]
@johnvanbreda & @burkmarr here is a link for multidev's doc -> https://pantheon.io/docs/guides/multidev

**Comment by robin-hutchinson** [comment]
Thank you @johnvanbreda , I will email the user who reported it to let them know.
