### ISSUE TITLE
Download filters producing incorrect dataset

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#133]
From Matt Smith:

I had a quick look at the NatureSpot records on the screen. However, when I tried to download the data to have a look at the complete set of records the download only produced records of Tachinid flies, not aculeates, entered via NatureSpot.  I was expecting bees!
 
Filters were as per this image:

![matt](https://cloud.githubusercontent.com/assets/16039111/21766470/a9987046-d666-11e6-954c-ee931bbd5c3d.jpg)

Selecting Tachinid flies works fine, but several attempts at downloading the aculeate data with this combination of filters only produced Tachinids, not aculeates.

**Comment by MNSmith** [comment]
Not sure if any work has been done with this but the problem seems to have disappeared and the expected data is being seen in the download.

**Comment by kitenetter** [comment]
Good - thanks for letting us know @MNSmith
