### ISSUE TITLE
Bulk record edit

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1331]
For iRecord user id: 140179 and upload date: 08/08/2022 or 09/08/2022, some records were entered with the year only and so have been interpreted as a vague date in 1905. 

Records that appear as

09/07/1905 should be 01/01/2017 - 31/12/2017
12/07/1905 should be 01/01/2020 - 31/12/2020
13/07/1905 should be 01/01/2021 - 31/12/2021

Is it possible to bulk edit these records, please?

**Comment by kitenetter** [comment]
@robin-hutchinson do you know roughly how many records are affected?

**Comment by robin-hutchinson** [comment]
It is 1151 records

**Comment by kitenetter** [comment]
Okay, this will need a database update in that case.

**Comment by DavidHepper** [comment]
Should this kind of request should be handled as a delete of the whole batch, for reimport by the user?

**Comment by kitenetter** [comment]
@DavidHepper there is a case for that, but it can be problematic if any of the records have already been verified (i.e. the verifier/s would then have to re-verify the same records following a replacement upload). And in any case we do not currently have any tools available to users to do bulk deletes of a whole batch of records, so either way a database update query needs to be run.

We do hope to develop additional editing tools for users in future.

**Comment by johnvanbreda** [comment]
That's done. Here's the script:

```sql
drop table if exists to_fix;

select id, sample_id, date_start, record_status, record_substatus
into temporary to_fix
from cache_occurrences_functional 
where created_by_id=140179
and date_start in ('09/07/1905','12/07/1905','13/07/1905');

insert into occurrence_comments (occurrence_id, comment, created_by_id, created_on, updated_by_id, updated_on)
select id, 'Imported date corrected so verification status has been reset.', 1, now(), 1, now()
from to_fix
where record_status<>'C' or record_substatus is not null;

update occurrences set record_status='C', record_substatus=null, updated_on=now(), updated_by_id=3 
where id in (select id from to_fix where record_status<>'C' or record_substatus is not null);

update samples 
set date_start='01/01/2017', date_end='31/12/2017', date_type='Y', updated_on=now(), updated_by_id=3
where id in (select distinct sample_id from to_fix) and date_start='09/07/1905';

update samples 
set date_start='01/01/2020', date_end='31/12/2020', date_type='Y', updated_on=now(), updated_by_id=3
where id in (select distinct sample_id from to_fix) and date_start='12/07/1905';

update samples 
set date_start='01/01/2021', date_end='31/12/2021', date_type='Y', updated_on=now(), updated_by_id=3
where id in (select distinct sample_id from to_fix) and date_start='13/07/1905';

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, 100, 2, now()
from to_fix;

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_update', 'sample', sample_id, 100, 2, now()
from to_fix;
```
