### ISSUE TITLE
Record verification query emails are not sending

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1332]
This was reported by a verifier and I have replicated it using the iRecord Support_2 account.

Steps:
Masquerade as iRecord Support_2
Go to the "All Accepted Species" context verification window.
Search for record ID 23736905 (I believe this will work for other records, but this one is associated with my email account so any test emails won't go to another user)
Click the query record question mark, and select to Send Email.
Click "Send email" at the bottom of the page
Error: The email is not sent (the button changes colour when it is clicked but nothing else happens, as this is going to my account I checked and no email is sent)

**Comment by kitenetter** [comment]
I've just reproduced this (using Chrome). One thing to add is that the query window itself is taking a very long time to open up when you first click on the query button for a particular record.

And just to clarify that when you click on the "Send email" button the query window does not close, nor does the email get sent.

**Comment by johnvanbreda** [comment]
I've deployed a fix to the test setup on Pantheon, however the dialog doesn't close so I'll look into that. You may get an email though @robin-hutchinson.
