### ISSUE TITLE
Problems with Spam Master Firewall - users unable to log in

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1335]
There were various discussions about this last week and we are continuing to receive messages from users who are unable to log in. Something must have changed to make this happen. Several users have tried clearing their cache but this does not allow them to log in.

Some background info from John:
> I think what is happening is that some users are accessing iRecord via a shared IP address (which most web ISPs will use) but someone else using the same IP address has abused it so that address has been blacklisted. Therefore the Spam Master module on iRecord is blocking their access.
> 
> A while ago, Biren told me that Spam Master should be only used to filter posts to the forum area of a website, not for the other stuff on the website like registration, as I originally found a similar problem to the one you’ve reported on the Garden Butterfly website. As I didn’t have a forum I simply uninstalled Spam Master on that site. However, iRecord does have a forum so I don’t really want to uninstall the module. Looking through the settings I can’t see how to turn just the firewall part off, or disable it for the login but not the forum. So I’m a bit stuck without Biren’s aid.
> 
> I can completely uninstall the Spam Master module but it will mean Biren loses the current settings and makes it much more likely that we’ll get forum spam.

I know that people are on leave but when possible we need to fix this, so I'll assign it to the August milestone.

**Comment by kitenetter** [comment]
@robin-hutchinson John also suggested that we might be able to bypass the problem by assigning new passwords to individual users. Could you try doing that for one or two people and see if it works? If it does we can do so for the other users (although this isn't a sustainable solution in the long term).

**Comment by robin-hutchinson** [comment]
@kitenetter I did try this on Friday, I had a response back over the weekend to say that this did not work:

Even after clearing the cache/data etc I can't access the login page. I'm immediately redirected to the firewall, on both browsers. It's definitely an IP issue as the same thing happens on my mobile.

**Comment by kitenetter** [comment]
@robin-hutchinson okay, sounds like we're stuck for the moment. If more messages arrive, let people know we're investigating, and we can discuss at tomorrow's meeting.

@johnvanbreda or @burkmarr please let us know if you have any immediate suggestions.

**Comment by robin-hutchinson** [comment]
@kitenetter thank you, I will go through the email inbox and do that now.

**Comment by johnvanbreda** [comment]
The Spam Master module has a firewall component which states in the configuration it is always on across the site and can't be turned off if Spam Master is used. There was a new version of Spam Master on the 10th August and the Pantheon Automation applied the updated module on the 11th. It's highly likely this is the root of the issue - either the firewall is now more aggressive in the way it detects bad IP addresses, or it has a bug. There is nothing reported on the module's issues list.

At this point, we have 2 choices. Either get Pantheon to revert to an earlier version of the module (I'm not sure how, or if this is possible). Or, just uninstall Spam Master and hope that it doesn't lead to lots of additional spam. @kitenetter & @robin-hutchinson , any preferences?

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 
I don't want to hassle Biren while he is on leave, but he has accepted the meeting invite for tomorrow morning, so I suggest we wait till then and make a decision in the morning (which may well be to uninstall Spam Master for now).

@robin-hutchinson let us know if we start to see an increase in the number of people being affected by this - if there are a lot then we might have to uninstall today.

**Comment by robin-hutchinson** [comment]
I will do - we had one new over the weekend and two this morning, which is so far comparable with last week.

**Comment by DavidHepper** [comment]
Spam Master also has IP Whitelisting, so if the problem is restricted to a few static IPs this could be a useful workaround. See > https://www.drupal.org/project/spammaster

**Comment by BirenRathod** [comment]
Thanks, @DavidHepper. I sugget we should go for a whitlist option. At present, there are not many as @robin-hutchinson suggets, so fairly easy to achievable.
Uninstalling Spammaster module is not a wise decession as I seen problem on other website lots of spam user accounts including spam forum posts.

**Comment by DavidHepper** [comment]
One of my users reported on 16/08 being blocked for the first time. Has this been resolved?

**Comment by kitenetter** [comment]
@DavidHepper as far as we're aware the blocking issue has been resolved, and at the moment the Spam Master has been disabled. If you want us to investigate your user's account could you send details through to the iRecord email address.

**Comment by johnvanbreda** [comment]
@DavidHepper just to confirm, Spam Master was uninstalled on 17/08, so it should be resolved for your user now.

**Comment by kitenetter** [comment]
@BirenRathod as far as I'm aware there are no further problems being reported, and we have not seen an influx of spam. Can we close this?

**Comment by BirenRathod** [comment]
@kitenetter yes, please.
