### ISSUE TITLE
Users unable to download csv files

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1336]
This has been reported by a user. I am not sure if it is an IP issue as I was able to download records while masquerading as their account:

I was hoping you could help me with a recurring issue I have when trying to download my records from iRecord. I am using the ‘Download records’ page accessed from the ‘Explore’ tab. I create a filter to determine the records I want to download, press ‘Download,’ and it produces the .zip file. When I click on the link to download the .zip file, it comes up with ‘This site cannot be reached.’

I have tried using iRecord in different internet browsers and the same issue occurs. 
 
My colleagues have also reported the same problem.

**Comment by kitenetter** [comment]
@robin-hutchinson do you if this issue has continued to be a problem for the user? As a one-off solution we can of course send the user the download that you have done from the masquerade. I'm not aware of similar reports from other users so please close this issue unless there is still something we need to investigate.

**Comment by BirenRathod** [comment]
@johnvanbreda if download stored somewhere else apart from files folder then there will be a problem to access that file to download.

**Comment by robin-hutchinson** [comment]
Thank you - I haven't heard back about whether this has continued to be an issue for them, so I will close this
