### ISSUE TITLE
Allow users to subscribe to forum threads

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1338]
Some users would like to receive notifications if someone replies to them in the iRecord forum. Could this be set up to either automatically subscribe someone when they comment on a thread, or allow them to choose if they would like to be subscribed?

**Comment by BirenRathod** [comment]
@robin-hutchinson I have configured the notifications for forum. So forum user should receive email notifications when somebody add or update forum.

That is for whoever create forum and reply accordingly. But apart from that somebody like you or Martin might would like to recevie notification as well. if that is the case do let, so I can one of or both email address in the setting.

At present user will receive text like this "A new content has been poste/updated on your iRecord site <br/> Submitted by : @user_who_posted <br/> New content link : @content_link".

If you want to add or modify anything in it let me know too.

**Comment by robin-hutchinson** [comment]
Brilliant, thank you @BirenRathod.

I have let the person who suggested this know that the change is in place https://irecord.org.uk/forum/feedback-and-suggestions/feedback-notifications#comment-436

**Comment by BirenRathod** [comment]
@robin-hutchinson Thanks for that. you didn't mention the eprson email address who should get notification simultaneouly when somebody add new post in forum, so that, that person will then make reponse accordingly. That person is either you or @kitenetter (Martin Harvey).

**Comment by BirenRathod** [comment]
@robin-hutchinson I have added your email address so you should be notified if somebody post or reply in the forum.

**Comment by robin-hutchinson** [comment]
Thank you @BirenRathod !
