### ISSUE TITLE
Filter which iNaturalist records come through to iRecord by last update date

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1339]
This issue is to find out whether this is possible to do within the iNaturalist API, in order to give records a moment to be disputed before they are sent through to iRecord.

**Comment by johnvanbreda** [comment]
No, unfortunately the API supports "updated_since", not "updated_before" so we can't do this.

**Comment by robin-hutchinson** [comment]
Good to know, thank you!
