### ISSUE TITLE
'Recorder' placeholder in search results is unhelpful

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#134]
Currently, for records with more than one recorder name (or perhaps for recorder name strings that are too long) iRecord displays a placeholder 'Recorder' message in search results.

Would it be possible to use a more informative string. Even if there is insufficient space for the full list then a truncated string with an ellipsis or 'First Person et al.' would be more user-friendly.

**Comment by kazlauskis** [comment]
Maybe this would help if you can separate the first word:
```css
overflow: hidden;
white-space: nowrap;
text-overflow: " et al.";
```

**Comment by japonicus** [comment]
Unfortunately, it's difficult to extract the significant part of the first name using only css. E.g. as a real example of the problem:

T.C.G. Rich, K. Wilkinson, C. Owen, M. Jones, J. Woodman

shouldn't become
T.C.G. et al.
T.C.G. Rich, K. et al.
etc.

A satisfactory solution for this might be "Rich, T.C.G. et al.", "T.C.G.Rich et al." or "T.C.G. Rich, K. Wilkinson..."

**Comment by johnvanbreda** [comment]
The reason for this code was that early apps submitted a GUID for the recorder name. As it was both long and had no spaces it messes table layout up a lot, hence the replacement with just the word Recorder.

Therefore one idea might be to skip this replacement altogether unless there are no spaces in the name and the name is over a certain length.

**Comment by DavidRoy** [comment]
Agree.  This is a legacy from the first version of the PlantTracker app. Reverting to a different threshold is a sensible immediate change

**Comment by johnvanbreda** [comment]
Needs changing across a number of report files which implement a column called Recorder, having the sql output set to "CASE WHEN LENGTH(snf.recorders)>30 THEN 'Recorder' ELSE snf.recorders END". This could be changed to skip the replacement if there are spaces in snf.recorders.

**Comment by Gary-van-Breda** [comment]
I'm changing this to WHEN (TRIM(snf.recorders) !~ ' ' AND LENGTH(snf.recorders)>30)

Note there are several reports which use a variant where the same clause is based on the cache_occurrences view (the snf.recorders is replaced with o.recorders): I'm assuming these are to be done as well.

Can I also assume that I only do the library reports, and not the (client specific?) reports under reports_for_prebuilt_forms? (There are instances under CEDar, COCoast, MNHNL, NHM, Shorewatch, UKBMS)

**Comment by johnvanbreda** [comment]
Hi Gary
I agree - only the library reports, though you might consider that this change is valid and worthy for the projects we know about (e.g. CoCoast).
Regards
John

**Comment by Gary-van-Breda** [comment]
Code lodged - pull request set up and into develop branch as well.
