### ISSUE TITLE
Habitat hierarchy for BMIG recording form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1343]
We are developing an iRecord recording form for BMIG, to allow recording of terrestrial centipedes, millipedes and woodlice. Robin has set up a draft form here:
https://irecord.org.uk/node/9097

The main thing left to do is to add a custom habitat hierarchy. BMIG have three levels in the hierarchy: a set of broad habitats, each of which has a set of more detailed subdivisions, some of which have a set of even more finely grained subdivisions.

I'm not sure how this should be set up in the warehouse to enable suitable termlists, and I'm not sure how we then implement this on the recording form so that users are guided through the hierarchy.

@robin-hutchinson to provide a full spec (based on BMIG document) to @burkmarr so that Rich can work on this in September, with Robin assisting as required.

**Comment by robin-hutchinson** [comment]
A draft spec is now in the BMIG irecord development folder.

**Comment by burkmarr** [comment]
I've created a habitat termlist for the BMIG form and linked to it from the form. 

Warehouse termlist - BMIG habitat termlist - http://warehouse1.indicia.org.uk/index.php/termlist/edit/1008 

I've recreated the form in my development environment and I will look at the remaining requirements on there because I think that it will require some JS code. I'll keep the issue updated.

**Comment by burkmarr** [comment]
@BirenRathod - This new record entry form for BMIG needs some custom JS code - https://irecord.org.uk/node/9097. I've developed and tested the code locally and used Cyberduck to copy it to the `sites/default/files/indicia/js` folder. All seems well and it is reachable here: https://irecord.org.uk/sites/default/files/indicia/js/node.9097.js

However the page does not pick up the custom code. I've tried refreshing the cache but to no avail. Any ideas?

**Comment by BirenRathod** [comment]
@burkmarr What can you expect of happenning of node.9097.js code?

**Comment by BirenRathod** [comment]
@burkmarr I have published the form and it works if I change any of those haibitats in dropdown list.

**Comment by burkmarr** [comment]
@BirenRathod - yes it is working now! I unpublished it again to see if that had any effect, but it still works when unpublished - very odd! Anyway it's working now so thanks for taking a look.

**Comment by burkmarr** [comment]
@robin-hutchinson - do you want to take a look to see if it meets the spec you can me?

**Comment by BirenRathod** [comment]
> @BirenRathod - yes it is working now! I unpublished it again to see if that had any effect, but it still works when unpublished - very odd! Anyway it's working now so thanks for taking a look.

I know, it has got nothing to do with publish/unpublish but it needs to save form after you copied js file, so it will create new cache which works with it.

**Comment by kitenetter** [comment]
I think this recording form is fine to pass on to BMIG for testing, so I have published it and will send them the link.

**Comment by kitenetter** [comment]
Awaiting feedback from BMIG.
