### ISSUE TITLE
Incorrect VC allocation

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1344]
Record ID 15105500 has been indexed to Berkshire VC but is a long way outside that county.

Is it possible for me to correct this or does it need a database update?

**Comment by johnvanbreda** [comment]
You could probably have edited and resaved the record, but I just added it to the work_queue for spatial reindexing which should do the trick. The sample was edited and the coordinate moved - I'm not sure why this didn't trigger reindexing at the time though.
