### ISSUE TITLE
Transfer NBN export files exported under old system

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1348]
We need to send off the set of files for NBN, using the old system process - please can you copy across the files that we currently have.

Is it also possible to trigger a new export for the caddisfly recording scheme so that this one is as up to date as possible.

I need to send them off tomorrow - sorry for short notice due to having been on leave last week unexpectedly.

**Comment by kitenetter** [comment]
I've just re-triggered the caddisfly export from this page:
http://192.171.199.201/exports

I hope that will have generated a new file by tomorrow morning.

**Comment by BirenRathod** [comment]
@kitenetter I have copied those files now.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - closing.
