### ISSUE TITLE
Filtering for bats doesn't include "Chiroptera"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#135]
Our verification filters for bats are currently set to include all species in families Rhinolophidae and Vespertilionidae. However, there are quite a lot of records of unidentified bats that have been recorded at order level, as Chiroptera.

It is possible to set up a filter for Chiroptera, but this filter still excludes records entered as Chiroptera (this behaviour seems to be different from other filters, e.g. if you filter for family Carabidae you can see the records entered at family level).

**Comment by johnvanbreda** [comment]
One of those ones where once I'd worked out the cost of the fix, it was easier to apply the fix (but only in the develop branch).
The searches were failing to find taxa higher than family. V2 includes a new way of doing hierarchical queries so it's been updated to use that.

**Comment by johnvanbreda** [comment]
Tested on irecord_dev and seems OK against v2 warehouse.
