### ISSUE TITLE
Garden Butterfly Survey capturing records of a mite

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1350]
The GBS dataset on iRecord has 54 records of the mite Camisia lapponica. I assume this is an error, but I don't know what might be causing it.

@DavidRoy who has the overview of the GBS website? We seem to be accumulating a number of glitches with it at the moment.

**Comment by DavidRoy** [comment]
@johnvanbreda - can you liaise with BC over this issue and #1351

**Comment by johnvanbreda** [comment]
I've fixed this issue - a typo in the configuration for the data entry form. Existing records and new records should now use the correct ID for Dark Green Fritillary.
