### ISSUE TITLE
Garden Butterfly Survey - grid ref questions

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1351]
If I try to enter a GBS record on my Android phone, I can't find any way of setting the grid ref from the map. Tapping on the map produces no result.

(We have some records with very misleading grid refs that apparently originate from someone entering them via a phone.)

**Comment by johnvanbreda** [comment]
Is it the garden details on the user registration page that has the problem? You don't actually use a map on the data entry page. Tapping the map on the garden details for the user registration works OK on my iOS phone but I don't currently have an Android phone to test.

**Comment by johnvanbreda** [comment]
1. That's fine - it won't conflict.
2. Just the recorder, or someone with masquerade rights on the GBS website.
3. No, it won't affect existing records.
4. That shouldn't happen - when they enter a list of records, they choose the garden but cannot set the grid reference. The records form does not have a control for the grid ref or a map, just a selector for the garden. So the records are always given the garden's grid ref.

**Comment by kitenetter** [comment]
I can persuade my android phone to pick up a grid ref from the map, but only if I repeatedly and rapidly drum two fingers on the map! Same behaviour on Nina's android phone.

**Comment by kitenetter** [comment]
On point 4, I haven't actually tried saving a record, but it looks like when you go to the record page you are given the default grid ref for your garden. However, you can over-ride this by manually typing in a different grid ref, or by using the "Find my current location" button.

I've just tried entering a record using "Find my current location" to add a grid ref that is different to the default grid ref, and the record saves, but if I then try to edit it it appears to have reverted to the default grid ref that I originally set up for the garden.

Which is presumably what is supposed to happen, but if so there seems no point in having an editable grid ref box on the "enter sightings" page https://gardenbutterflysurvey.org/enter-sightings

**Comment by kitenetter** [comment]
On point 2, I cannot see anywhere within the GBS website that allows a recorder to edit the default grid ref that they have originally set up.

**Comment by kitenetter** [comment]
Note to self: it is in fact possible to enter a grid ref for a particular record that over-rides the default grid ref set up for the garden, although it isn't very obvious that this is happening during data entry. I'm not sure that is helpful - presumably this survey should always be for records linked to a specific garden? Will raise with BC.

**Comment by kitenetter** [comment]
Have passed info on to Chloe at BC - closing.
