### ISSUE TITLE
Verification reporting index error

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1353]
It feels like I'm seeing this error more and more frequently:

![image](https://user-images.githubusercontent.com/16039111/190866658-65c9f958-b532-4a1b-a5e0-b1f36ee2f14a.png)

I _think_ records are being verified correctly, as the message states, but it doesn't inspire confidence, and slows things down.

Do we know the underlying cause?

**Comment by johnvanbreda** [comment]
Please can you try to reproduce this error with the developer tools running, then send the HAR file.

**Comment by kitenetter** [comment]
Haven't encountered this recently. Closing.
