### ISSUE TITLE
Data for NBN Atlas

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1357]
As usual, we need to generate this month's set of files for NBN Atlas.

@BirenRathod please can you copy across the files that we currently have from the old export process.

@johnvanbreda please can you trigger the new batch file process.

**Comment by BirenRathod** [comment]
@kitenetter I have copied those files now.

**Comment by johnvanbreda** [comment]
This is done now @kitenetter

**Comment by kitenetter** [comment]
Please can @johnvanbreda and @BirenRathod copy over this month's datasets (I need to send them off on Friday).

**Comment by BirenRathod** [comment]
@kitenetter I have copied now.

**Comment by johnvanbreda** [comment]
@kitenetter All the Elasticsearch generated files are now ready.
