### ISSUE TITLE
BTO non-avian taxa import has pulled in out-of-range records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1360]
One of my dragonfly verifiers reports:
> I have about 1500 old records from one observer arrived into iRecord from the Birdtrack route. These date from 2012. I have done a random check of about 10 records and ALL are repeats/duplicates that are already present as verified records. I propose to bulk reject these as duplicates with a note as you describe below. Hope you agree with this. 

Our agreed import spec should prevent import of records with an external key lower than OBS290186151 but it appears that "old" records that we have already manually imported are being regenerated in BirdTrack with higher OBS key numbers. 

Also, some are being imported that do not match the restrictions on Geographical Uncertainty, such as iR ID 24238020.
This has an output grid ref of "TQ" from a BTO-specified grid ref of "TQ96", neither of which meet our criteria of monad!

Please investigate how these have got past the criteria. I can provide lists of records if necessary. They really must be deleted.

**Comment by DavidHepper** [comment]
I'm in contact with Steve Pritchard to work out how these records are getting through. There are some unexpectedly old records, back to 1980, too.

**Comment by kitenetter** [comment]
@DavidHepper I'm going to close this one for now and focus on #1316 when we are able to next work on this, but let me know if you have any further feedback from your discussions with Steve.
