### ISSUE TITLE
Change Chorthippus parallelus to Pseudochorthippus parallelus

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1361]
The preferred name of Meadow Grasshoppers has been changed in the UKSI (https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021583970), and Bjorn has asked if we can change this in Indicia as currently iNaturalist records are not uploading because the species names do not match.

Is it possible to change this species in Indicia, please?

**Comment by robin-hutchinson** [comment]
There are a couple of other orthopterans that also should be changed to reflect the UKSI if possible:

Ectobius panzeri is now Capraiellus panzeri (https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021584595)
Acanthoxyla prasina subsp. geisovii is now Acanthoxyla geisovii (https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000006812)
Acanthoxyla prasina subsp. inermis is now Acanthoxyla inermis (https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000005380)

The Acanthoxyla species are moving from iNaturalist ok, but Capraiellus panzeri is not flowing through correctly.

**Comment by kitenetter** [comment]
@robin-hutchinson I'm hoping that these are all updated now, could you check (e.g. via the "Enter a casual record" page) and if all is well close this issue?

**Comment by robin-hutchinson** [comment]
Just checked these and they are all there correctly, closing the issue now.
