### ISSUE TITLE
update filter categories on notifications page

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1362]
Update the filter categories. The aim is to make it easier for users to see queries that need a response from them in order to progress the verification process.  

The "Rejections and queries" filter currently shows notifications with the following logic
•	The RECORD's status must be rejected or dubious
•	The NOTIFICATION's type itself is related to verification, but isn't a comment

Perhaps by separating rejections and queries (but I'm not sure if the current 'rejections and queries' includes records queried by the verifier before any status is given)?

**Comment by kitenetter** [comment]
What I would ideally like to see on the notifications page (on iRecord and on NPMS) are these categories, with no. 1 as the top priority that should be as easy as possible for users to see:
1. "Record queries" = notifications of any queried records, which will show either the comment added to a query, or the message that an email has been sent if the query was done via email. My understanding is that when a record is queried this results in a flag being added to the record (e.g. in attribute cache_occurrences_functional.query), and that the query status is independent of any verification status. Rationale: we would like all users to be alerted to any query on their record, in the hope that this will encourage them to reply to the query.
2. "Re-identifications" = notifications of redeterminations. I'm not sure whether we do actually provide notifications of this at present? But I think we should if we can. Rationale: it's good for users to know if a record has been redetermined, as they may learn something from the process, or they may wish to offer further evidence in support of the original determination.
3. "Comments = notifications of non-verification comments added to records (e.g. comments added by other users). Rationale: there are relatively few of these comments, but it's good for users to be aware of them when they are added.
4. "Records not accepted" = notifications of any records verified as "Not accepted". Rationale: users may wish to offer additional evidence in support of a rejected record.
5. "Records accepted" = notifications of any records verified as "Accepted". Rationale: it's good to provide this positive feedback to users, but regular recorders will receive large numbers of these emails and probably won't want to see each one individually.
6. "Automated checks" = notifications of automatic record cleaner responses. Rationale: although in theory these are useful feedback for recorders, there are often so many of them, and often highlighting relatively trivial issues, that users probably won't want to see every one.
7. "Requests to join a group that you administer" = as currently used in iRecord.

Is this achievable?

**Comment by johnvanbreda** [comment]
I've fixed the rejections and queries category and added a separate queries category. Most other tweaks suggested are done, not the re-identifications one though.

**Comment by johnvanbreda** [comment]
For the re-identifications item, currently there are no notifications for this category. There are 2 options:
1. When a user changes the identification on any record, add a comment automatically explaining the change. This can then be picked up as a comments notification. Note that the change would appear as a comment and a redet on the record details page.
2. Create a new category for redet notifications, then trigger that notification type directly without requiring a comment. This is slightly more work but won't result in the duplicate information on the record details.

We could potentially prevent the notification being generated if the user redets their own record.

**Comment by johnvanbreda** [comment]
Option 2 - create a new category for redet notifications, will be required so that the notifications page can provide filter options for redets separately to other miscellaneous comments. Wait until further review of the notifications system before making any changes.

**Comment by kitenetter** [comment]
At the moment the notification categories on the iRecord "My notifications" page are ordered as follows:
1. Record queries
2. Records accepted
3. Records not-accepted
4. Rejections and queries
5. Record comments
6. Automated checks

Item 2 on that list should be moved to below item 5.

Do we need item 4, which seems to duplicate items 1 and 3?

**Questions**
- What defines a record comment?
- More specifically, when a record is accepted, and a comment is added to the verification decision, is that treated as "Records accepted" or as "Record comments"?

**Redets**
I think your option 2 is preferable. I am again unclear whether the redet itself constitutes a comment, or whether this depends on whether the redeterminer has typed in a comment.

**Ordering**
My ideal outcome would be for the categories to be subdivided and ordered in the same way on the website, in the email notifications, and in the user account notification settings. The order should be:
1. Record queries
2. Records not-accepted
3. Redeterminations
4. Record comments
5. Records accepted
6. Automated checks

In the notification emails the ordering of the contents should reflect the above list.

In the account settings people should be able to opt in or out of each category (although we should strongly advise peopel to accept notifications for queries, if nothing else).

**Comment by DavidHepper** [comment]
How about making the naming more consistent and requiring less reading? Since 'Records' is really common to all and based on your revised ordering (above), the list becomes: 

 1. Queried
 2. Not accepted
 3. Redetermined
 4. Commented on
 5. Accepted
 6. Failed automated checks

**Comment by kitenetter** [comment]
Thanks @DavidHepper that's a good suggestion and I agree with all of your wording.

**Comment by johnvanbreda** [comment]
Coding now done for all this. Includes a bit of a tidy up of the different notification source types - so queries and redets now have their own notification.source_type value.
Will be deployed at the next release.
