### ISSUE TITLE
Add species to mammal form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1365]
We've been asked to enable records of Beaver (Castor fiber) to be added to this form:
https://www.brc.ac.uk/mammals

The form links to the "Mammal Atlas" survey (survey ID 35), which uses a custom taxon list "Mammals (MamSoc)" (ID 22). That list already includes Beaver, but the "Allow data entry" box was unticked. The species page in the warehouse is:
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/260536

I have now ticked the "Allow data entry" box, and cleared the Indicia cache, but Beaver is still not appearing as an option on the recording form. Is there something else that needs to be done?

**Comment by BirenRathod** [comment]
@kitenetter it will take time to update list but trick is that re-save data entry form and it will get full list.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - closing
