### ISSUE TITLE
Registration query

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1366]
Mark Gurney registered a new account on iRecord yesterday, using an email address that he had not previously used. The new account has ended up being linked to Mark's existing iRecord account, i.e. the new one is linked to the same warehouse ID as the old one. Mark says he did not see a pop-up asking if he wanted the accounts to be merged, and in fact he does not want the account to be merged.

I don't understand why they were linked automatically, I've not seen that happen before.

This is for warehouse user ID 82440 (which was first set up in 2014). The email address stored in the People table is now showing as the new address that Mark added yesterday.  This user is linked to websites iRecord; National Plant Monitoring Scheme; Pantheon.

That warehouse ID is linked to iRecord user 16717, username "MarkGurney"; if I log in as that user I can see 10,450 "My records".

The same warehouse ID is also linked to iRecord user 124485, username "Mark Gurney RSPB"; if I log in as that user I can see the same set of 10,450 "My records".

Can iRecord user 124485 be separated from warehouse user ID 82440 and linked to a new warehouse ID.

**Comment by kitenetter** [comment]
Actually it is possible that when Mark registered in 2014 he used the work email that he had at that time. He subsequently left that job, and probably edited his iRecord profile to a non-work address. He's now gone back to a job at the same organisation, so when he registered the 'new' email address it may have matched the address that he originally used in 2014.

Are we able to disentangle these accounts?

**Comment by johnvanbreda** [comment]
Your synopsis of what happened is correct. I've removed the "new" email address from the old account and re-linked the new account to the warehouse, creating a new warehouse user ID.
