### ISSUE TITLE
iRecord performance problem?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1367]
I've just had a report from a verifier that "records aren't clearing when I verify them, and keep coming up again and again".

I can't immediately replicate that, but with the first record that I verified just now I did get the egg-timer for a while, followed by an error message: "An error occurred whilst updating the reporting index. It may not reflect your changes temporarily but will be updated automatically later."

Is there any indication that something has gone wrong this morning?

**Comment by johnvanbreda** [comment]
Our Elasticsearch instance seems to be locked as read-only. I found this link:
https://stackoverflow.com/questions/50609417/elasticsearch-error-cluster-block-exception-forbidden-12-index-read-only-all

As a result, I ran the following in Kibana which has fixed it:
PUT /_all/_settings
{"index.blocks.read_only_allow_delete": null}

@BirenRathod please can you look into why this might have happened, e.g. a disk space issue?

**Comment by BirenRathod** [comment]
@johnvanbreda There is no disk space problem. it has still got 21 GB left. 

I found below error from logstash logs & elasticsearch logs.
[2022-10-19T10:29:30,448][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 403 ({"type"=>"cluster_block_exception", "reason"=>"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"})
[2022-10-19T10:29:30,448][INFO ][logstash.outputs.elasticsearch] Retrying individual bulk actions that failed or were rejected by the previous bulk request. {:count=>1}

[2022-10-19T00:47:20,255][WARN ][o.e.x.m.e.l.LocalExporter] [cqsTpEW] unexpected error while indexing monitoring document
org.elasticsearch.xpack.monitoring.exporter.ExportException: ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]

**Comment by johnvanbreda** [comment]
Yes, that's the same error I found, which I think means that the Elasticsearch cluster when read only because of some problem.

**Comment by BirenRathod** [comment]
@johnvanbreda The cause of this porblem is this -> The low disk watermark has been exceeded in the following node/s:cqsTpEW

Now there are three options to resolve this.
1. to delete this node/s:cqsTpEW
2.  Increase percentage of low disk watermark
3.  I will IT team to increase disk size upto 300GB. (Not sure they will agree but I will try my best.)

**Comment by BirenRathod** [comment]
@johnvanbreda One more thing ...

The number of shardes allowed per node is unlimited, we could limit that to upto 1000.

**Comment by BirenRathod** [comment]
@johnvanbreda I have limited the shardes value to 1000 including taking action of low watermark disk value. I got below log from elasticserach.
[2022-10-19T11:54:19,846][INFO ][o.e.c.r.a.AllocationService] [cqsTpEW] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[occurrence_brc1_v1][3]] ...]).

**Comment by BirenRathod** [comment]
@johnvanbreda Our IT team has kindly increased the disk size to 300GB. That means the error which we got about low disk watermark will no longer be produce. 
It is not straight forward. I had to implement a cluster settings of it. Let me know if you notice any unusaul things.

**Comment by kitenetter** [comment]
As far as I'm aware this particular issue has been resolved - closing
