### ISSUE TITLE
Request for two new NBN export routines to be set up

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1368]
We need two new exports please.

**NBN - Small Acalypterate Families**
This uses the filter "NBN - Small Acalypterate Families":
https://irecord.org.uk/filters/admin-edit?filters_user_id=13456

**NBN - Diptera non-scheme**
This uses the filter "NBN - Diptera non-scheme":
https://irecord.org.uk/filters/admin-edit?filters_user_id=6811

EML files (corrected versions at 28 Oct 2022):
[NBN eml files.zip](https://github.com/BiologicalRecordsCentre/iRecord/files/9887455/NBN.eml.files.zip)

Ideally needed by the beginning of November, but can go to the following month if that's not possible.

**Comment by kitenetter** [comment]
The filters are now finalised. Hoping we can get this set up before the next NBN deadline, which is 4 November.

**Comment by johnvanbreda** [comment]
@kitenetter doing these now. Please can you let me know the datasetName and rightsHolder to set for the records in each of these datasets.

**Comment by johnvanbreda** [comment]
These are both done now and the exports generated.

**Comment by kitenetter** [comment]
@johnvanbreda for this month's exports, the new process has generated a file for "NBN - Diptera non-scheme" that contains 28,813 records. However, the old version of the file (which also got generated) contains 72,764 records.

I can't remember whether the new process is still being driven by the filters set up on iRecord, which for this dataset should be:
https://irecord.org.uk/filters/admin-edit?filters_user_id=6811

I have had to edit that filter a few times over the last month or two. Should the edits get picked up by the new process?

No urgency to regenerate a file as I can use the old format one, but it would be good to sort it out for the next upload.
