### ISSUE TITLE
Editing permission anomaly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1369]
I'm currently logged in with my personal (non-admin) account, but it appears that I am able to edit the Help pages. I don't think this should be possible!

However, if I log in with one of my other accounts that have no roles at all, the edit option is not there. So it may be that it has become linked to the verifier role.

Can you check the permissions for this please Biren.

**Comment by BirenRathod** [comment]
@kitenetter which role has got of your personal (non-admin)?

**Comment by BirenRathod** [comment]
@kitenetter if your personal (non-admin) account has got "Site Editor" role then yes you can edit those help pages. so need to make sure if people needed that role.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - my account has the role "help editor" which I had completely forgotten about, sorry. False alarm - closing.
