### ISSUE TITLE
Last page of search results includes no records, page navigation buttons missing

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#137]
For the past few days (since I deleted ~ 20 records), the search results table under My Records (masquerade as 'Tom Humphrey') claims that I have a total of 141 records, whereas I actually have only 140. 

![screenshot 2017-01-12 00 14 55](https://cloud.githubusercontent.com/assets/207360/21871911/28926c1a-d85d-11e6-8ed4-6e7c4e891256.png)

Clicking on the 'last' button of the search results page (or on page '8') displays a search result page with no records.  The blank results page has no navigation links so I cannot return to earlier parts of the result set.

![screenshot 2017-01-12 00 15 09](https://cloud.githubusercontent.com/assets/207360/21871917/2dc302f8-d85d-11e6-86bd-25f91fab29fb.png)

**Comment by kitenetter** [comment]
Being looked at under #340 - closing this one.
