### ISSUE TITLE
Handling of notification deletes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1372]
If you go to "My notifications" on the iRecord website, you can filter for particular types of notification, e.g. "Automated checks". Having done that, you can click on the button to "Acknowledge all your notifications". You are then shown a message which says that only the auto-check notifications will be deleted:

![image](https://user-images.githubusercontent.com/16039111/202920504-81852312-93bf-453a-9812-75d0ad2aad83.png)

However, in fact all notifications of all types are deleted.

Ideal solution would be to only delete the notifications that are linked to the current filter.

If that can't be done, the pop-up notice wording needs to change to make it clear that all notifications are being deleted.

**Comment by johnvanbreda** [comment]
Coding completed for this - the acknowledge button will only affect notifications loaded by the current filter (i.e. the current notification type and with any grid filters applied).

**Comment by johnvanbreda** [comment]
The notifications page on the test site now has the new functionality available for checking.

**Comment by kitenetter** [comment]
I went to Explore - My notifications, and filtered for Failed automated checks. Currently 43 notifications are displayed under that filter. I then clicked on the button to Acknowledge this list of notifications. However, this does not seem to have resulted in any change - the page goes back to the full list of notifications, and the automated check notifications are still being displayed.

**Comment by johnvanbreda** [comment]
Fixed.
