### ISSUE TITLE
Mammal Mapper record creation

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1373]
We have had an issue reported on the Mammal Mapper of photos not coming through from the app, and records not being from the account that made them.

"Just submitted a rabbit record that has a photo – see attached screenshot.
It arrives as record 28728624 but with no photo – I can see this as a verifier for Yorkshire, but not through “Explore my records”."

"More or less every mammal record I submitted since 2019 did not link to my email address and gets the “Recorder was not logged in” message showing the link with Mammal Mapper was not working."

I checked pgAdmin, and for the Mammal Mapper website, all records are being created by brc_read_only:

SELECT year, user, count(occurrence) as total_records
FROM (SELECT DISTINCT o.created_by_id AS user, extract(year from o.created_on) AS year, o.id AS occurrence
FROM cache_occurrences_functional o
WHERE o.website_id in (120) 
AND o.training = FALSE 
AND (extract(year from o.created_on)) > 1999) data
GROUP BY year, user

**Comment by kitenetter** [comment]
@robin-hutchinson as far as I'm aware this is working as expected. Mammal Mapper is not an Indicia-based app, so there is no direct link to users on the app. The records are imported into Indicia to make them available for verification. Where available, a link is provided to any photo, but the photos are hosted in the app infrastructure in Coreo, not in Indicia, and do not display on the Explore pages.

So all Mammal Mapper records will show that the recorder was not logged in to Indicia.

I don't know if there is any filtering on photo licences that might prevent some photos from appearing in iRecord, but I can't see anything in the app itself that allows a licence to be set.

If the person enquiring wants to know more it's best if they talk to the Mammal Society. There are contact details at the foot of this page:
https://www.mammal.org.uk/volunteering/mammal-mapper/

**Comment by robin-hutchinson** [comment]
Thank you, Martin, I have let them know!
