### ISSUE TITLE
Species name searches behaving differently on "List" forms and "Casual" forms

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#138]
If you enter the dragonfly genus "Ischnura" into a "List records" form you are offered a mix of Welsh names and scientific names, but no English names. So the only way you can record "Ischnura pumilio" is by adding it as a Welsh name:

![image](https://cloud.githubusercontent.com/assets/16039111/21894842/91e9103a-d8d8-11e6-8a22-15a00e1ba428.png)

If you enter the same genus into a "Casual records" form you are offered a wider range of names, and can choose "Ischnura pumilio":

![image](https://cloud.githubusercontent.com/assets/16039111/21894914/d019415e-d8d8-11e6-82fb-215fb5934a9d.png)

The latter behaviour is preferable, but I can't see anything in the form settings that would influence this behaviour - is there a setting somewhere that would allow the List form to behave in the way the Casual form does?

**Comment by JimBacon** [comment]
Looking at the request to and response from the server, both forms have the same list of 7 species provided to them. The List Record form drops _Ischnura pumilio_ and _Ischnura elegans_. 

The code that processes the results is quite distinct between the solitary autocomplete and the much more complex species grid. If you look at the end of https://github.com/Indicia-Team/media/blob/master/js/addRowToGrid.js, around line 898, you will find the function that parses the list of species obtained by the grid.

At line 907 there is a comment 

> note we track the distinct ttl_id and display term, so we don't output duplicates

but the subsequent line tracks `taxon_meaning_id`, not `taxa_taxon_list_id`, plus a display attribute which is undefined (although it may have existed when the code was written).

You can see from the data like
```
"taxa_taxon_list_id":"250225",
"original":"Ischnura Brin",
"taxon_meaning_id":"106066",
"preferred_taxon":"Ischnura pumilio",
```
and
```
"taxa_taxon_list_id":"250221",
"original":"Ischnura pumilio",
"taxon_meaning_id":"106066",
"preferred_taxon":"Ischnura pumilio",
```
that the vernacular name and the scientific name have the same meaning so the second one is filtered out as a duplicate.

This was a modification made by John to eliminate some other problem, see https://github.com/Indicia-Team/media/commit/2e7e26d2d0614e0773a0d915c4f4543777bdb759.

A possible resolution is to replace `item.taxon_meaning_id + '_' + item.display` with `item.taxon_meaning_id + '_' + item.taxon`. This would only filter out cases where the same name with the same meaning is duplicated.

**Comment by kitenetter** [comment]
The issue from the recorder's perspective is that the name they choose gets stored in the database (if I understand things correctly), and as things stand it is not possible to record "Ischnura pumilio" unless you enter "Ischnura Brin". So although in one sense it doesn't matter, because the end meaning comes out as Ischnura pumilio either way, it is confusing for recorders to have to use a Welsh name to record a widespread species.

One solution would be to provide iRecord users with an option to switch between different vernacular name languages, but I'm assuming that would not be straightforward to implement. So if your suggested change to "item.taxon_meaning_id + '_' + item.taxon" will reinstate the English names alongside the Welsh ones then I think that would be a better short-term solution.

**Comment by JimBacon** [comment]
Yes, its a bug. They are supposed to be offered both common names and scientific names and the scientific name is being removed erroneously. I proposed a change which would fix this issue, hopefully without introducing a new one. 

The common names are selected without regard for the user's language from these options:
![post](https://cloud.githubusercontent.com/assets/2545390/21925007/6831055e-d973-11e6-8d56-ed019db11172.png)
You may wish to raise a separate feature request for an option "Allow common names in the user's language or preferred latin names". Given that it is a combination of currently available choices I don't imagine it would be too hard to implement.

**Comment by Gary-van-Breda** [comment]
Code for Jim's suggestion lodged into Git.

**Comment by johnvanbreda** [comment]
Code deployed to iRecord.

**Comment by DavidHepper** [comment]
I confirm that the picklists look consistent and correct now on the 'list' type entry forms. However, I'm now puzzled that I cannot find the picklist for **Species Names Filter** (as in the screenshot above by Jim on 13 Jan) to test it fully. It isn't in my Account Preferences. I can only find the little Filter button above the Species field of the form itself: ![image](https://cloud.githubusercontent.com/assets/24915271/26068626/ffd6a0da-3995-11e7-8e6d-94bacccfc964.png) that shows the four options

**Comment by Gary-van-Breda** [comment]
The **Species Names Filter** is part of the web page configuration, and defines how the species list as seen by the user will behave: as such it is not visible to the general user, only the administrators of the website.
