### ISSUE TITLE
Datasets for NBN Atlas

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1380]
Please can @johnvanbreda and @BirenRathod copy over this month's datasets (I need to send them off on Friday).

**Comment by BirenRathod** [comment]
@kitenetter The datasets have been copied.

**Comment by johnvanbreda** [comment]
I've updated all the ES datasets as well.

**Comment by kitenetter** [comment]
Thanks - closing.
