### ISSUE TITLE
Verify: querying a pending record sometimes results in a double dialog

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1384]
I queried record 25791731 and was presented with overlapping dialog boxes: 
![image](https://user-images.githubusercontent.com/24915271/205063633-9706b779-8175-493a-a1ea-025ef9496f73.png)
whereas querying 25791732 only showed the lower (simpler) dialog.
The record _does_ have an email address.

**Comment by kitenetter** [comment]
So far I have been unable to reproduce this - has it happened more than once @DavidHepper?

**Comment by DavidHepper** [comment]
I've not had it reported by any of my verifiers and don't do much querying of records. Happy to close for now.
