### ISSUE TITLE
Moth night locations

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1391]
The Moth Night surveys (e.g. survey ID 696 for year 2022) have a custom attribute for "Moth Night Site". This is displayed to verifiers as a custom attribute in the record details panel on the verification page, but does not get shown in the main "location" column, nor does it get output in the standard data downloads.

I would very much like to resolve this for Moth Night 2023 (if that happens) and ideally would like to fix it retrospectively for previous years.

In the attribute settings I can apply a system function to the previous surveys, but the only relevant option seems to be "Linked location ID". Two questions:
1. If I did set that as the system function, would it have the effect of making "Moth Night Site" behave like a normal location name, or is it more complicated than that?
2. And I assume that if a change was made it would not be applied retrospectively. Do we have a way of doing that? I guess it could be tackled via a database update, but in this case I think we should avoid re-triggering the records for verification (on the grounds that we are not changing anything in the record, we are just moving a piece of information into a different column).

Depending on the answers we can consider whether a database update would be appropriate.

**Comment by johnvanbreda** [comment]
Linked location ID should be an integer custom attribute containing the location ID of an associated entry in the locations table, so that won't work. If the Moth Night Site is now going to appear in the location field value in downloads and the verification system, why would we not just move the value into the samples.location_name field?

**Comment by kitenetter** [comment]
Good question. I don't know why Moth Night was set up in the way that it was. I will ask BC if this can be changed.

**Comment by DavidRoy** [comment]
Jim and Les setup the first survey I believe

**Comment by kitenetter** [comment]
BC have advised that we should wait for their next Moth Night planning meeting before taking action.
