### ISSUE TITLE
Pre-populate comments for redets

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1393]
Many verifiers add a comment when redetermining records. When the recorder then receives a notification it may not be clear that the comment refers to a redet. This suggested pre-population is intended to help both verifiers and recorders.

Proposal is to to auto-populate the redet comment box with:
- Redetermined from [rank] [taxon A] to [rank] [taxon B].

The verifier could then add any further comment they wish.

Supplementary question 1: can we add the "use template" button to this comment box as proposed for other comments? - see #1392 

Supplementary question 2: can we make the taxon names intelligent and provide English if the record was entered with English, or scientific otherwise? Would need to allow for redet from a taxon with an English name to a taxon without. This would be a nice-to-have, but the main requirement can be satisfied with using the scientific name (to which the verifier could manually add an English name if needed). Or we could consider extending the text:
- Redetermined from [rank] [taxon A scientific (taxon A English)] to [rank] [taxon B scientific (taxon B English)].

**Comment by johnvanbreda** [comment]
1. Yes, we can integrate this with the new templates tool.
2. Yes, that's also possible.

Here's a summary of progress so far.

A default comment template is loaded when the redet popup is shown. Note that this uses tokens in {{ }} which will be replaced when the comment is saved:

![image](https://user-images.githubusercontent.com/2392594/210530550-08714ae0-eae7-431a-b053-a9c7644dc892.png)

They can click [preview] to view the comment in its final form:

![image](https://user-images.githubusercontent.com/2392594/210530610-e3a7f15e-c31f-4258-812f-8828065f8578.png)

Then click [edit] to return to the edit box.

[save template] will show a popup box allowing you to specify a template name for the current text (not implemented yet).

[help] will show a popup box with a list of the template tokens you can use (not implemented yet). Here's a suggested list:

- {{ date }}
- {{ entered sref }}
- {{ species }}
- {{ common name }} – will revert to scientific name if no common name
- {{ full taxon name }} (scientific name, plus common name in brackets if there is one)
- {{ rank }}
- {{ action }} – always redetermined (for consistency with other verification templates)
- {{ location name }}
- {{ new species }}
- {{ new common name }}
- {{ new full taxon name }}
- {{ new rank }}

If they have previously saved any templates, then there is a drop-down for selecting one, which loads the template into the comment box:

![image](https://user-images.githubusercontent.com/2392594/210530794-7c5732be-e82f-4d6f-a6ac-ae3fdb62c841.png)
