### ISSUE TITLE
Enable common names as well as scientific in notifications

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1395]
Firstly, a question: I think that when we send out notification messages we include the taxon name originally entered by the recorder, so that this will either be an English name or a scientific name depending on what they entered - is that correct?

The request is for all notification to give both an English name and a scientific name, as some users appear to be receiving notifications with scientific names when they are not familiar with them.

**Comment by johnvanbreda** [comment]
That's correct, the notification is based on the taxon name as entered (code as per postgreSQL::selectVerificationAndCommentNotifications method).

This can of course be changed - do you want to use the accepted scientific name + the accepted common name, or should the name as entered be included? A suggested format might be:

If taxon has a common name and it was recorded as either the accepted common or accepted scientific name:
**accepted common name** (**_accepted scientific name_**)

If taxon has a common name and it was recorded as a non-accepted common name:
**accepted common name**, recorded as **given common name** (**_accepted scientific name_**)

If taxon has a common name and it was recorded as a synonym:
**accepted common name** (**_accepted scientific name_**, recorded as **synonym**)

If taxon has no common name and was recorded as the accepted scientific name:
**_accepted scientific name_**

If taxon has no common name and was recorded as a synonym:
**_accepted scientific name_**, recorded as **_synonym_**

**Comment by kitenetter** [comment]
@johnvanbreda if you can implement the above options without causing any performance issues or other complications that would be great.

**Comment by johnvanbreda** [comment]
Done in develop branch of code.

**Comment by johnvanbreda** [comment]
This change is now live.
