### ISSUE TITLE
Record cleaner rules not being applied?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1397]
Not sure if this is just running very slowly, but on my verification page it looks like there have been no rules checks applied since 13 December.

**Comment by johnvanbreda** [comment]
Work queue unblocked - I've updated the develop branch to prevent this particular issue blocking the queue. It related to an occurrence being added to a deleted sample.

**Comment by kitenetter** [comment]
Auto checks seem to have stopped again, none have been applied to the records I verify since just after 2pm on 29 December.

**Comment by johnvanbreda** [comment]
I've re-indexed a batch of samples so it should start up again now.

**Comment by kitenetter** [comment]
Thanks, the checks have now appeared again for me.
