### ISSUE TITLE
Vice-county spelling to correct

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1398]
Vice-county 78 is "Peeblesshire" with a double ss. 

On the dropdown for the Explore pages this is showing correctly, but in the data that is downloaded from iRecord it is being output incorrectly as "Peebleshire" with only one s.

**Comment by burkmarr** [comment]
It looks as though the VC in the Warehouse was updated on 20/10/2022 to correct the spelling, but this change is not reflected existing records in the ES index from where the download data is obtained. @johnvanbreda - what needs to be done to trigger an update of these records in the ES index?

**Comment by johnvanbreda** [comment]
There are instructions on updating the locations lookup used by logstash at https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/docs/occurrences.md#prepare-the-lookup-for-location-data. Or an update directly to the YAML file at https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/data/locations.yml. 

Once done, this needs to be pulled onto the Elasticsearch server and logstash restarted. 

Finally, you will need to trigger a re-index of all records in Peeblesshire, something like this which just causes the tracking sequence ID to increase:
```sql
update cache_occurrrences_functional set website_id=website_id were location_ids && array[<id for Peeblesshire>];
update cache_samples_functional set website_id=website_id were location_ids && array[<id for Peeblesshire>];
```

**Comment by burkmarr** [comment]
Thanks @johnvanbreda

**Comment by burkmarr** [comment]
@kitenetter - I've taken the steps outlined by John above. So now I think it's just a question of waiting a while for logstash to do it's thing and update the records/samples in the ES index.

**Comment by kitenetter** [comment]
Thanks @burkmarr 

I will check next time I do a download - closing.
