### ISSUE TITLE
Lookup from Survey Code to Survey Name

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1399]
I've been sent info about a record, including the Survey Code 142|686, as copied from the Verify grid. Where can I look up the Survey Name? These are being added to all the time. Please could we have a page, at a memorable permalink, with an authoritative reference table sorted by Survey Code?

**Comment by kitenetter** [comment]
A short-term workaround is to go to your verification grid (or Explore - All records), and then type the code (or just the first part of it) into the column-head filter box for the "Src" column. That should enable you to find records from that source, and if you then hover the cursor over the Src code for any one of the records it will tell you what that source is.

142|686 is the BirdTrack non-avian data.

Will find out how easy it would be to add a report that shows the list of survey names against codes.

**Comment by johnvanbreda** [comment]
Adding a survey and/or website lookup report would be a simple task.

Also - if you are in the Explore page or verification grid, then you can hover over the source IDs in the grid and it should show you what they mean.

Finally, I'd suggest a small change to the record details page would be to include the source website and survey dataset name in the details shown.

**Comment by DavidHepper** [comment]
I withdraw this request as unnecessary. Survey / Dataset name is already in the Details area. In this case: 
> BirdTrack non-avian taxa :: BirdTrack non-avian taxa

It turned out that I'd not noticed being in Training Mode, which explains why I couldn't find the record. See https://github.com/BiologicalRecordsCentre/iRecord/issues/1268
