### ISSUE TITLE
Explore all records - "where" filter not working outside home county

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#140]
If you have a preferred recording county set, this appears to override filters set outside of that county. E.g. I have my preferred recording area set to Buckinghamshire, and if I try to "Explore all records" using one of "My sites" that is outside Buckinghamshire, no records are returned. Similarly if I use a grid square search.

**Comment by johnvanbreda** [comment]
Fixed in the development branch - will be applied next time there is a feature release of the code.

**Comment by johnvanbreda** [comment]
See https://github.com/Indicia-Team/media/commit/fede53f58b6e60134c0a5051a31bb829329e3b9b
