### ISSUE TITLE
Effects on iRecord of an account deletion within iNaturalist?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1401]
There's quite a rumpus on iNat currently, in case you're interested > https://forum.inaturalist.org/t/the-vanishing-of-a-fellow-inatter/38221
What happens to all the verifications on iRecord if an iNat user deletes his or her account there?

**Comment by kitenetter** [comment]
As far as I understand it, if a record has been imported from iNat to iRecord and has been verified, it becomes 'locked' and won't be over-written by any subsequent edits within iNat. If a record hasn't been verified, and if it gets changed on iNat, I would expect the changes to be imported into iRecord. If it gets deleted on iNat or if it loses its research grade status (e.g. if a determination is withdrawn as seems to have happened in the iNat thread you linked to) I'm not sure what would happen.

**Comment by kitenetter** [comment]
Update to the final sentence in the previous comment: if an observation on iNat gets deleted that does not trigger a delete in iRecord. If an observation on iNat falls out of research grade that will not trigger an update on iRecord either, unless its identification gets changed and reaches research grade under a new name, at which point it would be updated in iRecord (assuming that it hasn't already been verified).

Closing.
