### ISSUE TITLE
Column Configuration form sometimes compresses height of column selection frame

### ISSUE THREAD

**Issue by cubitmg** [BiologicalRecordsCentre/iRecord#1404]
The form sometimes appears as in the attached screenshot where the frame that allows the list of columns that can be selected is only big enough to show one column at a time. It still works, but very difficult to use.

![ColumnConfigurationFormatingBug](https://user-images.githubusercontent.com/65334323/211353528-ecde2286-8f42-4d6c-b236-72154d1e915c.png)

**Comment by johnvanbreda** [comment]
I'd already noticed some problems with the layout here and have fixed them in the code that should be deployed in the next week or so.

**Comment by DavidHepper** [comment]
In case that doesn't fix it, this happens to me when the number of records that happen to be shown in the Grid is small, e.g. 1. The Column Configuration box sizes itself only to the current Grid size.

**Comment by johnvanbreda** [comment]
Thanks @DavidHepper. I've been able to check that use case on the code running on the dev setup and it's fine now.
