### ISSUE TITLE
Issue with view columns in 'Verifier record counts by Vice County'

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1406]
Statistics view 'Verifier record counts by Vice County' offers the spanner icon to configure columns but shows no data for additional columns selected. It could be useful to show 'Submitted on' and 'Verified on' dates, for example.

**Comment by DavidHepper** [comment]
Or should I just ignore the spanner?

**Comment by kitenetter** [comment]
I think the spanner is a default part of this particular display, and as you point out it isn't functional on this page. Ideally it should be customised to work with the data appropriate to the page, but I don't know when we will have resources to put into this. So I'm afraid the short-term answer is to ignore the spanner.

**Comment by johnvanbreda** [comment]
The report is an aggregate report, so cannot show individual record values, though we could include columns for minimum and maximum submitted and verified dates if useful, though they would increase the resources required to run the report.

I've removed the columns tool with the following config on the dataGrid:
```
@includeColumnSettingsTool=false
```

**Comment by kitenetter** [comment]
I'm going to close this one, but the "deferred" label is intended to highlight issues that we should keep under review for future work.

**Comment by DavidHepper** [comment]
That's fine. Expandable categories to show the detail rows would be a whole load more work.

**Comment by johnvanbreda** [comment]
True, but making the counts into a link that opens a filtered version of the Explore page showing the same records sounds do-able.
