### ISSUE TITLE
UKSI update

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1407]
We are now close to being able to carry out a full update and then implement regular (monthly?) incremental updates.

@johnvanbreda to liaise with Chris Raper over final queries

John and @burkmarr to liaise over applying full update

**Comment by cubitmg** [comment]
Would to be possible to get the full update list when it is applied and then to be informed about updates (specifically if they involve lepidoptera (both moths and butterflies) so I can update the Spreadsheet Validator(s) creating import date for iRecord?

**Comment by sacrevert** [comment]
@cubitmg Just to note that you can check custom lists against the current version of the UKSI (and so changes affecting iRecord when updated) at any time by using the UKSI Sandbox ( https://uksi-sandbox.nhm.ac.uk/index.php )

**Comment by kitenetter** [comment]
Thanks @sacrevert and to add to that if you go to the Lepidoptera page:
https://uksi-sandbox.nhm.ac.uk/taxonbrowser.php?txtSearch=lepidoptera

you can click on the "Excel" button to download all the current UKSI names. All ranks and synonyms are included so some additional filtering is needed to extract the list of current recommended species names but as far as I know this will always give you the most up-to-date UKSI names, which should match to what is in iRecord once we have the incremental update system in place.

**Comment by cubitmg** [comment]
Thanks @sacrevert & @kitenetter. Those links are just timing out this afternoon, but I will try later this evening when the servers may be quieter.

**Comment by cubitmg** [comment]
I have downloaded the lepidoptera list, but this doesn't seem to have a flag to indicate whether a species is moth or butterfly which I need. There is a simplified UKSI list on the nhm website which does distinguish, but that appears not to have been updated for a couple of years: https://data.nhm.ac.uk/dataset/uk-species-inventory-simplified-copy.
Any thoughts?

**Comment by kitenetter** [comment]
@cubitmg I think you'll need to take this up with Chris Raper at the Natural History Museum, who manages the UKSI. Drop me an email if you don't have his contact details. The full UKSI does contain "informal taxon groups" that distinguish butterflies and moths but as you say those groups are not in the spreadsheet download.

**Comment by cubitmg** [comment]
Thanks Martin. I've tried using his contact form on the NHM website.

**Comment by burkmarr** [comment]
@johnvanbreda - I noticed that the data files in https://github.com/Indicia-Team/support_files/tree/master/UKSI have been updated quite recently. Can I use these for the UKSI update or do I need to get a new db from Chris. I remember last time that he sent me an access database from which I had to extract the data files.

**Comment by johnvanbreda** [comment]
@burkmarr I've just checked my copy of the scripts and there were some changes I'd made a few months ago that weren't committed, so I've now done that. These should ensure the sync results in an as exact as possible copy of UKSI, including some of the population of new flags that track the deprecation status of names (such as taxa.organism_deprecated). Without these the new method can't understand the exact situation regarding a name so can't reliably update it from a logged change.

As for your question, I don't think it takes very long to update the data files so we may as well go for the latest copy that we can get from Chris.

**Comment by DavidRoy** [comment]
@burkmarr not wanting to slow you down but once you've done the latest UKSI update, can you include some work to link the UKSI to national recording schemes.  @StephRorke has worked with Chris Raper to define the nodes on the taxon tree to link to schemes.  see https://github.com/BiologicalRecordsCentre/BRCtracker/issues/165

Please raise a new issue for this if simpler

**Comment by burkmarr** [comment]
@DavidRoy - I've created a new issue for it (see above)

**Comment by DavidHepper** [comment]
If there are untested coding changes please let me know when this is live. Also please test that you can record 'Common Darter' and 'Sympetrum striolatum', as these have been knocked out twice previously by UKSI updates.

**Comment by burkmarr** [comment]
@johnvanbreda - have the SQL queries for generating the data files from the UKSI Access DB been updated to include the new flags (described here https://indicia-docs.readthedocs.io/en/latest/administrating/warehouse/importing-uksi.html)? I can't see 'organism_deprecated' in there anywhere.

**Comment by johnvanbreda** [comment]
Apologies @burkmarr - I've pushed those changes now as well.

**Comment by kitenetter** [comment]
@johnvanbreda do we need a new issue to set up the incremental updates - is there more to do to make this happen?

I know that there has been at least one taxon added since Wednesday, for the moth aggregate "Phyllocnistis ramulicola/saligna", so that would be a good test to see if we can pick it up.

**Comment by johnvanbreda** [comment]
Closing as #1479 now covers the incremental updates.
