### ISSUE TITLE
Unhelpful behaviour during upload

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#141]
BDS county recorders need to upload data from spreadsheets into iRecord on a regular basis. One county recorder in particular has been struggling to get this process to work, and reports:
"Unfortunately the program is not telling me when the upload has been successfully completed, it just appears to stay at the preparing to upload and does so for about an hour without telling me that the upload was successfully completed. I have gone into verify after a period of time and the uplload was successful. This lack of informing me that the upload was complete is a recent problem it did not happen last year. It is very frustrating as i don't know what has been uploaded and as a consequence have entered data more than once or stopped the upload partly through the process and only uploaded part files."

David Hepper and I have so far not been able to reproduce an upload 'hanging' without providing information on its completion, and we are assuming that it results from poor internet connectivity (the recorder in question is in a remote part of Scotland).

Anything that can be done to provide information to the user on the completion or otherwise of the upload process in such circumstances would be helpful.

**Comment by kitenetter** [comment]
Further to this, I've just tried to import a CSV file containing 2,854 moth records, into the "iRecord Moths" survey. The importer took 50 minutes to get to 1,950 records, and after a further half-hour has gone no further, so I assume that the operation has hung. I don't yet know if it will have imported any of the records, nor whether it has rejected anything.

Earlier this evening David Hepper reported that the importer took nearly 10 minutes to upload 333 records.

To me these timings seem very slow, and the behaviour when an import fails is very unhelpful. So it looks like we could have a bug in the import process, and the internet connection may not in fact be an issue, contrary to my earlier assumptions.

**Comment by kitenetter** [comment]
@johnvanbreda As discussed, last week I hit similar problems to those reported by BDS about data failing to upload to iRecord, and here's some more info:
- I started off with a CSV file containing 2854 moth records, uploading on the evening of 18 January.
- The importer ran for a long time as detailed in the previous comment, but eventually got stuck.
- As far as I can tell, 1,949 records got imported successfully, and were given record IDs running from 4439794 to 4441998

**Comment by johnvanbreda** [comment]
I've improved the performance significantly recently on upload - do these issues still occur now?

**Comment by kitenetter** [comment]
I have had no further reports of similar problems, so will close.
