### ISSUE TITLE
Note to users re: wildcard* in dropdowns 

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1415]
The drop-down lists (e.g. when creating an ectivity) which use the UKSI list and need a wildcard * used to search within the text of options is not very user-friendly, and either needs a re-think, or at a minimum some more accessible help text alongside the filter box itself. Note this is covered in guidance documents though @kitenetter (I don't think I am able to add labels or assign?)

**Comment by kitenetter** [comment]
This is being addressed through #1489 

Closing
