### ISSUE TITLE
File names for NBN exports need to be edited

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1417]
NBN have requested that our zip files for upload to the Atlas are given names that exclude spaces, punctuation or any non-stnadard characters such as "&". I will edit the dataset names on the old NBN export page, and check that this also updates the zip file name.

@johnvanbreda what controls the names of the files you generate under the new scripting process? Do I just need to send you a list of new names for these files?

**Comment by johnvanbreda** [comment]
The "outputFile" is a simple setting in the JSON configuration files for each export in the C:\indicia\config folder on the Elasticsearch server. I've updated them to lowercase alpha and underscores only.
