### ISSUE TITLE
Set up dataflow for herpetofauna from iRecord to NBN Atlas

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1418]
Agreements in place, need to set up metadata and filters so that an auto export can be implemented.

**Comment by kitenetter** [comment]
Please can we generate a file for this new dataflow, ideally so that I can send it on Friday 3 Feb.

EML file:
[Herpetofauna_NBNA_eml_MH.zip](https://github.com/BiologicalRecordsCentre/iRecord/files/10536710/Herpetofauna_NBNA_eml_MH.zip)

Filter being used is called "NBN - amphibians and reptiles":
https://irecord.org.uk/filters/admin-edit?filters_user_id=13500

Dataset title:
Records of amphibians and reptiles via iRecord

We have been asked to avoid the use of spaces and special characters in the file names for files we generate to send to NBN Atlas.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 

I've been asked to change the contact email that is given in the eml metadata, so this is a revised version:
[Herpetofauna_NBNA_eml_MH_v2.zip](https://github.com/BiologicalRecordsCentre/iRecord/files/10537369/Herpetofauna_NBNA_eml_MH_v2.zip)

There is one more new export that I might be able to get set up tomorrow, and then I will ask Biren to copy the files across (I don't think I can access the folder that you use).

**Comment by kitenetter** [comment]
@johnvanbreda there will be no further new exports this month. Please can you regenerate this herpetofauna one with the revised eml details, and then make the files for all new-format exports available on the server so that Biren can access them.

**Comment by johnvanbreda** [comment]
The files are now all regenerated @kitenetter.

**Comment by kitenetter** [comment]
Thanks - closing.

**Comment by kitenetter** [comment]
@johnvanbreda if I download the herpetofauna records from iRecord using the "NBN - amphibians and reptiles" dataflow filter I get 78,000 records, The export file that you've generated contains 24,480 records.

Why are so many missing?

**Comment by kitenetter** [comment]
It's a similar issue for the "nbn_diptera_non_scheme" data. Under the new export process we are generating 36,566 records, while the old version (which is still running) generates 83,081 records.

**Comment by kitenetter** [comment]
Closing this issue and moving to #1424
