### ISSUE TITLE
Species with names beginning Ae not found

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#142]
When searching for a species with name beginning 'Ae' the request is being mangled and the 'Ae' is being rewritten as 'E'. Thus, if I type 'Aepo' the list of suggestions are actually for letters 'epo'. This then fails to match the desired entry in the database.

In cache_taxon_searchterms there are 771 entries meeting the criteria
```
original like 'Ae%' 
and searchterm not like 'e%'
and taxon_list_id = 15
and preferred = true
```
which will not be found. (On the other hand, there are 9 which do have a searchterm beginning with 'e' which could be found.)

Refer to http://forums.nbn.org.uk/viewtopic.php?pid=26093

**Comment by kitenetter** [comment]
Hi @JimBacon - this one was first reported as #116 so am closing this #142
