### ISSUE TITLE
NBN files for February 2023

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1421]
@BirenRathod please can you transfer over the latest files from the old NBN export process, and also copy the new ones that John has generated, into the usual shared folder. Needed by Friday.

**Comment by BirenRathod** [comment]
@kitenetter I have copied from old NBN and those which John generated earlier.

**Comment by kitenetter** [comment]
@BirenRathod I can see 21 files in the export folder, but I was expecting just over 60. Are the other files missing or have they not been updated since Nov/Dec last year?
