### ISSUE TITLE
Redet is failing to update the determiner

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1422]
A verifier reports that recent redets have successfully applied the new determination, but have not updated the "Identified by" attribute. This is for records that did originally have the "Identified by" attribute populated.

An example is record ID 27516185.

May relate to #899

**Comment by kitenetter** [comment]
This continues to be reported by verifiers, adding to May milestone.

**Comment by MNSmith** [comment]
This issue is still present on re-deted records.
