### ISSUE TITLE
Buttons not working on verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1423]
If you use one of the verification buttons on the verification page, and then press Cancel, it is not being cancelled, the decision is being applied. This is likely to lead to incorrect decisions being stored.

Also, the button on the far right for "View species page" has stopped working.

**Comment by johnvanbreda** [comment]
It seems like the species details link code had only been committed to the iRecord Pantheon repository so had been overwritten when updated from GitHub. Now recreated and the cancel buttons fixed.
