### ISSUE TITLE
NBN files generated under new process are missing records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1424]
The new process for generating NBN files appears to be missing out on a lot of records that should be included.

The file "nbn_amphibians_and_reptiles" contains 24,480 records, but if I download the herpetofauna records from iRecord using the "NBN - amphibians and reptiles" dataflow filter I get 78,000 records,

The file "nbn_diptera_non_scheme" data contains 36,566 records, while the old NBN export version (which is still running) generates 83,081 records.

**Comment by kitenetter** [comment]
The file "nbn_national_mammal_atlas_project" is generating the expected number of records, so this doesn't seem to be a problem with all the new exports, just some of them.

**Comment by johnvanbreda** [comment]
For the amphibian and reptiles data, the ES extraction does seem to be correct. If I run the download from iRecord using the the "NBN - amphibians and reptiles" dataflow filter I get 24K records if I change the quality filter to accepted records only. The UI's "Record status included" control is overriding the quality filter built into the NBN extraction filter, so you were including records that were pending review in the 78,000 record download.

**Comment by kitenetter** [comment]
That's because the NBN filter for the amphibinans and reptiles is set to include the unverified ones, and we do want to send the unverified ones to NBN Atlas in this case. Is it possible to set it up so that it follows the definition in the dataflow filter?

**Comment by kitenetter** [comment]
It will be the same issue for the non-scheme Diptera. Some of our exports to NBN are intended to include unverified records, so the new process needs to take into account the dataflow filter settings in iRecord.

**Comment by johnvanbreda** [comment]
I've regenerated the herpetiles and non-scheme Diptera files with the filter set to exclude rejected. Are there any others?

**Comment by kitenetter** [comment]
The other one that includes unverified is "nbn_national_plant_monitoring_scheme".

Ideally we should exclude both rejected and queried records, but if needed we can live with excluding just the rejected ones this time round.

(There are some further exports that include unverified but we haven't moved them into the new system yet.)

**Comment by johnvanbreda** [comment]
I've modified the Diptera non-scheme and herpetiles exports to exclude queries and regenerated the files. The NPMS export was already set up to include all records except rejections and queries.

**Comment by kitenetter** [comment]
Thanks John.

@BirenRathod could you transfer "nbn_amphibians_and_reptiles" and "nbn_diptera_non_scheme" into the shared Export folder please.

**Comment by BirenRathod** [comment]
@kitenetter That's done now.

**Comment by johnvanbreda** [comment]
Closing as the original issue now sorted.
