### ISSUE TITLE
Indicia Warehouse page loads hang -- due to OpenStreetMap tiles?

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#1425]
When editing various things in the BRC indicia warehouse, I keep finding that the page hangs on "Save" (for example, editing the spatial ref of a location). However, if you copy the URL to a new browser tab, the page loads and the edit is reported as having been made (often within seconds).

The hanging page seems to be due to OSM, as there is a loading bar in Chrome saying something like "Loading b.tile.openstreetmap.org..." bottom left of the window (which is especially odd, as the OSM backdrop is present): is there some way to timeout this loading so that the page actually shows the desired save as completed rapidly as it actually has done? I can see some people assuming that the save has failed, or just waiting for ages for it to complete when it already has. (This doesn't always happen, but it does seem frequent).

**Comment by johnvanbreda** [comment]
@sacrevert before looking into this further can I check this is still happening since the warehouse performance was fixed a couple of weeks ago? Also if so, can you let me know a specific page/save action you've seen this happen on  as I've not noticed it myself.

**Comment by sacrevert** [comment]
seems ok now @johnvanbreda closing
