### ISSUE TITLE
Woodland Trust Explore page - permissions not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1429]
We have three iRecord users with the "Woodland Trust admin" role. That role should give them access to this page:
https://irecord.org.uk/woodland-trust/explore-es/all

However, they are getting an "Access denied" message. Can we reinstate the correct permissions for this page please.

**Comment by BirenRathod** [comment]
@kitenetter do you know the user of this role? so I can masquerade this to test this.

**Comment by kitenetter** [comment]
If you filter the people table for role = "woodland trust admin" you'll see the users (there are actually four, not three).

**Comment by BirenRathod** [comment]
@kitenetter right so, that problem is for all users of "woodland trust admin"?

**Comment by kitenetter** [comment]
Thanks - closing
