### ISSUE TITLE
How to access records from Download filter

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#143]
I'm trying to download a set of records to pass on to a recording scheme, and have set up a Download (= data flow) filter (assigned to the iRecord support account). However, the filter is not appearing as an option from my download page - should it? (I have a feeling that it used to do so but can't be certain.)

**Comment by JimBacon** [comment]
Hopefully John can answer as this is not an area of function I am familiar with and it would take me a good while to figure out what it is doing and then longer to figure out if that is what it should be doing.

**Comment by kitenetter** [comment]
Okay, for now I will stop using the Download filters and set up Verification filters instead.

**Comment by kitenetter** [comment]
Have now realised that the problem is forgetfulness on my part - I had forgotten to give myself the "survey downloader" role. Apologies all round.
