### ISSUE TITLE
How to add a blank space to the Download page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1430]
I've just added some Help text to the download page, in order to give some context to the "Download single survey" option.

However, the text is adjoining the box above, and I would prefer there to be a blank row so that it is clearer the the Help text applies to the option below, not above:

![image](https://user-images.githubusercontent.com/16039111/222434003-faf1a3eb-e136-4d2d-938b-e9aa4a5cfb12.png)

How can I add a blank row between the box that says "Exclude not accepted records" and the blue box for "Under download single ..."?

**Comment by BirenRathod** [comment]
@kitenetter I have added the margin now, you can see that in "Form structure" settings. Is that ok?

**Comment by kitenetter** [comment]
I don't think that's quite what I had in mind. Does this help?:

![image](https://user-images.githubusercontent.com/16039111/222453767-81cc68b4-8a89-4f26-a3f0-bc3353590555.png)

**Comment by BirenRathod** [comment]
@kitenetter I have increased the margin now. is that ok?

**Comment by kitenetter** [comment]
Thanks, that looks better - closing
