### ISSUE TITLE
NBN files for March 2023

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1431]
@BirenRathod please can you transfer over the latest files from the old NBN export process, and also copy the new ones that John has generated, into the usual shared folder. I have only just realised that we are in March already (!) and I will need to send these to NBN on Monday - if you aren't able to provide the files by Monday we will have to miss a month and catch up in April.

**Comment by BirenRathod** [comment]
@kitenetter I have copied all of them now.

**Comment by DavidRoy** [comment]
Assuming we can close?
