### ISSUE TITLE
Unhelpful formatting when opening downloaded records into Excel

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#144]
If a recorder enters a quantity as "1-5", and the data is subsequently downloaded into a CSV file and opened into Excel, Excel interprets "1-5" as "1 May". Is there anything we can do to prevent this happening?

**Comment by japonicus** [comment]
A kludgy solution is to wrap ambiguous text items in the csv file with an '=' prefix

`="1-5"`

Doing that results in non-conformant csv files but they open correctly in Excel (and LibreOffice also appears to cope).  Example file at http://bsbidb.org.uk/dev/example_csv_file_for_iRecord_bug.csv

If you decided to do this then you should probably also provide standard-compliant csv files as an option. 

The better solution may be to provide a download option for native Excel (.xlsx) format.  The [phpExcel library](https://github.com/PHPOffice/PHPExcel) works well (though is memory hungry so may not be suitable for very large downloads).

**Comment by BirenRathod** [comment]
The simple one is add apostrophe (') before the number. for e.g. '1-5 . Another one convert cell as "text" while importing the CSV file.

**Comment by japonicus** [comment]
> The simple one is add apostrophe (') before the number.

That works within Excel, but not for data from csv files

**Comment by BirenRathod** [comment]
As I mentioned while importing the CSV file use column as "text" which stop converting data to date.

**Comment by kitenetter** [comment]
@BirenRathod your solution works but it is an extra step - when I download CSV files I usually just double-click on them to open them straight into Excel, and I suspect most users do the same? Having to go through the import routine is quite time-consuming in comparison.

I think the ability to download a native Excel format is probably the best solution.

**Comment by BirenRathod** [comment]
Another solution is that data could be save as '1--5'  or  add space '1 - 5' instead. will this be mislead the data?

**Comment by johnvanbreda** [comment]
The problem with the last solution (1--5 or 1 - 5) is we are putting a constraint on the values that people use on their record forms in order to fix a problem caused by Excel's csv processing.
Other than native Excel support, the other solutions seem like a bit of a kludge in my opinion. I should also note that the Germans have been having problems with CSV files where if you save them in Excel and re-open them, it actually breaks the format and they won't open again.

**Comment by DavidHepper** [comment]
There's a fix for this. You could offer a choice of target system at Export time: Excel or Other. The way around this for Excel (and Google Sheets, allegedly, but not LibreOffice or other sensible apps) is to change what is output for Abundance fields:
```
To code		Output in the CSV
1-5		"=""1-5"""
6-20		"=""6-20"""
```
It isn't pretty but that doesn't matter.
Pat B. has been changing the dates back to number range codes A, B, etc. manually... This option would really help.
(p.s. I use LibreOffice.)
David

**Comment by kitenetter** [comment]
Most of these problems arise from recording forms that use termlists for abundance categories. If we can't find a fix that works with the "1-5" format I think there is a case for changing our termlists to "1 to 5", although I realise that any change will cause problems for people trying to maintain consistency with older data.

**Comment by kitenetter** [comment]
Moved to #1599
