### ISSUE TITLE
Error message when importing on TVKs

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1445]
I haven't tried to replicate this in the v2 importer, but I had some records fail to import when I tried to use the TVKs on the v1 importer, and I don't recognise the error message:

occurrence:general: An error occurred: There was an SQL error: ERROR:  invalid reference to FROM-clause entry for table "workflow_events"
LINE 3: ...ts" ON ("cache_taxa_taxon_lists"."external_key" = "workflow_...
                                                             ^
HINT:  There is an entry for table "workflow_events", but it cannot be referenced from this part of the query. - SELECT "workflow_events"."id", "workflow_events"."event_type", "workflow_events"."mimic_rewind_first", "workflow_events"."values", "workflow_events"."attrs_filter_term", "workflow_events"."location_ids_filter", "id"
FROM workflow_events, lookup_taxa_taxon_lists
JOIN "cache_taxa_taxon_lists" ON ("cache_taxa_taxon_lists"."external_key" = "workflow_events"."key_value")
WHERE "workflow_events"."deleted" = 'f'
AND "key" = 'taxa_taxon_list_external_key'
AND ("group_code" IN ('NNSIP','SENSITIVE'))
AND "external_key" = 'NBNSYS0000029070'
AND "taxon_list_id" = '15'
LIMIT 1 OFFSET 0

There are 3 TVKs that it related to:
 
NBNSYS0000029070
NBNSYS0000028961
NBNSYS0000007051

I then re-uploaded the records using the species names and they uploaded perfectly.

**Comment by cubitmg** [comment]
I get something similar with the V2 importer.

I used a TVK that I had just exported from iRecord as a test, but it was not recognised: NHMSYS0000520878

Matching error
There was an SQL error: ERROR: relation "list_licenceses" does not exist LINE 3: FROM list_licenceses l ^ - UPDATE import_temp.import_202304202230_6441aed1ce3c0_irecord_test_import i SET licence_id=l.id FROM list_licenceses l WHERE trim(lower(i.licence))=lower(l.title) AND l.website_id=23;

**Comment by johnvanbreda** [comment]
@cubitmg I've committed a fix for your issue to the code base, which will be released next time I do a full update. It related to the lookup of the licence information for your import.

**Comment by cubitmg** [comment]
Thanks @johnvanbreda 

The field mapping form now asks for three new mandatory fields and I don't understand why?

- Group or activity title (lookup in Groups table)
The old import guide said to ignore Groups (whatever they are), so why is this now mandatory? If it is a species group, then my survey dataset was iRecord Moths, so the system should already know this?

- Licence title (lookup in Licences table)
Is there not a one to one mapping between licence code and licence title in which case why are both mandatory?

- Licence code, e.g. "CC0" or "CC BY-NC" (lookup in Licences table)
My account profile already has default values for the licence code for photos and other media. Why is this value not being used by default? It might be fine to allow that t be overridden in the import file, but should it be mandatory?

More generally, the statements like "lookup in Groups table" isn't going to be meaningful to a user. For things like this can we have a link that allows that table to be browsed online in the context of the survey dataset type? 

Sorry, Mark

**Comment by cubitmg** [comment]
I decided to persevere rather than give up. So I guessed at what was required and added extra columns to my spreadsheet.

I found that mapping just the licence code field set both the code and name mandatory checkboxes, so what is the purpose to having two checkboxes?

I then ran into errors on the Background processing and got Matching error:
There was an SQL error: ERROR: column l.website_id does not exist LINE 5: AND l.website_id=23 ^ - UPDATE import_temp.import_202304271414_644a754c004a7_irecord_test_import i SET sample_method_id=l.id FROM lookup_terms l WHERE trim(lower(i.sample_method))=lower(l.term) AND l.website_id=23 ;

I then change the mapped to field to the survey's Method (which I should have done before) and that error was avoided, but it then failed on the licenses lookup:
There was an SQL error: ERROR: column l.website_id does not exist LINE 5: AND l.website_id=23 ^ - UPDATE import_temp.import_202304271414_644a754c004a7_irecord_test_import i SET licence_code_id=l.id FROM licences l WHERE trim(lower(i.licence_code))=lower(l.code) AND l.website_id=23 AND l.deleted=false;

**Comment by johnvanbreda** [comment]
Thanks for the feedback @cubitmg - it appears my fix hasn't done what I hoped. The 3 extra fields should not be mandatory. I'm just looking into it...

**Comment by johnvanbreda** [comment]
@cubitmg I've fixed the unnecessary additional required fields as well as the 2 errors you saw if the licence field is mapped.

FYI, we have an internal table called "groups" which contains any arbitrary grouping of users, e.g. the users involved in a project, society, bioblitz or anything else. On iRecord we refer to these as activities, but in other Indicia sites we use the term recording groups, or sometimes projects, depending on the requirements of the site. 

@kitenetter any thoughts on the wording to use for the various column captions on the mapping page, plus if we need to offer some additional assistance where a column relates to a lookup table as Mark suggests?

**Comment by cubitmg** [comment]
@johnvanbreda, thank you.

The additional mandatory fields are have gone. There are no lookup table errors. :-)

Now get as far as 'Importing data' and get this error: Import error - An error occurred on the server whilst importing your data. No more details I'm afraid.

**Comment by cubitmg** [comment]
Some thoughts on the UI:

Aside from the field names, the existing dropdown list I find complicated and hard to navigate. I think it would be beneficial to do away with the survey 'attributes' headings and include them under Occurrence or Sample headings. The use of the terms 'sample attributes' and 'occurrence attributes' is not helpful from a user perspective. Just having 'survey specific' in parentheses after the field value, if required. There should not be any duplication of field names across categories eg. Comment (which should be 'Occurrence comment' or 'Sample comment'). 

The field suggestions buttons are quite nice. Again the 'attributes' term should be avoided. Also, the suggestions should only be ones relevant to the survey e.g. 'Sample - Recorder names' should not be there as under most/all circumstances the survey-specific Recorder Name should be used.  Indeed in this case the latter should have been automatically selected (as well as being called 'Recorder name (survey-specific)' perhaps).

Some suggestions for the fields (not sure what to do about their order). I have added my comments [in square brackets] - these are not art of suggested list content! To be honest, I am not sure whether having Occurrence and Sample headings is that meaningful or helpful when importing individual records?:

Occurrence
Taxon (iRecord list) [replaces Taxa taxon list]
Species or taxon key (TVK) [remove the word external as it confusing and add TVK which many people can relate to if they are wanting to import it]
Genus (of Taxon name) [just describing the field, not what it does]
Species or taxon iRecord id [is this required? remove species or taxon taxa_taxonlists.id
Species or taxon iRecord search code
Specific name (of Taxon name)
Identified by 
Quantity [ignore what survey calls it internally]
Zero abundance
Sex
Stage
Occurrence comment
Confidential
Occurrence sensitivity precision
Occurrence external key (your reference)
Import guid [is this required What is it a guid for - the occurrence, species?]
Record status [don't know what this is? Validation status?]
Record substatus [don't know what this is? Validation status?]
Release status [don't know what this is? ]

Sample
Sample Cooment
Date
Day (of compound date)
Day (of compound date)
Month (of compound date)
Year (of compound date)
Date end
Date start
Date type
Spacial reference
Spacial reference system
Sample external key (your reference)
Group/Activity (iRecord held)
Creative commons licence name
Creative commons licence code
Location (iRecord held)
Location code (iRecord held) [if it is an iRecord code?)
Location external key (your reference) [assuming this is really external?]
Location iRecord key [using Indicia is confusing?]
Sample method (iRecord held)
[Is Input form relevant?]
Location name
Sample privacy precison
Sample record status [ What is this?]
Sample recorder names
Recorder name [not sure that sample is relevant and probably confusing when importing records]
Recorder email
Recorder first name
Recorder last name
Method

**Comment by cubitmg** [comment]
The other thing (referred to under #1405 is what values can be used in import file column headings to automatically select these. Maybe the names as in the list above as a stating point?

**Comment by kitenetter** [comment]
This has been addressed during development of the the v2 importer and associated Help pages, which should be available in the next few days. Closing.
