### ISSUE TITLE
Email notifications of record comments/queries not arriving

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1446]
Four users over the past week have emailed to say that email notifications about queries from a verifier have not come through, despite 'Email digest frequency for queried records' set to daily/hourly on the account. 

When the user is logged into iRecord the comment is visible/question mark appears, but no notification is arriving via email (including junk/spam folder). In one case where the record was then 'Accepted as correct', the user noted that they did then receive an email notification of this.

Examples are record #29702167 and #23736929.

**Comment by johnvanbreda** [comment]
I found a bug where the notification setting was being set to 'q' rather than 'Q' causing this - now fixed.
