### ISSUE TITLE
UKSI update: incorrect English name

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1452]
The UKSI has two English names for the moth Mythimna pallens:
- Common Wainscot
- Mathew's Wainscot (which used to be considered a separate species but has been shown to be M. pallens)

UKSI itself makes no distinction between these two names, but we should always display Common Wainscot in preference over Mathew's Wainscot. I'm not sure what needs to be edited to ensure that this happens.

**Comment by burkmarr** [comment]
@kitenetter - do you have some examples of when Mathew's Wainscot is being displayed where it shouldn't be?

**Comment by kitenetter** [comment]
Chris Raper has said that for Mathew's Wainscot he's now changed the NAMESERVER.TAXON_VERSION_STATUS flag to S for junior synonym which will rank it lower than the Common Wainscot name but keep it available for data entry if people have old, documentary records for it. I'm not sure if that will get picked up by the incremental updates that I hope we will be able to implement soon.

**Comment by burkmarr** [comment]
Doesn't the displayed common name always reflect that used by the recorder when the record was entered?

**Comment by kitenetter** [comment]
@burkmarr we're getting more enquiries about this - is it easy to switch them over? Chris has now marked Mathew's Wainscot as a junior synonym:
https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000168761

So the same issue shouldn't arise in future, but I don't know if our incremental updates will pick this up, and it would be good to correct it in iRecord as soon as we can.

**Comment by burkmarr** [comment]
The `taxa_taxon_lists` table could be updated so that `common_taxon_id` is set to `179826` on all entries where `taxon_meaning_id = 76410 and taxon_list_id = 15`. But that would then need to be propagated to the `cache_taxa_taxon_lists` table. 

@johnvanbreda - I thought there would be a work_queue task to enable that but I can't see it. Would the `default_common_name` field in that table have to be updated manually?

**Comment by johnvanbreda** [comment]
@burkmarr If you look in the cache_builder's config file you'll find a query under `$config['taxa_taxon_lists']['get_changed_items_query']`. This shows that a taxa taxon list entry will get regenerated in the cache table as long as it's updated on field is updated (or the updated on field of the common taxon, e.g. if you were just fixing a typo in the common name). 

Once done you should use the work queue to update all occurrences for that taxon meaning ID.

**Comment by burkmarr** [comment]
@kitenetter - the update to taxa_taxon_lists is done and the cache_builder tasks entered into the work_queue for 17,293 occurrences. Once the cache occurrences table is updated from the work_queue the changes will filter through to the ES index.

**Comment by johnvanbreda** [comment]
@burkmarr have you also updated the Elasticsearch lookups (taxa.yml)?

**Comment by burkmarr** [comment]
@johnvanbreda - ah sorry, I'll take a look now.

**Comment by burkmarr** [comment]
@johnvanbreda - should this be done by running https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/queries/prepare-taxa-lookup.sql and downloading the results to a file to replace https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/data/taxa.yml and then pulling to the ES server?

**Comment by johnvanbreda** [comment]
@burkmarr Yes, that's the one. But, last time I did this (shortly after the UKSI update) the file size had exceeded Guithub's 100MB limit so I didn't manage to commit it, I just copied the file over. I haven't had time yet to think about the best solution for version control of taxa.yml.

If it's really a simple change of the common name for 1 taxon, you could just edit the text file rather than regenerate it completely if easier. This would involve using the prepare taxon lookup query to understand the order of the columns, then searching for the preferred name TVK in the correct column (order will be TVK, accepted name, authority, accepted name TVK). Then you can find the common name in the correct column and replace it.

Logstash will need a restart in order to pick it up.

**Comment by burkmarr** [comment]
@johnvanbreda Ah - I wondered why the repo wasn't showing a more recent update. When I ran the query in pgAdmin and downloaded results to a text file, it looked incorrectly formatted - too many double-quotes. Any tips for getting getting the correctly formatted yaml?

**Comment by johnvanbreda** [comment]
@burkmarr Did you see this note in the documentation?

> In pgAdmin's preferences, set CSV/Text output CSV Quoting option to "None".

**Comment by burkmarr** [comment]
I didn't @johnvanbreda - can't find it. Where in the documentation is that?

**Comment by robin-hutchinson** [comment]
There is a comment on the forum about another species name that is having the same issue - for Mesapamea secalis (the species not the aggregate), the name Common Rustic has been replaced by Remm's Rustic: https://irecord.org.uk/record-details?occurrence_id=29932111

This was reported on the forum here: https://irecord.org.uk/forum/feedback-and-suggestions/another-wrong-vernacular-name

**Comment by kitenetter** [comment]
Thanks @robin-hutchinson 

This is a similar issue - UKSI has two English names for Mesapamea secalis, and makes no distinction between their validity, and iRecord has chosen the wrong one. As with the wainscots, I've asked Chris at NHM to mark Remm's as a junior synonym.

**Comment by burkmarr** [comment]
I will do a similar update for Common Rustic and when that's done, I will regenerate the taxa.yml file. I'll look at that now.

**Comment by burkmarr** [comment]
Common Rustic taxonomy and records are updated in the warehouse now, taxa.yml regenerated and replaced on ES server and Logstash service restarted.

**Comment by kitenetter** [comment]
All seem to be correct now. Closing.

**Comment by robin-hutchinson** [comment]
We've just had some more Mathew's Wainscot records reported. If I look at the record itself, it is correctly Common Wainscot: https://irecord.org.uk/record-details?occurrence_id=29225010

But the Explore page shows Mathew's Wainscot:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/e1c650b9-e694-4afe-966d-9bb7aa565116)

I've had a look for these records in the cache tables, and all are linking correctly to Common Wainscot:

SELECT cof.id, cof.taxa_taxon_list_id, cttl.taxon, cttl.taxon_list_id, cttl.taxon_list_title, cttl.default_common_name
FROM indicia.cache_occurrences_functional cof
JOIN indicia.cache_taxa_taxon_lists cttl
ON cof.taxa_taxon_list_id = cttl.id
WHERE cof.id  in (29225010 ,23879502 ,22802842 ,21741457 ,21727492 ,20258031  ,17536324   ,1118910)

Looking on the explore pages, there are 14186 records still showing Mathew's Wainscot.

**Comment by burkmarr** [comment]
Okay I think that the records need to be requeued for an ES update - I'll do that.

**Comment by burkmarr** [comment]
@robin-hutchinson - I requeued all records with default_common_name 'Common Wainscot' (19,778 records). I'm not sure how long the ES updates will take, so I'd give it a few hours before checking.
```sql
update cache_occurrences_functional  
set website_id=website_id 
where taxon_meaning_id in (
	select distinct(taxon_meaning_id)
	from cache_taxa_taxon_lists
	where default_common_name = 'Common Wainscot'
)
```

**Comment by robin-hutchinson** [comment]
Thanks Rich that's great - I'll check and close at the end of the day.

**Comment by robin-hutchinson** [comment]
There are 308 there now but that is a lot fewer than previously so I think its slowly working through, I'll close the issue.
