### ISSUE TITLE
'Flight period' rule not always being applied?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1454]
I'm puzzled that two apparently similar records of the same species were treated differently by the Flight Period rule.

ID | Species | Source | Obs. Date | Submitted | Autocheck
-- | -- | -- | -- | -- | --
29911687 | Pyrrhosoma nymphula | iRecord general data | 13/04/23 | 13/04/23 19:31 | Failed on Flight period
29911693 | Pyrrhosoma nymphula | iRecord Dragonflies | 13/04/23 | 13/04/23 19:43 | Passed

The second record 'Passed' on Flight period but this is incorrect. It should have failed, as the first did, because the date range of this rule for this species is 16/04 to 28/07.
The only significant difference I can see is the Source. Apparently the record was re-entered only a few minutes after the first entry by the same recorder using the more detailed 'iRecord Dragonflies' form.
Have I missed something?

**Comment by kitenetter** [comment]
I'm puzzled as well. It's the same recorder and the same location, and I agree that the expected behaviour would be for both records to be flagged as outside the flight period. Hopefully Jim can shed some light on this.

**Comment by JimBacon** [comment]
Hi.

Here are the pieces of information you are missing:

1. Indiica modifies the record cleaner rules to pass records where there are more than 5 previously verified records from the same 10km square within 7 days of the record under test, having the same stage.
2. There are 3 verified records with adult stage and 45 with no stage matching the space/time characteristics of the record.
3. The record that failed checks had life stage specifed as adult. The one that passed had no life stage.
