### ISSUE TITLE
Odd behaviour when querying records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1459]
I've seen this a few times now, but not sure what triggers it: I click on the query button, and the normal add comment box opens, and the a second or so later a second comment box opens. This is confusing and I'm not convinced that the messages actually get saved properly, although since it's hard to reproduce I'm not sure.

![image](https://user-images.githubusercontent.com/16039111/234417513-23ea4780-c136-492b-9ad7-2f51784247a4.png)

**Comment by kitenetter** [comment]
After cancelling the above comment boxes and refreshing the page, when I queried the record a second time it just opened up the expected single comment box.

**Comment by johnvanbreda** [comment]
I've managed to reproduce this - if the query popup is slow to appear then you move to the next record and click the button again, you can get 2. I'll work on a fix...

**Comment by kitenetter** [comment]
Just experienced this problem again and I'm 99% sure that I didn't click on the button more than once. Will see if it happens again before re-opening.
