### ISSUE TITLE
Dragonflies: Missing Forms and Survey Conversions

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#146]
- The form for survey **iRecord | iRecord Dragonflies app** is definitely missing. (Attempting to edit a record with this form shows the record with the form for iRecord General instead. It makes a complete hash of it and risks corrupting the data.) We agreed on 9 Jan 2017 that Karolis would create this form by 1 Mar. I am offering to help.

- The form for survey **iRecord | iRecord Dragonflies** is present and appears to work correctly. (Confusingly, at the top of the edit screen is displayed "The records on this form are part of the British Dragonfly Society recording group" even though in the filter definition the **Source > Websites** value is 'iRecord' not 'British Dragonfly Society'). Creation of this form is a top priority.

- The form for survey **iRecord | DRN dragonfly imports** is definitely missing. Attempting to edit a record with this form shows with the form for **iRecord General**. Creation of this form is a top priority.

- The form for the obsolete survey **British Dragonfly Society | BDS Advanced Records** may be missing. (I cannot find a record that shows an Edit button.) Records created for this Survey should be converted to iRecord | iRecord Dragonflies.

- The form for the obsolete survey **British Dragonfly Society | BDS Simple Records** may be missing. Comments as for **BDS Advanced Records**.

**Comment by kitenetter** [comment]
This now supercedes #121 which is also referred to in https://github.com/NERC-CEH/irecord-dragonfly-app/issues/3

**Comment by DavidHepper** [comment]
Please see the additional comment 15/02/2017 against #120 regarding Edit of a record causing the Survey ID to be changed. Data corruption!

**Comment by kitenetter** [comment]
@DavidHepper can we close this one?
