### ISSUE TITLE
Extend comment templates to the query comments

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1460]
Sorry to be raising a feature request on the same day that the comment templates have gone live!

Is it feasible to extend the comment template options to the comments added when querying a record?

**Comment by johnvanbreda** [comment]
Yes, this would be feasible. Would you like it to be done?

**Comment by kitenetter** [comment]
Yes please!

**Comment by johnvanbreda** [comment]
Done in code, ready to release.
