### ISSUE TITLE
Correction to the exclusion rules for Odonata from BTO BirdTrack

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1461]
@kitenetter , thank you for the meeting last week regarding issue #1455. As a separate issue, we are receiving batches of records into iRecord that are duplicates of records that were imported and verified several years ago. The new ones should have been excluded by our original specification. The relavant clause is:
> Exclude all records with BTO RECORDKEY <= OBS290186151

However, BTO are supplying their record key with prefix "BTO" e.g. "BTOOBS290186151" so it appears that the exclusion is never triggered. Please change the clause to: 
> Exclude all records with BTO RECORDKEY <= BTOOBS290186151

and delete all records that should have been excluded by it.

**Comment by DavidHepper** [comment]
Any progress here, please? For example, iR record 28716689 that has External Key BTOOBS289041489 is a dupe of 19071725 and should no longer be present.

**Comment by johnvanbreda** [comment]
@DavidHepper this is now done.
