### ISSUE TITLE
Error in My Notifications

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1462]
When I log in to my personal account (Martin C. Harvey), and look at the Home page, for some time iRecord has been telling me that I have a large number of unread notifications. However, when I click on the link to go to the My Notifications page, there are no notifications listed.

Not a major problem of course, but how do I clear the Home page message? And is there a more general issue here or is it just affecting me?

**Comment by kitenetter** [comment]
Has now resolved itself. Closing.

**Comment by johnvanbreda** [comment]
FYI I cleared these with a query - they were old training record notifications. Although we are no longer generating training record notifications I'd not cleared any existing ones.
