### ISSUE TITLE
Spreadsheet upload: choice of survey dataset

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1466]
Please can we remove "iRecord moths" as a first-choice survey for import, i.e. it goes back in the list of "other options". The first choice options should be iRecord Import (which is the default for most users) plus the BDS dragonfly import (which is the only other regularly used import survey that I'm aware of, but if others are requested we can consider adding them later).

**Comment by johnvanbreda** [comment]
Done
