### ISSUE TITLE
Spreadsheet upload: Channel Islands grid refs

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1467]
Transferred from #1405 

The new importer does allow importing on Channel Island grid references (a user has tested this out) - there are a couple of import systems with very similar names that don't all work for WV- grid references but they have worked out that the correct one is "UTM 30N (ED50)". Would it be possible to edit the name of this one to make it clearer (e.g. "UTM 30N (ED50) - Channel Isles Grid"), please?

**Comment by johnvanbreda** [comment]
Now done
