### ISSUE TITLE
Spreadsheet upload: no attribute available for importing species name

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1472]
Testing an import of ten moth records. Imported on scientific name. Fields matched, and all values matched. Clicked Next, expecting to arrive at the Import summary page, but got an error "Page Could Not Be Loaded. The request could not be completed due to a networking failure."

No records were imported.

**Comment by kitenetter** [comment]
Not sure if this is related to the above. Having previously failed to import using TVKs - see #1464 - I was using the scientific names this time. I matched the full binomial names to the attribute "Specific name/epithet (builds binomial name)", but that is the wrong thing to do isn't it?

Which raises these questions:
- How should binomial names be imported - I can't see a suitable attribute listed?
- Why did my mismatch not get picked up on the value matching page?
- Could this have led to the error message and the failure to import?

**Comment by kitenetter** [comment]
Okay, will test again and see if a similar error message occurs.

Have edited this issue to focus on how we import scientific or vernacular names.

**Comment by kitenetter** [comment]
Having gone back to something you told me many years, am I correct in thinking that the taxon name can be imported into the attribute we currently call "Taxa taxon list (lookup in database)"? If so that is fine, we just need to rename that attribute to something more understandable.

**Comment by johnvanbreda** [comment]
Correct - I'll change it to "Species or taxon name".

I've also fixed importing using the genus and species epithet in 2 separate fields.

**Comment by kitenetter** [comment]
Tested using the "Species or taxon name" attribute, no problems. Closing.
