### ISSUE TITLE
Setup NBN exports on iRecord Live site

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#1474]
@johnvanbreda Please set up NBN exports on live Drupal 9's iRecord site on Pantheon similar to the one done on Drupal 7. This will be needed as Drupal 7's iRecord site stopped.

**Comment by johnvanbreda** [comment]
@BirenRathod do you have any information as to when the copy of Drupal 7 iRecord that I used yesterday will stop being available?

**Comment by BirenRathod** [comment]
@BirenRathod As soon as we finish migrating websites on Drupal 9.

**Comment by kitenetter** [comment]
Moving to #1539
