### ISSUE TITLE
Spreadsheet upload: field mapping

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1477]
This document contains the proposals we discussed for organising the list of attributes for field mapping:
[attributes for field matching.docx](https://github.com/BiologicalRecordsCentre/iRecord/files/11497486/attributes.for.field.matching.docx)

Question: where I have suggested changing the name of an attribute, should that be done in the underlying attribute in the warehouse, or is it better to only make the change in the list presented on the page?

**Comment by cubitmg** [comment]
This looks excellent. 
I note that the term "External key (your reference)" occurs twice in the first column. Is this correct and hence adding another column to the database table?
Could we add a column to the attribute table to specify the column names in the incoming csv or xlsx file that will be recognised for automatic mapping? The order of the acceptable names for a field would indicate their priority in case two valid column names occurred in the file. I attach an updated document with that column and some suggestions.
[attributes.for.field.matching.+.column.names.docx](https://github.com/BiologicalRecordsCentre/iRecord/files/11498789/attributes.for.field.matching.%2B.column.names.docx)

**Comment by kitenetter** [comment]
@cubitmg one of the external keys is for the sample, and the other is for the occurrence, hence the suggested re-naming as shown in the second column. Arguably, the external key for the sample could be moved to the "advanced" list, as I don't expect it will be used very often.

I agree with your suggestions for automatic name recognition, thanks.

Actions for @johnvanbreda:
Unless you can see a reason not to do this, I suggest that we transfer these two attributes out of the standard list and into the advanced list:
- External key (your reference) [renamed as "External sample ID"]
- Location external key [renamed as "External location ID"]

If it possible to incorporate Mark's suggestions for automatic matching of incoming column headings that would also be good.

**Comment by johnvanbreda** [comment]
Code changes now in the develop branch.
Some of the field name changes are specific to iRecord so can be handled by a page specific language strings file once the code is deployed.

**Comment by johnvanbreda** [comment]
@DavidHepper it will only affect the new V2 importer. Once you have setup a mapping though, you can save it as a template so future imports are easier. At the moment templates are kept separately per user but it might be worth exploring the idea of having some "officical" templates that are available for all users.

**Comment by DavidHepper** [comment]
Thank you @johnvanbreda. I've not tried V2. Please let me know here when it is mature and I can test it. Currently I advertise the /import link to my CDRs.

**Comment by johnvanbreda** [comment]
@kitenetter please can you let @DavidHepper know about the v2 importer once you are happy he can test it.

**Comment by kitenetter** [comment]
Will do. 

@DavidHepper you are welcome to start testing it whenever you wish, bearing in mind that in its current form it hasn't yet been fully tested by us, and we don't yet have documentation, so as usual it makes sense to try it in training mode first. Feedback welcome. (It does not currently allow the updating of existing records.) The link is:
https://irecord.org.uk/import/v2

**Comment by kitenetter** [comment]
@cubitmg the info in the previous comment applies to you as well!

**Comment by cubitmg** [comment]
Thanks @kitenetter. 

I note you say there is no documentation yet, but is there a high level function spec or set of use cases? 

Is the current release essentially replacing the function provided by import[v1]?

Updating existing records is not included, but are importing records with verification values set and with photographs planned for future releases?

Thanks

**Comment by kitenetter** [comment]
@cubitmg I don't have any documentation that I can pass on other than what has been discussed in the related github issues.

We are not proposing to remove the v1 importer imminently - it will remain available while we test v2 and beyond.

Allowing verifiers to import records with verification status set is not currently possible but we hope to address this later in the year. Upload of photos remains an aspiration but we don't have current plans to work on this.

**Comment by cubitmg** [comment]
@kitenetter Thanks. Sorry, I wasn't clear, the v1 reference was really asking whether this release of v2 has any functionality that v1 doesn't currently provide?
