### ISSUE TITLE
Indicia sample attribute 'Vice County' not location linked

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#1478]
I want to use the general Vice County sample attribute (27) for the SRS record entry page, but I want it to be linked to location so that if someone goes back to a location they've recorded at before, it is filled in automatically (along with a bunch of other SRS specific habitat custom attributes).

However the 'applies to location' checkbox for this attribute is not checked in the Warehouse. Does anyone see any reason why I should not check it?

@kitenetter @johnvanbreda

**Comment by johnvanbreda** [comment]
I can't see any reason not to tick that box.

**Comment by kitenetter** [comment]
@burkmarr I wasn't aware of the 'applies to location' option, so not sure what if any wider implications it might have. On the face of it it looks fine to apply it but would be good to have confirmation from @johnvanbreda - which I see he has just given!

Does this only work if the user has saved their location?

**Comment by burkmarr** [comment]
Thanks both. @kitenetter - it also seems to work for any generally available locations.

**Comment by johnvanbreda** [comment]
The flag doesn't have any wider implications. The original intention in terms of the data model was that if you recorded an attribute of the location vs an attribute of the current environmental conditions in the sample, it might be useful to be able to identify which are the persistent(ish) location attributes vs which are the transient environmental attributes. Then we could do a report on a site and pull out the location information from the samples. In practice, the flag has only been used to identify which attribute values can default to the previously recorded value when repeat sampling.

**Comment by burkmarr** [comment]
It's *extremely* useful for the SRS habitat stuff when going back to a previously recorded site. There's a lot of it so it saves a lot of time if it resets the control values to what you used last time. Even though you might be in a different part of the site and need to change some of the values, e.g. relating to microhabitat, it is still a massive time saver. Recorded SRS phase II data is a *massive* pain in MapMate, so it's a big selling point for entering into iRecord/Indicia.
