### ISSUE TITLE
Verify - expanded Grid row remains on display after its upper row disappears

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#148]
If a record in the grid is expanded (click the '+' sign) to show a second row of detail, this second row is not closed or updated when an action such as Accept or Reject causes its parent row to be removed from the grid. This is confusing. 

Steps to reproduce: Expand a row; mark it as Accepted.
Workaround: expand the row above that remains.
Suggested Fix: the grid should be more comprehensively refreshed after a record changes its status so that it no longer matches the selection criteria.

**Example:**

- Row before expansion:
![image](https://cloud.githubusercontent.com/assets/24915271/22293313/00a788e8-e307-11e6-990d-a3d49cacd462.png)

- Row after expansion:
![image](https://cloud.githubusercontent.com/assets/24915271/22293380/3fd679c0-e307-11e6-942d-58312ca0ecf5.png)

- Lower row only of ID=4448067 remains after Accept or another change of status:
![image](https://cloud.githubusercontent.com/assets/24915271/22293497/bbf1ea9e-e307-11e6-8de4-82b7a048ec16.png)

**Comment by johnvanbreda** [comment]
This relates to the verification_5 prebuilt form when the grid is configured with responsive columns to appear only when the + button is clicked. The code to remove a row that's been accepted or rejected doesn't check the next row and also remove it if it contains responsive content.

**Comment by johnvanbreda** [comment]
Code deployed to fix this.
