### ISSUE TITLE
Final testing for iRecord PHP code upgrade

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1480]
This picks up from #1410 

The new code has been implemented in the dev version of iRecord:
https://dev-brc-test-irecord.pantheonsite.io/

The dev website is linked to a separate dev warehouse:
https://devwarehouse.indicia.org.uk/index.php/login

There are no email notifications associated with the dev sites so it is fine to test out verification etc., there is no link to live data or external user accounts.

All areas of the site would benefit from testing, so perhaps each of you could pick an area to focus on initially and tick things off from this list when you have done so.
- [ ] adding records 
- [ ] downloading records
- [ ] verifying records
- [ ] Activities (creating and displaying)
- [ ] setting up a new recording form
- [ ] uploading from spreadsheets
- [ ] Explore pages
- [ ] Forum pages and posting

**Comment by kitenetter** [comment]
@BirenRathod we are unable to test the verification page, it gets stuck with the spinning wheel.

**Comment by Sam-Amy** [comment]
@BirenRathod I am also having problems with the speed of the site in general; trying to navigate to 'My records' and getting 'The application did not respond in time.'

**Comment by Sam-Amy** [comment]
Testing spreadsheet import (https://dev-brc-test-irecord.pantheonsite.io/import) is now failing and giving the message:
An error occurred during the upload.
Array ( [result] => 1 [output] => )

**Comment by robin-hutchinson** [comment]
I've just tried replicating this but I just get the "Application didn't respond in time" message!

**Comment by BirenRathod** [comment]
@kitenetter, @Sam-Amy & @robin-hutchinson I have updated the code this morning and the site is available to test now including the verification page. 
Just to let you know that the site is synched with live data.

**Comment by robin-hutchinson** [comment]
Thanks Biren - I was just testing querying a record and got this, it said there was no email address for the recorder, but there is (it is my account) - is this just because its the dev warehouse?

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/9ccd4967-a05e-4c92-afb3-5fb6ffc0b3ec)

**Comment by BirenRathod** [comment]
@robin-hutchinson it is linked to live warehouse only.

**Comment by robin-hutchinson** [comment]
Ok thank you - I'm not sure what is causing this then!

**Comment by BirenRathod** [comment]
@robin-hutchinson if you check this same on live iRecord, you could see the same.

**Comment by robin-hutchinson** [comment]
Ok thanks - I'll create a new issue for this (it doesn't seem to be happening consistently so I'll try and work out how to recreate!)

**Comment by Sam-Amy** [comment]
@robin-hutchinson I think this is a standard message? Just warning you that email isn't necessary as the recorder checks notifications, and adding a comment (rather than email) is generally preferable as the comment remains linked to the record for future reference.

**Comment by johnvanbreda** [comment]
See #1190 - I actually thought I'd fixed this in https://github.com/Indicia-Team/media/commit/46c989f0179303caefe36b33dd15d558bb438f96 but maybe not. If you can work out a reliable way of reproducing it that would be extremely helpful!

**Comment by kitenetter** [comment]
From the verification page on the dev site, I clicked on the button to view the record details for this record:
https://dev-brc-test-irecord.pantheonsite.io/record-details?occurrence_id=30351942

At the top of the page it showed a warning message "You are editing a sample containing some records which have already been checked. Changing details relating to the visit will require all records to be rechecked but changing details relating to a single species or other record attributes will only affect that record. Please only make changes if they are important, otherwise the records will need to be rechecked." However, I had not clicked the edit button, and was not on an editable page.

**Comment by kitenetter** [comment]
@johnvanbreda I can't reproduce it either.

I don't think we have identified any major problems recently, but we haven't been able to test verification much due to page unavailability. I will do some more testing today and close if no problems found.

**Comment by johnvanbreda** [comment]
@kitenetter the test iRecord and live iRecord are now both on PHP 8.1 so no need for further testing, as the aim was to pick up major issues before the live site switched. I'll close now...
