### ISSUE TITLE
Feature request for Verify Photo to support multiple selection

### ISSUE THREAD

**Issue by cubitmg** [BiologicalRecordsCentre/iRecord#1483]
One of the beauties of the new photo verification is that many photos can be verified based on the large thumbnail. Being able to 'tick' each one and then do a multiple verify on several records at a time would be a great time saver for verifiers in avoiding selecting each one an verifying in turn. At the moment I go through and check the identifications and deal with any that can't be accepted and then go into the normal Verify to use that multiple select which is quite a pain.

**Comment by zrandle** [comment]
I agree that batch verification of selected images would be a great feature.

**Comment by kitenetter** [comment]
Happy to consider this @cubitmg but can I just ask how much difference this would make compared to the existing keyboard shortcuts. As things stand, you can click on the first record on the photo verification page, check the photo, and if it is correct then you can accept it with four keyboard strokes: 
press "1", then tab, then tab again, then enter

at which point the record is removed from view and the next one automatically comes into focus.

If I'm understanding your proposal correctly, you would click on the first record on the photo verification page, check the photo, and if it is correct you would have to tick it (using a mouse click?). You would then have to click again, or use an arrow key, to move on to the next record, and then when you get to the end of the current set of records you would have to apply a bulk verification.

I can see that the bulk verification option would provide an alternative way of doing things, but I'm not convinced that it actually saves much time. However, if you feel that the alternative way of doing things is in itself desirable we can add it to the list.

**Comment by cubitmg** [comment]
Hi @kitenetter, thanks for considering this. I was thinking more along the lines of what websites such as Google Photos does where there is the option just to click on a tick 'box' on each photo. So one mouse click per record and Click 'correct' and then on the confirmation message. See attached image. 
![Photos](https://github.com/BiologicalRecordsCentre/iRecord/assets/65334323/7f4bd381-3564-48db-86aa-7ef51e392771)
There are lots of butterfly and moth species that this would work well for as the thumbnail sized photo is perfectly big enough to confirm a Brimstone (moth or butterfly!), for example, although not all species obviously.
Mark

**Comment by johnvanbreda** [comment]
Agreed - batch verification in zoomed in mode isn't very useful, but when working with the thumbnails and easily identifiable photos it makes a lot more sense.

**Comment by kitenetter** [comment]
@johnvanbreda I assume this would need to be done by adding the functionality to "Enable multiple selection mode", and then allowing a tick box per record in a similar way to Mark's example. Are there complications if the verifier then opens up the record cards?

Let me know if this is a large-scale piece of development, but if it is reasonably straightforward it would be good to tackle it once we've finished off some of the other BC-related issues.

**Comment by johnvanbreda** [comment]
Code now deployed.

**Comment by cubitmg** [comment]
Is there (can there be) an ability to "select all" photos when in multi-select mode?

**Comment by kitenetter** [comment]
@cubitmg it is currently possible to apply a verification decision to all records with photos (i.e. to all records matching the current filter settings, across all pages). I think you are asking for a means of selecting all the records showing on the current page, e.g. all 30 of them if you are using the default page setting? If so I agree that would be useful, and will add as a new issue.

**Comment by cubitmg** [comment]
Yes, exactly. Sometimes want to select on on page in view and then 'untick' the ones that have a different verification decision for.
