### ISSUE TITLE
Filters 2: changes to "Create a filter section"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1488]
Give this section the title "Stored filters".

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/6417f367-4c4c-419f-b364-f4fdefa6d91b)

Edits to wording in connection with saving a filter:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/fb516500-c147-4746-b5b1-186d39eae3bb)

New text:
- To save these filter settings for future use, give the filter a name and then click Save filter:

**Comment by johnvanbreda** [comment]
Code now deployed.
