### ISSUE TITLE
Filters 3: options for "What" settings

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1489]
Some wording changes, and addition of default wildcard when searching for **Species groups**:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/f27b2494-cda9-4f36-b2bb-9360cf24761f)

New text:
- Select the appropriate tab to filter by species group; or taxon name; or taxon level; or other flags (such as marine, or non-native)
- This tab allows you to choose one or more broad species groups. These have to match the group names that we use (full list). Find a group by typing any part of its name, e.g. type “moth” to find “insect - moth”.
- Click on the group name from the dropdown list, then click on Add. You can add multiple groups. When you have added all the groups that you want, click Apply to filter the records.
- _Go to the “Species or higher taxa” tab to chose an individual species, genus or family etc._
- (taken from your account settings)

Wording change for **Species or higher taxa**:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/c891e3e2-1499-4013-967a-668737f827ba)

New text:
- This tab allows you to choose one or more individual species, or you can use genus, family, order etc. Type in a scientific or English name and click on the name you want from the dropdown list that appears. Then click on Add. 
- You can add multiple species or higher taxa. When you have added all the names that you want, click Apply to filter the records

**Comment by johnvanbreda** [comment]
Coding done so will be in the next full release.
