### ISSUE TITLE
Filters 5: "When" settings

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1491]
Clarify wording for selection of date field:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/c0296b4a-829d-4b1c-b7d8-c181ee605673)

New text:
- Field record date
- Date of record input
- Date of last edit or verification
- Date of last verification

Enable easy selection of an entire calendar year, either by adding a new section for year, or enabling years to be entered into the existing date pickers (without needing to specify 1 Jan-31 Dec):

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/78e195e1-51ba-4bea-9b6a-c4b7e805d0a6)

**Comment by johnvanbreda** [comment]
Code now deployed.
