### ISSUE TITLE
Import not appearing after using v2 importer

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1495]
At about 5pm today I imported a set of 3,423 records using the v2 importer, which completed successfully and reported no errors. I can find the records in the warehouse, but they are not available in the warehouse cache tables, which is presumably why they have not appeared on iRecord in either the elastic or non-elastic views.

An example of the imported data is for sample ID = 22174763, which has 15 linked occurrences.

Maybe it is just taking its time, but normally imports appear fairly quickly don't they?

Will check again tomorrow.

**Comment by kitenetter** [comment]
The records are now (7pm) beginning to appear, so hopefully all is well, although I wonder if people are getting caught out by this and uploading records a second time when they don't seem to appear after the first import. Closing for now.

**Comment by johnvanbreda** [comment]
v2 imports prioritise loading the data quickly and delay building the cache table entries which are done on the work queue. So there is likely to be a bit extra delay vs v1. Possibly this needs to be reflected in the wording? We could probably provide a report which shows a summary of an import, including the number of records left to index.

**Comment by johnvanbreda** [comment]
@kitenetter searching for metadata.import_guid:36C2F7ED-C60B-4066-B0BD-0A804ADEB3C3 I can see they are all present. They may have only recently been indexed as things were backlogged in the work queue. Suggest checking the time for records to appear next time you do an import as that may give a more accurate reflection of normality.

**Comment by johnvanbreda** [comment]
I've implemented the first fix and also sorted some additional existing occurrence data where this problem appeared. I'm not 100% sure that the fix will cover all cases where the problem occurred so feel free to re-open if it happens again.
