### ISSUE TITLE
Record cleaner checks have stopped again

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1496]
As far as I can tell no record cleaner checks have been applied since 26/05/2023 16:05.

(Possibly related: the warehouse is reporting work queue issues.)

**Comment by johnvanbreda** [comment]
I've cleared the work queue errors (due to high server load) and also re-queued a few entries for spatial indexing, which was delaying the record cleaner checks. It should right itself over the next few hours.

**Comment by kitenetter** [comment]
Checks have caught up to some extent, although there currently seems to be a c. 24-hour delay. Assuming this is a general performance issue rather than a specific bug. Closing.
