### ISSUE TITLE
Import v1 failing to complete

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1497]
Having had problems with the v2 importer yesterday I've tried importing a small .xlsx file of ten records using the old version of the importer today. It has hung at the final "Preparing to upload" stage, and has not completed nor produced any error message.

Once again I am left wondering whether anything has imported or not, and I'm not sure if I should try doing the import again or whether this will produce duplicates. Given the delays with the records appearing even when the import is successful it makes it very difficult to know what is happening.

**Comment by johnvanbreda** [comment]
Do you know what time this happened, so I can check the logs?

**Comment by kitenetter** [comment]
It must have been just before the above comment, so just before 1pm (i.e. probably between 12.30 and 1pm) on Tues 30 May.

The records I was trying to upload have not appeared on the verification page so I assume the upload did not complete in this case.

**Comment by JimBacon** [comment]
Sounds like it. See https://github.com/Indicia-Team/warehouse/issues/462
Also, @kitenetter, the scheduled tasks have been grindingly slow since Sunday lunch time which may affect the rate at which the records arrive. The data cleaner has only just processed Tuesday afternoon.

**Comment by kitenetter** [comment]
With the imminent move to the v2 importer I'm closing this one.
