### ISSUE TITLE
Verify - Grid record count is incorrect after a record is accepted

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#150]
After a record is verified and disappears from the Grid, the record count below the grid is incorrect. 
After accepting or rejecting several, both the 'showing' and the total count values are too high.
Example screenshot:
![showing records 1 to 8 of 7](https://cloud.githubusercontent.com/assets/24915271/22294235/6a86fb7e-e30a-11e6-823d-65e1b363f099.jpg)

**Comment by kitenetter** [comment]
There is a generic problem with the "x of y" counts throughout iRecord and Pantheon.

**Comment by kitenetter** [comment]
Being looked at under #340 - closing this one.
