### ISSUE TITLE
Sensitive species workflow question

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1501]
This relates to the Essex Wildlife Trusts website (website ID 57). They want their records to be shared to iRecord, but before doing so had requested that we implement sensitive species blurring for a list of taxa. @Sam-Amy has set up the list under the ESSEXWT workflow group.

Question: will these sensitivity settings get applied retrospectively to all the records currently in this website, or do we need to request a workflow operation or other database update to make this happen?

**Comment by johnvanbreda** [comment]
No, the existing records are not automatically updated. When ready we can write a script that generates a workflow update for the records in question.
