### ISSUE TITLE
Grid records are not cleared when filter conditions return 'no matches'

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1502]
Verify (and possibly also Explore):
When trying to refine a list of records: expand 'Create a filter' and enter a grid ref in 'Where'. If no records match the new criteria no error is shown but the grid continues to show whatever records were there previously. I'm sure it should clear these to indicate 'no matches'.
e.g. square SU909419 currently contains no records of Odonata.

This may also occur when other filters cause 'no matches'.

**Comment by kitenetter** [comment]
I think this is the same issue as #1561
