### ISSUE TITLE
'National Nature Reserve' picklist in Filter definition is incomplete

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1503]
The NNR picklist does not include 'Thursley' as listed at https://www.gov.uk/government/publications/surreys-national-nature-reserves
And it's my favourite! (To my surprise, the official name appears to be 'Thursley' rather than 'Thursley Common'.)
Others may be missing but I've not checked.

**Comment by johnvanbreda** [comment]
@DavidRoy there are a small number of the NNR layer locations that have been linked to the EBMS website so they are not appearing as public. Is it necessary to link them to EBMS as it's a public layer?

**Comment by DavidRoy** [comment]
@johnvanbreda I think that's in error.  There's no reason for the use of the NNR layer for the eBMS work.  eBMS typically uses the NUTS boundaries

**Comment by johnvanbreda** [comment]
Ok, thanks - now fixed. Closing.

**Comment by DavidHepper** [comment]
Thank you. I confirm that 'Thursley NNR' is selectable.
