### ISSUE TITLE
Records not being allocated to vice county

### ISSUE THREAD

**Issue by Mike-Averill** [BiologicalRecordsCentre/iRecord#1504]
15 Records from Desmond Jennings on 03/06/2023 not allocated to a Vice County

**Comment by Sam-Amy** [comment]
@Mike-Averill I see 15 records from Desmond Jennings on 03/06/2023 via Explore/All records, which are all assigned to Worcestershire. Are these the records in question (perhaps a delay in the system, unless anyone has done something to amend this already)? If not it would be helpful if you could give the record ID numbers please?

**Comment by Mike-Averill** [comment]
Yes, these 15 records suddenly appeared with the Vice county of Worcestershire on my verification list so i was able to deal with them. I had assumed someone had done something, so thanks for following up

**Comment by Mike-Averill** [comment]
Yes, it can, these records appeared with all attributes.
