### ISSUE TITLE
Unable to add logo to Activity

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1505]
Not sure if this applies to all activities, but for me and at least one other user we are unable to get a logo to upload when setting up a new activity. This is the case even when using the identical logo that had successfully uploaded in the past.

**Comment by BirenRathod** [comment]
@kitenetter The logo doesn't upload on the iRecord site, it uses a path from the warehouse, so if it is not uploading that means the code in the indicia module is unable to find the image file to upload it.

**Comment by kitenetter** [comment]
@BirenRathod it used to be possible to upload a logo when setting up an activity. Is that no longer possible?

**Comment by BirenRathod** [comment]
@kitenetter Something got changed when @johnvanbreda updated the plupload.full.min.js file.

**Comment by BirenRathod** [comment]
@kitenetter Check also record submit page and see if you can upload a photo or not.

**Comment by johnvanbreda** [comment]
I don't think this is anythning to do with plupload, it's just a normal file upload HTML control. I'm looking into it.

**Comment by johnvanbreda** [comment]
Should be fixed now.
