### ISSUE TITLE
Spreadsheet upload: three date columns

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1507]
If I am trying to upload on the version 2 importer using the three date columns (date_start, date_end, date_type), the importer doesn't recognise that I've completed the date requirement and won't let me upload:

![Screenshot (123)](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/1be906c4-81ee-4e46-bfca-393779c1c9a7)
![Screenshot (122)](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/1a1d495c-0be4-4126-820c-7fbd824ad088)

**Comment by johnvanbreda** [comment]
Coding done in develop branch.
