### ISSUE TITLE
Taxon missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1509]
In the warehouse we have entries for genus "Trachemys", and for three sub-species within that genus, but the species, "Trachemys scripta", is missing. See:
https://uksi-sandbox.nhm.ac.uk/taxon.php?orgKey=NBNORG0000049741

Not sure if this relates to #1506

**Comment by Sam-Amy** [comment]
Possibly also related, the Large Skipper _Ochlodes sylvanus_ (see on [UKSI sandbox](https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0020755521)) is missing from the iRecord dropdown, though in this case it is in the [warehouse](https://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-key=NHMSYS0020755521&filter-key_type=tvk&filter-taxa_taxon_list_id=&filter-taxa_taxon_list_id%3Ataxon=). Could it be relevant that there are multiple entries for the same taxon in the Warehouse? I'm not familiar enough to recognise if this is normal.

Let me know and apologies if this needs a separate issue.

**Comment by Sam-Amy** [comment]
Also, should the TVK for Trachemys scripta NHMSYS0000080227 be against a different name (Common name Pond Slider) in the [warehouse](https://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-key=NHMSYS0000080227&filter-key_type=tvk&filter-taxa_taxon_list_id=&filter-taxa_taxon_list_id%3Ataxon=)?

**Comment by johnvanbreda** [comment]
Trachemys scripta was modified in the sandbox on 24/05, a few days after we applied the last (incremental) UKSI update. It would be interesting to monitor this one after the next incremental update to see if it gets fixed.

Ochlodes sylvanus seems correct in the database, but missing from the search table (cache_taxon_searchterms), so I've re-queued it and a few other taxa using the following query:
```sql
update taxa_taxon_lists set updated_on=now(), updated_by_id=3 where id in (
	select cttl.id from cache_taxa_taxon_lists cttl
	left join cache_taxon_searchterms cts on cts.taxa_taxon_list_id=cttl.id
	where cttl.allow_data_entry=true
	and cts.id is null
	)
```

**Comment by Sam-Amy** [comment]
@johnvanbreda although now present in the iRecord dropdown (website and app), Ochlodes sylvanus is still not available on the Butterflies for the New Millenium portal - any idea why this would be please? Thanks

**Comment by johnvanbreda** [comment]
I found that some taxa had a null taxon_rank_sort_order value in the cache_taxon_searchterms table. Fixed with the following query:
```sql

select cts.id, tr.sort_order
into temporary to_fix
from cache_taxon_searchterms cts
join cache_taxa_Taxon_lists cttl on cttl.id=cts.taxa_taxon_list_id
 and coalesce(cts.taxon_rank_sort_order, 0)<>coalesce(cttl.taxon_rank_sort_order, 0)
join taxa t on t.id=cttl.taxon_id
join taxon_ranks tr on tr.id=t.taxon_rank_id

update cache_taxon_searchterms cts
set taxon_rank_sort_order=tf.sort_order
from to_fix tf
where tf.id=cts.id
```

It only affected BfNM as there is a filter limiting to selecting species - as the rank sort order was missing, the system didn't include O. sylvanus.

**Comment by Sam-Amy** [comment]
Great, thanks @johnvanbreda I can see it comes up on the form now

**Comment by kitenetter** [comment]
Trachemys scripta is now available. Closing.
