### ISSUE TITLE
Filter creation - 'Source' popup does not repopulate properly

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#151]
Trying to change the filter on **Source** does not display correctly and nor does it allow clearance of the previous selection in this field.
Example using Verify:
- Click **Create a filter** 
- Click the **Source** button
- Select a Website & Survey, e.g. **iRecord > iRecord DRN dragonfly imports**
- Click the **Source** button again
- The previously-selected survey is not shown as ticked in the popup.
- If a new survey is selected, records from _both_ surveys are shown in the grid but only one is named in the **Source** button.

Workaround: click **Reset** to clear down to the default criteria. (Slow and annoying.)

See also #87, regarding a similar issue (now resolved) with the 'When' criteria.

**Comment by johnvanbreda** [comment]
Thanks. Fixed in the codebase - will be deployed next time we do a feature release.

**Comment by DavidHepper** [comment]
Further assessment, after the fix: 
To clear a **Source** filter it is best to clear the tickboxes from right to left, i.e. clear Col3 then Col2 then Col1. It is harder to finder the ticked entries in Col2 if Col1 has already been cleared. Ideally, unticking a box in Col1 would automatically untick all the dependent boxes in Col2, Col3...
