### ISSUE TITLE
iRecord records not saving/not connecting to warehouse

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1513]
@BirenRathod @johnvanbreda 
Following link to record returns error message ‘Failed to connect to warehouse1.indicia.org.uk port 443: Connection refused 

It is possible to log in to iRecord, but the error message below is returned when a record is submitted

- the data could not be saved
- validation errors occurred when this form was submitted to the server. The form configuration may be incorrect as it appears the controls associated with these messages are missing from the form [and many more lines of detail]

**Comment by DavidRoy** [comment]
Should have been a minor blip while some work is ongoing to reduce redundant data storage on the server
