### ISSUE TITLE
Emails not sending from PHP's mail function (e.g. Recording Group invites)

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#1522]
As noted for Plant Portal in this issue (https://github.com/BiologicalRecordsCentre/plantportal/issues/87), the email is not sent because it uses the built-in PHP mail function which has never worked on Pantheon sites.

Switch all iForm mailing functionality to use Drupal's mailing facility which works well on NPMS.

Create hostsite_send_mail or similar function.

**Comment by Sam-Amy** [comment]
is this the same as [https://github.com/BiologicalRecordsCentre/iRecord/issues/1298]([](https://github.com/BiologicalRecordsCentre/iRecord/issues/1298))

**Comment by andrewvanbreda** [comment]
Hi @Sam-Amy 

That issue wasn't closed as resolved.
It is therefore possible that what is described in that issue could of caused the problem I am seeing.
I am not really an expert in configuration of email systems, so I am not sure.
What I really went by was purely based on behaviour observation.

The behaviour between the two issues is the same by the sound of it though, that the email doesn't send.......but the cause could well be different/

All I can also tell you that the invites were broken at the time I raised this issue. 
I cannot tell if that means last year's issue was never fixed, or it was fixed and there is a new problem.

Essentially I observed that the emails stopped sending when we moving to Pantheon hosting (unless coincidence)
The fix I suggested to John for that problem was to change the way the emails were being sent (using Drupal email service instead of PHP) and he agreed.


I actually haven't got around to implementing the main fix yet (I just did a smaller fix that would of stopped the mail sending in Drupal 8+, that fix is still in Develop so hasn't been deployed).

@johnvanbreda @BirenRathod 
Is it possible what I saw wasn't a problem with Pantheon and PHP's mail function, and is just the problem you mention in the other mail that hadn't been fixed?

Andy

**Comment by BirenRathod** [comment]
@andrewvanbreda Not sure what problem you are referring to about the thread but iRecord doesn't have any problem sending emails.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Unfortunately there are problems, as have tested with John
e.g Send Invites to a recording group does not arrive.

The problem is PHP's mail function doesn't work.
This same function does not work on NPMS, but that site overcomes that problem by using Drupal mail service in a custom function.

I think this started failing with the move to Pantheon.

I spoke to John about this yesterday, and I will go ahead and change Indicia to include a hostsite_mail function that uses Drupal mail instead.

Say if you still think what I am saying is wrong, so I don't change a load of code unnecessarily.

**Comment by BirenRathod** [comment]
Hi @andrewvanbreda Yes, that is fine. Go ahead to change that.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod ,

So I have attempted a fix for this, and although I was able to get the Drupal email to work (on my test multidev Plant Portal site), we have a big problem.

The problem is that the Drupal mail system does not support html mails.

I have checked this situation with John, and although it may be possible to get this to work with the assistance of a module, that is not ideal.
This leaves me with one choice, and that would be attempting to lift Drupal's mail code, put it into iForm, and remove the code that is deliberately converting it to plain text.

This would be a faff, but also something I would need to check with David for budget for.

So having spoken to John, our conclusion about the most sensible initial way forward is if we could ask you if you would be able to look into the existing problem please?

That problem is this.
Although mails work from the Warehouse and Drupal, any emails sent from Indicia's PHP code using PHP's built in mail function, do not work.
These emails include verification emails, Recording Group invites.

Would you be able to see if you could get these to work by fiddling with the configuration on Pantheon.
I am 75% sure this situation stated when the sites moved to Pantheon hosting, so would of been a long time ago.

Thanks for any further thoughts/help on this.

Andy

**Comment by BirenRathod** [comment]
@andrewvanbreda I believe this has been resolved now.

**Comment by andrewvanbreda** [comment]
Closing, ongoing tweaks being handled in https://github.com/BiologicalRecordsCentre/iRecord/issues/1571
