### ISSUE TITLE
Is it possible to look at all updates for a record in pgAdmin

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1523]
There is a record (ID: 136037) which was accepted, but then the grid reference was altered to be in the sea and so it was rejected. Is it possible to see whether the record was updated by someone manually? 

I've found updated_by_id in the occurrences table but this has the id of the verifier who rejected the record. I wondered whether there was a way to view update history (similarly to looking at redeterminations)? I've also had a look at updated_by_id in the samples table, but this is the id of the person that created the record, and the sample hasn't been updated since the record was created.

I did double check as it is an iSpot record - the grid ref in iRecord is different to the grid ref in iSpot

**Comment by johnvanbreda** [comment]
@robin-hutchinson yes, there is a full audit trail. Here's a query that gets the history of the occurrence (and associated attribute values):
```sql
select 'Inserted' as action,
      'occurrences' as entity,
      o.id,
      o.created_on as date,
      o.created_by_id as user_id,
      coalesce(p.first_name || ' ', '') || p.surname as user,
      null::hstore as row_data_before_action,
      (select row_data from audit.logged_actions where search_table_name='occurrences' and search_key=136037 and event_record_id=136037 and event_table_name='occurrences' order by id limit 1) as changed_fields,
      case when o.created_on>'2017-05-11 12:30:27.016+01' then 'Record entered before audit logging feature added to the warehouse so initial data values may be inaccurate.' else null end as notes
    from occurrences o
    left join users u on u.id=o.created_by_id
    left join people p on p.id=u.person_id
    where o.id=136037
   
    union
    select case la.action when 'U' then 'Update ' when 'I' then 'Insert ' when 'D' then 'Delete ' when 'T' then 'Truncate' end as action,
      la.event_table_name as entity, la.event_record_id as id, la.action_tstamp_tx as date,
      la.updated_by_id as user_id, coalesce(p.first_name || ' ', '') || p.surname as user,
      la.row_data, la.changed_fields, array_to_string(ARRAY[case
        when event_table_name='occurrences' and left(changed_fields::text, 30)='"last_verification_check_date"' then 'Record cleaner rule check'
      else null
      end, case
      when session_user_name='postgres' then 'Action carried out directly on the back-end database'
      when session_user_name='indicia_data_user' then 'Action carried out directly on the back-end database'
      else null
      end], '. ') as notes
    from audit.logged_actions la
    left join users u on u.id=la.updated_by_id
    left join people p on p.id=u.person_id
    join occurrences o on o.id=la.search_key
    where la.search_table_name='occurrences'
    and la.search_key=136037
	order by date
```

This confirms that the record was accepted in June 1st 2020, then the same verifier rejected it on November 23rd 2020.

If you modify the query above to replace 'occurrences' with 'samples' and the occurrence ID with the sample ID then you will see that the sample itself has never changed - so the grid ref is as it was originally entered (or imported).  So it looks like the verifier missed the incorrect grid ref first time round.

**Comment by robin-hutchinson** [comment]
Thanks John! I don't have permission to access the audit schema, but happy if the record looks ok! I'll email back the verifier to let them know.

**Comment by johnvanbreda** [comment]
@robin-hutchinson you might like to add an issue to request a better way of searching the audit information, based on this report. The audit UI in the warehouse is currently not working very well so could do with an overhaul.

**Comment by robin-hutchinson** [comment]
Good point - that is done now

**Comment by DavidRoy** [comment]
The original record supplied by iSpot had the NX201486 grid reference.  See: W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Loading\iSpot moth data 2013-02-19 with ObsID.xlsx

It is likely that the record subsequently got corrected at the iSpot end.  This was a one-off data import so we don't track any subsequent iSpot updates

**Comment by DavidRoy** [comment]
@robin-hutchinson I suggest we don't spend a lot of time tracking down inconsistencies in the iSpot data

**Comment by robin-hutchinson** [comment]
Ah thank you David, that makes sense! I'll let the verifier know.

**Comment by robin-hutchinson** [comment]
I agree - now I understand what is going on, I can explain it so it shouldn't be a problem!
