### ISSUE TITLE
Crediting iRecord when reproducing a Distribution Map

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1526]
If I wish to reproduce (not link to) a Species Distribution Map [such as this one](https://irecord.org.uk/species-details?taxon_meaning_id=21852) in a society newsletter how should I credit iRecord? How about adding a standard credit wording to the [Terms of Use](https://irecord.org.uk/terms_of_use)? Should the map have a copyright notice in the bottom right corner, similar to this one ![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/e59852ee-aece-4089-9a19-2408632d1710) on the Explore and Verify pages?

**Comment by burkmarr** [comment]
Hi David. If you copy the map using the 'Download' button, a notice is appended to the foot of the downloaded image to detail where the data come from. But if you'd rather not include that text in your newsletter, I think that just acknowledging that the map comes from iRecord - in whatever way best fits your page design - will be enough.

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/9275178/3ad15efc-7289-4009-88b2-dce971d63cc6)

**Comment by DavidHepper** [comment]
Thanks. That's helpful.
