### ISSUE TITLE
Species Distribution maps show Unverified records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1527]
The **Summary Details** page is now very useful. The distribution maps would most likely be used to show where a species (or other taxon) is known to occur within the configurable range of years. Currently the map is distorted both by the known dodgy ones that are Queried and by those simply Pending Review. Since there is no gradation of dot intensity (c.f. in Explore All Records) a single duff record in the wrong place is given as much weight as a whole set of accepted records in the right place: one filled dot.
Would it not be more useful to show only Accepted records? 
Are some groups _never_ verified, requiring unverified records to appear? It would be the only reason I can think of to retain them.

**Comment by burkmarr** [comment]
@kitenetter - it would be possible to add an 'exclude unverified' checkbox.

**Comment by DavidHepper** [comment]
@burkmarr - That would be even better, especially if it's the default so that to include Unverified requires an extra click.

**Comment by kitenetter** [comment]
@DavidHepper some groups are never verified (there are no recording schemes for some taxa, and there are still a few examples of recording schemes that exist but don't wish to engage with iRecord). So I agree that having the option to control whether unverified records are shown would be a good addition to the Summary Details pages, but I think the default probably has to be to include the unverified ones, with a click to exclude them.

**Comment by burkmarr** [comment]
@kitenetter @DavidHepper - you can try this out here: https://burkmar3-brc-irecord.pantheonsite.io/species-details

The checkbox appears below the map. A complete page resubmission is required if unverified records are to be excluded, so clicking on the checkbox resubmits the page and there is a delay before the display refreshes.

Checking the box adds a URL parameter `xu=on`. So the URL for a species page for _Araneus diadematus_ which excludes unverified records is: `https://burkmar3-brc-irecord.pantheonsite.io/species-details?xu=on&taxa_taxon_list_id=248907`. Just leave out the parameter for a map with the unverified records excluded.

This example for _Araneus diadematus_ illustrates Martin's point that it would not normally be desirable to exclude unverified records by default. The SRS is one of those schemes where verification is very patchy.

**Comment by kitenetter** [comment]
Thanks @burkmarr that works well for me.

If you tick the box to exclude unverified records, do the phenology charts also exclude them, or just the map?

**Comment by burkmarr** [comment]
@kitenetter - it only affects the map.

**Comment by kitenetter** [comment]
Would it easy to apply it to the charts as well or is that a separate issue?

**Comment by burkmarr** [comment]
Actually I was wrong - it affects the charts too!

**Comment by kitenetter** [comment]
Excellent! In which case I'd be happy for this to go live.

**Comment by burkmarr** [comment]
@kitenetter - this is deployed to live now and as a hotfeature to the client_helpers repo.

**Comment by DavidHepper** [comment]
> Checking the box adds a URL parameter `xu=on`. So the URL for a species page for _Araneus diadematus_ which excludes unverified records is: `https://burkmar3-brc-irecord.pantheonsite.io/species-details?xu=on&taxa_taxon_list_id=248907`. Just leave out the parameter for a map with the unverified records excluded.

This works well but it's the other way around: Leaving out the parameter shows the map with unverified records *included*.

**Comment by burkmarr** [comment]
@DavidHepper - yes sorry about that - I confused myself!

**Comment by DavidHepper** [comment]
This appears to work well. I only question the position of the checkbox to Exclude unverified: the other controls (on dates) are either above or at the top left of the map and it would be better for this checkbox to above the map, along with the text "Rejected and unverified records are excluded from this map."

**Comment by burkmarr** [comment]
I like that separation because the controls above the map all affect the display instantly because they simply re-visualise the data already downloaded. But using the checkbox causes a resubmission of the page to retrieve a different set of data.

**Comment by DavidHepper** [comment]
That's a technician's answer! I don't mean to disrespect the user base, of whom I'm a member, but the distinction will be lost on the average user and I doubt many will spot the checkbox.
