### ISSUE TITLE
The terms Import and Upload are used confusingly and the Import process is inconsistent

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#153]
The terms Upload and Import are used inconsistently and confusingly in the (hidden) page from where spreadsheets may be imported. The process is unintuitive and does not guide the user. The function should always be referred to as 'Import' and the term 'upload' should refer only to the tiny technical step of getting the CSV from the user to the server.
-----
- The page title is '**Import Records from a spreadsheet**' and the page URL is **http://www.brc.ac.uk/irecord/import**
- But the prompt refers to 'upload' and the button label is 'Upload':
![import csv](https://cloud.githubusercontent.com/assets/24915271/22295367/8dff5eee-e30e-11e6-94d2-98ed5a7749ae.jpg)

- There is no indication here of the number of steps before the import actually happens. The button should instead be labelled 'Next'
-----
- The next screen prompts for **Survey** and **Species List**. 
- The drop-down list of Survey names includes surveys that would never be imported like this e.g. "iRecord Dragonflies app". Can the list be pared down?
- The drop-down list of Species List names includes 'UK Master List' sorted near the bottom. Could this be the default? (It is always used for dragonflies and presumably for most others.)
- There is no 'Back' button.
- The button to accept the choices is correctly labelled 'Next' ... except that if the system finds that the fields appear to match between the CSV and the Survey selected it now does the import without further prompts! It should be labelled 'Next' and lead to a final screen indicating that the import has been validated and will take place, with an opportunity to cancel.
- If the fields do not match, the user is prompted to match them up. This works fine but the button at the bottom is labelled 'Upload'. This should be 'Next', leading to the same final screen as is reached when matching is not required.
-----
- The final screen should explain that the time taken to complete the import is proportional to the number of records in the CSV. The button should be labelled 'Import'.
-----
- If rows fail to import due to data errors (e.g. missing or invalid Grid Ref.) a useful file of errors can be downloaded. However, if the import crashes or the browser session is lost, there is no way to recover this file and the user does not know which records were imported.
-----

(Much of the above also applies to Pantheon.)

**Comment by kitenetter** [comment]
Closing, but will be addressed as part of #16
