### ISSUE TITLE
Thumbnails not showing on explore pages

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1535]
Thumbnails of photos attached to record is not showing on 'My records' or 'All records' pages E.g. record number [30849376 ](https://irecord.org.uk/record-details?occurrence_id=30849376)(see [forum post](https://irecord.org.uk/forum/general-discussion/missing-images)).

The photos are stored with the record, and they are visible as thumbnails on the verification page, it is just the Explore page that is missing them. Filtering to display only those records that don't have photos includes this record ;the filter thinks that there are no photos.

Not sure if relevant but it is marked as a sensitive record as a scarce species, and the image file sizes are quite small (55-64kb when saved from record page).

Appears to be a minor glitch and we are not aware of it affecting others.

**Comment by kitenetter** [comment]
@Sam-Amy it appears that we are hiding all photos associated with sensitive records. Must admit I wasn't aware that was happening but I can see why it might be needed. So I think this counts as a feature rather than a bug. Closing.

**Comment by johnvanbreda** [comment]
@kitenetter that's correct. The original thinking was that we can't be sure if anything in the photo gives the location away.
