### ISSUE TITLE
Taxon to add - Tithonia rotundifolia

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1537]
Missing taxa to record in iRecord - Tithonia rotundifolia

Listed by BSBI DDb but missing from UKSI?
https://database.bsbi.org/object.php?objectid=2cd4p9h.vgsh6e&class=TaxonInstance

@kitenetter I'm not sure of the mechanism for adding names

**Comment by kitenetter** [comment]
Requests for additions to UKSI need to go to Chris Raper. I believe Chris is working with BSBI on the next major update for plants but I'm not sure where that has got to, can @Sam-Amy update us (and let us know if we should ask for this particular taxon to be added, or whether we should wait for the wider update)?

**Comment by Sam-Amy** [comment]
I'll ask Chris to add this if there has been no further progress. This is one of the newer garden plants which probably make up a large portion of the species not yet in the UKSI. 

Can you remind me @kitenetter please, are UKSI updates now being fed back through to iRecord regularly now?

**Comment by kitenetter** [comment]
John said "the first one has been done, process is semi-automated but requires manual scheduling, ideally every month or two"

**Comment by johnvanbreda** [comment]
I think we said we'd discuss prioritising the next update at the last iRecord progress meeting. It may be worth me doing one alongside @burkmarr so we are both able to do them.

**Comment by Sam-Amy** [comment]
UKSI import file for Tithonia rotundifolia and parent Tithonia sent to Chris as no progress on the wider update yet.

**Comment by burkmarr** [comment]
@johnvanbreda wrote:

> It may be worth me doing one alongside @burkmarr so we are both able to do them.

If you identify a time when you want to do this @johnvanbreda - let me know and I'll observe as planned.

**Comment by johnvanbreda** [comment]
@burkmarr I can be free to do this from mid next week - I'll request a UKSI update from Chris so we are ready.

**Comment by burkmarr** [comment]
@johnvanbreda - okay, I will send you an email re availability.

**Comment by Sam-Amy** [comment]
@DavidRoy where did this request originally come from? Thanks

**Comment by DavidRoy** [comment]
@Sam-Amy me wanted to submit a record of an 'escaped' plant in Wallingford.  Not urgent but wanted to capture this inconsistency between the BSBI list and UKSI
