### ISSUE TITLE
Maintenance for NBN exports

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1539]
I used to go here to manage our NBN exports under the old system:
http://192.171.199.201/exports

That link seems not to be available any more, has it been made available anywhere else, or have we lost the ability to use the old exporter altogether?

**Comment by johnvanbreda** [comment]
@BirenRathod do you know?

**Comment by BirenRathod** [comment]
@johnvanbreda & @kitenetter This (http://192.171.199.201/exports) site is no longer available to access due to UKCEH security policy. Under this policy, we are no longer to use old version of PHP 7.4.

**Comment by johnvanbreda** [comment]
@kitenetter do you have a list of the additional exports that we should set up using the new Elasticsearch system?

**Comment by kitenetter** [comment]
As discussed via email, John will look at "automating the [ES] filter setup as it may actually save me time in the initial setup. I’ll have a look at that first and will revert to manually setting up the filters if it looks like a bigger task to automate it."

**Comment by johnvanbreda** [comment]
I have now implemented an automated creation of the filter for an export, using the filter ID of a filter that's been created. This simplifies the creation of the required configuration a lot, though there are still a few files to copy and edit to create a new export (takes a few minutes now and it's fairly simple). 

I've set up an export for all the filters which started with "NBN" in the title so I think that is everything? There were 74. In doing these, I've created a folder to hold the metadata required for the DwC archive for each, but the eml file is a blank stub for all of them (apart from the ones where the export already existed so I could obtain an EML file). 

Also, for all the new exports, the config/*.json file contains a few settings such as the filter ID. I've set these up, but the datasetName and rightsHolder are just set to "---" so will need to be updated as appropriate.

Finally - there is a batch file called `c:\indicia\run-all.bat` which will recreate all the exports. It will take a few hours to run. @BirenRathod - just letting you know that you can run this batch file on the Elasticsearch server if Martin needs to regenerate all the exports. I have tested quite a few of the exports but not all so let me know if any don't generate correctly.

**Comment by kitenetter** [comment]
I think I have now got all the files up to date.

@BirenRathod please can you run `c:\indicia\run-all.bat` as soon as you get a chance (does that need to be done overnight?).

@johnvanbreda can you let me know why we have two versions of the Natural England export:
- FILTER NBN - Natural England iRecord Surveys.json
- FILTER NBN - Natural England iRecord Surveys v2.json

**Comment by johnvanbreda** [comment]
@kitenetter I'd created this filter for testing under my own account a few years ago - when i generated all the exports I didn't spot that this was linked to my account so did not need to be done. I've removed it.

**Comment by BirenRathod** [comment]
@johnvanbreda I just started to generate exports file by running the run-all.bat file and I got the very first PHP warning.
@johnvanbreda is this okay to ignore? The process is still running, so not sure if should I stop in the middle of running it.

Here is the warning -- PHP Warning:  Elasticsearch\Connections\Connection::Elasticsearch\Connections\{closure}(): Argument #2 ($key) must be passed by reference, value given in C:\indicia\ipt-dev\vendor\elasticsearch\elasti
csearch\src\Elasticsearch\Connections\Connection.php on line 336

**Comment by johnvanbreda** [comment]
@BirenRathod fine to stop the process - worst it will do is make a partially complete export. Let me know when it is stopped and I will take a look - I didn't see this error when I tried it the other day.

**Comment by johnvanbreda** [comment]
@BirenRathod ignore the above - this is a PHP warning emitted due to the Elasticsearch library not being upgraded to support PHP 8.1, but it should work fine anyway. So fine to just leave the process running.

**Comment by BirenRathod** [comment]
@johnvanbreda It is still running, do you think that is okay or unusual?

**Comment by johnvanbreda** [comment]
It will take quite a while (maybe several hours) - you should see the files being updated in the exports folder as it proceeds.

**Comment by BirenRathod** [comment]
@johnvanbreda I can understand that but it is not even processing the first file, so bit more suspicious.

**Comment by johnvanbreda** [comment]
I agree - looks like it is stuck. Please stop your copy and let me know so I can try it out.

**Comment by BirenRathod** [comment]
@johnvanbreda I stopped now. It has thrown below error, so something is not right there. See below for more error.
.....................................................................................................................................................................PHP Fatal error:  Uncaught Elastics
earch\Common\Exceptions\Missing404Exception: {"error":{"root_cause":[{"type":"search_context_missing_exception","reason":"No search context found for id [145216247]"},{"type":"search_context_missing_e
xception","reason":"No search context found for id [145216245]"},{"type":"search_context_missing_exception","reason":"No search context found for id [145216246]"},{"type":"search_context_missing_excep
tion","reason":"No search context found for id [145216248]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":-1,"index"
:null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [145216247]"}},{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":
"No search context found for id [145216245]"}},{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [145216246]"}},{"shard":-1,"index":
null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [145216248]"}}],"caused_by":{"type":"search_context_missing_exception","reason":"No search context fou
nd for id [145216248]"}},"status":404} in C:\indicia\ipt-dev\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:628
Stack trace:
#0 C:\indicia\ipt-dev\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(295): Elasticsearch\Connections\Connection->process4xxError()
#1 C:\indicia\ipt-dev\vendor\react\promise\src\FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#2 C:\indicia\ipt-dev\vendor\guzzlehttp\ringphp\src\Future\CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then()
#3 C:\indicia\ipt-dev\vendor\guzzlehttp\ringphp\src\Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#4 C:\indicia\ipt-dev\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(315): GuzzleHttp\Ring\Core::proxy()
#5 C:\indicia\ipt-dev\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(187): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#6 C:\indicia\ipt-dev\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(107): Elasticsearch\Connections\Connection->performRequest()
#7 C:\indicia\ipt-dev\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Client.php(1586): Elasticsearch\Transport->performRequest()
#8 C:\indicia\ipt-dev\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Client.php(1056): Elasticsearch\Client->performRequest()
#9 C:\indicia\ipt-dev\dwc-generate.php(302): Elasticsearch\Client->scroll()
#10 C:\indicia\ipt-dev\dwc-generate.php(1351): BuildDwcHelper->buildFile()
#11 {main}
  thrown in C:\indicia\ipt-dev\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php on line 628

**Comment by johnvanbreda** [comment]
@BirenRathod I have double clicked on run-all.bat using Windows Explorer (from the C:\indicia folder on the Elasticsearch server) and it is currently running fine - it's generated 14 exports in the last half an hour with no warnings. Did you run it from Explorer, or do something else to start the bat file off?

**Comment by BirenRathod** [comment]
@johnvanbreda That is good news, I always run through Windows explorer.

**Comment by johnvanbreda** [comment]
Ok - for now I will finish running it so that @kitenetter can get the latest export files. Once this is done, you can try again and we'll see if we can diagnose why there is a difference between when you run it and when I run it.

**Comment by kitenetter** [comment]
I now have a copy of the exported files thanks.

Two of them appear to be way too large, @johnvanbreda can you check the export code for these:
- filter_nbn___shieldbugs.zip
- filter_nbn___sawfly_records_from_irecord.zip

**Comment by johnvanbreda** [comment]
The filter implementation in the NBN export code doesn't currently support all possible filter options - I'd left out a small number of options which I'd thought weren't used. These both use a scratchpad for the taxon list which I hadn't realised was used so I've now implemented this option and regenerated the 2 files.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda that looks better. I have copies saved so if you need to do any testing on the ES server with Biren it's fine to do so. I'll do some final checks on Monday before sending to NBN but it looks like it is working well.

**Comment by kitenetter** [comment]
@johnvanbreda in at least one of the exports, 'training' records have been included. Does that mean that all the exports could include training records? If so then we'll have to adapt the code to exclude training, and re-run the process.

**Comment by johnvanbreda** [comment]
I've fixed the code and started the process again.

**Comment by kitenetter** [comment]
@johnvanbreda the bat file for the Calliphoridae data was referring to the wrong filter, so I've edited the filter name in the bat file. Please can you re-run this one:
FILTER NBN - Calliphoridae data from iRecord - generate.bat

**Comment by kitenetter** [comment]
Also, I can't find an export file for the Chrysomelidae - I can't see any problems in the bat file so could you try re-running this one as well:
FILTER NBN - Chrysomelidae beetle data from iRecord - generate.bat

**Comment by kitenetter** [comment]
Also missing:
FILTER NBN - RISC Heteroptera Non-Native Species Records - generate.bat

**Comment by johnvanbreda** [comment]
All done - the missing files were due to small mistakes in the config which are now fixed.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - I'll close this issue.
