### ISSUE TITLE
Generic editing tool

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#154]
There is a need to provide a generic record editing tool for records which don't have the recording form available for various reasons (e.g. BDS records entered on the old website which now no longer has the forms).
* This form will be entirely generic and allow editing of the main attributes and custom attributes of the occurrence record, plus sample and optional parent sample.
* It will need to work across website IDs
* Could be like an editable version of the details panel used for verification of a record.
* Could be accessed to allow editing a record from within the verification tool, or from a separate report listing record.

**Comment by kitenetter** [comment]
Ensure this also deals with #120

**Comment by johnvanbreda** [comment]
There is now a new sharing mode allowing websites to agree to allow other websites to edit their records. I've added a demo page to iRecord which allows you to edit records from the BWARS single species surveys and sent the link to @kitenetter and @DavidRoy to check.

**Comment by DavidRoy** [comment]
Thanks John.  Closing as looks to work as expected
