### ISSUE TITLE
Email expert issue

### ISSUE THREAD

**Issue by cubitmg** [BiologicalRecordsCentre/iRecord#1544]
I was using the email to expert function from the Verify (photo version) page. The popup to allow the email address to be selected and subject and body of email to be updated was shown. Chrome offered a my email address to use as a prefill. When I clicked on that offered email address it populated both the email address and the subject line text. I sent the email and only saw the subject line text as I did so.. The record id is: 32202735. The email being sent is recorded in the record comments. However, and this may or may not be related the email never arrived.
I attach screen shots of the prefill popup (for a different record) and the comment in the record mentioned above.
When I just types the full email address and left the subject line unchanged then the email did arrive (albeit into Junk which may be a further issue!)
![iRecExpertEmailComment](https://github.com/BiologicalRecordsCentre/iRecord/assets/65334323/2b1dfd7d-cffb-4d04-bd1d-af8c380f258e)
![iRecExpertEmail](https://github.com/BiologicalRecordsCentre/iRecord/assets/65334323/ec7f1077-bf82-46da-986c-91224dbf3407)
.

**Comment by kitenetter** [comment]
This seems to be a browser issue. As far as I'm aware emails are being sent correctly. Closing for now.
