### ISSUE TITLE
Deleted records not being removed from ES pages

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1547]
During testing I added two record to the vascular plant recording form, record IDs 32255524 and 32255526 (both part of the same sample). These are not genuine records, and after testing I deleted them. They are showing as deleted if I try to find them in the warehouse interface. However, they are still displaying on the "My records" and "All records" pages, and on the verification page.

If I try to edit the records from the "My records" page, I arrive at the vascular plant form, but it is displaying various "Unsupported control" messages.

If I try to edit the records from the verification page I get "The record you are trying to load does not exist".

The records are not visible on the old (non-ES) explore page, so I guess this is a problem with the ES version not getting properly updated following the deletes.

**Comment by DavidHepper** [comment]
This is the same issue as #1543.

**Comment by kitenetter** [comment]
Thanks David, I'll revert to the previous issue and close this one.
