### ISSUE TITLE
Changing grid ref in iRecord hasn't changed gridref_calculated.

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1548]
This record was edited last week as the grid reference was incorrect. It has changed the Gridref column correctly, but the grid ref calculated has stayed the same so its going to the wrong verifier:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/b74c9d54-99c8-4d88-9bcc-62232137ddc5)

**Comment by johnvanbreda** [comment]
@robin-hutchinson Gridref_calculated is a custom value stored by the app, not a part of the Indicia core system. Therefore there is nothing in the system which triggers it to be updated if the grid reference get's altered. It should not be used either when the system filters the list of records for a verifier - are you sure that the record is still going to the wrong verifier?

**Comment by robin-hutchinson** [comment]
Ah that makes sense thank you - yes I noticed this as the verifier told me they were getting notifications for that record this morning. As you can't edit records in the app is there any way to change this?

**Comment by robin-hutchinson** [comment]
I've double checked that and I was wrong, sorry! they were getting notifications as they had previously commented on the record to verify it, telling them that the verification status had changed (the comments not the verification). So they have notifications about it, but it is going to the correct verifier! Sorry again, I'll close the issue!

**Comment by johnvanbreda** [comment]
@robin-hutchinson you can edit this value on the records edit form used by verifiers to change records - i.e. https://irecord.org.uk/edit-generic-record?occurrence_id=32372015.

**Comment by robin-hutchinson** [comment]
Thanks so much John, I've fixed that now.
