### ISSUE TITLE
Record > Activities - inconsistent Species picklists across Forms

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#155]
The picklist for selecting a Species by common, scientific or 2+3 name is not consistent across all Forms. For example, entering "banded" at a Species field on the BDS forms.
- Form 'Enter a List...' shows incomplete list (Banded Agrion, Banded Darter) 
- Form 'Enter a Single...' shows complete list (Banded Agrion, Banded Darter, Banded Demoiselle, Banded Demoiselle Damselfly) 

These are respectively:
http://www.brc.ac.uk/irecord/enter-dragonfly-list?group_id=149&implicit=t
http://www.brc.ac.uk/irecord/enter-dragonfly-record?group_id=149&implicit=t

[Note that the presence of the archaic common name "Banded Agrion" in both lists is considered to be a problem with the UK Species Index and not with iRecord. However, it is unfortunate that the name picked by the original recorder is 'frozen' into the record, even if it is deprecated, potentially making searching harder.]

**Comment by kitenetter** [comment]
I've checked the settings for those two recording forms and I can't see any difference in the way they handle species names, so there must be another issue here.

**Comment by kitenetter** [comment]
Is this the same issue as #138 ?

**Comment by DavidHepper** [comment]
Yes, I believe this is the same issue as #138. It would provide another example for testing when #138 is fixed.

**Comment by johnvanbreda** [comment]
#138 now closed.
