### ISSUE TITLE
NBN export for NE data

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1551]
For the export to NBN Atlas of NE data we set up a custom filter, see https://github.com/BiologicalRecordsCentre/iRecord/issues/351#issuecomment-395712209

Can the new export procedure be adapted to replicate the old one? I'm guessing that the config file `FILTER NBN - Natural England iRecord Surveys.json` will need editing.

**Comment by kitenetter** [comment]
@johnvanbreda is it possible to resolve this issue in the next few days so that it can be included in the data that will go to NBN Atlas at the end of the week?

**Comment by johnvanbreda** [comment]
I'll take a look this afternoon @kitenetter.

**Comment by johnvanbreda** [comment]
Now done and the file has been generated.
