### ISSUE TITLE
Record deletion request

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1554]
Please could the records with the ids attached be deleted?

[Records to be deleted.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/12620092/Records.to.be.deleted.txt)

**Comment by burkmarr** [comment]
@robin-hutchinson  - I just attempted this deletion using pgAdmin, but I was unable to run an UPDATE query. It looks like I can currently only run read-only transactions on the new Warehouse. I've raised a ticket with IT to sort it out. I'll keep you posted.

**Comment by BirenRathod** [comment]
@burkmarr Did you run a query using indicia_user?

**Comment by burkmarr** [comment]
Yes I think so:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/9275178/c6ec6dc1-7178-4a4f-90d7-0e7260a6a097)

**Comment by burkmarr** [comment]
The problem was that I had connected pgAdmin to the database replica, which is for reporting only. Once I connected to the actual database server I was able to update. 

@robin-hutchinson - I've marked those occurrences as deleted now and removed the corresponding records from the cache_occurence_functional and cache_occurrence_nonfunctional tables.

**Comment by BirenRathod** [comment]
@burkmarr That is interesting as replica doesn't allow to connect using indicia_user. Anyway, as long as you managed to update records is matter.

**Comment by robin-hutchinson** [comment]
Thank you! I'll close the issue.

**Comment by burkmarr** [comment]
@BirenRathod - I've definitely got a connection to the replica with indicia_user so perhaps something needs looking at there?

**Comment by BirenRathod** [comment]
@burkmarr Don't worry about it. I mentioned it as I didn't realise that you have used a replica server before.
