### ISSUE TITLE
Provide butterfly app summary report for 2023

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1557]
We've been asked why there is no butterfly app summary for 2023, in the list of reports under Summarise - Survey summaries.

@DavidRoy @johnvanbreda can I just clone the [2022 report page](https://irecord.org.uk/butterfly-summary-2022) and then edit it so that the year parameter is set to 2023, or is it more complex than that?

**Comment by BirenRathod** [comment]
@kitenetter yes, you can clone it and rename it with 2023 but it needs to change the year in the iform settings.

**Comment by BirenRathod** [comment]
@kitenetter I just checked, you can change the year value in the form structure.

**Comment by kitenetter** [comment]
Thanks @BirenRathod 

I've created the 2023 summary page: https://irecord.org.uk/butterfly-summary-2023

Questions:
1. On the "Overview" tab no totals are being displayed - is there something else that needs to be done to make this happen, or does it just take time to generate?
2. On the 2022 page the is a URL redirect from "/butterfly-info-centre-2022", do I need to set up an equivalent redirect for the 2023 page?

**Comment by BirenRathod** [comment]
@kitenetter 
1. you just need to clear the cache which I did. So all done.
2. you don't need to create a redirect as the menu link has already got the original link.

**Comment by kitenetter** [comment]
Thanks again @BirenRathod - closing.
