### ISSUE TITLE
Unable to query records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1559]
Just tried to query a record from my verification page, using the add a comment option. I type in the comment, and then click "Add comment". In the background, the record gets removed from the verification grid, but in the foreground the comment box remains and can only be removed by clicking cancel. Having done that, when I go back to the record it is not displaying the comment, nor the 'queried' status.

**Comment by DavidHepper** [comment]
I make quite a few comments, including some on multiple records, yesterday evening and they all seemed to work. Firefox 117.

**Comment by kitenetter** [comment]
Thanks @DavidHepper 

I will test again and save a HAR file. (I was using Edge.)

**Comment by johnvanbreda** [comment]
@kitenetter no need for the HAR - I think I've reproduced the problem and a fix will follow shortly.

**Comment by johnvanbreda** [comment]
Should be fixed now.
