### ISSUE TITLE
Slow appearance of records in Verify after Import or Edit

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#156]
I'm getting reports that the Verify queue not updating to show newly-imported or recently-edited records, with delays of 20 minutes. Is there some view caching or delayed view rebuilding going on or have we missed a 'refresh' feature?
David

**Comment by johnvanbreda** [comment]
There is an delay related to the fact that records are indexed against their vice county polygons every 15 minutes by a background task. This means that any report filter based on vice county will not pick up records added since the last task run.

**Comment by DavidHepper** [comment]
Thank you!
