### ISSUE TITLE
Anchor links on help pages

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1560]
Is it possible please for me to add anchor links to jump further down the same page on the help pages on iRecord (I am trying on the test site)? I would like to have subheadings listed at the top of the page that link to the correct section further down the page. I managed to do it by adding the following code, but this disappeared as soon as I opened the edit page again, so I must have some error 

I added this to the text at the top: 
<p><a href=https://test-brc-irecord.pantheonsite.io/help/how-do-i#Submit>

And this on the line I want it to link to:
<a href="#" name="Submit"></a>

I've seen examples online where there is a different button next to the link button in the toolbar of the body text box - either with an anchor or flag - is this something that could be enabled?

**Comment by BirenRathod** [comment]
Thanks, @Sam-Amy for creating this issue.

Basically, you need to add an id on each h3 tag and create a href link using that id `<a href='#[id]'>`. I have created two at the top of the page.

**Comment by Sam-Amy** [comment]
Thanks @BirenRathod
