### ISSUE TITLE
Content images function not working

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1565]
Content images function is not allowing us to upload images when editing page content. The only way currently to upload images is to use the icon in the toolbar, but this doesn't allow images to be resized.

This 'insert' button does nothing:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/f540c776-4924-4de1-ac72-48173b4844e2)

Seems to be working ok on the test site though.

**Comment by BirenRathod** [comment]
@Sam-Amy it does add an image but needs to refresh the page by clicking on the browser reload button at the top left corner. Not sure why it doesn't immediately react but I will find out about it.

**Comment by Sam-Amy** [comment]
I can't make it work even after re-loading the image, and refreshing the cache on the page [https://irecord.org.uk/run-bioblitz](https://irecord.org.uk/run-bioblitz)

**Comment by BirenRathod** [comment]
@Sam-Amy No need to refresh the page. just need to reload the page. This is a temporary option while I investigate more into it further.

**Comment by Sam-Amy** [comment]
Reloading doesn't seem to achieve this for me? The only way can add an image is a workaround that Martin showed me by copying the correct url (for the file manager location) in to source code, but I have to re-size the image first.

**Comment by BirenRathod** [comment]
@Sam-Amy it is loading but it inserts at the top of the body text editor. Also, you can achieve resizing when popup windows appear after clicking on the image icon at the top of the body text editor.

**Comment by Sam-Amy** [comment]
@BirenRathod Images are not inserting like this for me, so I'm not sure what I am doing differently to you? But no problem I can manage the way I am doing and yes, that is how I was re-sizing (just meant normal options e.g. colourbox large/medium not available). Thanks
