### ISSUE TITLE
Unable to add occurrence to an existing list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1566]
I went to add an extra occurrence to an existing list of records, starting from this edit page:
https://irecord.org.uk/enter-record-list?occurrence_id=31791623

and clicking the button to "Show the full list of records"

The occurrence would not save, and generated this error:
`The data could not be saved.`
`Validation errors occurred when this form was submitted to the server. The form configuration may be incorrect as it appears the controls associated with these messages are missing from the form.<ul><li>form_error_messages.licence_id.default<br/>&nbsp;&nbsp; (related to attribute [occurrence_medium:licence_id])</li></ul>`

**Comment by DavidHepper** [comment]
Dragonfly verifier Mike A. reports today that this error is more general to Editing any existing record, not limited to adding an occurrence to a sample.

**Comment by johnvanbreda** [comment]
@JimBacon I'm working on the basis that this is related to the sequence issue we tried to fix on Friday.

**Comment by johnvanbreda** [comment]
Ignore the above comment. I've discovered the licence ID is not being set correctly in the form for existing photos so the form won't save.

**Comment by johnvanbreda** [comment]
Fixed
