### ISSUE TITLE
Are rule checks and indexing running since restart?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1568]
We have new records coming in following the restart, but as yet no rule checks have been applied to any records added since the restart. Geographical indexing also appears not to be happening.

**Comment by johnvanbreda** [comment]
@BirenRathod this is because the Indicia Workqueue task in the scheduled tasks library was disabled and hadn't been restarted. I've restarted it now.

**Comment by BirenRathod** [comment]
Thanks, @johnvanbreda yes indeed I have disabled it but I'm sure I restarted it anyway thanks again @johnvanbreda .

**Comment by johnvanbreda** [comment]
No worries - easily missed as you had a lot on your plate yesterday! You did restart the other task, it was just this one that was disabled.
