### ISSUE TITLE
Reports not working on new server?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1578]
- The public 'My data summary' completes eventually.
- The custom 'Verifier record counts by Vice County' report https://irecord.org.uk/elastic/verification/stats/counts_by_vc shows number behind rotating rings that never complete.
- I'm sure there were more reports advertised somewhere but they're not in the menu system yet. Is that right?

**Comment by kitenetter** [comment]
The second bullet point is covered by #1601 

Not aware of any 'missing' reports, although potentially the "Summarise" section of iRecord would benefit from a review. Closing for now.
