### ISSUE TITLE
iNat Eurasian Copper Underwing Complex Complex appearing as Copper Underwing

### ISSUE THREAD

**Issue by cubitmg** [BiologicalRecordsCentre/iRecord#1579]
There are records that are "agg" / complex in iNat are coming through as specific species into iRecord. for example this one:
https://irecord.org.uk/record-details?occurrence_id=33423571

This is not really acceptable and causes lots of extra work for verifiers.

**Comment by kitenetter** [comment]
This is being addressed under #1222
