### ISSUE TITLE
Occurrence page login redirect

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#158]
If a user is logged out and visits an occurrence page, say **..../record-details?occurrence_id=4405519** it quite nicely presents some details about the record, next to it is the login form if the user wants to log in and see more details. After you login it **redirects you away to your user account page**. Which is not great if you came to this record from an app and must navigate back to the page.

![screen shot 2017-02-02 at 16 45 21](https://cloud.githubusercontent.com/assets/7383162/22558904/51aceac4-e967-11e6-90b6-d00cfd047c65.png)

**Comment by kitenetter** [comment]
This appears to have been fixed. Closing.
