### ISSUE TITLE
Photo verification page: enable selection of multiple tick boxes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1580]
On the photo verification page we now support "multiple selection mode". When this mode is active, can we add an option to select the tick boxes for all records on the current page of the grid (i.e. the equivalent of the column head tick box on the standard verification page)?

**Comment by cubitmg** [comment]
This would still be of great value and would provide consistency across the same function as available on the standard Verify page or a tickbox in the header row ticking all records.

The additional value is that once all records have been selected/ticked then one or more can be unticked allowing the bulk of the records to have their verification status set and leave the few for further consideration at a later time.

**Comment by kitenetter** [comment]
This appears to have been duplicated by #1690 so I will close this one.

**Comment by cubitmg** [comment]
Sorry. I'm not very good at finding existing issues!
