### ISSUE TITLE
NBN Atlas data exports

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1583]
@johnvanbreda please can you run the process to generate all the NBN data files in the next day or two.

**Comment by johnvanbreda** [comment]
That's now done. For info it took 2 hrs 6 minutes in total.

**Comment by johnvanbreda** [comment]
@BirenRathod @JimBacon did the process for creating Elasticsearch exports for the NBN Atlas get migrated to a new server? Or is this a task still to be done?

**Comment by JimBacon** [comment]
I have no knowledge of this process so have not done anything related to it.

**Comment by BirenRathod** [comment]
that was on the ES server, so need a copy of it.

**Comment by JimBacon** [comment]
I think that means it is a task still to be done. Can you do it, @BirenRathod, since you know what is required?

(Probably entirely irrelevant: we investigated migrating Kibana dashboards but this was not supported for a leap from v6 to v8)

**Comment by JimBacon** [comment]
@johnvanbreda are there files (and documentation) for this in a git repo somewhere?

**Comment by BirenRathod** [comment]
I have already sent a request to set up an old server to Damien.

**Comment by johnvanbreda** [comment]
> are there files (and documentation) for this in a git repo somewhere?

https://github.com/Indicia-Team/support_files/tree/master/Dwc%20Exporter

The actual config files could indeed do with going in a repo I guess.

**Comment by kitenetter** [comment]
@JimBacon are we able to estimate when the NBN data exports will be available again? I need to inform our partners about this. What scale of work is involved?

**Comment by JimBacon** [comment]
@BirenRathod undertook this work and I believe it was completed.

**Comment by kitenetter** [comment]
Thanks @JimBacon and @BirenRathod 

@johnvanbreda I would like to generate the next set of data files, but before we do that can we address #1595

**Comment by BirenRathod** [comment]
@kitenetter Still pending. I'm in the process of resolving that.

**Comment by johnvanbreda** [comment]
@BirenRathod I will make a new version of thew DwC Generate script which works with the latest Elasticsearch PHP client and Elasticsearch 8.x whilst I resolve #1595.

**Comment by BirenRathod** [comment]
@johnvanbreda that is a good idea as I was looking at this morning the script I think that is needed but before making sure with you I needed to test first, so taking a bit longer for me to respond anyway you are doing, no need to test. saved time actually.

Another issue is to allow @kitenetter to run this script. I have one idea at present but before confirming that can I ask you where are you going to run or test this script from?

**Comment by johnvanbreda** [comment]
@BirenRathod I've pushed a version of the dwc-generate code which works on Elasticsearch 8 and PHP 8.2. I have only tested this on my local development setup, I'm not sure how to test on the live infrastructure.

**Comment by BirenRathod** [comment]
@johnvanbreda That is fantastic. where did you push the code? I'm thinking of testing using wlsc-brcmgm01 VM at present. Let's see, how it goes. it will take time as I need to set up some bit on it.

**Comment by johnvanbreda** [comment]
I've also fixed #1595 as requested by @kitenetter.

@BirenRathod the code is in a subfolder of the support files repository - https://github.com/Indicia-Team/support_files/tree/master/Dwc%20Exporter.

**Comment by kitenetter** [comment]
@BirenRathod how close are we to being able to produce NBN export files? The February deadline is tomorrow, 2 Feb, otherwise our next target is 1 March.

**Comment by BirenRathod** [comment]
@kitenetter This is not going to happen soon but we can target to do for 1st March. I'm following IT regarding this.

**Comment by kitenetter** [comment]
Thanks @BirenRathod, understood.

**Comment by kitenetter** [comment]
All 65 datasets were successfully generated today using the Linux VM system that Biren has provided access to. Closing.
