### ISSUE TITLE
Certain photographs assigned wrong licence attribution - apparently randomly

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1589]
On iRecord and NMRS websites certain photographs are, since the server move, assigned the wrong licence attribution:

1. Somehow during the recent migration, the licence attribution changed in iRecord from 'CCO' to 'CC BY-NC-SA'. It was originally 'CCO' in both cases. Interestingly, I note that it is shown as 'CCO' in NMRS
2. Consequently, I cannot change the licence in iRecord back to 'CCO'
3. Not all images are assigned 'CC BY-NC-SA'. However and interestingly, the wrong licence attribution is only assigned to the following record IDs but in BOTH websites (NMRS and iRecord). ID references 33847762-33847791 (all images within this range). All records before and after this range in both websites appear to be correct.

**Comment by kitenetter** [comment]
The images with an incorrect licence appear to be unavailable now, and the records they are linked to have been accepted, so I don't think there is any further action we can take. Closing.
