### ISSUE TITLE
Explore all records - spurious recent records filter warning

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#159]
The default view of 'Explore all records' has a helpful warning that the map will 'only display records from the last month, unless you change the filter settings'.

This warning message can be confusing as it is still displayed even if the view is already showing records for all dates (which can be the result of following a link - without the user having cleared the date restriction filter manually).

e.g. clicking on a link to 'Explore records of Ourapteryx sambucaria' from an occurrence page leads to the 'Explore all records' page with the date constraint filter already cleared, but the page still displays the warning message.

The warning should only be displayed if a date constraint filter is set.

**Comment by kitenetter** [comment]
Have updated the text to say "if you have arrived here from "Explore - All records", the map will only display records from the last month". Not the ideal solution but hopefully will reduce confusion for now.

**Comment by kitenetter** [comment]
A longer-term solution/enhancement would be to have some way of highlighting what filters are currently in operation.
