### ISSUE TITLE
Some iNat record grid refs differ from map location

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1592]
Some records are showing differences between the grid references (which in the following cases I think are probably correct) and the locations shown on the map in the verification page (which are therefore probably wrong being around 10km south of where they should be): See records 33820466, ~512-517, ~537, ~539-544. One record (3380542) does not give a full reference, but does appear on the map in more or less the same location as other records from that recorder.

E.g.
[https://irecord.org.uk/record-details?occurrence_id=33820466](https://irecord.org.uk/record-details?occurrence_id=33820466) Grid ref given as 56.551N, 4.218W, Uncertainty 1170m

Map on record details page:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/1047579b-757f-48c6-949e-9d31759266fa)

Map on verification page: 
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/7f5e9880-c363-4819-8005-8efcd8ce8022)

Map on iNaturalist showing about 10+ km further North
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/980d2ddd-ecf5-4f8f-abd8-603ce5d76fc6)

**Comment by johnvanbreda** [comment]
Jim already has this on the task list for post migration fixes. There was a period of time when the new system first came online where the spatial functions built into PostGIS had an incorrect calculation, resulting in the offset you see. We will at some point re-calculated the geometries for these records.

**Comment by JimBacon** [comment]
I did the work to fix this on 7th December.
If a problem still exists, please can you let me have more details so I can investigate.

**Comment by Sam-Amy** [comment]
For record ID 30154522 the grid reference TQ40910965 is displaying more than 20km south of its true location in Lewes. Screenshot shows correct location (red arrow, above) and iRecord location (point in sea, below).

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/07f8ec51-3d65-47ff-8f2a-3df474357bb4)

**Comment by JimBacon** [comment]
I reckon I only fixed records created on 14th November and this one has slipped through because it was updated on that date. I guess there might be one or two others that I have also overlooked.

**Comment by Sam-Amy** [comment]
From a list of iNat records imported before 14th Nov but updated on 1415th Nov in update time order, and by manually checking occasional records I found that any updated at or before 19:22:16 on 14th Nov had errors, but after that didn't.  I'm not sure why there were no updates before 16:12 that day based on my query (below), but based on this, the 711 iNaturalist records in the attached list I think probably have the error. 
[iNat_likely errors.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/13875648/iNat_likely.errors.csv)

select cof.id, w.title as website, cof.updated_on
from cache_occurrences_functional cof 
join websites w on w.id = cof.website_id
where w.title like 'iNaturalist' 
and extract (year from cof.updated_on) = '2023'
and extract (month from cof.updated_on) = '11'
and extract (day from cof.updated_on) in ('14','15')
AND cof.created_on < '14-11-2023'

**Comment by JimBacon** [comment]
Good work. I'll get those fixed. There were no updates earlier in that day as the warehouse was off line while we migrated to the new infrastructure.

**Comment by JimBacon** [comment]
I found 1040 records which need updating from 3 surveys which are either lat/lon points or OSGB grid squares.
@Sam-Amy can you check a random selection and close the issue if all seems okay?

In the following queries
- The faulty records are found by comparing the entered_sref, normalised to a consistent format, against a spatial reference back-calculated from the geom. 
- The correct geoms are calculated from the entered_sref. 
- Both the samples tables and cache tables are updated.

For points the query was
```sql
with points as (
  select 
    id, 
       
    -- Calculate correct geom
    case 
      when position('E' in entered_sref) != 0 then
        -- '<lat>N <lon>E' format
        st_transform(st_geomfromtext(
          'POINT(' ||
          substring(entered_sref from ' (.*)E') || ' ' ||
          substring(entered_sref from '^(.*)N') || ')',
        4326), 900913)
      when position('W' in entered_sref) != 0 then
        -- '<lat>N <lon>W' format
        st_transform(st_geomfromtext(
          'POINT(-' ||
          substring(entered_sref from ' (.*)W') || ' ' ||
          substring(entered_sref from '^(.*)N') || ')',
          4326), 900913)
      when position(',' in entered_sref) != 0 then
        -- '<lat>, <lon>' format
        st_transform(st_geomfromtext(
          'POINT(' ||
          substring(entered_sref from ', (.*)') || ' ' ||
          substring(entered_sref from '^(.*),') || ')',
        4326), 900913)
      when position(' ' in entered_sref) != 0 then
        -- '<lat> <lon>' format
        st_transform(st_geomfromtext(
          'POINT(' ||
          substring(entered_sref from ' (.*)') || ' ' ||
          substring(entered_sref from '^(.*) ') || ')',
        4326), 900913)
      end as correct_geom,
       
    -- Reformat entered_sref consistently to 5 decimal places for comparison.
    case 
      when position('S' in entered_sref) != 0 then
        'Eeek - Southern hemisphere'
      when position('E' in entered_sref) != 0 then
        -- '<lat>N <lon>E' format
        round(substring(entered_sref from '^(.*)N')::numeric, 5) || ' ' ||
        round(substring(entered_sref from ' (.*)E')::numeric, 5)
      when position('W' in entered_sref) != 0 then
        -- '<lat>N <lon>W' format
        round(substring(entered_sref from '^(.*)N')::numeric, 5) || ' ' ||
        '-' || round(substring(entered_sref from ' (.*)W')::numeric, 5)
      when position(',' in entered_sref) != 0 then
        -- '<lat>, <lon>' format
        round(substring(entered_sref from '^(.*),')::numeric, 5) || ' ' ||
        round(substring(entered_sref from ', (.*)')::numeric, 5)
      when position(' ' in entered_sref) != 0 then
        -- '<lat> <lon>' format
        round(substring(entered_sref from '^(.*) ')::numeric, 5) || ' ' ||
        round(substring(entered_sref from ' (.*)')::numeric, 5)
      else
        'Problem!'
      end as consistent_entered_sref,
       
    -- Calculate sref from geom in same format.
    round(st_y(st_transform(geom, 4326))::numeric, 5) || ' ' || 
    round(st_x(st_transform(geom, 4326))::numeric, 5) as calculated_sref
  from samples
  where date(updated_on) = '2023-11-14'
  and entered_sref_system = '4326'
),
update_samples as (
  update samples
  set geom = points.correct_geom, updated_on = now(), updated_by_id = 2
  from points
  where points.id = samples.id
  and points.calculated_sref != points.consistent_entered_sref
  returning samples.id
),
-- updated sample cache
update_cache_samples as (
  insert into work_queue (task, entity, record_id, params, cost_estimate, priority, created_on)
  select 'task_cache_builder_update', 'sample', samples.id, null, 100, 2, now()
  from update_samples, samples
  where samples.id = update_samples.id
  and samples.deleted = false
  order by samples.id
)
-- updated occurrence cache
insert into work_queue (task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', occurrences.id, null, 100, 2, now()
from occurrences, update_samples 
where occurrences.sample_id = update_samples.id
and occurrences.deleted = false
order by occurrences.id
```

For OS grid refs the query was 
```sql
with polygons as (
  select 
    id, 
       
    -- Calculate correct geom
    convert_osgb_to_geom(entered_sref) as correct_geom,
       
    -- Reformat entered_sref to no more than 10m accuracy.
    case length(entered_sref)
      when 12 then 
        substring(entered_sref from 1 for 6) ||
        substring(entered_sref from 8 for 4)
      else
        entered_sref
      end as comparable_entered_sref,
       
    -- Calculate sref from geom
    get_output_sref(accuracy, geom) as calculated_sref
    
  from (
    select samples.*,
    case length(entered_sref)
      when 4 then 10000
      when 6 then 1000
      when 8 then 100
      when 10 then 10
      when 12 then 10
      end as accuracy
    from samples
    where date(updated_on) = '2023-11-14'
    and entered_sref_system = 'OSGB'
  ) sq
),
-- update all sample records
update_samples as (
  update samples
  set geom = polygons.correct_geom, updated_on = now(), updated_by_id = 2
  from polygons
  where polygons.id = samples.id
  and polygons.calculated_sref != polygons.comparable_entered_sref
  returning samples.id
),
-- updated sample cache
update_cache_samples as (
  insert into work_queue (task, entity, record_id, params, cost_estimate, priority, created_on)
  select 'task_cache_builder_update', 'sample', samples.id, null, 100, 2, now()
  from update_samples, samples
  where samples.id = update_samples.id
  and samples.deleted = false
  order by samples.id
)
-- updated occurrence cache
insert into work_queue (task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', occurrences.id, null, 100, 2, now()
from update_samples, occurrences
where occurrences.sample_id = update_samples.id
and occurrences.deleted = false
order by occurrences.id
```

**Comment by Sam-Amy** [comment]
Thanks @JimBacon, I've checked a random selection and all looks good now.
