### ISSUE TITLE
NBN export handling absence records incorrectly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1595]
In #381 we stated that zero-abundance records were being excluded from NBN export files.

The NBN DwC format does allow for zero-abundance records to be flagged as such, under attribute "occurrenceStatus", which is defined as "the presence or absence of individuals in the occurrence".

However, it has been reported that NBN Atlas is displaying zero-abundance records of glow-worms (from the iRecord glow-worm survey) as "present". Glow-worm records go to NBN as part of the soldier beetles recording scheme dataset.

In the file that we send, we are including the zero-abundance glow-worm records, and they are being flagged as "present" under the "occurrenceStatus" attribute.

Ideal solution is to include zero-abundance records in the datasets we generate for NBN, but make sure that they are correctly flagged as "absent".

Work-around if needed: go back to excluding all zero-abundance records from all datasets that we generate for NBN Atlas.

Example occurrence IDs of zero-abundance records that are being flagged as "present" in the NBN datasets:
32126885
32126848
31772978
26319483
24311017
14386821
10507718
6988445
5347999

**Comment by johnvanbreda** [comment]
Done - occurrenceStatus is set dynamically using the zero abundance flag.
