### ISSUE TITLE
ES errors

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1600]
As you've probably seen, iRecord is generating a lot of "Elasticsearch query failed" messages at the moment. Not sure who is best placed to look into this @JimBacon @BirenRathod @johnvanbreda

**Comment by BirenRathod** [comment]
@kitenetter yes, we already noticed that and @johnvanbreda has started looking into it.

**Comment by robin-hutchinson** [comment]
Possibly related - clicking the download link on https://irecord.org.uk/downloads is producing the error: An error occurred with the request to download data.

**Comment by johnvanbreda** [comment]
Yes, all related. An upgrade to Drupal 10.2 has been pushed through Pantheon which has broken the way some of our web service proxies worked. I have a fix in the pipeline but it has required quite a lot of refactoring.
