### ISSUE TITLE
'Verifier record counts by Vice County' never completes

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1601]
The summary view 'Verifier record counts by Vice County' shows plausible Count values but never completes. I don't know whether to believe the numbers.

**Comment by DavidHepper** [comment]
And I can't screen-scrape the table to update my stats because I'm unable to highlight any text.

**Comment by DavidHepper** [comment]
I cannot carry out my role of helping and shepherding my verifiers without this basic report. Recently we submitted an update to NBN Atlas with several VCs unverified for a whole year and it's almost impossible to spot them without this report.

**Comment by kitenetter** [comment]
@johnvanbreda if possible it would be good to add a csv download button to this report. For reference the link is:
https://irecord.org.uk/elastic/verification/stats/counts_by_vc

**Comment by DavidHepper** [comment]
The other issues referring to this one have been closed but the 'Verifier record counts by Vice County' page still never completes:
![image](https://github.com/user-attachments/assets/64b7ecee-75da-4195-b4a2-44552b22d9c6)

**Comment by DavidHepper** [comment]
Do others see the same issue here? Is there any other report that could produce figures similar to this? I really need the results, please.

**Comment by johnvanbreda** [comment]
@DavidHepper I've fixed this now - there was an issue with the pager causing it to crash due to the custom nature of the query on this report. 

I can't easily add the download tool to this report, but you can manually select the rows and copy and paste into Excel.

**Comment by DavidHepper** [comment]
Excellent! Thank you. After clearing cookies it now completes quickly.
