### ISSUE TITLE
iRecord offline

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1603]
At the moment I'm getting an "unexpected error" message when I try to access the home page.

@BirenRathod @johnvanbreda

**Comment by kitenetter** [comment]
The home page has now become available again. Will close this issue shortly.

**Comment by BirenRathod** [comment]
@kitenetter It has been resolved now after clearing the cache. Once I get time I will debug the code for below error.
UnexpectedValueException: base:Downloads has no corresponding route. in Drupal\Core\Url->getRouteName() (line 567 of /code/web/core/lib/Drupal/Core/Url.php).
