### ISSUE TITLE
Downloads tab in Explore

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1604]
In Explore all records, the Downloads tab shows explanatory text:
`Any downloads you generate using the data on the Records, Species, Families and Groups tabs will appear here.`
However, it does not appear possible to generate a download of Records because the download button is missing from the Records tab. Being able to download exactly what I'm seeing on the Records tab would be such a useful and intuitive feature.

**Comment by DavidRoy** [comment]
This functionality is deliberate as we do not want to bypass formal data publishing by recording schemes

**Comment by DavidHepper** [comment]
OK, just correct the explanatory text, then?

**Comment by kitenetter** [comment]
Text now updated to:

Any downloads you generate from the Species, Families and Groups tabs will appear here (download from the Records tab is only available when using "My records").
