### ISSUE TITLE
Dynamic stage terms have been lost from "enter a list" recording form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1605]
The default [enter a list](https://irecord.org.uk/enter-record-list) form is not providing the dynamic termlist for stage, and is defaulting to the "pre-adult" etc. generic terms.

**Comment by johnvanbreda** [comment]
This is the same underlying issue as https://github.com/BiologicalRecordsCentre/iRecord/issues/1600. I've committed a fix to the code but will need to wait for the warehouse to be updated tomorrow before it can be applied.

**Comment by johnvanbreda** [comment]
Have requested for Biren to update the iform module upstream.

**Comment by BirenRathod** [comment]
@johnvanbreda All sites have been upgraded with the latest iForm code.

**Comment by johnvanbreda** [comment]
Thanks Biren, closing.

**Comment by kitenetter** [comment]
@johnvanbreda I think this was fixed for a while, but it has gone wrong again today. Also, a verifier has reported that a significant number of records entered into the iRecord General survey in 2023 have missing stage information, so I wonder whether this has been a recurrent bug for a while.

**Comment by kitenetter** [comment]
(Ignore the comment about "a significant number of records entered into the iRecord General survey", it looks like most of them were entered onto a correctly working form, it's just that the recorder chose to give the stage as "not recorded".)

**Comment by DavidHepper** [comment]
FYI: if a dragonfly species is selected on the enter-record-list form, the Stage options list changes to **adult / pupa / cocoon / etc.** from the short **not recorded / adult / pre-adult / other** list, which I think is as expected.

**Comment by kitenetter** [comment]
Actually you can ignore me altogether, I was forgetting to enter a taxon into the list. Apologies, it must be the end of the week ...
