### ISSUE TITLE
Records showing as unreleased?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1610]
This has just happened in the last few minutes I think (11.30pm 17 Jan). All of a sudden, if I try to view one of the record details pages it is showing as "unreleased". This seems to be applying to all records, both my own and from other users. Happening in Edge and Brave browsers.

Will check in the morning to see if this is persisting.

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/d8495ae0-c6fd-468c-8639-9171c4c2d942)

**Comment by johnvanbreda** [comment]
Fixed.
@andrewvanbreda note that this was an additional fix to the reports parameters change we discussed yesterday so may be worth double checking your reports still work.

**Comment by kitenetter** [comment]
Records displaying correctly again, thanks.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Yes all seems to be working still. Thanks for letting me know.
