### ISSUE TITLE
Layer features undefined error on record details page.

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#1611]
I found this error on irecord.org.uk/record-details page.
@johnvanbreda please have a look.
Uncaught TypeError: layer.features[0] is undefined
    initMap https://irecord.org.uk/modules/custom/iform/client_helpers/prebuilt_forms/js/record_details_2.js

**Comment by johnvanbreda** [comment]
Duplicate of #1610
