### ISSUE TITLE
Importer v2: map import column matching

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1613]
In the grid for mapping import columns there are some very helpful buttons for choosing an attribute where more than one match is suggested. However, there always seems to be a duplicated suggestion, see example below.

Also, can we remove the attribute "Recorder names" from the standard attribute list, so that the only choice is "Recorder Name"? I'm not sure if we need to retain "Recorder names" at all, given that it does fulfil the need for a recorder as a Required field. But if we do need to retain it can it be shifted into the "advanced" fields, and given a name that is more different to "Recorder Name" to avoid confusion. (Not sure what that name should be because I don't understand what this attribute is used for!)

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/d4107041-2724-4856-a209-60f29aa583aa)

**Comment by kitenetter** [comment]
One more similar request: can we remove the "Determiner" attribute (i.e. the one that links to a user ID) from the standard list, leaving just "Identified By", so that anyone importing a column headed "Identified By", or "Determiner", or "Identifier", gets automatically linked to the attribute "Identified By".

**Comment by johnvanbreda** [comment]
Duplicated suggestions now fixed. I've also removed the sample recorder names field, but only if the survey dataset has a recorded by field so there is no duplication of options. 

Regarding the determiner field, that is a custom attribute so presumably you can remove this field from the dataset @kitenetter ?

**Comment by kitenetter** [comment]
@robin-hutchinson please can you run a query for me: if you look at all records in the iRecord Import survey (survey ID 93), can you let me know how many of them include data for the "Determiner" attribute, which is attribute ID 125?

And for any that do have a value for "Determiner", can you check if they also have a value for "Identified By" (attribute 18).

(We are proposing to remove the Determiner attribute, to avoid confusion when people are uploading, but if it has been used to store names then we'll have to transfer them first.)

**Comment by robin-hutchinson** [comment]
No problem, that is attached. It looks like there are 320 records, but 282 of them have the same value in the identified by column. 26 have a different value in the identified by column, and for the rest identified by is blank.

[Determiner Data.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/14192394/Determiner.Data.csv)

**Comment by DavidHepper** [comment]
I tried importing with the Survey Dataset = 'DRN dragonfly imports' and a CSV containing only the usual v1 column headers plus one data row. Most columns matched but:
- Column header '**Species or taxon name**' fails to match Destination field '**Species or taxon name**' (!) and there is no suggestion below. It has to be manually selected. This really should match.
- Column header '**Grid ref or other spatial ref**' fails to match Destination field '**Spatial reference**' and there is no suggestion below. This is OK as I will issue a new template spreadsheet with the revised column headers.
- Column header '**Comment**' fails to match Destination field '**Occurrence comment**'. The suggestion 'Occurrence - Occurrence comment' is shown _twice_ below. This is ~OK.
- Column header '**External Key**' fails to match Destination field '**External record ID**'. This can be selected from the suggestion below 'Occurrence - External record ID'. This is OK.

The imported record looks good.
The import file is attached: [33. 2021-Beds-CSV - first row.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/14206471/33.2021-Beds-CSV.-.first.row.csv)

I then renamed the column headers to match the destination field names and tried importing again. Most fields matched but:
- Column header '**Species or taxon name**' still doesn't match - see above.
- Column header '**External record ID**' fails to match Destination field '**External record ID**'. This should now match.

The revised import file is attached: [34. 2021-Beds-CSV-revised-headers - first row.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/14206630/34.2021-Beds-CSV-revised-headers.-.first.row.csv)

**Comment by DavidHepper** [comment]
Further to the above: 
I have now separated 'Sample comment' and 'Occurrence comment' in my CSV and they match automatically to the Destination fields.
However, in the table headed Column Mappings, on the final screen before import, they appear to be destined for the same field, suggesting a clash or overwrite.
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/f4fc41a7-3a9e-45c1-ba0a-fb31910ef9f4)
When I did a test import they were actually kept separate, so this just looks wrong but works as expected - please check!

**Comment by kitenetter** [comment]
@johnvanbreda @robin-hutchinson I have edited the few records that had mismatches between "Determiner" and "Identified By", and I have deleted the custom attribute "Determiner" from the iRecord Import survey. I can confirm that if you import a spreadsheet column that has "Determiner" or "Identified By" as the heading, either will be auto-matched to "Identified By".

If the issues from @DavidHepper have also been addressed we can close this one.

**Comment by johnvanbreda** [comment]
I've fixed a few things - waiting for the code to be applied to the upstream later today:
1) Sample and occurrence comments are now labelled differently in the destination database fields on the final summary page.
2) Fixed automatic match to field names where the labels have been amended.

**Comment by johnvanbreda** [comment]
Code now applied - please close if OK @kitenetter
