### ISSUE TITLE
Comments showing from 'null' rather than name & user's filters disappeared

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1619]
A verifier's comments on others' records are appearing from 'null' rather than his name. The user ID is 373602.

The first and surname are entered correctly in the account details for both on iRecord and Indicia, though the username differs between the two - I can't remember if this is this unusual. @BirenRathod do you know what the problem could be please?

One example is 30637850, and comments from another verifier on the same record are correctly attributed:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/4532f9db-2c26-4f4e-878d-7ba7e68d24f3)

**Comment by Sam-Amy** [comment]
Something very odd has happened to this user now; all filters on their account had disappeared including verification filters (which I have now reset), but also filters which I think they set themselves on the download page (waiting for confirmation).

They applied for a Pantheon account on the 20th and it said that their name was into two systems (iRecord and BNM) so they I ticked both boxes to confirm it was them. They were then supposed to be taken to a form to set their password but this didn't happen, and they couldn't change their password in the account because they didn't have an existing password (as using the one-time link). They didn't want to risk messing up account for either of the two systems by asking for a password reset, so they gave up on Pantheon as a lost cause, though it looks like they are registered as it appears in the warehouse... 

This user does have two separate iRecord accounts, each with separate emails, one of which  is also linked to Pantheon and BNM, but not the one with verification permissions in question here, so can't see that this should be causing problems.

**Comment by BirenRathod** [comment]
@Sam-Amy I found an uncheck box of "Confirm that you are aged 13 or over" in this user profile. Is this the cause of this? I saved its profile with that checkbox now. See if that makes any difference.

**Comment by Sam-Amy** [comment]
Yes! Thanks Biren, new comments now have the verifier name next to them, though old ones remain as null. 

This reminds me that I have noticed when assigning verifiers that it is not uncommon to find that "Confirm you are aged 13 or over box" is not checked, even though it has a red asterisk suggesting it is compulsory.

The Terms of Reference just say "Do not use this website if you are under 13 years of age", but should it even be possible for people to complete their registration and start using iRecord without checking this box?

**Comment by BirenRathod** [comment]
@Sam-Amy I can't comment on term reference bit. I think @kitenetter might have got the answer to it.

**Comment by kitenetter** [comment]
@Sam-Amy will send email re age tick box
