### ISSUE TITLE
Importer v2: import error 'SyntaxError: Unexpected end of JSON input'

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1620]
Trying to import to the survey BBS (bryophyte), and get the error:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/6a522e29-14a5-4fb9-bed9-31b9c03f71da)

The data is quite straightforward I think, though there were various columns (red) not currently possible to match, and one species that I selected the correct name for.
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/6d73d406-b6a7-462d-a0d4-b7f85afc7066)

**Comment by johnvanbreda** [comment]
Hi @Sam-Amy would you be able to provide the data file you imported please?

**Comment by Sam-Amy** [comment]
[test bry data2.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/14112715/test.bry.data2.xlsx)

Thanks John. These are the field mappings I used - perhaps I have made an error there?:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/6381c663-bf53-4dcd-b284-a282d1349d11)

**Comment by johnvanbreda** [comment]
Thanks @Sam-Amy. It was related to the builds date fields which weren't implemented in the v2 importer. I've now fixed that so this should be OK.
