### ISSUE TITLE
Microsoft edge iRecord user password issue

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1621]
Every time I go to edit my account details (i.e. to go into training mode) on the Microsoft Edge browser, it gives me this error message as soon as I arrive on the page:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/006ee3f1-bce7-482e-99c2-b7fd5f60fac3)

And I then have to put my existing password in and a new one (or re-type the existing one in the two new password boxes. The problem may be that the browser is autofilling the new password boxes I think, and so then it wants the existing password to be entered. I appreciate this is a browser issue rather than iRecord, but @biren do you know what I can do to stop this please? Thanks

**Comment by BirenRathod** [comment]
@Sam-Amy I don't see it on my browser, so can't tell you but you can try accessing it on other browsers like Chrome or Firefox.

**Comment by Sam-Amy** [comment]
Thanks Biren. Do yo mean this doesn't affect you when using MS Edge? I do usually use Chrome, but it would be good to figure out what is going on here.

**Comment by BirenRathod** [comment]
No, I don't see that.

**Comment by johnvanbreda** [comment]
@Sam-Amy I've just tried in Edge in Windows 11 and I don't see that message.

**Comment by kitenetter** [comment]
I don't see an error in Edge either. Has your browser saved an incorrect version of your current password? In which case it might help to delete the saved password from your browser's password manager?
