### ISSUE TITLE
Verifiers unable to edit records

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1622]
From the verification pane, clicking on edit this record is bringing up an error message "Page not found. The requested page could not be found."

This is affecting my account and a few other have been in touch, so potentially all verifiers?
@kitenetter and @robin-hutchinson are you seeing the same?

**Comment by robin-hutchinson** [comment]
Hi @Sam-Amy yes I am getting the same error

**Comment by BirenRathod** [comment]
@johnvanbreda I checked and found that this page edit-generic-record does not exits. Has this page ever been created before or somebody has deleted it by mistake?

**Comment by BirenRathod** [comment]
@Sam-Amy, @robin-hutchinson, @kitenetter & @johnvanbreda I just checked on the old site and found it. Looks like somebody deleted it on live site.

**Comment by BirenRathod** [comment]
I have now re-created that page and it is now available on the live site.

**Comment by Sam-Amy** [comment]
It is most likely this was me Biren, as I managed to do this once before when trying to delete content - apologies if so. Thanks for sorting.
