### ISSUE TITLE
Importer v2: names used for field mapping

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1623]
In #1477 we had proposed to rename some of the Indicia attributes within the "iRecord Import" survey to clarify them. In [this comment](https://github.com/BiologicalRecordsCentre/iRecord/issues/1477#issuecomment-1749073847) @johnvanbreda said that some of these changes would need to be done following the code implementation, and would need a "page specific language strings file".

What information do you need to create that file, or can you let me know what format it needs to be in?

Are we able to include the synonyms that @cubitmg proposed in [this comment](https://github.com/BiologicalRecordsCentre/iRecord/issues/1477#issuecomment-1551434196)?

**Comment by cubitmg** [comment]
Thanks @kitenetter. A further observation is that some of the values in the 'iRecord attributes' column of the table in the comment of mine that you refer to don't actually work as column names by import/v2 as they do in import/v1 e.g. Recorder name and Identified by. So I would propose including values:
-  in the 'iRecord attributes' column where there is no value in 'change name to'
- values in the 'change name to' column
- values in the 'recognised column name' column

**Comment by kitenetter** [comment]
@cubitmg both Recorder name and Identified by should match automatically one we've dealt with #1613

**Comment by johnvanbreda** [comment]
These changes are now implemented.

**Comment by cubitmg** [comment]
Thanks @johnvanbreda .

I'm afraid "Identified by" does not seem to have been recognised?

**Comment by johnvanbreda** [comment]
@cubitmg that's because @kitenetter is looking into whether simply removing the determiner custom attribute is the best way forward - see #1613.

**Comment by cubitmg** [comment]
Ok, thanks @johnvanbreda.
I thought that looked like possibly removing determiner in favour of just using Identified by? In which case Identified by should continue to be imported by default?

**Comment by cubitmg** [comment]
Now resolved and working well.
Thanks.
