### ISSUE TITLE
Verification page: recorder experience links not working correctly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1624]
On the verification page, under the "Recorder experience" tab, there are links to see records previously accepted, or pending, or rejected. The links have got mixed up, e.g. if I click on the "Accepted" link I'm seeing Pending and vice-versa.

What is odd is that the URL seems to be correct but does not show what I expect it to show, e.g. this URL appears to be filtering for rejected records but the displays shows accepted ones:
`https://irecord.org.uk/all-records-verification?filter-quality=R&filter-date_from=2023-01-01&filter-date_to=2023-12-31&filter-user_id=18178&filter-date_age=&filter-indexed_location_list=&filter-indexed_location_id=&filter-my_records=1&filter-taxon_group_list=114`

**Comment by johnvanbreda** [comment]
Fixed.
