### ISSUE TITLE
Order of subheads in notification emails

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1627]
Previously we have made changes to ensure that record queries are given more prominence in the notifications, e.g. #1362 

I've just noticed that the emailed notifications are not following the agreed pattern - I thought they were previously so this seems to have changed, although as ever I can't guarantee that I'm remembering things correctly.

In any case, I'm now seeing examples of emails that start off with "Record Cleaner results for your records" and then "Queries on your records". The risk is that if someone has added a lot of records they will have a long list of record cleaner notifications and amy overlook the more important queries.

The ordering we had previously been aiming for was:
1. Queried
2. Not accepted
3. Redetermined
4. Commented on
5. Accepted
6. Failed automated checks

I'm not sure where the email formatting is controlled - @BirenRathod are you best placed to make these changes?

**Comment by BirenRathod** [comment]
@kitenetter by formatting means the order of those 6 items. If that is the case then it is again maintained through code. So @johnvanbreda is the best person to give input in this.

**Comment by kitenetter** [comment]
@johnvanbreda I've just received an email in which the queries are shown first, which is great. And I'm now wondering whether the example I saw where the headings were in a different order was a result of a mix-up when a recorder forwarded some message to us. I'll close this issue for now.
