### ISSUE TITLE
Importer v2: browser problem in Brave?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1628]
Just tried to import using v2 from the Brave browser. On the field matching page there are no auto-suggestions for the mapping, and the list of required fields is not shown. The "Next step" button remains greyed out and it is not possible to continue beyond this page.

Fairly sure it was working in Brave last week. It is still fine in Edge today.

**Comment by johnvanbreda** [comment]
@kitenetter please can you check the contents of the developer tools Console tab?

**Comment by kitenetter** [comment]
Just tested this again and the auto-mapping is working in Brave. Closing.
