### ISSUE TITLE
Importer v2: fails if spreadsheet has "&" in its file name

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1629]
Hopefully this won't impact many users, but if you attempt to import a spreadsheet that has "&" as part of the file name the importer cannot get past the Import settings page. The background processing does not run. No error message is generated:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/ee936fd4-8e1d-4339-b4e2-69ff7901628f)

Not a priority to fix, will add this to the guidance, but if there is an easy solution it would be good to resolve it.

**Comment by sacrevert** [comment]
I'm guessing this means that there are probably lots of unacceptable characters? Perhaps this is a matter of providing guidance rather than adjusting the system to accept any possible character that any OS can accept as a filename?

**Comment by johnvanbreda** [comment]
I'd rather the code was able to cope with this than expecting users to read the guidance. I'll post a fix shortly.

**Comment by johnvanbreda** [comment]
Fixed.
