### ISSUE TITLE
Obtaining location from images no longer possible as it was

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1631]
A user reports that it used to be possible that a location of an observation be generated when the photo was uploaded on the recording page. 

After a while this feature stopped working so they resorted to copying the photo location details from the metadata and pasting into the "Enter a spatial reference" box, then, by clicking on the "Location" box, the co-ordinates would be recognised and the location generated automatically.

In last month or so this method has also stopped working; meaning that they can no longer accurately assign a location to an observation (accessing iRecord website on a chromebook).

@kitenetter do you now if this is somethign possible from other OS and/or why this functionality changed?

**Comment by johnvanbreda** [comment]
I know that this functionality has been developed only for specific projects with Indicia and it has never been the case that an uploaded photo's location was automatically extracted into the sample spatial ref on iRecord.

**Comment by Sam-Amy** [comment]
Thanks John. Have there been any changes recently to the 'enter spatial infomation field' (i.e. the requirement to choose between ref types) that might prevent copied location metadata from working there as it had been?

**Comment by johnvanbreda** [comment]
No, not that I am aware of.

**Comment by Sam-Amy** [comment]
OK, thanks John
