### ISSUE TITLE
LERC boundary update

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#1633]
Update the LERC boundaries (location type: LRC Boundaries, location_type_id = 1370) with new complete set of boundaries supplied to @robin-hutchinson by ALERC.

**Comment by burkmarr** [comment]
Without checking the minutia of the geometry of each polygon in the newly supplied shapefile against the geometry already in the system, it was safer to assume that any of the polygons might have changed and to therefore do a complete update. Polygons in the new shapefile were used to replace existing polygons where the LERC names matched.

The update and re-indexing is complete now.

Workflow for future reference:

- Downloaded a complete set of names from the Warehouse as a CSV (`select name from locations where location_type_id = 1370 and deleted = false`) and also saved a copy of the new shapefile as a CSV from QGIS. Both had 66 LERCs.
- Sorted the two CSVs on LERC name, pasted into a single spreadsheet and compared with an Excel formula.
- In this case, there were two differences. It was obvious that these were both mistakes in the Shapefile (rather than amendments to the names currently in the Warehouse), so I edited the shapefile to fix the problems, then I repeated the comparison to ensure that I had spotted all the errors on those two lines.
- Zipped up the saved Shapefile and then used the Warehouse interface to update the locations (https://warehouse1.indicia.org.uk/index.php/location).
- Although the upload of the zipped shapefile to the server was okay, the actual update failed with a Kohana error indicating that some memory allocation limit had been exceeded. To get round this I used QGIS to save the polygons into a number of smaller shapefiles (five). I zipped these up and used the Warehouse interface to upload these individually which worked. All the messages indicated that an existing location feature was updated.
- Checked the work queue in the warehouse on pgAdmin to check that `task_spatial_index_builder_location` tasks had been entered into the work queue and kept an eye on these over the next few hours to see that they completed okay.
- In fact there were 8 tasks that errored. The `error_detail` message said something about a 'block'. I'm not sure what caused them but I re-entered these 8 tasks `insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)  
select 'task_spatial_index_builder_location', 'location', record_id, 70, 2, now() 
from work_queue where task = 'task_spatial_index_builder_location' and error_detail > ''` - which completed okay in due course - and deleted the 8 errored tasks.

**Comment by burkmarr** [comment]
@robin-hutchinson it may be worth letting your contact at ALERC know about the name alterations so that they can update their master copy. The two alterations are shown below. The first of each pair is what was supplied and the second is what I changed it to in order to match our existing records.
```
RECORD - Biodiversity Information Centre for Cheshire, Halton, Warrington & Wirral.
RECORD - Biodiversity Information Centre for Cheshire, Halton, Warrington & Wirral

Warwickshire Biologcal Record Centre
Warwickshire Biological Records Centre
```

**Comment by robin-hutchinson** [comment]
Thank you Rich - I will let Deb know

**Comment by robin-hutchinson** [comment]
Hi Rich, I've just heard back from the LERCs that "filter layer still shows the old boundary but the data that comes out is for the current one so the system is working right for us to download". Do you know what would cause this?

**Comment by burkmarr** [comment]
I don't. Can we have an example for a specific LERC?

**Comment by robin-hutchinson** [comment]
Sure thank you it was NESBReC - ALERC just sent a new update, but I'm not sure how different it is, I'll email it over but also ask what the changes are to see if we can avoid redoing it!

**Comment by kitenetter** [comment]
@robin-hutchinson is this issue still open?

**Comment by kitenetter** [comment]
@robin-hutchinson @burkmarr is there any update on this one? Note that the Channel Islands have been updated separately and we don't want to over-write them, see #1671

**Comment by burkmarr** [comment]
@kitenetter - the Shapefile that ALERC sent back in February had many problems and Robin and I corresponded by email about it but we never got a replacement so no update occurred. More recently they indicated to @robin-hutchinson that a new update may be coming soon.

**Comment by burkmarr** [comment]
@kitenetter - on the issue of the Channel Islands being updated separately, it underlines a point of concern for me in that I don't think that we really have an agreed 'source of truth' for the various LERC boundaries and what they actually are. One of the problems with the last shapefile was that it did not include the marine buffers. Ideally we'd agree with ALERC exactly what the LERC boundaries should be like and they would be the single 'source of truth'.

**Comment by johnvanbreda** [comment]
@burkmarr I agree with your concerns, though the Channel Islands update was supplied by Jersey and Guernsey record centres working in conjunction so I am reasonably sure they are as they should be.

**Comment by burkmarr** [comment]
I agree @johnvanbreda - but we need to know, for example, what we do if ALERC supply us with a full update which includes CI. Do we override those that came direct from the CI centres? It all needs hammering out.

**Comment by robin-hutchinson** [comment]
In Debs last email, she said:

"I recently emailed LERC members to check their details were correct and have made a few changes (contact numbers etc)  
I am planning to send out to non-members in the next few days. " 

I can double check whether they plan to include CI in the shape file, and if so is this based on the files sent by the CI centres. Deb also said

"The BBDP process is likely to change the boundaries with the formation of a couple of new LERCs, I think(?)."

Which would mean a larger update.

**Comment by kitenetter** [comment]
This is an issue for ALERC to resolve. I agree that they need to decide on a consistent way forward, and that the inclusion of marine buffers is highly desirable (and was originally requested by the LERCs).

I'm going to close this for now, but when we next hear from Debs we need to check that the marine buffer issue has being correctly addressed, and maybe have a discussion with her to clarify things if the next version she sends is still problematic from our perspective.
