### ISSUE TITLE
Error message on iRecord pages

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1634]
This has just appeared for me:

cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:https://warehouse1.indicia.org.uk/index.php/services/report/requestReport?report=library/notifications/notifications_list_for_notifications_centre_simple.xml
Server response
{"error":"Report: \/srv\/sites\/warehouse1.indicia.org.uk\/reports\/library\/notifications\/notifications_list_for_notifications_centre_simple.xml\npg_connect(): Unable to connect to PostgreSQL server: FATAL: password authentication failed for user "indicia_report_user"\nFATAL: password authentication failed for user "indicia_report_user"","code":0,"file":"\/srv\/sites\/warehouse1.indicia.org.uk\/application\/libraries\/XMLReportReader.php","line":441,"trace":[]}

@BirenRathod @johnvanbreda can you advise?

**Comment by kitenetter** [comment]
Appears to be affecting other Indicia sites as well, or at least I can't see any data on the PoMS website.

**Comment by johnvanbreda** [comment]
It appears like the reporting user account's password has changed on PostgreSQL but I don't have permission to change it. Have reported to @BirenRathod as well as posted on Teams for Damien to pick up.

**Comment by BirenRathod** [comment]
@johnvanbreda & @kitenetter please check now and let me know if this hasn't resolved yet.
