### ISSUE TITLE
Importer v2: what should we do after validation checks fail?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1635]
An import has failed. After acknowledging the modal error box: 
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/8e583ed6-9bcf-4dc6-8f7e-08059df70c6b)
there's no indication of which records failed or why. 

The page hangs like this:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/cb10a98c-6b9b-4e7a-a851-4b658b647c63)

**Comment by johnvanbreda** [comment]
This shouldn't get stuck like that - it's a server-side error. Fortunately I've managed to find it in the logs (needle/haystack comes to mind!) so should be able to post a fix later.

**Comment by DavidHepper** [comment]
Thanks. I wanted to get these in and used the Importer v1 instead. It successfully imported all 2,579 records.
The v2 file that failed, in case useful, is this one: 
[34. 2021-Beds-CSV - remaining rows.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/14210764/34.2021-Beds-CSV.-.remaining.rows.csv)

In case it's useful for logs I usually work from a static IPv4 address: 31.22.14.139

**Comment by johnvanbreda** [comment]
Now fixed.
