### ISSUE TITLE
Problem with new verification filter

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#164]
I've just set up a verification role and filter for user:
http://www.brc.ac.uk/irecord/user/225

The filter is for Diptera in Orkney:
http://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=3155

But if I masquerade as this user and go to their verification page, it is showing me all ~2 million unfiltered records.

Have I done something wrong or is there a bug here?

**Comment by kitenetter** [comment]
I've just deleted the filter I created yesterday, and removed the verification role for the user. Then recreated the filter, and added back the verification role. The correct set of Orkney Diptera is showing in the filter itself, which is now at:
http://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=3159

but the same problem remains if I masquerade as the user and go to their Verify page - all records are showing.

**Comment by kitenetter** [comment]
Have had a another go at this:
- Removed the verifier role from http://www.brc.ac.uk/irecord/user/225 and saved
- Deleted the existing verification filter
- Created two new filters, one using "insect - true fly" and one using "Diptera" (filter IDs 3187 and 3188)
- Gave verification role back to user
- Masqueraded as user and went to verification page: it is still showing all records from all locations, and also it is not showing a "Context" box, despite there now being two filters assigned to the user

@johnvanbreda any ideas on what the problem might be?

**Comment by johnvanbreda** [comment]
Lee had created 2 user profiles at some point, by registering again with a capital L in his email. The filters were therefore linking to the wrong profile. I've tidied it all up.

**Comment by JimBacon** [comment]
Note an issue already exists to try to prevent this. https://github.com/Indicia-Team/warehouse/issues/151
