### ISSUE TITLE
Spider recording form: synonyms not labelled as such

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1641]
On the iRecord generic list of records form, if you add a name that exists in multiple versions it tells you which is the current name and which a synonym:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/8435e0ea-1a40-4639-bc8d-e35572e39582)

On the spider form we are only displaying the names without giving any context:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/eb807750-602c-4c8e-8ae3-4d1c524dcb98)

I can't remember what controls this behaviour - is it one of these controls on the form:
- "Include both names in species controls and added rows"
- "Include taxon group name in species autocomplete and added rows"

Also, I think we should tick the box to display the icons for ID difficulty (or did BAS ask us not to do that?).

**Comment by burkmarr** [comment]
I've ticked those three boxes. I don't recall Richard saying they didn't want ID difficulty, but we probably never showed it to him. No doubt we will hear from them if they want it removed.
