### ISSUE TITLE
NBN Atlas exports: check filter settings to ensure iNat is included

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1645]
A number of our NBN dataflow filters currently exclude iNaturalist data - this was originally done to exclude records with mixed licences that NBN couldn't process, but that is no loner an issue. Review the NBN filters to add in the iNat datasets where appropriate.

**Comment by DavidHepper** [comment]
What has changed at iNat? We can't persuade them to default to CC BY for the observation.

**Comment by kitenetter** [comment]
@DavidHepper nothing has changed as far as I'm aware.

**Comment by kitenetter** [comment]
NBN export datasets checked and iNat included where appropriate. Closing.
