### ISSUE TITLE
v2 importer: unhelpful error message for Irish VCs

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1646]
At 22:37 this evening I tried to import an Excel spreadsheet containing three records from Northern Ireland, with grid ref H977903, using the v2 importer. All the initial settings were okay, and I used the Irish grid reference option. All three records failed to import. The downloaded 'errors' file gave the error as "[{}]" so I can't tell what went wrong.

I can't see anything in the file that would cause problems.

**Comment by kitenetter** [comment]
It seems that the problem arose from including a vice-county column, that contained the "H" prefix for the Irish vice-county. The importer expects this attribute to be an integer.

It is common practice to use the "H" prefix for Irish vice-counties, but the GB vice-county attribute is restricted to integers to allow consistent matching of VC number to VC. Need to put some more thought into how we handle the import of Irish VCs (this will also arise for the proposed work for BBS). For now I will add something to the guidance about this.

In the meantime it would be helpful if the error message could be more informative, and ideally if this type of error could be checked as part of the pre-import checking process.

**Comment by johnvanbreda** [comment]
I've fixed the issue with [{}] in the error response - the Vice County is separate. Please close if you are happy with the resolution for Irish VCs being through documentation.
