### ISSUE TITLE
Can't access user account - taken to blank T&C page

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1649]
User ID 375564 account can't be accessed. User was trying to change password but reset link in email takes them to an odd blank Terms and Conditions page, which is where I am also taken if I try to masquerade as them.

They are hoping to use iRecord for a bioblitz tomorrow so if anyone can take a look today that would be much appreciated @BirenRathod, @johnvanbreda?

**Comment by kitenetter** [comment]
It also seems to be the case that the user's Drupal account does not seem to have ticked the box to accept the terms, but it's not possible to tick the box, it seems greyed out. Can the admin accounts normally tick that box or does it have to be done by the user themself?

**Comment by BirenRathod** [comment]
@kitenetter That should be ticked by user them shelves. it seems like user has missed to tick that box.

**Comment by BirenRathod** [comment]
@Sam-Amy I'm going to delete his account as even I can't able to enabled it. Can you ask him to re-register the account? Let me know and I will delete his account.

**Comment by Sam-Amy** [comment]
Will this affect their access to records? I guess we can identify and John can re-attach the records to the new account later.

**Comment by BirenRathod** [comment]
I don't think he has got any records but please check with him first. he has just registered about 2 hours ago.

**Comment by Sam-Amy** [comment]
OK, thanks Biren that's fine

**Comment by BirenRathod** [comment]
Sorry @Sam-Amy. what is fine? shall I delete or not?

**Comment by Sam-Amy** [comment]
Yes please!

**Comment by BirenRathod** [comment]
@Sam-Amy I deleted her account. Ask her to register again using same email address, please.
