### ISSUE TITLE
Vascular plant recording form - icon to show additional fields is missing

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1652]
On the vascular plant recording form there are additional fields within the 'Plant records' tab that can be viewed by clicking in the white space to the right hand side of the record row. There should be an icon here to show that this is possible, but it is currently blank. I'm not quite sure what the icon shoudl be, but can something be added please?

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/5ff22baa-c4ad-4110-949b-6aa64a51af5e)

We will also need this functionality on the bryophyte form as we are looking to add extra fields. Having copied the source code for this from the vascular plants form in a test version ([https://irecord.org.uk/BryophyteBBS_test](url)) the same issue obviously arises.

**Comment by kitenetter** [comment]
@Sam-Amy you should find that if you fill in a species name in the first column, a plus sign appears on the right to give access to the additional attributes, but you have to add a species first.

What is the toggle button under "spatial ref" supposed to do? I can't see anything happening when I click on that.

**Comment by Sam-Amy** [comment]
Ah yes, sorry, hadn't noticed that, thanks! I think the toggle was intended to alow for a more precise grid reference associated with an individual species, and I see you had added an issue for that here last year: https://github.com/BiologicalRecordsCentre/iRecord/issues/1540
