### ISSUE TITLE
Importer v2: unable to upload using TVKs

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1654]
A couple of weeks ago I tried to upload a file of 7,688 records using Taxon Version Keys to bring in the names. The file appeared to start importing and then generated an error message:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/6027deaa-5180-451c-a265-8d7dd70f427d)

When I clicked OK on the error, the page stayed frozen saying that it had imported 631 records. I eventually closed the web page. No records were successfully imported as far as I could tell.

Is there a problem with importing using TVKs?

**Comment by kitenetter** [comment]
Just tried to import a single record using a TVK and got the same error message, so it does seem to be TVKs that are causing the problem (unless there's a problem with the spreadsheet itself).

**Comment by johnvanbreda** [comment]
@kitenetter can you send me the example spreadsheet and settings used please - my attempt to reproduce this earlier failed.

**Comment by kitenetter** [comment]
Have just done another import using TVKs and all has imported correctly, so this appears not to be an ongoing issue. Closing.
