### ISSUE TITLE
Importer v2: disallow duplicate options for importing taxa?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1655]
The importer appears to allow the import of both TVKs and taxon names:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/80cf069c-c229-4f2a-8c90-05db34b48c09)

I haven't tested this, and I don't know what happens if you try to import both, or what happens if the names and TVKs are not correctly aligned. But it seems like an unwise thing to do, and I think we should only allow one or the other to be imported for any given import.

**Comment by johnvanbreda** [comment]
They could both be selected but would be in conflict (one may overwrite the results of the other). I've added checks so that conflicting fields can't be selected in the develop branch.

**Comment by kitenetter** [comment]
@johnvanbreda is this code still unreleased?

**Comment by johnvanbreda** [comment]
Yes, it's still only in the develop branch.

**Comment by johnvanbreda** [comment]
This has been deployed.
