### ISSUE TITLE
Explore and Verify: hard to fit the whole Grid below the Map

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1656]
Even with a Full HD 1080 px display, getting the header area, map and 30 rows of hits to fit is a challenge, requiring the browser to be zoomed out. In particular, there seems to be far too much wasted space above the map. The iRecord logo is unnecessary and there are white gaps between each element - title, crumb trail, explanation, search bar - none of which is collapsible. This screenshot is from **Explore my records** but is only an example. Specifically, it's impossible to select the lower 10 rows of the grid while keeping the map in view. It would be really helpful if the pages could be tightened up generally. 
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/35743ce5-8444-4332-bb61-53649de92fc2)

When viewing my own records in Explore, each row of the grid requires 3 lines of text in order to show the 3 icons in a vertical stack at the right. This is also an inefficient use of space.
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/4cf1f040-fed5-4de2-967f-36a51ad22f2d)

Consequently, even when zoomed out to 67% on my HD external monitor, it's not possible to fit the whole of the map and the grid panel on screen. Working at 50% zoom, the only level that allows them to fit, the text becomes unreadable.

**Comment by kitenetter** [comment]
@DavidHepper I've reduced the amount of text at the top of the Explore pages. I agree that there is scope for reviewing the design of other elements on these pages but I'm not sure when we will have an opportunity to do that.

**Comment by johnvanbreda** [comment]
@kitenetter without going as far as a full review, we could easily remove the breadcrumb from explore pages, plus reduce the space above the logo and between the logo and menu bar generally across the site.

There is also a recently developed option to layout the map and grid on separate tabs with the filter builder down the left - that's a bit of a more radical change though.

**Comment by DavidHepper** [comment]
Explore is certainly better now, thank you. Verify has a much smaller header area anyway so is acceptable.
