### ISSUE TITLE
Project/activity landing pages

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#1657]
* Give each Activity its own home page, with data summaries and a unique shareable URL
* Activity home pages can include a ‘blog’ element to enhance communication with contributors

**Comment by johnvanbreda** [comment]
Suggested approach:
1. Make a small library of reports, maps and any other visualisations and wrap them up in Drupal blocks, so they can be added to any page. For example, this would include the recent records, photos and maps from iRecord’s home page, but we could also add a map of all records, a pie chart of verification statuses or taxon groups, or recorder league tables etc. Where appropriate I can pinch the code for these from Rich’s visualisations.
2. Make a new module that auto-detects a URL such as /groups/<group title> where the group title is in lowercase, with hyphens instead of spaces.
3. We can automatically generate a link to that URL from the Activities list page in iRecord.
4. When a request to a group/<group title> page comes in, use a page template to return a default project landing page layout. This layout would be built using Drupal’s templating system and can embed any of the blocks from the library mentioned above. The module would add filters to the page so that the output from the blocks only shows the records within the activity’s filter.
5. We can use the Drupal templating system to allow different page layouts to be declared, for example a project could have a completely custom page layout, or we could configure it so that bioblitzes have a custom layout different to other kinds of activities.
6. The module would also add some extra activity specific blocks and views, for example a block for a list of the available page links for the activity, or a block for the activity’s blog entries.

There was also a separate requirement (#226) to enhance the user profile view page to make it more interesting. Although not an NCEA requirement, simply by making this library of data output blocks detect when they are shown within a user profile page and to filter to that user’s records means we can easily build a user landing page similar to the output for a project landing page, constructed with the same library of blocks but filtered to the user’s own records.

This approach would be very flexible and extensible, plus relatively simple to build. We’d make best use of the effort we put into building the library of data output blocks because the same block code can run in the context of the site home page, the user’s profile page, or an activity landing page (plus any other contexts we think of). The downside is that we wouldn’t allow users who are creating an activity to create brand new landing page templates, that would have to be done by a developer. I would imagine that most activities can share the same landing page layout anyway.

**Comment by johnvanbreda** [comment]
@kitenetter the code infrastructure required for this is now ready. Please can you feed back on the following:
1. Do you have any thoughts on what you would like to see on the default project homepage? I.e. what report outputs/visualisations etc? Maybe a sketch of a proposed layout?
2. Same question for the user profile page - shall we add some report outputs to make it more interesting? (probably best to add this to #226).
3. For the blog part of this, do you see any value in the blog content being part of the Indicia database? If not, I would suggest that we use Drupal's built in content management system to set up a blog content type so that the blog content gets stored in the Drupal database instead, as we'd be then able to leverage lots of nice features built into Drupal. There would just be a small amount of customisation to link entries to groups.
4. Should activity members be able to comment on blog entries (this adds an overhead of moderation of course)?
5. Should blog entries be able to contain images? I'm presuming that only activity admins will be able to create blog posts so that this should be low risk, but there is of course an overhead of keeping the images which will be on the Pantheon server.
6. I'm reminded of an idea that I discussed with Charles Roper (FSC) many years ago - adding a "nature note" field to samples which would allow recorders to diarise their recordings in a readable fashion (if they want to of course). This could then be used to auto-generate a feed of information about recording going on in the activity. I suspect this is out of scope but thought it worth mentioning while this is being considered.

**Comment by johnvanbreda** [comment]
Draft of project landing pages on test site.

**Comment by kitenetter** [comment]
In reply to numbered questions above:
1. What we have is a good start. Some comments and potential additions (based on Rich's visualisations) here:
[Activity home page layout.pdf](https://github.com/user-attachments/files/16639304/Activity.home.page.layout.pdf)

I realise that these suggestions may not all be achievable immediately :)

2. See #226 
3. See #1703 
4. See #1703 
5. See #1703 
6. Noted; maybe overlaps with the blog functionality to some extent? Agree that it is out of scope for now.

**Comment by johnvanbreda** [comment]
Before adding more visualisations, is it worth deciding on a smaller number of blocks to include on an activity overview page, then split the other visualisations out into other pages with links, or possibly tabs? This would avoid overloading the user with too much info and also avoid overloading the server with multiple simultaneous requests.

We could also consider an activity limited version of the species details page as an alternative to adding the various visualisations on the PDF linked above which are for a species within the activity. Also, the altitude/latitude chart could be added to the existing species account page if you think it is useful and generating it is not too resource intensive.

**Comment by kitenetter** [comment]
@johnvanbreda agree that it is useful/necessary to limit the number of blocks. Do we need to pre-define which blocks appear on the pages/tabs, or can we give users some choices when they set up the activity, so that they can opt in to including the blocks they want?

Here is another hypothetical visualisation that splits things into three pages or tabs: overview, activity progress, and taxon summary list:
[Activity multi page layout.pdf](https://github.com/user-attachments/files/16673872/Activity.multi.page.layout.pdf)

The taxon summary list then includes two links for each taxon, one that goes to a new activity-specific taxon page, and one that goes to the existing iRecord taxon summary page. I've also suggested a few additions to the iRecord page (which maybe ought to become a separate issue).

This assumes that all these things can be done without too much impact on performance! If that's not the case we'll need to think again.

**Comment by kitenetter** [comment]
I suppose this also raises questions over whether we need to retain a separate activity summary report, or whether everything now becomes part of the activity landing page.

**Comment by johnvanbreda** [comment]
I've now implemented a set of changes related to the new tabbed layout in the develop branch, ready to be deployed at the next update. This includes the blogging functionality.

I agree about the activity summary report, though perhaps we don't necessarily need to force it to be removed from any activities that still want to keep it.

The suggested additional visualisations on the species details page have not yet been done - can these be put in a separate issue to avoid scope creep? This issue has required quite a lot of new code already.

I'll flag this as coding complete so I know to do the required configuration when doing the next deployment - this will include module configuration and also setting up the new group specific species details page.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda and I agree that the scope has grown. Will move the species links to a new feature request issue.

**Comment by johnvanbreda** [comment]
Changes are now live, accepting that there are additional changes required on the species details page referred to by #1725 and #1726, so closing.
