### ISSUE TITLE
Filter settings not being displayed

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1662]
This applies to the Explore and Verification pages, and also the admin page for setting up verification filters. Using Edge, the filter boxes are not displaying any information about the settings chosen:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/55a626d4-ec40-49df-8bd4-bf39dc9369c5)

However, the boxes on the Download page are displaying as normal:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/6d83803b-5f31-48ad-9daf-c8a5b0e2baed)

**Comment by johnvanbreda** [comment]
I don't think this is a problem in the code. If I inspect the JavaScript on the page, I can search for a function called indiciaFns.updateFilterDescriptions, which has the following line of code near the end:
```js
$(pane).find('span.filter-desc').html(description);
```
However, the master branch of Indicia has the following (without the span which is no longer correct) and this matches the repository on Pantheon:
```js
$(pane).find('.filter-desc').html(description);
```
So the version loading on iRecord seems to be out of date. But if I change the settings to not compress JS files I can see that the file loaded is then correct (and the filter descriptions start working again). It's only when the JS compression is enabled that it doesn't work. I've tried clearing Drupal caches but had no luck.

@BirenRathod or @JimBacon would you be able to look into this please as I'm not at work the rest of this week?

**Comment by BirenRathod** [comment]
@johnvanbreda & @kitenetter I think it started working again after I cleared the indicia cache. Let me know if that is not the case.

**Comment by johnvanbreda** [comment]
Thanks @BirenRathod - it looks OK to me too now. I don't know why it didn't work when I cleared the cache yesterday though.

**Comment by kitenetter** [comment]
Thanks - closing.
