### ISSUE TITLE
Deleted record appearing in search grid

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1663]
For record id 35281124, the record has been deleted (I double checked this in Indicia), but is still appearing under Explore All Records:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/38f10e10-3ee9-43bb-ab54-4f803c791c34)

When you click to view record details, a notification pops up that the record cannot be found. 

I double checked and it also appears on the verification page?

**Comment by johnvanbreda** [comment]
Have reported the following on the SciCom/BRC teams chat:

> I've discovered that the PHP function date_default_timezone_get() on warehouse1 (wlsc-brcweb02) is returning UTC. Shouldn't that be Europe/London? It's causing issues with tracking of deletions on the warehouse at the moment.

I've kicked off re-running the deletions since just before the clock change when the problems would have started.

**Comment by robin-hutchinson** [comment]
Thank you John, I will let the recorder who reported it know.

**Comment by kitenetter** [comment]
Seems to be fixed - closing
