### ISSUE TITLE
Grid Column Configuration cannot be adjusted if only a few records are present in the grid

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1672]
There's a window sizing issue in Verify (and Explore?) if the wrench icon is clicked to adjust the Column Configuration while only a few rows of data are present in the grid: the column names window is set too small to be usable.
In this (deliberately extreme) example, only 2 data rows are present and only the top half of the first column name can be seen: 
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/96e9bb24-1f17-4cc0-b136-0f377556f60b)

A workaround is to remove filtering so that more data rows appear in the grid, adjust the columns, then reapply the filtering.

**Comment by DavidHepper** [comment]
It would be lovely to get this corrected. It's only a vertical sizing taking the wrong value. Having to lose the current filters just to adjust the included columns is annoying. Here's a screenshot showing just how much space isn't being used when it could be:
![image](https://github.com/user-attachments/assets/3208c42d-79e6-4095-b206-ac4e88fd9c06)

**Comment by johnvanbreda** [comment]
I've changed the code in the develop branch to use a popup dialog, rather than fit this inside the grid's container. This will be released at the next full code update.

**Comment by DavidHepper** [comment]
Thank you! Looking forward to this...
