### ISSUE TITLE
Bloomin Algae summary report missing

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1676]
The Bloomin algae record map isn't appearing on this page: https://irecord.org.uk/bloomin-algae-app-summary

The page is showing an error message:

Unable to find report specific_surveys/bloomin_algae/bloomin_algae_grid.xml.
Unable to find report specific_surveys/bloomin_algae/bloomin_algae_map.xml.

**Comment by johnvanbreda** [comment]
@BirenRathod possibly a report missed when the servers migrated to the cloud?

**Comment by BirenRathod** [comment]
@johnvanbreda I believe those reports from the specific_surveys should be on the git repository. I have no recollection of migrating those reports. Maybe @JimBacon could shed more light on it.

**Comment by Sam-Amy** [comment]
This has been queried again by someone from SEPA. @JimBacon can you suggest anything please? Thanks

**Comment by JimBacon** [comment]
Fixed.
The report files must not have been under version control previously, got lost when the server was migrated to the cloud, and no one noticed in mid-winter.

There is a backup of the old warehouse reports folder on the CEH file server location `...\PYWELL_SHARED\Pywell Projects\BRC\Indicia\Migration to Private Cloud\prod` in case similar happens again.
