### ISSUE TITLE
Review code for vascular plant data export

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1677]
@japonicus has shared the code used for the last export of vascular plant occurrence data for BSBI (2019, I think), which I have saved at [BSBI_Indicia_Reporting/vascular_plant_occurrences.sql](https://github.com/Sam-Amy/BSBI_Indicia_Reporting/blob/main/vascular_plant_occurrences.sql).

This seems to run fine, but if anyone could please have a quick look for areas that may need updating (i.e. to reflect database changes since 2019) that would be much appreciated, as I'm not yet clear on all aspects of it especially around the spatial reference and attributes @JimBacon @johnvanbreda @andrewvanbreda @BirenRathod @DavidRoy. Thank-you.

(Note: this code runs fine via DBeaver with my read-only permission, but I did have to remove the CREATE query and export manually)

**Comment by sacrevert** [comment]
Thanks Sam. A couple of specific things I was thinking about were (i) introduction of how training samples propagate to occurrences within them and (ii) specific flagging of null occurrences (not used much as we know). I'm not saying these are issues, they are just things that occur to me relating to vascular plant data in the BRC warehouse that might be worth checking here.

**Comment by japonicus** [comment]
Thanks for posting this.

The query already includes a zero_abundance column, but it would be good to check if 'training' samples need an explicit filter.

I think the export code was last revised in 2021 (but I wasn't necessarily fully on top of database changes since the query was first put together in 2019).

**Comment by kitenetter** [comment]
@Sam-Amy you may have done this already, but it would be worth comparing the BSBI query with "iRecord download format v2.sql", which is in:
`W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\Indicia\Warehouse SQL\iRecord download format`

That query produces an output very similar to the download that you get from iRecord itself, and is what I use to export data for some of the invertebrate schemes. In the same folder there are some explanatory notes form John: "Notes from John van Breda on optimising the download SQL 2021_04_16.docx".

**Comment by Sam-Amy** [comment]
Thanks @kitenetter, I've checked Jon's notes and that script, and can't see anything obvious, though they are in quite a different format.

I notice only records from iRecord, NPMS and CeDAR are included (iNaturalist is there as an option but currently excluded). @japonicus did you want to exclude iNaturalist data, and were other websites excluded on purpose (e.g. some other LERCS account for significant numbers of vascular plant records - I'll email with more details).

**Comment by johnvanbreda** [comment]
I've had a quick look at the query and it looks fine, a few minor things to point out:
1. integer and float custom attributes now have an option to allow ranges, so there is an allow_ranges flag in the attributes table, and an upper_value in the values table which provides the upper value of a range. For future-proofing the query should be updated to include the upper value in the output, but I don't think there are any data in the iRecord dataset affected by this.
2. The approach with nested queries might not be the fastest approach, but having said that rewriting it to try a different approach may take some effort without any guaranteed of improvements, so for an occasional data extraction I'd leave it as it is.
3. Being fussy - some of the tables are prefixed indicia. and some aren't. It's probably best to be consistent.

**Comment by kitenetter** [comment]
Hi @johnvanbreda is there a reason why the ranges get transformed to an upper_value for the output? I would normally expect to see the lower value (on the grounds that all a number range can tell us is that there were at least as many as the lower value).

**Comment by johnvanbreda** [comment]
Ranges aren't transformed to the upper value in the output, but both the original (lower) value and the upper value should be included if a value is a range. The logic is:
```
If the attribute for a value has allow_ranges=true 
    AND is a float or integer 
    AND the value upper_value field is populated, then
  output "value - upper_value"
else
  output "value"
```

**Comment by kitenetter** [comment]
Thanks @johnvanbreda that clarifies things. Do we need to consider the still open issue #1599 about using an en-dash rather than a hyphen for number ranges, to avoid misinterpretations in Excel?

**Comment by johnvanbreda** [comment]
In that it makes sense to be consistent, yes. I'm not sure if the vascular plant data will be opened in Excel, but it makes sense to assume that it might.

**Comment by japonicus** [comment]
I've attached a revised version of the export query that includes the allow_ranges flag and upper_value.
[vascular_plant_occurrences_modified.txt](https://github.com/user-attachments/files/15811189/vascular_plant_occurrences_modified.txt)

The list of permitted websites hasn't been modified yet, but based on @kitenetter's email comment it would be good to base this on all data-sets where sharing with BSBI was permitted, with the exception that I'd like to export NPMS and iNaturalist as separate batches if possible.

**Comment by kitenetter** [comment]
@Sam-Amy can this be closed yet?

**Comment by Sam-Amy** [comment]
Yes, sorry! The export has now been completed and passed to BSBI.
