### ISSUE TITLE
OS mapping availability

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#168]
OS backdrop mapping would be a desirable addition to all mapping windows, particularly in upland landscapes.

**Comment by kazlauskis** [comment]
Agree. Not sure if OpenLayers mapping library supports this, but alternatively this could be done with LeafletJS, like I've done for the iRecord App. Not sure how easy it is to switch to it though.

**Comment by sacrevert** [comment]
As I'm sure you know, Tom H has experience with this.

**Comment by johnvanbreda** [comment]
@kazlauskis Are you using OpenSpace for the iRecord app map? If so I think we can use OpenSpace in the same way (I assume this is OK with the licensing - would need to check), e.g. http://www.macfh.co.uk/JavaJive/ProgScriptWeb/UKOSOpenLayers.shtml.

**Comment by BirenRathod** [comment]
The below link has got more details about the licensing and API to use with OpenSpace.
https://www.ordnancesurvey.co.uk/business-and-government/licensing/licences/os-openspace-developer-agreement.html

**Comment by kazlauskis** [comment]
Yes, I use the OpenSpace service with [Leaflet OS plugin](https://github.com/rob-murray/os-leaflet)

**Comment by JimBacon** [comment]
Have you addressed the licensing question? There is the warning on the plugin page saying "The use of this project does not comply with the Ordnance Survey OpenSpace service terms and conditions." but perhaps our participation in the Public Sector Mapping Agreement means we are compliant.

**Comment by kazlauskis** [comment]
Yes, I have read most of the licensing and as far as I remember it does not indicate anything about not using their Javascript SDK.

**Comment by JimBacon** [comment]
Hmmm. Just been reading the OpenSpace agreement that Biren linked plus information on our intranet and I think my above comment is a bit muddly. 

Looks like the Public Sector Mapping Agreement only applies to internal use of map data and does not include the OpenSpace service any way.
See http://intranet.ceh.ac.uk/procedures/commercialisation/data-licensing-ipr/terms-of-use-for-os-datasets and related pages if internal to CEH.

Assuming that it is the OS OpenSpace agreement that is in place then we have obligations such as 
4.6.1 make a copy of the end user licence available
5.2 include an acknowledgement
5.3 include a logo
Furthermore, that agreement comes with a usage limit of 65k tiles per 24 hours per application.
It is not clear to me yet if a developer can register for additional API keys for different apps. Do you know, Karolis?

Having used the plugin, Karolis, can you explain how it is not compliant with the agreement?

**Comment by kazlauskis** [comment]
I should add a logo and a link to their license somewhere in the credits, which I will do with the next app update.

We only use one API key for all apps and as far as I know we haven't reached any limits yet.

> 4.8 You are not permitted (nor may You permit others), to register or use multiple API Keys across multiple Applications which in essence clone, duplicate or imitate the whole or part of each other. For the avoidance of doubt, Applications will be deemed to be cloned where in Ordnance Survey’s sole opinion there is no clear distinction between the website content and features.

**You can only have one API key and specify multiple domains (see screenshot)**

![screen shot 2017-02-21 at 20 06 18](https://cloud.githubusercontent.com/assets/7383162/23182846/e0a4ee66-f871-11e6-8497-e796d9e341b7.png)

**Comment by kazlauskis** [comment]
Maybe we could have one for CEH and one for BRC? 😆

**Comment by JimBacon** [comment]
4.7 says 

> You are not permitted to use more than one (1) API Key on any one Application.

My reading of 4.8 is that you cannot make clones of that app to try to get round this restriction.

However, I don't see anything saying you can't have multiple API keys where each key is for a different app, although you would have to register separately for each one.

**Comment by johnvanbreda** [comment]
I just tried using iRecord to add a record, following a typical pattern of using the map to zoom in a couple of times on a location, then counted the network requests to the Google tiles. There were 45. If my test is representative, then we get approx 1400 samples max per day within the license limit. Although if you look at iRecord data entered via the website alone I don't think we exceed that yet, we are sometimes close.

**Comment by kazlauskis** [comment]
We can add graceful degradation to satellite/OSM mapping if we encounter limits.

**Comment by JimBacon** [comment]
I'll contact our licensing team and see if we have any special terms for OpenSpace as part of our other licence agreements.

**Comment by JimBacon** [comment]
Note that https://www.ordnancesurvey.co.uk/forums/discussion/1010339/is-this-forum-active states 

> OpenSpace is still being supported by OS, but is not being actively developed. OS Maps API is the new offering by OS for slippy mapping, however does not currently have a free plan.

**Comment by JimBacon** [comment]
A licence for the latest OS API for web mapping is being ordered.
I think the initial order is for the entry level of 1.2 million transactions per year.

A transaction is “the display, in response to a request, of up to 15 Map Tiles”
I think there is a management console where we can track usage.

Being an annual subscription, I’m not sure what chance there is of it being renewed.
However, it is much more likely to be renewed if we use it.

I'll circulate more details when I get them.

**Comment by kitenetter** [comment]
OS maps now available on the iRecord website (need to be specified in the individual recording forms and reports). Closing.
