### ISSUE TITLE
Records missing from ES views

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1680]
I added about 50 records last night, at around 9-10pm, which are visible if I use the old (non-ES) My Records view, but they have not come through to the ES dataset.

Other new records by other people have appeared in the ES dataset this morning, so it doesn't appear to have got completely stuck, but I don't know whether the issue that has affected my records will also have affected other people. Can we run a check to ensure all records are being brought into the ES dataset?

**Comment by BirenRathod** [comment]
@kitenetter @robin-hutchinson reported of missing records of glow-worm. could be link to this.

**Comment by kitenetter** [comment]
And another user has reported "I submitted some records via iRecord Butterflies last night [Sunday night] but they haven't appeared yet on the iRecord database".

**Comment by robin-hutchinson** [comment]
It could be the same thanks Biren - copying from my email yesterday:

[35883256] is definitely in Indicia, but I looked and it isn’t on iRecord, the last record to appear on the iRecord explore records page was submitted 12/05/2024 19:17, with id number 35878714.

I looked for a record I submitted at about 11 this morning, which also is not appearing yet.

**Comment by robin-hutchinson** [comment]
We also have this in the forum: https://irecord.org.uk/forum/mobile-applications/app-records-missing

**Comment by robin-hutchinson** [comment]
Adding @Sam-Amy for info as we are getting some emails about this

**Comment by DavidRoy** [comment]
I've also had emails about this in the context of the ButterflyCount app.
@johnvanbreda - is the ES indexing catching up or is there a more fundamental problem?

**Comment by johnvanbreda** [comment]
It appears the PostgreSQL database went down around 2am on the 12th - there are errors like this in the log:
"02:04:22 error #2: Error in Rest API report request. pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: No route to host
Is the server running on host "192.171.199.243" and accepting
TCP/IP connections on port 5432? at line 48 in file /srv/sites/warehouse1.indicia.org.uk/system/libraries/drivers/Database/Pgsql.php"

As a result of this the flag which indicates the ES indexing is in progress got stuck on, so no new requests were being accepted. I've reset this so it should start to catch up slowly.

**Comment by kitenetter** [comment]
I added some records late last night and there are six that have not come through to the ES pages. Did the ES indexing get stuck last night or is this related to this morning's down time?

**Comment by BirenRathod** [comment]
@kitenetter ES could have been impacted due to the warehouse was down.

**Comment by kitenetter** [comment]
I ran the background process maintenance, and the records have now appeared in the ES view.

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/862c7295-c1dc-4c7e-839a-5c565112a1b4)

Closing.
