### ISSUE TITLE
Summary report not displaying correctly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1682]
Yesterday I set up the [report page for the 2024 butterfly app records](https://irecord.org.uk/butterfly-summary-2024), which I cloned from the 2023 report. The tables of species, recorders and vice-counties are all displaying correctly, but on the "Overview" tab the totals are missing, and on the "Trending" tab the word clouds for species and recorders have not been populated.

When I did this last year there was a similar problem (#1557) but it was fixed by refreshing the Indicia cache. That hasn't worked this time.

**Comment by johnvanbreda** [comment]
Fixed by clearing the Drupal cache.

**Comment by DavidHepper** [comment]
Sadly this hasn't fixed the similar #1601 but is this related?
