### ISSUE TITLE
Email expert error

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#1683]
Just had this notification appear when attempting to email a record to a local expert:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/5985134/6a094e89-ab66-462c-a4b8-f2a90c80172f)

Related to issues with Plant Portal @andrewvanbreda ? Already known @kitenetter ?

**Comment by andrewvanbreda** [comment]
@sacrevert
Am not sure if same issue as Plant Portal until solutions are found, could be related.

**Comment by kitenetter** [comment]
Tagging @johnvanbreda who is looking into alternative options for handling emails from our systems. I assume this is another example of the same issues that have arisen elsewhere (in which case we can close this issue).

**Comment by Sam-Amy** [comment]
I think this has been resolved, but @sacrevert if you get the error again perhaps you can re-open?
