### ISSUE TITLE
Question re dynamic attributes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1687]
On this form:
https://irecord.org.uk/enter-bird-record

the available species are restricted to birds, and it is currently using the default (non-dynamic) stage termlist.

However, it is not possible to lock the taxon name for adding multiple records of the same species, and I'm assuming that might be because of the way that our dynamic taxon forms work (whereby a taxon has to be entered each time in order to trigger the appropriate stage termlist).

How can I change this form so that it allows the taxon to be locked?

And having done that, is it possible to change the survey structure so that it uses occurrence attribute 872 ("Stage (birds)") instead of occurrence attribute 1092 ("Stage")? In other words, can attribute 872 only be used with dynamic forms, or can it be used in place of the default stages on a non-dynamic form?

**Comment by johnvanbreda** [comment]
I managed to use the lock on the species control fine - are you sure it is not working?

I've switched the stage attribute over - there is nothing special about the attribute itself related to being used in a dynamic way on the general dataset, so that's fine.

**Comment by kitenetter** [comment]
I'm sure it wasn't working (and RSPB also were when they raised the issue), but I agree it is working now! Don't really understand why this is, but hopefully all is well - closing.

**Comment by kitenetter** [comment]
Just heard back from RSPB that they are still unable to lock the species: "Just trying to enter skylark data but still not working when entering a locked species record."

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/5c08a684-41e4-447c-9502-4c0d19401662)

**Comment by kitenetter** [comment]
I've just tried again myself, using the form via the activity that RSPB are using, and the locking works. Will ask them to clear their cache.

**Comment by kitenetter** [comment]
RSPB say: "Just logged out of irecord, cleared all my browsing history & cookies then logged back in but still getting same issue."

**Comment by johnvanbreda** [comment]
@BirenRathod please can you deploy the latest master branch of iform (especially the media submodule) to the upstream, which will fix this issue. The Drupal cache will need to be cleared.

**Comment by BirenRathod** [comment]
@johnvanbreda  & @kitenetter The site has been updated with the latest iForm release.

**Comment by kitenetter** [comment]
@johnvanbreda RSPB are still reporting the same problem - not sure what else we can try.

**Comment by BirenRathod** [comment]
@kitenetter I have just cleared the cache. Can you ask them to check again, please?

**Comment by johnvanbreda** [comment]
When I tried yesterday, it didn't work until I did a proper page reload (Ctrl-F5, but depending on browser). Or clear browser cache. It looks like it still works OK for me.

**Comment by kitenetter** [comment]
@johnvanbreda RSPB report that they still cannot get the taxon field locking to work when using MS Edge, but it does work when they use Chrome. The locking is working for me within Edge so I don't know why it isn't for RSPB. Can't think of anything else to suggest so I'll leave this closed but let me know if it is worth any further investigation.
