### ISSUE TITLE
Subgneric names preventing successful name lookup

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#169]
For species that include subgenera as part of the species name, it is usually possible to call them up by typing in the name without the subgenus, but in a small number of cases this does not work. Example:

"Bombus (Pyrobombus) pratorum": cannot be found if typing in "Bombus pratorum"; typing "Bopra" or "Early Bumblebee" does find it. (Whereas you can type in "Bombus lapidarius" and be offered "Bombus (Melanobombus) lapidarius".)

Other similar examples that have been reported recently are:
- Vespula (Paravespula) vulgaris
- Bombus (Thoracobombus) pascuorum
- Agonum (Agonum) viduum
- Stenus (Stenus) boops
- Ischnopterapion (Chlorapion) virens
- Atractodes (Atractodes) bicolor
- Atractodes (Atractodes) gilvipes

This issue has only been reported in the last few weeks so far as I'm aware, but not sure if it dates back to the last UKSI update.

**Comment by kitenetter** [comment]
In relation to this Chris Raper has suggested that we:

> remove the bracketed subgenus as part of the UKSI import routine, to create a "display name" field - keeping the TVK the same. I have no problem with modifying a name string as long as that doesn't alter the taxonomic concept meaning of the name. For instance I would say that it is more important to show the author and attribute in the selection list than it is to show the subgenus.

**Comment by johnvanbreda** [comment]
I've spotted the error in a script which would have caused this a couple of weeks back - I'm fixing it now. Removing the subgenera is not necessary, though a different discussion is whether recorders (as opposed to taxonomists) want to see them at all.
