### ISSUE TITLE
Unable to edit an existing activity

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1691]
I wanted to edit some text in the description of an activity, but when I click the save button I'm getting as error: "The data could not be saved."

Have tried editing different things and on two different activities but each time the same error appears.

**Comment by johnvanbreda** [comment]
Have fixed this in the code, but can't log into the cloud for some reason to apply it. Will try again tomorrow.

**Comment by johnvanbreda** [comment]
Now fixed.
