### ISSUE TITLE
Images being cropped to square in some cases

### ISSUE THREAD

**Issue by cubitmg** [BiologicalRecordsCentre/iRecord#1694]
Several, but not all, images appear to be getting cropped to square. I have not spotted a pattern about when it happens and have not managed to reproduce.

The square cropping is used for the main verification screens, and in most cases clicking on the image shows the uncropped version. However, some records the original image is not available often with parts of the moth (in my case) missing making verification quite a challenge.

Here are two examples:
https://irecord.org.uk/record-details?occurrence_id=36747611
https://irecord.org.uk/record-details?occurrence_id=36391463

**Comment by johnvanbreda** [comment]
Do we have any evidence that the cropping was not done on the phone before upload? It would seem odd that the system would crop some images and not others.

**Comment by cubitmg** [comment]
This was one of the uploaded files:
![IMG_0074](https://github.com/BiologicalRecordsCentre/iRecord/assets/65334323/961947bb-f5fc-4d8b-a43f-4fbe9ba59232)

**Comment by kitenetter** [comment]
@cubitmg both those examples are records added via the iRecord app. The app does enforce 1 x 1 proportions for photos, so if someone tries to upload a photo that was very closely cropped in wider format the app will cut off part of the image. I don't think we have any options for altering this behaviour.

**Comment by cubitmg** [comment]
OK, useful to know, but the app should not do that and should be changed IMO. However, it isn't one for this forum. Can it be moved to the app forum?

**Comment by kitenetter** [comment]
Have added a feature request to the app issues (but don't yet know if this is feasible). Closing this one.
