### ISSUE TITLE
Importer v2: switching between fields for mapping gets stuck

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1705]
I started an import process, and for testing purposes chose "DRN dragonfly imports" as the survey. As expected, when I arrived at the field mapping page, the choice between "standard fields" and "standard and advanced fields" was greyed out, as this is not implemented for anything other than the "iRecord Import" survey.

However, I then abandoned that import, went back to the start of the process, imported a file, and set it to import into "iRecord Import". When I arrive at the field mapping page, the choice between "standard fields" and "standard and advanced fields" was still greyed out.

Can we enable this functionality to refresh when a new import is started?

**Comment by kitenetter** [comment]
I was testing this in Chrome. Have just cleared cache and cookies and logged back in to iRecord, but the the choice between "standard fields" and "standard and advanced fields" is still greyed out.

**Comment by johnvanbreda** [comment]
The option will get greyed out if any of the fields that have been automatically mapped to your spreadsheet are advanced ones, since changing the option would remove fields that are in use. Does that explain the issue?

**Comment by kitenetter** [comment]
@johnvanbreda yes it probably does (I had added some 'advanced' fields to a previously imported 'standard' spreadsheet as part of my testing). I'm not convinced that this is the ideal solution, but I can see there are pros and cons and I'm not inclined to suggest a change at the moment. But at least I can now explain it on the Help page! Closing.
