### ISSUE TITLE
Can we improve the indentation of the Source filter options?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1708]
The wrapping of the list elements when selecting filter by Source(s) is confusing. Could the wrapping be improved from: 

![image](https://github.com/user-attachments/assets/8d17e5d7-a58b-4370-b0c2-53eef79d7155)

to something that behaves like a normal bullet list: 

![image](https://github.com/user-attachments/assets/c19ee0c6-fa15-4f51-a226-1eed093c6c32)

please?

**Comment by johnvanbreda** [comment]
Agreed - changes done in the develop branch ready for the next full update.

**Comment by DavidHepper** [comment]
(This one's closed but the fix isn't live for me yet on Firefox.)

**Comment by johnvanbreda** [comment]
Sorry - that was automated. The code is in the live branch now, but as there are quite a few changes I've set it up only on a test server for Martin to check.
