### ISSUE TITLE
Log-in prompt for recording forms

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#171]
In many cases, if people arrive at an iRecord recording form when they are not logged in, they are able to add a record by giving their name and email at the point of data entry. But as far as I can see there is no obvious/easy way of logging in from the recording forms.

Would it be possible to add some standard text to the top of recording forms so that when an unlogged-in user goes to them they see something like:
> You are welcome to add records to iRecord without logging in, but if you do log in first you will be able to retrieve your records at a later stage, and to build up your list of records over time. Click here to _log in to an existing account_, or here to _set up a new account_.

**Comment by DavidRoy** [comment]
Agreed.  @kitenetter  - can you do this for the standard forms?

**Comment by johnvanbreda** [comment]
If you do this by editing content, it will be visible for all users when logged in as well, so I would do this by creating a block. The block could contain text explaining why iRecord is better when logged in with a link to the login and register forms. These could be displayed in a popup e.g. using https://www.drupal.org/project/modal_forms. We would then configure the block to only appear when logged out and to not appear on the home page or other pages where it is not deemed relevant.

**Comment by JimBacon** [comment]
An alternative is demonstrated by http://www.brc.ac.uk/irecord/external/enter-grasshopper-records.

This adds some text to the About You section of the form structure which is only presented to users who are not logged in. I think this is simpler although it does require an edit to every form where it is needed. The destination in the links also has to be adjusted to ensure that, after login/registration, you return to the correct form.

This method is also forwards compatible whereas modal_forms is not being ported to Drupal 8 at present.
```

=About you=
?This record is being submitted to <a href="http://www.brc.ac.uk/irecord/" target="_top"><strong>iRecord</strong></a>. If you have an iRecord account, please <a href="http://www.brc.ac.uk/irecord/user/login?destination=external/enter-grasshopper-records"><strong>log in</strong></a> so that this sighting appears in your records. If you are not already registered with iRecord we highly recommend to <a href="http://www.brc.ac.uk/irecord/user/register?destination=external/enter-grasshopper-records"><strong>register</strong></a> so that you can view your previous records and use all the site’s facilities. However, you can continue without registering by providing your details below. We ask for these in case we need to contact you when verifying your sighting. They will not be used for any other purpose.?
[*]
@smpAttr:36|helpText=Please provide your first name
@smpAttr:36|class=control-width-5
@smpAttr:58|helpText=Please provide your surname
@smpAttr:58|class=control-width-5
@smpAttr:8|helpText=Please provide your email. This will only be used to contact you if we require further information to verify the record.
@smpAttr:8|class=control-width-5
```

**Comment by kitenetter** [comment]
Thanks @JimBacon - I've got that working for the glow-worms and will add to the other forms.
