### ISSUE TITLE
Alderney (Channel Islands) lat-lon being translated unreliably to BNG

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1711]
Records from St Anne, Alderney via BTO are inappropriately being translated to GB grid refs - in unpredictable ways. 
(They're then being inadvertantly accepted as GB records.) Here's a selection: 
[Sheelagh Halsey's peripatetic Alderney records.xlsx](https://github.com/user-attachments/files/16557480/Sheelagh.Halsey.s.peripatetic.Alderney.records.xlsx)

Does this affect other Channel Islands records, none of which are on BNG?

**Comment by johnvanbreda** [comment]
I have applied a fix for this for incoming data - will just see if I can apply a similar fix for already loaded data.

**Comment by johnvanbreda** [comment]
Now fixed for existing records too (there were 10 in all).

**Comment by DavidHepper** [comment]
Thank you. Some record details haven't been updated (e.g. 30739340 still says 'Midlothian' and 'The Wildlife Information Centre') but maybe this happens later.
The verification status isn't changed from e.g. Accepted (by our Scotland CDR) but I think the Alderney will get the idea.
