### ISSUE TITLE
Record cleaner checks are stuck?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1717]
For Berkshire moths at least, no record cleaner checks have been applied to records added after 16:48 on 15 August 2024.

**Comment by johnvanbreda** [comment]
I've unblocked some spatial indexing tasks in the work queue, using the button at the top of this page: https://warehouse1.indicia.org.uk/index.php/diagnostics. I also noticed a record from the iRecord app for Coeloglossum viride which was using a deleted version of the taxon, so presumably an old copy of the app, that was causing issues so fixed this. Hopefully things will return to normal over the afternoon.
