### ISSUE TITLE
Changing species record total

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1718]
Reported by a user (81636):

If they look at the "My records" tab and scroll down, it looks like Ulopa reticulata has 4 records:

![image](https://github.com/user-attachments/assets/33a39f38-7035-4653-b0d0-7009f135ea26)

If you type "Ulopa" into the accepted name text box instead, it now shows 6 records:

![image](https://github.com/user-attachments/assets/325990de-6616-4cd6-bcbe-94145f52894b)

Looking at the records tab, there should be 6 records. I'm not sure what is happening here?

**Comment by kitenetter** [comment]
It appears that the table under the "Species" tab is inconsistently inconsistent. This isn't just affecting Ulopa reticulatus, the majority of species I've tried so far comes up with a different (and more correct) total if I filter for that one species, compared to the lower (incorrect) total shown when the table is not filtered. But not all - some species have the same correct total whether filtered or not.

@johnvanbreda is this another unhelpful feature of the ES grouping? Is there likely to be a solution?

**Comment by johnvanbreda** [comment]
@kitenetter that's my working theory at the moment. But, my efforts to reproduce this by directly querying ES have failed, so I'm trying to capture the exact request being generated when that user loads the Species tab. Unfortunately my cloud connection has just died so I'll have to wait for support assistance.

**Comment by johnvanbreda** [comment]
Here's an explanation of why this happens: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-shard-size

I've committed code that will allow the shard size to be increased to 500 (it was currently 85 - the default for a 50 row table) which fixes the specific issue. Some variations may still occur but they should be far less frequent and the difference is likely to be smaller. The change will be applied next time I do a full code update.

**Comment by robin-hutchinson** [comment]
Thank you! I'll let the user know
