### ISSUE TITLE
Activity failing to display properly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#172]
This is a long-running problem that started with an activity called "Moelyci Wildlife", group_id=574. This activity was originally set up with quite a complex set of overlapping site boundaries from the "My Sites" of the user who created it. It has been failing to display records correctly for some months, and for much of that time has been defaulting to a view of records in Anglesey, which is not the county for the sites in question.

On the assumption that activity 574 must have got corrupted I recreated it today, calling it "Moelyci Wildlife 2", group_id=927. At first I used two non-overlapping polygons, and then I tried to simplify it to one polygon (not sure if that succeeded, it's not easy to see whether a previously applied sites filter has been cleared or not).

But it is still failing to display correctly. If I go to the explore records page for this activity (http://www.brc.ac.uk/irecord/activities/explore?group_id=927&implicit=) it shows a zoomed out map, with a blue dot in the correct location, but it shows no records as being available. If you zoom in, the record squares appear correctly, but still no records show in the grid unless you use the 'question-mark' map tool button to actually select the relevant squares. The site boundary itself does not display at all.

![image](https://cloud.githubusercontent.com/assets/16039111/23371024/91127d90-fd0e-11e6-8051-997982722601.png)

**Comment by johnvanbreda** [comment]
Fixed by https://github.com/Indicia-Team/client_helpers/commit/14a8ed37aa0cb853487cf71f345d2164a4a002fd
