### ISSUE TITLE
NBN exports still contain incorrect licences

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1723]
@johnvanbreda earlier this year we discussed how best to exclude the record licences that cannot be used by NBN:
- "CC BY-SA"
- "CC BY-ND"
- "CC BY-NC-SA"
- "CC BY-NC-ND"
- "ARR"

I can see that this exclusion has been coded into the NBN export config files, but unfortunately it isn't working - the csv files still contain records with the above licences.

**Comment by johnvanbreda** [comment]
Fixed - needed to filter on metadata.licence_code.keyword (with the .keyword qualifier). All export configurations have been fixed.
