### ISSUE TITLE
Potential enhancement to Activity species lists

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1725]
New feature request growing out of #1657 

Add a new species summary page for activites, and link to the main iRecord species summary - possible visualisation:
[Activity enhancement_species links.pdf](https://github.com/user-attachments/files/16762707/Activity.enhancement_species.links.pdf)

**Comment by johnvanbreda** [comment]
When #1657 is deployed, I can clone the existing page, change the map to an Explore map (so it shows the activity boundary) and configure the Group Landing Pages with the page path.

**Comment by johnvanbreda** [comment]
Done - e.g. https://irecord.org.uk/activities/species-details?taxon_meaning_id=93336&group_id=45&implicit=
