### ISSUE TITLE
Images of wrong taxa on species details page for Ludwigia peploides

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1727]
[https://irecord.org.uk/species-details?taxon_meaning_id=117824](https://irecord.org.uk/species-details?taxon_meaning_id=117824)

Note this species doesn't show on the explore page, I guess because it is an INNS (is that right @StephRorke ?), though I can see there is one unverified record with a verification filter for all species. Hence there should probably be no photos shown on the species details page (clicked to from that unverified record) though it is actually displaying photos of Didemnum vexillum (sea vomit).

**Comment by sacrevert** [comment]
All the details are wrong here by the look of it (map, annual and monthly temporal distributions). Presumably there is some database join gone awry here or something @johnvanbreda ?

Not really sure what is going on here taxonomically either, as the warehouse UI has some odd results. For example, two versons of L. grand. hexa. but no valid instance of L. peploides:
https://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-taxa_taxon_list_id=239388

And then L. peploides synonimised with one of these L. grand. hexa. instances:
https://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-taxa_taxon_list_id=604854

UKSI has this confusion too, which may explain some of the indicia problems, e.g. https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0020979164

I don't understand why this is wrong post BSBI-reconciliation, as seems right in DDb. @japonicus, any thoughts?

**Comment by japonicus** [comment]
The BSBI-UKSI reconciliation hasn't gone through yet, we're still waiting for Chris to assimilate the changes. Hopefully that should fix problems of this sort.

**Comment by sacrevert** [comment]
Thanks @japonicus, sorry, didn't appreciate that. If @johnvanbreda thinks that this will be solved by sorting the taxonomy, then I suppose this could be closed

**Comment by japonicus** [comment]
I'd missed Sam's initial post, I don't think the UKSI synonymy problems account for the mismatched iRecord images - something else odd is going on apart from the UKSI confusion.

**Comment by johnvanbreda** [comment]
The problem here (as well as any taxonomic issues) is that the taxon_meaning_id parameter points to a taxon on the GBNSSIP Non-natives list and this list does not have any taxon version keys for the names. The system relies on the taxon version key to map across lists to find the record to include, but mistakenly includes all records when the taxon version key is empty. So there is indeed a bug here as the page should really show no records - though in order to work correctly the GBNNSIP list really ought to have TVKs added where possible.

**Comment by burkmarr** [comment]
I've updated the species_details_2 prebuilt form to prevent data retrieval when no external key can be identified. A message is displayed to the user where that occurs. It's implemented on iRecord live site and in the develop branch of client_helpers.

**Comment by sacrevert** [comment]
The page that generated this no longer displays any photos (I assume this is correct?)
@burkmarr Can this be closed?
