### ISSUE TITLE
CC0 vs CCO

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1728]
A picky point that may possibly also explain #1589.

The [Creative Commons Public Domain Dedication licence type](https://creativecommons.org/publicdomain/zero/1.0/) is 'CC Zero' = CC0.

The Quality filter dialog shows this as CC oh = CCO 
![image](https://github.com/user-attachments/assets/9a646a5c-8333-49f2-8563-27f57889ca85)

Is the correct string being tested for under the surface?

**Comment by johnvanbreda** [comment]
@DavidHepper - good spot, it's just a typo though so I'll fix that in the next code release.
