### ISSUE TITLE
iRecord Butterflies - user statistics page is showing a 500 error

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1730]
The statistic report page is failing on the iRecord Butterflies app: https://github.com/NERC-CEH/irecord-butterflies-app/issues/180

Could you have a look from the website side to see what might be causing this, please?

**Comment by BirenRathod** [comment]
@robin-hutchinson See my comment here -> https://github.com/NERC-CEH/irecord-butterflies-app/issues/180

**Comment by robin-hutchinson** [comment]
Thanks!

**Comment by BirenRathod** [comment]
@johnvanbreda Can you suggest anything? The error comes from indicia_advanced_report module. See the error posted in -> https://github.com/NERC-CEH/irecord-butterflies-app/issues/180

Somehow ES failed to run the report using taxon filter.

**Comment by johnvanbreda** [comment]
Hi @BirenRathod - I had started to upload a fix but I see you have tried to implement a fix as well. Can you rollback your commit please as it breaks the fix already in the queue to go onto live iREcord - see https://dashboard.pantheon.io/sites/120420b2-2705-4ad9-8201-0f1bb320bc3f#live/deploys.

**Comment by BirenRathod** [comment]
@johnvanbreda I realised that so I already reverted back my changes.

**Comment by johnvanbreda** [comment]
Thanks @BirenRathod, I'll deploy the changes now then.

**Comment by BirenRathod** [comment]
@johnvanbreda just hold for a minute, please.

**Comment by BirenRathod** [comment]
@johnvanbreda All done. Thanks.

**Comment by BirenRathod** [comment]
Thanks, again @johnvanbreda. @robin-hutchinson This has been resolved now so please check.

**Comment by robin-hutchinson** [comment]
All sorted, thank you!
