### ISSUE TITLE
Old version of importer no longer available?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1731]
@johnvanbreda following the code update you mentioned in your email the [old version of the importer](https://irecord.org.uk/import-old) is no longer working (error "Please check that the indicia_svc_import module is enabled on the Warehouse").

Is it possible to keep both versions running without disproportionate effort, or should we now remove the old version?

**Comment by johnvanbreda** [comment]
The Excel import library was upgraded as a result of security checks, it broke the old importer but I've just released a fix.
