### ISSUE TITLE
NBN exports containing records that should have been filtered out

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1732]
A query over a record on NBN Atlas has led to anomalies being found in the way that records are being filtered.

So far I have only looked at the records we send using the [NBN - Coleoptera non-scheme](https://irecord.org.uk/filters/admin-edit?filters_user_id=7421) filter. That filter is set up to exclude records that are rejected or queried.

However, the file that is being generated for NBN Atlas contains a number of records that have been either rejected or queried. For example, record IDs 37785085 and 10448895 are both marked as rejected. The data file that is generated for NBN Atlas includes these records, and the "identificationVerificationStatus" attribute is empty.

ID 978661 had been queried (I have now rejected it) but was also being included, although I suspect this was a legacy problem from the Garden Bioblitz data in 2014.

If I download the data using the same "NBN - Coleoptera non-scheme" dataflow filter the rejected records do not get included (although a couple of the 2014 Garden Bioblitz queried records are included). So it seems that the NBN Atlas export procedure is somehow over-riding the exclusions that are set up in the dataflow filter.

Marking as urgent because this issue was highlighted by a potentially serious record of an invasive species being shared when it had in fact been rejected.

Possibly relates to #1723

**Comment by johnvanbreda** [comment]
@BirenRathod I have updated the code in https://github.com/Indicia-Team/support_files/blob/master/Dwc%20Exporter/dwc-generate.php to handle the new format Quality filter, which is the problem here. Please can you update it so that @kitenetter can test if the files it generates are fixed?

**Comment by BirenRathod** [comment]
@johnvanbreda  & @kitenetter I have updated the dwc-generate.php file on the NBN export VM.

**Comment by kitenetter** [comment]
Just tried to run the .sh files to test this, and I'm getting an error message for each file - example:
`-Starting extraction
Config file "config/FILTER NBN - Auchenorrhyncha.json" loaded
PHP Fatal error:  Uncaught Exception: Duplicate index 0 in meta.xml list of fields. in /home/nbn_data/ipt-dev/dwc-generate.php:284
Stack trace:
#0 /home/nbn_data/ipt-dev/dwc-generate.php(239): BuildDwcHelper->getFileMetadataFromXml()
#1 /home/nbn_data/ipt-dev/dwc-generate.php(423): BuildDwcHelper->loadMetafile()
#2 /home/nbn_data/ipt-dev/dwc-generate.php(1613): BuildDwcHelper->buildFiles()
#3 {main}
  thrown in /home/nbn_data/ipt-dev/dwc-generate.php on line 284
Script is running
`

**Comment by johnvanbreda** [comment]
This is due to the new exporter code being a bit stricter about the configuration - the meta.xml file we used which lists all the fields had a duplication of the id and occurrenceID field outputs (which are the same thing). I have fixed the first 2 in the list (aculeate Hymenoptera and amphibians and reptiles) but cannot test that the change worked as my account doesn't have permission to run the script. Please can you try one of these and let me know if it worked?

**Comment by BirenRathod** [comment]
Not sure @kitenetter can test that, but let me know if you can't and I can do it for you.

**Comment by kitenetter** [comment]
@johnvanbreda I've successfully generated a file for amphibians and reptiles, so the change to the meta.xml seems to have worked thanks.

However, it still includes records with non-usable licences, so we haven't yet resolved #1723

**Comment by johnvanbreda** [comment]
All the meta.xml files are now fixed (along with #1723).

**Comment by kitenetter** [comment]
Thanks @johnvanbreda I've tested a couple of export files and can confirm that they do not include incorrect licences, and they do not include rejected records.

One other issue has come to light: a few records from 2014 have ended up with no verification status at all, i.e. not even unconfirmed/pending. That's not urgent and I'll raise it as a separate issue.

**Comment by kitenetter** [comment]
@johnvanbreda all the files have generated successfully except for the soldierflies and allies - I'll try not to take it personally! That's the only one that is still producing a "Duplicate index 0 in meta.xml list of fields" error message. If it's easy to fix on Friday morning I can include it in this month's upload, but no problem if it has to wait till next month.

**Comment by johnvanbreda** [comment]
Hi @kitenetter - sorry, missed that one. Should now be sorted.
