### ISSUE TITLE
Problems during registration process

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#1739]
I know what problem is as I have seen this on other projects.

**Comment by andrewvanbreda** [comment]
Problem is a bug is the User Registration Password module that is known, but the module creator has not deployed the fix yet.
https://www.drupal.org/project/user_registrationpassword/issues/3467248

Issue seen on other projects NPMS/EBMS/Plant Portal and fix has been seen working on those projects

The fix I included is the simple
$output = $mail['result'] ?? FALSE;
change to
$output = $mail ?? FALSE;

@BirenRathod @johnvanbreda 
I have committed a bug-fixed version of the module to the Custom modules folder.
However as I am not main developer on iRecord, I have not deployed to live, I have only committed the change to Dev.
Deploy yourself, or if you want to, you can instruct me to deploy it to live.

**Comment by johnvanbreda** [comment]
@BirenRathod are you OK to deploy this?

**Comment by BirenRathod** [comment]
@johnvanbreda this has updated on iRecord now.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 

The original error has now gone away.

However I am still seeing issues with the registration process.

1. When registering, once I fill in the details, I always get the following message,

"Unable to send email. Contact the site administrator if the problem persists."

This is in addition to a message confirming registration instructions were sent to you,. Actually the registration mails DO arrive at your account.
There is nothing obvious in the logs where the email message is displayed to the user.

2. Another slight oddity about the registration process is the user seems to receive 2 emails.
One says that the account is pending approval, and the other is an email allowing you to activate the account yourself with a one-time link.
This doesn't really make sense,
It is a bit like saying, please wait while we approve your account, actually do it yourself.

I cannot be 100% sure the multiple emails don't relate at all to my above fix, however the message about the email not being sent still occurs on a multidev I created where I uninstalled User Registration Password and User Registration Password REST modules.
Unfortunately I can't test the multiple emails problem when User Password Registration is not installed, because the multidev site doesn't seem to send any emails at all, so I can't experiment.
Just to note, EBMS doesn't have either issue even though that site received the same update from myself.

Biren are you able to look into this please? (or assign someone else to if you can't), as actually I have no timesheet to work on iRecord, I essentially did the User Registration Password fix as a favour because I was doing the other sites.

**Comment by andrewvanbreda** [comment]
Forgot to attach pictures of the emails, I suppose this issue is relatively minor, but the one about the email not being sent is definitely something we don't want users to see.

<img width="630" alt="Screenshot 2024-10-22 at 08 48 38" src="https://github.com/user-attachments/assets/3b4ed45d-568c-4ab8-af81-60f9dabaf817">

<img width="626" alt="Screenshot 2024-10-22 at 08 48 51" src="https://github.com/user-attachments/assets/000055b2-6465-41a0-a23a-7cd835593bbc">

**Comment by BirenRathod** [comment]
Thanks, @andrewvanbreda.

Can I check one thing with you? did you test this on live site?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yes it was tested on live and it gives the message about email not being sent and I received the 2 emails.

It is better than it was before, where I would get "website ecountered an error" white screen upon registration.

**Comment by BirenRathod** [comment]
@andrewvanbreda & @johnvanbreda This has been implemented now. if you are happy , please close this issue.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Good work, both issues have indeed been fixed.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Sorry I have just noticed a problem.
The original 2 issues are indeed fixed.
When I clicked on the one-time link to activate my account everything seemed fine so I closed this issue, however I just returned to my email box and iRecord has sent a second email a minute later.
The email subject is the same as the other email
"Account details for Andrew van Breda NA140 at iRecord"
however the contents of the email are completely blank, it literally says nothing at all in the email body.

<img width="1107" alt="Screenshot 2024-10-23 at 16 24 17" src="https://github.com/user-attachments/assets/d3b4badc-17ca-496e-b0b5-b9749ce556d6">

**Comment by BirenRathod** [comment]
@andrewvanbreda it needs to add account activation policy to resolve that.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
OK, iRecord isn't one of my sites so I don't change its configuration.
Could you make the change please, and then I will retest it.

**Comment by BirenRathod** [comment]
@andrewvanbreda Done. you can test now.

**Comment by BirenRathod** [comment]
@andrewvanbreda it hasn't yet resolved. I'm testing it and let you know once resolved.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
I just noticed one other thing, the registration email from iRecord is quite confusing, on NPMS it is much clearer. For instance iRecord says "log in" as an active link twice, but actually they do totally different things.
I will leave it up to you if you want to change it to be more like NPMS, so I won't consider it part of closing this issue

<img width="545" alt="Screenshot 2024-10-23 at 16 46 02" src="https://github.com/user-attachments/assets/ebce01f4-01f8-4707-af67-0e448b36b035">

<img width="507" alt="Screenshot 2024-10-23 at 16 46 20" src="https://github.com/user-attachments/assets/c20ed811-46b9-4a35-8ffe-928f7c71966f">

**Comment by BirenRathod** [comment]
@andrewvanbreda This has now resolved. iRecord delivers two emails but that is fine as both have got different instructions in it. 

Thanks about NPMS email details. I eventually find the original iRecord email which I implemented now. It is more over similar to NPMS one.

@kitenetter are you happy with the details in the emails when new user register?

**Comment by kitenetter** [comment]
@BirenRathod do you have any examples of the emails currently being sent, or do I need to go through the process of registering a new email to see what happens?

**Comment by andrewvanbreda** [comment]
@kitenetter I can get you email screenshots if you give me a few minutes

**Comment by BirenRathod** [comment]
Thanks @andrewvanbreda.

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter 
I have attached email screenshots below.

Here are my own opinions on situation now.
I now receive 3 emails.
The first 2 come together.
The third is the activation email that was previously blank.

Two of the emails are now fine (pending Martin's view on them). In my opinion the text in the main email is now far less confusing because the user can no longer accidently miss the one-time activation link.
The activation email is also no longer blank which is good.

However I would suggest adjusting the wording of the other email

Subject: Account details for Andrew van Breda NA140 at iRecord (pending admin approval)

"Andrew van Breda NA140,

Thank you for registering at iRecord. Your application for an account is currently pending approval. Once it has been approved, you will receive another email containing information about how to log in, set your password, and other details."

There are 2 problems I can see here.
A.
In the subject it says the account is awaiting admin approval, this is actually not true, the activation is done by the user.

B.
Actually once approved (activated) the user doesn't receive any email about setting passwords etc, they just get one saying the account is activated. The password setting is done prior to all of this on the registration form.

Main email

<img width="460" alt="Screenshot 2024-10-24 at 09 51 49" src="https://github.com/user-attachments/assets/63c37d1a-ea54-422f-90ae-867efaa5e35b">

Second email sent at same time

<img width="442" alt="Screenshot 2024-10-24 at 09 51 37" src="https://github.com/user-attachments/assets/a9991ed9-c8c9-4ab5-bf29-3431651cf0da">

Email that is sent after activation

<img width="453" alt="Screenshot 2024-10-24 at 09 51 54" src="https://github.com/user-attachments/assets/7e49d491-f433-4b99-b4ba-34bebf14345a">

**Comment by BirenRathod** [comment]
@andrewvanbreda The second issue is not actually an issue as there is no activation required. The account activation process is only required when the account left blocked for sometime. So the email content is right.

for first issue, I removed the pending admin approval from the subject line and amended the content slightly.

**Comment by BirenRathod** [comment]
@andrewvanbreda Also, email sequences are like below ...
First to receive this ....
![image](https://github.com/user-attachments/assets/eaf5c285-4648-4cc2-b611-843f5b42721a)

Second to receive this ...
![image](https://github.com/user-attachments/assets/955f6e03-0527-4b6a-bd0a-2ffd4cc7ba4b)

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter 
Thanks Biren,

For simplicity, I have included the latest version all 3 emails below for Martin to check. The activation and pending approval texts have been changed since my message above and I think are mostly OK now.

I didn't quite understand what you meant about the account activation process not being required, as the account is blocked as soon as someone signs up until they activate it.......but anyway, that doesn't matter, I think it is ok now, subject to martin's thoughts on wording.

I suppose the only slight oddity is the activation email says the user should got to a page to set their password, when it is already set on the registration form before then, but I will let Martin decide on this. I am ok to close once Martin is happy.

<img width="456" alt="Screenshot 2024-10-24 at 10 41 17" src="https://github.com/user-attachments/assets/380d0bbb-dcb1-4c0d-94bc-97482e6c5215">


<img width="455" alt="Screenshot 2024-10-24 at 10 41 36" src="https://github.com/user-attachments/assets/b35262e3-212a-403d-9102-037857c50214">

<img width="455" alt="Screenshot 2024-10-24 at 10 41 53" src="https://github.com/user-attachments/assets/6748dfac-9413-4b62-bfa1-aacf43f538e2">

**Comment by BirenRathod** [comment]
Thanks, @andrewvanbreda once again.
@andrewvanbreda about activation email ...

As the email content says, the activation email deliver when somebody block & reactivate the account or account been remained block for sometime and reactivate them.

**Comment by kitenetter** [comment]
Thanks - I'm testing the process again, and will get back to you.

**Comment by kitenetter** [comment]
I've now gone through the process myself and captured some additional screenshots:
[iRecord registration process.pdf](https://github.com/user-attachments/files/17505439/iRecord.registration.process.pdf)

From the user's perspective, the first and third emails are unhelpful. It is only the second email that contains an action the user has to carry out. 

The first email that arrives is easy enough to ignore, and is followed immediately by the second, so that is all fine. But the third email, with the apparent request to set another password, is very unhelpful.

I realise that we have to cater for the situation where an account has been blocked for some time, but as things stand the process for normal users is more onerous than I have experienced when registering on other websites. The apparent requirement to reset the password for a second time is very frustrating, given how most users find password management hard enough at the best of times.

Do we have any options that would avoid us asking for the second password?

**Comment by BirenRathod** [comment]
@kitenetter Did you receive the third email after the account activated? if that is the case , I will remove the password information.

**Comment by kitenetter** [comment]
@BirenRathod yes, the third email was sent after I'd had activated the account from the second email, and had seen this message displayed:
![image](https://github.com/user-attachments/assets/44369d4d-f70c-4568-bee3-d4772cfa872f)

**Comment by BirenRathod** [comment]
@kitenetter I got it. I have removed the password lines from the third email. Let me know if anything needed to amend.

@andrewvanbreda sorry for my earlier comment. I didn't realise that the website sends the third email after the account being activated.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
No problem.
Feel free to close the issue once Martin is happy with the process.

**Comment by kitenetter** [comment]
Thanks both, it sounds like we have arrived at an improved sequence. I'll do another test at some point but it sounds fine for now - closing.
