### ISSUE TITLE
Data downloads from Activities

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#174]
Question for @johnvanbreda 

My understanding was that we had set things so that an Admin for an Activity could download ALL records that fall within that Activity's filters, AS LONG AS the records had been explicitly assigned to the Activity (i.e. by using the Activity's recording form, or by joining an Activity via the app).

However, I've just been testing this for John Bratton's "Moelyci Wildlife" Activity, and it appears that John is not able to download records that were entered by other users, even if they were explicitly added via the Activity recording form.

Am I misunderstanding what John should be able to do? Or is there a setting that needs to be in place to allow download? (On his current download page the only option he has is to download "My records contributed to Moelyci Wildlife", should an "All records contributed ..." also appear?).

**Comment by johnvanbreda** [comment]
Now done - you can select this under Download type if you are admin of an activity.

**Comment by kitenetter** [comment]
The download options include both current and expired activities. This is probably a good thing, but because users are currently unable to delete activities we have ended up with activities being created, then expired, then created again under the same name. From the download dropdown options there is no way of distinguishing between current and expired activities.

Possible solutions:
- Allow users to delete their activities - see #211 
- Add a flag to the dropdown list to show which ones are expired

**Comment by johnvanbreda** [comment]
I've added code to include a suffix (finished) in the list on the download when the activity has expired. This will be deployed next time we do a feature code release.
