### ISSUE TITLE
Some records from 2014 have no verification status

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1740]
A very small proportion of the records we send to NBN have no verification status at all, i.e. they are not labelled as unconfirmed/pending, and thus do not show up to verifiers in their pending lists on the verification page. Which means these records are in limbo.

Quite a lot of them originate from "iRecord | Garden BioBlitz 2014", but there are also a few examples from other sources including "iRecord | General data", "GIGL | Royal Parks Survey", "NNSS | RISC ARC". All that I have found so far are from year 2014.

Examples of such records:

Weevil dataset
969391
975511
1008375
980154
973247

Amphibian/reptile dataset
851945
1534830
928787
1088484
1023451

I assume what's needed is a database update to find all records that are not linked to any status and set them to "unconfirmed".

**Comment by johnvanbreda** [comment]
These are all records which have been marked as "dubious" - a state we used in similar fashion to a query before the verification statuses got reviewed. As the queries will all be old, I'd agree that the best solution is to simply reset all dubious records to pending verification - please can you confirm this is what you'd like done? FYI - there are 3403 records in this state.

**Comment by kitenetter** [comment]
I think if the records were previously considered dubious then we should mark them as "Not accepted - unable to verify", as the chances of getting responses to queries so long after the event will be low. That can be done as soon as you get a chance, but could you also send me a list of the affected record IDs and I'll do a quick check to see if any particular records would be worth following up.

**Comment by johnvanbreda** [comment]
I've sent you the records via email.

**Comment by johnvanbreda** [comment]
I've updated the records from 'D' to R4 (not accepted as unable to verify) apart from for BRERC.
