### ISSUE TITLE
Notification settings not being saved

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1742]
On the user account page, people can set their preferences for how frequently they wish to receive notifications. 

However, if you try to change any of the settings to "Never", this not being saved. It is possible to change to other options such as "Weekly" and the changes are being saved, but setting to "Never" fails to be saved. This is the same if applied to the overall choice for all notifications, or for individual notifications under the "Advanced" settings.

Marking as urgent so as to avoid sending out notifications that are not wanted.

@BirenRathod please reassign to John if this isn't an issue for you.

**Comment by BirenRathod** [comment]
This is something @johnvanbreda to look into.

**Comment by johnvanbreda** [comment]
Now fixed.
