### ISSUE TITLE
Importer V2: useful having two Comment fields

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1744]
This is a comment, not a request. 
I've successfully imported separate columns 'Occurrence comment' and 'Sample comment' using survey 'DRN dragonfly imports'. This may have been available in V1 but I never tried it. Presumably this is also available with other surveys. Worth celebrating!

**Comment by sacrevert** [comment]
Note #1752 regarding downloads, otherwise closing this comment for the sake of tidyness
