### ISSUE TITLE
Importer V2: field shown twice on the field matching screen

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1745]
_Minor issue_
In Training Mode, the summary is shown, including the 'Fixed values that apply to all rows'. All looks OK except:
- 23396	>	smpAttr:21		unexplained
- t		> 	Training			occurs twice
![image](https://github.com/user-attachments/assets/5a1d4556-5f44-46af-8c37-d730f1864339)

**Comment by sacrevert** [comment]
Training flags are used at both the occurrence and sample level. Perhaps that is why there are two here.

**Comment by johnvanbreda** [comment]
@sacrevert is correct about the reason. I've clarified this by adding the destination table to the label (so it shows "Occurrence training" and "Sample training") plus corrected the label of the sample attribute. Code in the develop branch so will be released at the next full update.
