### ISSUE TITLE
Importer V2: crossover symbol for list match is worrying

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1747]
The summary page after field matching shows a crossover symbol 
![image](https://github.com/user-attachments/assets/b053d227-eaa8-4e44-996a-2e249fca9fa2)
 for 'Species or taxon name', although the column header is an exact match. The mouseover help for this symbol says "Values in this column are matched against predefined lists of term". So that's OK but could the icon be improved because it worries me that the input text is being manipulated in some way?

**Comment by johnvanbreda** [comment]
I'll switch it to this alternative in the next release:
![Screenshot 2024-10-31 at 12 31 07](https://github.com/user-attachments/assets/a04f2351-d305-4737-b936-61548edf345f)

**Comment by DavidHepper** [comment]
Perfect!
