### ISSUE TITLE
System function: can it be applied retrospectively?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#175]
The custom occurrence attribute "Qty" (occ. attr. 133) stores a quantity measure in the iRecord Moths survey. A couple of weeks ago I set "Qty" to have a system function of "Count or abundance of a sex or life stage".

New records added to the iRecord Moths form since 20 Feb 2017 do now have data included in the "attr_sex_stage_count" column in the standard download format, but records prior to that date remain as null in the "attr_sex_stage_count" column.

Is it expected behaviour that when we assign a system function it only applies from that point in time forwards?

Is there any way of 'forcing' a system function to be applied retrospectively?

In this example for moth abundance data I would want the quantity field to be populated in the standard download for all records entered in the past, but are there cases where a system function should not be applied retrospectively?

**Comment by johnvanbreda** [comment]
@kitenetter Currently because this is a rare occurrence there is no automation of the change for existing records - we would write a simple SQL script to do it. Potentially we could write a process to do this update a chunk at a time as an automatic background task but I am not sure it is worth the effort.

**Comment by kitenetter** [comment]
Understood. For this particular case (occ. attr. 133 in the iRecord Moths survey) I would like to request that an SQL script is applied to add the system function to records from before 20 Feb 2017.

**Comment by kitenetter** [comment]
@johnvanbreda I'm not sure if the update to moth records before 20 Feb 2017 was ever applied - if not, please can you do this.

**Comment by kitenetter** [comment]
In the last week I've been alerted to two cases where attributes that I thought had been given a system function do not in fact have that function in the warehouse. I will assign the system functions.

Based on the discussion above I think we will also need to do a number of database updates to retrospectively apply the new system function to data from previous years.

Question for @johnvanbreda : am I right in thinking that for every new system function we apply a database update is required if we are to ensure that the relevant attributes from previous years get included in data downloads?

**Comment by johnvanbreda** [comment]
@kitenetter that is correct, unless we write some code to handle this case which would be a few hours work. I'd suggest it would be done via the work queue.

**Comment by johnvanbreda** [comment]
@kitenetter I've done the moth record data for occAttr ID 133 - using the following query:
```sql
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_attrs_occurrence', 'occurrence', occurrence_id, 100, 2, now()
from occurrence_attribute_values 
where created_on<'2017-02-21'
and occurrence_attribute_id=133;
```

This query could be adapted by changing the attribute ID, filter date (using the day after you changed the system function to ensure all records are captured), or by replacing 'occurrence' with 'sample' to do sample attribute values.

**Comment by kitenetter** [comment]
If further updates are needed I'll open a new issue - closing this one.
