### ISSUE TITLE
Rule-checks for incoming records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1750]
At 12:26 today, I can see no rule checks appearing for records added since we came back online. Is this just the usual delay while the system catches up, or does something need to be reset?

**Comment by johnvanbreda** [comment]
I've found an error relating to email services, probably something to do with the servers restarting. I'm just checking with IT Support.

**Comment by johnvanbreda** [comment]
Things seem to be catching up as of this morning so presumably something has been fixed. Will close but please re-open if still a problem.
