### ISSUE TITLE
Importer v2: More info about species value (mis)matching

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#1755]
The current value matching for species does not specify what the "Save matches for Species" checkbox actually does. As far as I can tell it only "saves" the match for the current import operation; at least when I upload the same file again it picks up the same error, so it does not seem to be saving the match globally. That's fine, and makes sense (for bryophytes there are a number of cases where we may have different matches for the same (ambiguous) species name based on the identity of the dataset e.g. _Ulota crispa_ has three potential meanings, and we would not want any given match to be saved universally).

- If the checkbox is only supposed to be for the current import (i.e. all values matching in this file), then can we add some explanation that this is the case (ideally under the checkbox itself), as BBS members have queried this.
- If there is supposed to be global save of the match relating to this, then can this be explained, but, additionally, can it be made optional please (currently one must agree to proceed).

![image](https://github.com/user-attachments/assets/93e1ed4b-cc5f-459a-8b32-3a8a1a391ffb)

**Comment by johnvanbreda** [comment]
I agree - the save is for the current import. @kitenetter would you like to suggest wording changes for this part of the importer to make this clearer?

**Comment by kitenetter** [comment]
Suggestions:

The blue button could be labelled "Tick to proceed with the above name-matches", and some supplementary help text could say "Once you have specified the taxon names that you wish to use, tick the box to apply the names to the current import."

I think it is the use of the word "Save" that may be misleading people about what this function does.

**Comment by johnvanbreda** [comment]
As it's really a button, not a tickbox, I ended up with the following text:
Once you have specified the taxa that you wish to use when matching values from the "Species" column, click the button below to apply the matched terms to the current import.
[Apply matches]

This is in the develop branch ready for the next release.
