### ISSUE TITLE
Activity not filtering on location

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#176]
This is another issue reported by John Bratton, so I'm beginning to wonder if there is something in his account settings that is causing the Activities to work incorrectly (John was an early joiner of iRecord).

He is trying to set up a new Activity, "Winteringham (N. Lincs) Wildlife":
http://www.brc.ac.uk/irecord/activities/edit?group_id=930

He is using the "Where" filter to choose a Winteringham boundary from his "My Sites", and that choice seems to get saved okay into the Activity. But when he goes to Explore records for the activity it is attempting to show all records for the whole country.

I've masqueraded as John and have re-saved his Activity with the Winteringham boundary, but it is still not filtering the records correctly.

The site boundary seems to work correctly if John goes into his "My Sites" lists and explores the records from there.

**Comment by kitenetter** [comment]
Possibly related - this Activity is also not showing any records within its custom freehand boundary:
https://www.brc.ac.uk/irecord/activities/explore?group_id=730&implicit=

**Comment by johnvanbreda** [comment]
Hi Martin, 
I'm not seeing the behaviour you describe in the first comment - either logged in as myself or John the site boundary works on the page https://www.brc.ac.uk/irecord/activities/explore?group_id=930&implicit=. There are some low precision grid squares that get in the way though. Are you still seeing this behaviour?

The 2nd comment is explained by the fact that there aren't any verified records of those 4 species in the dataset (the filter is verified records only).

Regards
John

**Comment by kitenetter** [comment]
@johnvanbreda I've just looked again at John Bratton's activity and I agree that it is now working okay.

And for the second one I hadn't realised that it was set to look for verified records only - apologies for that.
