### ISSUE TITLE
Set level 2 verification terms to be the default when you go to your verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#177]
At the moment, every time a verifer goes to their verification page the buttons for setting a verification flag are set to the default level 1 choices of Accepted or Not accepted. Since we know that most verifiers prefer to use the level 2 terms (Considered Correct etc.), can we make the level 2 options the ones that appear by default?

An additional feature would be for iRecord to remember a verifier's choice from previous use, so that having chosen either level 1 or level 2 that choice would be remembered as the default for the next visit.

**Comment by MNSmith** [comment]
Please leave this feature as it is at present.  For aculeates we use "Correct" for records with photos and "Considered correct" for those without.  I regularly go down the verification list switching betweeen the two as I go.  Having the system offer the previous choice each time i move on to a new record would not be helpful at all.  Please do not change the current setup.

**Comment by kitenetter** [comment]
@MNSmith that's not what I meant Matt, so apologies if I was unclear. What I mean is that whenever I go to the verification page it is set to use the two-option version:

![image](https://cloud.githubusercontent.com/assets/16039111/23876033/83656ee8-0833-11e7-8a3f-e5247c7f29a1.png)

So the first thing I always have to do is change this to the five-option version:

![image](https://cloud.githubusercontent.com/assets/16039111/23876047/9841b556-0833-11e7-9d28-79465a19b7e0.png)

What I'm proposing is that when you first go to the verification page it defaults to the five-option version, which you can set back to the two-option version if that's what you need. This is not just to make my life easier (!) but because we know that the majority of verifiers are now using the five-option version.

The ideal would be for iRecord to 'remember' an individual's preference for the two-option or five-option choice and default to that when they first go to their verification page, but in the short-term I think there is a case for the five-option version being the standard default.

**Comment by MNSmith** [comment]
Ah-ha.  Showing the 5 buttons by default - that's fine then because that's the first thing I have to get to display via the "more" button.
