### ISSUE TITLE
Verify is not showing the Grid

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1771]
Verify isn't working for Main or iNat.
FF & Chrome.

**Comment by kitenetter** [comment]
Records also missing from Explore and Activity pages.

**Comment by johnvanbreda** [comment]
@kitenetter looks like we've had a Drupal upgrade which has broken things. Should we put iRecord into maintenance mode? I'm not 100% sure how quick I can fix it.

@BirenRathod is it possible to not apply any Drupal upgrade to the live site until it's been checked on the test site?

**Comment by johnvanbreda** [comment]
@kitenetter having said that - I've turned off JavaScript aggregation just now and it's fixed the problem. We can't leave it like that permanently but it should be OK while I investigate.

**Comment by johnvanbreda** [comment]
For info - the Drupal 10.4 release notes included the following, which is a likely source of the issue:

> [Assets are now ordered by dependencies](https://www.drupal.org/node/3473558) instead of relying on the order that libraries were attached to the page. This is a bug fix that resolves various issues with asset handling. However, there may be side effects in some situations (for example, if a library specifies an individual asset weight that conflicts with its dependencies). Module or theme authors should review their projects for library dependencies that specify custom weights and evaluate any that do to determine if they are affected by this change.

**Comment by johnvanbreda** [comment]
@BirenRathod there is now a new version of the iform module - please can you deploy this to the upstream? The only change required is the file client_helpers/helper_base.php so if it is easier you can just update that.

Once done we can turn JS aggregation back on.

**Comment by BirenRathod** [comment]
@johnvanbreda  No problem. I will do that and let you know soon.

**Comment by BirenRathod** [comment]
@johnvanbreda helper_base.php updated on all sites now.
