### ISSUE TITLE
Form editing queries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#179]
A couple of questions relating to editing forms. I am testing this on the beetle form:
http://www.brc.ac.uk/irecord/enter-beetle-list
 
First, how do I control the width of the boxes in the species table part of the form? I want to make the "Stage" column wider so that the red asterisk does not go onto a second line, and I want to make "Determination year" narrower.
 
Second, when I add a species name to the first row in the table, and then specify in Stage that it is "Adult", what I want is for the Stage term in the subsequent rows to automatically be set to "Adult". That is how the main iRecord "Enter a list of records" form works. It possible for the beetle form to work the same way, or does setting the Stage to mandatory mean that it can no longer be automatically updated in the subsequent rows?

**Comment by BirenRathod** [comment]
Hello Martin

1. To control a width, please set the size of the each columns (e.g. 15,6,8,....) in the "Grid Column Widths".
2. Set the default value of the stage occurrence is "Adult" (e.g.  @occAttr:288|default="Adult") in the configuration of the "Form structure" of User interface section.

Biren

**Comment by kitenetter** [comment]
1. Where do I find the Grid Column Widths?

2. I don't want to set a default in advance - what I want ideally is for the Stage attribute to be blank when the user first goes to the form, but for it to be mandatory so that the user is required to give a stage term. But having given a term in the first row of the grid I'd like that term to be automatically copied into the second row and into subsequent additional rows.

**Comment by BirenRathod** [comment]
1. In the "Species" section
2. make sure to check this "New species grid rows use previous row's data" checkbox.

**Comment by BirenRathod** [comment]
For 2. also make sure to include columns in "Columns to include" box.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - that's all okay. Can't get the red asterisk to move up from its second line but that's not important.
