### ISSUE TITLE
Photo added to record but not displaying

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#180]
I've just edited this record:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=2817554

I wanted to add a photo to it as it has been queried by the county recorder. Clicked on the record's Edit button and added the photo, but it isn't showing up on the record page. The date/time of latest edit is correct, and if I try to edit it again I can see that the photo is there but it's not showing on the record page itself.

The thumbnail is showing:
![image](https://cloud.githubusercontent.com/assets/16039111/24057762/695d59c4-0b40-11e7-8aa5-2ffd92aff3ce.png)

but nothing on the actual record page, which is a shame as I'm hoping to use this as a demonstration of the usefulness of iRecord in an attempt persuade the county recorder that he should get involved with verification!

**Comment by kitenetter** [comment]
This morning the photo is visible at:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=2817554

So was I just being impatient - does it take some time for photo edits to feed through to the main record display?

**Comment by johnvanbreda** [comment]
Yes, there is caching on the output of the record details.

**Comment by kitenetter** [comment]
Thanks - I guess what caused concern for me was that the thumbnail appeared immediately but the main photo didn't, so it's good to know that the caching affects this.
