### ISSUE TITLE
NatureSpot taxon groups missing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#182]
Some of the taxon group names used by NatureSpot seem to have gone missing from the iRecord filter options. The one I needed to use today was "Fungi", which has been used before to set up filters for NatureSpot verifiers, but no longer appears under "Species groups" in the "What" filter.

I think some of the other NatureSpot group names are also missing.

**Comment by DavidRoy** [comment]
I think you need to use the 'NatureSpot' version of the filter setup form with 'ns' on the end
..../filters/admin-edit-ns
