### ISSUE TITLE
Making the "Stage" field mandatory

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#184]
We've been asked by a number of recording schemes to make the "Stage" field (occAttr:106 in the iRecord General survey) mandatory, in order to reduce the number of records that arrive without a stage - for insect groups in particular this makes phenology analysis and verification checking much more difficult than it needs to be.

David and I have agreed that we should make this change. As far as I'm aware, to do this I will have to mark the Stage attribute as "Required" within the iRecord General survey settings. I intend to make equivalent changes to other relevant surveys, such as iRecord Moths.

@BirenRathod @johnvanbreda @JimBacon is there any reason why I shouldn't go ahead and make this change? Is it right to make the change at the Survey level, rather than at the Global level?

@kazlauskis does this have any implications for the apps? (I'm assuming it doesn't since they feed in to different surveys?)

Thanks.

**Comment by JimBacon** [comment]
Do you also intend to remove the "Not recorded" option as well? If you make the attribute mandatory that only removes the option of leaving it blank. 
Will this confuse the plant recorders?
I definitely wouldn't do it globally as it would affect many other organisations sharing the same attribute who might not want to experience this change. See http://warehouse1.indicia.org.uk/index.php/occurrence_attribute

**Comment by kazlauskis** [comment]
Yes, it would affect the iRecord App. It uses that same attribute for stage and if you made it mandatory then all app records would throw an error if were sent without stage.

I would create a new mandatory-stage attribute and use it in the general form or elsewhere new.

**Comment by japonicus** [comment]
For plant recording the current terms 'adult', 'pre-adult' and 'other' don't make much sense, so I would be strongly in favour of retaining 'not-recorded' as the default for plant records if this attribute became mandatory.

Even for taxon groups where 'stage' is meaningful I think that there is a need for an undefined response - as people may be using iRecord to transcribe records from sources where 'stage' wasn't specified by the field recorder and compelling a positive answer on the form will degrade the value of the attribute by requiring people to guess at what was originally observed.

**Comment by BirenRathod** [comment]
Definitely not to do globally but you can set mandatory on survey base. It won't affect the iRecord app or any app, because all apps have got synced with their own survey.

**Comment by kitenetter** [comment]
Follow-up comment:
- The option for "Not recorded" will still be available, we just want people to make a positive choice to use it, rather than just accepting it because it's there by default. And we are also intending to add a few additional stage terms (including "flowering" and "vegetative") to make this attribute more relevant to additional taxonomic groups. 

Follow-up question:
- @japonicus raises a further question: if we make the Stage attribute mandatory going forward, what happens to any existing records that have a blank value for this attribute? Do we need to run a database query to change all existing blanks to "Not recorded"?

**Comment by BirenRathod** [comment]
No need to change any existing records but it will ask if somebody edit existing record which might not accept the blank record.

**Comment by johnvanbreda** [comment]
Although Biren is correct in that it is not necessary, I would still recommend updating the existing records to add "not recorded" where the stage is missing, otherwise editing records will be confusing.

**Comment by kitenetter** [comment]
Moving to #186 to implement database update
