### ISSUE TITLE
Verifiers "Log" behaving erratically?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#189]
If I log on as me and go to my verification grid for Berks moths, and choose the "Log" tab, it is only showing 9 entries, but I have queried and commented on many more records than that.

A couple of other verifiers have reported seeing this when they go to the Log:
![image](https://cloud.githubusercontent.com/assets/16039111/24911283/56cab000-1ec2-11e7-891a-63718cb5b2f6.png)

I'm not sure whether that is a bug or a feature that I don't understand?

**Comment by johnvanbreda** [comment]
@kitenetter Does the default input form issue still occur? This area of code has been tidied so I hope not.
The log tab is subject to the same filter as the main tab, so you may need to change the Quality setting to All records to get a full list of information.

**Comment by kitenetter** [comment]
All seems to be fine when I log on as me and check my verification page (in Chrome) - thanks.

**Comment by kitenetter** [comment]
Have had recent reports from another verifier that his comments are not appearing in the log, and when I tried to check my verification log just now I got stuck with the egg-timer.

**Comment by johnvanbreda** [comment]
@kitenetter is this OK now?

**Comment by kitenetter** [comment]
Seems to be working fine for me at the moment, thanks - closing.
