### ISSUE TITLE
Recording form for interactions

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#19]

**Comment by johnvanbreda** [comment]
We have 2 potential user interfaces. If you register at http://fungallife-bvff.temp-dns.com/ (test records only at the moment), you can try the simple entry form which allows a simple associated species to be added to the record. Or, at http://fungallife-bvff.temp-dns.com/?q=record/list you can add a list of species and associations with multiple interactions. Its of course more complex then.
Any preferences?

**Comment by johnvanbreda** [comment]
@kitenetter Setting up a page with a simple "associated species" input is fairly simple now - if you let me know the details of what you want on the form I can set this up.

**Comment by kitenetter** [comment]
@johnvanbreda I think this was a generic requirement from a long time ago, and has been superseded by the subsequent work for BMS etc. Closing.
