### ISSUE TITLE
Importing date ranges for dragonfly survey?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#190]
In survey ID 346, "DRN dragonfly imports", if I look at the Database fields they include the standard attributes sample:date_end, sample:date_start and sample:date_type. BDS need to import CSV files with date ranges, and I had hoped that they would be able to do so by importing to those attributes. However, using the iRecord CSV import process, if I select "DRN dragonfly imports" as the Survey, I am not offered sample:date_end etc. as one of the attributes that I can import into.

Presumably there is a settign somewhere that restricts the attributes for "DRN dragonfly imports" so that only the custom attributes are shown. How is that done? And can it be adjusted to include the three date range attributes?

**Comment by johnvanbreda** [comment]
@kitenetter if you have access rights to view the Edit tab on iRecords import page (https://www.brc.ac.uk/irecord/node/159/edit) you can find the setting called **Field/column mappings**. This does indeed define a custom set of columns for DRN with the date field mapped and an option just underneath set to enforce that only these columns are used. Therefore the alternative date fields for vague dates are not available. You should be able to add sample:date_start, sample:date_end and sample:date_type to the list.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda, I have added those three fields, but have not yet tested the import.

Moving slightly off-topic, would a similar set of enforced Field/column mappings allow me to define a slightly simplified version of the standard iRecord Import structire, so that users have fewer fields to choose from?

If so would I need to define a new survey in the warehouse, or can we have two routes to import into the same survey?

**Comment by johnvanbreda** [comment]
Each import page can have a single configuration of column mappings per survey set up. So, if the iRecord import survey is to remain as a relatively complete option, then you could perhaps set up a new survey called iRecord simple import. This could then be configured with simple column mappings to make it easy to use. You could even have a simple import page configured with just this survey dataset available so it skips the survey selection stage.

**Comment by kitenetter** [comment]
@kitenetter to review this under #16 - closing
