### ISSUE TITLE
Extension of Stage terms

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#192]
As previously discussed, we are intending to extend the list of stage terms available on the standard recording forms. I can see two ways of doing this - please can you let me know of any preferences/implications/alternatives:

1. Add extra terms to existing attribute (occurrence attribute 106), so that the list offered will be extended for all surveys and forms that use occAttr:106
2. Add a new occurrence attribute using the extended termlist, set that attribute to have a system function of "Stage", and replace occAttr:106 with the new attribute on all forms that we wish to change

Would be grateful for opinions from any or all of @johnvanbreda @JimBacon @BirenRathod @DavidRoy + Oli and Tom (can't find your Github names)

Current list of terms for occAttr:106:
- not recorded
- adult
- pre-adult
- other

Proposed extended list:
- not recorded
- adult
- egg
- larva
- nymph
- pupa
- exuviae
- teneral
- juvenile
- tadpole
- nest
- gall
- leaf-mine
- flowering
- fruiting
- mature
- seedling
- vegetative
- other

(The extended list is long but is a compromise between all the possible stages that might be used across all taxa, and keeping the list manageable.)

**Comment by DavidRoy** [comment]
I think it has to be option 2 given the wide use of the existing occurrence attribute 106.  Call the new one 'Stage-extended list' or something similar?

**Comment by JimBacon** [comment]
If you switch to a new attribute then I think there will be a problem editing existing records made with the old attribute. We could update all existing records with SQL to rectify that.

**Comment by japonicus** [comment]
If converting from the old list to the new then what does 'pre-adult' map to? It's not present on the new list, but the simplest option of adding it is also problematic as the long list would then contain a confusing non-exclusive option.

Are there any plans to allow iRecord forms to dynamically adapt to the selected taxon group?  That would be a useful feature.  If that is planned, then would the proposed expanded status list fit well with a more flexible form. Might it be better instead to have multiple specialised 'stage' attributes that apply to particular taxon groups, rather than a single catch-all attribute (so that only the taxon-relevant stage attribute is ever displayed on the form).

The proposed list is already problematically long and is likely to grow further as additional demands come in from recording schemes. I'd be somewhat inclined to wait until specialist lists are possible. 

Using a single general purpose list will inevitably result in mistakes (or deliberate perversity) by recorders, resulting in weird stages being applied to inappropriate groups - errors which will need to be filtered-out by each recording scheme that uses this attribute.

As we'd previously discussed by email, possibly also add 'sporophyte' and 'gametophyte'.
Would mammalian recorders want 'scat' as an option?

**Comment by JimBacon** [comment]
All very sensible Tom but I dispute scat describes a life stage except possibly for adolescent human males although I tend to use a coarser word ;-)

**Comment by kitenetter** [comment]
I agree with much of what @japonicus says, but it leaves us with the question of whether it is worth implementing the extended list in the short term, in order to allow better quality records to be made, while we wait for the better long-term solution of having taxon-group-specific term lists. I'm still undecided on that.

If we do move to an extended list I think we will have to retain "pre-adult" on the list for backwards compatibility. Is there any way of retaining a term on a termlist in the warehouse but excluding it from view in the data entry forms, i.e. are there any controls in the forms that allow termlists to be filtered?

**Comment by JimBacon** [comment]
I assume you would have a new termlist to go with your new attribute. Not sure why you would want to filter...

**Comment by kitenetter** [comment]
@JimBacon the reason is that if we have a new termlist, we will need to keep "pre-adult" in the list, as we can't translate the existing "pre-adult" records into anything more specific. But we wouldn't want to continue accumulating "pre-adult" records into the future, because the term is too broad. So "pre-adult" needs to be on the list, but we would prefer to hide it from people adding new records.

**Comment by JimBacon** [comment]
Ah, I see. We could do something blunt and form-specific in JavaScript to hide the pre-adult term if it is not the current value. I think there would need to be some programming involved as it is not a simple filter but conditional.

**Comment by DavidRoy** [comment]
I'm not sure we need complete backwards compatability.  One option is to:
1. create a new occurrence attribute with an extended term list (excluding the now redundant pre-adult)
2. create a new version of recording forms where this will be used (e.g. enter-casual-record-v2017) which uses the new term list
3. replace the 'enter-casual-record' form on iRecord with the new one 'enter-casual-record-v2017'. 

Existing records will link to the old form, new ones to the new form, i.e. both are editable with the right term list.

**Comment by JimBacon** [comment]
Would a new form have to retain the existing url so that external links and iframes start to use it?

**Comment by DavidRoy** [comment]
Maybe.  Perhaps another option is to rename the current form to 'enter-casual-records-old' and update the relevant database field 'entry-form' in the warehouse.  Then the new form is named 'enter-casual-records' to retain external links

**Comment by johnvanbreda** [comment]
I agree with this approach - renaming the old form's path and updating existing entries to match, then creating a new form with the enter-casual-record path seems better than adding a new form with a new path. You'd of course want a new survey_id added to the database as well so the 2 structures can be kept separate.

As Jim said, another approach would be to implement some code to hide deprecated terms in the list such as pre-adult unless they are already in use on a selected record. This could be more widely useful though so it might be worth considering?

**Comment by JimBacon** [comment]
Could you keep one survey, assign both attributes to it, and use the form structure to pick out the appropriate attribute to show on each form?

**Comment by kitenetter** [comment]
I like @JimBacon 's suggestion as it avoids duplication of surveys. I assume that the system function will allow the Stage column to be populated in any download, regardless of which attribute was used for data entry. The only dangers I can see are:
- if people try to import CSV files into the "iRecord General" survey - they will be faced with two similar but different attributes for Stage
- it adds complexity for anyone wanting to analyse the data via database queries (but having two surveys would add at least as much complexity)

However, if we are able to implement "some code to hide deprecated terms in the list" as John suggests then that might be an even better solution, as it would enable us to add new terms to the existing list while hiding "pre-adult" from use, and would avoid having to set up new surveys and forms. Have added that as #195 

I suggest that we park the extension of the termlist for Stage and see if we can implement the hiding of deprecated terms first, so will close this issue for now.
