### ISSUE TITLE
Enable terms in termlists to be flagged as "not in use" or similar

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#195]
This arises from #192 and some other recent cases where we have had a need to edit termlists, including removing terms from existing lists. The problem is that if we simply remove a term from a list, and that term has been used in any existing records, we corrupt the link between record and term.

A generic solution would be to implement some code to enable us to hide deprecated terms in termlists, so that they remain in the list and links from existing records will be respected, but become unavailable for any new data entry.

Need to ensure that hidden terms are hidden from the CSV upload process as well as the recording forms.

**Comment by johnvanbreda** [comment]
1) Add a termlists_term.allow_data_entry flag (boolean, default true), to match the similar flag for taxa.
2) Add this field to cache_termlists_terms.
3) Update the code which loads terms into lookups so it filters for allow_data_entry=true.
4) Update the warehouse UI so this field's value can be set.

**Comment by johnvanbreda** [comment]
Code now dropped into develop branch.
