### ISSUE TITLE
Extension of sex termlist - does this cause any problems?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#196]
I'm hoping that this will be less complex than the extension of stage terms!

We have requests to allow queen and worker bees and ants to be recorded as such. The obvious way to do this is to add these two terms to the sex termlist (occAttr:105) to become:
- not recorded
- male
- female
- mixed
- queen
- worker

Can anyone see any problems or unintended consequences from adding these terms in the the main termlist?

**Comment by johnvanbreda** [comment]
Technically from the code perspective I can't see any problems.

Technically from the biological perspective, aren't these castes, not sexes? Also the attribute is used across a wide variety of surveys which means you might start getting records of queen moths, for example. 

You could add a new attribute and termlist, then run a query to map the existing bee data across?

**Comment by kitenetter** [comment]
I agree that these are castes, not sexes, and I think that for BWARS the ideal solution would be to replicate what appears on their bumblebee-specific recording forms:

![image](https://cloud.githubusercontent.com/assets/16039111/25386576/be43374a-29bf-11e7-8f4b-bf17cbe98160.png)

But it does not seem reasonable to add these fields to the generic all-taxa recording forms. And I don't see how we could map existing bee data across to a new termlist as information about queens and workers is currently missing or is given in non-standard form in the comments.

Also, any new attribute would need to be added to the default download in order for it to be accessible.

So the question becomes whether it is worth adding the two caste names to the termlist for sex in order to make some improvement in data quality in the short term, or whether we leave things as they are until such time as it may be possible to implement intelligent forms that offer attributes tailored to the taxon entered.

Or alternatively we could revisit the idea of setting up a more comprehensive set of recording-scheme-specific data entry forms, and devise ways of steering users to those forms in preference to the default generic forms wherever possible. This also has implications for downloads.

Would be grateful for opinions on whether the short-term fix is worth pursuing.

**Comment by DavidRoy** [comment]
One immediate option is to review/finalise this form and then ask BWARS to direct recorders to it for one-off sightings?
http://www.brc.ac.uk/irecord/enter-aculeate-record

This complicates the question of downloads though

**Comment by kitenetter** [comment]
This is likely to be addressed under #222 (although the download issues are not yet resolved) - closing.
