### ISSUE TITLE
Species Alert subscription does not allow 'Cyanobacteria'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#197]
http://www.brc.ac.uk/irecord/species-alert-notifications

I suspect because the form is restricted to taxon rank = Species or lower.

We need to enable alerts for 'Cyanobacteria' linked to an App for recording algal blooms

**Comment by johnvanbreda** [comment]
The list available for searching is list 34, the GBNNSIP list which cyanobacteria is not on. Should we add cyanobacteria to the list, or switch to allowing a search on UKSI? The latter was originally discounted as it might not be up to date enough I think,

**Comment by DavidRoy** [comment]
I thought because the form allows the selection of a full species list (where UK Master List is an option), that it could extend the option for alerts.  But I now realize that this dropdown is to 'restrict' the GBNNSIP list.

I think the best option is to allow Alerts to be identified from the UKSI Master List and GBNNSIP

**Comment by johnvanbreda** [comment]
That requires a smallish code change to enable multiple lists to be enabled - you'll probably want to pick the list to search as a first step. Or - could we create a clone of the form for species alerts against any species as opposed to just non-native invasives?

**Comment by DavidRoy** [comment]
I think the first option gives more flexibility in future.  The form should default to UKSI unless other list selected.  I assume the underlying database storage and processing remains unaffected whatever interface changes we make

**Comment by johnvanbreda** [comment]
Fixed applied to develop branch. When this goes live the form will need a config tweak to enable search in both lists.

**Comment by johnvanbreda** [comment]
Now done
