### ISSUE TITLE
Filter on input date, modified date, or verification status dates not working correctly in exlpore all records

### ISSUE THREAD

**Issue by colinharrower** [BiologicalRecordsCentre/iRecord#198]
I'm not sure that filters using the input date, modified date or verification status on the explore all records page are working correctly as they aren't showing all of the records they should be.

If I view verified ladybird data and set the record date range to 01/01/2012 to 31/12/2012 713 records are displayed. At least a few of these records for 2012 record were entered and/or verified in the last couple of years however if I use the date filter to show ladybird records input since 01/02/2016 then 953 records are returned (which seems extremely low) and all of the records returned have recording dates in 2017. This query should have returned 2016 data along with any records from previous years including the selection from 2012 that were entered to iRecord after Feb 2016.

**Comment by colinharrower** [comment]
I've check the download page and the input date filter does appear to work correctly for downloads as I tried the same query (all accepted ladybird data with an input date >= 01/02/2016) and the download file contained over 12,000 records with recording dates covering a wide selection of years including 2012. It therefore looks like the issues is specific to the explore page

**Comment by johnvanbreda** [comment]
Hi Colin
I've tried to reproduce this but can't. I've got the following settings in my filter:
What - family set to Coccinellideae
Where - no filter
When - records recorded on or after 01/02/2016
Quality - accepted records only

This filter gives me over 11K records and if I sort on the date column I can see that the first record is indeed on 01/02/2016 as expected. Likewise with the filter set to 2012, I get 713 records but sorting on date shows them all to be in the correct year.

Can you explain in more detail how I can recreate the problem please?

**Comment by colinharrower** [comment]
Hi John,

What you have written sounds exactly like what I tried and was having issues with, although I was starting from a saved filter that shows all accepted ladybird records and then modifying the filter to add the input date restriction. At the time I did go and speak with David to check I wasn’t doing something silly and he seemed to have the same problem and I think he tried it both as an administrator and also psuedo as my account. He asked me to raise it as an issue.

I’ve attached a screenshot showing the filter selection that is shown on screen after modifying my existing saved filter. 

![image](https://cloud.githubusercontent.com/assets/4245916/25382291/d7466f16-29ae-11e7-8ff3-c5de2071b536.png)

This query returns 1021 records but it should return a lot more.

I've just tried creating the filter from scratch and the filter only seems to return 14 records this time. I think there might be a problem where parts of the filter are not actually being updating correctly after changing the options (or that the default filter values are never being entirely cleared?). 

If I go into the explore all records the default filter (show below) seems to show: taxonomic groups I'm interested in in Berkshire, recorded in the last month, excluding no accepted records. This default search is currently returning 1843 records. Note that in the image there is no indication that the species list is being filtered to species I'm interested in but looking at the records suggests it is.

![image](https://cloud.githubusercontent.com/assets/4245916/25382965/c61f92aa-29b1-11e7-87fe-60ee61796a17.png)

If I go into the where section however there isn't shown to be any active filter currently despite the previous screen showing a filter for Berkshire. Selecting apply with nothing in any of the filter boxes should remove any geographic filters (I can't see any explicit button/option to remove the hidden berkshire filter).

![image](https://cloud.githubusercontent.com/assets/4245916/25382992/e4996c88-29b1-11e7-83ec-f6d9394ab724.png)

The text within the where part of the filter options no longer shows Berkshire (see image below) but the map and total number of records are unchanged and the Berkshire filter appears to still be in effect. Even if I save the filter, reload the form and then select and apply this new filter the records are still restricted to Berkshire.

![image](https://cloud.githubusercontent.com/assets/4245916/25383186/d81a07f0-29b2-11e7-81dd-50c2fa0e2b06.png)

If I choose another region in where clause (i.e. country = England) and apply that map will update and show records covering the new region (41,981 records in my case) but if I then go back in and remove this filter and press apply it goes back to only showing Berkshire records (1849 records).

There is a similar problem with the when filters if I use any date but the field record date. For example if I reset/reload the page and attempt to change just the when clause from the default (records in the last 1 month) to show any records with an input date >= 01/02/2016.

![image](https://cloud.githubusercontent.com/assets/4245916/25383585/b4c6fb30-29b4-11e7-8e69-d8246444b510.png)

Despite this filter (shown above) now showing the new filter in the when box the map and records set are unchanged showing only the 1849 records from the default filter indicating that the filter changed hasn't been applied. If I do the same but for the field record date rather than input date then the clause does appear to work and the map and record set are updated (30,198 records returned).

I hope this new information gives you enough details to replicate the issues, If you can replicated the issue I'm happy to skype with screen sharing to show you what I've been trying.

**Comment by kitenetter** [comment]
I'm assuming that this problem has gone away, or failing that will be addressed with the new ES Explore pages nearly ready to deploy. Closing.
