### ISSUE TITLE
Bug in setting the "determiner_person_id" attribute during upload?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#199]
This came to light while trying to respond to a question highlighted by Jim on the NBN forum:
https://forums.nbn.org.uk/viewtopic.php?pid=26866

I'm not sure if there is a bug here or if I am misunderstanding something.
1. If I import a CSV file into iRecord Import, and provide "Harvey, Martin" as the recorder name, when I subsequently download the data (via the default download) there is an attribute "recorder_person_id" that gets populated with "50", which my ID in the warehouse users table.
2. If I import a CSV file and provide "Harvey, Martin" as the determiner name, when I subsequently download the data the attribute "determiner_person_id" that also gets populated with "50".
3. If I import a CSV file and provide "Roy, David" as the recorder name, when I subsequently download the data the attribute "recorder_person_id" shows "unknown".
4. If I import a CSV file and provide "Roy, David" as the determiner name, when I subsequently download the data the attribute "determiner_person_id" gets populated with "50".

I've never understood what we use "recorder_person_id" or "determiner_person_id" for, nor why it gets included in the download.

Based on points 1-3 above it appears that a link between name and ID is only made when the recorder is the same person as the user who is uploading the data, i.e. it is not just matching the text string (which is a good thing as that may not be unique).

Based on point 4 above it looks like there is a bug - I cannot see why having David as the determiner should trigger putting my ID into the "determiner_person_id" attribute.

If this is a bug it would of course be good to fix it, and at some point I'd like to understand what these attributes are for and what if any implications they have in the upload and download processes.

**Comment by johnvanbreda** [comment]
The intention of these attributes was to provide a unique ID for a person in the situation that the record can be linked to a known person, rather than just a text label. It could then be used by processes such as the Indicia2Recorder addin for Recorder 6 to link records to the correct person in the Recorder database (rather than have to assume all instances of Roy, David could actually be different people for example). 

Can you provide me with an ID of a record that shows the problem in point 4 please so I can look into it.

**Comment by kitenetter** [comment]
Record ID for point 4:
4834010

Let me know when you're done with it as it isn't a genuine record and I need to delete it!

**Comment by kitenetter** [comment]
This doesn't seem to have caused any recent problems, and record ID 4834010 has been deleted. Closing.
