### ISSUE TITLE
Inconsistent presence and placement of links to login/register

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#201]
I think that it is conventional for websites with login/registration links to present these in a consistent location across all pages of a site, so that a user can login or register at any point, regardless of the page they entered at.

While not logged-in, several iRecord pages are accessible that either have only a 'register' link, e.g. 
http://www.brc.ac.uk/irecord/explore (which prompts me to 'register', but provides no option to login with an existing account)

The forum pages have neither registration or login links.

Other pages such as the data entry forms include links to register or login, but only in the body text. The inline links are fine, but I think the links should also be duplicated in a consistent location as part of the site navigation (e.g. top-right corner).

**Comment by kitenetter** [comment]
AS far as I can tell we do now have a consistent log-in option at the top-right of most if not all pages. Closing.
