### ISSUE TITLE
VC boundaries shapefile for map

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#203]
Provide VC boundaries shapefile as an option on map (ideally both British and Irish). (Although I note that the Irish ones are occasionally being updated as they are perfected).

**Comment by kitenetter** [comment]
@sacrevert I realise you raised this issue a long time ago! Was the request for VC boundaries to be a layer that can be added to the verification page map, or was it for another map? (I think it would be a useful addition to the verifiers' map, if there is no performance cost.)

**Comment by sacrevert** [comment]
I think it was actually for the data entry page, but no doubt it is useful if multiple places.

I wonder if this issue also has relevance to that discussion about records overlapping VC boundaries?

**Comment by kitenetter** [comment]
Yes, we need to put some thought into the overlap issue, will re-visit that.

For the current issue, the action required is:
- Enable VC boundaries to be added to maps via the blue "+" symbol, as long as this does not result in performance issues

**Comment by johnvanbreda** [comment]
To avoid performance issues, my suggested approach would be to use GeoServer to serve up a WMS. This can point to a query against the locations table in the warehouse, or possibly a SHP file. The point is that loading all the boundaries as vector geometry onto the map is likely to be too much data.

**Comment by burkmarr** [comment]
@kitenetter @johnvanbreda 
Notwithstanding that I have some work to do on the VC layers boundary (Irish buffers and general data check), I have set up a WMS layer on VC boundary data on the dev server and configured the casual entry page to use it: http://test.brc.ac.uk/irecord_dev/enter-casual-record. The issue I have with this is that it is switched on by default and even if I switch it off, the next time I visit the site it is on again. Have I overlooked a configuration option?

**Comment by BirenRathod** [comment]
@burkmarr 
May be you can add URL of VC layer in "Additional WMS Base Layer Service URL" instead.

**Comment by burkmarr** [comment]
@BirenRathod That would make it an alternative base layer instead of an overlay that you can put on top of a basemap though.

**Comment by johnvanbreda** [comment]
@burkmarr I suspect the code that saves the currently selected base layer to a cookie in indiciaMapPanel doesn't do anything with the other layers you add. So their status will always revert on reload. This might well need to be changed.

**Comment by burkmarr** [comment]
Shall I take a look at that @johnvanbreda?

**Comment by johnvanbreda** [comment]
Sounds like a good plan @burkmarr .

**Comment by burkmarr** [comment]
A WMS layer is created on live warehouse geoserve: https://warehouse1.indicia.org.uk/geoserver/iRecord/wms?service=WMS&version=1.1.0&request=GetMap&layers=iRecord%3AVice%20County%20Boundaries&bbox=-10.398834458001643%2C48.87116669998501%2C1.8447784432829595%2C60.910630660459226&width=768&height=755&srs=EPSG%3A4326&format=application/openlayers

Waiting for incorporation of code to remember WMS display choices between sessions before making available on iRecord.

**Comment by BirenRathod** [comment]
@burkmarr 
It would be good if stores have been created in indicia workspace instead, so it could be use on other sites too.

**Comment by burkmarr** [comment]
Okay @BirenRathod I'll sort that.

**Comment by BirenRathod** [comment]
@burkmarr 
Thanks.

**Comment by burkmarr** [comment]
https://warehouse1.indicia.org.uk/geoserver/indicia/wms?service=WMS&version=1.1.0&request=GetMap&layers=indicia%3AVice%20County%20boundaries&bbox=-10.398834458001643%2C48.87116669998501%2C1.8447784432829595%2C60.910630660459226&width=768&height=755&srs=EPSG%3A4326&format=application/openlayers

**Comment by burkmarr** [comment]
@kitenetter @sacrevert - this is now implemented in irecord_dev and you can try it here: http://test.brc.ac.uk/irecord_dev/enter-casual-record.

**Comment by sacrevert** [comment]
@burkmarr nice one :)
I wonder whether anything you've done here could be used in the app? (Asked in total ignorance!)

**Comment by DavidRoy** [comment]
that an @kazlauskis question.  Not an immediate priority though

**Comment by DavidRoy** [comment]
@burkmarr look good to me.  @sacrevert - shall we deploy to the live site?
I'd never realised how much the Oxfordshire VC boundary swaps sides of the Thames, nor the kink at wallingford brigde

**Comment by sacrevert** [comment]
@burkmarr @kitenetter @DavidRoy
Is it odd to deploy this to the casual form without giving people the option to specify VC (as is available through the plant card e.g.)?

**Comment by kazlauskis** [comment]
@sacrevert yeah, we could add this to the plant-recording-mode of the app. At the moment, the user has to use a text input search with suggestions for VCs. If the user is offline or knows the VC then typing in `ox` for Oxfordshire and clicking on a dropdown suggestion is probably quicker than finding it on the map, so we should support both options.

**Comment by burkmarr** [comment]
@sacrevert it's a WMS layer served by the Warehouse Geoserver so could potentially be consumed anywhere. When code to remember overlay choices (currently only incorporated on irecord_dev) is incorporated into the live site, then the layer will potentially be available from any iform map that allows addition of WMS layers and I'll close the issue. To actually incorporate the map on any particular form, someone will need to edit the form on iRecord and specify that it's to be included. I only put did that for the casual single record form on irecord_dev because it was a convenient way to demo it.

**Comment by sacrevert** [comment]
Thanks. Anyway, I would prefer @DavidRoy to decide on how/where this is deployed. I suppose it is somewhat useful to see on the casual form, but would be more useful if there was the same VC choosing functionality as in the plant card. I think somewhere else we discussed how, so as not to put recorders who are unaware of VCs off, if a location straddled a VC boundary, then "don't know" would also be an option for choosing VC.

**Comment by burkmarr** [comment]
Merged to master. https://github.com/Indicia-Team/media/commit/4c46fb9ff4060074db1b25059b023e1c9f908830
