### ISSUE TITLE
Maps not displaying all records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#204]
Just tried to produce a map of Odontomyia argentata (Silver Colonel soldierfly), and I can only get a partial set of records to display, and it is partitioned differently in different places.

Via Summary details (http://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=62463):

![image](https://cloud.githubusercontent.com/assets/16039111/25565506/ef4ba9a4-2dbf-11e7-8da2-0e20569e9df1.png)

Via activity page - explore activity data (http://www.brc.ac.uk/irecord/activities/explore?group_id=350&implicit=):

![image](https://cloud.githubusercontent.com/assets/16039111/25565515/110fc0ac-2dc0-11e7-9744-448ee0f6b7e5.png)

Via Explore - all records:

![image](https://cloud.githubusercontent.com/assets/16039111/25565527/4be7959c-2dc0-11e7-9cad-8732541ac3e6.png)

**Comment by johnvanbreda** [comment]
I masqueraded as you and reproduced the difference on the species details map, but the other 2 are the same (they look like your 3rd image above). If you can explain exactly how to reproduce map 2 I'll take a look.

The difference on the species details page is this map is generated from the iRecord dataset only, it excludes the other sites which "share" data with iRecord. Perhaps this should be changed?

**Comment by kitenetter** [comment]
This is really odd. I can't find a way of reproducing map 2 now. But there are definitely records missing from maps 1 and 3, e.g. this one from Somerset (which is iRecord General data):
http://www.brc.ac.uk/irecord/record-details?occurrence_id=4857497

**Comment by johnvanbreda** [comment]
This link is for O. ornata, rather than O. argentata: http://www.brc.ac.uk/irecord/record-details?occurrence_id=4857497. Records do show in Somerset on the correct species details page.

**Comment by kitenetter** [comment]
Apologies @johnvanbreda, that was particularly daft of me. So the only discrepancy we are left with is that the species details page (e.g. http://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=62463) excludes non-iRecord records.

My view is that we ought to set the species details pages to show the same set of records as the "All records" page, i.e. species details should include all records for which there is agreement to share with iRecord. Does @DavidRoy agree?
