### ISSUE TITLE
Species-details page: photos and map should indicate verification status

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#205]
e.g. https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=22887

See iRecord forum post:
https://www.brc.ac.uk/irecord/node/4523

Actions required are:
1. Photos to indicate verification status (preferred option).  Alternative is the ability to filter photos by verification status
2. Map symbols to be coded by verification status

**Comment by johnvanbreda** [comment]
Photos done in development code ready for next feature release. Still to do map symbols.
