### ISSUE TITLE
Error message from inviting user to join Activity

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#206]
Error message:

![image](https://cloud.githubusercontent.com/assets/16039111/25684958/4342eeac-305c-11e7-911a-ad2ac7748542.png)

**Comment by johnvanbreda** [comment]
@kitenetter I think Biren has fixed this and it can be closed?

**Comment by kitenetter** [comment]
Will double-check next time I invite someone. Closing in the meantime.
