### ISSUE TITLE
Editing text associated with auto-generated emails

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#209]
Is it possible for me to edit the text that gets sent out with auto-generated emails? If so, could someone point me in the right direction, or if not can I request that the following changes are made.

**Comments on your records:**
Underneath the heading “Comments on your records”, and above the column headings, please can we add this text:

> Please do not reply to this email – replies go to the iRecord email account and will not be seen by the person who has commented on your record.
> If you wish to reply to this comment, please click on the blue “Record ID” link below, which will take you to your record on iRecord, You can add your reply in the “Add new comments” box at the foot of that page.

![image](https://cloud.githubusercontent.com/assets/16039111/26147617/02f88268-3aec-11e7-8485-70f9412634ca.png)

**Record cleaner results:**
Underneath the heading “Record Cleaner results for your records”, and above the column headings, can we add this text:

> Please do not reply to this email – replies go to the iRecord email account and will not be seen by the verifiers. 
> This is an automatically generated message based on sets of 'rules' for checking records that have been developed by the national recording schemes. It does not imply that your records are being disputed, just that the record may be unusual in some way. The rules can help highlight data entry errors or records for which further information might be required, but final decisions on verification will be taken by the human verifiers who volunteer for the recording schemes active on iRecord.

![image](https://cloud.githubusercontent.com/assets/16039111/26147657/1bafa3b8-3aec-11e7-988e-3979aa8ca3d4.png)

**Verification results:**
Underneath the heading “Verification of your records”, and above the column headings, can we add this text:

> Please do not reply to this email – replies go to the iRecord email account and will not be seen by the verifiers. If you wish to respond to a verifier, please click on the blue “Record ID” link below, which will take you to your record on iRecord, You can add your reply in the “Add new comments” box at the foot of that page.

![image](https://cloud.githubusercontent.com/assets/16039111/26147684/303bda40-3aec-11e7-80f2-481a4ee01be9.png)

**Comment by BirenRathod** [comment]
@kitenetter , Is it possible to send me the URL of this page?

**Comment by kitenetter** [comment]
@BirenRathod I'm not aware of any URL associated with this, the images above are from the emails that get sent out.

**Comment by johnvanbreda** [comment]
@BirenRathod This would require a modification to the notification_emails warehouse module, to make the email output templateable.

**Comment by kitenetter** [comment]
Bumping this one up - is it quick to make the required changes to the warehouse module or is this a bigger piece of work that we'll need to schedule in at a later stage? @johnvanbreda @BirenRathod

**Comment by johnvanbreda** [comment]
It would take me a couple of hours to add the ability to set this text in a configuration file. Let me know if you want me to prioritise it.

**Comment by DavidRoy** [comment]
Yes, please assign as high priority

**Comment by johnvanbreda** [comment]
Now done
