### ISSUE TITLE
Problem with adding photos to species list form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#212]
A few forum posts on this issue:
https://www.brc.ac.uk/irecord/node/4540
https://www.brc.ac.uk/irecord/node/4538

Potentially browser-specific.

Users not able to attached photos to species list.  Description of problem:
The add photo button appears but when clicked disappears with no new window opening. The button then does not appear again even when trying to repeat the process. I have tried submitting the records and then editing them but with the same result.

**Comment by kitenetter** [comment]
After John fixed #208 I tried uploading photos via Firefox yesterday and it seemed to work fine, so maybe browser-specific as you suggest.

**Comment by BirenRathod** [comment]
Photo uploading works fine, but "Add image" or "Add media" button disappeared after clicking (-) link.

**Comment by DavidRoy** [comment]
I'll post to the forum asking for details of browsers affected and we'll then assess

**Comment by DavidRoy** [comment]
Closing for the time being
