### ISSUE TITLE
Save filters not working?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#215]
Ian Winfield reports that he can use the Explore menu to display records, and can apply filters to those records, but if he names and then tries to save a filter nothing happens - the pop-up that says the filter has been saved is not appearing, and the filter does not appear in his drop-down list for subsequent use.

I cannot replicate this on my computers, but Ian has tried it on IE on a laptop, and using Safari on a Mac, with the same lack of result in both cases.

**Comment by johnvanbreda** [comment]
I masqueraded as Ian on Safari on a Mac and managed to successfully save a filter for the bony fish group (which I've now deleted). So, I couldn't reproduce it either. Are you able to find out if there were any JavaScript errors on the page when Ian tries to save the filter?

**Comment by kitenetter** [comment]
Ian says that he is no longer experiencing problems with saving the filters - closing.
