### ISSUE TITLE
Map behaviour has changed

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#216]
On the Enter a list of records form, the Google map keeps defaulting to a blank area somewhere in the North Sea, apparently at grid ref NZ64066772:

![image](https://cloud.githubusercontent.com/assets/16039111/26428649/c86fd3cc-40da-11e7-8e12-9fd59d4ac3ff.png)

Makes data entry slow as you have to constantly zoom out to find where Britain is, and then zoom back in again to find the location you want. Previously the map has defaulted to whatever location was last used,

**Comment by johnvanbreda** [comment]
Fixed by https://github.com/Indicia-Team/media/commit/cce05676af718f872abfa77f221d46e835e7bea6
