### ISSUE TITLE
Irish 1km square grid refs occasionally stored with precision of 2000 metres

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#217]
As far as I can tell the users have picked a 1km square from the map, but the database has stored a precision of 2000 metres. This only seems to affect a small proportion of Irish records. In the soldierflies dataset there are just five records in this category, record IDs:
- 2055305 (iRecord | National Trust Bioblitzes)
- 672869 (CEDaR Recording | Ulster Folk and Transport Museum Mini-BioBlitz)
- 672868 (CEDaR Recording | Ulster Folk and Transport Museum Mini-BioBlitz)
- 672836 (CEDaR Recording | Ulster Folk and Transport Museum Mini-BioBlitz)
- 521355 (CEDaR Recording | Colebrooke)

**Comment by japonicus** [comment]
may relate to this issue https://github.com/Indicia-Team/warehouse/issues/136

**Comment by johnvanbreda** [comment]
Warehouse fix deployed.
