### ISSUE TITLE
Output grid ref for Channel Islands gives lat/long

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#218]
Records located using projection UTM30ED50 in the Channel Islands provide a grid reference in the "Grid ref" download column, and lat/long coords in the lat/long download columns, but the "Output grid ref" column displays lat/long coords. It would be more helpful if the "Output grid ref" always contained the grid ref, not any lat/longs.

**Comment by johnvanbreda** [comment]
Duplicate of #243
