### ISSUE TITLE
"admin, core" requests to join Activities

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#219]
Why do I occasionally get requests from "admin, core" to join the Activities I have set up? Should I approve such requests?

![image](https://cloud.githubusercontent.com/assets/16039111/26720019/8ca23358-477e-11e7-86f3-4865039b84ae.png)

**Comment by johnvanbreda** [comment]
I wouldn't worry - the one that happened this morning was a result of me trying to test the layout on the join up page, so they are probably all just the results of testing.
