### ISSUE TITLE
Guidance on how to select the map boundary

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#221]
It took me a while to understand how to use the drawing tool in the map toolbar when drawing a boundary to find intersecting records. Looks like you need to double click it to finish the boundary, I was clicking 'Apply' instead.

I think this could be improved by adding a few words to mention the double-click.

**Comment by kitenetter** [comment]
The double-click is now mentioned in the tool-tip and the Help page.
