### ISSUE TITLE
Activity edit page - name lookup is not unique

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#225]
On the admin editing/setup page (e.g. https://www.brc.ac.uk/irecord/activities/edit?group_id=185) when selecting a activity administrator, the names returned are not unique (e.g. search for 'Roy, David' returns multiple accounts).  We require a way to uniquely identify user accounts, but not by revealing full email addresses.  Would welcome suggestions of potential solution.

**Comment by kitenetter** [comment]
I think the only suggestion we came up last time this was discussed with was to display both the 'real' name (surname + firstname), and the registered user name. That doesn't guarantee a unique match but would help reduce the potential for duplicate names.

**Comment by JimBacon** [comment]
The list of warehouse usernames looks like David_Roy_1, David_Roy_2, David_Roy_3, ...
Usernames are guaranteed to be unique but I'm not sure how much this helps as people typically don't know their usernames as they are automatically allocated.
Drupal usernames  are also unique but are often email addresses although a user can find and change this.

**Comment by kitenetter** [comment]
@DavidRoy also suggests including the iRecord user ID in the name string displayed, which would be unique.

@JimBacon it was the Drupal user name that I was thinking of, i.e. the name that you choose when registering on iRecord, but you are correct that many people who register via an app end up with their email address as their user name, so we hit the same problem as with exposing the stored email address.

**Comment by DavidRoy** [comment]
What about adding warehouse user ID to the name, plus creating a user-profile page and encouraging people to give some background details which they are happy to share and which would help identify them.  User profile page could also include summary recording stats?

**Comment by BirenRathod** [comment]
Yes, for user profile page, we could add field like type_of_user, So user will appear like DavidRoy ->irecord_website, david_roy_1 ->irecord_app and so on. again if there are two users created for same purpose than user might need to add bit more information to distinguish them.
Warehouse user ID has already added to the profile page, but IDs are not easy to remember.

**Comment by JimBacon** [comment]
Middle initials plus affiliation?
E.g.
 - David B. Roy, CEH.
 - David B. Roy, Personal.

**Comment by DavidRoy** [comment]
That would work.  Would it need an extra field in the user registration or could this be derived in another way?  I also think the warehouse id could be useful e.g. 
David B. Roy, CEH. (5)
David B. Roy, Personal. (325)

**Comment by JimBacon** [comment]
Possibly you could extract something from a .org, .ac or .gov email address to infer an affiliation but I am uncomfortable with that, On the one hand it is a bit limited and, on the other, it might expose information that a person might not want public. An extra field I think.

Initials could be squeezed in to the first name field but then you might get an email starting Dear David B. Also better as extra field I think.

**Comment by DavidRoy** [comment]
Thanks.  I recommend two things.
1. An immediate change to add the warehouse ID in brackets after the namestring.  This at least allows uniqueness even if little or no use to general users.  When this is done I suggest this issue is closed. @JimBacon can you do this?

2. Separate issues raised for:
a: extended user profile to capture affiliation and middle name information.  Use this to extend name string for activities etc
b: create a publicly accessible user-profile page showing name, affiliation, summary recording stats, photo etc.  iNaturalist do this well.  See: https://www.inaturalist.org/people and http://www.inaturalist.org/people/srall

**Comment by johnvanbreda** [comment]
Couple of thoughts:
1) the solution we came up with last time this was discussed was to allow you to type in a known email address and click Add - iRecord will then lookup the user account for you. This obviously gets around the problem of being able to discover email addresses since it's up to you to type one in. This has already been implemented.
2) Implementation notes about the user profile extension - if we extend the Drupal user profile to support the iinitials and affiliation we also need to ensure that these details are mapped back into the warehouse database since the lookup is a search against the warehouse user list, not the Drupal user list. Or we'd need to change the search to work against Drupal instead. We could use the existing user view page in Drupal to present the user's profile - at the moment this is just the default view but we could use a module such as Display Suite to make it look very nice.

**Comment by DavidRoy** [comment]
Thanks.
1. I'd missed this but very useful.  
@johnvanbreda - Can you add some help text to the activity edit/setup page to cover this.
@kitenetter - can you add something about this to the activity setup help page
2. I'll add a new issue to cover this requirement

**Comment by johnvanbreda** [comment]
Reopening as still to:

* add some help text to the activity edit/setup page to cover this.
* append the warehouse user ID to the namestring so that they are unique

**Comment by kitenetter** [comment]
Have added a brief note to the Help page, see point A.8 here:
https://www.brc.ac.uk/irecord/make_activity

**Comment by johnvanbreda** [comment]
ID added to looked up names as suggested, in develop branch ready for next feature release.
