### ISSUE TITLE
Inconsistency in Common Name between Grid and Record Detail

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#228]
If the recorder chooses from the species list a common name "Large Red Damsel" and the new record is saved, this name is then shown in the **Record Detail** but the name "Large Red Damselfly" is shown in the **grid**.
Is this a case of converting the user's choice to "Pyrrhosoma nymphula" and then displaying the _preferred_ common name "Large Red Damselfly" in the grid? This is confusing. Could the field name in **Record Detail** be changed to "Species, as entered by the recorder" and a separate field show the preferred common name?
It would be really helpful if the preferred common name could appear in lists first. In this case, "Large Red Damsel" sorts before "Large Red Damselfly" so is more likely to be picked and perpetuates an archaic common name.

**Comment by johnvanbreda** [comment]
We store the original name as entered. This can then be used to map to the preferred name or preferred common name for output purposes, so in effect we can accept any name then have full control over which name is included in each output.
Questions (perhaps for @kitenetter to confirm):
1) In the Explore page table we currently output the preferred latin name and the default common name. Is this correct? Do we need the "name as entered" as an additional column? (Personally I'm not sure there is space).
2) On the details page, the title currently shows the name as input by the recorder, with the preferred name shown in the list of fields if different. My proposal is:
  * Page title = name as input by the recorder, plus the preferred name in brackets if different.
  * In the list of fields - output the preferred name first. Output the common name next if there is one. Output the name as entered by recorder as a third name field.

Any thoughts?

**Comment by kitenetter** [comment]
@johnvanbreda my opinion is that the Explore page table columns are sufficient, and that adding a "name as entered" column would be confusing and consume too much space in that context.

By "record details" do we mean the main block of data when viewing an individual record page, such as this Wasp Beetle: https://www.brc.ac.uk/irecord/record-details?occurrence_id=3315957 ?

If so then I agree with your suggestions re page title and having three clearly labelled fields for the three types of name - would this work for you @DavidHepper?

Do we have a mechanism for encouraging users to select the preferred vernacular name (e.g. "Large Red Damselfly" gets offered before "Large Red Damsel", or even "Large Red Damselfly" as the only default option), or is that a limitation of UKSI not flagging preferred vernaculars?

**Comment by johnvanbreda** [comment]
I've updated the develop branch to update the page title and output the additional name details as described on the record details page. It will be deployed next time we do a feature release.

**Comment by DavidHepper** [comment]
@kitenetter : yes, I'm happy with the proposed changes, thank you.
