### ISSUE TITLE
Issues with downloads

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/iRecord#229]
From laptop using chrome and explorer when tryign to download a dataset the filters are not working they have blank drop down menus or nothing happens at all when you click on them (this also applies to selecting the recording method/form type e.g. 'iRecord>Moth records'. This means can't currently download datasets which is important because need to send some datasets to CMR's for new moth atlas fairly sharply.

**Comment by BirenRathod** [comment]
dropdown list has got problem to get list if survey/site name has got single quote.

**Comment by DavidRoy** [comment]
Thanks.  @marcbotham as a quick fix you could edit your filter names?

**Comment by BirenRathod** [comment]
No need to change the filter name. I implemented the code and send it to @johnvanbreda for review.

**Comment by marcbotham** [comment]
Ok but I have lots, one for every site I’ve recorded more than casually at. But hopefully not many will have the character issue. Thanks, marc

**Comment by BirenRathod** [comment]
As I mentioned, no need to change the site name. I have change the code and placed on to live site.

**Comment by johnvanbreda** [comment]
Now properly deployed to live site.
