### ISSUE TITLE
Enable upload of video/sound files

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#23]

**Comment by johnvanbreda** [comment]
- Does this need to be on all forms or just specific ones?
- Do we want to support upload of video (huge/slow) or just links to Youtube, FB, Vimeo etc?
- Sound files can also be uploaded or linked to Soundcloud.

**Comment by johnvanbreda** [comment]
Just to make sure this is clear - Indicia supports this now and we just need to configure specific forms by adding an option called @mediaTypes. The bat recording form shows an example.

**Comment by kitenetter** [comment]
@johnvanbreda @DavidRoy we've had another request to make the upload of sound files more widely available on iRecord. Are there performance or storage implications in doing so?

**Comment by kitenetter** [comment]
The discussion is here:
https://irecord.org.uk/forum/feedback-and-suggestions/sound-files

where it is suggested that we have a "brutal" limit on the file size for bat sound files, so presumably we are able to impose a limit on the size that can be uploaded?

But if we were to make this generally available on the main recording forms I think that people would be likely to want to upload potentially very large files, and while links to soundcloud would be an option for technically confident users I suspect that others would find that tricky to manage. But we obviously have to be realistic about storage so I'm not suggesting that we offer unlimited upload size.

**Comment by johnvanbreda** [comment]
Do you think we can enforce mp3 file format? It's significantly smaller than wav.
