### ISSUE TITLE
entering spatial reference in activities

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/iRecord#230]
when using an activity such 'Moth recording form' to enter records when you go to add location data you cannot search for a place. Entering a place name to search for does not work. In main iRecord recording pages this still works fine - you gte a drop down menu of auto-complete place names as you start typing in a place name and then when you press search it works fine. If you don't know th grid reference and use these forms then you have to go into a different software or website to find the grid ref to export it which is pretty frustrating.

**Comment by DavidRoy** [comment]
@BirenRathod can you look at this please

https://www.brc.ac.uk/irecord/enter-moth-sightings

**Comment by BirenRathod** [comment]
The georeference setting has implemented now. Value set to Google search,
