### ISSUE TITLE
species name codes

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/iRecord#231]
the codes which use first two letters of genus and first three letters of species name are not all working. There are many that simply don't bring anyhting up to select. An example is Cabera exanthemata. If you type in caexa you find nothing. So you either have to type in long hand common or binoial name. these shorthand codes are so useful when typing in long lists, they really save time.

**Comment by DavidRoy** [comment]
This works if you put a space between genus and species, e.g. 'ca exa'?

**Comment by marcbotham** [comment]
Oh that's weird. You don't do that for any of the other codes. Presumably just a space has accidentally crept in there?


Dr Marc Botham
Butterfly Ecologist
Centre For Ecology and Hydrology Wallingford
Maclean Building
Benson Lane
Crowmarsh Gifford
Wallingford
Oxfordshire OX10 8BB

telephone
Office: 01491 692437
Mobile: 07779 599996

email
Office: math2@ceh.ac.uk
Home: bgymsb@gmail.com


________________________________

**Comment by DavidRoy** [comment]
One for JvB to investigate

**Comment by kitenetter** [comment]
Possibly related to the ongoing problems with names/abbreviations that contain "ae"? #116

**Comment by johnvanbreda** [comment]
Yes, this relates to the ae search issue. I've fixed it in the code and will release it during the next feature release (which I hope to do today or Monday).

**Comment by johnvanbreda** [comment]
Fixed and deployed
