### ISSUE TITLE
species names and synonyms

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/iRecord#232]
I appreciate that in the app this cannot be done as species lists need to be as short as possible but in the main iRecord website it should be possible to find a species using a synonym. Names continually change and it is hard to keep up with it and sometiems difficult, if you don't know the new name, to find out what it is. For example, Chloroclysta truncata (Common Marbled Carpet) is now Dysstroma truncata. If you type in the old species name you do not even get Common Marbled Carpet as a choice. It doesn't even show what the new genus name is so then you have to search the internet to find out or type in the awkward long common name. Ideally the option to select a synonym should be available with the correct species name as what shows up in records. this would also help people to start learning the new species names. currently this is very frustrating

**Comment by DavidRoy** [comment]
@johnvanbreda @kitenetter I can't remember the reason for not allowing synonyms within the standard entry forms

**Comment by marcbotham** [comment]
I do remember Martin explaining actually so sorry for raising this again. I too can't remember the reason. I feel there needs to not necessarily be all the synonyms under the sun, but a kind of grace period of maybe 2 years after a name change that allows the most recent synonym to be used during the switch over - if that makes sense?


Dr Marc Botham
Butterfly Ecologist
Centre For Ecology and Hydrology Wallingford
Maclean Building
Benson Lane
Crowmarsh Gifford
Wallingford
Oxfordshire OX10 8BB

telephone
Office: 01491 692437
Mobile: 07779 599996

email
Office: math2@ceh.ac.uk
Home: bgymsb@gmail.com


________________________________

**Comment by kitenetter** [comment]
If you are using an "Enter a list" type of form, you can choose to set it to show synonyms. Have added a Help page to explain how to do this:
https://www.brc.ac.uk/irecord/help-species-names

As far as I know you can't switch to using synonyms if you are using the "Enter a casual record" form.

I agree with Marc that in an ideal world it would be good to have a cleverer way of dealing with recent name changes.
