### ISSUE TITLE
app: names missing

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/iRecord#233]
still names missing from species list in iRecord app - e.g. Peacock. This finds nothing, neither the buttrfly or the bird, or in fact the moth. To enter a record of Peacock you have to know the exact current binomial. Some species appear to be missing altogether e.g. Bombus pratorum. This means you have to make a paper record of these species and use the website when get home or get internet signal in order to make these records. I don't know a quick way to find out all the species that are missing as there could potentially be lots. I only use the app minimally and I have found several from the limited number of species I have tried to find.

**Comment by DavidRoy** [comment]
closing as covered by:
https://github.com/NERC-CEH/irecord-app/issues/108
