### ISSUE TITLE
Memory error after 100+ verifications

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#234]
@BirenRathod @JimBacon I am getting reports of someone who tried to do 100+ veirifications on iRecord and got the following error. I have seen this kind of error before, but usually only during development when some kind of loop has gone wrong and is gobbling up memory.
Will email you the user's name in question privately.

Fatal Error – allowed memory size 2000000000 bytes has been used up, tried to allocate 20000 bytes

**Comment by BirenRathod** [comment]
Interesting to know. This means we have allocated 2GB memory is not enough. We need to consider to allocate more memory. How much more we could allocate? Have you thought about it? Let me know, if that is a requirement. @johnvanbreda, @andrewvanbreda, @Gary-van-Breda, @JimBacon, @DavidRoy

**Comment by JimBacon** [comment]
2GB is a vast amount of memory to be using. I would prefer we investigated the code a little bit to see if we can work out whether anything bad is going on. Do we have more information about the method this person was using to do their 100+ verifications?

**Comment by BirenRathod** [comment]
@johnvanbreda, @andrewvanbreda, @Gary-van-Breda, @JimBacon
Although this felt more sensible answer to me -> https://stackoverflow.com/questions/561066/fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter-xml

**Comment by johnvanbreda** [comment]
I agree with Jim - 100+ verifications shouldn't use 2GB of memory. We should find out why as there may be a bug or some extremely inefficient code.
Therefore we need details on how to reproduce this.

**Comment by andrewvanbreda** [comment]
I will ask to see if we can get more details from the verifier, although I am not sure how easy it will be to get hold of the verifier. I would be interested to know if the verification went through even though there was an error.
If the verification didn't happen and are still waiting to be verified we might be able to masquerade as the user and try what they did

**Comment by andrewvanbreda** [comment]
Have now requested more information on this, that will get posted here if I get any further info.

**Comment by andrewvanbreda** [comment]
I have received more information regarding this..

-Problem occurred around Feb 2nd when  bulk verifying records

-When the user tried to close his computer it said it was in the middle of a download

-After about an hour and a half it was still running this, so the user forced it to close

-Then in June the user was verifying about 200 records, when he tried to bulk verify some it came up with this error…
Allowed memory size of 2147483648 bytes tried to allocate 20480 bytes in D:\website\warehoure\system\libraries\drivers\database\pgsql.phh on line 426

-Now the user can only verify a few records but can’t bulk verify without getting the error message
<div class = “error2>cUrl POST request failed. Please check cUrl is installed on the server and the$base_url setting is correct <br/> URL : http : // warehouse 1. Indicia.org.uk/index.php/services/data_urils?bulk_verify<br/> server response <br/> { “error”: ‘’general_errors

There is more of this message, but the user only sent the start of it

**Comment by johnvanbreda** [comment]
@andrewvanbreda Do you know who the user was and which records they were intending to bulk verify?

**Comment by andrewvanbreda** [comment]
I know the username I will email you it in a mo

**Comment by andrewvanbreda** [comment]
@johnvanbreda just wondering if anything has happened with this which I can report back to Pauline in Northern Ireland with?, even if you just tell me it is on hold.

**Comment by andrewvanbreda** [comment]
@JimBacon @BirenRathod @johnvanbreda 
Hi, just wondering if anyone knows if this was fixed? (or not fixed as the case may be). Any information would be useful for me to let Pauline now how we got on with this.
Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda 

I can't remember but I have increased the memory limit to 2048M, so it shouldn't be a problem.

**Comment by andrewvanbreda** [comment]
@BirenRathod OK thanks, I will report back it should be less likely to happen now, even if it isn't a fix for the verification for taking up so much memory

**Comment by johnvanbreda** [comment]
Closing as has not been reported since.
