### ISSUE TITLE
Adding families to existing verification filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#236]
We have some verification filters set up for micro-moth verifiers. These have to be set up by listing each individual micro-moth family. Currently the filters have c. 40 families listed, but there are now 50 families in the latest checklist and in UKSI.

As far as I can see it is not possible from within the iRecord filter admin page to add additional families to existing filters. Is there any other way of achieving this, e.g. via the underlying database? Or do I have to delete the existing filters and start all over again?

**Comment by johnvanbreda** [comment]
I've posted a fix to the code in the develop branch which fixes the report filters so that the families can be updated and resaved successfully when loading an existing filter. It will be deployed at the next feature update (which I am hoping to do soon).

**Comment by johnvanbreda** [comment]
Deployment of updated done.
