### ISSUE TITLE
Show a quickview of the record on a map

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#238]
Clicking or hovering on a record in the map view should show some more info about it (a soft dialog or something.).

**Comment by johnvanbreda** [comment]
Which page? On most pages there is a query icon in the corner of the map which either highlights the row or filters the associated grid.

**Comment by kazlauskis** [comment]
It would be great to shift the user focus to the map a bit more. I know you can click on the query icon and start selecting the records on the map but for a mobile device user, it would be a better experience to click on that record on the map and have some tooltip appear with the record's info. Rather than scroll down and check the record the focus would remain on the map. This in general, would benefit a desktop user as well.

**Comment by kitenetter** [comment]
The NBN equivalent shows:

![image](https://user-images.githubusercontent.com/16039111/36027563-bfe25122-0d93-11e8-8473-6376af9767db.png)

We'd need to add a species name, and the link would presumably go to the relevant "record-details?occurrence_id=" page. Don't think we need to show grid size.

**Comment by kitenetter** [comment]
I can see the benefit of this approach but it hasn't been requested recently. Closing for now.

**Comment by johnvanbreda** [comment]
Just to note that I've recently implemented custom code for Guernsey Biological Records Centre that does something similar in case it comes up again.
