### ISSUE TITLE
Algae images not in lightbox

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#239]
Goto https://www.brc.ac.uk/irecord/bloomin-algae-app-summary, switch to the trending tab and click on an image. The browser navigates to the image url rather than appearing in a lightbox.

Compare with https://www.brc.ac.uk/irecord/ladybird-app-summary which works.

**Comment by johnvanbreda** [comment]
@JimBacon The freeform report for the photos doesn't actually trigger the linking of the fancybox resource itself. On the ladybird summary there are report grids included in the user interface definition which do cause the fancybox resource to be included - therefore having the beneficial side effect of fixing the Fancybox behaviour on the freeform report. 

I think the best fix is to force the event_reports.photos_block extension control to include the fancybox resource. There is also a small issue of why the report grids defined on the ladybird summary are not appearing on the rendered page. If you want me to take this on then please assign it back to me.
