### ISSUE TITLE
Source filter error on explore all records

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#240]
Go to https://www.brc.ac.uk/irecord/all-records
Create a filter.
Select a Source website or survey and apply.
An error saying "The report did not load correctly appears."

**Comment by kitenetter** [comment]
I had this issue yesterday when using Chrome, but it seemed to be working okay in IE.

**Comment by BirenRathod** [comment]
It doesn't work for jQuery 1.10. This is not kind of things people to experience,So moved it to 1.8.

**Comment by johnvanbreda** [comment]
I've commited a proper fix to this for jQuery 1.10 (since I am supporting D8 on a few sites now).
