### ISSUE TITLE
Name change request in species dictionary

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#241]
Alan Stewart has requested a name change in the dictionary (we'll try to get this done in the UKSI as well, but it would be helpful to change it in iRecord in the short term).

If you enter a record into iRecord and just type in "Leafhopper" the only choice you are given is a vary rare and hard-to-ID species, Anoscopus duffieldi. This is because the UKSI has the English name "Leafhopper" linked to the recommended name Anoscopus duffield, and not to any other hoppers:
http://nbn-sd-dev.nhm.ac.uk/taxonbrowser.php?txtSearch=leafhopper

Alan would like to remove the link between "Leafhopper" and Anoscopus duffieldi, but I'm not sure how best to achieve this, given that there will be existing records for which the name entered was "Leafhopper" (most of which will have been rejected or redetermined).

Can just remove the English name "Leafhopper" so it no longer appears for data entry? Or can we retain the name but link it to family Cicadellidae (instead of species Anoscopus duffieldi)?

**Comment by johnvanbreda** [comment]
Ok, I think I should:
* Change the taxon_meaning_id for the leafhopper common name entry to match Cicadellidae instead of A. duffieldi. 
* Change the updated on for Cicadellidae (plus any synonyms or other common names) and A. duffieldi (plus any synonyms or remaining common names). This will force all records to update - any records entered as Leafhopper will point to Cicadellidae and any records of A. duffieldi will lose Leafhopper as the common name.

Is that OK? I would be keen to hear that Chris has agreed this so we don't reintroduce this in future.

**Comment by kitenetter** [comment]
Chris has just made the change at the UKSI end - he said:
"Well spotted - I have made that change, to Cicadellidae. I think these odd common names came in on old checklists where a descriptive term was misinterpreted as a vernacular name :)"

**Comment by johnvanbreda** [comment]
Done. It will take a few minutes for the change to ripple through. For reference, here's the script (the first query was to check the data, the next 3 make the change):
```

select cttl.id, cttl.taxon_meaning_id, cttl.default_common_name, ttl.taxon_meaning_id, cttl.taxon, cttl.preferred, cttl.external_key, t.id as taxon_id, t.external_key, t.search_code, ttl.taxon_meaning_id
from cache_taxa_taxon_lists cttl 
join taxa_Taxon_lists ttl on ttl.id=cttl.id
join taxa t on t.id=ttl.taxon_id
where cttl.taxon_meaning_id in (20956,175563)

update taxa_taxon_lists set taxon_meaning_id=20956 where id=197470;
update taxa set external_key='NHMSYS0020475498' where id=197470;
update taxa_taxon_lists set updated_on=now() where taxon_meaning_id in (20956,175563);
```
