### ISSUE TITLE
Data Downloads - Vice County

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#242]
Vice County issues picked out from umbrella issue https://github.com/BiologicalRecordsCentre/iRecord/issues/74.

**Vice county**
This is an essential field for many recording schemes, but currently is much less helpful than it should be:

* it sometimes includes the ‘pseudo-vice-counties’ of Yorkshire or Sussex
* it is sometimes left blank
* the vice-county names used are not standardised with other systems, nor with the list of vice-counties on the BRC website
* the VC number is not given

Suggested solutions:

* Can we remove all references to the two pseudo-vice-counties?
* Can we run a database update to ensure that all records have a vice-county allocated to them where appropriate?
* Can we edit the list of vice-county names to make them more compatible with other lists (and if we do will that cause problems elsewhere, e.g. with the verification filters)? (Problem: there doesn't seem to be much consensus on what the correct names are!)
* Add an additional column that gives the vice-county number (which is much easier to work with when collating with other external data) [if we do this the issue of non-standard VC names become less pressing]

**Comment by japonicus** [comment]
What method would be used to assign counties to ambiguous records (those where a grid-square spans a boundary), or would those records be left without an assigned county (which might be preferable).  If the wrong county were to be assigned then this could be misleading.

I'm keen that a distinction should be drawn between counties that are assigned by the recorder v's those assigned by automated means.  The reason for this is that matching vice-county with grid-reference can be a really useful validation method to catch grid-reference errors - this obviously fails if the assigned VC has been silently inferred from the grid-ref.

It would be really useful to have a numeric vc column in exports.

**Comment by johnvanbreda** [comment]
I've reviewed the state of the data with respect to the combined Yorkshire and Sussex vice counties. There was an update to the spatial indexing code in early June and all the records which are linked to combined counties fall before this date. The current code seems correct and produces the expected results so I hope this issue is fixed going forwards. I've also run some queries to update the existing data to point to the individual vice counties.
I've also added the VC code to the download reports in the development branch of the code so you will get that change with the next feature update.

Updating the existing VC names should be OK as they are just stored as IDs in the filters, except when you load an existing filter it may cache the old name - it will still work though.

@japonicus ambigous records are assigned to the VC with the greatest overlap which was requested by David and the BDS verifiers - otherwise records fall down the gaps for verification. I agree with the distinction between recorder assigned and automated VC links which we already have and intend to keep.

I just checked a random selection of records with no vice county assigned, they were all either in the sea, on the continent or in Ireland. @kitenetter do you know of any records without the vice county assigned that should have it?

**Comment by kitenetter** [comment]
I've just tested 1,575 records between ID 10475 and ID 5361197 - none of them have missing VCs, which is excellent! WIll report back if any more problems emerge.

Closing.
