### ISSUE TITLE
Data downloads - output grid ref

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#243]
Output grid ref issues picked out from umbrella issue #74.

This is mostly working well but for records outside the UK (including from the Channel Islands) this column is being populated with lat/longs. Since lat/longs have columns of their own, they don’t need to appear in the Output grid ref column. For the Channel Islands, it would make more sense to use the Channel Islands grid ref for the Output field, while for other overseas records Ouput grid ref should be blank.

Additional comment by JVB 7/6/17: 

> Minor point - I am not sure I agree with leaving the output grid ref empty when only a lat long available (i.e. outside a supported grid system). As it is now, you can include this column in any report or view of the record and it should give you the "best available representation" of the map reference. You don't need to have special code that grabs the entered map reference if the output map reference is empty to do this.
> 
> In relation to the last comment above, I suggest calling the 2 columns "Original map reference" and "Output map reference" which should make their purpose clear.
> 
> Any thoughts @kitenetter?

Reply from DR 7/6/17

> I'm not sure if this is related to John's last comment (about leaving output grid empty for lat/long records), but a view has been expressed (e.g. by some LERCs) that it is awkward having grid refs and lat/long spatial locations stored in the same column of downloads.

**Comment by johnvanbreda** [comment]
I've implemented the channel islands WV format in output_sref for the appropriate records. 

As mentioned above - I don't really agree with the viewpoint that the output sref should be null if not one of the supported grid references. The idea here is to provide a reporting label that can be shown for all records which gives the best localised version of the map reference that Indicia knows how to generate - a "display label". If it can be null then reports will need special handling to find an alternative label in these cases. Surely anyone trying to process this field could skip it if in lat long form?

**Comment by kitenetter** [comment]
I think the problem arises when data from iRecord is imported into other systems that only use British or Irish grid refs. The output sref field is by far the best one to use as it contains most spatial refs in grid ref format. But the grid ref field in external systems is a text field, so it will quite happily import any lat/long data from the output sref field and present it as an odd-looking, but not invalid, grid ref.

When importing into external systems, there is no easy way to exclude records with lat/longs in the output sref field other than manually searching for them, or building in code to strip out 'grid refs' that don't start with a letter.

I can see the benefit of always having the output sref populated with something, but for exchange with external systems it would be helpful to have an easy way of being able to filter out the lat/longs.

Is it worth considering an additional export attribute called "output sref format" that sits alongside "output sref" and states whether the output sref is "gridref" or "lat-long"?

**Comment by johnvanbreda** [comment]
That's a better idea. For consistency with the way the entered_sref & entered_sref_system fields are done, I'll add a field called output_sref_system which outputs the grid reference system name (OSGB, OSIE, utm30ed50 for Channel Islands) or projection EPSG code (4326, 27700 etc). This will be more useful than just saying it's a grid ref or lat long.

**Comment by johnvanbreda** [comment]
I've deployed code for the new output_sref_system field to the develop branch which will be deployed next time we do a feature release.
