### ISSUE TITLE
Don't lock the map on drag refresh

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#244]
It would be much better experience not to gray out and lock the map on its drag. When I am exploring my records then at times a bit of a map move/drag locks it with the spinning circle in the middle and for those 2-5 seconds, while it is trying to fetch new records I cannot see any of the current map view that I am exploring

I would show the loader somewhere in the corner and update the records on the map after the report has returned only.

**Comment by kitenetter** [comment]
@kazlauskis I'm not certain which part of iRecord you were referring to in the comment above. Is this still an issue?

**Comment by kazlauskis** [comment]
The new map reports don't lock the view anymore. Closing this.
