### ISSUE TITLE
Data downloads - state

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#245]
State issues picked out from #74

At the moment we are only showing the old level 1 verification terms (Verified/Rejected etc.) We need to change this, or add to it, to display the new two-tier verification terms. Suggest having two fields:
Verification status: Accepted / Not accepted / Unconfirmed
Verification detail: Correct / Considered correct / Unable to verify / Incorrect / Plausible / Not reviewed

**Comment by johnvanbreda** [comment]
The record status field has already been updated as a result of https://github.com/Indicia-Team/client_helpers/issues/8 to include the substatus information. Please let me know if you still want this split into 2 fields.

**Comment by kitenetter** [comment]
Personally I would find it easier to have two fields, simply because it gives me more and easier filtering options (i.e. I can run queries for everything where "status 1 = Accepted", rather than having to remember to query for 'starts with' Accepted etc,). But perhaps that's just me - will see if I can get opinions from other users of the download process.

**Comment by johnvanbreda** [comment]
We currently have a "State" field which outputs the full descriptive label. What should the 2 new columns be called, e.g. 
Status + Substatus
State L1 + State L2
State + State detail
Status + Status detail
?

Also, for a plausible record, what should the top level be set to (this is a 2nd level status)? Options include:
L1=Plausible, L2=blank
L1=Reviewed, L2=Plausible

**Comment by kitenetter** [comment]
The way we've presented things in the verifiers' guidance doc is:

![image](https://user-images.githubusercontent.com/16039111/28358720-c5f68100-6c67-11e7-85d0-75eb4e7cce0d.png)

I'd be happy with sticking to that pattern, with "Plausible" as a second level subdivision of "Unconfirmed", but let me know if you think that misrepresents how we are handling the data in the database.
