### ISSUE TITLE
Data downloads - attr_biotope

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#246]
Biotope issues picked out from #74

Not currently getting populated. Do we need two columns to display the two tiers of habitat?

reply from JVB:
>  As far as I can see, it is populated where the system function is set to biotope for the attribute on the warehouse. However if you run the following query you will see there are many potential attributes that don't have their system function set:
> select * from sample_attributes where (caption ilike '%habitat%' or caption ilike '%biotope%') and coalesce(system_function, '') = '';
> Habitats can potentially be several levels deep, not just 2. Perhaps a generic change so that any hierarchical termlist attributes are output with their ancestry in the reporting cache tables (used to populate the downloads), e.g.:
> "Grassland >> Dry grasslands including chalk downland"

Reply from DBR:
> @kitenetter - can you set the system function for relevant habitat attributes. I don't see any reason not to
> @johnvanbreda I would support the generic change of using a standard notation for multi-values for attributes

**Comment by kitenetter** [comment]
Have set system function for "iRecord general" survey, will test and report back.

(Re multi-values, personally I always find multiple columns easier to deal with than concatenations of hierarchies into a single column, but given the complexity of habitat terminology I think the concatenation option is probably the best solution.)

**Comment by johnvanbreda** [comment]
The attr_biotope field is being populated for new records in iRecord general data, but not ones before you made the change (the script to update the entre cache would be too slow to run via the UI). I'll have to run a manual script when the system functions have been set. Rather than do this twice, I suggest you set the system functions first, then when I apply the change to create hierarchical information in the attribute output I can get it to also update the biotope data generally in one go which will be more efficient.

**Comment by johnvanbreda** [comment]
I've updated existing blank data with the following script:
```sql
update cache_samples_nonfunctional snf
set attr_biotope=case when a.data_type='T' then v.text_value else t.term end
from sample_attribute_values v
join sample_attributes a on a.id=v.sample_attribute_id and a.deleted=false and a.system_function='biotope'
left join cache_termlists_terms t on t.id=v.int_value and a.data_type='L'
where snf.attr_biotope is null
and v.sample_id=snf.id and v.deleted=false
```

Still need to implement a hierarchical biotope labelling output.

**Comment by kitenetter** [comment]
@johnvanbreda I think we can close this one?

**Comment by johnvanbreda** [comment]
@kitenetter It's needed if you want the biotope attribute output in reports to show the parent levels of a hierarchical classification. If you are happy with the current behaviour which just shows the "leaf" term then it can be closed.

**Comment by kitenetter** [comment]
I'm not aware of any pressing need for the parent levels. Closing for now.
