### ISSUE TITLE
Sref wrong when editing glow-worm records

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#247]
When editing a record associated with a location (from the locations table), the spatial reference of the location centroid is displayed rather than that of the record e.g. https://www.brc.ac.uk/irecord/glow-worm?occurrence_id=5363153. I only see this affecting the glow-worm form though

Perhaps as a direct consequence, the map zooms to the location rather than the record e.g. https://www.brc.ac.uk/irecord/glow-worm?occurrence_id=5362569 which adds to confusion.

**Comment by johnvanbreda** [comment]
Now fixed. The code which causes a chosen location to load it's centroid into the sample entered sref control is enabled on this form. However the code should not really apply during initial load of the form, only subsequently.
