### ISSUE TITLE
Data downloads - date

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#248]
Date issues picked out from umbrella issue #74.

It’s very difficult to use the downloaded Date field consistently at the moment because it includes vague dates. We need three columns:

Date
Date to
Compiled date (i.e. the column we currently have that mixes vague dates and single-day dates – this may be easier for some users who simply wish to display the data, but the two separate Date and Date to fields are needed for use with external databases)
I would also prefer the date columns to appear earlier in the sequence of columns than they currently do (see below for reordering).

**Comment by johnvanbreda** [comment]
I've:
* Included the date from and date to fields in the download report outputs
* Renamed date to interpreted date
* Applied a general fix so that the vague date output column is in it's intended position in the columns list rather than added as the last column.
These changed will be deployed at the next feature release.

**Comment by kitenetter** [comment]
Excellent, thanks, can't wait!

One other question that has only just occurred to me: should we also include a column for date type, e.g. to facilitate import into Recorder and other systems that use the old NBN formats?

**Comment by johnvanbreda** [comment]
I think that's a question for you - are other people asking for this? It's easy to do.

**Comment by kitenetter** [comment]
If it is easy to do I think we should do it, it will be helpful for some users and can be ignored by those who don't need it.

**Comment by johnvanbreda** [comment]
Date type has now been added.
