### ISSUE TITLE
Inconsistent species totals in activities

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#25]
Using DUMP activity as example: Summary tab says 46 species; Species tab says 62 species. I'm guessing that the two tabs handle higher taxa differently, but there are also issues with different versions of the same species name (e.g. with or without subgenus). Maybe this is an issue for the UKSI, but it would be nice to make the stats on iRecord more meaningful and consistent if we can. I've just checked the soldierflies activity, and on the Species tab it has many species listed in triplicate for no apparent reason (scientific and English names are identical).

**Comment by johnvanbreda** [comment]
The main problem here was the fact that the same species appears on UKSI and the NatureSpot checklist with variations in how the name is written (e.g. subgenera). I have changed the species report so it always maps names back to UKSI and this has fixed the counts for the DUMP & Soldierflies summaries so they match the totals on the front tab. 
Some points:

- This changes means that any taxa not on UKSI will not appear on the species tab for any activity summary. Probably not an issue but might be e.g. if a group uses a custom warehouse checklist.
- Currently we are actually counting taxa not species. We only use the word species really to avoid introducing new terminology. We could filter out higher taxa fairly easily, but this would be slightly complicated when handling subspecific taxa as we really need to map from any subsp up the hierarchy to species level to do the counting, which could be a bit slow (or require optimisation work).

**Comment by DavidRoy** [comment]
I think this is a good improvement.  I would favour restricting to species or lower taxa, as the 'taxa' count is labelled as 'species'.

As an aside, I also wonder if we should standardise summaries by UKSI taxon groups.  This would exclude associated surveys/websites that do not match their taxon groups to the UKSI (e.g. NatureSpot primarily).  Perhaps a new issue to discuss this?

**Comment by johnvanbreda** [comment]
I've now mapped the species list and taxon groups list reports used on the summaries and explore pages for activities to UKSI for the output, hopefully fixing most of this issue.
Still need to do the rank filter...

**Comment by kitenetter** [comment]
John, the above changes all sound very positive. However, at least some of the Activities are still displaying UKSI and NatureSpot taxon groups as two different things in the Activity summary pie-charts, e.g.:

![image](https://cloud.githubusercontent.com/assets/16039111/16748034/b53910d6-47b9-11e6-9927-067c90ef4e4b.png)

Is there a way of either combining the taxonomies, or restricting the pie-charts to the UKSI totals?

**Comment by johnvanbreda** [comment]
I've mapped the groups to those used in UKSI so you only get insect - beetle (coleoptera). The reports now only include species level or lower as well.
