### ISSUE TITLE
Any user can edit public locations

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#252]
It appears that there is no permission check to restrict the editing of public locations.

E.g. masquerading as a simple user I appear to be able to make changes to https://www.brc.ac.uk/irecord/my-site-details?location_id=1120

I haven't tried saving a change as I don't want to corrupt any of these locations.

**Comment by kitenetter** [comment]
I've tested this including saving a boundary edit and Jim is correct that it is possible to edit sites created by other users. It appears that it would also be possible to edit one of the system-supplied boundaries such as an NNR.

**Comment by kitenetter** [comment]
We should tidy this up - adding to September milestone to discuss prioritisation.

**Comment by burkmarr** [comment]
This didn't just apply to public locations - any user could edit anyone elses sites. If made a pull request that changes the form so that map editing and form submission buttons are removed if the user does not own the location. https://github.com/Indicia-Team/client_helpers/pull/114

**Comment by johnvanbreda** [comment]
Now deployed and seems to work.
