### ISSUE TITLE
Data download - text codes in csv download

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#256]
Derived from umbrella issue #74 

Small addition to this issue. Strip out text codes (e.g. &#) from .csv download fields. Example is:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=4236774

Field value for 'Record comment':
A Male (same as yesterday's?)
gets translated to:
A Male (same as yesterday's?)

Other fields where this occurs are 'Record name', 'Site name' etc.

- Response from japonicus:

While I agree that html entities shouldn't appear in csv output, I think this reflects a problem with the data entry or import code rather than with the csv download view. The character entities should have been interpreted before being stored in the database - so that the raw database content is clean and doesn't contain entities.

There appears to be quite a widespread problem with character encoding at the moment. If using iRecord for data entry, no escaping of sensitive characters occurs at all - which makes it trivial to maliciously or innocently enter records that break html formatting or editing.

e.g. these two records on the dev website:
http://192.171.199.230/irecord7/record-details?occurrence_id=4338397
This displays correctly but the ' "A" ' in the recorder name in double-quotes means that that field is corrupted on the edit form (it truncates at the first double-quote)

http://192.171.199.230/irecord7/record-details?occurrence_id=4338396
demonstrates unescaped html. The example is obviously deliberate abuse, but similar behaviour could be triggered inadvertently just by including a less-than symbol in a comment - which would be quite reasonable to do innocently.

Both these records currently display correctly if exported as csv.

At the moment the iRecord mobile app stores escaped html (unlike iRecord) which means that the records display correctly on the website (without security holes) but if exported as CSV would contain html entities rather than the correct characters. I assume that the butterfly app that generated your example record also encodes entities.

I think the 'correct' behaviour would be to store unescaped html in the database but to escape content wherever it is displayed as html (so that character encoding is always a function of the view code - just as the csv view currently correctly escapes '"' characters).

**Comment by johnvanbreda** [comment]
By default Indicia does not encode the content stored in the database - that should be the responsibility of the output as @japonicus correctly stated. The iRecord Butterflies app is encoding saved content but I am not sure it is right to expect the CSV download functions to un-encode this content.
I couldn't see the 2 saved records you linked to as that site is down, but I did manage to recreate encoding problems in the record details output of attribute values. I have committed a change to the develop branch which fixes this and also adds a twig-like option to enable escaping in our output template format.

**Comment by kitenetter** [comment]
@johnvanbreda I've had a recent query about the csv encoding, and am not sure how to respond:

> CSV files, I expect to be encoded in WIN1252, but they contain some HTML characters such as for Apostrophe, etc.. Hence names, comments need editing before importing into Recorder6. If the encoding was defined, then I could download as a TXT file, and import into Excel from there.

Would be grateful for advice.

**Comment by johnvanbreda** [comment]
I think our CSV downloads are UTF-8 encoded with a Byte Order Marker which allows Excel to interpret this correctly. HTML characters are probably there for a different reason - do you have an example that will allow me to reproduce this?

**Comment by kitenetter** [comment]
There have been no recent reports of similar problems - closing.
