### ISSUE TITLE
Data download - images

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#257]
Derived from umbrella issue #74 

Additional requirement/suggestion:

Currently the download provides hyperlinks directly to images associated with a record (sometime multiple links strung together if there is more than one image). I think it would be more useful if we:

    Add a column that gives a hyperlink to the record page (rather than direct to the image)
    Add a column that is a yes/no for whether images are available for the record
    Remove the column that we currently have for hyperlinks to the images themselves

- response from JVB:

Hi @kitenetter, does @DavidRoy agree with the proposed change to the images column? I am aware that a link to the record page does not give the same functionality as having the image filenames. This would affect any code written to extract the images from a download, though I'm not sure if anyone has done that.

- response from DBR

Sorry for delay in responding to this thread. I agree with Martin's suggestions about how to handle image information within downloads

**Comment by johnvanbreda** [comment]
This change is a little more complex than initially thought so I'm just noting some points here while I think of them.

A download report can contain records from any website which shares its records for downloading (data flow) with iRecord but these websites might not actually share their records for reporting in iRecord (e.g. NNSS, UKBMS and Moth Night are all set up like this). Therefore it is possible to download a record from iRecord even though iRecord cannot show the record details. 

There is another issue, a website that shares a record to iRecord might or might not have it's own record details page. Which page takes precedence and what happens when downloading from that site instead of iRecord?

On a technical note, it might be necessary to create some sort of lookup table between website IDs and their preferred record details page URLs.

**Comment by kitenetter** [comment]
Given the complexity of handling images from multiple websites, perhaps we should retain the column containing hyperlinks to the photos, and simply add an additional column containing the hyperlink to the record, where available.

**Comment by kitenetter** [comment]
Review under #886 - closing.
