### ISSUE TITLE
Activities higher taxa not displaying

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#26]
In Activities - Explore Activity Data - Taxon Groups, there are figures given for number of records and species, but the column showing the taxon group name is missing - this only appears to be the case for some activities, but is affecting soldierflies and DUMP

**Comment by johnvanbreda** [comment]
Fixed. It affected some activities which filtered to a single taxon group as these activities deemed the group column not to be necessary if it would only show one thing. This makes sense on a list of records or species, but not on the groups list itself.
