### ISSUE TITLE
iRecord import of taxa with 'sensu lato' or 'sensu stricto' finds no matching taxa

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#260]
I've done a few uploads over the past few days - mostly it's worked very smoothly. But I've had problems when using taxon names such as 'Araniella cucurbitina sensu stricto'. These records do not import and the message in the error CSV is "Species_name: Could not find "Araniella cucurbitina sensu stricto" in Taxa taxon list Taxon".

However when I've checked for the correct name using the casual entry iRecord form, the names are there. I've even copied and pasted the text from the iRecord form into my import spreadsheet - it makes no difference.

I have 80 or so spider records that are recorded either as 'sensu stricto' or 'sensu lato' and I cannot import these. I also noticed the same problem on a plant taxon - although 'Erophila verna sens.lat.' is in the drop-down for the iRecord casual entry, I couldn't use that name to import the record.

I'm importing against the 'UK Master List'.

Rich

**Comment by kitenetter** [comment]
@burkmarr one work-around option would be to import these agg. records using the Taxon Version Key for each aggregate. You can import using TVKs instead of taxon name strings.

I'm not sure what the problem is with the agg. name strings, but a longer-term solution may be for iRecord to adopt the additional functionality that @johnvanbreda has developed for importing species names into Pantheon, where non-matching or ambiguous names are highlighted before import and users have the option to specify the UKSI name that they wish to use.

**Comment by burkmarr** [comment]
Thanks @kitenetter - that had occurred to me and I was going to have a go but I couldn't get the UKSI keys from their website (see excerpt from email to Chris below).

> When I search (http://www.nhm.ac.uk/our-science/data/uk-species/species/index.html) on ‘Enoplognatha ovata’, I get both ‘Enoplognatha ovata sensu stricto’ and ‘Enoplognatha ovata sensu lato’ returned in the results. But it doesn’t matter which one of these I click on, it takes me to the page http://www.nhm.ac.uk/our-science/data/uk-species/species/enoplognatha_ovata.html where I can see the key for ‘Enoplognatha ovata sensu lato’, but not ‘Enoplognatha ovata sensu stricto’.

Do you know of better way for me to key the keys?

**Comment by kitenetter** [comment]
@burkmarr suggest using Chris's 'sandbox' site, e.g. this search for "Araniella cucurbitina" returns the s.s. and s.l. options and gives TVKs:
http://nbn-sd-dev.nhm.ac.uk/taxonbrowser.php?txtSearch=Araniella+cucurbitina

**Comment by burkmarr** [comment]
Thanks @kitenetter - Chris' Sandbox was the tool I needed and I was able to use the workaround to import all the outstanding records.

**Comment by johnvanbreda** [comment]
@burkmarr I've updated the lookup used for taxon names on import to include the taxon attribute so this should not be a problem in future.

**Comment by burkmarr** [comment]
That's brilliant - thank you both @johnvanbreda and @kitenetter. I will test this later in the week when I'm back from the course, but I'm sure you've already done that John.
