### ISSUE TITLE
Unable to remove preferred locality boundary when searching "All records"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#266]
If a user has set a county as a preferred locality, it seems that if they go to Explore - All records they are unable to see any records outside their preferred locality, even if they switch the county off in the "Where" part of the filter.

I've only tested this while masquerading as user "Jassy", but presumably it's a general issue.

**Comment by johnvanbreda** [comment]
Fixed in code - will be deployed at the next feature release.

**Comment by johnvanbreda** [comment]
I've reverted this commit as it introduced other problems.
