### ISSUE TITLE
BDS Life stage field order has suddenly reversed

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#267]
The two BDS Dragonfly recording forms (Single and List) have always shown the life stage abundance fields in a standard order:
Ad, Co, Ov, La, Ex, Em
Last week the order suddenly reversed. 
I'm hoping (but haven't checked) that the correct value is still assigned to the stated field and that the handling of Import spreadsheets and submissions from the App are unchanged.
Please change the ordering back! We risk receiving nonsense from experienced recorders.
David H.

**Comment by johnvanbreda** [comment]
Resolved - the view was not applying the order correctly when loading the attributes. There should have been no other side effects.

**Comment by DavidHepper** [comment]
Thanks. Tested OK on both forms.

**Comment by DavidHepper** [comment]
One of my dragonfly recorders has just reported that the same problem was seen for Butterflies. Is recoding generic to all Activities?

**Comment by johnvanbreda** [comment]
Yes, it was a generic issue and it should be generically fixed.
