### ISSUE TITLE
Unable to add administrators for Activities

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#268]
Bug on this form:
https://www.brc.ac.uk/irecord/activities/edit

When trying to add Activity administrators, the name search no longer works.  Problem found using Chrome and IE
![image](https://user-images.githubusercontent.com/2699478/30101823-a3903044-92e5-11e7-89fe-25b8025e2e5e.png)

**Comment by johnvanbreda** [comment]
Fixed - an upgrade script had not been correctly applied.
