### ISSUE TITLE
Unable to add 'Families and other higher taxa' filter

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#269]
When adding a verification filter (https://www.brc.ac.uk/irecord/filters/admin-edit), the search box within the tab for 'Families and other higher taxa' is unresponsive when setting up a verification filter.  The progress wheel keeps spinning when entering 'Coc' but returns no result.

Urgent because prevents verification roles being setup for some groups.

**Comment by johnvanbreda** [comment]
I've fixed the basic search, though I've also noticed that due to the new search algorithm this search is no longer filtering to families and higher taxa only, though you can still find families so the basic functionality is OK. I'll fix that now...

**Comment by johnvanbreda** [comment]
Now fixed.
