### ISSUE TITLE
Recorder name for non-logged-in users

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#27]
Change behaviour of forms for users who are not logged in, so that this field a) does not get populated with just a comma and b) if empty and the user’s name is filled in, automatically copy it across. It does not sound like more than an hour or two to fix.

**Comment by kitenetter** [comment]
From @johnvanbreda 2 June 2016:
Things we could do to fix this:
1)	Auto-fill the recorder name from the first name and surname. You could overwrite it of course.
2)	Don’t fill in just a comma as a default – blank is better.
3)	Remove the recorder name values from the database which are just a comma and recalculate the recorder names for these (which will then use the firstname and surname to construct it).

**Comment by johnvanbreda** [comment]
I've done points 2 & 3 from the above list. Can you let me know if 1) is still needed please @kitenetter as it's slightly more work than the other 2.

**Comment by kitenetter** [comment]
1) is still desirable if/when we have resources to achieve it

**Comment by kitenetter** [comment]
This has not been raised as still being an issue recently, closing.
