### ISSUE TITLE
Button missing in Lichen recording form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#270]
In the lichen recording form:
https://www.brc.ac.uk/irecord/node/3668/edit

I think there should be a +/- button at the right-hand end of the species row, but (in Firefox) it is just a blank space:

![image](https://user-images.githubusercontent.com/16039111/30771011-2d939058-a036-11e7-9239-01e75aebe090.png)

**Comment by johnvanbreda** [comment]
The + button only appears when you enter a species name which I think is intentional.
