### ISSUE TITLE
Redetermination to genus level fails for large genera

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#271]
This is a fairly minor issue, but twice today I've had to redetermine supposed bee-fly records, once to genus Eristalis and once to genus Bombus. However, in both cases these are very large genera, and the genus name on its own only appears at the end of the list of species. There is a limit on how many species iRecord will display in the verifiers' redet. window, which means I've not been able to select the correct genus in either case (had to go to a species for the Eristalis, and made do with family Apidae for the Bombus).

Is there any way of removing the limit, or putting the genus at the top of the list?

**Comment by MNSmith** [comment]
I've encountered the same problem with record redeterminations

**Comment by johnvanbreda** [comment]
@MNSmith Have you had this problem in the last few days? I think it should be fixed now as a result of a different issue being fixed in the species search.

**Comment by kitenetter** [comment]
Genus names are now appearing at the top of the dropdown list. Closing.
