### ISSUE TITLE
Unable to enter species on ladybird form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#272]
https://www.brc.ac.uk/irecord/enter-ladybird-records

When trying to enter a species name, the list of names does not appear - just a spinning circle.  Problem with species search changes?

**Comment by johnvanbreda** [comment]
Fixed. There were a couple of problems, one of which related to the new search and one didn't.

**Comment by DavidRoy** [comment]
Another issue with form, reported via iRecord forum:
https://www.brc.ac.uk/irecord/node/4648

"Cannot add in adult or number of individuals and If you add these first selecting the species then removes them so not quite fixed"

**Comment by DavidRoy** [comment]
@johnvanbreda bumping up the urgency of this given recent news coverage of harlequin's coming into houses
