### ISSUE TITLE
Biotope missing in download from saved sites

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#273]
If I enter a record using one of the saved "My sites", the habitat information gets filled in automatically within the iRecord form. But habitats from saved sites are not being included in the "Biotope" column of the downloaded data.

Can this be fixed within the download process, or is it a matter of editing the saved site to update its habitat link?

**Comment by johnvanbreda** [comment]
The code hasn't been saving the associated biotope, just the link to the site. I've fixed this in the develop branch. Should we auto-allocate the biotope associated with any My Sites to the linked records, if the record doesn't have a biotope already?

**Comment by kitenetter** [comment]
I can see the case for auto-allocating this data, but I can also think of occasional exceptions among my own records where I would have deliberately wanted to remove the habitat link (e.g. if a particular record came from a different habitat within the same site). On balance I think it is probably best to accept that this data is lost and not make any assumptions about auto-allocating it (i.e. my judgement is that it is better to lose this data than to add potentially misleading data).
