### ISSUE TITLE
Verification grid default filters not working.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#274]
Looking at my verification grid, it appears not to be selecting those records "awaiting verification" for display but rather displaying ALL records, which makes selecting unverified records for review somewhat difficult.  I assume one of the filters is not working correctly.  Other users are seeing the same problem.

**Comment by DavidRoy** [comment]
@johnvanbreda - some forum posts about this.  I think the default filter on the verification grid (i.e. to exclude accepted/rejected records) is not being applied.

Mark as urgent given it relates to verification

**Comment by johnvanbreda** [comment]
Should be OK now.

**Comment by MNSmith** [comment]
Looks all ok for this side.  Thanks for this.

Regards

Matt

____________________________________________________________________________________________________________________________________

Matthew Smith BSc (Hons) ARCS FRES MCIEEM
Consultant Ecologist
24 Allnatt Avenue
Winnersh
Berks
RG41 5AU

Tel: 0118 979 4313   Mob: 07710 160 690
  ----- Original Message -----
