### ISSUE TITLE
iRecord explore reports to give [Output map ref] instead of [Original map ref]

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#275]
Mobile apps capture lat/long as the spatial precision.  However, recorders are more familiar with OS grid references.  To address this confusion and inconsistency with the filtering options (e.g. for filtering by square), standard explore reports should show [Output map ref] instead of [Original map ref].  

https://www.brc.ac.uk/irecord/my-records
https://www.brc.ac.uk/irecord/all-records

to be changed.

**Comment by johnvanbreda** [comment]
Fixed in develop branch for next feature release.

**Comment by DavidHepper** [comment]
Good move. Does this apply to and behave in the same way in **Verification - <taxon group>** reports, please?

**Comment by johnvanbreda** [comment]
Hi @DavidHepper, yes this will apply to verification reports unless we configure it not to.
