### ISSUE TITLE
Page navigation on 'Verifiers summary' - inconsistent results

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#277]
Steps to reproduce:

- Run a **Verifiers summary** report (anything that generates more than 20 rows): the report shows "Showing records 1 to 20 of nnnn", where nnnn may be an unexpectedly large number, more likely to be a count of the number of records summarised than of the rows in the summary list above.
- Click the hotspot 'next': rows 1 to 20 are repeated. This is not correct.
- Again click the hotspot 'next': rows 21 to 40 are shown. Hotspots 'next' and 'last' may now be greyed out, which is correct but there are additional page selection hotspots for pages '3', .. '7'. Clicking any of these shows in the grid "No information available" and all the page navigation hotspots disappear.

This is not in itself a high priority but it may be an example of page navigation problems elsewhere.

**Comment by johnvanbreda** [comment]
Fixed. This isn't a wider issue - it happens when a report doesn't specify how its content rows are counted correctly.
