### ISSUE TITLE
CSS problems following recent update

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#278]
Release 1.46.0 of the media included a change to CSS, https://github.com/Indicia-Team/media/commit/bbb5a2231ef436888f0ce4531f66f5d24e19356a.

There are problems with the appearance of forms since this change was applied.

Initial inspection suggests that a new file, theme-generic.css, is not being included.

**Comment by johnvanbreda** [comment]
Looks like I missed the update required to the iform module. I'll do that now.

**Comment by johnvanbreda** [comment]
Fixed.
