### ISSUE TITLE
Make vague data options more widely available

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#28]
Option 1: add a toggle to recording forms so that user can switch between vague date or normal date - Option 2: give users a setting in their profile so that they can choose which option to use 

[Option 1 gives more flexibility?]

**Comment by johnvanbreda** [comment]
Vague date entry options are on the user profiles now so I think this can be closed.

**Comment by kitenetter** [comment]
Help page now updated. Closing.
