### ISSUE TITLE
Report grids returning non marine species when marine flag set on filter

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#283]
Trying to program a page on the Northern Ireland CEDaR site for marine species.
When I got them to check the existing report grids to see whether they met their reporting requirements a strange issue was observed.
This applies to both the CEDaR and iRecord record grids (they are both attached to same warehouse).

If you change the report filter so that it should only return marine species, it seems to return some non marine ones, examples include (but not limited to) Andrena (Mining bee), Cornu aspersum (Common Garden Snail), Armadillidium vulgare	(Common Pill Woodlouse)
I think this is just a flag on the taxon table. Is someone able to query the warehouse to find the flag setting for the above species and/or provide an explanation for this behaviour?

If there is an explanation at best it is confusing

**Comment by andrewvanbreda** [comment]
Note: I have been informed the issue also occurs the other way around, with marine species missing when they should be showing if the marine flag is on in the report grid filter, although I don't have specific examples of that at the moment, I assume it is the same issue.

**Comment by johnvanbreda** [comment]
I've looked at the UKSI database we last loaded into iRecord for Andrena and it is set to true, so the functionality is correct. The flag may be being set for species which have some association with the coast - in this case Andrena nitida is flagged as such which knocks on to Andrea. Same for Cornu aspersum etc.
You can post questions on the NBN forum about the UKSI data.

**Comment by andrewvanbreda** [comment]
OK thanks for the infor. I will let them know and I will close this issue once I am happy with their response.
