### ISSUE TITLE
Unable to add verification filter

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#285]
If I try to add a verification filter via https://www.brc.ac.uk/irecord/filters/admin-edit I get an error message:

general_errors.There was an SQL error: ERROR: canceling statement due to statement timeout - SELECT count(o.*) FROM cache_occurrences_functional o JOIN cache_occurrences_nonfunctional onf on onf.id=o.id JOIN cache_samples_nonfunctional snf on snf.id=o.sample_id JOIN cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id JOIN websites w on w.id=o.website_id and w.deleted=false LEFT JOIN index_websites_website_agreements canEdit on canEdit.from_website_id=o.website_id and canEdit.to_website_id in (23) and canEdit.provide_for_editing=true JOIN users privacyusers ON privacyusers.id=o.created_by_id WHERE o.training=false AND (o.website_id in (23) OR privacyusers.id=1 OR privacyusers.allow_share_for_reporting=true OR privacyusers.allow_share_for_reporting IS NULL) AND o.website_id in (101,12,24,14,8,6,17,25,11,7,30,40,34,5,43,13,29,33,44,32,42,51,49,65,68,73,75,9,71,87,97,88,69,23,10) AND o.release_status='R' AND o.confidential='f'

**Comment by BirenRathod** [comment]
@johnvanbreda 
I have increased the time limit to 2min in PostgreSQL. Let me know if that is enough or not required action or affect any other operation. Another option is, you could implement the query to perform better. 

@kitenetter, check if that works OK for you. I have no idea about whether that page could perform same way in lower internet speed.

**Comment by JimBacon** [comment]
I am running a lot of time-consuming queries on the database today which could be impairing performance.

**Comment by BirenRathod** [comment]
I'm not sure that could be the reason at present but it has returned with 2510860 total and than it (report) filters the records according to.

**Comment by kitenetter** [comment]
The page is quite slow to open, but seems to be working again now, thanks.
