### ISSUE TITLE
Data grid filters for recordIDs not working (<, <= ... etc)

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#287]
The pop up in the top (filter) row of data grids in explore reports says that user can enter "<, <= ... etc" for a RecordID.  Users report this not functioning as expected.  Error message says 'report did not load properly'

**Comment by kitenetter** [comment]
This appears to have been fixed for the old Explore pages. It doesn't work on the ES pages but the tooltip text doesn't imply that it should, and similar functions are available by using a range or using the Create a filter options. Closing.
