### ISSUE TITLE
Update NNR (England) boundaries in iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#289]
Our set of NNR boundaries needs updating for use with the NE activities.

A shapefile is stored in:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Boundaries\National_Nature_Reserves_England_2017_12_08.zip

As fas as I can tell we have only had England NNRs in iRecord to date, so this new dataset should completely replace the one currently in use.

**Comment by BirenRathod** [comment]
Hello @kitenetter 

I update the boundaries and let you know.

**Comment by kitenetter** [comment]
Hi @BirenRathod, Natural England are chasing us for this one, do you know when you'll be able to do the boundary import?

**Comment by BirenRathod** [comment]
Hello @kitenetter 

I have uploaded this onto Dev warehouse. please check that onto http://test.brc.ac.uk/irecord_dev. If all goes ok than I will upload onto live warehouse.

**Comment by DavidRoy** [comment]
The boundaries seem to be duplicated.  If you search for Monks Wood you get 'Monks Wood' and 'Monks Wood NNR'

**Comment by BirenRathod** [comment]
I have expected that. Anyway I will add IDs of existing layers to new file and I upload again on dev warehouse. Thanks David, for looking into.

**Comment by kitenetter** [comment]
Something odd has happened with the "Fenn's, Whixall & Bettisfield Mosses" boundary (which is the one that prompted this update!). The old version (currently labelled "Fenn's, Whixall & Bettisfield Mosses NNR") is unchanged, and the new version ("Fenn's, Whixall & Bettisfield Mosses") consists of just a small fragment of what should be a larger area than the old boundary.

Could this be a problem with multi-polygon boundaries?

**Comment by johnvanbreda** [comment]
Yes, the SHP importer in Indicia expects each row in the dbf file associated with the SHP to imply a single location, so it will only import 1 boundary if there are several rows. The rows can be combined into a single multipolygon using GIS though.

**Comment by BirenRathod** [comment]
@kitenetter, @DavidRoy 

I rectified layers and implemented the records in the shape-file. I than updated NNR boundaries in the devwarehouse. I checked in the database & irecord, there hasn't any duplicate.

**Comment by kitenetter** [comment]
@BirenRathod  I’ve just looked at the NNR boundaries on the development iRecord. So far I have just checked the one for “Fenn’s, Whixall & Bettisfield Mosses NNR” (FWB NNR), for which the boundary should change.

If I log on as iRecord support and go to Explore – My Sites, I can find FWB NNR in the drop-down list and I can add it to My Sites. The boundary here looks like the correct new one.

However, if I go to Explore – My records and set up a filter for FWB NNR I’m still seeing the old boundary. 

Also, is it possible for people outside CEH to see the development version of iRecord (i.e. would Andy Webb at NE be able to log on under his usual account name)?

**Comment by BirenRathod** [comment]
Hello @kitenetter 
I couldn't see any difference when I looked at boundary in "My Sites" & "My Records". Please clear the cookies and try again.

Development site is available to anybody. it has got same username and password as live site.

**Comment by BirenRathod** [comment]
@kitenetter 

you can see that boundary here - > http://devwarehouse.indicia.org.uk/index.php/location/edit/1755

**Comment by kitenetter** [comment]
Thanks @BirenRathod, having cleared cookies the boundaries are now consistent.

Another possible issue: if I log on to the development site as "Martin C. Harvey" and go to My Sites, I have two sites relating to Ruislip Woods NNR. 

One of these "Ruislip Woods NNR: Park Wood" is not linked to the NNR boundary, it is simply one that I saved against a grid ref.

The other, "Ruislip Woods NNR", is based on the NNR boundary layer, but when I go to the Explore button for this site it is not displaying any of my 7 records from the "Ruislip Woods NNR: Park Wood" site, the grid ref for which falls within the NNR boundary (and records from this grid ref should get displayed within the NNR polygon shouldn't they?).

Maybe this is just odd behaviour on the development site that would be fine on the live site but thought I should document it in case it highlights any problem with the new layer.

**Comment by BirenRathod** [comment]
@kitenetter 

Ruislip Woods NNR & Ruislip Woods NNR: Park wood are two individual one. Ruislip Woods NNR is the one comes from NNR list. So, if you have stored records with "Ruislip Woods NNR: Park Wood", Records will not display in Ruislip Woods NNR filter. Both has got individual location id. Ruislip Woods NNR has got layer attached to it and "Ruislip Woods NNR: Park Wood" has got grid ref. 

Same with live site too. I just checked on the live warehouse, they both exists in there.

**Comment by kitenetter** [comment]
Hi @BirenRathod - I'm confused! On the live site, if I go to My Sites and choose "Ruislip Woods NNR" and then click on Explore, I **_do_** see the seven records from "Ruislip Woods NNR: Park Wood":

![image](https://user-images.githubusercontent.com/16039111/36376455-1434c8fc-156b-11e8-8ece-086676272df7.png)

So as far as I can see the live site is behaving differently to the development site.

What I don't know is whether that is just the result of the development site working slightly differently to the live site, or whether the updated NNR boundary is causing it to behave differently.

**Comment by JimBacon** [comment]
I'm wondering whether the index_locations_samples on the development warehouse has processed the old samples against the new boundaries. Just a thought.

**Comment by BirenRathod** [comment]
@kitenetter 

That is because both the boundaries associated with your account id on the live site. That has changed on dev warehouse and dev irecord site. so association of the location ids don't behave same as live irecord site. The explanation, I gave earlier was about the individual ids created on both the warehouses. 
New NNR boundaries will not impact of @kitenetter raised the concern.

**Comment by kitenetter** [comment]
Thanks for clarifying @BirenRathod. I've asked Andy Webb at NE to check the changed boundaries on the development site but it seems we are very close to being able to move this over to the live site.

**Comment by BirenRathod** [comment]
@kitenetter 
Once you get a feedback from Andy, let me know, so I will upload the layers.

**Comment by kitenetter** [comment]
@BirenRathod Andy is happy for the boundaries to go live

**Comment by BirenRathod** [comment]
I will upload it on live and let you know soon.

**Comment by kitenetter** [comment]
Hi @BirenRathod, Natural England are chasing us again for the new boundaries, do you know when we'll be able to get them added to the live site?

**Comment by BirenRathod** [comment]
@kitenetter, It has uploaded now, please check.

**Comment by kitenetter** [comment]
Thanks @BirenRathod

**Comment by kitenetter** [comment]
NE report that since the boundary update records are not displaying as expected, at least for the Feen's and Whixall Moss activity at:
https://www.brc.ac.uk/irecord/groups/summary?group_id=1143&implicit=

It now shows 6 records within the NNR, where there used to be c. 700.

I tried to edit the existing activity to re-save the NNR boundary filter, activity, but it is not letting me choose an NNR:

![image](https://user-images.githubusercontent.com/16039111/37144836-2313ce96-22b7-11e8-99d8-96ae9f5adfed.png)

Do we need to do any re-idexing, or ir there another issue here?

**Comment by BirenRathod** [comment]
Hello @kitenetter 
This has resolved now. John has validated some of the invalid boundaries.

**Comment by kitenetter** [comment]
Thanks @BirenRathod and @johnvanbreda
