### ISSUE TITLE
Make it possible to distinguish between users in the list of Activity admins

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#29]
When adding admins to activities the dropdown list shows only "Surname, First name" (presumably from the info in user profiles?), and there are often duplicated names. We need a way of showing who is who. We can't show full email addresses, but could we show user names in addition to 'real' names?

**Comment by johnvanbreda** [comment]
Fixed - you can search by email to pick out the correct name.
