### ISSUE TITLE
Update LERC boundaries in iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#290]
Our set of LERC boundaries needs updating to reflect recent changes, especially in Scotland.

A shapefile is stored in:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Boundaries\LERC Boundaries.zip

This is for full LERC coverage and should completely replace the one currently in use.

(In the past we have had issues with gaps and overlaps in the LERC boundaries but I am assured that this dataset is clean.)

**Comment by BirenRathod** [comment]
@kitenetter 

I will do that.

**Comment by kitenetter** [comment]
Not sure where we are with this one, but if we haven't yet updated we may need to review some of the issues raised previously in #64, in particular in relation to whether LERC boundaries should include offshore elements and what to do about regions that have no LERC. Closing this issue and continuing on #64
