### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#292]
I just added an additional form to an Activity, clicked the Update button, and got this error message:

> Notice: Constant PREDIS_VERSION_MAJOR already defined in Redis_Client_Predis::setPredisAutoload() (line 63 of D:\web sites\irecord\sites\all\modules\redis\lib\Redis\Client\Predis.php).
> PDOException: SQLSTATE[HY000] [2002] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. in _registry_check_code() (line 3477 of D:\web sites\irecord\includes\bootstrap.inc).

The Activity seems to have saved okay and is working fine as far as I can tell, so this may not need any response, just reporting it in case it is significant.

**Comment by BirenRathod** [comment]
This looks like the problem with your connection than Redis module itself. Please check your connection fine. If you still experience the problem, let me know.

**Comment by kitenetter** [comment]
This doesn't seem to be recurring, so am closing.
