### ISSUE TITLE
Genus Cheilosia is missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#294]
The hoverfly genus Cheilosia is not currently available for data entry nor reporting. Can't find any problems with other genera.

UKSI link:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000006203

**Comment by johnvanbreda** [comment]
There is an attribute `suppr.` for this genus, so the name is listed as "Cheilosia suppr."

**Comment by JimBacon** [comment]
![image](https://user-images.githubusercontent.com/2545390/35672750-641ed0ca-0737-11e8-9655-ce9ff4fe8549.png)

There it is, in the screenshot, on test.brc.ac.uk. You have to click the 'more available' link to get to it.
A couple of thoughts (apart from 'what the heck is suppr.' which not even the power of Google has managed to explain to me yet).
 - Should species A and species B be in there?
 - Is ordering genus+attribute alphabetically with genus+species good or would ordering by rank and then alphabetically be an improvement?
 - Would it help recorders to show the rank for non-species level recording? E.g.
     - _Cheilosia suppr._ genus
     - _Cheilosia ahena_
     - _Cheilosia albitarsis_

**Comment by kitenetter** [comment]
@JimBacon "suppr," means "suppressed" and as far as I'm aware it is used when a decision has been taken that a particular variant of a genus name has been formally agreed as the one to be used, while others (often mis-spellings of the same name) are suppressed. In this case, UKSI seems have marked "Cheilosia" incorrectly as being suppressed; in fact, the spelling "Chilosia" is the one that has been suppressed.

The (incorrect) UKSI one is here:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000006203

What I understand to be the correct interpretation is here:
http://www.dipteristsforum.org.uk/sgb_check_browse.php?id=7786

Species A and species B: this is another area where UKSI is out of date. Species A and B (and C, D and E) were keyed out in earlier editions of Stubbs and Falk's key. In the latest edition only species B is retained (species A is now known to be Cheilosia uviformis, which UKSI includes, but has not marked species A as a synonym). Species B still exists in the current keys so needs to be in the UKSI (although it may get resolved to a 'proper' species at some point in the future).

I don't understand your ordering suggestions, sorry! I think in most cases the genus name does appear at the top of the list, it is only because of the erroneous "suppr." that things have gone wrong for Cheilosia. If "suppr." were needed, it ideally ought to be treated as some sort of metadata about the name, rather then being part of the name itself.

I agree it would ideally be helpful to explicitly label higher taxon names as being higher taxa, maybe using square brackets e.g.
- Cheilosia [genus]
- Syrphidae [family]
 
The over-riding issue behind this is that the UKSI is a long way out of sync with the current UK Diptera checklist, a problem that Chris Raper is well aware of and intends to address when possible.

**Comment by johnvanbreda** [comment]
If there is a consensus that higher taxon ranks should be added to names as suggested, then please add a new issue to cover this.
The suppressed attribute is correctly displayed then, but I am not sure I understand why it is important for this to appear as an attribute in this instance (i.e. to become part of the displayed name) when there is no requirement to do that for normal synonyms. In my opinion, this should have just been a synonym of Chilosia and the fact that it is suppressed isn't that important, or it could be stored in a field somewhere which does not form part of the name.

**Comment by kitenetter** [comment]
I agree that the suppressed attribute is not important for iRecord use, and that it would be better for "suppr." not to be part of the name that is displayed. If that is easy to change I would do so, but it probably isn't worth spending time on as it will hopefully get corrected in UKSI before too long.
