### ISSUE TITLE
Verifiers' quality filter not working as expected

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#295]
If I set up a filter for my verification grid and ask it show only those records that have photos, I get a substantial number of records.

If I set up a filter and ask it to show only those records with ID difficulty of 2 I get a substantial number of records, but none with photos.

If I set up a filter and ask it to show only those records that both have a photo and are of ID difficulty 2, I get no records. There are in fact quite a lot of records of species with ID difficulty 2 that do have photos.

It seems there is some interaction between the photo filter and the ID difficulty filter that is set incorrectly?

**Comment by johnvanbreda** [comment]
I'm not sure I follow - aren't these statements contradictory:

> If I set up a filter and ask it to show only those records with ID difficulty of 2 I get a substantial number of records, but none with photos.

> There are in fact quite a lot of records of species with ID difficulty 2 that do have photos.

>

**Comment by kitenetter** [comment]
@johnvanbreda this issue does not currently apply to the ES verification page, because on that page the "Create a filter"options under "Quality" no longer allow you to filter by identification difficulty. That was possible on the old page.

Could it be reinstated on the ES page or is there a reason why it did not get transferred over?

**Comment by johnvanbreda** [comment]
I think the reason is I made a mistake with the ES data structure and, although the id difficulty message is available, the scale from 1 to 5 is not. So this needs to be added to the index and it refreshed. But, yes, this functionality should be recreated for ES at some point.

**Comment by kitenetter** [comment]
Transferring ES requirement to #904 and closing this one.
