### ISSUE TITLE
Error message from NBN download report

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#297]
Not sure if this is related to #296 - I tried to run the report for generating NBN export files. and it seems to have failed partway through the process. I will re-visit this in the new year, but for reference the message was:

> Created D:\web sites\irecord\sites\default\files/autogenerated_downloads/user_id_10120/download-NBN - Consultants Portal.txt
> Created D:\web sites\irecord\sites\default\files/autogenerated_downloads/user_id_10120/download-NBN - GA001157 RISC Heteroptera.txt
> Created D:\web sites\irecord\sites\default\files/autogenerated_downloads/user_id_10120/download-NBN - GA001158 RISC Mammal.txt
> Created D:\web sites\irecord\sites\default\files/autogenerated_downloads/user_id_10120/download-NBN - GA001159 RISC BSBI.txt
> Created D:\web sites\irecord\sites\default\files/autogenerated_downloads/user_id_10120/download-NBN - GA001160 RISC MBA.txt
> Created D:\web sites\irecord\sites\default\files/autogenerated_downloads/user_id_10120/download-NBN - GA001162 RISC Leafhopper.txt
> Created D:\web sites\irecord\sites\default\files/autogenerated_downloads/user_id_10120/download-NBN - GA001163 RISC Conch.txt
> cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
> URL:https://warehouse1.indicia.org.uk/index.php/services/report/requestReport?higher_taxa_taxon_list_names=&taxon_group_names=&website_list_op=not+in&mode=nbn&reportSource=local&report=library%2Foccurrences%2Ffilterable_nbn_exchange.xml&input_forms_list_op=in&survey_list_op=in&default_input_form=enter-record-list&sharing=data_flow&auth_token=c7a59004813b66f4e6a39e546dda8d1902ca88fd&quality=V&taxon_rank_sort_order_op=%3D&nonce=432d280729130b7972b9afd5a620dfbc77be16ae&higher_taxa_taxon_list_list=211146&website_list=29&smpattrs=%23det_full_name%2C%23sex%2C%23stage%2C%23sex_stage_count&occattrs=%23biotope&taxon_group_list=&taxon_rank_sort_order=&autochecks=&has_photos=&taxon_rank_sort_order_combined=&survey_list=&input_form_list=
> Server response
> {"error":"general_errors.There was an SQL error: ERROR: canceling statement due to statement timeout - \nselect o.id as \"id\",\n'iBRC' || o.id as \"recordkey\",\no.survey_id as \"surveykey\",\no.sample_id as \"samplekey\",\no.taxa_taxon_list_external_key as \"taxonversionkey\",\nupper(cast (o.zero_abundance as character)) as \"zeroabundance\",\ncase when onf.sensitivity_precision is null then 'F' else 'T' end as \"sensitive\",\ncast(o.date_start as character varying) as \"startdate\",\ncast(o.date_end as character varying) as \"enddate\",\no.date_type as \"datetype\",\no.location_id as \"sitekey\",\nsubstring(o.location_name, 1, 100) as \"sitename\",\ncase when snf.entered_sref_system in ('4326', '27700') then null else replace(snf.public_entered_sref, ' ', '') end as \"gridreference\",\ncase when snf.entered_sref_system in ('4326', '27700') then st_x(st_transform(st_centroid(o.public_geom), snf.entered_sref_system::int)) else null end as \"east\",\ncase when snf.entered_sref_system in ('4326', '27700') then st_y(st_transform(st_centroid(o.public_geom), snf.entered_sref_system::int)) else null end as \"north\",\ncase upper(snf.entered_sref_system) when '4326' then 'WGS84' when '27700' then 'OSGB36' when 'OSIE' then 'OSI' else upper(snf.entered_sref_system) end as \"projection\",\nget_sref_precision(snf.public_entered_sref, snf.entered_sref_system, snf.attr_sref_precision) as \"precision\",\nvc.name as \"vicecounty\",\nsnf.recorders as \"recorder\",\nonf.verifier as \"verifier\",\ncoalesce(g2.title || '::', '') || snf.group_title as \"source_group\"\nFROM cache_occurrences_functional o\nJOIN cache_occurrences_nonfunctional onf on onf.id=o.id\nJOIN cache_samples_nonfunctional snf on snf.id=o.sample_id\nJOIN cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id\nLEFT JOIN locations vc on vc.id=o.location_id_vice_county and vc.deleted=false\nLEFT JOIN group_relations grel on grel.to_group_id=o.group_id and grel.deleted=false\nLEFT JOIN groups g2 on g2.id=grel.from_group_id and g2.deleted=false\nJOIN users privacyusers ON privacyusers.id=o.created_by_id\n\n\nwhere o.training=false AND (o.website_id in (23) OR privacyusers.id=1 OR privacyusers.allow_share_for_data_flow=true OR privacyusers.allow_share_for_data_flow IS NULL)\n AND o.website_id in (12,24,14,8,6,17,11,3,30,16,27,34,5,43,13,29,33,44,32,42,51,49,63,65,73,9,71,87,97,69,23,10) \nand o.date_type in ('D','DD','O','OO','Y','YY','-Y','U') \nand (snf.entered_sref_system ilike 'osgb' or snf.entered_sref_system ilike 'osie' or snf.entered_sref_system = '4326' or snf.entered_sref_system = '27700')\nand o.taxa_taxon_list_external_key is not null\nand st_x(st_transform(st_centroid(o.public_geom), 4326)) between -14 and 13\nand st_y(st_transform(st_centroid(o.public_geom), 4326)) between 48 and 62\n\n AND o.release_status='R'\nAND o.confidential='f'\nAND o.record_status='V'\nAND o.family_taxa_taxon_list_id in (211146)\nAND o.website_id not in (29)\n ORDER BY o.id ASC","code":44,"file":"D:\\web sites\\warehouse1\\system\\libraries\\drivers\\Database\\Pgsql.php","line":342,"trace":[]}

**Comment by JimBacon** [comment]
They are both timeout errors. It may just indicate the server is busy and not that anything is particularly wrong. Would you be trying to run several slow tasks at the same time by any chance? The server is a lot quieter right now than it was an hour ago.

**Comment by kitenetter** [comment]
Thanks Jim - I wasn't trying to multi-task at the time but I will pick a quiet moment to try again. Closing.
