### ISSUE TITLE
Verification: review grid no longer allows for choice of verification status term

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#298]
When I wrote the verifiers' guidance it was possible to use the "review grid" bulk verification option and choose which verification flag to set, i.e. you could choose between setting all records to "Correct" or to "Considered correct":

![image](https://user-images.githubusercontent.com/16039111/34471884-19d6147c-ef4c-11e7-9119-93d1cb974727.png)

We appear to have lost the ability to choose between "Correct" and "Considered correct" - the window now shows:

![image](https://user-images.githubusercontent.com/16039111/34471888-47b0c4aa-ef4c-11e7-98d7-874403e1984e.png)

Please can we go back to being able to specify the verification flag, I think it is important to be able to use "Considered correct" for these bulk verification options and I don't see why it was removed.

On the same subject, when using the bulk verification options from the "Record tools" option it would be good to be able to choose "Considered correct" there as well. That option hasn't been avaialble in the past, but if it can be added that would be good.

**Comment by DavidHepper** [comment]
Whilst I support this request, Martin, I query whether status 'Correct' would be set for bulk-verified records. **Review tick list** still allows either status to be chosen. 'Review grid' is typically used by my Dragonfly verifiers to mark newly-imported records as verified but much more useful would be the ability to _import_ the verification status with the record, allowing records of differing status to be imported in a single file.
David

**Comment by kitenetter** [comment]
@DavidHepper I agree that the ability to (for registered verifiers only) to import a verification status would be useful, and have raised that as #301

See also #34 

I also agree that for bulk verification purposes it is much more appropriate to use "Considered correct" than "Correct", but it is conceivable that a set of records that are known to be correct might be uploaded by someone else and then need to be bulk verified by a verifier, so I would favour giving verifiers the choice.

**Comment by kitenetter** [comment]
@johnvanbreda : @sacrevert reports that when doing bulk verification via the grid, the choice between Correct and Considered correct has gone missing again. Can it be reinstated please?

**Comment by kitenetter** [comment]
The choice between Correct and Considered correct for bulk verification seems to be working as expected today, closing.
