### ISSUE TITLE
Rotation of photos from iPhone

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#299]
This has been reported via the forums and the iRecord emails, can anyone offer a solution?:

> If I take a photo on my iphone 5s in portrait mode, when I add photo, iRecord switches it to landscape mode. I don't have this problem when viewing photos on my laptop, i.e. the photo is taken in portrait mode and it is shown in portrait mode on my laptop, it is only when uploaded to iRecord that it is changed to landscape. This is particularly frustrating for plants which are usually taken in portrait mode as in iRecord they are rotated 90 degrees anti-clockwise (or 270 degrees clockwise) which doesn't look very good.
> 
> I get the same result regardless of whether the iphone 'Portrait Orientation Lock' is on or off so I think this is an iRecord issue not an iphone issue but I'm happy to be corrected as I just want to get this sorted. It didn't used to do it, perhaps that was when I was using the iphone 4, I'm not sure.
>

**Comment by JimBacon** [comment]
It is not clear to me from this whether they are using the iRecord app or not. It may be an app issue rather than an iRecord website issue. Do you know?

**Comment by kitenetter** [comment]
Not sure, I have asked.

**Comment by johnvanbreda** [comment]
Closing - please re-open if you get a response.
