### ISSUE TITLE
Vague date information gets lost on edit

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#30]
For data entered via http://www.brc.ac.uk/irecord/enter-records-vague-date with a range from one day date to another, the data saves okay, but if a record in the list is edited the date defaults back to the first date of the range - you have to manually re-enter the date range to persuade the edited list to save correctly. Can this be fixed? 

Jim says he found some code that may indicate there is still work to do on how vague dates are handled: "self::$entity_to_load['sample:date'] = self::$entity_to_load['sample:date_start']; // bit of a bodge to get around vague dates"

**Comment by johnvanbreda** [comment]
This has already been fixed in the develop branch of the code (courtesy of German users). Fix copied to iRecord.
