### ISSUE TITLE
Scottish islands missing from VC polygons

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#300]
I've noticed that the islands of Foula and Fair Isle are not covered by our vice-county polygons. They should be treated as within VC112 Zetland/Shetland, and are in the NBN polygons, but we seem to have removed them. There may be similar issues with some of the other Scottish offshore islands, I haven't checked them all.

We only have two verifiers for Shetland so far, and I don't think either of them have records on these two islands, so this isn't a priority. But it would be good to resolve it when we can,

In the meantime, the Shetland records centre boundary does include the islands so is probably the better one to use if needed.

**Comment by burkmarr** [comment]
Added in by replacing existing VC polygon for Shetland with the original from NBN (3 mile offshore extent).   Name used in NBN polygon - Zetland - replaced with name used in iRecord - Shetland - in order to replace existing polygon.
