### ISSUE TITLE
Unable to add multiple families to verification filter

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#302]
Have just been trying to set up a verification filter for sawflies. This requires adding 12 families to the taxon filter. At the moment, I can start adding families but after the first few the "Add" box stops finding any further names.

Sometimes it stops after adding just one family, sometimes it allows me to add several, but for now at least I can't get beyond four:

![image](https://user-images.githubusercontent.com/16039111/34666803-fe0e484c-f45d-11e7-8594-73c5fc9af34c.png)

**Comment by kitenetter** [comment]
Have hit the same problem when using the "Species groups" tab.

(Apologies for marking another one as "Urgent" but this is preventing me from fulfilling at least two requests from new verifiers who wish to get involved with iRecord.)

**Comment by DavidRoy** [comment]
Assigning to John given implications for verifier setup

**Comment by johnvanbreda** [comment]
Hi @kitenetter, I'm not seeing these symptoms. Which browser are you using and are you able to check if any JavaScript errors are occuring?

**Comment by kitenetter** [comment]
John, this problem seems to have gone away. Can't remember whether I was at home on Firefox when it arose, or at CEH on Chrome. Will document more thoroughly if it happens again.
