### ISSUE TITLE
Incomplete email notifications

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#303]
Over the last few days I have seen email notifications that are lacking part of the normal text/information, including the hyperlinks back to the record/s concerned. For me, this only happened once or twice last week, and then they went back to normal, but others are still reporting it today.

Example:

![image](https://user-images.githubusercontent.com/16039111/34667542-530e8aa2-f461-11e7-8f27-979bf961da88.png)

**Comment by johnvanbreda** [comment]
This was a bug briefly last week when I deployed some of the notification changes. I suspect that any mails received today are people with weekly digests so the notifications didn't come through till today. Please re-open if still occurring in a couple of days.
