### ISSUE TITLE
Develop process for exporting species datasets automatically

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#305]
Export of species datasets in Darwin Core Archive format as per #304 

To enable automatic flow of datasets to the NBN Atlas

**Comment by johnvanbreda** [comment]
Beta version provided to @DavidRoy and @kitenetter for testing. See http://indicia-docs.readthedocs.io/en/latest/site-building/iform/modules/sub-modules/indicia-auto-export.html
