### ISSUE TITLE
LRC download menu duplicated

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#308]
The main route for LRC download should be via Explore - Download, from where it is possible to choose from either the old download format or the new one.

However, a top-level LRC download menu is still showing when I log in (as Martin C. Harvey), which takes me to the old format download. It would be best if this top-level menu was removed so that all downloads are accessed via Explore.

I will check whether I can edit the menus to remove the top-level LRC one.

**Comment by johnvanbreda** [comment]
I've disabled this stray link - not sure why but there is no option to delete it.
