### ISSUE TITLE
Paste species lists from Pantheon of wider use

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#309]
Following some discussions on FaceBook, the idea came up of supporting the tool on Pantheon for pasting species lists as part of the workflow for data entry on iRecord. For example, there could be a "paste names" button on the list of records form which opens up a panel with the paste names & matching tool, then when done the tool closes and populates the records entry grid with the names.

**Comment by kitenetter** [comment]
This may be a good approach but would need careful handling to ensure that relevant sex/stage/abundance information was not lost. Closing for now.
