### ISSUE TITLE
Issue with user name in relation to recorder name?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#31]
User "T & J Weale" started off with name "Jennifer Weale" but changed after having entered some records. Now unhappy that "Jennifer Weale" still appears on the site, despite no longer being shown as the recorder for any records. E.g. Bringsty Common activity summary (http://www.brc.ac.uk/irecord/activities/summary?group_id=374&implicit=) - League Tables has "Jennifer Weale" even though Trending has "T & J Weale".

[Could this be a caching issue? But the name change was done over a month ago]

**Comment by johnvanbreda** [comment]
I've fixed this particular case in the data.
Question - if you change your name in this way, should the name update be changed in your details held on the warehouse so that all other sites you use are also affected?

**Comment by DavidRoy** [comment]
Yes, I think a name change should propagate across website/surveys.

**Comment by johnvanbreda** [comment]
The rules surrounding this could get fairly complex.
1) If someone changes their name (e.g. when getting married, as opposed to correcting it or changing it for reasons of personal preference) should their prior records be updated to reflect the new name? Ideally we'd have a notion of "recorder originally known as ..." but I suspect this is overkill.
2) If we do change prior records after a name change, what about cases where they have updated the recorder name. E.g. if Jane Smith entered a record but changed the Recorder field from "Smith, Jane" to Jane Smith & John Brown, then marries John and updates her name to Jane Brown, would we search for either "Smith, Jane" or "Jane Smith" contained any of her Recorder fields and update them? Note that if John Brown had entered some records and added Jane's name to the Recorder field, we probably can't do anything about it as we couldn't be sure he meant the same person.

**Comment by kitenetter** [comment]
I don't think we've ever managed to resolve the complexities mentioned above, so I'm proposing that for now we deal with name change requests on a case-by-case basis. See #468 for the latest discussion. Closing this issue.
