### ISSUE TITLE
Error on saving account preferences

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#310]
Error on trying to save account preferences.

general_errors.There was an SQL error: ERROR: duplicate key value violates unique constraint "ix_unique_email_address" DETAIL: Key (email_address)=(---email removed---) already exists. - UPDATE "people" SET "email_address" = '---email removed----' WHERE "id" = '39778'

**Comment by BirenRathod** [comment]
@johnvanbreda 
Similar problem have been reported in this issue https://github.com/BiologicalRecordsCentre/iRecord/issues/307

**Comment by johnvanbreda** [comment]
@DavidRoy Whose account and what changes were being made?
