### ISSUE TITLE
Why are old records appearing for verifiers?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#312]
I've had half-a-dozen or so enquiries about old records (i.e. records added to iRecord several years ago) 'suddenly' appearing in people's verification grids, when they hadn't been available before. Are there any recent changes or updates that would explain this? I don't think it is causing any major problem, it is just making people nervous that iRecord is handling records erratically.

**Comment by johnvanbreda** [comment]
Hi @kitenetter, can you get some example record IDs please so I can find out why?

**Comment by kitenetter** [comment]
Have not had any further reports - closing
