### ISSUE TITLE
Error message on iRecord home page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#313]
https://www.brc.ac.uk/irecord/

cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:https://warehouse1.indicia.org.uk/index.php/services/report/requestReport?report=projects/irecord/species_occurrence_image_counts.xml
Server response
{"error":"general_errors.There was an SQL error: ERROR: relation \"custom_cache_tables.counts_by_website\" does not exist\nLINE 5: FROM custom_cache_tables.counts_by_website c\n ^ - \n SELECT sum(c.species_count) as \"species_count\",\nsum(c.occurrences_count) as \"occurrences_count\",\nsum(c.photos_count) as \"photos_count\"\n FROM custom_cache_tables.counts_by_website c\n WHERE c.website_id in (101,12,24,14,8,6,17,25,11,7,30,40,34,5,43,13,29,33,44,32,42,51,49,65,68,73,75,9,71,87,97,88,69,23,10)\n AND c.training=false\n ","code":44,"file":"D:\\web sites\\warehouse1\\system\\libraries\\drivers\\Database\\Pgsql.php","line":342,"trace":[]}
general_errors.There was an SQL error: ERROR: relation "custom_cache_tables.counts_by_website" does not exist LINE 5: FROM custom_cache_tables.counts_by_website c ^ - SELECT sum(c.species_count) as "species_count", sum(c.occurrences_count) as "occurrences_count", sum(c.photos_count) as "photos_count" FROM custom_cache_tables.counts_by_website c WHERE c.website_id in (101,12,24,14,8,6,17,25,11,7,30,40,34,5,43,13,29,33,44,32,42,51,49,65,68,73,75,9,71,87,97,88,69,23,10) AND c.training=false

**Comment by johnvanbreda** [comment]
I've applied a temporary fix and I'm also changing the responsible module (custom cache tables) to make it more "robust" so it should at least repair itself if this happens again.

However there does seem to have been something odd happen last night which resulted in my new table being deleted. This new table provides a cached count of records, speeding up the count query on iRecord's home page (as it was sometimes the cause of a long pause when the home page loaded). The new table (custom_cache_tables.counts_by_website) was installed yesterday and was functioning OK until last night's backup. In the PostgreSQL logs I can see successful queries against this table up to 02:37 last night, when I can see there is a COPY command issued by the backup function against the table as it copies the data out. That seems OK:

> 2018-02-14 02:37:31 GMT LOG:  duration: 15.000 ms  statement: COPY custom_cache_tables.counts_by_website (website_id, training, species_count, occurrences_count, photos_count) TO stdout;

There are no further references to the table until 03:15 when there is the following:
2018-02-14 03:15:01 GMT LOG:  duration: 3100443.000 ms  statement: DROP TABLE custom_cache_tables.counts_by_website
2018-02-14 03:15:01 GMT ERROR:  table "counts_by_website" does not exist

The DROP of the table is part of the custom cache tables module rebuild of the table content - that is a correct statement, but what is really weird is that the table seems to have disappeared.  I can only think that this occurred as a result of the backup as it is the only difference between this event and previous successfull events.

It would be good if this could be investigated so we understand what happened.
