### ISSUE TITLE
Download page confusing to access

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#314]
The Download page is confusing to get to. 
I was trying to provide support this morning, and didn't actually realise this page even existed.
It is the "Explore" menu->"Download" option I am referring to

1. The Download menu item with sub-items actually has an active parent, I thought the "Download" was just a label and not clickable.
2. The issue from point one is exaggerated because it seems a double-click is required on the parent "Download" item. It doesn't respond to single click.

**Comment by DavidHepper** [comment]
The menu option could helpfully be renamed 'Download records' but I've only ever needed a single-click from Firefox or IE to reach the Download page.

The confusing things about Download are that:

- The **Download Types** offered in the picklist seem to depend on the user's account permissions in unexpected ways.
- The **Filter to apply** field disappears if certain Download Types are selected.
- There is no indication that you need to download Surveys one at a time to get the custom fields included in the CSV.

**Comment by kitenetter** [comment]
I believe that the double-click is only needed for those users who have permission to download data for LRCs - having that permission produces the sub-items that @andrewvanbreda refers to. Non-LRC users are not affected.

I will add a Help page about downloads next time I'm working on them.

**Comment by andrewvanbreda** [comment]
Hi,
It was actually Martin Harvey who noticed the double-click was required after I reported my state of confusion to him (as he had pointed me towards the download page with a link in an email). 
My initial observation was that I couldn't find the page relating to the URL he sent me in the iRecord menu system due to the behaviours I described above.

I just thought I would raise that it confused me, so if you prefer to update help then that is fine by me.

**Comment by DavidHepper** [comment]
Understood. Menus should never require a double-click, which I'm sure was never intended.
It is indeed confusing having an upper- or mid-level menu that is itself clickable. My policy would be that only the bottom-level (leaf) menu items should go to pages. In this case the general **Download records** page would be reached by **Explore > Download > Download records**.

**Comment by andrewvanbreda** [comment]
Yes, I prefer only having leaf menu items going to pages also.

Just a quick answer to your other questions. I am an experienced Indicia developer, but I haven't really used this particular iRecord page much.
In the code, it looks like the Download Types come from a few places. It looks like it is mostly interested in verification filters, and these are setup in the background by BRC and would not be user editable, however they can be affected by the expertise settings on your account.
If you have a specific example I might be able to answer for you.

Filter to apply: Not sure exactly how these are affected by the Download Type selection without looking in detail at the code. I did notice what is available is dependent on the Download Type though, so if it disappears there is probably just nothing to show.

Again in reference to what you say about the fields, attributes/fields can be setup for individual surveys only. I assume if all surveys is selected we wouldn't show all the fields as if you have access to lots of surveys you might end up with a massive CSV file where most columns are unused most of the time.
Although as you say this might need to be clearer on the page.

**Comment by johnvanbreda** [comment]
@kitenetter Can you confirm which of the 3 following menu layouts you'd like for downloads:
Explore
    Download
        Download records
        (other download pages)

or
Explore
    Download records
    Other download options
        (other download pages)

or
Explore
    Download records
    (other download pages)

The first is easy to implement, but means you have to go Explore > Download > Download records for the standard page, which will seem like an extra unnecessary click to most users. The 2nd solves that, but needs additional code to delete the "Other download options" link when no options are available. The 3rd solves those problems, but the Explore menu could be quite long for admin users.

**Comment by kitenetter** [comment]
The second option seems best, assuming that the additional coding required is not too big a task. 

If it is a big task then the first option would still be an improvement over what we currently have.

**Comment by kitenetter** [comment]
Maybe need to revisit after the ES downloads are in place, and I know that we've had discussions elsewhere about the Drupal menu behaviour that seemed not to be easily resolvable. Closing for now.
