### ISSUE TITLE
Add "All records" filter as a standard option for verifiers

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#315]
Can we add "All records" to the list of filter options available as standard to verifiers?

![image](https://user-images.githubusercontent.com/16039111/36375769-8a56a1a2-1568-11e8-9081-e169f7b01ce3.png)

It's often easiest to use an All records filter when trying to check up on records that may already have been queried or verified. Such a filter can be created by any individual verifier, but it would be good to have it there as standard.

Question before proceeding: if a verifier has already set up their own "All records" filter, and we then add it to the standard list, will then end up with two filters called "All records"?

**Comment by DavidHepper** [comment]
This would be good but it is easy to select the 'All records' filter under the Quality criterion button. 
Of significantly more use would be to simplify the Quality criteria from the baffling list (containing such gems as "Recorder thought the record was at least likely") to a list of checkboxes, one for each possible Status and Query status, and even Certainty if enough people use this.

**Comment by kitenetter** [comment]
The options are different, and I think better, on the ES page. Closing.
