### ISSUE TITLE
Unable to add iRecord user as Activity admin

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#316]
I am trying to add another user to one of the Natural England activities. The edit link is:
https://www.brc.ac.uk/irecord/centre-activities/edit?group_id=1143&dynamic-from_group_id=993

The user name is "fenns and whixall volunteer", warehouse ID 68043, real name "Huxley, Paul".

When I try to find "Huxley, Paul" in the lookup to add him as an admin his name does not appear.

**Comment by johnvanbreda** [comment]
Hi @kitenetter I'm pretty sure this user originally registered as Tom Mather - does this make sense?
