### ISSUE TITLE
Linking new account to warehouse taking too long (almost 3 mins)

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/iRecord#317]
When signing up to iRecord (also noticed on NPMS), the sites are taking AGES to link the account to the Indicia Warehouse during registration.
This occurs once the user receives their email, and they click Login after clicking on the email link.

This is currently supposed to take seconds, but is currently taking almost 3 minutes making users think the system has frozen.

**Comment by andrewvanbreda** [comment]
@johnvanbreda can you look at this. Perhaps issue with the Warehouse? or the code can no longer work with the current number of users without further optimisation.

**Comment by johnvanbreda** [comment]
Fixed
