### ISSUE TITLE
NBN Atlas DwC verification statuses

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#319]
Part of #304.
Note that NBN have now announced that want level 1 and level 2 verification terms in one attribute, for which the termlist is:
* Accepted
* Accepted - Correct
* Accepted - ConsideredCorrect
* Unconfirmed
* Unconfirmed - Plausible
* Unconfirmed - Unreviewed

(I assume that the lack of a space in “ConsideredCorrect” is deliberate, will check.)

**Comment by kitenetter** [comment]
The lack of a space in “ConsideredCorrect” **_is_** deliberate.

Awaiting confirmation as to whether there should be spaces either side of the hyphen or not (have seen both forms).

**Comment by kitenetter** [comment]
New and definitive list from Sophie:

Accepted
Accepted - correct
Accepted - considered correct
Unconfirmed
Unconfirmed - plausible
Unconfirmed - not reviewed

**Comment by johnvanbreda** [comment]
With spaces?!

**Comment by kitenetter** [comment]
Yes!
