### ISSUE TITLE
Allow filtering by level of ID difficulty (and rarity)

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#32]
Would be good for verifiers to be able to filter for all records of species with ID difficulty level 5 etc.; also, if we implemented conservation statuses in iRecord it would be good to be able to filter by those. This would allow verifiers to quickly check for potentially difficult and important species (or misidentifications thereof) at times when they are too busy to check through everything, and thus enable unusual records to be followed up promptly.

**Comment by johnvanbreda** [comment]
Agreed. Would this be an additional option under the "Quality" panel?

**Comment by kitenetter** [comment]
I think that ideally it needs to work independently of the Quality filters, so that you could choose to look at, say, all rejected records of species that have ID difficulty level 4. I wonder if it is possible to implement something in the column-heading filters, so that the "auto-check" column can filter by ID difficulty, but maybe it needs to be in the main filter panel. In which case then it either needs to be a new filter type (ideal), or it will have to be incorporated into the Quality choices (workable).

**Comment by johnvanbreda** [comment]
Now done and will be deployed in the next code release
