### ISSUE TITLE
What to do about licence for records which have no explicit licence attached in Dwc-A exports?

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#320]
Part of #304.

**Comment by johnvanbreda** [comment]
Reponse from Martin:
"I assume we can leave these Null as at present, pending further decisions in relation to licences and GDPR, but see second bullet point below. To do: 
•         Need to double-check that this column does pick up any licences that may have been applied via the consultant’s portal
•         Not sure how NBN want to handle datasets that contain a mix of record-level licences, and how that might interact with a dataset-level licence – if they are intending to only use the record-level licensing for datasets that have them then I presume we will have to auto-populate the licence column with CC-BY, as that is what we would be using at dataset level? I will ask NBN."

**Comment by johnvanbreda** [comment]
The NBN guidance on the DwC CSV template states that the licence is a required field so we can't leave it null.

One thought is that if the dataset is going to be CC-BY, then
a) this should be explicit on the terms & conditions (and maybe existing users notified?)
b) we can then tag records with CC-BY in their licence field. This means the licence will be displayed on the record details pages etc, so it is clearer. The licence gets automatically included in the export.

**Comment by kitenetter** [comment]
At the NBN end of things the information from Sophie is:

> my understanding is that if no license column is included in the records file then the license on the dataset is applied to all records. At the moment all the datasets that we have have the same license for all records (I think). We would need to change the text on the dataset page to indicate that the dataset contains a mix of licenses - that would be possible. 

At the iRecord end of things we currently apply the licence specified by us or by the recording scheme concerned to the entire dataset. Most frequently this has been CC-BY, but some schemes have gone for CC-BY-NC (and some NE-related data has gone under an open government licence). We need to consider how this relates to record-level licensing and the terms of use as part of the review relating to GDPR. 

@DavidRoy I don't think we have reviewing GDPR and terms as an issue, should we add it?

**Comment by kitenetter** [comment]
Until such time as we move to user-level licenses we have to implement dataset-level licensing. The iRecord export report needs do this:
- Ensure that any record-level licensing (e.g. from Consultants' Portal data) is shown
- Leave all other records with "licence" = Null

Then at the NBN import end of things a blanker licence will need to be applied to all records EXCEPT those that already have a record-level license; the blanket licence to be the one that is specified in the metadata form for the dataset concerned.

Question for @sophiathirza - is that suggested procedure workable for NBN?

**Comment by sophiathirza** [comment]
Yes, this will be okay. If no license is supplied then it will be taken from the dataset.

**Comment by kitenetter** [comment]
@johnvanbreda I think this means we have a choice between leaving "licence" as Null, or adding another field for "dataset licence" in the automated export content type, so that the value can be added there, and the value used as a parameter to the report to populate "licence".

I think either of those approaches would work.

**Comment by kitenetter** [comment]
Dataset-level licences are being specified in the EML section of the automated export set-up. This is sufficient for now I believe. Closing.
