### ISSUE TITLE
How to handle the rightsHolder field in Dwc-A

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#322]
Part of #304.

**Comment by johnvanbreda** [comment]
Reply from Martin:
NBN definition: “A person or organisation owning or managing rights over the resource”. I assume this equates to the Data Partner for the dataset, which will be BRC for some datasets, but will need to be the relevant recording scheme for others. Possibly could be automatically resolved by using the tool for linking taxa to schemes that Steph has been working on? But in short-term there is a need to create separate datasets as per the existing scheme/project filters for NBN upload, and to populate this column accordingly. Not sure what implications that has for automating the export process.
(Long-term one could think about adding the associated schemes or projects as attributes for the records, and NBN allowing links to be made to those attributes, but that would require a new approach for both us and NBN.)

**Comment by johnvanbreda** [comment]
Would a suitable solution be to add a rights holder field to the automated export content type, so you can add the value there? I can then submit the value as a parameter to the report so it gets included with every record in the download.

**Comment by kitenetter** [comment]
Answer to @johnvanbreda : yes, that sounds like a good solution.
