### ISSUE TITLE
gridReference to use output_sref field value in Dwc-A

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#323]
Part of #304.

Suggest using the output_grid_ref for consistency and because it copes with blurring. If we do that, then the coordinateUncertaintyInMeters is already accounted for so can be set to 0?

**Comment by johnvanbreda** [comment]
Reply from Martin:

> Agree that output_grid_ref is the one to use. Re coordinateUncertaintyInMeters, NBN guidance is that this should contain the grid ref precision where a grid ref is being used (which we can calculate), or an estimate of uncertainty if lat/long is being used, e.g. for app data. Our app does store an accuracy measure, but presumably most app records will end up with an output grid ref, so perhaps we just stick with the grid ref precision? Question: does output_grid_ref ever end up being null or containing anything that is not a grid ref?

**Comment by johnvanbreda** [comment]
Yes, the output_grid_ref can be a lat long if outside the bounds of any of the grid systems we've coded for. It gets formatted with a 3 decimal place accuracy so it looks nice.

My suggestion therefore is:
When output_grid_ref is a grid square, then coordinateUncertaincyInMetres is the size of the grid square.
When output_grid_ref is a lat long and there is a spatial ref precision field provided (e.g. the GPS precision from the app) then we use that.
When output_grid_ref is a lat long and there is no spatial ref precision field provided, then we have to pick an arbitrary estimate of accuracy, e.g. 50?

Does that sound OK?

**Comment by sophiathirza** [comment]
The coordinateUncertaintyInMeters describes the area in which the occurrence was recorded, so the resolution of the record.

GPS precision from the app, I think should go in the coordinatePrecision field - as it describes the error associated with the coordinates, unless it really does describe the area in which the occurrence may have been. This is not a required term.

**Comment by japonicus** [comment]
Doesn't GPS precision effective describe the bounds of a recording area - so fit in the coordinateUncertaintyInMeters field? That appears to be the way it's used in TDWG's documentation:
http://rs.tdwg.org/dwc/terms/index.htm#coordinatePrecision where 30m is given as an example; whereas coordinatePrecision is specified for GPS in terms of fractions of a degree.

**Comment by sophiathirza** [comment]
That's great then, thanks. I wasn't sure what was meant by GPS precision from the app, so just wanted to mention it.
