### ISSUE TITLE
georeferenceVerificationStatus in Dwc-A exports

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#325]
Part of #304.

How to handle georeferenceVerificationStatus? Either set to the same as the identificationVerificationStatus on the assumption the verified checked both, or leave as "Unconfirmed"? Same question for georeferenceVerificationStatus2.

**Comment by johnvanbreda** [comment]
Reply from Martin:

> identificationVerificationStatus is labelled as a required field, so presumably it needs to be added to the download, but I suggest we leave this as Null (although NBN may default that to “unconfirmed”). As yet there is no guidance on how geographical verification should be done.

**Comment by johnvanbreda** [comment]
I think if a field is required, then surely it has to be present AND populated? Therefore shall I put unconfirmed in the field value?

**Comment by kitenetter** [comment]
Info from Sophie is that NBN will reconsider whether this field needs to be a required one. In the meantime she is happy for us not to include it (I think this means not including this attribute at all, rather that including it but setting it to null).

**Comment by sophiathirza** [comment]
georeferenceVerificationStatus is not a required field, so you can ignore it. It won't be given a default value.

**Comment by johnvanbreda** [comment]
Ok, closing as the georeferenceVerificationStatus were never in the beta code.
