### ISSUE TITLE
Is Dwc-a individualCount numeric only?

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#326]
Part of #304.

Martin to check.

**Comment by kitenetter** [comment]
From Sophie:

> The individualCount field can take non-numeric values. GBIF records an error when it does - but it's okay to include. An alternative is to use the organismQuantity and organismQuantityType field, which is useful when the quantity value is on some kind scale (such as SACFRON).

**Comment by kitenetter** [comment]
individualCount not currently included in the test report - should be added I think?
