### ISSUE TITLE
Dwc-A occurrenceRemarks to include any comment made at the sample level?

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#327]
Part of #304.

Should occurrenceRemarks include any comment made at the sample level?

**Comment by johnvanbreda** [comment]
Reply from Martin:

> I think it would be good to include sample comments, but I don’t know if NBN are able to accept additional custom attributes beyond the defined list. I will find out.

**Comment by kitenetter** [comment]
To include sample comments the only DwC term I can find is eventRemarks: http://rs.tdwg.org/dwc/terms/#eventRemarks

Suggest we used that unless @sophiathirza has an alternative suggestion?

**Comment by johnvanbreda** [comment]
@sophiathirza We have comments attached either directly to the occurrence, or higher level comments attached to the sample/event. Would it make sense therefore to use eventRemarks for sample comments and occurrenceRemarks for occurrence comments?

Also the comments we are talking about here are comments made by the recorder or person who input the record. Should comments appended after record entry by other users also be included (e.g. verifier responses)?

**Comment by sophiathirza** [comment]
Sorry, I missed the comments above.

Yes, that would make sense to use eventRemarks for sample comments and occurrenceRemarks for occurrence comments. I imagine that would mean that the eventRemarks would be the same for all occurrences in the one sample - which is okay.

There is also identificationRemarks, which might be useful for comments made after the record was input. There is nothing to say that you have to include all comments made on the record.

**Comment by kitenetter** [comment]
I would be wary of including additional comments (such as those by verifiers) until we have reached consensus on supplying verifier names and other GDPR matters. The sample and occurrence comments seem to me to be clearly part of the record and therefore okay to include.

**Comment by johnvanbreda** [comment]
Ok, there is now both occurrenceRemarks and eventRemarks in the develop branch of the code, so it will be updated the next time I do a full code update on the warehouse.
