### ISSUE TITLE
Handling of species name as recorded in Dwc-A

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#328]
Part of #304.

The NBN Atlas format only includes the scientific name, so any vernacular names will be translated to the current preferred name. What about synonyms - should they be output in their original form or also translated?

**Comment by johnvanbreda** [comment]
Reply from Martin:

> Personally I would prefer to see the current recommended name, with the original name as entered perhaps added as another custom attribute. However, I will ask NBN if they have a view on this. I presume that NBN are also matching older synonyms to the current recommended name within the Atlas itself so perhaps in the end it won’t make a difference, but that assumes that NBN and we are matching synonyms in exactly the same way.

**Comment by sophiathirza** [comment]
I don't think that it matters whether it's the current recommended name or the synonym as the Atlas uses the UKSI for the names matching and it matches synonyms to the recommended name.

We can accept vernacular names, so they could be included as well. What the Atlas isn't able to match are vernacular name TVKs. The order of the name matching routine is: TVK, then scientific name, and finally vernacular name. So if the TVK match fails, it tries the scientific name, and then finally the English name (if available).

**Comment by johnvanbreda** [comment]
Thanks. What field should the vernacular names be provided in? I can't see one in the DwC specification.

At the moment we have 2 name related fields in the code I've written:
* taxonID - we populate this with the taxon version key of the current recommended name associated with the record.
* scientificName - currently populated with the recommended name associated with the record.

So the way it is right now, the actual name used by the recorder is not provided. The Atlas will match against the provided taxonID and it should work OK. If the record was input using a synonym, then we could do the following:
* taxonID - the taxon version key associated with the synonym.
* scientificName - the synonym itself.

The Atlas should then presumably match against the taxonID of the synonym. So far so good. What I'm less certain about then is what to do if the record was input as a common name. If we treat the common name as an "English synonym" then we'd do the following:
* taxonID - the taxon version key associated with the common name.
* scientificName - the common name itself.

However I think you are saying that the taxonID wouldn't match in this case so it would attempt to match the common name. But, aren't there huge risks with matching on common names (e.g. Redshank occurs for several different taxa)? Also it doesn't feel right to include the common name in the scientificName field. We could instead just provide the info for the recommended scientific name but this means the name used by the recorder would be lost - as Martin says it would be nice to capture this somewhere.

Any thoughts?

**Comment by sophiathirza** [comment]
There is a vernacularName term, which you can use.

I agree that there is a risk in matching on common name. I mentioned it more for information. 

There is a previousIdentifications term: http://rs.tdwg.org/dwc/terms/#previousIdentifications, in which you could put the name used by the recorder.

**Comment by johnvanbreda** [comment]
Ok, so just for clarity, I will do the following:
1) If the recorder used a recommended name OR a synonym during data entry then:
* scientificName = name as given
* taxonID = TVK of the name given
* vernacularName = null
2) If the recorder used a vernacular during data entry, then:
* scientificName = name of the recommended latin name
* taxonID = TVK of the recommended latin name
* vernacularName = name as given.

No need to comment on this unless you think I am incorrect.
