### ISSUE TITLE
Use of decimalLat/Long in Dwc-A if gridReference populated

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#329]
If we are always outputting the output_sref in the gridReference field, then does that make decimalLatitude and decimalLongitude redundant? If so, then should I drop them out or leave them in as the gridReference term is not recognised within the DwC specification. Then we would use georeferenceVerificationStatus to imply the accuracy of this field. If we do that, will the NBN atlas use the gridReference in preference to the other fields and will it recognise that the precision relates to the lat long fields?

**Comment by johnvanbreda** [comment]
My understanding of the NBN guidance is that they wish to see either a grid ref, OR a lat/long, not both. And if we go with grid ref (which I think we should) then the grid ref precision should be given under “coordinateUncertaintyInMeters” (see Q4 above). Question: how could we “imply the accuracy of this field” in georeferenceVerificationStatus?

**Comment by johnvanbreda** [comment]
@kitenetter The difficulty with dropping decimalLatitude and decimalLongitude from the record is that the gridReference field is not an official term in DwC. Therefore if the records are passed to another DwC compliant system from the Atlas, they won't actually have any recognisable georeferencing info.

**Comment by sophiathirza** [comment]
When records are uploaded in the Atlas with a grid reference, the Atlas calculates the lat/long coordinates for each record, and it's the new coordinates and the coordinate uncertainty in meters that are used in the darwin core archive that is sent to GBIF.

I think that we should try using grid reference and the coordinate uncertainty in meters terms, even though gridReference is not a darwin core term.

**Comment by johnvanbreda** [comment]
Personally I think that where the record has a GPS lat long and an accuracy available, then it makes more sense to supply that in decimalLatitude and decimalLongitude rather than our calculated output_sref field as a gridReference. This is because the latter is an approximation of the best fit square which reflects the size of the circle of inaccuracy, designed for giving consistent report output. If you use this square to recalculate the decimalLatitude and decimalLongitude then they will be slightly wrong.
So, my proposal is:
* If the record is for a point (rather than a grid square), then supply a GPS lat long in decimalLatitude and decimalLongitude. If the record includes an accuracy value, then supply this in coordinatePrecisionInMetres, otherwise set this to 50 (as a fair approximation).
* Otherwise, if the record is for a grid square, then supply that in gridReference and supply the size of the square in coordinatePrecisionInMetres.

Is that OK?

**Comment by sophiathirza** [comment]
For the NBN that is okay.

There are no access controls on the Atlas so the public resolution of the data is the same as the supplied resolution.
