### ISSUE TITLE
Refresh/commit button for verifiers

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#33]
BDS have requested that the verification grid should not refresh automatically when filters of verification flags are applied, but instead the user should click a refresh button when they want the grid to update. 
This is partly to reduce calls on a remote server for those with limited wifi, and partly to allow verifiers to consider a set of verification decisions before committing them. 
Need to decide whether this approach is desirable and feasible.

**Comment by johnvanbreda** [comment]
I think this is probably a good idea and it would also apply to the other Explore pages. I would suggest:

* Change the Apply button on each of the filter popups to a "Save" button which stores the change in the filter without applying it.
* Add an Apply Changes button to appear under the set of filter panels (e.g. to the right of the "Save Filter As" controls). This button would only appear when there are changes to apply.

Do you agree?

**Comment by kitenetter** [comment]
I agree.

**Comment by DavidRoy** [comment]
Agreed

**Comment by kitenetter** [comment]
ES verification functionality now addresses this - closing.
