### ISSUE TITLE
Additional attributes for NBN Atlas Dwc-A export

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#330]
Martin's comment:

> If NBN is able to handle additional custom attributes, I’d suggest:
> •         Sample comment (see Q8 above)
> •         Verifier name – personally I would be in favour of including this, but it probably needs consultation among the schemes
> •         NE have a requirement for their project code to be included as an additional attribute in the data on NBN (they wish to be able to search on NBN for data relating to particular projects, although it is not clear to me that NBN allows searching at that level of detail). See: https://github.com/BiologicalRecordsCentre/iRecord/issues/304#issuecomment-361968100
> •         BDS responded to the above NE requirement by adding another request, that the iRecord attribute “External key” should be included in the NBN datasets, so that if data has originated elsewhere and imported to iRecord, when it arrives at NBN both the iRecord unique ID and the source’s unique ID are shown. See: https://github.com/BiologicalRecordsCentre/iRecord/issues/304#issuecomment-362011129 
> 
> If we can include any of the above additions, then we need to agree an appropriate Darwin field to import them into – assuming that NBN can deal with this at all (which I will enquire about).
>

**Comment by johnvanbreda** [comment]
@kitenetter to confirm with the NBN.

**Comment by kitenetter** [comment]
From Sophie:

> We can import custom attributes but at the moment they are not included in the download unless they are darwin core terms. So ideally we should try and identify a darwin core term for all attributes and use the dynamicProperties term for fields that don't fit an existing term. The list of the darwin core terms is here http://rs.tdwg.org/dwc/terms/ let me know if I can help with these.

And:

> It will only be possible to search on darwin core terms. Any darwin core terms that are not included in the template will need to be added to the index so that it can be searched and filtered on, so please let me know what terms you use. We should be able to find a suitable term for project ID. Is it different to the Survey Key, which we have mapped to collectionCode?

collectionCode is fine for holding the NE Project codes, which are sample attributes applying to sets of records (https://github.com/BiologicalRecordsCentre/iRecord/issues/304#issuecomment-361968100)

However, the external keys (https://github.com/BiologicalRecordsCentre/iRecord/issues/304#issuecomment-362011129) are occurrence attributes for individual records and I think will need a different Darwin mapping? otherCatalogNumbers looks a good candidate:
http://rs.tdwg.org/dwc/terms/#otherCatalogNumbers

**Comment by sophiathirza** [comment]
For the external keys, you could also use the recordNumber term.

The unique iRecord ID should be in the occurrenceID field but there was a mistake when the data was imported from the Gateway and often the iRecord ID is in the recordNumber field: e.g.: https://records.nbnatlas.org/occurrences/916970e7-6890-442f-aebf-ffec58d3eb9a. When these datasets are updated the occurrenceID is replaced with the recordNumber value.

**Comment by kitenetter** [comment]
@sophiathirza can I clarify this please: 
- the unique iRecord ID for each record should always go into occurrenceID
- any additional record ID (stored as "External key" within iRecord) could go in to EITHER recordNumber OR otherCatalogNumbers

Looking at the DwC definitions, otherCatalogNumbers seems more appropriate, as recordNumber talks about being something that is applied in the field.

Should we go with otherCatalogNumbers based on the DwC definitions, or go with recordNumber as that is already in use? 

If we do go with recordNumber, is there any danger of confusion given that this attribute has previously been used to store what should really be occurrenceID data?

I'm assuming that the next time we export iRecord data to NBN it will be another complete dataset export that will replace what is currently on NBN, and that therefore the wrongly allocated recordNumber values will get removed anyway?

**Comment by kitenetter** [comment]
I had suggested that we might want to include the verifier's name as an additional attribute, but I cannot find an appropriate DwC term for this.

@sophiathirza do you know of a suitable term?

@DavidRoy do you have a view on whether it is in fact desirable to include verifier names, or is this something we need to consult on among the verifiers?

**Comment by sophiathirza** [comment]
Yes, the recordNumber values will be removed when the records are next updated.

I don't think that it matters which field you use. otherCatalogNumbers is perhaps more self-explanatory. I don't know whether it will display by default on the occurrence record page, we may need to add it, which is okay.

Would otherCatalogNumbers need to be in the simple download or is it okay to only include it in the full darwin core download?

recordNumber is already included in the simple download but I agree that it might be confusing, as we have already been using it for the iRecord ID.

**Comment by sophiathirza** [comment]
We use the identifiedBy term.

**Comment by kitenetter** [comment]
Thanks @sophiathirza. The identifiedBy term is used for the person who determined the species name isn't it? The verifier is a separate category for the person who made the judgement as to whether the record is accepted or not, so would need a separate field I think?

Maybe this is one to leave for now and re-visit if required.

**Comment by sophiathirza** [comment]
The darwin core definition is: The name(s) of the person(s) who applied the currently accepted Scientific Name to the Cataloged Item.

We have been using it as the name of the person who gave the taxon name to the record. Often it's the same as the recordedBy term.

**Comment by kitenetter** [comment]
Yes, that is my understanding too. But the verifier is something different. I think we'll have to leave it out for now.

**Comment by sophiathirza** [comment]
Ah, sorry. No, there is nothing in darwin core for the verifier name. If we have a good argument for it, we may be able to get it added to darwin core. I know that gbif have a project to look at improving data quality, so it might be good timing to approach them.

**Comment by kitenetter** [comment]
For clarification, I believe that from the above we have agreed:
- TO RETAIN occurrenceID as the appropriate DwC term for the unique iRecord ID for each record
- TO RETAIN otherCatalogNumbers as the DwC term for an external record ID (stored as "External key" within iRecord)
- **TO ADD** collectionCode as an additional exported attribute, to hold the NE Project codes
- TO DEFER exporting of verifier names pending a suitable DwC term and consultation with verifiers

**Comment by sophiathirza** [comment]
This sounds okay.

The unique ID of the record must be occurrenceID.

**Comment by johnvanbreda** [comment]
See #324. NE Project Codes added to datasetID term in develop branch.
