### ISSUE TITLE
DwC-A export names missing authority

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#331]
Question from Martin:
scientificName field - why are most names taxon plus authority name, but some are taxon only? Even when the TVKs are the same? Looks like it might be a NatureSpot issue.

**Comment by johnvanbreda** [comment]
@kitenetter The NatureSpot team manage their own list of names and don't specify the authority. Indicia has no knowledge of whether the NatureSpot names given take precedence or defer to those in the UKSI list so we use the names as they provide them.

**Comment by kitenetter** [comment]
Question: how do TVKs get assigned to NatureSpot names, are they managed by the NatureSpot team or do we add them subsequently? If the TVKs can be relied upon then presumably we could link back to the names (with authorities) that we are using elsewhere. Not sure if this needs any further action though, as I believe NBN will in any case use the TVK where available.

**Comment by johnvanbreda** [comment]
The NatureSpot team allocate the TVKs themselves and I think they are at least mostly reliable. Although we could do as you suggest, I am not sure it is worth it and I'm also keen to avoid introducing any "special rules" where we don't need to.
