### ISSUE TITLE
eventDate in ISO 8601 format

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#332]
Comment from Martin:

> eventDate: we are not yet outputting the ISO 8601 format that NBN recommends (or maybe we are but Excel is reformatting it when I open the CSV file?)

**Comment by johnvanbreda** [comment]
@kitenetter If you open the csv file in a text editor you should see that the date is correctly formatted. E.g. the first record in the NNR dataset is 2013-06-30.

**Comment by japonicus** [comment]
I'd asked about this on the NBN message board. Sophie Ratcliffe's [just replied](https://forums.nbn.org.uk/viewtopic.php?pid=28266#p28266) to say that the recognised form for an open-start date is a '/' prefix, e.g.

`/1977-14-06`

**Comment by sophiathirza** [comment]
Yes, this is what our developer recommended.

**Comment by johnvanbreda** [comment]
Ok, I'll think I can map all our dates to something sensible now, thanks.
