### ISSUE TITLE
identificationVerificationStatus2 field location

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#333]
Comment from Martin:

> I would prefer the CSV file to have “identificationVerificationStatus2” adjacent to “identificationVerificationStatus”, especially if we are going to make this NBN/Darwin format available to all users via their download page.

**Comment by sophiathirza** [comment]
We no longer need the identificationVerificationStatus2 field (or the georeferenceVerificationStatus2) now that we are combining the two verification status fields.

**Comment by johnvanbreda** [comment]
Thanks @sophiathirza - presumably the guidance will need an update to reflect this?

**Comment by sophiathirza** [comment]
Yes, I have updated the csv template and template guide on the Atlas to reflect the changes: https://nbnatlas.org/help/share-data-nbn-atlas/.
