### ISSUE TITLE
Can we avoid proliferation of notifications to undeliverable email addresses?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#334]
An ever greater number of "undeliverable" messages now fill up the iRecord email inbox, presumably the result of people registering on iRecord and then changing email address without updating their user account (although I think the latest batch includes a number send to biodiverseit that were presumably for testing purposes?). 

At the moment this is more of an irritation that a significant issue, but the time taken to deleted all the undeliverable messages is inevitably growing.

For now I have set up an email rule to shift undeliverable messages into their own folder, but is there anything cleverer we can do prevent iRecord repeatedly sending notifications to non-functioning email addresses?

**Comment by johnvanbreda** [comment]
We could add a flag to the people table which indicates if the email address is believed to be defunct. Then this could be manually edited (or we could add a tool that you paste broken email addresses into) to set this flag. The email notification code would then be configured to skip addresses where this flag is set.
A better solution would be to detect the incoming emails and automatically set the flag but I'm not sure how feasible that is - @BirenRathod may be able to comment?
We should take care to ensure that a temporary failure to send an email does not set the flag thus permanently stopping emails.

**Comment by kitenetter** [comment]
This is a low priority - closing.
