### ISSUE TITLE
Navigating the Activity organisations

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#335]
More organisations are setting up activities, and we now have more than one page of organisations.

If you go to Activities and then to the tab for "Organisations offering activities", you can of course see the first page of organisations. If you then click on the "2" button or the "next" button at the bottom, to go to the 2nd page, you get taken back to the "My activities" tab. If you then click back on to Organisations you are on page 2 of the organisations, but that's not a very intuitive way to do things.

**Comment by johnvanbreda** [comment]
A copied and pasted bit of configuration had set @ajax=false on this grid - removed and therefore fixed.
