### ISSUE TITLE
Moth families no longer working as filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#341]
Following the UKSI update, some moth species (mainly macro-moths) seem to have lost links to their families. The informal group "insect - moth" seems to be working okay, but verifiers with separate filters for macro and micro moths are missing most of the species that should be there. E.g. if you use the Explore pages and filter by family Noctuidae there are no records showing.

I guess this is due to some change in the UKSI taxon hierarchy, but I didn't think moths had been changed much this time round?

**Comment by kitenetter** [comment]
Have now had a report that the family Agromyzidae (leaf-mining flies) has also lost links to its species.

**Comment by kitenetter** [comment]
Looks like Tachinidae is also affected.

**Comment by kitenetter** [comment]
Longhorn beetles Cerambycidae also affected. It's odd that it seems to be affecting random families across many different taxa.

**Comment by johnvanbreda** [comment]
Fixed. I don't know why but one of the last steps of the UKSI update should rebuild all the hierarchical data and there were indeed some families with nulls in the data. Re-running the same scripts has filled in the blanks.

**Comment by kitenetter** [comment]
Many thanks @johnvanbreda
