### ISSUE TITLE
Remove ambiguity in icons on verification grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#343]
Request from David Hepper, agreed by @kitenetter and @DavidRoy:
The green tick icon that shows a record has passed all the auto-checks is very similar to the green tick icon for verifiers to mark a record as considered correct, and has caused confusion for verifiers.

Suggest we do not display an icon at all for records that pass all the auto-checks - this will make the verification page a bit cleaner and give more emphasis to the records that don’t pass the checks.

**Comment by johnvanbreda** [comment]
@kitenetter Although I agree in principal, that means records which have not yet been checked by record cleaner will not be distinguishable from those which have. So I think a better option might be to remove the "passed" icon as suggested above but add an icon to those which are still awaiting a check (e.g. an hourglass, with a hint "Pending check by automated rulesets"). Or, just find a better passed icon?

**Comment by MNSmith** [comment]
To be honest, when verifying records I never bother to look at the "auto-check" icon, you could remove the column from the verification page and make more room without worry.

**Comment by kitenetter** [comment]
@johnvanbreda I think either of your proposals would be an improvement. Initially I favoured the hourglass approach for those awaiting a check. However, given that we don't have rulesets for all taxa, there is an argument for distinguishing between those that have passed and those that haven't been checked at all. So does that mean that the best solution is to find a new 'computer-says-yes' icon that is different to the 'accepted record' green tick?

**Comment by johnvanbreda** [comment]
@kitenetter A green P (rather like a driver's just passed plate) might suffice? In relation to @MNSmith's comments, we could enable the column configuration popup (as used in Pantheon) to turn off columns? Or, rename this column to just "RC" (record cleaner), then remove all padding and make the icons a tad smaller would help with real estate a bit.

**Comment by DavidHepper** [comment]
How about these icons for the **Auto check** column?
- Unassessed by the Automated Checker (or pending reassessment e.g. after an edit): show a cog wheel icon with mouseover pop-up help "Pending Auto-check";
- Where the record passes all Automated Checks: show no icon.

**Comment by johnvanbreda** [comment]
@kitenetter - I think we all agree on passed being no icon, so can I ask you to decide on an icon for pending check please. Options are a cog, green P, or an hourglass, with a hint "Pending auto-check".

**Comment by kitenetter** [comment]
@johnvanbreda @DavidHepper I'm not sure we are agreed that records that pass all auto-checks should have no icon!

I felt that it was useful to be able to distinguish between those records that have passed auto-checks, and records of taxa that have no auto-checks available. Which I think means we do need an icon for those that pass the auto-checks, and the green P seemed to be appropriate for that.

For records in the process of being assessed I have no strong favourite, so let's go with David's proposal of a cog icon plus hint "Pending auto-check".
