### ISSUE TITLE
Odd use of "{1}"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#344]
I've started seeing "{1}" in various places in iRecord, e.g. this species record:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=6549009

![image](https://user-images.githubusercontent.com/16039111/37254538-2333c00c-2537-11e8-986a-c69a40e52705.png)

The explore buttons from that species page also seem to be affected:

![image](https://user-images.githubusercontent.com/16039111/37254543-3a9dfe9c-2537-11e8-9958-a5724bed2773.png)

I saw something similar on an Activity page recently as well.

**Comment by johnvanbreda** [comment]
Fixed.
