### ISSUE TITLE
Older records not displaying on some pages/maps.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#345]
I wanted to look at all of the records for Osmia (Osmia) cornuta on the system as we are asking people to look out for this "new to Britain" species.
So far this year we have had 2 records which have been verified and display on the "Explore all Records" and the "Species Maps" page.

We had 3 additional records entered last year, 2 for 2017 and 1 for 2014.  None of these 3 older records display on either of the two maps using an appropriate filter ( Sp = Osmia (Osmia) cornuta), Records = Accepted, Age = 5 Years).  The Species Maps page only lists 2 records for this species.

The missing records are  4833030, 4766345 and 4693121.  All of these can be found using the appropriate filters on the Verification grid.

Possibly this is linked to a problem reported via the iRecord forum the other day, I cannot see all of a recorders history if I click on the number on the Experience tab on the verification screen.

**Comment by kitenetter** [comment]
If you go to any one of the 'missing' records they are visible:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=4833030

and if you then use the buttons from that page to "Explore records" they are all there:
https://www.brc.ac.uk/irecord/all-records?filter-date_age=&filter-indexed_location_list=&filter-taxon_meaning_list=183854

and similarly if you go to the details page they are all there:
https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=183854

So it appears that the filters are behaving differently in some places compared to others.

**Comment by johnvanbreda** [comment]
Hi @MNSmith - I've fixed the problem. Where there were preferred name changes (Osmia cornuta -> Osmia (Osmia) cornuta counts) my UKSI import script needed an extra step to tidy this up which I've now added.
