### ISSUE TITLE
Query over sensitive records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#348]
There are two routes by which records may be flagged as sensitive:
- Marked as sensitive by the recorder, with a user-defined level of grid-ref blurring applied
- Records of species on the NBN agreed list of sensitive species will be auto-blurred (not yet implemented in iRecord, will be done soon)

Question for @johnvanbreda : how are user-flagged sensitive records being handled in the exports to NBN, are they being included, and if so are we blurring the the grid ref?

Question for @sophiathirza : are records of species in the NBN Sensitive list being blurred at the NBN end, regardless of the grid ref provided in the iRecord export?

For future reference, NE have made a request that iRecord should continue to provide records of species on the NBN sensitive list at full capture resolution, so that NE will in future have the options of allowing full access to these records in certain circumstances.

NE (Andy Webb) request:
> There’s an outstanding query around the export of Sensitive Species records. There is development work in progress on the Atlas to give data partners the ability to manage full access to Sensitive Species records held in the Atlas. We plan to use it, but its not finished and there are uncertainties around funding to complete it, which will need to be next FY. We would therefore want the full location details passed with the export dataset(s) to the NBN Atlas, rather than having them ‘blurred’ on export from iRecord. This ought to be a general approach - leaving iRecord still blurring those records when viewed/downloaded from iRecord.

**Comment by johnvanbreda** [comment]
@kitenetter User flagged sensitive records are included in exports but are blurred. 

Regarding the latter point about exporting full precision to the Atlas, we would need a field to flag the records as sensitive in the export in a way that the Atlas would recognise. I think we also need to be transparent about this to the recorders - I recently had a query about sensitive badger sett data being made available to the Atlas from iRecord with the concern that Defra licenced cullers might gain access to the data at full precision.

**Comment by kitenetter** [comment]
My understanding (which may be wrong) is that the Atlas will be blurring **all** records of the set of sensitive species, which includes badgers, regardless of how they are supplied. So maybe we don't need to flag them specifically on export? But we do need to blur the species within iRecord itself, as agreed following the badger data isssue.

**Comment by sophiathirza** [comment]
The Atlas blurs the location of all records of species that are on the sensitive species list for the particular country. The location is only blurred if the supplied resolution of the record is greater than the required blurred resolution for the particular species in the particular country.

**Comment by johnvanbreda** [comment]
@kitenetter As well as the list of records on the sensitive species list, there are those which are flagged as sensitive by the recorder, e.g. because of local issues, consideration of site sensitivity etc. If we supply these at full resolution then we are not operating in the way the recorder would have expected. If we supply these at full resolution with a sensitive flag set so the Atlas blurs them, then it allows NE to have privileged access. Though this brings me back to my original point that we need to be transparent about this and very clear, so there is no misinterpretation about who could gain access to the precise record location.

**Comment by sophiathirza** [comment]
The Atlas will only blur record those records on the sensitive species lists, it will not blur records that have a sensitive flag set.

**Comment by kitenetter** [comment]
@johnvanbreda I wasn't proposing that we should supply user-flagged records at anything other than their blurred resolution. My query was in relation to the NBN-flagged sensitive species - I thought you were proposing that we needed to add a flag in our exports to these species, which I thought was unnecessary because NBN are automatically blurring these, but perhaps you were only questioning the user-flagged ones?.

So I think we are in agreement, we are just misunderstanding each other! I think we're saying we will:
- Supply user-flagged sensitive records to NBN at their user-chosen blurred resolution
- Supply records of NBN-flagged sensitive species to NBN at capture resolution, with blurring being applied by NBN
- [And add equivalent blurring within iRecord reports, maps etc. for any NBN-flagged sensitive species]

**Comment by johnvanbreda** [comment]
I think there is also the issue of records which were submitted at full precision of sensitive species, knowing that they will be blurred automatically. In these instances the recorder may well assume that marking the record as sensitive themselves is not necessary, not realising there is a difference in behaviour. So, although I agree with the bullet points above, that does not negate the need to have a clear statement of policy regarding sensitive species records so that it is unambiguous who gets access to the full record. 

On a technical note, iRecord doesn't really separate user-applied vs automatically applied sensitivity so it would be easier to supply them all at full precision but with a blur flag.

**Comment by kitenetter** [comment]
Re your technical note, that appears to conflict with Sophie's previous comment that the Atlas "will not blur records that have a sensitive flag set" so in the short term at least I think we will have to implement blurring within iRecord and within the files we export to NBN.

**Comment by MNSmith** [comment]
As an addition to this, I have downloaded records flagged as "sensitive" in some of my datasets.  In the "Site Name" field I see the comment "Sensitive. Lat   long is approximate.", the "Original Map Ref" field is empty but the "Output Map Ref" field contains the full 6 or 8 figure OS Grid Ref.

From a Recording Scheme point of view, I think it is important to distinguish between the "dot on the map" displayed on iRecord or the NBN and the geo-location precision.  As a Scheme Organiser I want to see the full geo-location so I can relate it to other records in my scheme.  When I send my own dataset off to the NBN which includes iRecord data I will "blur" any records myself but I still want to see the data.

A couple of other points.  The Recorder can tag any record as "Sensitive", thus affecting mapping, not listed "sensitive" species.

Some species like Great Crested Newt (Fully protected, Schedule 5, consultants provide fees to LRCs for data etc) are not actually included on the JNCC "Sensitive Species" list so will not have their locations automatically blurred when they really should be.  I think this is part of the NE "District Level Licencing" process.

**Comment by kitenetter** [comment]
Closing this issue and transferring to #407
