### ISSUE TITLE
Query over DwC basisOfRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#349]
Query for @sophiathirza : iRecord does not store data that can be used to populate basisOfRecord. Should we populate this with "not recorded" (which is what we are currently doing) or leave it Null?

**Comment by sophiathirza** [comment]
If the records are field observations, then the value needs to be HumanObservation. 

The most common alternatives are FossilSpecimens and PreservedSpecimens.

It is a required field and we need it populated so that we can distinguish between field records and natural history collection specimens.

**Comment by kitenetter** [comment]
Thanks @sophiathirza. However, few of the iRecord records have any unambiguous way of telling whether the record is of a species identified in the field, or a species collected and subsequently identified under the microscope. And in fact there are some records on iRecord that will have been derived from museum specimens but we won't necessarily know which ones.

So is there a way of specifying that this attribute is unknown (which is what I'd prefer to do), or do we have to stick with HumanObservation in the knowledge that it won't be correct in all cases?

**Comment by sophiathirza** [comment]
I don't know what to suggest for the best here. The default is HumanObservation - that is what gets sent to GBIF if no basisOfRecord is supplied.

If the basisOfRecord is not known then perhaps it is best to set it as Unknown, but I am not sure how GBIF would handle that.

**Comment by johnvanbreda** [comment]
Under section 1.4 of http://rs.tdwg.org/dwc/terms/simple/index.htm, there is reference to the basisOfRecord being one of the list of Darwin Core classes (LivingSpecimen, PreservedSpecimen, FossilSpecimen, MaterialSample, HumanObservation, MachineObservation, Event, Occurrence, Taxon, Identification, Organism, Location, GeologicalContext, MeasurementOrFact, ResourceRelationship)

Looking through these, Occurrence seems like the correct class: "An existence of an Organism (sensu http://rs.tdwg.org/dwc/terms/Organism) at a particular place at a particular time.". Shall I use that?

**Comment by kitenetter** [comment]
Well-researched @johnvanbreda - I agree that Occurrence looks like the best solution to this.

**Comment by sophiathirza** [comment]
Our controlled vocabulary is "PreservedSpecimen", "FossilSpecimen", "LivingSpecimen", "HumanObservation", "MachineObservation", and I think that we would prefer if you don't know which one to select, then 'Unknown' would be the best alternative.

However, at the moment, I don't think that it matters.

**Comment by johnvanbreda** [comment]
I've set it to Unknown, though I do so under mild protest ;)! Isn't the point of adopting DwC that we should stick to the standards and recommendations it provides? Unknown is not in your vocabulary and it's also not in the DwC recommendations that this should be a DwC class, so I think Occurrence is better personally.

**Comment by sophiathirza** [comment]
then make it Occurrence.
