### ISSUE TITLE
Unhelpful refresh behaviour

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#35]
BDS: "In some circumstances (e.g. invalid selection in a column-heading filter) the animated 'Refresh in progress' symbol  remains over both the map and the recordset, indicating (falsely) that the query has not finished. No error message is shown and it is not clear that control has already been passed back to the user to edit the offending column-heading filter or click 'Reset' "

**Comment by johnvanbreda** [comment]
This is fixed in the develop branch of code so will be deployed soon.

**Comment by kitenetter** [comment]
@johnvanbreda can we close this?

**Comment by johnvanbreda** [comment]
Not yet.
