### ISSUE TITLE
Tidy up term list for Stage (extended)

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#353]
In termlist http://warehouse1.indicia.org.uk/index.php/termlist/edit/136

@kitenetter to delete the terms:
"[Do not use] Queen", "[Do not use] Worker", "teneral", "Pupae"

@johnvanbreda to:
Move all adult -> Adult
Move all larva -> Larva
Remove “adult”, “larva”

**Comment by kitenetter** [comment]
@johnvanbreda I have deleted "[Do not use] Queen" and "[Do not use] Worker", but I cannot find "teneral" nor "Pupae" in the termlist. However, they are still appearing in the dropdown on the recording forms, e.g. at https://www.brc.ac.uk/irecord/ne-single-record

**Comment by johnvanbreda** [comment]
I've just discovered that the lowercase term variants are actually synonyms (in the dictionary sense) of the terms with leading caps. So an alternative approach here is to add a filter to the drop down sample attribute configuration:
@extraParams={"preferred":"t"}
This causes it to only show the preferred version of each term. Is that OK?

**Comment by kitenetter** [comment]
That sounds okay - I just went to edit the NE form but it looks like you'd already done it? Looks like it is working well.

I think there have been one or two other termlists where we've wanted to combine terms. Does this synonym behaviour offer a more general solution, and if so how does one specify that one term is a synonym of another?

**Comment by johnvanbreda** [comment]
Synonyms in terms does provide a solution for combined terms with the same meaning, but there is no current UI for combining 2 existing terms. Instead you should create the termlist with the main preferred term, then list all the synonyms on that term's edit page. If there is a need we could either write a script for merging terms, or perhaps better, code this into the UI.

**Comment by kitenetter** [comment]
Will revisit the script/UI issue next time we encounter a situation that requires terms to be merged.
