### ISSUE TITLE
Miscellaneous questions (non-urgent)

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#354]
I'd be grateful if anyone can answer these questions for me as and when convenient!
- [ ] If I need to delete a record in the warehouse (e.g. if test data has been entered) I first find the relevant sample, then look for any linked occurrences, then mark each occurrence as deleted, then mark the sample as deleted. That takes quite a long time - are there any shortcuts, e.g. do I actually need to delete the individual occurrences if I am going to delete the sample?

[further questions to be added as they arise]

**Comment by JimBacon** [comment]
You only need to mark the sample deleted (and set updated_on and updated_by_id).

If you look at the database you will see the samples table has a trigger called sample_delete_trigger. This calls the procedure cascade_sample_delete. If you look at Trigger Functions (below tables in pgAdmin) you will see cascade_sample_delete which marks occurrences, sample_attribute_values, sample_comments and sample_media all as deleted. When it updates the occurrences to be deleted this, in turn, causes another trigger which will call cascade_occurrence_delete. This marks the occurrence_attribute_values, occurrence_comments, occurrence_media and determinations as deleted.

"What about the cache tables?" I hear you ask. I don't have an instant answer to that. Perhaps depends on whether you are doing this through pgAdmin or the web interface.

Jim.

**Comment by johnvanbreda** [comment]
The cache tables for samples are updated immediately the change is applied via the web interface, not on scheduled tasks. Therefore if deleting through pgAdmin you will need to delete from the cache tables as well, but via the web interface it should be OK.

**Comment by kitenetter** [comment]
Thanks both. As far as I'm aware I don't have the ability to edit or delete via pgAdmin, so I'm using the web interface to the warehouse (warehouse1.indicia.org.uk). So it sounds like I can just mark the sample as deleted, without doing anything to the occurrences.

For the web interface, do I need to worry about updated_on and updated_by_id?

**Comment by JimBacon** [comment]
No. If you are using the web interface all you need to do is delete the sample and everything else is taken care of.
