### ISSUE TITLE
Enhancement - Verification levels

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#355]
I know I have mentioned this a few times before in various meetings, but I think it about time I got it on the Github pages.

I would like to see the addition of 3 different levels of Verification ability, No 1 at the bottom and No 3 at the top.  Records verified by a level 1 recorder would still appear on the Verification grid of higher level recorders until that verifier was "signed off" by a higher level verifier, ideally at an individual species level.  This would fit nicely with the Local - County - National Recorder model and allow mentoring of verifiers within the system.

The reason I am prompted to write this - I have downloaded the verified Tachinid records for the last year for processing and inclusion in the recording scheme database and submission to the NBN.  However, I find that that a good number of records have been verified by people other than myself or Chris Raper, some of whom I have never heard of and have no idea of how competent they are at verifying Tachinid flies.  These names all appear to be associated with the NatureSpot system.

This means I have to go through all these records on an individual basis to reverify them.  As iRecord does not allow me to select records on a "verified by" basis, I am having to search for records individually using a copy/paste of the record number from the download spreadsheet.  This is very slow and not ideal.

**Comment by kitenetter** [comment]
@MNSmith I think we are close to being able to more easily filter the verification grid to show "records that have been verified by verifiers other than me", see #9 

The 3 levels of verification ability might be a useful enhancement but adds complexity and raises the question of on what basis verifiers can be graded in such a way (which relates to the BWARS work on developing a more evidence-based system which is being discussed next week). But let's see how the filtering system works once that is in place and whether that alleviates the problem.

**Comment by DavidRoy** [comment]
I do support some thinking/work in this area.  It has been raised by other verifiers, e.g. https://www.brc.ac.uk/irecord/node/7225

**Comment by kitenetter** [comment]
The ES verification page makes it easier to view records verified by other verifiers. For BWARS at least there may be some additional options in the future following the work that is being done on a verification tool under PoMS. Closing for now.
