### ISSUE TITLE
New activity within hierarchy is not displaying the global activity

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#357]
Natural England have an organisation set up in activities. That organisation has a global activity "Ad hoc records": https://www.brc.ac.uk/irecord/organisation-global-activities/list?dynamic-from_group_id=978

There are a number of centres under the organisation. As expected, the centres that were originally set up include the "Ad hoc records" global activity.

I have just set up a new centre, "NE species records": https://www.brc.ac.uk/irecord/centre-activities/list?dynamic-from_group_id=1275

This new centre has not inherited the global activity.

Is this a bug, or is there something else I need to do to make the global activity appear?

**Comment by kitenetter** [comment]
I need to find a solution for this today or tomorrow! I could just create a new activity within the new centre, "NE species records", that does the same thing as the global activity would have done. Is that the best thing to do in the short-term?

**Comment by johnvanbreda** [comment]
Hi Martin
Global activities are "semi-global" - they are available for all centres, but only if you turn them on. So to fix this you'd need to masquerade as Andy Webb (or have admin permissions to the ad hoc records activity), then edit the group (https://www.brc.ac.uk/irecord/organisation-global-activities/edit?group_id=1120&dynamic-from_group_id=978). You can then tick off the centres that the activity should appear for. I've done this for you in this instance.
Cheers
John
