### ISSUE TITLE
Transfer NE data to "Natural England Surveys"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#358]
The steps are:
1. Work out a query that lists all the records which need to be moved and their sample IDs.
2. Run a query that changes the survey ID for all the samples.
3. Run a query that updates the cache_occurrences_functional.survey_id and cache_samples_functional.survey_id fields for these samples.
4. Run a query that updates the cache_samples_functional.survey_title field. 

In addition we need to be able to assign a survey_reference_code to each set of data, see below.

For step 1, the records to move are:
- All records with group_id = 982; related survey_ids are 42, 93, 100, 374; should be 4,040 records; survey reference code needs to be set to: "NEFU"
- All records with group_id = 992; related survey_id is 374; should be 21 records; survey reference code needs to be set to: "RP00316"
- All records with group_id = 1120; related survey_id is 42; should be 3 records; survey reference code needs to be set to: "uncoded"
- **_TO BE CONFIRMED:_** All records with group_id = 1143; related survey_ids are 42, 374; should be 231 records; survey reference code TO BE CONFIRMED

@kitenetter to provide confirmation for the fourth of those filter settings.

The target survey that all these records need to be moved to is survey_id 509 Natural England Surveys.

**Comment by kitenetter** [comment]
@johnvanbreda do we need to treat the different originating surveys separately? 
- Records from survey 42 (iRecord general) should be fine to transfer
- Records from survey 93 (iRecord Import) should be fine to transfer
- Records from survey 100 (Multi-site records) have a rather different data structure I think - is it going to be possible to transfer these?
- Records from survey 374 (iRecord app) also have a rather different data structure - is it going to be possible to transfer these, or would we be better off keeping them in the app survey and maybe updating the group_id to match the new NE activity pages?

**Comment by kitenetter** [comment]
@johnvanbreda 

This is an attempt to simplify things a little, based on the assumption that it is relatively easy to move data from surveys 42 and 93 into 509, but relatively difficult to move from 100 or 374 into 509. Is that assumption correct, does this seem sensible to you?:

Records to move are:
- All records with group_id = 982 AND survey_id = (42 OR 93): move to survey_id 509; set Survey Reference Code to: "NEFU" [3898 records]
- All records with group_id = (1120 OR 1143) AND survey_id = 42: move to survey_id 509; set Survey Reference Code to: "uncoded" [77 records]

Not moving:
- All records with group_id = 982 AND related survey_id = 100 OR 374: leave as is [183 records]
- All records with group_id = 992 AND related survey_id = 374: leave as is (unless it is feasible to move from the app survey to the NE survey - if so, survey reference code needs to be set to: "RP00316") [21 records]
- All records with group_id = 1143; AND related survey_id = 374: leave as is ((unless it is feasible to move from the app survey to the NE survey - if so, survey reference code needs to be set to: "uncoded") [157 records]

Update the report code for NE export to DwC and custom download (cf #351 ):

```
where o.website_id=23 
and (
  o.survey_id in (97, 509)
  OR o.group_id in (973, 978, **982, 992,** 1120, **1143,** 1275)
)
```

**Comment by johnvanbreda** [comment]
@kitenetter I think your assumptions are correct. Looking at the suggestion here I think it is OK except there are 19 records of stage pre-adult (group ID 982) and there is no pre-adult term in the extensive version of the stage term list. Is it OK to add it? Or map to a better term?

**Comment by kitenetter** [comment]
@johnvanbreda I suggest that we map "pre-adult" to "immature" - I can't see any problem with doing that.

**Comment by johnvanbreda** [comment]
Hopefully all done correctly - it was fairly complex so worth checking. Here's the script for reference:

```SQL

-- records to move to survey 509 and add reference code NEFU
select o.id, o.sample_id
into temporary to_fix
from cache_occurrences_functional o
where group_id=982 and survey_id in (42, 93) and website_id=23

-- sample stuff
update samples set survey_id=509, updated_on=now() where id in (select sample_id from to_fix);
update cache_samples_functional set survey_id=509, updated_on=now() where id in (select sample_id from to_fix);
update cache_samples_nonfunctional set survey_title='Natural England Surveys' where id in (select sample_id from to_fix);
-- Don't bother with first name, last name and email from old survey as all records for logged in users.
delete from sample_attribute_values where sample_id in (select sample_id from to_fix) and sample_attribute_id in (35, 58, 8);
-- Switch EUNIS habitat attribute over.
update sample_attribute_values set sample_attribute_id=1065 where sample_attribute_id=209 and sample_id in (select sample_id from to_fix);

-- occurrence stuff
update cache_occurrences_functional set survey_id=509, updated_on=now() where id in (select id from to_fix);
-- switch stage to comprehensive version
-- This change requires a termlist_term_id update in the attribute values, so find the mappings
select t1.term as from_term, t2.term as to_term, t1.id as from_id, t2.id as to_id 
into temporary terms_fix
from cache_termlists_terms t1 
join cache_termlists_terms t2 
  on (t2.term ilike t1.term or t1.term='pre-adult' and t2.term='Immature')
  and t2.termlist_id=136
where t1.termlist_id=127;
-- Now do the update
update occurrence_attribute_values av
set occurrence_attribute_id=124, int_value=tf.to_id
from terms_fix tf
where av.occurrence_attribute_id=106 and av.occurrence_id in (select id from to_fix)
and av.int_value=from_id;
drop table terms_fix;
-- Update this into the cache
update cache_occurrences_nonfunctional o
set attr_stage=t.term
from occurrence_attribute_values av
join terms t on t.id=av.int_value
where o.id in (select id from to_fix)
and av.occurrence_id=o.id
and av.occurrence_attribute_id=124;

-- Add the NEFU reference code
insert into sample_attribute_values (sample_attribute_id, sample_id, text_value, created_on, created_by_id, updated_on, updated_by_id)
select 1144, sample_id, 'NEFU', now(), 3, now(), 3 from to_fix;

drop table to_fix;

-- records to move to survey 509 and add reference code uncoded
select o.id, o.sample_id
into temporary to_fix
from cache_occurrences_functional o
where group_id in (1120,1143) and survey_id=42 and website_id=23;

-- Now, Repeat the sample stuff and occurrence stuff blocks from above.


-- Add the uncoded reference code
insert into sample_attribute_values (sample_attribute_id, sample_id, text_value, created_on, created_by_id, updated_on, updated_by_id)
select 1144, sample_id, 'uncoded', now(), 3, now(), 3 from to_fix;

-- input forms
update cache_occurrences_functional set input_form='ne-single-record' where input_form='enter-casual-record"' and website_id=23 and sample_id in (select sample_id from to_fix);
update cache_samples_functional set input_form='ne-single-record' where input_form='enter-casual-record' and website_id=23 and id in (select sample_id from to_fix);
update samples set input_form='ne-single-record' where input_form='enter-casual-record' and id in (select sample_id from to_fix);

drop table to_fix;
```

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - have you updated the code for the NE export to NBN, so that if I run an export it should include the transferred records? Will run the export this evening.

**Comment by johnvanbreda** [comment]
Yes, they should be updated - here's the commit for you to check: https://github.com/BiologicalRecordsCentre/indicia-reports/commit/ca18a99fe6fef23d1fb0d67dc3d76a039856b9bf

**Comment by kitenetter** [comment]
@johnvanbreda this is an additional request from NE related to the data transfers. NE would like to be able to view all the older NE data via the more recently set up "Natural England surveys" Activity (group_id = 1120).

Assuming that this does not raise any complications that I haven't considered, please can you run a database update to link ALL records that are in the "Natural England Surveys" dataset (survey_id 509) to the "Natural England surveys" Activity (group_id = 1120).

**Comment by johnvanbreda** [comment]
Please can you confirm that this means moving records out of the existing groups "NEFU Surveys 2017" (ID 986, 3898 records) and "NNR: Fenn's, Whixall & Bettisfield Mosses" (ID 1143, 107 records), not just assigning a group ID to those which don't currently have one in this survey.

**Comment by kitenetter** [comment]
Thanks for checking that @johnvanbreda 

Please move the existing "NEFU Surveys 2017" (ID 986, 3898 records) into group ID 1120.

Please leave the "NNR: Fenn's, Whixall & Bettisfield Mosses" (ID 1143, 107 records) where they are.

**Comment by johnvanbreda** [comment]
Done. Here's the script for info:
```sql
select id as id_to_change, sample_id as sample_id_to_change into temporary to_update
from cache_occurrences_functional 
where website_id=23
and survey_id=509 
and group_id=982;

update samples set group_id=1120 where id in (select distinct sample_id_to_change from to_update);
update cache_samples_functional set group_id=1120 where id in (select distinct sample_id_to_change from to_update);
update cache_occurrences_functional set group_id=1120 where id in (select distinct id_to_change from to_update);
```
