### ISSUE TITLE
Error message in Activity summary display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#359]
I've just created a (temporary) activity page at;
https://www.brc.ac.uk/irecord/groups/summary?group_id=1280&implicit=

In the "Trending" tab, where photos would normally be displayed, I'm getting an error message:

> Here are a few of the photos recently uploaded for this activity.general_errors.There was an SQL error: ERROR: canceling statement due to statement timeout - SELECT COUNT(*) FROM ( SELECT * FROM cache_occurrences_functional o JOIN cache_occurrences_nonfunctional onf on onf.id=o.id JOIN cache_samples_nonfunctional snf on snf.id=o.sample_id JOIN cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id JOIN websites w on w.id=o.website_id and w.deleted=false JOIN occurrence_media om on om.occurrence_id=o.id and om.deleted=false JOIN cache_termlists_terms mtype on mtype.id=om.media_type_id JOIN users privacyusers ON privacyusers.id=o.created_by_id JOIN locations lfilt_context on lfilt_context.id in (1806) and lfilt_context.deleted=false and st_intersects(coalesce(lfilt_context.boundary_geom, lfilt_context.centroid_geom), o.public_geom) and not st_touches(coalesce(lfilt_context.boundary_geom, lfilt_context.centroid_geom), o.public_geom) WHERE o.training=false AND (o.website_id in (23) OR privacyusers.id=1 OR privacyusers.allow_share_for_reporting=true OR privacyusers.allow_share_for_reporting IS NULL) AND o.website_id in (101,43,13,97,87,33,29,44,98,12,24,14,17,6,8,25,11,7,30,5,27,34,40,32,42,51,49,65,73,68,75,9,71,88,10,69,23) AND o.media_count>0 AND o.release_status='R' AND o.confidential='f' AND o.sensitive=false AND o.taxon_rank_sort_order >= 300 LIMIT 9) AS subquery

**Comment by johnvanbreda** [comment]
I've improved the performance of the photos query considerably. There are other slow queries on the activities summary but they will benefit from possible use of Elastic Search.
