### ISSUE TITLE
Filter management

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#36]
Produce spec for filter management tool, to see all available filters, flagged with whether they are system-supplied or custom, and be able to choose which filters you want to see for Explore, Verify and Download. Not high priority.

**Comment by kitenetter** [comment]
Include Oli's request for national-level verifers to be able to filter by VC (i.e. include standard location filters in the "Where" options)

**Comment by johnvanbreda** [comment]
Minor config done to add the location types for filtering (including VC boundaries).

**Comment by kitenetter** [comment]
Not currently required, closing.
