### ISSUE TITLE
In hierarchical activities, can we add NNR boundaries using "Manage centre sites"?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#361]
(Not urgent, and not a requirement for the NE project.)

If I've understood correctly, the "Manage centre sites" button for a centre allows you to set up a list of sites that will then be available for use in any activities associated with that centre. I wanted to try adding the NNRs to the NE Surveys centre. However, the "add an existing site" dropdown seems to only offer sites with boundaries that I have set up myself. 

![image](https://user-images.githubusercontent.com/16039111/38047938-d5990e5a-32bb-11e8-9414-3d813e425186.png)

I do have a number of NNRs included in my "My sites" list, but these My-sites-NNRs don't get carried across to the dropdown for "Manage centre sites".

Is it possible to add the NNR site definitions to the list of sites for the centre?

**Comment by johnvanbreda** [comment]
This requires a change to the report library/locations/locations_available_for_group.xml. It currently lists just sites you created, not any others in your My Sites list. @kitenetter let me know if this is a priority.

**Comment by kitenetter** [comment]
@johnvanbreda since individual activities can already choose NNRs from the lists in the "Where" part of their filter, there is presumably no benefit from including them in the "Manage centre sites" function. Which I think means that "Manage centre sites" is only needed for those organisations that are creating new site boundaries within iRecord (rather than asking us to import shapefiles for them).

If I've understood that correctly then no further action is needed.

**Comment by johnvanbreda** [comment]
Correct.
