### ISSUE TITLE
Question: verification status codes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#364]
Occurrence attribute record_status contains five different codes, but I only know the meaning of three of them:
- C = ready for checking = not yet reviewed
- V = verified = accepted
- R = rejected = not accepted

What are:
- D
- I

**Comment by kitenetter** [comment]
Hi @johnvanbreda this question has arisen again - thanks

**Comment by johnvanbreda** [comment]
I = In progress, intended to be used when a data entry form has not been completely filled in so should be withheld from reports. However I think it's been used by mistake on occasion.
D = dubious. Now superceded by the querying functionality but still present for backward compatibility.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda  

For the record, I've looked at the verification status terms in conjunction with whether they are flagged as human decisions or machine decisions (occurrences.record_decision_source). We have a couple of anomalies:
- record_status = C (not reviewed): 16,954 occurrences flagged as human decision and 64 as machine decision - I don't understand how their can be a decision source for records that haven't yet been reviewed?
- record_status = V (verified): 422,027 occurrences have no decision source, which I guess means they are records that came into the system before we were flagging decision sources - presumably they are all human decisions?

I don't the above anomalies are causing any problems, so will close this issue.
