### ISSUE TITLE
Verification Page - Recorder experience tab not working

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#366]
Currently, the Recorder Experience tab is not working correctly on the verification grid.
Looking at my Tachindae verfication grid, I have a Recorder with 7 records waiting to be verified. 

If I look at the Recorder experience tab, I can see he had logged 987 Diptera records and has had 57 of these verified.
If I click on the Verfied total (57) I end up with an empty grid - I do not see what other verified Diptera records this Recorder had.
If I click on the Total Records (987) the grid returns only the 7 Tachinid records awaiting verification, the other 980 do not appear.
As I am only seeing Tachinid records when I click on these numbers I suspect that the filters behind the numbers are not working correctly.

**Comment by johnvanbreda** [comment]
The verification explore page (used to display the records when you click on the experience link), is currently limited to only show the records for your verification filter. Therefore although the totals shown are all diptera, only tachinids will appear on the report due. I agree this is confusing - just need @DavidRoy or @kitenetter to confirm that they are happy for verifiers to have access to all the verification records in the group, not just those which match there filter.

**Comment by DavidRoy** [comment]
If this is just to view records then yes.  Verification/edit rights should not extend beyond existing verification filters

**Comment by johnvanbreda** [comment]
Done
