### ISSUE TITLE
Cannot view records in training mode

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#369]
Viewing a record says it cannot be found. Editing is still possible though. Here is a training record submitted with the general recording form on the website:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=6663399

<img width="739" alt="screen shot 2018-04-22 at 12 07 36" src="https://user-images.githubusercontent.com/7383162/39094332-ca73efe0-4625-11e8-8471-52604c60cf3a.png">

**Comment by johnvanbreda** [comment]
Fixed in the develop branch.
