### ISSUE TITLE
Unable to add some Activities to My activities

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#372]
If one iRecord user makes another an Administrator of an Activity, the gold star is no longer available and the other person has no way to add the activity to the My activities tab. See the attached example screenshot of the available actions but the missing gold star. It would be helpful (and less fragile) for the gold star to be present always. 
![activity actions - but gold star missing](https://user-images.githubusercontent.com/24915271/39245265-26a12d84-488b-11e8-968d-a9c2fe10140e.jpg)

**Comment by DavidHepper** [comment]
Clubtail Count 2018. 
Not only has that not happened (for Gen Dalley) but it isn't even on my own **My activities** tab! I think the coding would be simpler if it didn't check but always showed the gold star icon, even it's a by-invitation Activity. Any error msg could appear when the **Join** button is clicked. (Joining when you've already joined shouldn't cause a problem.)

**Comment by kitenetter** [comment]
The activity is set to not become active until 1 May - I'm not certain if that is what has caused the lack of visibility but it may well be.

**Comment by DavidHepper** [comment]
If so, it's trying to be too clever!

**Comment by DavidHepper** [comment]
If so, it's trying to be too clever. Admins should be able to admin in advance of the start and I can't see why anyone should be stopped from joining early.

**Comment by johnvanbreda** [comment]
Rather than set the activity start date (which defines when the activity becomes available), you could set the date filter for "Records that are of interest to the activity". Does that help?

**Comment by DavidHepper** [comment]
Yes, thanks. That worked. It isn't very obvious, though.
