### ISSUE TITLE
Add the ability to show species phenology charts

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#373]
Idea suggested by a user - e.g. could be added to the species details pages, or a group report showing the first and last record of any species within the current year.

**Comment by DavidHepper** [comment]
Worth noting but we already have the Phenology chart available to verifiers. BDS philosophy is that iRecord is for data-collection and verification whereas NBN is for retrieval and mapping.

**Comment by kitenetter** [comment]
Being addressed via current work on data visualisations - closing.
