### ISSUE TITLE
Verifiers Summary report has broken

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#374]
The Verifiers Summary report used to work. The report below, which should show many thousands of verifications, now brings up three records as verified by 'White, Steve' and nothing else:
![image](https://user-images.githubusercontent.com/24915271/39425991-dfae3cac-4c75-11e8-85e0-d33a01f2671c.png)
Note that the Location Type and Location params are deliberately unspecified in this case but entering a VC here does not help the report to produce results.
It would also be useful if the Date parameters would indicate in the field help whether **Record date** or **Verification date** is being specified.

**Comment by DavidHepper** [comment]
Now I'm getting a timeout asking for 'insect - dragonfly (Odonata)' records from 01/01/2017: 
`general_errors.There was an SQL error: ERROR: canceling statement due to statement timeout - SELECT COUNT(*) FROM ( SELECT DISTINCT oc.verified_by_id FROM cache_occurrences_functional o JOIN occurrences oc on oc.id=o.id and oc.deleted=false JOIN users vu on vu.id=oc.verified_by_id JOIN people vp on vp.id=vu.person_id JOIN users privacyusers ON privacyusers.id=o.created_by_id WHERE o.training=false AND (o.website_id in (23) OR privacyusers.id=1 OR privacyusers.allow_share_for_reporting=true OR privacyusers.allow_share_for_reporting IS NULL) AND o.website_id in (101,43,13,97,87,33,29,44,98,12,24,14,17,6,8,25,11,7,30,5,27,34,40,32,42,51,49,65,73,68,75,9,71,88,10,69,23) AND o.website_id = 23 --iRecord only AND o.taxon_group_id=107 AND o.date_start >= '2017-01-01' LIMIT 42) AS subquery`

**Comment by johnvanbreda** [comment]
@DavidRoy this report will be slow because the verified_by_id field is not in the cache tables and the report is grouped by that field. This is a report that could probably work well with Elastic, so an option is to wait for that investigation. Or, I can add the verified_by_id to cache_occurrences_functional but it will need a background task to update it so isn't a completely trivial task.

**Comment by DavidHepper** [comment]
The 'Verifiers summary' is still broken, with or without a date range. Have I missed the ES version?

**Comment by kitenetter** [comment]
@DavidHepper I'll email you a link to the test page for an ES report.

**Comment by DavidHepper** [comment]
Thank you. That's not quite the same but it works for me.

**Comment by kitenetter** [comment]
We have an overlapping discussion under #519 so I'm closing this one and continuing there.
