### ISSUE TITLE
Location Name should be a required field for all BDS and Dragonfly recording forms

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#375]
At the recent training sessions on iRecord, BDS verifiers were unanimously in favour of making the Location Name field 'required', as a useful sanity check for the grid ref or lat long, avoiding many gross errors. I strongly support this.

**Comment by MNSmith** [comment]
Agreed - a location name should be required for all records.

**Comment by johnvanbreda** [comment]
Done for the single and multiple dragonfly forms on iRecord.

**Comment by DavidHepper** [comment]
@johnvanbreda please check that the Location is being copied to all rows of the enter-dragonfly-list form. It is only entered once. I've received reports that the first record of the list saves but subsequent records in the same list report error "The data could not be saved" and "[sample:location_name]" with various browsers. See attachment.
![image](https://user-images.githubusercontent.com/24915271/43033364-113eeace-8cc1-11e8-92c3-8e0927e1dae1.png)

**Comment by DavidHepper** [comment]
Thank you! Much appreciated.

**Comment by johnvanbreda** [comment]
@DavidHepper I was unable to reproduce the original error in my development setup so if you can provide any more information on exactly what steps led to the error then it would be useful. Thanks.

**Comment by DavidHepper** [comment]
Tested this for manual entry into the BDS 'Enter a list of dragonflies (for a site on a date)' form in Training Mode and everything worked as expected. The Location name is Required and gets attached to each species of this multi-species recording form. The form field was not padlocked.
(I'm unable to test Imports because it gets stuck 'Preparing for upload' today.)

**Comment by kitenetter** [comment]
As far as I'm aware this can be closed.
