### ISSUE TITLE
Retaining foreign record keys in iRecord

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#376]
How best to can I retain foreign record keys through iRecord? I believe this was also a recent issue for Natural England keys: see #304.

**Example**: BDS has received 100,000 dragonfly records from BTO for import and verification in iRecord. Each has a source survey (either BirdTrack or Garden BirdWatch) and source record key that needs to be preserved separately from the iRecord record ID. Both fields need to be propagated to the Atlas, too. 

**Implementation**: This should mean simply adding two columns to the 'DRN dragonfly imports' CSV format, with Null/Empty being the default for ordinary records. If I lump these values into the existing Comments field they won't be searchable. I can't do more towards importing BTO records until this is resolved.

**Comment by kitenetter** [comment]
@DavidHepper I don't see any problem with adding these two columns to the DRN imports format. The more difficult question is how they can then be included in the atlas export. I'm happy to look into this but cannot do so before week beginning 14 May, sorry.

**Comment by johnvanbreda** [comment]
@DavidHepper in my opinion you should consider importing the record key into occurrence -> external key. This will then automatically appear in the Atlas export as OtherCatalogNumbers.

If you then add the survey reference code (ID 1144) to the DRN imports dataset then you can use this to import the source survey. This will then appear in the Atlas as DatasetID.

**Comment by DavidHepper** [comment]
@johnvanbreda, yes I'll take your advice on this. Please make **Occurrence::External Key** and **Occurrence::Survey Reference Code** available to Survey **DRN dragonfly imports**. I'm expecting to be able to upload Keys of at least 12 alphanumerics and Survey Refs of "BTO BT" (for BirdTrack) or "BTO GBW" (for Garden BirdWatch) unless these are relational and I need to conform with different codes.

**Comment by johnvanbreda** [comment]
@DavidHepper I've added the survey reference code to the DRN dragonfly import dataset - note that it is a sample attribute, not an occurrence attribute. You should find that occurrence:external_key is already available as it is a core field.

**Comment by DavidHepper** [comment]
Testing these imports (in Training Mode) but am unable to match either of these fields on survey 'DRN dragonfly imports'. All the usual fields match automatically whereas the new fields on the CSV trigger a manual match and are both absent from the 'Maps to attribute' drop-down lists. I'm stuck. Is this a regression problem or were they never enabled fully?

**Comment by kitenetter** [comment]
@DavidHepper I think this is now working - there is a filter in the iRecord import form settings that also needed adjusting.

**Comment by DavidHepper** [comment]
@kitenetter - thanks; nearly there! My test record imported without a squeak. Example ID: **8489835** (Training Mode). I can see the _Survey Reference Code_ set to "BTO BT" as expected but _External Key_ (which should be "OBS181992351") is missing. Is this a permissions issue or is the display form not set to show it to verifiers?
(There is a field on the Comments tab labelled _External reference or other source_ but this is blank.)

**Comment by DavidHepper** [comment]
@kitenetter - Please let us see *External Key* after import - see above. It's the last step of the process.
(I'm unable to reopen this issue in GitHub.)

**Comment by kitenetter** [comment]
@DavidHepper where is it that you need to see it, are we talking about the "details" pane on the right of the verification grid, or something else?

**Comment by DavidHepper** [comment]
Yes, showing in 'details' at Verify is the most important, so that verifiers can query with BTO by quoting a record ID that BTO will recognise. When this is done I'll have confidence to do the big import. 

These two fields should be shown in the details at Explore and must be eligible for export to NBN, too.

**Comment by kitenetter** [comment]
I'll have to ask @johnvanbreda to advise on the verifiers view, I'm not sure what controls that.

I'll add the NBN export issue to the list of things we need to sort out for exporting BDS data, will get back to you as soon as I can.

**Comment by DavidHepper** [comment]
Excellent! I'll test one more and then import the large BTO dataset.
