### ISSUE TITLE
Abundance fields should also allow Exact Numbers for all BDS and Dragonfly recording forms

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#378]
BDS forms have abundance ranges, entered either numerically e.g. "6-20" or by the matching archaic letter code e.g. "C" (originally used for the small columns of a paper recording card). However, we would now like recorders to be able to enter exact numbers, without losing their ability to enter ranges, please. This relaxation should apply to all six abundance fields Ad, Co, Ov, La, Ex and Em.
Note that exact counts have always been allowed in spreadsheet imports using form "iRecord | DRN dragonfly imports".

**Comment by johnvanbreda** [comment]
@DavidHepper how do you envisage this working? Currently the control is a drop down with the available number ranges as options. If we revert to a free text field, how will we enforce that any ranges entered will conform to the existing options?

**Comment by kitenetter** [comment]
BDS forms and dragonfly recording on the iRecord app continue to use number ranges. There is still debate in several recording schemes about the pros and cons of using number ranges as opposed to best-guess integers for abundance, with some expressing the view that we should do away with ranges and only allow integers.

@DavidHepper is this still a live issue for BDS?
