### ISSUE TITLE
Unable to delete records from an import into iRecord Import

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#379]
A user has imported some records, but forgot to assign them to the correct Activity. He wishes to delete the records and re-import. However, when he goes to the edit page for any one of the records he is unable to delete them (this is using https://www.brc.ac.uk/irecord/edit-generic-record?occurrence_id=).

For single records there appears not to be a delete option at all.

For lists of records there is a red cross delele button for individual records within the list (altough it is almost impossible to find the button, as it is nearly completely hidden, in Chrome at least) - if you click on the delete button the records appears to be removed, but after saving it is still there.

**Comment by kitenetter** [comment]
There are also difficulties with editing apparently: "Also, within the same data row it appears that no edits are accepted, e.g. I tried to change Stage and Quantity as an experiment and these were not accepted.  However, I was able to change the date, very strange!"

As yet only one user has reported this, but assuming it is a general problem with the generic form it is likely to be an issue for others as well, and could result in errors creeping in to the dataset.

**Comment by johnvanbreda** [comment]
This form wasn't saving properly when a multi record sample was loaded - now fixed.
The delete icons in the grid look OK to me in both Windows and Mac Chrome - does this problem still occur @kitenetter?
There is a delete button for the entire form in the develop branch so that will arrive after the next full code update.

**Comment by DavidHepper** [comment]
How will we know when "the next full code update" has occurred?

**Comment by DavidHepper** [comment]
- The icons show up in Firefox for me but there is no mouseover pop-up help for them.
- The icons are unusably small in Chrome.

**Comment by johnvanbreda** [comment]
Icons OK now in Chrome so closing.
