### ISSUE TITLE
Import RSPB reserve boundaries into iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#380]
RSPB have today supplied a shapefile containing their reserve boundaries, for use within iRecord. The shapefile is in:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Projects\RSPB\RSPBReserves2018_05_24.zip

These need to be imported and made available in the same way as National Nature Reserves are currently shown.

Not urgent, but needed for development of partnership working with RSPB over the coming months.

**Comment by kitenetter** [comment]
@BirenRathod are you able to pick this one up?

**Comment by BirenRathod** [comment]
Hello @kitenetter

Could you check the exiting boundary be possible to access in iRecord? I will than upload this boundary into existing layers.

**Comment by BirenRathod** [comment]
I have just added the RSPB location id in "Explore my records" report page, you should be able to see the option in the drop down list. See if that works fine or not. I will now checked the existing layers from the database.

**Comment by BirenRathod** [comment]
@kitenetter 
I have uploaded this new boundaries. About 13 new locations have been added.

**Comment by kitenetter** [comment]
Hi @BirenRathod that is working well in "My Records", thanks. Can you enable it in all the other similar filters as well (All Records, Activities, Verification filters).

**Comment by BirenRathod** [comment]
@kitenetter 
I have amended all these pages and added RSPB location id.
