### ISSUE TITLE
Export to NBN - issues to check

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#381]
A few things to double-check:
- [ ] Are confidential records automatically excluded from the export filters (even for filters that were set up some time ago)?
- [ ] Are grid references for sensitive records being blurred in the exported grid refs?
- [ ] Are CC licences applied within the Consultants Portal being carried over into the licence output for exported records?
- [ ] Are zero-abundance records being included in the exports? (And if so, should they be? How is the Atlas displahing them?)

**Comment by johnvanbreda** [comment]
1) Yes confidential records are excluded unless the filter was changed via direct access to the database to include them (which should not be the case I think!).
2) Yes, the default report output uses blurred data.
3) Yes, the licence code should be output in the licence field.
4) Hmm, that's a good question. I think they are being output but either they should not be, or we need to know a field to use which sets a "zero" flag for these records in the output.
