### ISSUE TITLE
BRC Open Access data is not available for iRecord

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#385]
Hello @johnvanbreda 

Any idea, why BRC Open Access data is not available to access from iRecord despite the agreement has been created? The main purpose is to access all records of its surveys via iRecord.

**Comment by johnvanbreda** [comment]
It's because all the data have been loaded onto the warehouse with the training flag set to true.

**Comment by BirenRathod** [comment]
So that means by enabling Training mode in my account will not resolve this problem. Am I right?
if I remove the training status in the database, would that resolve this problem?

**Comment by johnvanbreda** [comment]
If the records are training records, then you can only see them if you are in training mode. If the records are not training records, then you can only see them when not in training mode. So, at the moment you will only see the records when your account has training mode enabled. Also if you are using Explore All Records then note they are > 1 month old so you must remove the date filter.

If these records are real records, then the solution is to remove the training flag from the records in the database (occurrences table and cache_occurrences_functional).

**Comment by BirenRathod** [comment]
@johnvanbreda 

Ok, thanks for your explanation. I'm going to update all records as they are all real.

Thanks again.

**Comment by BirenRathod** [comment]
@johnvanbreda 
Sorry top

**Comment by BirenRathod** [comment]
And can't see in Explore all records too.

**Comment by kitenetter** [comment]
I think I'm right in saying that @StephRorke imported these records into the warehouse using a generic BRC account with email brcdatabase@ceh.ac.uk. That email has not been registered with a user account in iRecord. Could that explain why the records are not visible? If so can Steph register an account?

Apologies if I'm introducing an unrelated issue.

**Comment by BirenRathod** [comment]
I don't think that is the problem because it is accessible via this link -> https://www.brc.ac.uk/irecord/edit-generic-record?occurrence_id=6385015.

**Comment by johnvanbreda** [comment]
@BirenRathod although about 6000 of the records are not training, there are a further 128,000 which are training still:
```SQL
select training, count(*) from cache_occurrences_functional where website_id=98
group by training
```

Also, the other records do not appear because the brc data input user account has the sharing options disabled for some reason - 
```SQL
select username, allow_share_for_reporting from users where id=150129
```

**Comment by BirenRathod** [comment]
Hello @johnvanbreda 
Thanks for finding this out. Yes there are more than one survey and not all records as training false. We will do eventually after thorough checks. At present I only needs first 6720 records.

Ok, I just enabled that. That makes more sense. 

Many thanks again for looking into this. I'm finally now closing this.

**Comment by StephRorke** [comment]
@kitenetter I'm not in the office today, but if a requirement includes the user needs to share for dataflow then that will probably need ticking also. I can try and log on to do this.

**Comment by johnvanbreda** [comment]
Hi @StephRorke - I'll do it for you if you are not around - don't worry.

**Comment by kitenetter** [comment]
The boxes for dataflow are ticked already:
http://warehouse1.indicia.org.uk/index.php/websites_website_agreement/edit/66

**Comment by BirenRathod** [comment]
It is not in website agreement, it is in user settings.

**Comment by kitenetter** [comment]
Okay, thanks. In that case can @johnvanbreda make the change please? If possible I'm hoping to send the data to NBN today.

**Comment by johnvanbreda** [comment]
I've updated the brc_data_input user so the records added under that account are available for data flow. That should make the NBN export include all the records.

**Comment by BirenRathod** [comment]
@kitenetter This is the link -> http://warehouse1.indicia.org.uk/index.php/user/edit_from_person/150429

@johnvanbreda  has just enabled the data flow checkbox.

**Comment by StephRorke** [comment]
Thank you @johnvanbreda

**Comment by kitenetter** [comment]
Thanks everyone, the NBN filter is now including all the records.

**Comment by kitenetter** [comment]
One more question for @johnvanbreda - I've triggered the Anthomyiidae export to run again, but when will that happen? If it's not going to run until this evening that will be too late to get to NBN. Are we able to force it to run earlier?

**Comment by johnvanbreda** [comment]
It happens when cron runs, normally every few hours. You can trigger a run at https://www.brc.ac.uk/irecord/admin/config/system/cron. I've just done one for you.
