### ISSUE TITLE
Review NBN export process

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#386]
The initial export round has worked well. Some things to pick up on before we next do an export in late August:
- should we include zero-abundance records? (see #381)
- review latest NBN data format to ensure we are still matching it

**Comment by kitenetter** [comment]
Add:
- How to handle records that have a 'queried' flag (from #279)

**Comment by kitenetter** [comment]
@johnvanbreda yes there is, partly because we are still finding slight glitches each time we export and partly because NBN's procedures are also still changing. Nothing immediate for you to do, but I need to gather together all the latest feedback and update this issue.

**Comment by kitenetter** [comment]
First of the additional glitches (there will be a few more to add to this list so probably best to wait until I've caught up with all):
- [ ] line breaks in the comments (eventRemarks and occurrenceRemarks) and recordedBy/identifiedBy fields are preventing data being imported cleanly by NBN; can we strip out such breaks during our export process?

**Comment by johnvanbreda** [comment]
Ok, I'll wait, but one might argue that the Atlas should sort out handling of line feeds rather than us. They are valid in comments, surely? I can't find any reference to them not being valid for DwC-A files.

**Comment by kitenetter** [comment]
@johnvanbreda I'd like to close this issue as it has become rather diverse. I can see two outstanding queries:
1. Handling of absence (zero-abundance) records: as far as I can tell we currently exclude these from export, which I am happy with, although we may need to revisit this if NE have a requirement to include them. No action required for now.
2. Handling of queried records. I think these should be excluded from export to NBN, even for those schemes that are exporting unverified records. Is that what we are doing? If not, can we add this exclusion?

**Comment by DavidRoy** [comment]
2. is controlled by filter setting.  Review if filter settings enable what is needed for export

**Comment by kitenetter** [comment]
Filter settings are sufficient to deal with the exclusion of queried records, and this is being done where relevant. Closing.
