### ISSUE TITLE
Problem editing record

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#388]
The record is:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=7158538

The recorder wishes to redetermine it to genus level Yponomeuta, but when he tries to edit it it fails to save and generates a message:

> An error occurred
> There was an SQL error: ERROR: current transaction is aborted, commands ignored until end of transaction block - SELECT "core_validation_rules" FROM surveys WHERE "id" = '90'
> [sample:general] 

If I masquerade as the recorder I get the same result.

The only unusual thing I can see about this record is that there are some odd characters in the photo caption, but no idea if that would cause a problem:

![image](https://user-images.githubusercontent.com/16039111/42960484-dfdb41fa-8b83-11e8-875b-8e73883e1a3c.png)

**Comment by johnvanbreda** [comment]
The odd characters were indeed very odd - each visible character actually required 2 presses of the right arrow to navigate through it as there was a hidden character alongside it. Some sort of mess up with character encodings I think. I'd be interested to know what caption was originally pasted in.

I've cleaned this case up in the database and updated the record.
