### ISSUE TITLE
Vernacular name to be removed

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#389]
There are two British species of wood white:
- Leptidea sinapis (= Wood White)
- Leptidea juvernica (= Cryptic Wood White)

L. juvernica used to be known as L. reali (= Real's Wood White). UKSI seems to have got this a bit confused, and has synonymised L, reali with L. sinapis. And as a result we have "Real's Wood White" as a vernacular name for L. sinapis.

Actions:
- For all records of Leptidea sinapis, link them to the vernacular "Wood White"
- Remove the vernacular name "Real's Wood White" from the iRecord dictionary (or alternatively attach it to the scientific name Leptidea reali, but in that case neither "Real's Wood White" nor Leptidea reali should be shown as current names)

I will pass on the info to UKSI.

**Comment by johnvanbreda** [comment]
Do you want me to make the changes at our end @kitenetter?

**Comment by kitenetter** [comment]
Yes please @johnvanbreda - I'm still uncertain as to how the links between vernacular and scientific work.

**Comment by johnvanbreda** [comment]
I've run the following script, first to find the relevant IDs, then to make the changes (i.e. making the Real's Wood White common name not available for data entry):
```sql

select id, taxon_meaning_id from cache_taxa_taxon_lists where taxon='Real''s Wood White' or taxon='Réal''s Wood White' and taxon_list_id=15
update taxa_taxon_lists set allow_data_entry=false, updated_on=now() where id in (148553, 148556);
update taxa_taxon_lists set updated_on=now() where taxon_meaning_id=393298 and taxon_list_id=15
```

We should be able to close this in an hour or two after checking that the changes have rippled through into the reports and species searches.
