### ISSUE TITLE
Guidance on map polygons

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#39]
Make clearer on the main screen of the interactive maps (not just in the popup button help) that a boundary polygon can only be completed with a double-click on the map itself, not by clicking a button. 

MH to review and enhance guidance pages on map usage

**Comment by kazlauskis** [comment]
I would like to be able to save a custom filter and see that listed on, say 'Explore all records' page filters. Now I have to set it manually again on every page refresh.

**Comment by johnvanbreda** [comment]
Karolis, if you create a filter, you can save the filter as a custom filter to appear in your filters drop down in future. When the filter panel is dropped down there is a "Save filter as" box and button just below.

**Comment by kazlauskis** [comment]
Oh that's so good! Sorry, I didn't notice the 'save as' input, thanks!

PS. this comment should have been on the #36 filter management issue.

**Comment by kitenetter** [comment]
This is covered in the maps Help page, and has not been raised as an issue by users recently. Closing.
