### ISSUE TITLE
Load revised National Trust property boundaries

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#390]
Using source supplied by National Trust on 23/7/18.

Replace existing boundaries for recording forms.

@johnvanbreda how does this affect records already submitted against previous versions of boundaries?

**Comment by johnvanbreda** [comment]
Is this in relation to the nt-property form? This form does link the samples to the appropriate property location_id directly. If you update the boundary_geom field for the existing properties then it won't really matter - there is a small chance that records will fall inside the old version of the boundary and not the new one, but it won't actually cause any technical problems. When you load the record to edit, the record will show as outside the boundary but that's OK. If you are actually going to add a new list of locations then the records will still load the old one when you edit, but you won't be able to pick one of the old ones any more using the search. So, I think that's also OK.

**Comment by kitenetter** [comment]
@johnvanbreda @BirenRathod this is not specific to the nt-property form (although it will affect the boundaries displayed in that form), it is a more general request to make the NT boundaries available throughout iRecord in the same way as we have been discussing for RSPB. So they will need indexing and adding to the filter options for downloads and activities (including organisational activities) etc.

**Comment by BirenRathod** [comment]
@kitenetter 
I have uploaded this onto devwarehouse. So please check this boudary on test.brc.ac.uk/irecord_dev.

**Comment by kitenetter** [comment]
@BirenRathod how do I access the boundaries on the development site? They don't appear as an option on the Explore - All records "Where" filter.

**Comment by DavidRoy** [comment]
Closing as work on NT boundaries taken on by John
