### ISSUE TITLE
Make RSPB reserve boundaries available for verification/download filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#392]
I need to create a download filter for some RSPB reserves, but when I go to the filter page (https://www.brc.ac.uk/irecord/filters/admin-edit) the "Where" filters do not offer RSPB reserves as an option. Please can they be added (required by RSPB ASAP in connection with Chris Packham bioblitzes).

**Comment by johnvanbreda** [comment]
Done.
