### ISSUE TITLE
OS map availability

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#395]
The OS map background seems to be working well on the main generic iRecord forms.

Is there any reason for us not to make the OS backgrounds more widely available (e.g. do we have a limit on how many OS maps we can display)?

If we can use it more widely, is it just a matter of ticking the box for the "OS Leisure" option in the "Base Map Layers" part of the form set-up?

(If so I will add it to the vascular plants/grid recording form, and probably others as well.)

**Comment by JimBacon** [comment]
There is a limit on the number of map views per year. We have paid for 1.2 million 'transactions' per year. The OS developer console is very poor and it is hard to know how much of our quota has been used. 

Our contract runs from 27th June.
We have 4 users of the licence: iRecord, iRecord Land, Honey Monitoring and Test.

For each key I can get a chart like the following for a given time period.
![image](https://user-images.githubusercontent.com/2545390/43404827-57dd1f68-9410-11e8-970c-c70d0ada56cf.png)
I can export the data and sum in excel. This shows iRecord used 10500 'messages'. Who knows whether a transaction and a message are the same thing.
In the same one-month period the other keys recorded 90, 326 and 0.

That looks like we are using around 10% of the available capacity, not allowing for the fact that winter usage will be lower than summer.

My conclusion is that yes, you should go right ahead and use it. You enable it exactly as you describe. 
Be aware that it only covers Great Britain, not the UK.

**Comment by kitenetter** [comment]
Thanks @JimBacon. I've implemented OS maps for the vascular plants form. Closing.
