### ISSUE TITLE
Boundary update for Channel Islands

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#397]
[CI_MarineLimits.zip](https://github.com/BiologicalRecordsCentre/iRecord/files/2244241/CI_MarineLimits.zip)

This boundary should replace the current vice-county location for the Channel Islands (location_id = 1135).

**Comment by johnvanbreda** [comment]
Related - I've added an LRC boundary for the Jersey Biodiversity Centre limits, which is effectively Jersy + territorial waters: http://warehouse1.indicia.org.uk/index.php/location/edit/202728

**Comment by johnvanbreda** [comment]
Another related point - we currently have a countries location type which is indexed. This could be broadened to "countries and crown dependencies" meaning that we can add a polygon for the Bailwick of Jersey and the Bailwick of Guernsey. It's not appropriate to use the latter polygon in the LRC boundaries layer as I have done for Jersey since Bailwick of Guernsey also includes Alderney record centre.

**Comment by kitenetter** [comment]
@johnvanbreda Yes please to having "countries and crown dependencies" - NPMS have a requirement to export data for England, Wales and Scotland with the addition of Channel Islands and Isle of Man, so having those two additional entities in the list of countries would meet their requirements.

**Comment by johnvanbreda** [comment]
I've been provided with Jersey, Guernsey and combined polygons, based on the territorial waters, by the Jersey Biodiversity Centre so can tackle this task. Here's what I plan:
1) Update the VC 113 boundary to a combined polygon for the Channel Islands.
2) Add to the "countries" layer - Bailwick of Jersey and Bailwick of Guernsey polygons.
3) Although I don't have them available yet (David Tipping is trying to obtain them) - add polygons for the Guernsey and Alderney record centres to the appropriate layer.

**Comment by johnvanbreda** [comment]
Done (except separate issue of Guernsey/Alderney record centre polygons)

**Comment by johnvanbreda** [comment]
@kitenetter Actually - leaving this open in case you want an Isle of Man polygon added. If so can one be sourced?

**Comment by burkmarr** [comment]
Closing at @DavidRoy suggestion. We can open a new issue of IoM subsequently required.
