### ISSUE TITLE
Upload new boundaries for Yorkshire Wildlife Trust reserves

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#398]
Yorkshire Wildlife Trust have requested an upload of their reserve boundaries so that they are available for use within the Activities. They have supplied a shapefile (includes multi-part polygons) which is saved into:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Boundaries\YWT Sites.zip

Once uploaded we need these boundaries to be selectable when setting up an Activity, but (assuming that this is possible) I don't think there is a need to make them visible on the main Explore pages.

Question for @DavidRoy - we've agreed that it is okay for us to upload project-specific boundaries into iRecord, but do you think they should be made visible in the Explore pages? Maybe they should if there is no great impact on performance, but I'm conscious that if we go down that route we could end up with a lot of categories to choose from when adding boundaries to filters for the Explore pages.

**Comment by johnvanbreda** [comment]
I've also had a request from the National Trust to make their site boundaries available during activity setup. Personally I think if we are accepting that these boundaries will be available for filtering, then they may as well be available everywhere (Explore & activity setup). It might be worth a quick think about improvements to the filtering UI in this area to mitigate the increase in number of options in the list though.

**Comment by BirenRathod** [comment]
@kitenetter 

This has uploaded to test on irecord dev website.

**Comment by kitenetter** [comment]
This project seems to have gone quiet - closing for now.
