### ISSUE TITLE
User accounts require merging

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#399]
A user wanted to update his email address, but misunderstood the procedure and has ended up creating a new account. He wants to carry on using his old account, but I'm now not able to update the email on his old account because the new account has used it.

The accounts in question are:
1. Old account: "Cliff Morrison", https://www.brc.ac.uk/irecord/user/35621, Warehouse User ID: 141443
2. New account: "Cliff Morrison1", https://www.brc.ac.uk/irecord/user/45372, Warehouse User ID: 164298

Please can we:
1. If possible, move the two records linked to the new account so that they are linked to the old account instead.
2. Delete the new account.
3. Update the email address for the old account - I don't want to put the email address on here, so can whoever is able to pick this up let me know and I'll forward it direct.

**Comment by johnvanbreda** [comment]
Done.
