### ISSUE TITLE
OS maps

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#40]
It would be great to have an option (maybe as default) to see Ordnance Survey map tiles. They are [free to use](https://www.ordnancesurvey.co.uk/business-and-government/products/os-openspace/api/index.html).

**Comment by JimBacon** [comment]
It would be great. This would always have been the map of first choice but OS were difficult to work with.

Things keep changing and I'm not clear on the current offering from OS. We use the OpenLayers library (v2) to display a choice of map layers.

Here is a 2013 discussion of a problem:
http://gis.stackexchange.com/questions/65244/openlayers-with-uk-ordnance-survey-maps

Then there is a 2014 discussion which sounds like progress has been made but there are still some difficulties:
https://www.ordnancesurvey.co.uk/forums/discussion/1002001/openlayers-3/

Have you found any better sources of information?



Some discussion, possible out of date, indicates it not as easy as you might like, https://www.ordnancesurvey.co.uk/forums/discussion/1002001/openlayers-3/

**Comment by kazlauskis** [comment]
I haven't used openlayers as I am using a more popular [Leaflet](http://leafletjs.com/) for my mapping on the apps and that supports OS, google, bing, OSM.. tile servers. It wasn't difficult to set it up.

**Comment by kazlauskis** [comment]
Duplicate #168
