### ISSUE TITLE
Plant common name linking incorrectly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#400]
I'm not sure if this is an issue for the iRecord website, or the app, or both.

The English name "Common Cornsalad" is linked to both "Valerianella locusta" and "Valerianella locusta var. dunensis". On the iRecord website, if you enter a record as "Common Cornsalad" you are shown both taxa, but on the app it seems to be defaulting to "Valerianella locusta var. dunensis" which in most cases is not the taxon that people are trying to record.

This needs correcting on the app, but I think it would also be beneficial to remove the English name "Common Cornsalad" from the taxon "Valerianella locusta var. dunensis", or alternatively to edit the English name to "Common Cornsalad (dwarf coastal form)".

On the app only one choice is given for the English name, so this needs updating so that "Common Cornsalad" links to "Valerianella locusta".

Let me know if I need to raise this as an issue on the app Github as well.

**Comment by DavidRoy** [comment]
@kazlauskis to resolve for the iRecord app
@johnvanbreda to resolve for iRecord website

**Comment by johnvanbreda** [comment]
Done on iRecord - I changed the name to Common Cornsalad (dwarf coastal form) as this had the least implications. Presumably Chris Raper needs to be informed?

**Comment by kitenetter** [comment]
Have informed Chris at NHM.

@kazlauskis are you able to update the app names or did I read in another of your comments that you don't have access to the relevant table/s?

**Comment by kazlauskis** [comment]
Hi @kitenetter, I will try to find the SQL query I was running to get the list in to the app and pass it to John or someone your end to turn it into a report.

**Comment by DavidRoy** [comment]
@kazlauskis can you look at this again?

**Comment by kazlauskis** [comment]
Done, app v4.0.0.
