### ISSUE TITLE
Can we exclude particular taxa in a verification filter?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#402]
I have a request from a verifier to be able to see all marina taxa **_except_** birds. I can't think of any way of doing this other than constructing a complex filter based on lots of individual taxon groups, but I just wanted to check if there was a simpler method before I go down that route.

What I'd like to do is to have a filter for all taxa that have the marine flag (which is easy to set up), and then specify the exclusion of birds, but I don't think we can do that can we?

**Comment by DavidHepper** [comment]
I suggest that implementing this would be a slippery slope towards complex queries that risk timing out. Users may say next that they wish to exclude _several_ taxon groups...

**Comment by johnvanbreda** [comment]
I agree with @DavidHepper. Although the technical change required to support inversion of the groups filter is not huge, it's very likely to result in sequential scans of the database which will be very slow.

**Comment by kitenetter** [comment]
Okay, just wanted to check that I hadn't missed an easier solution to this. I will stick with constructing very large lists of taxon groups! Closing.
