### ISSUE TITLE
Updating a genus name

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#403]
I've just added the species Acrocera sanguinea to iRecord. In the process of adding that one, Chris Raper found that the UKSI had an ill-formed genus name "Acrocera misident." Chris has supplied a new TVK for the genus, but I'm not sure what the implications are of changing the genus name, nor how best to do so.

For the genus we currently have:
TVK NBNORG0000026692 : Acrocera Meigen, 1803 misident.

Chris has now set that to be a synonym of the correct version, which is:
TVK NHMSYS0021199197 : Acrocera Meigen, 1803

As things stand, in iRecord there are now two species in this genus:
- Acrocera sanguinea
- Acrocera orbiculus
 and both are currently linked to the incorrect form of the parent genus.

Should we update the parent genus, or is that something that can be left until the next full UKSI update?

**Comment by johnvanbreda** [comment]
I think in the circumstances, updating the existing entry for Acrocera misident to correct the name, also updating both the external key and search code to the new TVK will be the best approach. There is no risk of a record being attached to the misident form of the name deliberately so changing the existing taxon is OK. This can be done via the warehouse UI.

**Comment by kitenetter** [comment]
@johnvanbreda I've updated the TVKs for the external key and search code via:
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/142886

However, in the main taxon table there is a value "misident." shown in the attribute column, and I don't think I can edit that via the warehouse UI. It's not a major problem but if you can remove the misident. from the taxa table that would keep things tidy.
