### ISSUE TITLE
VC and BC boundaries excluding Lundy island

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#406]
The current boundary for North Devon vice-county does not include Lundy, and likewise the Devon Butterfly Conservation excludes Lundy. What is the process for changing these boundaries, do we need to edit a shapefile and then re-import? If so, where are the current shapefile versions of these boundaries stored?

**Comment by burkmarr** [comment]
Added in by replacing existing VC polygon for North Devon with the original from NBN (3 mile offshore extent).  For BC boundary I updated the original boundary with the polygon of Lundy included in the NBN VC boundary layer (unbuffered).

**Comment by johnvanbreda** [comment]
@burkmarr just checking that you are aware that if you update the boundary directly in the database, you can insert a record into the work_queue table to request that the spatial indexing system re-indexes it at the next opportunity?

**Comment by burkmarr** [comment]
@johnvanbreda - hi John I did it via the import procedure described here: https://indicia-docs.readthedocs.io/en/latest/administrating/importing-shp.html?highlight=spatial%20upload

Do I need to insert into the work_queue if I did it that way? If so, can you tell me what I need to insert?

**Comment by johnvanbreda** [comment]
Ah - that's fine then if you used the warehouse UI. I wasn't sure if you'd done it via a direct query.
