### ISSUE TITLE
Document procedures for sensitive records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#407]
Add Help page documenting procedures for:
- Records marked by users as sensitive
- Records of species flagged as sensitive by NBN

To include what happens when verifiers and LERCs access such records.

**Comment by kitenetter** [comment]
Not yet found time to address this further.

**Comment by kitenetter** [comment]
There is considerable complexity to implementing the NBN sensitive species in full:
- Some species have different levels of blur in different countries.
- It is often records of roosts or nests that are regarded as sensitive, not species records as such.
- Some species are only regarded as sensitive for parts of their life-cycle.

If we are to adopt the NBN list then I think we would have to take a precautionary approach and apply the blur to all records of the species concerned, as we are unable to reliably separate out stages, breeding locations etc.

It seems to make sense to follow the NBN list, it has been agreed with the country agencies and it is difficult to see on what basis we would come to different conclusions. However, that would mean we are unable to offer any comfort to people who are worried about species such as hares that are not listed.

Questions for @johnvanbreda:
Do we currently do any auto-blurring for anything other than badger at the moment? And/or is there somewhere that I can access to see what auto-blurring is set up - where are the controls for this?

Are we able to implement blurring to different resolutions in different countries, or will we have to take a precautionary approach to that as well?

**Comment by DavidRoy** [comment]
These are setup in the warehouse under Admin -> Workflow events: http://warehouse1.indicia.org.uk/index.php/workflow_event

We also have the requirement of enabling sensitivity by geographic region within other projects (e.g. ABLE).  I don't think this option currently exists

**Comment by johnvanbreda** [comment]
@kitenetter just Badger and Asian Hornet as it stands.

**Comment by kitenetter** [comment]
Currently NBN Atlas also takes a precautionary approach and blurs records based on taxon, regardless of stage or breeding status. The taxon lists and degrees of blurring are country-specific.

Need to prioritise country/regional filtering (will add new issue) and to start adding species to workflow events (will do under this issue).

**Comment by kitenetter** [comment]
Following discussion, we agreed to leave regional filtering for now. @kitenetter to look at implications for implementing single list of blurred records for all locations, taking the maximum blur amount as a precautionary approach.

**Comment by kitenetter** [comment]
I'm trying to add a species to the workflow events, intially as a test before extending this to the full NBN list. I am using:
http://warehouse1.indicia.org.uk/index.php/workflow_event/create

However, I am getting an error message linked to the species name:

![image](https://user-images.githubusercontent.com/16039111/100917127-a4ef8500-34ce-11eb-9b35-a39874caf0c6.png)

I've tried entering the name (Acosmetia caliginosa) and the TVK (NHMSYS0021144548), but neither is accepted.

Is there something else I need to do @johnvanbreda @DavidRoy ?

**Comment by johnvanbreda** [comment]
If you try accessing the warehouse via https://warehouse1.indicia.org.uk this should work.

**Comment by kitenetter** [comment]
Currently under review as part of NCEA. Closing this one.
