### ISSUE TITLE
Potential for interim UKSI updates

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#409]
From Chris Raper:

> It just dawned on me that it might be really useful to semi-automate what you do to add in individual taxa manually. I could give a range of field values and keys (like I give you in emails) in a spreadsheet and then if John van Breda could write an import routine you'd just suck in the data … skipping rows that already exist, to prevent any duplication. 

> It would go a long way to improving the speed from new names/taxa being added and appearing in iRecord because I'm always asked why stuff isn't available yet in iRecord. I could even just send you regular exports of new stuff and you just import what is needed at your end. Then we'd do a major update every 6-months to tidy up and lose ends. 

> Is that feasible?

**Comment by johnvanbreda** [comment]
If you can provide a CSV file then it will go in via the standard warehouse importer found on the warehouse Taxa tab for the UKSI species list. The columns should be:
Taxon
Authority
Taxon group (=the output group name)
Parent (e.g. the genus name)
External key (=the TVK of the preferred name)
Search code (=the TVK of the actual name, same as external key when adding a preferred name).
Rank (e.g. Species, or Genus)
When you do the import the list needs to be set to UKSI and the language to latin on the first tab. The mappings on the 2nd tab should hopefulyl be automatic.

**Comment by kitenetter** [comment]
Questions:

1. Are there any checks in place to prevent duplicated names and/or TVKs being imported? I'm guessing not, in which case careful checking will be needed before importing.
2. Are we able to import new vernacular names in a similar way? 
3. If so would this need to be done as a separate import, so that the language is correctly set? 
4. In this case would the Search code be the TVK of the vernacular name, and the External key would be the TVK of the preferred scientific name that the vernacular refers to?

**Comment by johnvanbreda** [comment]
1. No
2. You can import new taxon concepts that have common names in one go, using a field with the same format as the common names box on the edit form. Same for synonyms. You can't import common names or synonyms to attach them to existing names though as it stands.
3. See 2.
4. Correct - all names should have their own TVK in the search code and the preferred name TVK in the external key.
