### ISSUE TITLE
Recent sightings show more info

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#41]
I feel that when a user enters iRecord and finds Recent sightings listed it expects them to be clickable and show more information. This would be easy to do by adding a link to them. 

Currently, clicking it zooms to and highlights a record on the map, I think this could be done when the mouse hovers over the record.

**Comment by johnvanbreda** [comment]
Agreed. Personally I would extend this to a complete review of the home page UI as it is fairly dated now.

**Comment by kitenetter** [comment]
Suggest taking this into account under #22
