### ISSUE TITLE
Create survey and form for BPGS alien gall project

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#411]
As discussed with @johnvanbreda 

Survey structure is in W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Projects\BPGS\Alien cynipids

**Comment by johnvanbreda** [comment]
Hi @kitenetter I can't see the W drive from here - can you either email me the document or attach to this issue please?

**Comment by kitenetter** [comment]
Sent via email.

**Comment by johnvanbreda** [comment]
@kitenetter there is a draft of this form at https://www.brc.ac.uk/irecord/record/enter-alien-cynipid

1. Are there any changes to text you'd like?
2. Are the mandatory fields correct?
3. Any other changes?
4. Should we set up an activity for this?

**Comment by kitenetter** [comment]
Awaiting update from Karsten as to whether the alien gall project is still live - depending on answer to that will then see if plant gall society wish to re-engage.

**Comment by kitenetter** [comment]
No progress on this for now, I will pursue this outside Github to see where we go next for BPGS. Closing.
