### ISSUE TITLE
Asian Hornet records - unable to view those mentioned in "Notifications"

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#412]
I verify incoming "Asian Hornet Watch" app submissions.  If these are referred onwards for checking / follow up by the NNSS or NBU, then on occasions other users will add comments / (re-)verify the record.

I see notifications of follow up actions via the "Explore / My Notifications" page.  However, I cannot access the record via the "View this record" icon.  Clicking on the button produces a message "This record cannot be found".  I can still access the record via the Verification Grid by filtering by Record Number.

I assume this is something to do with the addition of "confidential" markers to the record.  Not a major gripe but it would be nice to be able to access the record directly from the notification page.

**Comment by DavidRoy** [comment]
@StephRorke can you pick this up in discussion with John about supporting GBNNSIP

**Comment by StephRorke** [comment]
@DavidRoy Yes, I think this is part of an issue already on a list of bugs to fix, I have linked this issue as another example and assigned to John.

**Comment by johnvanbreda** [comment]
Are the notifications Matt receives pointing to the GBNNSIP site or the iRecord site?

**Comment by kitenetter** [comment]
@StephRorke @MNSmith can we close this one?

**Comment by MNSmith** [comment]
At present I think the problem at my end is still there.  If Steph could at a test comment to one of the currently open "Plausible" records I will see if I can access the record or not from My Notifications

**Comment by kitenetter** [comment]
Closing for now but let us know if this is still a problem.
