### ISSUE TITLE
Provide permissions for triggering NBN DwC exports

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#418]
From the NBN export admin page:
https://www.brc.ac.uk/irecord/exports

if I am logged on as "iRecord support" I can create and edit auto exports, but I cannot trigger them - I have to log out and log back in as admin. Since I rarely need to use the admin account for anything else it would be great if the iRecord support account could be given permissions to trigger the exports.

**Comment by kitenetter** [comment]
Hi @johnvanbreda - I've marked this as "urgent" because it's nearly time for the next round of NBN exports and it would be really useful if I didn't have to keep juggling log-ons and passwords! Hoping this is an easy task to sort out.

**Comment by johnvanbreda** [comment]
Permission created and assigned to admin user role, which iRecord support has.
