### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#42]
I would like to see user profiles. I think that this is something I naturally expect from a website like this. On 'Explore all records' page the recorder column should be clickable and show user photo, short description, possibly experience and other similar stuff.

**Comment by kitenetter** [comment]
Agreed, but probably needs to be optional - some users dislike sites that expose what they see as unnecessary personal information, and we want to encourage as many recorders as possible to feel comfortable with using iRecord. Include in review under #22
