### ISSUE TITLE
Blue area highlight makes map useless in Verify, esp. for low-res obs. and/or with a Where filter is applied

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#421]
The red highlight / overlay / cast on the Google map when a Where filter is applied is causing trouble for Verifiers, making the map unusable.
The problem is particularly acute for records where the Output Map Ref is vague or has been blurred, such as 7978225.

Steps to reproduce:
- Select **Verify**.
- Create a **Where** filter and set it to any VC. The map shows the VC overlaid with red.
- Double-click any observation in the Grid and double-click it to show its position.
- An even more intensely-cast filled red square (or circle) shows the Output Map Ref positioned on the Google map. 
- The map outside the square is uncast at high resolutions but if the map is zoomed Out (using minus sign), at some undetermined resolution the whole of the chosen VC shows with the same red cast as the fill within the square, making the map obscure, with only place names being distinguishable. This fill seems unnecessary. At very least the fill should have much reduced opacity, both within and outside the square. I can't see why it is needed at all, given that the solid border, which could itself be lightened, is easily interpreted.

[ This issue was previously reported in the Forum at https://www.brc.ac.uk/irecord/node/7178 ]

**Comment by DavidHepper** [comment]
Here's a screenshot detail. The overlay colour is red in this case. A 'Where' filter on VC is set. The map is unusable, and even worse for records near villages. Please reduce the opacity.
![map obliterated by overlay colour casts](https://user-images.githubusercontent.com/24915271/53241972-48292e80-369b-11e9-88e8-0d4b455a7019.jpg)

**Comment by DavidHepper** [comment]
I've had another complaint about this.

**Comment by johnvanbreda** [comment]
@DavidHepper I've changed the map layer to show full precision data rather than large circles when you zoom in. I've also adjusted the opacity a bit. Please can you re-check if this is still an issue?
