### ISSUE TITLE
iRecord records layer in verification map should not include rejected records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#422]
In the map shown on the verification page it is possible to view a layer "iRecord data for selected species". This is very useful, but currently includes all records: "accepted", "not reviewed", and "not accepted". I think that it should include "accepted" and "not reviewed", but that "not accepted" records should be excluded.

I suppose the ideal situation would be to give the user a choice over which types of record get displayed, and/or to show the different verification statuses as different colours or shapes, but in the short term it would be best not to include "not accepted" records.

**Comment by DavidHepper** [comment]
Both 'Plausible' and 'Absence' (not a verification status but zero-value, shown in the grid in strike-through text) records should also be excluded.

**Comment by kitenetter** [comment]
I definitely agree that absence records should not be mapped (under pretty much any circumstances!), but personally I'm happy to keep Plausible ones, which are no less informative than 'not reviewed' ones. But I suspect there will be a variety of views among verifiers as to exactly how this should be done, and we'll have to pick a compromise solution (or go down the route of adding complexity by allowing verifiers to choose exactly what appears on their maps).

**Comment by kitenetter** [comment]
Would like to be able to distinguish accepted and unconfirmed records on the verication page map. Assigning to October milestone for review.

**Comment by kitenetter** [comment]
Rejected records are no longer displayed on the verification map. Closing.
