### ISSUE TITLE
Error on my-sites page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#426]
Reported via iRecord forum:
https://www.brc.ac.uk/irecord/node/7434

When I go into https://www.brc.ac.uk/irecord/my-sites after logging in I get the following error

 general_errors.There was an SQL error: ERROR: syntax error at or near "AND" LINE 7: AND o.created_by_id= AND o.created_by_id<>1 ^ - SELECT COUNT(*) FROM ( SELECT DISTINCT l.id FROM locations l LEFT JOIN cache_termlists_terms lt ON lt.id=l.location_type_id LEFT JOIN locations_websites lw ON lw.location_id=l.id AND lw.deleted=false LEFT JOIN cache_occurrences_functional o ON o.website_id in (23) AND o.created_by_id= AND o.created_by_id<>1 AND ST_INTERSECTS(o.public_geom, COALESCE(l.boundary_geom, l.centroid_geom)) AND NOT ST_TOUCHES(o.public_geom, COALESCE(l.boundary_geom, l.centroid_geom)) LEFT JOIN (person_attribute_values pav JOIN users u ON u.person_id=pav.person_id AND u.id= ) ON pav.person_attribute_id=1 AND pav.int_value=l.id AND pav.deleted=false WHERE (o.id is null or (o.training=false AND 1=1)) AND (l.public=true or lw.website_id in (23)) AND l.deleted=false AND l.created_by_id= UNION SELECT DISTINCT l.id FROM locations l LEFT JOIN cache_termlists_terms lt ON lt.id=l.location_type_id LEFT JOIN locations_websites lw ON lw.location_id=l.id AND lw.deleted=false LEFT JOIN cache_occurrences_functional o ON o.website_id in (23) AND o.created_by_id= AND o.created_by_id<>1 AND ST_INTERSECTS(o.public_geom, COALESCE(l.boundary_geom, l.centroid_geom)) AND NOT ST_TOUCHES(o.public_geom, COALESCE(l.boundary_geom, l.centroid_geom)) LEFT JOIN (person_attribute_values pav JOIN users u ON u.person_id=pav.person_id AND u.id= ) ON pav.person_attribute_id=1 AND pav.int_value=l.id AND pav.deleted=false WHERE (o.id is null or (o.training=false AND 1=1)) AND (l.public=true or lw.website_id in (23)) AND l.deleted=false AND u.id IS NOT NULL LIMIT 42) AS subquery

Top

**Comment by johnvanbreda** [comment]
The problem here was that a user account was added to the warehouse a long time ago, called Chris_vaughan (with a capital C). When the code tried to check if chris_vaughan was unique, it determined it was (case sensitive check) but then saved to the database layer with a case insensitive check that rejected the username as a duplicate. So Chris' account was never linked correctly to the warehouse.

I've fixed this and added unit tests so this scenario can't recur without us knowing.
