### ISSUE TITLE
Make habitat and comments field 'lockable' on casual entry form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#427]
Related to request via the iRecord forum:
https://www.brc.ac.uk/irecord/node/7397#comment-4267

Requirement is to have habitat and comments field lock-able

**Comment by kitenetter** [comment]
Question: 
I've just tested this on the development version of the casual record form. I can add a lockable option to the Comment, but I can't see how to make it work for the hierarchical habitat box, so I haven't yet changed anything on the live site.

There is a danger that this will result in comments getting attached to long lists of species when they only intended for one occurrence, but maybe that is just something that users will need to take into account. It might lead to requests for bulk-edit function from users.

**Comment by kitenetter** [comment]
There have been no further requests for this that I am aware of, and given the complications outlined above I don't think this is a priority. Closing.
