### ISSUE TITLE
User surname/firstname change diverges from the warehouse user account names

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#428]
By changing a user's surname on the iRecord website this is not synced back to the warehouse. If the user is then making a record with a recording form that doesn't have a `Recorder name` field on it, then the record will be under an old user's surname. This shows up when using the iRecord App, where users with their names changed get the app records under the original-old names. See this [forum post](https://www.brc.ac.uk/irecord/node/7433#comment-4272). 

This might be linked to Indicia-Team/warehouse#128

An example:
- This is how it is edited on the website
<img width="822" alt="screen shot 2018-10-07 at 15 01 19" src="https://user-images.githubusercontent.com/7383162/46582750-f3ff1400-ca43-11e8-8e21-e39e12998813.png">

- How it appears on the general edit form  
<img width="923" alt="screen shot 2018-10-07 at 15 00 53" src="https://user-images.githubusercontent.com/7383162/46582752-f82b3180-ca43-11e8-993d-c3ec8c4030be.png">

- The same account on the warehouse with the old name
<img width="906" alt="screen shot 2018-10-07 at 15 00 27" src="https://user-images.githubusercontent.com/7383162/46582753-fa8d8b80-ca43-11e8-8dab-62da7f0adcae.png">

**Comment by kitenetter** [comment]
There are some wider issues here I think. Years ago I edited my iRecord name from "Martin Harvey" to "Martin C. Harvey" but the app still uses "Martin Harvey" presumably for the reasons Karolis gives above. One of the consequences of the name edit seems to be that it is not possible to bulk verify records attached to "Martin C. Harvey".

We've also had a number of instances of people querying why a name edit hasn't fed through to the league tables that appear in various places.

It is difficult though. If a user gets married and changes their name, they might in some cases wish all their records to be updated to the 'new' name, and in other cases would prefer the old records to stay linked to the name that was used at the time. If we do make name edits propagate through the system we will no doubt end up making changes that some users don't want to see, and also it may be added complication for verifiers.

Would a propagated name change result in records being seen as edited, thus exposing them for re-verification?

One answer might be to give users the choice: upon editing their name they could be asked whether they want the edit to propagate to their existing records. But that's adding complexity.

Are there any other approaches we could consider?

**Comment by JimBacon** [comment]
This is further complicated because there is not a single way of recording names. It varies between surveys.

Some surveys have sample attributes for name, some use the sample.recorder_names field and some are just linked to a person record which contains a name. Some do more than one of these things. Those which store the name as part of the sample have a record of the name used at time of recording which could be fixed. Those without can only access the persons current name (which I would expect to update if changed in iRecord).

**Comment by kazlauskis** [comment]
Maybe, for a start, the core drupal account name+surname could be synced to the warehouse ones. This would at least get those records without custom `recorder` attribute showing correct names.

**Comment by BirenRathod** [comment]
I think changing name & matching according to Drupal's profile way to go ahead. If possible you can add the message like "you have been registered previously with [existing name], would you like to change to this [new name]" .

**Comment by JimBacon** [comment]
Couple of thoughts. 
1. I don't think changing the person name doesn't currently triggers an update on the cache_samples_nonfunctional table. It will be needed for reports to reflect the new name.
2. When updating the cache, a name in a sample attribute is preferred to a warehouse person name so, where a survey stores the name at time of recording, this will continue to show.

**Comment by kitenetter** [comment]
I'm going to close this old issue - the question of how we handle names still comes up, but has been more recently addressed in #869
