### ISSUE TITLE
Occurrences duplicated in NBN export of NE data

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#431]
The automated export of NE's dataset to NBN is producing duplicate records. This only affects a small proportion of occurrence IDs, but some of the IDs appear up to 11 times:

![image](https://user-images.githubusercontent.com/16039111/47253773-f2741980-d44f-11e8-8a37-f14570a85cbc.png)

All the duplicated IDs are from the "Natural England Surveys" survey (id 509). I can't see a reason for these particular records to be duplicated.

Is it possible to set the underlying query to produce unique rows?

A copy of the full NE export dataset with the duplicates flagged is here:
[NE_NBN_duplicates.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/2497986/NE_NBN_duplicates.xlsx)

**Comment by johnvanbreda** [comment]
Should be fixed now. A data error - when I'd added uncoded to some of the records, the values had duplicated somehow.
