### ISSUE TITLE
Upload of ZC files for bat recording

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#432]
https://www.brc.ac.uk/irecord/node/7447

Request to enable upload of sonograms in ".ZC" (zerocrossing) format

**Comment by johnvanbreda** [comment]
Enabling upload of the file format would be easy. However, enabling some kind of visualisation of the file on the web interface may be a more significant task, especially as a quick web search didn't find any specification for the file format or JavaScript libraries for viewing them.

**Comment by kitenetter** [comment]
BCT are keen to enable upload of .zc files if possible. BCT say:

> .zc files can be handled using a few very widely used free-of-charge sound analysis programs (such as Analook and Kaleidoscope), and they are among the core methods for recording and identifying bat calls. They can’t be converted to audio files as they simply capture data points that plot the calls as frequency against time. A verifier would deal with .wav files in the same way, opening them using sound analysis software rather than listening to the audio which would rarely enable calls to be identified to species level with confidence (often the calls would not even be audible given the recent move more towards recording bat calls at their original frequencies).

I don't think they are wanting a visualisation of the files on the web, they just want to be able to upload files with the records so that verifiers can download them and use them offline.

The priority is to make it available on the two bat recording forms, not sure if it needs to be available n the more generic forms as well (but if it is simply allowing the ifle format then I suppose it won't do any harm to make it available more generally?).

**Comment by johnvanbreda** [comment]
@kitenetter please can you obtain an example *.zc file and send it to me.

**Comment by kitenetter** [comment]
Have requested an example.

**Comment by kitenetter** [comment]
Some example files here:

[Bat zc files.zip](https://github.com/BiologicalRecordsCentre/iRecord/files/6191376/Bat.zc.files.zip)

Philip at BCT says:

"I’ve attached a few example files. Depending on the device used they can have an extension in the format .nn# (nn is the seconds in the time of recording – the last four digits in the main file name are hh:mm) but other times the format is standardised to .zc.

"If you are basing file restrictions on extension then you could add an instruction for users to right-click on the file name and change the extension to .zc, which is easy to do. However, if it’s possible to simply accept the “number hash” file extensions this will make things easier for users with lots of files to upload.

"As you can see, the file sizes are tiny. Looking through my own files the largest I’ve found so far is 30 KB.

"I hope this gives you what you need, but any questions then let me know."

**Comment by johnvanbreda** [comment]
Code for Zerocrossing support now in the develop branches

**Comment by johnvanbreda** [comment]
@kitenetter I've added zc file support to the 2 bat recording forms on iRecord. It would be good to get these tested with a few records.

**Comment by kitenetter** [comment]
On upload an error message is being generated:

> An error occurred when the data was submitted.
> submit ok but file transfer failed
> The file is not one of the allowed types.

If I ignore the error message the record appears to save but the .zc file is not available:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=20686585

**Comment by johnvanbreda** [comment]
Should be working now - I'd set it up on the client side, but missed the "upload_file_types" configuration setting in the warehouse.

**Comment by kitenetter** [comment]
I can now save the record and I don't get an error message. However, I can't see any way of retrieving the file from the record:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=20687238

I get "404 - File or directory not found" if I try to open or download the file.

**Comment by johnvanbreda** [comment]
@BirenRathod please can you check if there is a limit on the types of file that the warehouse web server can serve? There is a file in https://warehouse1.indicia.org.uk/upload/o_1f8ct9pio13nl7f44apot61qfnb.zc which I've confirmed exists, but it returns a 404 via a web-browser.

**Comment by BirenRathod** [comment]
@johnvanbreda I have added .zc file type in IIS for warehouse and iRecord.

**Comment by kitenetter** [comment]
I can now download the file from:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=20687238

So it looks like this is now working, thanks - please close if you agree.
