### ISSUE TITLE
Remove spaces from NBN export zip file names

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#435]
NBN have requested that we name our export .zip files using only numbers, letters and underscores.

Am I correct in thinking that the file name derives from the parameter “Dataset name” that we set up in the auto-export form?

And does that parameter also get used to populate the DwC attribute datasetName in the occurrences csv? 

If my two assumptions are correct it means that if I were to remove the spaces from the parameter “Dataset name” it may fix the file names, but will corrupt the csv datasetName.

Can you suggest a solution?

**Comment by DavidHepper** [comment]
Suggest replacing spaces with underscores rather than removing them.

**Comment by kitenetter** [comment]
Not raised as problematic by NBN recently. Closing.
