### ISSUE TITLE
Verifier names missing from cache_occurrences_nonfunctional table?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#436]
As part of the work on the BDS dataset for export to NBN I'm trying to join the list of occurrence IDs that are included in the NBN export csv to the relevant verifier name (verifiers are not currently included in the NBN export format).

In pgAdmin I'm doing this by joining cache_occurrences_functional to cache_occurrences_nonfunctional, and then using the attribute cache_occurrences_nonfunctional.verifier.

However, this is resulting in null values for a large proportion of records that are flagged as verified, and that do show a verifier name on iRecord itself.

Am I looking in the right place for the verifier name, and if so is it possible that the cache table needs re-building?

**Comment by johnvanbreda** [comment]
Hi @kitenetter, I've ran a query to update these:

```sql

update cache_occurrences_nonfunctional onf
set verifier=p.surname || ', ' || p.first_name
from occurrences o
join users u on u.id=o.verified_by_id
join people p on p.id=u.person_id
where o.id=onf.id
and (o.record_status in ('V', 'R') or o.record_substatus=3)
and onf.verifier is null;
```

**Comment by johnvanbreda** [comment]
I've added a test case to the automated testing to check that verification does update the verifier. It seems to work in the current code so will close this.
