### ISSUE TITLE
Rejected records should not appear on explore reports

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#438]
Issue raised in the context of explore reports accessed via record_details page, e.g. 
https://www.brc.ac.uk/irecord/all-records?filter-date_age=&filter-indexed_location_list=&filter-taxon_meaning_list=83778

accessed via link 'explore records of Colletes hederae' from record_details page:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=1589501

similar requirement to issue #422

**Comment by kitenetter** [comment]
I think this has been fixed for the current Explore pages - need to check ES pages take this into account. Closing.
