### ISSUE TITLE
Habitat does not always populate for saved sites

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#44]
When a site is saved, its associated habitat details appear to get saved as well, but when re-using a saved site it seems to be very hit and miss as to whether the habitat box gets filled in.
As an immediate fix, is it okay if I edit the standard forms so that the habitat field becomes lockable?
And in the longer term can we fix it so that the habitat is always filled in for saved sites?

**Comment by DavidRoy** [comment]
I agree with your pragmatic suggestion, thanks

**Comment by johnvanbreda** [comment]
Locking the habitat field might not work exactly as you'd expect because it is hierarchical. Worth trying but it might need extra effort to fix properly.
The habitat field should be filled in with the habitat you used the last time you recorded at a site. If this does not happen as you'd expect, are you able to check for JavaScript errors on the page? Also could you let me know the site, date and time you were using the form (approx) and the habitat you expected to see.

**Comment by kitenetter** [comment]
Okay, I'm nervous of trying to add field locking to the live site if it might not work as expected, so will leave that for now.
The lack of consistency in completing the habitat attribute is something that has been happening ever since I started using iRecord, and another user mentioned it on Facebook today which is what prompted me to add it as an issue. Where I most often notice it is if I add records for my garden. My site is saved as "Great Kimble: Bridge Street garden", so I normally type in "Great" to call up the site. Sometimes it auto-fills the habitat, sometimes it doesn't. 
I've not been able to tie down why it works sometimes and not others. I always use the add a list form, not sure if it is an issue on other forms. And for my garden I always fill in the habitat manually if it hasn't auto-completed, so presumably it isn't remembering anything from the previous use.
I've just tried adding a new record (16:29, 22 April, via Chrome) and it currently isn't auto-filling. What it should fill in is "Arable land, gardens or parks: Garden and parks".
If I look for Javascript errors after entering the site name I get:
![image](https://cloud.githubusercontent.com/assets/16039111/14746682/ab1e9ee0-08a8-11e6-8470-b4090c27dd07.png)

**Comment by johnvanbreda** [comment]
Thanks Martin, that was very useful. I think the problem occurs if you've used that site on a different form without a habitat field so it effectively clears the stored habitat. I've fixed this, though your garden habitat is loading as gardens and parks which looks right from the data.

**Comment by kitenetter** [comment]
Thanks John, that seems to be working, assuming that "Gardens and parks" is ending up in the right bit of the hierarchy.

**Comment by kitenetter** [comment]
This problem has re-occurred, I'm no longer getting the habitat filled in automatically when I choose a saved site.

**Comment by johnvanbreda** [comment]
Fixed in code and will be deployed with the next release.
