### ISSUE TITLE
Enable filtering and downloading for records linked to activities

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#440]
This originates from a request by the Sustrans project in Scotland, but has cropped up elsewhere as well.

Sustrans have an activity with its own recording form, and currently have download access to the records added via that form. However, they have also enabled the activity to be used in the iRecord app, and wish to be able to download those records as well.

Records from the app will be getting linked to the activity ID, but at the moment we do not have a way of including app records in the download.

One option would to be to add an Activity filter to the standard lists of filters under the "Source" heading. But there are complexities around whether filtering by activity should be an and/or operation alongside filtering by form or other source.

Another option would be to make it easier to create custom reports for download purposes, that would allow more complex combinations of source including activity ID.

Which of the above two is most promising? Are there other options?

**Comment by DavidHepper** [comment]
Would be useful for the BDS 'Clubtail Count' survey, for example, though I've now made an alternative download filter in Verify.

**Comment by kitenetter** [comment]
I believe this is no longer an issue, since Activity admins automatically get given a download for records linked to their activity. Closing.
