### ISSUE TITLE
User download failing when "iRecord general" survey filter is set

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#442]
A user has reported a problem with downloading his own records. 

From the Download page he is choosing his own records and setting the survey to iRecord general:

![image](https://user-images.githubusercontent.com/16039111/48486428-66b59900-e813-11e8-9628-538d8d7ec29c.png)

The download fails (error message below). If I masquerade as this user I get the same problem. The user has around 4,000 records in the iRecord general survey (out of nearly 20,000 records in total).

If I try downloading his records **_without_** setting a survey filter the download the records do download successfully. Also, the user says that if he downloads with a filter set for other surveys (e.g. iRecord app, for which he has many more records) it does download successfully (I haven't tried to replicate that). So it appears to be an issue specifically with iRecord general.

Error message from the iRecord general download attempt:
`{"error":"general_errors.There was an SQL error: ERROR:  canceling statement due to statement timeout - \n  SELECT  distinct on (o.id) o.id as \"occurrence_id\",\n'iBRC' || o.id as \"recordkey\",\no.external_key as \"external_key\",\nsnf.website_title || ' | ' || snf.survey_title || coalesce(' | ' || snf.group_title, '') as \"source\",\ncase when onf.sensitivity_precision is null then o.sample_id else null end as \"sample_id\",\ncttl.preferred_taxon as \"taxon\",\ncttl.default_common_name as \"common\",\ncttl.taxon_group as \"taxon_group\",\ncttl.kingdom_taxon as \"kingdom\",\ncttl.order_taxon as \"order\",\ncttl.family_taxon as \"family\",\no.taxa_taxon_list_external_key as \"taxonversionkey\",\no.taxa_taxon_list_id as \"taxa_taxon_list_id\",\ncase when onf.sensitivity_precision is null and onf.privacy_precision is null then o.location_name else 'Sensitive. Lat long is approximate.' end as \"location_name\",\nsnf.public_entered_sref as \"entered_sref\",\nsubstring(st_astext(st_transform(st_centroid(o.public_geom), 4326)) from E'POINT\\\\(.+ (.+)\\\\)') as \"lat\",\nsubstring(st_astext(st_transform(st_centroid(o.public_geom), 4326)) from E'POINT\\\\((.+) ') as \"long\",\ncase snf.entered_sref_system when '4326' then 'WGS84' when '27700' then 'OSGB36' else upper(snf.entered_sref_system) end as \"projection\",\nget_sref_precision(snf.public_entered_sref, snf.entered_sref_system, snf.attr_sref_precision) as \"precision\",\nonf.output_sref as \"output_sref\",\ncase onf.output_sref_system when '4326' then 'WGS84' when '27700' then 'OSGB36' else upper(onf.output_sref_system) end as \"output_sref_projection\",\nsnf.attr_biotope as \"attr_biotope\",\nvc.code as \"vicecounty_number\",\nvc.name as \"vicecounty\",\nnull as date,\no.date_start as \"date_start\",\no.date_end as \"date_end\",\no.date_type as \"date_type\",\nsnf.attr_sample_method as \"attr_sample_method\",\nrtrim(snf.recorders, ', ') as \"recorder\",\nCASE WHEN onf.attr_det_full_name IS NULL THEN         CASE WHEN onf.attr_det_last_name IS NULL THEN NULL ELSE onf.attr_det_last_name || COALESCE(', ' || onf.attr_det_first_name, '') END       ELSE onf.attr_det_full_name END as \"determiner\",\nCASE o.certainty WHEN 'C' THEN 'Certain' WHEN 'L' THEN 'Likely' WHEN 'U' THEN 'Uncertain' END as \"certainty\",\nonf.attr_sex as \"attr_sex\",\nonf.attr_stage as \"attr_stage\",\nonf.attr_sex_stage_count as \"attr_sex_stage_count\",\nupper(cast (o.zero_abundance as character)) as \"zeroabundance\",\nonf.comment as \"record_comment\",\nsnf.comment as \"sample_comment\",\ncase when onf.media is null then null else 'http:\/\/warehouse1.indicia.org.uk\/upload\/' || replace(onf.media, ',', ', http:\/\/warehouse1.indicia.org.uk\/upload\/') end as \"images\",\no.created_on as \"input_date\",\no.updated_on as \"last_edit_date\",\nCASE o.record_status         WHEN 'V' THEN 'Accepted'         WHEN 'C' THEN 'Unconfirmed'         WHEN 'R' THEN 'Rejected'         WHEN 'I' THEN 'Input still in progress'         WHEN 'D' THEN 'Queried'         WHEN 'S' THEN 'Awaiting check'         ELSE o.record_status         END as \"record_status\",\nCASE o.record_status         WHEN 'V' THEN           CASE o.record_substatus WHEN 1 THEN 'correct' WHEN 2 THEN 'Considered correct' ELSE NULL END         WHEN 'C' THEN           CASE o.record_substatus WHEN 3 THEN 'Plausible' ELSE 'Not reviewed' END         WHEN 'R' THEN           CASE o.record_substatus WHEN 4 THEN 'Unable to verify' WHEN 5 THEN 'Incorrect' ELSE NULL END         ELSE NULL         END as \"record_substatus\",\ncase o.query when 'A' then 'Answered' when 'Q' then 'Queried' end as \"query\",\nonf.verifier as \"verifier\",\no.verified_on as \"verified_on\",\nonf.licence_code as \"licence_code\",\nCASE CAST(o.created_by_id AS character varying) WHEN '#currentUser#' THEN true ELSE false END as \"belongs_to_user\", sample22.id as attr_id_sample_22, sample22.text_value as attr_sample_22, sample36.id as attr_id_sample_36, sample36.text_value as attr_sample_36, sample58.id as attr_id_sample_58, sample58.text_value as attr_sample_58, sample127.id as attr_id_sample_127, sample127.text_value as attr_sample_127, sample209.id as attr_id_sample_209, sample209.int_value as attr_sample_209, ltt209.term as attr_sample_term_209, occurrence18.id as attr_id_occurrence_18, occurrence18.text_value as attr_occurrence_18, occurrence105.id as attr_id_occurrence_105, occurrence105.int_value as attr_occurrence_105, ltt105.term as attr_occurrence_term_105, occurrence54.id as attr_id_occurrence_54, occurrence54.int_value as attr_occurrence_54, ltt54.term as attr_occurrence_term_54, occurrence93.id as attr_id_occurrence_93, occurrence93.text_value as attr_occurrence_93, occurrence106.id as attr_id_occurrence_106, occurrence106.int_value as attr_occurrence_106, ltt106.term as attr_occurrence_term_106\n  FROM cache_occurrences_functional o\n  JOIN cache_occurrences_nonfunctional onf on onf.id=o.id\n  JOIN cache_samples_nonfunctional snf on snf.id=o.sample_id\n  JOIN cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id\n  LEFT JOIN locations vc on vc.id=o.location_id_vice_county and vc.deleted=false\n  JOIN users privacyusers ON privacyusers.id=o.created_by_id\n  LEFT JOIN sample_attribute_values sample22 ON sample22.sample_id=o.sample_id AND sample22.sample_attribute_id=22 AND sample22.deleted=false\n LEFT JOIN sample_attribute_values sample36 ON sample36.sample_id=o.sample_id AND sample36.sample_attribute_id=36 AND sample36.deleted=false\n LEFT JOIN sample_attribute_values sample58 ON sample58.sample_id=o.sample_id AND sample58.sample_attribute_id=58 AND sample58.deleted=false\n LEFT JOIN sample_attribute_values sample127 ON sample127.sample_id=o.sample_id AND sample127.sample_attribute_id=127 AND sample127.deleted=false\n LEFT JOIN sample_attribute_values sample209 ON sample209.sample_id=o.sample_id AND sample209.sample_attribute_id=209 AND sample209.deleted=false\n LEFT JOIN cache_termlists_terms ltt209 ON ltt209.id=sample209.int_value\n LEFT JOIN occurrence_attribute_values occurrence18 ON occurrence18.occurrence_id=o.id AND occurrence18.occurrence_attribute_id=18 AND occurrence18.deleted=false\n LEFT JOIN occurrence_attribute_values occurrence105 ON occurrence105.occurrence_id=o.id AND occurrence105.occurrence_attribute_id=105 AND occurrence105.deleted=false\n LEFT JOIN cache_termlists_terms ltt105 ON ltt105.id=occurrence105.int_value\n LEFT JOIN occurrence_attribute_values occurrence54 ON occurrence54.occurrence_id=o.id AND occurrence54.occurrence_attribute_id=54 AND occurrence54.deleted=false\n LEFT JOIN cache_termlists_terms ltt54 ON ltt54.id=occurrence54.int_value\n LEFT JOIN occurrence_attribute_values occurrence93 ON occurrence93.occurrence_id=o.id AND occurrence93.occurrence_attribute_id=93 AND occurrence93.deleted=false\n LEFT JOIN occurrence_attribute_values occurrence106 ON occurrence106.occurrence_id=o.id AND occurrence106.occurrence_attribute_id=106 AND occurrence106.deleted=false\n LEFT JOIN cache_termlists_terms ltt106 ON ltt106.id=occurrence106.int_value\n \n  WHERE o.training=false AND (o.website_id in (23) OR privacyusers.id=1 OR privacyusers.allow_share_for_reporting=true OR privacyusers.allow_share_for_reporting IS NULL)\n AND o.website_id in (101,43,13,97,33,29,44,87,98,12,24,14,17,6,8,25,11,7,30,5,27,34,40,32,42,51,49,65,68,73,75,9,71,88,10,69,23)\n  \n  AND o.release_status='R'\nAND o.confidential='f'\nAND o.created_by_id=4438\nAND o.survey_id in (42)\n ORDER BY o.id DESC LIMIT 20001","code":44,"file":"D:\\web sites\\warehouse1\\system\\libraries\\drivers\\Database\\Pgsql.php","line":342,"trace":[]}`

**Comment by BirenRathod** [comment]
This suggest that query stop in the middle while getting data, due to long list of data.

**Comment by johnvanbreda** [comment]
It's not really the amount of data, but the way the query planner fails to use indexes efficiently. 
I've just tested this on iRecord_dev (v2 warehouse). Good news. The query returns in approx 1 minute by default, as there are some small improvements in indexing. Better news - if the useJsonAttributes=1 parameter is passed to the report, then it returns in a couple of seconds. The latter case means you don't get the term IDs for attribute values, but I suspect these are very rarely used.

**Comment by kitenetter** [comment]
Hi @johnvanbreda this user has been chasing us for an update - can you let me know when the fix is likely to appear on the live site?

**Comment by johnvanbreda** [comment]
I've switched @useJsonAttributes=1 on, so the new method of outputting attributes is used. This makes the download MUCH faster, so worth the risk over the small format change (i.e. the term IDs are not in the report anymore). 
Graham's data downloads in a few seconds now.
