### ISSUE TITLE
Notifications being sent out from test version of iRecord?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#446]
I've only had a report from one user so far, but he has apparently been receiving a lot of notification emails that contain record ID links back to 
http://test.brc.ac.uk/irecord_dev/record-details?occurrence_id=7912698

That page generates an SQL error message.

Presumably we shouldn't be sending out notifications from the test site?

**Comment by BirenRathod** [comment]
@kitenetter 

http://test.brc.ac.uk/irecord_dev/ site has got copy of live irecord data, so the all the settings go along with it. I can simply disabled the email but that means other test site could affect too. Is there any way, I could disabled the notification with in the website?

**Comment by DavidHepper** [comment]
FYI, I receive frequent blank notifications of Records to Verify - no records listed - and have had more than usual in the last few days. I speculated before as to whether these are to do with Training Mode records but when nothing is listed it's hard to tell.

**Comment by johnvanbreda** [comment]
Apologies if this has been happening. The dev_warehouse code has all calls to $swift->send commented out to prevent this, but it is obviously not enough.  @BirenRathod, should we change the email config so it cannot send emails?

**Comment by BirenRathod** [comment]
@johnvanbreda 
I could change email config in PHP on dev warehouse. is that ok?

**Comment by johnvanbreda** [comment]
Yes I hope so.

**Comment by BirenRathod** [comment]
I disabled the email in php configuarion on dev warehouse server.

**Comment by kitenetter** [comment]
I haven't received any further duplicated emails myself, so it looks like this is fixed, thanks. Closing.
