### ISSUE TITLE
Species available for data entry but not for filtering via Explore

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#447]
The Zig-zag Sawfly, Aprocerus leucopoda, can be entered into iRecord, but I cannot find this taxon if I try to filter by species via the Explore pages.

This taxon was added to the system in July:
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/431227

I can't see any setting in the warehouse that would make it unavailable for general use.

**Comment by johnvanbreda** [comment]
Taxon rank data not set properly in the cache table data - now fixed.
