### ISSUE TITLE
Unexpected validation message on data entry

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#452]
For the "Natural England Surveys" dataset (survey_id 509) we have a custom sample attribute "Survey reference code" (attribute_id 1144). In the "Survey settings" the length of this text field is specified as being between 1 and 20:

![image](https://user-images.githubusercontent.com/16039111/49657778-61292880-fa38-11e8-9bce-9e0d5a7edd28.png)

As far as I'm aware this attribute has been successfully populated in the past, but today a user reports that when entering data they get a validation message:

![image](https://user-images.githubusercontent.com/16039111/49657865-874ec880-fa38-11e8-8f95-d3facfc237a2.png)

How can I reset this so that the attribute accepts longer text?

And do we know why this behaviour has changed?

**Comment by kitenetter** [comment]
I have resolved this at least temporarily by removing the "Length" setting altogether from the survey settings. The "Survey reference code" text box now accepts longer text again.

The wider question is why the 1-20 limit cannot be used. I've tried re-applying it and that results in the same error message reappearing, only allowing 1 character to be entered.

**Comment by johnvanbreda** [comment]
Fixed in develop branch of code.
