### ISSUE TITLE
Records to transfer to Natural England Surveys

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#455]
As a result of #452 a set of NE records got entered into the iRecord general survey, and now need to be transferred to Natural England surveys.

Requirements:
For record IDs from 8687376 to 8688843 (472 records in total I think), entered by user "NEFU" (Indicia Warehouse User ID: 131311):
- move from survey_id 42 (iRecord general data) to survey_id 509 (Natural England Surveys)
- add "NEFU" into sample custom attribute id 1144 (Survey reference code)

**Comment by kitenetter** [comment]
This still needs doing - will add to September milestone and we can review.

**Comment by kitenetter** [comment]
Note that when the records are transferred this should not result in them being set back to unverified - any existing verification status needs to be retained.

**Comment by burkmarr** [comment]
@kitenetter & @johnvanbreda - can I have your views on what to do about attribute values for these records where the occurrence and sample attributes are in the general survey but not in the NE survey?

**Occurrence attrs**
The general survey has 'Stage' (attr 106), but NE surveys has 'Stage (extensive)' (attr 124). All the attr values for 'Stage' are set to 'Not recorded' - int_val 1949 from term list ID 127. This would translate to int_val 10657 in term list ID 136 for the NE survey. Should I just update the 'occurrence_attribute_id' and 'int_value' fields in the 'occurrence_attribute_values' table for these records?

**Sample attrs**
There are a number of sample attributes in the general survey which are not present in the NE survey but for which some of these records have values:

- 8 - Email
- 36 - First name 
- 58 - Last name
- 209 - EUNIS Habitat

There's nowhere for the email attribute to go. Shall we just mark the corresponing records in the 'sample_attribute_values' table as deleted?

Should we use first name and last name to populate the 'Recorder name' (attr 127) attribute for the NE survey? (Although this attribute is also present in the general survey, none of these records have values for it.)

In the general survey, EUNIS Habitat is attr 209 whilst in the NE survey it is attr 1065. However, both use the same termlist of attribute values (EUNIS Simplified, ID 103). So I guess I only need to update the value of 'sample_attriubte_id' in the 'sample_attribute_values' table for these records from 209 to 1065?

**Comment by kitenetter** [comment]
@burkmarr as far as I can see the outomes that you are proposing are correct, so it's just a question of whether these are the correct operations to achieve those outcomes. They look correct to me.

For the sample attributes, the email and name information must mean that the records were added by users who were not logged in. Arguably we could attempt to repatriate the records to the user accounts of the recorders concerned, but I don't think the added complexity is jusitifed in this case, the main objective is to have these records included in the NE dataset. If we can populate the Recorder name appropriately based on the First name and Last name that would be excellent.

**Comment by johnvanbreda** [comment]
Note that the email, first name and last name attribute values can be filled in even when logged in depending on how the form is configured, as it can fill in hidden attributes for you.

@burkmar I agree with the suggested operations above.

**Comment by burkmarr** [comment]
Thanks both for your comments. @johnvanbreda can you give me any guidance on how to avoid triggering reverification. Do I have to avoid updating the 'updated_on' field? I'm going to have to insert records into the 'occurrence_attribute_values' for this:

> add "NEFU" into sample custom attribute id 1144  (Survey reference code)

Can I do that without triggering verification?

**Comment by johnvanbreda** [comment]
Re-verification is handled by logic in the model code, so if you make manual changes to the data it should not cause re-verification.

**Comment by burkmarr** [comment]
Okay thanks Jon. For some reason I thought that updating the updated_on could trigger something.

**Comment by johnvanbreda** [comment]
Updated_on changes trigger cache table updates (excluding occurrences as they update cache data immediately). It also triggers rule checks, but should not change the record_status as that's done at the point of saving via the model code.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - that clears up my confusion.

**Comment by burkmarr** [comment]
@kitenetter - I did this today and it looks to be all okay to me.

**Comment by kitenetter** [comment]
Many thanks @burkmarr - closing.
