### ISSUE TITLE
Species "summary detail" map report not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#456]
The "summary details" pages are producing an error message for the species map element: "general_errors.Unable to find report reports_for_prebuilt_forms/species_details/species_record_data.xml."

Example:
https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=81987

**Comment by johnvanbreda** [comment]
Fixed by 3e0329d62c1621a80bf11ab5d3a732420a817549
