### ISSUE TITLE
Verification filters: 'what' and 'where' settings not being applied to downloads

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#457]
A number of county verifiers are reporting that their verification page is showing records from the whole country, and that if they download they also get records from everywhere.

I've tested this with my own filter for Berkshire moths. If I look at the filter via https://www.brc.ac.uk/irecord/filters/admin-list it seems to be behaving correctly, and only shows Berkshire records. I tried re-saving it, but on returning to my verification grid it is still displaying records from all counties.

**Comment by kitenetter** [comment]
Further related information reported by David Hepper:

There seems to be a problem with the Record Checker background process for Odonata records.
- The verifier for Cheshire is seeing all the 'Pending auto-check' records recently entered for Oxfordshire. Example ID: 8709484.
- That import completed 11:15 today but it is now 12:26 and they are still Pending auto-check.
- The above imported records have an 'Output map reference' set but I thought this processing was done along with the Auto-check.
- The verifier for West Kent is seeing all the above plus auto-checked records of many for other counties - and can query or verify them. Example: JvB's Dorset record: 8701852. This suggests that there is a problem with the access control restrictions, even after the Auto-check has run.

**Comment by DavidHepper** [comment]
This could be a regression of some sort. The code that used to assign records to the VC that has the larger proportion of the grid square's area seems to have been dropped. Old boundary-straddlers are again being assigned to _both_ VCs, e.g. 6835208 is now visible to Surrey and West Kent verifiers, whereas until last week it was only visible to West Kent.
However, Stephen Coker reports that more unverified records are visible in Explore for Pembrokeshire than in Verify for his Carmarthenshire+Pembrokeshire context. (Sorry, I haven't had time to look for record IDs but could if you need me to.)

**Comment by kitenetter** [comment]
Update: for my Berks moths verification role the verification page now seems to be filtering correctly again, and the verification download is also back to normal, thanks. Haven't re-tested any of the issues that David has reported.

**Comment by kitenetter** [comment]
Not sure if this is part of the same issue or a new one. Keith Fowler https://www.brc.ac.uk/irecord/user/6771 reports (18 December) that when he tries to download under his verification filters he gets records filtered for the correct VC but not filtered at all for taxon group.

I've just tried to reproduce this for his Shropshire true bugs verification role but the download timed out, which I assume indicates that it is failing to filter by taxon group as there shouldn't be many records involved.

**Comment by DavidHepper** [comment]
I confirm that visibility of records is back to normal for verifiers restricted by VC.

**Comment by kitenetter** [comment]
There are still some issues with the download of records for verifiers. For example, Keith Fowler has three verification roles, one nationally and two locally. If he downloads a csv file for any one of his verification roles he is given data for **_all_** taxonomic groups (i.e. no taxonomic filtering is applied).

If I go to edit his filter set-up page, the records shown in the grid are being correctly filtered to the taxonomic group. However, there is no indication in the "What" part of the filter that a taxonomic filter is being applied - the initial view has no taxon filter:

![image](https://user-images.githubusercontent.com/16039111/50835225-114ac380-134e-11e9-9c3d-05a00e7665fc.png)

and if I open the "What" section it appears not to have remembered the taxon filter that was initially set:

![image](https://user-images.githubusercontent.com/16039111/50835290-350e0980-134e-11e9-9a05-c90172accab2.png)

If I re-apply the taxon filter (Psocoptera in this case) and then save the verification filter, the download behaves correctly and only includes the Psocoptera.

Why is the download behaving differently to the grid on the verification page?

And, more worryingly!, does this mean I have to re-save our existing filters or is there a way of correcting this behaviour for all filters?

I had the same experience with filters for the Agromyzidae recording scheme - downloads were producing all taxa, but reverted to the correct family after the filter had been re-saved.

**Comment by johnvanbreda** [comment]
Hopefully now all sorted - it related to a bug in the conversion from old style verification filters (where there was a separation between "higher taxa" of family and above and taxa beneath family level) and the new style where this separation is gone.
Martin - I've not applied the fix to the loading of the descriptions on the filter edit page, this will trickle through in due course.

**Comment by kitenetter** [comment]
Great, thanks John
