### ISSUE TITLE
PoMS data entry selection form failing to load

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#458]
From the PoMS activity "1km square survey - pan-traps" (group_id 1073) I need to use "Species data: select pan-traps" in order to enter PoMS specimen data. That button takes me to:
https://www.brc.ac.uk/irecord/node/7165?group_id=1073&implicit=f

On that page, the map is displaying but not the data table, and an error message is given:
```
The data did not load successfully. The reason given was: 
There was an SQL error: ERROR:  column s.blocked_sharing_tasks does not exist
LINE 16: ...ND (su.website_id in (23) OR s.created_by_id=1 OR s.blocked_...
                                                              ^ - SELECT COUNT(*) FROM (
  SELECT *
  FROM samples s
  JOIN surveys su on su.id=s.survey_id and su.deleted=false
  JOIN websites w on w.id=su.website_id and w.deleted=false
  LEFT JOIN (sample_attribute_values savrecorder
      JOIN sample_attributes sarecorder on sarecorder.id=savrecorder.sample_attribute_id and sarecorder.deleted=false
           and sarecorder.system_function='full_name'
  ) on savrecorder.sample_id=s.id and savrecorder.deleted=false
  LEFT JOIN locations l on l.id=s.location_id and l.deleted=false
  JOIN system sys ON sys.id=1
  LEFT JOIN sample_attribute_values sample1093 ON sample1093.sample_id=s.id AND sample1093.sample_attribute_id=1093 AND sample1093.deleted=false
LEFT JOIN cache_termlists_terms ltt1093 ON ltt1093.id=sample1093.int_value
 
  WHERE s.deleted=false
  AND (su.website_id in (23) OR s.created_by_id=1 OR s.blocked_sharing_tasks IS NULL OR NOT s.blocked_sharing_tasks @> ARRAY['R'::character ])
 AND su.website_id in (101,108,43,13,97,33,29,44,87,98,12,24,14,17,6,8,25,11,7,30,5,27,34,40,32,42,51,49,65,68,73,75,9,71,88,10,23,69)
 AND ('2018-01-01'='Click here' OR s.date_end >= CAST(COALESCE('2018-01-01','1500-01-01') as date))
AND s.record_status<>'R'
AND s.group_id=1073
AND s.record_status<>'R'
 LIMIT 42) AS subquery
```
Apologies for marking another issue as urgent but we're on a very tight schedule to get the PoMS data entered.

**Comment by johnvanbreda** [comment]
No apologies needed! I've fixed the page, BUT note the following:
1) The reason why this report failed was that it is a report that is not under source control for some reason, so I did not spot it when reviewing reports after making changes. In fact it is explicitly excluded under the Git configuration on the warehouse. 
2) Also, I noted that the grid report had poor performance. This is due to the inclusion of the pan-no attribute in the grid. The new warehouse version has a MUCH faster way of getting the attribute values out for reporting, so I have enabled it (using a parameter useJsonAttributes=1), but this new method relies on a task queue catching up (which will take another day or two to process all 8.5m records). So you may find that the pan trap no field is blank for the moment (you can edit the page and remove the option if you prefer).

Leaving this open as a reminder to review all the non-standard reports not under source control.

**Comment by kitenetter** [comment]
For info the pan-trap numbers have not yet re-appeared, so as yet I'm unable to enter PoMS data. I assume the processing is still in progress.

**Comment by johnvanbreda** [comment]
Apologies - I'd missed a bit of configuration that hid the new type of column. Now fixed.

**Comment by kitenetter** [comment]
The form is now loading and showing the pan trap numbers, but my normal practice is to use the column-head filter boxes to find the site that I need, and if I do that I get a similar error message:
```
The data did not load successfully. The reason given was: 
There was an SQL error: ERROR:  column s.public_entered_sref does not exist
LINE 18: AND s.public_entered_sref ILIKE 'sk0%'
             ^ - 
  SELECT s.id as "sample_id",
null as date,
st_astext(s.public_geom) as "geom",
1 as "sref_precision",
snf.attrs_json->>'1093' as attr_sample_1093
  FROM cache_samples_functional s
  JOIN cache_samples_nonfunctional snf ON snf.id=s.id
  JOIN system sys ON sys.id=1
  
  WHERE (s.website_id in (23) OR s.created_by_id=1 OR s.blocked_sharing_tasks IS NULL OR NOT s.blocked_sharing_tasks @> ARRAY['R'::character ])
 AND s.website_id in (101,108,43,13,97,33,29,44,87,98,12,24,14,17,6,8,25,11,7,30,5,27,34,40,32,42,51,49,65,68,73,75,9,71,88,10,23,69)
  
  AND ('2018-01-01'='Click here' OR s.date_end >= CAST(COALESCE('2018-01-01','1500-01-01') as date))
AND s.record_status<>'R'
AND s.group_id=1073
AND s.record_status<>'R'
AND s.public_entered_sref ILIKE 'sk0%'
 LIMIT 2000
```

**Comment by kitenetter** [comment]
P.S. if this is easy to fix that would be appreciated, but I do have a plan B for storing the data outside iRecord, so this issue needn't take priority over other things.
