### ISSUE TITLE
Spreadsheet Import appears to work but shows no imported records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#459]
Pat Batty reports that, since the warehouse changes last week, importing from CSV claims to have imported records but does not show them in Verify. I've looked in Explore for recently-imported records in Scotland but found nothing. Are they in limbo somewhere?
(She made no selection for the new field Sample Method but the system did not complain.)

**Comment by johnvanbreda** [comment]
Hi @DavidHepper can you supply more information, e.g. when the import was attempted, plus the details (grid ref, date, species) of a few example records please.

**Comment by DavidHepper** [comment]
The attached CSV (saved as .TXT to make it acceptable to GitHub) was uploaded by Pat without error along with about four others at about 16:00 on 18/12/2018.
[aDRN Template julie hogg CSV.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/2696510/aDRN.Template.julie.hogg.CSV.txt)

**Comment by DavidHepper** [comment]
I have found the missing records by removing any Where condition. This problem is almost certainly caused for Pat by the assignment bug to do with verifiers who cover more than one VC. See #461
