### ISSUE TITLE
Map behaviour on verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#46]
When you verify a record, it is removed from the grid and the next record is highlighted, but the map doesn't update to show the next record's location - would be very helpful if it did.

Additionally we have had requests to allow verifiers to customise what the map displays, i.e. to make it easier to turn layers on and off, and to display records at full location precision even when blurred for public display. Request from Jon Bielstein was:
"ideal world - click on record = map to zoom in to record with record displayed using recorder input (ie not distorted by sensitivity blurring) with no other data displayed on map. Or ability to select this on the map’s ‘+’ menu. Currently the map has lots of blue and green squares from other records, and displayed at form output ie public sensitivity view."

**Comment by johnvanbreda** [comment]
Fixed in the code and will be deployed to iRecord on the next feature release.
