### ISSUE TITLE
Filtering not working correctly for multiple VCs

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#461]
I've just set up a new verification filter for Diptera in the two Sussex vice-counties, and was surprised to find that it only listed 17 records. It looks like the filter is only including records that fall on the border between the two VCs - in other words it seems to be doing an "AND" query rather than an "OR" query. I get the same result via Explore - all records:

![image](https://user-images.githubusercontent.com/16039111/50279646-367c9e00-0442-11e9-9521-1a4239882cfb.png)

**Comment by DavidHepper** [comment]
This affects many verifiers of Odonata who cover more than one VC. We've had similar issues several times before. #157 might be relevant.

**Comment by johnvanbreda** [comment]
Fixed - there was a bug in the location filter logic when including multiple locations.
