### ISSUE TITLE
Unable to access warehouse via menus

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#463]
Not sure if I'm being daft, but I can't find a way to get in to any of the warehouse options. The top level menus are all visible (Lookup lists, Custom attributes etc.) but when I click on the menus nothing happens.

This is for http://warehouse1.indicia.org.uk/index.php/

**Comment by BirenRathod** [comment]
Blocking to access for non-admin users.

**Comment by DavidRoy** [comment]
I raised this issue here https://github.com/Indicia-Team/warehouse/issues/313

A problem on Chrome but not IE for me

**Comment by johnvanbreda** [comment]
Duplicate of https://github.com/Indicia-Team/warehouse/issues/313
