### ISSUE TITLE
English name change

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#464]
Please can we remove the vernacular name "Soldier-fly" from the species Odontomyia hydroleon, keeping the alternative "Barred Green Colonel" alone. This is correct in UKSI:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NHMSYS0020193707

but not in iRecord, which currently has both English names linked to Odontomyia hydroleon, leading to numerous erroneous records of this extremely rare species.

**Comment by johnvanbreda** [comment]
Flagged as "not for data entry". If you want the 5 remaining unverified records switched to Soldier flies (Stratiomyidae) let me know - we can do this for just the records that were input using the common name Soldier-fly and avoid any records that used the latin name (which were most likely to be deliberate).

**Comment by johnvanbreda** [comment]
@kitenetter Looking at the UKSI data, there are common names Soldier-fly and Soldierfly for this taxon. Although they are junior synonyms they will still be imported into our dataset next time there is an import unless Chris either removes them altogether, or marks them as redundant.

**Comment by kitenetter** [comment]
@johnvanbreda I can't see any unverified records assigned to Odontomyia hydroleon.

I can't remember what the position is with vernacular names. For this taxon, "Soldier-fly" is marked as a junior synonym, and "Soldierfly" is marked both as a junior synonym and as ill-formed. Whereas "Barred Green Colonel" is marked as the accepted name.

Are we able to filter out ill-formed and/or junior synonym names from the UKSI, or did we decide that the UKSI labels for vernacular names have not been applied sufficiently consistently for this to be safe? Is our **_only_** option to ask Chris to make the UKSI names redundant?

**Comment by johnvanbreda** [comment]
My discussions with Chris & Richard Shotbolt around a year ago (when the BMS updates were being applied) included several statements where it was implied that ill-formed names should not be dropped en-masse, as they may be required in some cases where there is nothing better. For example Chris said the following in relation to how to pick the best common name for a concept:
"I try to calculate the most appropriate English vernacular I filter by Language and Recommended TVK and then sort them to put well-formed above ill-formed and recommended above synonym - then pick off the first name in the list."

My own preference actually would be for UKSI to include a new "useful for data entry" flag. This would allow names such as soldier-fly to exist on a taxon, so to be visible on any generated reports, but to be excluded for data entry purposes. Without that though I think we do indeed have to rely on making them redundant.

**Comment by kitenetter** [comment]
Can't remember how we resolved this but it is no longer a problem following the recent UKSI update - closing.
