### ISSUE TITLE
Guidance for iRecord verifiers in how UKBMS data is processed

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#469]
A short help note is needed for verifiers on how UKBMS (and NPMS?) data is processed

**Comment by kitenetter** [comment]
Note to self - NPMS info:
https://www.npms.org.uk/sites/default/files/NPMS_Data_Capture_Verification_FINAL.pdf

**Comment by kitenetter** [comment]
Due to be drafted by BC staff in partnership with us, to include BNM online as well, but need to chase.

**Comment by kitenetter** [comment]
I think this will be included in the 'toolkit' that BC are producing under Supporting Science. Closing.
