### ISSUE TITLE
Unable to save a 'Download' filter

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#47]
Urgent issue as required for data flow to the NBN.

http://www.brc.ac.uk/irecord/filters/admin-edit

Select filter type = Downloading, then click on Go
Under 'what' filter, set Family = Sepsidae

Set name = NBN - Sepsidae
For who = iRecord, iRecord

Then unable to save.  Nothing happens when click on save icon.

**Comment by johnvanbreda** [comment]
I just tried this and it saved OK (using Firefox on Windows). In fact filtering on the list shows that there is already an NBN Sepsidae filter set up a while back.
Do you still get the problem and which browser were you using?

**Comment by DavidRoy** [comment]
The bug is perhaps an error (or no action) when trying to save a filter with the same name as an existing filter.

I've tested again and can setup filters with new names ok

**Comment by johnvanbreda** [comment]
This morning though I managed to create an NBN - Sepsidae filter even though one already existed. However now I can only see one, I was sure there were 2 - did you delete one?

**Comment by DavidRoy** [comment]
I did delete one as assumed I'd created the second. I could only delete one of them.  The bin icon didn't appear on the other one.

**Comment by johnvanbreda** [comment]
Ok, so that does mean I succeeded in saving a duplicate name. Are you sure you can't save one with the same name?

**Comment by kitenetter** [comment]
Assumed closed unless problem reoccurs
