### ISSUE TITLE
Update iRecord logo

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#471]
on www.brc.ac.uk/irecord

to use this version with (R)

![irecord_logo_positive_rgb](https://user-images.githubusercontent.com/2699478/50968581-77148800-14d3-11e9-9022-9d16fbbe619f.jpg)

**Comment by BirenRathod** [comment]
I have updated the logo on iRecord website.

**Comment by DavidRoy** [comment]
Thanks
