### ISSUE TITLE
Range of record IDs not working in column header filter of Grid

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#472]
In **Explore > All records** (and probably also in Verify), the pop-up help for the Grid dynamic filter cell of **ID** column ends with "... or enter a range such as 1000-2000" but if I enter range "5463300-5463320" (without the double-quotes) I receive an error:
```
The data did not load successfully. The reason given was: 
Invalid numeric parameter value 5463300-5463320 for occurrence_id
```
This might prompt a wider review of the usefulness of the **Create a filter > Record ID** facility for anything other than an exact match to a single ID number.

**Comment by johnvanbreda** [comment]
Fixed. The column names and ID report parameters were clashing.
