### ISSUE TITLE
Unable to access PoMS reports on iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#474]
I've just tried to access some of the reports set up via the PoMS activity pages - they were working over Christmas but are now showing no data and have the message:
Unable to find report library/samples/filterable_explore_list_2.xml.

**Comment by BirenRathod** [comment]
@kitenetter 
That report is now copied onto new server. it was not doenloaded from repository.

**Comment by kitenetter** [comment]
Thanks! Closing.

**Comment by kitenetter** [comment]
One of the three reports I needed is working correctly. However, the other two are displaying the correct dots on the map, but appear to be showing an unfiltered view of all iRecord data in the records grid.

I don't think this is urgent at the moment, will check on Monday.

**Comment by BirenRathod** [comment]
@kitenetter 
I have copied another two reports in the same folder see if that help.

**Comment by kitenetter** [comment]
No, they are still showing all records in the grid.

**Comment by kitenetter** [comment]
Another problem has emerged. From the activity "1km square survey - pan-traps" (id 1073), if I try to add a record using the button "ENTER pan-trap data" I get taken to:
https://www.brc.ac.uk/irecord/poms-1km-pan?group_id=1073&implicit=f

In the Location box on that form, what should happen is that an auto-complete looks up one of the pre-defined PoMS 1km squares, but it is currently only showing a list of "undefined" sites.

I'm afraid this is bumps it up into the urgent category again, as we need to get all the PoMS data entered.

**Comment by BirenRathod** [comment]
@johnvanbreda 
I uploaded that onto Live warehouse and added to develop branch of Git as well.

**Comment by kitenetter** [comment]
Thanks. That's fixed the urgent issue with data entry.

There is still a problem with some forms that are mapping the PoMS sites correctly but not filtering the data grid that appears under the maps:
https://www.brc.ac.uk/irecord/node/7157?group_id=1073&implicit=f
https://www.brc.ac.uk/irecord/node/7119?group_id=1073&implicit=f

Also, if I try to apply column-head filters to these reports I'm getting an error message that starts:

![image](https://user-images.githubusercontent.com/16039111/51317726-44790b00-1a50-11e9-9ce5-a17ae1f69e15.png)

(And this is perhaps a separate issue, but can we make it possible to copy the full text from these error message pop-ups?)

**Comment by johnvanbreda** [comment]
@BirenRathod why is the library/samples/filterable_explore_list_2.xml not in GitHub? Is it a special report for this project? If so then should it go in the brc_reports repository?
The first problem here was that this report was incorrectly structured, it had a line:
```
AND #sharing_filter# 
```
instead of 
```
WHERE #sharing_filter# 
```
I've fixed that.

**Comment by BirenRathod** [comment]
@johnvanbreda 
I'm not sure why? it was like that in the previous server and I haven't changed anything for filter too.

**Comment by johnvanbreda** [comment]
It may be that the problem Martin mentions with filtering existed before the server was moved. We should be aiming for the situation where all the reports under the reports folder are generic, core Indicia reports which are in Git, whereas any project specific reports are under brc_reports in the indicia-reports Git repository. So I was just suggesting this report should be added, or moved to brc_reports if just for POMS.

**Comment by kitenetter** [comment]
I'm not sure if the report has been moved yet, but the two PoMS forms are still displaying the incorrect set of records in the grid.

As far as I'm aware Jim wrote the report/s for these forms, and as far as I know they were specific to PoMS. I'm 99% sure that the column-head filtering was working correctly before the server move.

**Comment by kitenetter** [comment]
Now fixed - problem was an error in the report SQL. Closing.
