### ISSUE TITLE
NBN data file exports failing to produce valid files

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#477]
Among the most recent set of automated export zip files there are quite a lot that are invalid, see screenshot below. Some of these are the larger datasets, but others are relatively small.

NBN have also requested some changes to the EML data that I am working on at the moment, so most of these files will ideally need to be re-exported this week if we can in any case, but we need to investigate why the files are failing to be created correctly.

![image](https://user-images.githubusercontent.com/16039111/51111891-8b1ef900-17f5-11e9-9f7a-ad6aaacd015f.png)

**Comment by BirenRathod** [comment]
@kitenetter 

Could you send me the URL of this page to access the files?

**Comment by kitenetter** [comment]
@BirenRathod the files are the ones that we set up from here:
https://www.brc.ac.uk/irecord/exports

and which get saved into:
exports (\\WLBRCWEB1)

**Comment by kitenetter** [comment]
See also previous similar issue #433

**Comment by johnvanbreda** [comment]
@BirenRathod if you haven't already made progress, leave this to me as I understand this part of the code.

**Comment by BirenRathod** [comment]
@johnvanbreda 
I was just checking the path on the server which is fine. So rest I leave it with you.

**Comment by johnvanbreda** [comment]
Turns out to be same issue as https://github.com/BiologicalRecordsCentre/iRecord/issues/457. Fixed and files regenerated.

**Comment by kitenetter** [comment]
Files seem to be fine now, thanks @johnvanbreda 

Two queries over the Natural England dataset (not sure if they apply to other datasets, but I've noticed them in the NE one):
1. Some app records are being exported with lat/long, while others are using the output grid ref. My expectation was that we should always use the output grid ref, is there a reason why this isn't always being done? Example record that is being exported with lat/long: https://www.brc.ac.uk/irecord/record-details?occurrence_id=5506021
2. In column datasetID, the text is now being exported within double quotes (or at least that is how it appears if I open the csv into Excel), whereas previously it was just text. I don't know if this will cause any problems for NBN, but it is a change in behaviour from previous exports.

**Comment by johnvanbreda** [comment]
@kitenetter -
1. The logic currently in place is that we output decimalLat and decimalLong for ALL records, unless the records are sensitive in which case we use the blurred output sref. Not sure if that is the correct logic though so let me know if it needs changing.
2. I've fixed this.

**Comment by johnvanbreda** [comment]
1. Sorry, I misread the code. The logic is:
IF sensitive OR a grid reference (i.e. not lat long, easting northing, UTM or similar), THEN output_sref
ELSE decimalLat and decimalLong.

In other words, if the app submitted a lat long, then we use that, apart from sensitive records when we always use the output sref.

**Comment by kitenetter** [comment]
Thanks John, that makes sense - I thought we were always using output grid refs but there's no reason not to use lat/long for records that were created that way. Closing.

**Comment by kitenetter** [comment]
@johnvanbreda it would be very useful to be able to generate a NBN export file for BDS, as a test so we can work out what needs to be done for the real thing, but the export process is failing (only generates a 5kb zip file which is invalid).

Is it possible to generate a file under our current system or will this need further development e.g. via elasticsearch?

The export filter is at:
https://www.brc.ac.uk/irecord/node/7478/edit?destination=exports

(At present there is no EML in this filter, could that be causing problems?)

**Comment by kitenetter** [comment]
The larger datasets are failing to export at 2 May 2019. Let me know if any more information is needed.

**Comment by DavidRoy** [comment]
@johnvanbreda to provide SQL to export larger datasets by hand. 
@kitenetter to export

**Comment by johnvanbreda** [comment]
I've committed a change so that on error, you should find a readme file containing the SQL and instructions on how to repair the archive.
