### ISSUE TITLE
NBN exports: vernacular names appearing in scientificName column

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#478]
The NBN import process fails if it encounters a vernacular name in the scientificName column. I'm not sure how often this happens or which sources are involved.

One is the Capturing our Coast dataset, which has a wider range of vernacular names in the scientificName column, including "Barnacles", "Total algal turf", "Total algal canopy" etc. 

There must be at least some other sources involved as well but I haven't yet been able to track them down.

The export process recognises that these are vernacular names and includes them under the vernacularName heading, but we need to exclude them from the scientificName column.

The NBN import routine ignores vernacularName if there is an entry in scientificName, so if it finds a vernacular in scientificName it fails to match it and then ignores any data in vernacularName.

**Comment by johnvanbreda** [comment]
I've fixed this in an upcoming hotfix (which I will deploy today or tomorrow). But, aren't we supposed to be holding back the CoCoast data from the export to the Atlas, until Stephanie Dickens confirms otherwise?

**Comment by kitenetter** [comment]
@johnvanbreda Yes, it is just that of the datasets that have exported correctly CoCoast was the only example I could find! There must be others though otherwise NBN wouldn't have raised the issue.

**Comment by johnvanbreda** [comment]
Ok, the fix is generic though so it should be OK. The changes are:
1) Exclude ALL taxa which don't have a TVK assigned.
2) If the taxon has a common name in the preferred name column, the scientificName value exported is empty.

**Comment by kitenetter** [comment]
Re point 1, for the weevil recording scheme dataset it was reported that TVKs were missing for some species that had a valid scientificName. I don't have access to the weevil export file at the moment so can't check the sources of the records concerned, but is there a danger that we will lose valid records due to lack of a TVK (for whatever reason)?

**Comment by johnvanbreda** [comment]
Ah, I didn't realise the Atlas accepted records without a UKSI TVK - that's different to the old Gateway isn't it? If so, then I think the solution is to have a 2nd version of the Atlas extraction report for CoCoast and any other projects that want to exclude records which don't have a TVK. Shall I set that up @kitenetter?

**Comment by johnvanbreda** [comment]
@kitenetter Now that I can generate the file, I'll check the handful of Weevils that have no taxonID (TVK).

**Comment by johnvanbreda** [comment]
The records with missing TVK come from a specific coleoptera list set up for the Heathland Surveillance website. They don't have the TVK for each individual name loaded in the same way as UKSI, just the accepted.
I've changed the report so it reverts to the accepted name TVK if necessary and retriggered the weevil export.
