### ISSUE TITLE
Question: Null values from pgAdmin exports

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#479]
@BirenRathod in pgAdmin 3, the PoMS csv files contained empty strings, e.g.:

`2686921,21,"CMS User ID","",53,,53,"","2017-07-17 13:39:44","2017-07-17 13:39:44"`

In pgAdmin 4, these have been replaced by Null values, e.g.:

`2686921,21,"CMS User ID",NULL,53,NULL,53,NULL,"2017-07-17 13:39:44","2017-07-17 13:39:44"`

Is there a setting in pgAdmin 4 that I can change so as to go back to the empty strings? The Null values make the data harder to work with in Access.

**Comment by BirenRathod** [comment]
@kitenetter 

1. In the "File"menu, link called "Preferences", Click on that.
2. Change setting of "Replace null value with" empty string like "" in CSV oustput.
3. Here is the screenshot of that. 
![image](https://user-images.githubusercontent.com/5941255/51402217-c64a6080-1b44-11e9-8ceb-3c91932be4ea.png)

**Comment by kitenetter** [comment]
Excellent, thanks @BirenRathod - closing.
