### ISSUE TITLE
Querying locations in new cache table structure (through database access)

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#480]
The recent warehouse upgrade has change cache table structure.

Location_ids field now contains a list of ids.  Do these replace the vc, country IDs are not longer present.  If so, is there some example SQL or function to resolve the location_ids list.

**Comment by johnvanbreda** [comment]
Yes, the new structure is more extensible as it does not need a new field added for every indexed location type. Location_ids is an array of all indexed locations and can be queries as follows:
```sql
select * 
from cache_occurrences_functional
where o.location_ids && ARRAY[12345];
```
Replace 12345 with your location ID, or a comma separated list of locations if you want several.

**Comment by DavidRoy** [comment]
Thanks.  Have generally got it now but may take a bit of time to get used to.
