### ISSUE TITLE
NE records to delete

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#481]
Following the changes last year to move Natural England data into their own survey, there are a couple of loose ends to be tied up. 

**Record deletions**
Please delete 44 records in total:
- iRecord user 23209, Indicia Warehouse User ID: 102855
- Record IDs are 5365856 and then 43 further records within the range 5908794 to 5908891
- All were entered using the form  iRecord | Multi-site records | NEFU Surveys 2017

**App records to be linked to an activity**
The same user has 205 records on iRecord that have been added via the iRecord app. A proportion of these (we think totalling 134 records) are not linked to the NE surveys activity (due to the app not being linked to that activity for a period of time) - the request is to add this link, so that all the app records get included in the NE export to NBN.

Please add a link to activity group_id = 1120 for this set of (c. 134) records:
- for iRecord user 23209, Indicia Warehouse User ID: 102855
- for any record added using iRecord | App, and that is not already linked to activity group_id = 1120
- Record IDs are within the range 5002371 to 8800775

**Comment by kitenetter** [comment]
Another loose end that would be good to complete. Adding to September list for review.

**Comment by burkmarr** [comment]
@kitenetter - none of the records indicated in that range for the records to be deleted were created by user ID 102885. Record 5365856 was created by user ID 141180 and there are indeed 43 records in the identified range belonging to that user. Can you confirm the correct user for both parts of this issue (deletions and linking records to activity).

**Comment by kitenetter** [comment]
User for both operations is warehouse ID 141180 (iRecord user 35467).

(The IDs I originally gave were for my own 'iRecord support' account, so I must have been doing something spectacularly daft.)

The records that need to be linked to the activity should not result in them being re-triggered for verification.

**Comment by burkmarr** [comment]
@kitenetter - I've marked the 44 records as deleted as requested. 

When I ran the following query to identify records for the second part (linking records to a specified activity), I only find 33 records which is at odds with your figures. Have I missed an App dataset?
```sql
select * from occurrences o
join samples s on s.id = o.sample_id
where (o.id >= 5002371 and o.id <= 8800775)
and o.created_by_id=141180
and s.survey_id in (374, 576)
and s.group_id <> 1120
``` 
All 33 records this finds are from survey 374 (iRecord App) and none from 576 (iRecord App General Survey).

Rich

**Comment by kitenetter** [comment]
@burkmarr sorry it's taken so long to get back to this.

I ran this query:
`select * 
from occurrences o
join samples s on s.id = o.sample_id
where (o.id >= 5002371 and o.id <= 8800775)
and o.created_by_id=141180
and s.survey_id in (374, 576)`

That produces 241 occurrences.

Of those, 40 are already linked to group_id 1120, and another 33 are linked to group_id 982 (this must be the 33 occurrences that your query produced).

However, there are a further 168 records that are not linked to a group_id at all. A query to select these 168 records is:
`select * 
from occurrences o
join samples s on s.id = o.sample_id
where (o.id >= 5002371 and o.id <= 8800775)
and o.created_by_id=141180
and s.survey_id in (374, 576)
and s.group_id is null`

These 168 records need to be updated so that they have group_id = 1120 (but this should not result in changing their verification status).

**Comment by kitenetter** [comment]
Just to confirm that in order to close this issue we need one more update.

This should apply to 168 records, which can be listed via this query:
`select * from occurrences o join samples s on s.id = o.sample_id where (o.id >= 5002371 and o.id <= 8800775) and o.created_by_id=141180 and s.survey_id in (374, 576) and s.group_id is null
`
All of these 168 records need to be updated so that they have group_id = 1120 (but this should not result in changing their verification status).

**Comment by burkmarr** [comment]
@kitenetter to avoid altering deleted samples & occurrences I added `and s.deleted` to the above select which identified 134 samples and occurrences. (I also checked that there was a 1-1 relationship between the the samples and occurrences.)

I updated the group_id attribute on for the affected samples/occurrences in the samples table, the cache_samples_functional table and the cache_occurrences_functional table, so all should be done now.

```
select s.id as sample_id, o.id as occurrence_id 
into iss_irec_481
from samples s
join occurrences o on o.sample_id = s.id
where (o.id >= 5002371 and o.id <= 8800775)
and o.created_by_id=141180
and s.survey_id in (374, 576)
and s.group_id is null
and s.deleted = false

update samples
set group_id = 1120, updated_on = NOW(), updated_by_id=198219
from iss_irec_481 as u
where samples.id = u.sample_id

update cache_samples_functional
set group_id = 1120
from iss_irec_481 as u
where cache_samples_functional.id = u.sample_id

update cache_occurrences_functional
set group_id = 1120
from iss_irec_481 as u
where cache_occurrences_functional.id = u.occurrence_id
```
