### ISSUE TITLE
Notification emails: some format well, others do not

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#483]
The email notifications to me for records that are **Queried** (e.g. those that I've imported, so receive Queries from the verifier) do not format well in my preferred email client. The 'From' address of these is **noreply@brc.ac.uk** and they are missing the 'format=flowed' directive in the Content-Type line.
- Example of Body field source: [Query Source.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/2791003/Query.Source.txt)
- Example of Body field appearance: 
![query appearance](https://user-images.githubusercontent.com/24915271/51668645-95da4a80-1fba-11e9-84ee-7f38eabb0efc.jpg)

By contrast, the **Notification** emails, issued when records are verified, format well. It appears that they have better-formed HTML body fields. The 'From' address of these is **irecord@ceh.ac.uk** (better) and they include the 'format=flowed' directive.
- Example of Body field source: [Notification Source.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/2790950/Notification.Source.txt)
- Example of Body field appearance: 
![notification appearance](https://user-images.githubusercontent.com/24915271/51668071-52331100-1fb9-11e9-978d-49721ba1028f.jpg)

The format and sender of the Notification emails has been tidied up several times e.g. #209 and #61. Could a similar job be done on Query (and any other) emails, please? I need to log and tabulate queries of Imported records and this is currently impossible.

**Comment by kitenetter** [comment]
@DavidHepper are you still seeing formatting problems with the query emails?

**Comment by DavidHepper** [comment]
That goes back a long way. I get relatively few at present and would have to generate a few in Training Mode to test this.
By the way, I withdraw my complaint about blank notifications because I think that, as global verifier, I'm constantly being informed that records are being added that I _could_ verify.

**Comment by kitenetter** [comment]
Thanks David - I will close for now but let us know if the problem re-occurs.
