### ISSUE TITLE
Options for reducing use of GoogleMaps API

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#484]
Review use of GoogleMapsAPI now that Google have introduced a charging model.  Are there uses which are not needed?  Could we switch to OpenStreetMap for some requirements?

**Comment by kitenetter** [comment]
I think we've largely dealt with this haven't we?

However, I'm still finding that the map behaviour is frustrating when zooming in and out, with the map often jumping away from the location I am trying to view. Today this happened when trying to "Create a filter" from the Explore pages.
