### ISSUE TITLE
NPMS records being allocated to multiple VCs

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#485]
This issue has been raised by the Suffolk verifier for plants. It applies to a batch of records added to the NPMS "Extra species records" survey. An example is:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=7941622

The recorder entered the record with a 10-figure grid ref but also marked it as sensitive, so that the output grid ref is being given as a 10km square TM22. The precise location is well within VC North Essex, but the 10km square just overlaps the East Suffolk VC boundary where it is extended into inshore water.

This means that the Suffolk verifier now has rather a lot of Essex records in his verification stream.

**Question:** is it necessary to use the output grid ref to index the VCs, or could we use the more precise input grid ref?

**Question:** is there anything we can do to discourage NPMS recorders from blurring their records to such a large degree?

Not sure who is best placed to answer but would welcome views from @sacrevert @DavidRoy @johnvanbreda @japonicus

**Comment by johnvanbreda** [comment]
If we use the precise grid ref to index the VCs, then in this instance it will actually make the precise location of the record very clear indeed if it were a Suffolk record in the overlap. A blur to 10km with accurate VC data in some cases will in effect not be blurred at all.
We could have some sort of 2nd "secret" VC allocation for verification use, but this is then becoming rather complex. Or, perhaps for verification we would need an extra filter applied which limits based on the precise copy of the record - we could simulate this query fairly easily I think to test performance, but I have my suspicions it would make things slower.

**Comment by sacrevert** [comment]
Could the 2nd "secret" VC by a job that was run only occasionally (e.g. once a month), with verification view updates updated accordingly at the same time?

**Comment by kitenetter** [comment]
Another generic solution to this problem would be to provide an option for verifiers to be able to flag records as belonging to one VC or another, in cases where the grid ref overlaps the boundary. The main thing that is needed is a way for verifiers to be able to remove records from their grid if they are not applicable to their county role.

**Comment by DavidHepper** [comment]
Allowing verifiers to flag records as belonging to one VC or another would also help in cases where VC boundaries are tortuous, e.g. following rivers, and even records at 1km resolution frequently straddle boundaries. This isn't important in the great scheme of things, esp. for mobile groups such as flying insects, but it is good diplomacy to hand back records incorrectly assigned and helps the expected and actual numbers in the grid to match, especially after an Import. 

Note that imported dragonfly records already have an imported VC number, though this is currently ignored and not used in the automated assignment to VC. We would therefore have three VC fields available in some records:
- **Imported VC** - comment only;
- **Output VC** - computed by iRecord from the Output Grid Reference and can be more than one);
- **Assigned VC** - the new, authoritative field, initially set to 'Output VC' and changed only if a verifier has manually redetermined an ambiguous VC.

Should this scheme protect against a verifier making a mistake and setting a wildly-incorrect VC? iRecord _could_ check that the record is a border-straddler before offering the facility to redetermine the VC.

@sacrevert - iRecord's workings are obscure enough already without "secret VCs" and once-a month background jobs.

**Comment by sacrevert** [comment]
Hi @DavidHepper, the "secret" (i.e. second) VC was @johnvanbreda 's idea, not mine, and there are already numerous scheduled background tasks that take place within the iRecord system that the typical user is oblivious of. Anyway, it seems that @johnvanbreda is best placed to test these suggestions for performance implications and make a decision, presumably even adding "flagging" options has implications for the speed and complexity of the system.

**Comment by kitenetter** [comment]
Picking up this issue in #827 - closing it here.
