### ISSUE TITLE
Download of records produces empty file with multiple filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#487]
@DavidRoy reported that the download options for verifiers are producing empty files when additional filters are used. I haven't tested all combinations, but empty files have resulted from:
- Download type = Verification + "Survey to include" additional filter
- Download type = Verification + "Filter to apply" additional filter

I don't know for certain whether these filter combinations used to work in the past, but given that it seems logical for verifiers to want to use the options that the download form provides it seems that they ought to work.

I haven't yet checked whether similar problems arise for non-verifier users when applying multiple filters.

**Comment by kitenetter** [comment]
This has arisen again for the PlantLife Rapid Woodland Assessment project. We've given them a download permission, and they can get a generic records download, but they need to access their custom attributes.

Is it possible to fix this easily, or do I need to set up a manual SQL export?

**Comment by johnvanbreda** [comment]
@kitenetter can you let me know what username so I can masquerade, and exactly which download page and settings to try? I just tried to recreate the original error on my own account and it worked OK.

**Comment by kitenetter** [comment]
@johnvanbreda user is:
https://www.brc.ac.uk/irecord/user/78826

Download settings:

![image](https://user-images.githubusercontent.com/16039111/73572539-f4a59000-4468-11ea-935f-60dfcf41cc6e.png)

(this is for the "south-west" rapid woodland assessment)
