### ISSUE TITLE
Auto-check reports a recording period warning for the wrong species

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#488]
Recently-imported record 9068553 of Dainty Damselfly _Coenagrion scitulum_ is showing an auto-check warning about its recording period (not flight period) but the warning names a different species, _Oxygastra curtisii._ It is unclear which species' recording period is being used to generate the warning. I have not seen this class of warning before.
![wrong species auto-check warning](https://user-images.githubusercontent.com/24915271/52345516-5594b680-2a15-11e9-9d59-dd8e4c7b36b6.jpg)

**Comment by kitenetter** [comment]
This appears to have been corrected in the record cleaner ruleset. Closing.
