### ISSUE TITLE
Change behaviour of 'Explore' page for logged-out users

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#49]
At the moment, if you are not logged in, you can click on the "Explore" menu and get taken to this page:
http://www.brc.ac.uk/irecord/explore

but there is no information on the page (the links that are available to logged-in users are missing for logged-out users).

We don't intend to make the full Explore menu available to logged-out users, but the current page is unhelpful.

- Short-term solution: remove the "Explore" menu from view for logged-out users.

- Longer-term solution: create a report for logged-out use of the "Explore" page that will show some summary info (suggest total no. of records and species), along with an encouragement to register.

**Comment by JimBacon** [comment]
Longer-term solution implemented using two blocks, one shown to anonymous users, the other to authenticated users.
