### ISSUE TITLE
Urgent: Output Map Ref should recompute when (Original) Map Ref is corrected

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#490]
Where a record can be identified to a good monad, I'm asking my verifiers to correct the Map ref, if it is clearly wrong or too vague (e.g. only to hectad). The new ref is shown on the map in Verify but the correction does not update the Output map ref, nor recompute the VC to which the record belongs. It continues to be shown at the old location on the map in Explore. 
Example: https://www.brc.ac.uk/irecord/record-details?occurrence_id=11690 was originally at SO30 but redefined far away to SS9285.
Due to the important fix #275 the original ref continues to be shown in reports, too.
This is really urgent, please.

**Comment by johnvanbreda** [comment]
Hi @DavidHepper, as far as I can see when this particular record was edited the spatial reference input field was updated but the map itself did not update the geometry. Therefore the record has not really properly been moved, just the label given for the map reference was changed. I've just re-edited it and saved it correctly.
Do you know if this was a one off, or are there other similar cases? 
If there are other cases, can you find out what browser was used. Presumably they were changed just by clicking the Edit link on verification and changing the record form?

Note that the update of VC boundary is queued so won't be instant.

**Comment by DavidHepper** [comment]
I ask verifiers to **Ctrl+Click** the **Edit** button, then close the tab when the changes have been saved.
ID 11689 had also been given the wrong original Input map ref. It was last edited on Friday, by Steve Preddy, who changed the grid ref using the form and Accepted it (because he still could, even though he's CDR for Monmouthshire). It the record has its Output grid ref set correctly, the same as Input grid ref. If you didn't change it, is the background process less frequent than 20 minutes? I looked ~20 hours later and it still showed as SO30.

**Comment by DavidHepper** [comment]
Steve uses Firefox, as do I. 
Could the problem here be because the input form is very old? 
I'm considering exporting data from the old forms, reimporting as 'DRN dragonfly imports' and requesting complete deletion of the old forms and their records.

**Comment by johnvanbreda** [comment]
The output grid ref should actually change immediately (unlike the VC which is indexed). But, when Steve edited this record there must have been a problem because only the spatial reference label changed, not the underyling geometry. Hence the output sref was left unaffected as it is calculated from the geometry. I re-saved the record yesterday which is why it has been fixed.

**Comment by johnvanbreda** [comment]
I don't think there is any issue relating to the age of the form as the code running the form is still up to date.

**Comment by DavidHepper** [comment]
I'll assume this was a glitch and close the issue but we don't really know why this happened.
