### ISSUE TITLE
Photo upload enhancement requests

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#493]
User requests three photo enhancements.

1. Ability to re-use one photo for several records
This is for cases when several species have been captured in a single photo. Suggestions are to either have a "list species" type recording form that would allow a photo to be added once and then linked to all the species records, or to add the ability to 'lock' a photo following the initial upload.

2. Ability to link existing photo to a new record
This assumes that a photo has been added for a record of one species, and then a second species in the same photo is subsequently noticed. The function requested is to go the older records and "copy photo to new record".

3. Ability to drag-and-drop photos
Request to add photo upload functionality by allowing drag and drop, in a similar way to Facebook's photo upload.

**Comment by DavidRoy** [comment]
My feeling is that 1&2 would add a lot of complexity but I'm not sure of the wider requirement for this.

I can see that 3 is a higher priority, particularly if record details (date, location) could be pre-populated from photo EXIF data

**Comment by johnvanbreda** [comment]
1. You can already support sample level photos on forms which is a partial solution. The data model actually allows several image records to point to the same file so it's technically perhaps not too bad once we sort out how the UI should work.
2. As above - the model allows for this, we just need a UI. This might be a bit niche though?
3. I agree with this requirement. Actually I think the plUpload component we use can support drag and drop plus extracting EXIF.

**Comment by kitenetter** [comment]
Drag and drop now implemented on site. Closing.
