### ISSUE TITLE
Verification grid - queried records not being removed from grid

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#494]
Looking at some records that I queried with the recorders some time back, I noticed that the "last update" date shown on the verification grid and the date associated with the query comment on the record do not match.    

As I manage queried records based on the "last action date", could this be looked at and the date on the verification grid accurately reflect the last time it was amended (around 3 months ago) , not last viewed (a few days ago).  See the example SS attached.

![image4](https://user-images.githubusercontent.com/18451743/53022264-b9c26c00-3452-11e9-90ad-1c2b0183f671.jpg)

**Comment by kitenetter** [comment]
Possibly related:
@MNSmith reports unexpected results from adding verifiers' queries to records

> I did some more verification last night and "Queried" a number of records from a recorder who I know is keen on iRecord and does check her notifications regularly.  From the ones I "Queried" yesterday I am now seeing some of them on the verification grid with the "Query raised and answered" icon attached.   This suggests that somehow the Recorder is getting a notification somewhere and responding to it, but I can't see where.
> 
> I tried "Querying" one of my own amphibian records - Rec No. 2994868 and one of my Aculeate records - 8593639.  In both cases the record now contains a comment marked as a Query but the record is still sitting in the grid showing an "Accepted - considered correct" icon, and I'm not seeing a notification of a change to the record status either.

Looking at the latter two examples for record numbers 2994868 (frog):
https://www.brc.ac.uk/irecord/record-details?occurrence_id=2994868

And 8593639 (bumblebee):
https://www.brc.ac.uk/irecord/record-details?occurrence_id=8593639

the latter seems to be displaying correctly in as both awaiting review and queried, but the former is showing as Accepted (even though as Matt says the query comment has been attached).

There seems to be inconsistency in the querying behaviour.

**Comment by DavidHepper** [comment]
It would be unsurprising if Accepted overrides Queried whereas Queried overrides Unreviewed, even if (unusually?) the query were raised _after_ the acceptance. This would explain the above behaviour.
Keeping track of the order of events would be whole heap more complex. A status priority system (if that's what it is is) can be coded much more simply than one depending on event time-stamps.

**Comment by kitenetter** [comment]
Another possibly related issue: I've just queried a record, and was only offered the option to send an email, which I did. The "email sent" popup appeared, but the email window was still showing at the time, and the egg-timer went on for quite a long time before returning me to the grid.

The record that I queried is still showing in the grid, with no query icon against it:

![image](https://user-images.githubusercontent.com/16039111/53529145-a747d280-3ae3-11e9-8a62-6dbd28ccadda.png)

However, there is a query icon in the right-hand details pane:

![image](https://user-images.githubusercontent.com/16039111/53529196-c47ca100-3ae3-11e9-8cfb-40945df14a90.png)

I then refreshed the verification page, and this supposedly queried record is still showing in the main grid (and still has no queried icon). I then filtered for queried records only, and the above record is not listed as a queried record.

So it appears that the email has been sent (or at least the comment to say that it has been sent has been triggered), but the record itself has not been marked as queried.

I must admit I'm finding that the verification page is currently being very slow to load and update, not sure if that has any bearing on this.

**Comment by kitenetter** [comment]
Another oddity in relation to querying a record. I had the grid set to show tick boxes. I highlighted an individual record and queried it (via a comment rather than an email). An error message briefly flashed up and there was something about "unauthorised" but it didn't display for long enough for me note it down. The grid then completely vanished:

![image](https://user-images.githubusercontent.com/16039111/53687511-457aa900-3d2d-11e9-84b2-3943d121a1b1.png)

It all seems back to normal after refreshing the page, and the above comment has been saved, although once again the record is not showing as queried.

**Comment by DavidHepper** [comment]
I was helping a verifier earlier today. We queried record 8839053, first by Email and then by Comment. Despite these actions, the record remained in the 'Not reviewed' grid and failed to appear when the standard filter was changed to 'Queried records'. To get it out of the way, we set it to Plausible and it was no longer shown under 'Not reviewed'.

**Comment by kitenetter** [comment]
The starting point for this issue was Matt's report of date mismatches - this is being picked up under #516 

The current issue now focuses on inconsistencies with queried records, which are failing to be given an icon in the grid, and failing to be removed from the default grid view. This leads to problems when applying bulk verification.

**Comment by MNSmith** [comment]
Can I "bump" this please.  The lack of queried records moving off the Verification grid is starting to make it difficult to manage the Asian Hornet Watch App verification page.  We have seen a flush of records in the last week or so, most of which are "Queried" so as to send an e-mail to the recorder, and it is starting to get very difficult to see which ones have yet to be checked and verified.

**Comment by kitenetter** [comment]
I agree that this is problematic, and both the 'old' and 'new' verification pages are retaining queried records in the grid.

**Comment by kitenetter** [comment]
@johnvanbreda thanks for this, the records do seem to be being removed from the grid upon querying. However, I'm fairly certain that a record I queried a short time ago, which disappeared from view, then re-appeared when I refreshed the page.

**Comment by johnvanbreda** [comment]
Hi @kitenetter - if you know the record ID I can look into it. I think the fundamental problem underlying this issue is now closed though.

**Comment by kitenetter** [comment]
@johnvanbreda fairly sure the record ID was 9720975, but it is no longer showing in the pending grid. Probably no need to investigate further, will check again if the same thing occurs.
