### ISSUE TITLE
BRC Open Access records not visible to verifier

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#498]
Some time ago we uploaded a set of records for Anthomyiid flies into the "Anthomyiidae Study Group" survey (id 491) within the "BRC Open Access" website (id 98). These records are visible within iRecord (e.g. via Explore - All records) but I cannot get them to display within the verification view for the recording scheme verifier (who is iRecord user "pbrighto").

The same issue applies to the other survey, "Ladybird_data" (id 456), in the BRC Open Access website - they do not appear in Helen Roy's verification view.

These records have all been imported as "already-verified", but even so I would expect them to be visible to the verifiers when filtering to see "All records".

**Comment by StephRorke** [comment]
@kitenetter I have had a look into this and am not 100% certain why the records are not available in the verification view either. The BRC_Data_Input user provides data for verification and the BRC Open Access website has an agreement with iRecord to provide data for verification. 
It is possible that the query to make the data available for the verification filter is blocking the records and that this setting is not accessible via the filter options available to us on the admin-edit page...
looking at the record for Phil's verification filter in the Filter table the website_id field is populated with 23 (iRecord) and the description for this field is in the database is: "Foreign key to the websites table. Optionally limits the filter to being available on this website." Perhaps by removing this reference we would make the BRC_Open_Database records visible. I don't have enough of an understanding of how the database is set up to be confident of this though.

**Comment by johnvanbreda** [comment]
It looks like Phil had set some flags on his records to block them for sharing for certain tasks (users.allow_share_for_... fields). Although he has recently enabled sharing for verification this hasn't changed the existing records. So, I've just launched a background task to do this over the next few hours.
