### ISSUE TITLE
Column-head filtering: site names and wildcards

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#499]
In the tables of records that we display, e.g. from the Explore pages, most of the column headings can be filtered using a wildcard to return all matching values. However, for the "Site name" column, if you use an asterisk the search fails, whereas if you don't use an asterisk the search gets carried out as if it was using wildcards.

This is inconsistent with the other text columns, and contradicts the tooltip instructions at the head of the column.

My preference would be for the "Site name" column to use wildcards in the same way as the other columns, but if this can't be done then can the tooltip text be updated.

**Comment by DavidHepper** [comment]
See also related anomaly:  "Range of record IDs not working in column header filter of Grid"
#472
