### ISSUE TITLE
Email alerts for non-native species

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#50]
Request originated in relation to wild boar records for non-native species tracking at SNH (see correspondence with Colin McLeod et al.).

Generalised requirement:
- System to send an auto-generated email to one or more specified email addresses every time a record is added to iRecord (and/or to other Indicia databases?) for one or more target species in one or more target regions (e.g. vice-counties). Email to include hyperlink to record on iRecord.

**Comment by johnvanbreda** [comment]
@kitenetter Isn't this already supported, e.g. via https://www.brc.ac.uk/irecord/species-alert-notifications?
