### ISSUE TITLE
Taxon in taxa table but unavailable in iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#501]
@sacrevert reports that the plant name "Glaux maritima" is not available in iRecord, although its linked vernacular "Sea-milkwort" is available.

Both names are in the Taxa table, with ids 187579 (Glaux maritima) and 187581 (Sea-milkwort).

I can see no reason within the Taxa table for one name to be available and the other not. 

In table Taxa_taxon_lists both names are linked to the UKSI master list, and the only difference I can see is that taxa.id 187579 (Glaux maritima) has two entries in Taxa_taxon_lists, and that there are some differences between these two:
- taxa_taxon_lists.id = 187579 (Glaux maritima): preferred - true; allow_data_entry = false
- taxa_taxon_lists.id = 187581 (Sea-milkwort): preferred - false; allow_data_entry = false
- taxa_taxon_lists.id = 300247 (Glaux maritima): preferred - false; allow_data_entry = true

I can't understand how the above three variations result in only the vernacular name being available in iRecord, but maybe there are other tables that I haven't looked at that also interact.

Neither the scientific nor the vernacular appear to be available in the iRecord app.

**Comment by johnvanbreda** [comment]
The data weren't quite as you'd listed in that 300247 was for taxon Sea-milkwort, not the scientific name. The main issue though was the allow_data_entry flag being false for the preferred name. I've reset it and it will take an hour or so to update in the search cache.
