### ISSUE TITLE
Unable to create download filter

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#502]
I've been trying to set up a download filter today:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=5950

It seems to save successfully when created, but does not appear in my list of filters from the download page. If I go back to the filter editing page I then get an error message:
```
The data did not load successfully. The reason given was: 
There was an SQL error: ERROR:  column "receive_for_" does not exist
LINE 3: WHERE "receive_for_" = 't'
              ^ - SELECT "to_website_id"
FROM index_websites_website_agreements
WHERE "receive_for_" = 't'
AND ("from_website_id" IN ('23'))
```

**Comment by johnvanbreda** [comment]
To get access to your download filters on the Download page, you need to belong to the Survey Downloader role. I've done that.
I've also a fix for the error message applied to the code, which will be applied to the server later.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda and apologies for forgetting the survey downloader role, in theory I'm aware of that!

**Comment by johnvanbreda** [comment]
No worries! Server now updated.
