### ISSUE TITLE
Verification page loading very slowly and sometimes failing to load

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#506]
Several verifiers have been in touch to say that the verification page is loading very slowly, and sometimes generates a timeout message. My own experience is that it has quite often been very slow to load in recent days, both for the page itself and then for the details in the right-hand pane, but for me it has always got there eventually.

**Comment by DavidRoy** [comment]
@johnvanbreda unless there is an obvious reason for this, is this an option for moving reports to ElasticSearch to improve performance.  As ever, verifiers are my priority

**Comment by DavidRoy** [comment]
Page still unacceptably slow to load, e.g.  for user dbarlow - verification role for vascular plants in north-east Yorkshire.

**Comment by johnvanbreda** [comment]
@DavidRoy for user dbarlow, the verification page is slow because their filtered dataset contains few records in the recent data (less than 1 page full) and most of them are quite old. Therefore the query optimiser, which is not capable of understanding this skewing of the dataset, gets the wrong plan. The solution is, at least for now, to provide several filters each covering a range of, say, 1 million records (filtered by ID). I think @kitenetter has done this before.

I agree about the notion of moving to ElasticSearch and I'm confident it will drastically improve performance. It will take a while to build the client side reporting tools for the new API though.

**Comment by johnvanbreda** [comment]
I should add that whilst testing this, I found the performance variable depending on server load. The building of summary occurrences for UKBMS seems to be a significant culprit which has already been raised with Gary.

**Comment by kitenetter** [comment]
@johnvanbreda last time we split up verification into chunks like this I did it on the basis of date rather than record ID, but presumably either option would work?

However, I'm struggling to find a way to identify a suitable time period for the chunking, do you know roughly what date range the remaining unverified records fall into?

**Comment by DavidHepper** [comment]
My verifiers have been seeing slow response times and timeouts recently. Even the Home page is really slow - especially discouraging for people new to iRecord. When the Verification page is also slow some of them decide to leave it for a few days, assuming it must be a glitch.

**Comment by kitenetter** [comment]
@johnvanbreda David Barlow's verification role is for plants in North-east Yorkshire. There are currently just over 2,000 unverified records. Most of the unverified ones are recent (post-2000) and fairly evenly scattered through the years up to the present. Then there are some between 1960s and 1990s.

I've split Dave's verification filter into a pre-2000 one and a post-2000 one. The pre-2000 one (121 records) loads very quickly, the post-2000 one (2,397 records) is still slow to load but does get there.

That doesn't square with your description above of there being few recent records.

However, I think the issue is now resolved for Dave Barlow, and of course it should get considerably better once we move to the elastic search verification page (note to @DavidHepper - details of this to follow very soon). Closing this issue.

P.S. We are still getting verification filters duplicated every time I edit one of them (#508).

**Comment by DavidHepper** [comment]
@johnvanbreda - Elastic Search (or something!) to improve the speed and reliability of the Verify grid would be very welcome. Today I'm seeing SQL timeouts for a simple filter: 'Not reviewed' for E. and W. Norfolk. There should only be a handful of records currently awaiting review.
(I don't think this issue #506 should be closed yet.)
