### ISSUE TITLE
Add an additional forum for verifiers

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#51]
Request from Wil Heeney (Longhorn Recording Scheme) for a verifiers' forum, where questions can be asked and advice shared about the verification process. Would need to be visible only to users with verifier permissions.

**Comment by kitenetter** [comment]
A few other verifiers have also expressed a view that a verification forum would be helpful, although I don't know how widely that view is shared. One verifier said that a forum would be useful and needn't be restricted to verifiers. On balance I would support having discussion open rather than closed, although it may be there are some topics that would benefit from a 'frank exchange of views' among verifiers themselves.

I suggest we create an open forum, and maybe revisit the idea of a closed one if verifiers feel it is needed.

**Comment by kitenetter** [comment]
I'm still going backwards and forwards in my own mind as to whether an open or closed forum would be best. Can I ask:
- Is a closed forum easy to set up, or would it require additional development?
- What is @DavidRoy's view?

**Comment by DavidRoy** [comment]
I think closed

**Comment by johnvanbreda** [comment]
A closed verification forum is now on iRecord. Available to admin, support providers and verifiers only.
