### ISSUE TITLE
Timeout error for LERC download

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#510]
I assume this is related to the other timeout issues we've had recently, but documenting it just in case it sheds any further light. Herts Records Centre reports:

"Trying to download some iRecord data. I'm getting the following error when I try and download all surveys, last changed date, start 13/02/2019, end 13/02/2019 - I'm using version 2 of the LERC data download."

`{"error":"There was an SQL error: ERROR:  canceling statement due to statement timeout - \n  SELECT  distinct on (o.id) o.id as \"occurrence_id\",\n'iBRC' || o.id as \"recordkey\",\no.external_key as \"external_key\",\nsnf.website_title || ' | ' || snf.survey_title || coalesce(' | ' || snf.group_title, '') as \"source\",\ncase when onf.sensitivity_precision is null then o.sample_id else null end as \"sample_id\",\ncttl.preferred_taxon as \"taxon\",\ncttl.default_common_name as \"common\",\ncttl.taxon_group as \"taxon_group\",\ncttl.kingdom_taxon as \"kingdom\",\ncttl.order_taxon as \"order\",\ncttl.family_taxon as \"family\",\no.taxa_taxon_list_external_key as \"taxonversionkey\",\no.taxa_taxon_list_id as \"taxa_taxon_list_id\",\ncase when onf.sensitivity_precision is null and onf.privacy_precision is null then o.location_name else 'Sensitive. Lat long is approximate.' end as \"location_name\",\nsnf.public_entered_sref as \"entered_sref\",\nsubstring(st_astext(st_transform(st_centroid(o.public_geom), 4326)) from E'POINT\\\\(.+ (.+)\\\\)') as \"lat\",\nsubstring(st_astext(st_transform(st_centroid(o.public_geom), 4326)) from E'POINT\\\\((.+) ') as \"long\",\ncase snf.entered_sref_system when '4326' then 'WGS84' when '27700' then 'OSGB36' else upper(snf.entered_sref_system) end as \"projection\",\nget_sref_precision(snf.public_entered_sref, snf.entered_sref_system, snf.attr_sref_precision) as \"precision\",\nonf.output_sref as \"output_sref\",\ncase onf.output_sref_system when '4326' then 'WGS84' when '27700' then 'OSGB36' else upper(onf.output_sref_system) end as \"output_sref_projection\",\nsnf.attr_biotope as \"attr_biotope\",\n(SELECT string_agg(vc.code, '; ')         FROM locations vc         WHERE vc.location_type_id=15         AND vc.name NOT LIKE '%+%'         AND vc.id = ANY(o.location_ids)) as \"vicecounty_number\",\n(SELECT string_agg(vc.name, '; ')         FROM locations vc         WHERE vc.location_type_id=15         AND vc.name NOT LIKE '%+%'         AND vc.id = ANY(o.location_ids)) as \"vicecounty\",\nnull as date,\no.date_start as \"date_start\",\no.date_end as \"date_end\",\no.date_type as \"date_type\",\nsnf.attr_sample_method as \"attr_sample_method\",\nrtrim(snf.recorders, ', ') as \"recorder\",\nCASE WHEN onf.attr_det_full_name IS NULL THEN         CASE WHEN onf.attr_det_last_name IS NULL THEN NULL ELSE onf.attr_det_last_name || COALESCE(', ' || onf.attr_det_first_name, '') END       ELSE onf.attr_det_full_name END as \"determiner\",\nCASE o.certainty WHEN 'C' THEN 'Certain' WHEN 'L' THEN 'Likely' WHEN 'U' THEN 'Uncertain' END as \"certainty\",\nonf.attr_sex as \"attr_sex\",\nonf.attr_stage as \"attr_stage\",\nonf.attr_sex_stage_count as \"attr_sex_stage_count\",\nupper(cast (o.zero_abundance as character)) as \"zeroabundance\",\nonf.comment as \"record_comment\",\nsnf.comment as \"sample_comment\",\ncase when onf.media is null then null else 'http:\/\/warehouse1.indicia.org.uk\/upload\/' || replace(onf.media, ',', ', http:\/\/warehouse1.indicia.org.uk\/upload\/') end as \"images\",\no.created_on as \"input_date\",\no.updated_on as \"last_edit_date\",\nCASE o.record_status         WHEN 'V' THEN 'Accepted'         WHEN 'C' THEN 'Unconfirmed'         WHEN 'R' THEN 'Rejected'         WHEN 'I' THEN 'Input still in progress'         WHEN 'D' THEN 'Queried'         WHEN 'S' THEN 'Awaiting check'         ELSE o.record_status         END as \"record_status\",\nCASE o.record_status         WHEN 'V' THEN           CASE o.record_substatus WHEN 1 THEN 'correct' WHEN 2 THEN 'Considered correct' ELSE NULL END         WHEN 'C' THEN           CASE o.record_substatus WHEN 3 THEN 'Plausible' ELSE 'Not reviewed' END         WHEN 'R' THEN           CASE o.record_substatus WHEN 4 THEN 'Unable to verify' WHEN 5 THEN 'Incorrect' ELSE NULL END         ELSE NULL         END as \"record_substatus\",\ncase o.query when 'A' then 'Answered' when 'Q' then 'Queried' end as \"query\",\nonf.verifier as \"verifier\",\no.verified_on as \"verified_on\",\nonf.licence_code as \"licence_code\",\nCASE WHEN o.data_cleaner_result='t' THEN 'pass' WHEN not o.verification_checks_enabled THEN 'checks disabled' WHEN o.data_cleaner_result IS NULL THEN 'pending' ELSE onf.data_cleaner_info END as \"autochecks\",\nCASE CAST(o.created_by_id AS character varying) WHEN '#currentUser#' THEN true ELSE false END as \"belongs_to_user\", \nattr_biotope, \nattr_det_full_name, \nattr_sex, \nattr_stage, \nattr_sex_stage_count\n  FROM cache_occurrences_functional o\n  JOIN cache_occurrences_nonfunctional onf on onf.id=o.id\n  JOIN cache_samples_nonfunctional snf on snf.id=o.sample_id\n  JOIN cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id\n  JOIN websites w on w.id=o.website_id and w.deleted=false\n  JOIN system sys ON sys.id=1\n  \n  WHERE o.training=false AND (o.website_id in (23) OR o.created_by_id=1 OR o.blocked_sharing_tasks IS NULL OR NOT o.blocked_sharing_tasks @> ARRAY['data_flow'::character ])\n AND o.website_id in (43,13,97,33,29,44,87,58,79,12,24,14,17,6,8,25,11,3,30,5,27,34,16,32,42,51,49,63,65,73,9,71,10,23,69,98)\n  \n  AND o.release_status='R'\nAND o.confidential='f'\nAND ('2019-02-13'='Click here' OR o.updated_on >= '2019-02-13'::timestamp)\nAND ('2019-02-13'='Click here' OR (o.updated_on <= '2019-02-13'::timestamp OR (length('2019-02-13')<=10 AND o.updated_on < cast('2019-02-13' as date) + '1 day'::interval)))\nAND o.location_ids && ARRAY[1451]\n ORDER BY o.id DESC LIMIT 30001","code":44,"file":"D:\\websites\\warehouse\\system\\libraries\\drivers\\Database\\Pgsql.php","line":342,"trace":[]}`

**Comment by johnvanbreda** [comment]
@kitenetter did you get a chance to look into the new ElasticSearch based download? If the outputs are OK, then I think this is the way forward.

**Comment by kitenetter** [comment]
@johnvanbreda so far I have been unable to generate a download from the test page. I've been trying to add a filter (e.g. for VC Berkshire, or genus Bombylius) and I get the 'loading' image but no file.

Do the filter terms need to be in double-quotes?

![image](https://user-images.githubusercontent.com/16039111/54382914-d7b57200-4688-11e9-8dce-c9a7c67bbf9a.png)

**Comment by johnvanbreda** [comment]
I've moved this page to https://www.brc.ac.uk/irecord/national-trust/download and added a new page at https://www.brc.ac.uk/irecord/elastic/download for full data-flow access. To do a VC filter, just type the VC name in the limit to location field. You can either do a free text search for Bombylius, or a more accurate search for taxon.genus:Bombylius.

**Comment by DavidRoy** [comment]
This is a great improvement.  I presume the next steps are to put these downloads under Drupal permissions (e.g. LERC Downloads only for those with the right permission, filtered to relevant boundary)?

I managed to download the whole NT dataset of ~490k records with no problem.   Also downloaded an Oxfordshire VC file of ~375k records.

A few observations on the downloaded files:
1. In opening the .csv in Excel, it gives a popup box saying 'The file format and extension of 'xxx.csv' don't match.  The file could be corrupted or unsafe. Unless you trust its source, don't open it.  Do you want to open it anyway?'.  If you click on yes, you then get a popup saying 'Excel has detected that 'xxx.csv' is a SYLK file, but cannot load it.  Either the file has errors or it is not a SYLK file format.  Click OK to try to open the file in a different format.'  If you click ok the file still opens.
2. The download file had an ID field and a RecordKey field but the latter was all populated with '-'
3. Coordinate uncertainty (m) and Record status fields also all populated with '-'

**Comment by DavidHepper** [comment]
Re. the SYLK mismatch, are you running an old version of Excel? It can happen when "ID" is the first column header and Excel, unlike LibreOffice, is trying to be too clever. If this is changed to "Record ID" it won't happen.

**Comment by johnvanbreda** [comment]
ID renamed to Record ID to fix SLYK errors.

**Comment by kitenetter** [comment]
I think the issues discussed here around column naming are picked up in #632 - closing.
