### ISSUE TITLE
Help needed with RHS survey form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#511]
Hi @BirenRathod, I'm setting up a recording form for the Royal Horticultural Society's slug survey. This links to survey ID 542 in the warehouse. The first draft of the form is at:
https://www.brc.ac.uk/irecord/rhs-cellar-slugs

This has become less urgent than I feared, as I've managed to get things to the point where the form is functional, but there are four areas for which I could do with some help:

1. The survey is using just three slug species taken from the UKSI, but they wish to use English names that are different to the UKSI. Do we have any way of allowing custom English names for data entry while still linking the records to the UKSI for reporting?

2. Related to the above, since there are only three species involved, we could use a static grid showing all three species, rather than a extendable grid with auto-lookup on each row. Not sure which of these options would be best but would be good to see both alternatives.

3. I couldn't find a way of controlling the width of the columns in the species grid - I completed the percentage settings but they didn't seem to do anything. The form is workable as it stands, but would benefit from a little tidying up.

4. The third tab of the form, "Your garden", would probably benefit from being in two columns.

**Comment by BirenRathod** [comment]
@kitenetter 

Here are my comment.

1. The only way you could do this by adding another species list with external key value of storing NBN tvk in it.
2. There is a select option but that is not possible with grid feature. 
3. It is bit tricky to implement columns width when there are many columns to display all to gather.
4. how are you going to manage all those fields in two tabs. probably it is good to keep it as it is.

**Comment by kitenetter** [comment]
Have made some further adjustments, form now working fine. Closing.
