### ISSUE TITLE
Very large number of "last updated" resets in February

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#516]
Something in mid-February seems to have triggered a mass update of records, so that a large proportion of the iRecord dataset is now showing 13 Feb 2019 as the date last updated. I'd noticed this when verifying but wasn't sure how widespread the issue was, but judging from Ian Carle's information below it has affected a lot of records.

The main impact of this is likely to be on records centres and others who wish to download all the records changed since their previous download.

I'm not sure what the solution is, but it's probably worth trying to track down why this has happened to avoid it in future.

> The download facility seems to be working better now, although I still have a problem - I'm unable to download all of the data for 13/02/2019 as unbelievably more than 30,000 records have a last changed date on that day. 
> 
> Of the 30,000 that downloaded:
> 
> 17,187 - last changed 13/02/2019  18:31:49
> 
>  4,155  - last changed 13/02/2019  19:31:14
> 
>  8,624 - last changed 13/02/2019  16:20:10
> 
> These changes are across multiple sources eg 16:20:10:
> 
> BWARS | Advanced Single Species Surveys
> BWARS | Single Species Surveys
> CEDaR Recording | Cuckoo
> Consultants Portal | Animals
> Consultants Portal | Bats
> Hertfordshire Flora Group | Flora recording
> iRecord | Bryophytes (BBS)
> iRecord | Incidental ladybird
> iRecord | iRecord App
> iRecord | iRecord beetles
> iRecord | iRecord Butterflies
> iRecord | iRecord Dragonflies
> iRecord | iRecord Dragonflies | British Dragonfly Society recording
> iRecord | iRecord FSC Cuckoos | FSC - Listen Out For Cuckoos
> iRecord | iRecord general data
> iRecord | iRecord general data | Boxmoor Trust monitoring group
> iRecord | iRecord general data | Longhorn Beetle Recording Scheme
> iRecord | iRecord general data | Rothamsted Insect Survey suction trap data of migrating insects at 12.2 m
> iRecord | iRecord general data | Soldierflies and Allies Recording Scheme
> iRecord | iRecord Grasshoppers
> iRecord | iRecord Import
> iRecord | iRecord Ladybirds
> iRecord | iRecord mammals
> iRecord | Rinse
> iRecord | Vascular plants BSBI
> Mammal Society | Mammal Atlas
> Moth Night | Moth Night 2017
> Moth Night | Moth Night 2018
> National Plant Monitoring Scheme | Extra species records
> National Plant Monitoring Scheme | Indicator survey
> National Plant Monitoring Scheme | Wildflower survey
> Nature Locator | Plant Tracker
> NNSS | Non RISC
> NNSS | RISC Crayfish
> NNSS | RISC Het
> UKBMS | UKBMS Transects
> UKBMS | UKBMS WCBS-BBS
> UKBMS | UKBMS WCBS-BC
> It looks to me as if a system change on that day is making it impossible for me to download the data - I don't believe that all of a sudden at 16:20 on the 13th all of those records were changed by individuals. There are so many surveys involved that I don't think it's reasonable for us to be expected to try and download survey by survey for data with a date changed on that one day - as the number of records is incomplete we won't know if there are other surveys affected by this that don't happen to appear in the 30,001 that did download.
> 
> The download doesn't fail it just churns out a csv with 30,001 records in so unless you're on the ball you might not realise you may be missing records. 
>

**Comment by johnvanbreda** [comment]
Pretty sure this occurred as a result of re-scanning all the records against the new NUTS layers. I'll reset the updated on values to the one in the actual occurrence records.

**Comment by DavidHepper** [comment]
That would be welcome. While looking at 'last modified' dates, could you please also check the **Log date** on the grid, as this appears always to show the 'Submitted on' date rather than the date associated with the **Comment ID** shown to the left.
Example:  Comment ID: 10970409 for Record ID: 8642732 currently shows Log date 2018-11-25 16:47:47 instead of the date on which the record was Accepted.

**Comment by johnvanbreda** [comment]
Hi @DavidHepper I'm closing this one as the original issue is done now. Please can you open a request for the comments log fix as another issue as it's not really related.
