### ISSUE TITLE
Verification getting recorded twice

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#517]
I suspect this was a temporary glitch and as far as I know it hasn't affected many records or users, but documenting it in case it's informative.

A user reported receiving email notifications that contained the same records twice, with the same verification notice attached to each. At first I thought this might be a problem with the notification system, but it appears to derive from the verification flag itself having become duplicated.

Example records:
- https://www.brc.ac.uk/irecord/record-details?occurrence_id=9231203
- https://www.brc.ac.uk/irecord/record-details?occurrence_id=6988642

Maybe the slow running last week caused verifiers to repeatedly click on the buttons?

No action suggested unless this turns out to be an ongoing problem.

**Comment by DavidHepper** [comment]
A recorder has told me today of receiving a second notification of acceptance of a specific record but she may not be able to confirm the record ID. Would this be useful if we could dig further?

**Comment by kitenetter** [comment]
I've had another report of duplicated notifications and duplicated, in connection with records entered via the SewBrec system. Example record ID:
- 9656671

![image](https://user-images.githubusercontent.com/16039111/54911549-a6d60800-4ee6-11e9-8c86-8a086dc9c29b.png)

This is a new problem, at least in recent weeks.

**Comment by johnvanbreda** [comment]
@kitenetter is any of this still an issues or can it be closed?

**Comment by kitenetter** [comment]
@johnvanbreda I'm not aware of recent instances of this issue, although there are possibly similarities with #865 and #852 

Closing this one.
