### ISSUE TITLE
Summary Report of unverified records by vice-county, please

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#519]
It would be really useful to know the queue length of unverified / queried records by VC for a selected taxon. Currently I have to define a filter in Verify for each VC and scroll down to see the count below the grid.

This is a enhancement request, not a bug report, and could perhaps be a useful test of Elastic Search.

**Comment by johnvanbreda** [comment]
Indeed, a very useful test! 
Here's my first go at this:
https://www.brc.ac.uk/irecord/elastic/verification/stats/counts_by_vc

Note that this is very much experimental!

**Comment by DavidHepper** [comment]
That was quick! And it works quickly, too. 
A few observations, operating as myself in context 'Dragonflies; Hepper, David':
- If serious caching is involved (is it?) so that the numbers may be a little behind the times then this could be declared above or below the table.
- The 'East Sussex' total 'Pending' is 3115 whereas from the conventional grid 'Not reviewed' is 3113. Near enough.
- The 'West Sussex' total 'Pending' is 2314 whereas from the conventional grid 'Not reviewed' is 2310. 
- There's an extra non-VC at the top of the list: 'Sussex' with 5404. This appears to be the only one. From the conventional grid, E.&W. Sussex together shows 5400. But why is 'Sussex' present in the report when 'Kent' (for example) is only represented by 'East Kent' and 'West Kent' separately?
- Is it intentional not even to list VCs with zero records pending? e.g. 'East Norfolk' is currently absent, presumably for this reason.
- Below the table I see the text 'No hits' and buttons Previous and Next. Neither button does anything.

**Comment by DavidHepper** [comment]
I wonder whether differences can be explained by double-counting of border-straddling records, assigned to more than one VC? If so, I'm unconcerned but it would be reassuring to know one way or the other.

**Comment by johnvanbreda** [comment]
Sussex is a "special" VC boundary we added when iRecord did not support multi-boundary filters, so verifiers could work across Sussex. There is a similar one for Yorkshire but no others. They are in the process of being removed as they are no longer needed. It's quite likely that the Sussex boundary is slightly different to the 2 components since the true VC boundaries have had updates since the combined version was created. 

The unnecessary "No Hits" etc has been fixed in more recent code updates.

Note to self - ID:258120 is an example record for a now expired "damselflies" taxon. This is probably an explanation for the small number of differences. I need to look at why the ES indexing process is less tolerant of expired/dodgy taxon names and fix that.

**Comment by DavidHepper** [comment]
Thank you for your work on this. It really is most useful to us in offering assistance to verifiers who might be struggling. It also proved its worth in identifying a case where a VC had inadvertently lost its verifier!
Let us continue the issue of assigning border-straddling records to VCs in #679 rather than here.
Is this summary report now sufficiently robust to go public?

**Comment by kitenetter** [comment]
@johnvanbreda will this page only be visible to verifiers? I'm guessing so, as it only displays information related to the verification filter/s applicable to the logged-in user.

In which case what I'd ideally like to do is to have some new menu items under the heading "Resources for verifiers". However, our top-level menu items are already quite extensive, so I wonder if "Resources for verifiers" is best placed as a sub-menu underneath "Verify" and/or "Verify - new" - probably the latter.

And then there will be further sub-menu links under "Resources for verifiers", including:
- this verifiers' report 
- some specific verification Help pages [currently in progress]
- guidance for verifiers on csv upload [to be developed soon]

If you are logged in as a normal (non-verifier) iRecord user, if you try to go to https://www.brc.ac.uk/irecord/elastic/verification/stats/counts_by_vc you get "Access denied" and asked to log in, even though you are already logged in.

This verifiers' report shows records per vice-county, which is useful for national schemes but not so much for county verifiers (although it does give an idea of how many records are on the borders with other VCs). As a further enhancement request it would be good to have some other options such as verification per taxon group, or per taxon, or per year, or per verifier (within your own verification filter settings). But all those fall into the 'nice-to-have' as far as I'm concerned, and I'm not aware of a wider demand for them.

**Comment by kitenetter** [comment]
I'm currently in discussion with Mammal Society verifiers and this has produced some questions around the verifiers' summary, and why the numbers displayed don't always match the numbers that verifiers have on their main grid.

For example, the mammal verifier for Essex has 210 pending records for South Essex and 45 pending records for North Essex in his verification grid (both old and new versions), while the 'counts_by_vc' report shows 160 pending records for South Essex and 12 pending records for North Essex.

I can imagine that there might be some differences in the filtering for the 'counts_by_vc' report (e.g. I don't know how/if we are filtering on the various website agreements for that report), does that explain it?

**Comment by johnvanbreda** [comment]
The Mammal verifier for Essex has the geographic limit set to the boundary for Essex Wildlife Trust biological records centre. This boundary is quite different to the combination of North and South Essex VCs, especially around the edges of London where the old county of Essex has been partly subsumed into the London boroughs. So if he filters on North or South Essex, it's actually the intersection of the VC and the LRC boundary that gets applied. Therefore the data aren't comparable.

I think the menu restructure should probably become a new issue so this can be closed?

**Comment by kitenetter** [comment]
@kitenetter to review this

**Comment by kitenetter** [comment]
I've not yet got on to this, moving to December milestone.

**Comment by kitenetter** [comment]
Remaining items added as new issues - closing this one.
