### ISSUE TITLE
Admin rights for Activities

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#52]
A problem has arisen with the "East Lothian Moths" activity. It was created by Mark Cubitt (user cubitmg), but he sent himself an invite to join the group (so that he could test the invitation process), and when he accepted his own invitation he discovered that he was no longer administrator for the activity, and there are no other admins either, so it's been orphaned.

Specific issue: is it possible to reinstate Mark as the admin for this particular activity

General issue: is there a way that users with admin rights on iRecord can be given access to all activity editing pages, in order to sort out any future issues that may arise, and to provide guidance to users where needed?

**Comment by johnvanbreda** [comment]
Site admins do already have access to edit the group pages although the button for editing is only generated for the admins of the group. Therefore there is a quick way of solving this. First hover over the star icon (or leave icon) for a group you want to edit and note the ID from the URL. Now edit a different group you have rights to and swap the ID in the URL. There is a permission called iform group admin which you will need in order to be able to do this.
I've added Mark back as admin using this method.

**Comment by kitenetter** [comment]
Thanks John, that should be fine.

**Comment by kitenetter** [comment]
John, I have assigned the "IForm groups admin" permission to the "Admin user" role, and have logged on as "iRecord support" (which has the "Admin user" role), but I still can't gain access to edit the settings for other user's activites:
"You are trying to edit a group you don't have admin rights to"

Have I missed a step somewhere?

**Comment by BirenRathod** [comment]
By enabling or adding a core admin role doesn't solve to gain access to edit the settings for other user's activities too. 
The form restrict to access other people activities for "iForm groups admin"  as Martin suggested. may require to change the code.

**Comment by kitenetter** [comment]
@johnvanbreda this issue has arisen again - I need the "iRecord support" user account to be able to add a new admin user to an existing activity for which "iRecord support" is not an admin. Is there a fix for this, or do I need to ask you to make the change for me?

**Comment by Gary-van-Breda** [comment]
I have lodged a bugfix to the edit form - there was a case issue in the permission name.
I have also created a role "activities admin" which should be given to the relevant users who will be allowed to edit the groups created by other users but which thjey have not been assigned as an administrator for. I have given this to "iRecord support".

Next stage is to extend the groups_list.xml report to take a CMS permission flag to allow is to flag the icon as visible.

**Comment by Gary-van-Breda** [comment]
John has deployed the edit form bugfix, so the workaround mentioned by John on 17-Jun-2016 now works.

**Comment by kitenetter** [comment]
Today I needed to edit an Activity that has been set up as part of Natural England's organisation. There are two activites on this page - for one I am an admin and can edit, but for the other ("NEFU Surveys 2017") I have no editing rights:
https://www.brc.ac.uk/irecord/centre-activities/list?dynamic-from_group_id=979

I thought we had set things up so that the "iRecord support" account had editing rights over all activities? Do things work differently for activities that are set up under an organisation?

**Comment by johnvanbreda** [comment]
@kitenetter, has this been fixed? I just masqueraded as iRecord support and was able to edit the NEFU Surveys 2017 activity.

**Comment by kitenetter** [comment]
@johnvanbreda it's been fixed manually by the NE admin adding the "iRecord support" account to the activity, but not fixed in the general sense.

**Comment by kitenetter** [comment]
As far as I can tell the iRecord support account has edit rights over all 'normal' activities, but not over centres and activities created under the organisation hierarchy. Having editing rights for those as well would be useful.

**Comment by kitenetter** [comment]
Admin editing now available for all activities as far as I can see - closing.
