### ISSUE TITLE
Verify: filter by 'Where > records in Map Reference' includes some records in adjacent squares

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#521]
Steps to reproduce:
- Reset the filter.
- Set a filter on **Where > records in map reference** and enter any grid reference. The correct square is shown on the map.
- The grid includes records in that square plus any records with _adjacent_ (including diagonal) references but only where the record has an Output grid reference of the same precision.

Example 1: filtering to SU85 finds records with exact ref. SU94, SU95, SU96, etc.
Example 2: filtering to SU8151 finds records with exact ref. SU8052, etc.

This looks to me like a '**>**' vs. '**>=**' logic error.

**Comment by kitenetter** [comment]
Still an issue but more recently documented under #1570 - closing this one.
