### ISSUE TITLE
Verify: the 'Log date' doesn't show the expected log event date

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#522]
In the Log tab of the grid, the **Log date** column appears always to show the 'Submitted on' date rather than the date associated with the Comment ID shown to the left.
_Example:_ Comment ID 10970409 for Record ID 8642732 currently shows Log date 2018-11-25 16:47:47 instead of the date on which the record was Accepted.

( Moved to a new issue from #516 )

**Comment by kitenetter** [comment]
The log tab is not currently in use, so closing this for now.
