### ISSUE TITLE
Implement photo licence handling

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#526]
This is needed in order to import photos from iNaturalist, but we also wish to implement CC licensing for photos within iRecord more generally.

**Actions needed for iNaturalist import (if not already available)**
- Ability to store photo licence in a custom attribute (rather than into the caption as was done in 2018)
- Ensure this licence is displayed wherever the photo is displayed

**Actions for iRecord generally**
In addition to the above:
- Allow licence to be set for incoming photos (either on a per-photo level or as a default in the user account)
- Provide option for users to retrospectively apply licences to photos previously uploaded to iRecord
- Add photo licence attribute to the standard CSV download reports

**Comment by johnvanbreda** [comment]
These tasks are done:
**Actions needed for iNaturalist import (if not already available)**

* Ability to store photo licence in a custom attribute (rather than into the caption as was done in 2018)
* Ensure this licence is displayed wherever the photo is displayed

**Comment by kitenetter** [comment]
Thanks - I'll close this and move the other tasks into a more general iRecord issue.
