### ISSUE TITLE
Verifier unable to save filter

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#529]
Reported as follows:

> Saving Filters in Verify mode does not work. Very occasionally I do get a pop-up box saying Filter saved, but the new name never appears in the droplist of Filters (so I can't use it). It is awkward to have to re-define every filter, every time I need to use one. Mistakes will get introduced. Coupled with system slowness, it is tedious. Delete filter works.

I guess this is best resolved by adding filtering functions to the new verification page rather than spending time on the old?

**Comment by DavidHepper** [comment]
I've only had a problem saving filters when trying to save an existing saved filter under a new name.
