### ISSUE TITLE
Auto-redirect to WWW subdomain

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#53]
[www.brc.ac.uk/irecord](http://www.brc.ac.uk/irecord) works fine, but entering [brc.ac.uk/irecord](http://brc.ac.uk/irecord) gives _Gateway Timeout: can't connect to remote host_. It should support both cases.

**Comment by kitenetter** [comment]
David has asked Biren to resolve this one.

**Comment by BirenRathod** [comment]
This has resolved now.

**Comment by kazlauskis** [comment]
Thanks, it works fine, though in my opinion it is better to rewrite the URL so that in both links the user sees **www.brc.ac.uk/irecord**  and not **brc.ac.uk/irecord**

**Comment by BirenRathod** [comment]
Rewrite URL won't work because we don't host the website, so we don't have a complete control. it is not prominent as once logged in it will change to the original one.
