### ISSUE TITLE
Feedback on new verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#530]
From verifier Barry Warrington:

> On my usual page, there is nothing to verify but on the new page, there’s quite a few! Is there any reason these are on one but not the other?

I've had some similar discrepancies on my page.

**Comment by johnvanbreda** [comment]
I looked at Barry's page but he seems to have verified them so it's hard for me to spot examples to look into. Record IDs which appear on the new page but not the old would be very useful.

One reason may be that the way that taxonomy is calculated may be different - especially for records which are not on UKSI so do not have a built in hierarchy in the list. This may be an improvement!

**Comment by kitenetter** [comment]
Barry also reports:

> Also, on my tablet, I can't clear the records which have no photos ie Steve Mathers record but I can on my desktop.

**Comment by kitenetter** [comment]
I'm currently looking at my verification filter for "Diptera: Stratiomyidae". On the old verification page it shows 19 records, on the new it shows 86 records. Record id examples for the missing records:
- 4847862 - this originates from a csv file that was imported into the RSPB's survey
- 8772105 - one of several from NatureSpot
- 3022774 - one of many from a recorder's csv import
- 568647 - another of many from a recorder's csv import

**Comment by johnvanbreda** [comment]
Looking through many of the records in your new page that aren't in the old page, the answer seems to be that they are pointing to names that are now redundant and no longer in UKSI. We preserved the name (so as to not lose the data) but flag it as not for data entry - they are parentless but the new Elasticsearch code seems to tolerate this better than the old code.

**Comment by kitenetter** [comment]
In that case is there any way of preventing the csv import process from linking valid current names to redundant versions of the same names?

**Comment by kitenetter** [comment]
I'm sure you're aware of this, but the new page does not yet show the "Identified By" attribute. Also, having redetermined a record on the old page, the redetermination has now updated itself for the species name on the new page, but the comment attached to the redetermination is not displaying (this example is record id 9665737).

**Comment by kitenetter** [comment]
If you verify all the records on a single page, that page empties, but there doesn't seem to be any way of getting on to the second page, excpet by refreshing the whole web page. Would be good if the "Next" button worked for this situation.

**Comment by kitenetter** [comment]
Would be really helpful to have the "Redet" button added to this page.

**Comment by kitenetter** [comment]
If you zoom the map out a long way you get an error message "Elastic search failed".

**Comment by MNSmith** [comment]
So far the page seems to be working well, and I will come back to Martin directly with a list of more detailed thoughts and comments in the next week.  I'm just using this thread for little "one off" I have spotted.

Map:  Not retaining settings if you go "in and out" of the page.  Heat maps are nice but not what I want to see for record verification in the first instance.  However, if I change the setting from the default "Heat Map" to "Current Page of Data", this setting in not retained if I "move away" from the page by looking at something like the records shown my checking recorder experience.  Whan I go back to the main page I one again see "Heat Map" turned on.

Same applies to Map options - does not retain choice selected and reverts to default.  Should retain user selections.

**Comment by kitenetter** [comment]
I'm sure you're aware already, but there are some attributes missing from the record details pane:
- Taxon name as originally entered by recorder
- Certainty
- Quantity
- Sex
- Stage

Also, I think I would prefer it if the right-hand pane was a floating one that moved down the page as you scroll down through the list of records - it's not easy to cross-check the full details for records at the bottom of the grid.

**Comment by kitenetter** [comment]
I think all the above issues have either been fixed or transferred to the individual prioritised 'elasticsearch verification' issues. Closing.

**Comment by MNSmith** [comment]
**Previous & Next Buttons**

> If you verify all the records on a single page, that page empties, but there doesn't seem to be any way of getting on to the second page, excpet by refreshing the whole web page. Would be good if the "Next" button worked for this situation.<

I'm finding a similar problem.  If you clear a grid of records selected by typing a name in the species search box the "previous" and "next" button do not function at all.

**Comment by MNSmith** [comment]
**Record Details Pane**

Overall this page is working well and is much quicker than the existing grid.  If this way we are going with iRecord, could I once again ask if we could have some consistency in the way the details are displayed and the various field names used as they seem to vary greatly between different sources.  

Beyond the basic record details of "what, where, when who" there are a lot of other fields being displayed on records and it seems to me that this new page has added even more, adding even more clutter to the page.  I'm finding the addition of Vice County and LRC Boundary particularly confusing as they are right next to Location.  As a verifier, I don't really need to know the date and time the record was entered and then last updated or the Taxonomy of a record.  A fixed, standard basic layout allows for much faster processing of records.  I appreciate that certain Schemes may want to see particular specific details on records, but these "extras" should be displayed in a separate frame.

Ideally, I would like to see a "standard" record details pane that displayed the basics needed for verification. 

Record Number, Record Status and Passed checks should form a 1 line header, ideally in a slightly larger / bold font, followed by:

Accepted Name.
Common Name
Location
OS Grid Ref  - if this has to be generated from a calculated grid ref then so be it, no Lat / Long displayed in this section please.
Date of record
Recorded by
Identified by
Source (Dataset)

**Comment by MNSmith** [comment]
**Previous and Next Buttons**

Previous / Next buttons only a not sufficient.  We need the facility to jump forwars orbackwards across multiple pages as we have at present on the old grid.  When you have several 100 records on a grid it takes a long time loading 30 records at a time to get to the other end of the list.

**Comment by MNSmith** [comment]
**Verification Icons**

Verification icons - these should be consistent with current usage and / or consistent across the system.  We regularly describe records verified as "Accepted - Correct" as those with "Two green ticks".  If we do eventually move to these new icons then this needs to have the colours reversed to keep it as displaying two green ticks, not 2 white ones.

**Comment by MNSmith** [comment]
**Column headers**

Titles and terminology -  these should be consistent with current usage and / or consistent across the system.  Examples: Site Name or Location, Map Reference or Output Map reference, Species or Accepted name

**Comment by MNSmith** [comment]
**Verification Grid columns**

Main grid needs to display location name.
Main grid ideally should display "Identified by" name

Ideally, the grid should allow uses to select / order fields displayed in the grid..  Preferred order of grid for me would be:

ID - Source - Species - SITE NAME - OS Map Ref - Recorded by - IDENTIFIED By - Date - Media.

**Comment by MNSmith** [comment]
**Verification Grid Columns #2**

"Checks".  As this field is non searchable and also replicated in the "Details" pane of the record, remove it from the grid to save space?

"ID Field" - as left justified, reduce current column width to save space on grid

"Source" - as left justified, reduce current column width to save space on grid as only code numbers are currently displayed.  Allow text searches in this field

**Comment by MNSmith** [comment]
**Experience Tab # 1**

"Experience Tab"  The various Record totals need to be right justified, currently they are causing the various coloured bars to be offset if there are 100s and 10s and <10 records listed in different catergories, which is confusing to the eye.

**Comment by MNSmith** [comment]
**Experience Tab # 2**

"Experience tab"  Clicking on any of the numbers to view records displays records in a refreshed screen.  When going "back" to the Verification grid all filters previously entered are cleared and you have to refilter again.  Open records in a separate Window for this?

**Comment by MNSmith** [comment]
**Verification Grid - Action Buttons**

Fixed Action buttons.  At present the Action buttons are contained within the scrolling frame of the grid, which means if I scroll down through the records ticking selection boxes and the like, I then have to scroll all the way back up to the top to carry out an action.  Can we have these buttons fixed in place please.

**Comment by MNSmith** [comment]
**Verification Grid - Column Headers and search fields.**

Fixed column header search boxes.  At present the column headers and search boxes are contained within the scrolling frame of the grid, which means if I scroll down through the records ticking selection boxes and the like, I then have to scroll all the way back up to the top to carry out an action.  Can we have these buttons fixed in place please.

**Comment by MNSmith** [comment]
**E-mail recorder function**

Can we have a function to e-mail a recorder please, separate from the Query function.
