### ISSUE TITLE
Recording form losing its formatting

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#532]
The RHS cellar slug form is here:
https://www.brc.ac.uk/irecord/rhs-cellar-slugs

It was working fine last time I looked, but today it has lost its tabbed structure, the map has disappeared, and the species grid has vanished.

As far as I'm aware the only recent change I have made is to link it to the new "Project-specific forms" menu.

**Comment by BirenRathod** [comment]
@kitenetter 

@johnvanbreda has just implemented the code and resolved it. This has affected iRecord forms too.

**Comment by johnvanbreda** [comment]
Thanks for spotting that @BirenRathod - it was about 2 seconds ago!
Patched iRecord, will deploy update properly later.
