### ISSUE TITLE
PoMS FIT Count form request

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#533]
The pollinator scheme FIT Count uses this form:
https://www.brc.ac.uk/irecord/poms-fit-count-form?group_id=1074&implicit=

For sample attribute "Target flower species" (ID 1050) there is a termlist that consists of plant names. Depending which name you choose, the form has been coded to open up an additional text box for further details. For example, if you choose "Thistle" the text box appears so that you can add the exact species of thistle, if you know it:

![image](https://user-images.githubusercontent.com/16039111/55183827-9a70da00-5188-11e9-9e6a-75d243ad1c17.png)

We now need a similar text box to appear for an additional plant name. The plant is "Heathers - Calluna and Erica species", which has ID 13608 in termlist ID 668.

**Comment by BirenRathod** [comment]
@kitenetter 
ID 13608 has added to the list for displaying textbox.

**Comment by kitenetter** [comment]
@BirenRathod the "Exact species" text box is not opening up when "Heathers" is chosen on the form.

**Comment by BirenRathod** [comment]
It does open. did you clear the cookies? 
![image](https://user-images.githubusercontent.com/5941255/55499503-11e9b200-563e-11e9-81c4-a9d831e134d2.png)

**Comment by kitenetter** [comment]
Thanks, closing.
