### ISSUE TITLE
Problem with setting up NatureSpot verifier

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#536]
We've been asked to add a verifier for ants on NatureSpot. The NS species dictionary groups ants in with "Bees, Wasps and Ants". Two questions:
- If I set a filter for family Formicidae, only one ant record appears, and this is one that has been redetermined. So I'm assuming that the link to family is missing from the NS dictionary? But in the past we have set up family-level filters for NS verifiers - has something changed?
- In the "Species groups" part of the "What" filter setting I cannot call up the NS category "Bees, Wasps and Ants" - I thought this ought to be possible?

**Comment by kitenetter** [comment]
This may relate to #513

**Comment by kitenetter** [comment]
Related question: do NatureSpot users have to register on iRecord as well before we can set them up as verifiers? It appears that they do, although I can't remember that being an issue with previous verifiers I've set up (although perhaps all the previous ones were already registered on iRecord!).

**Comment by kitenetter** [comment]
This seems to be a general issue for NatureSpot verification - I can no longer find the NS top-level taxon groups in the iRecord filter settings, and the filters we've previously set up using UKSI families or orders no longer produce any NS records.

**Comment by DavidRoy** [comment]
Is this using the NatureSpot specific filter setup - https://www.brc.ac.uk/irecord/filters/admin-edit-ns

**Comment by kitenetter** [comment]
Thanks @DavidRoy - if I knew about that I had forgotten, sorry! Will try again.

**Comment by kitenetter** [comment]
Using the NS specific set-up I can find the top-level taxon groups.

I can't find the verifier name who has registered on NatureSpot but not on iRecord.

I can't see any way of selecting families or orders within the top-level species group - I assume that is a limitation of the NS species dictionary?

There are NatureSpot verifiers set up using UKSI familes, but presumably that was an error on my part, and those people will never have in fact been presented with the records they should have been seeing? I will review those and let Dave Nicholls know.

**Comment by kitenetter** [comment]
Is there any way of telling whether an existing filter was set up using the NS form or not?

And is it possible to edit an existing NS filter?

I'm 99% certain I've set up filters using the UKSI families/orders before, and they correctly displayed records, but they appear not to be doing so now.

I'm afraid I'm completely confused by all this.

**Comment by DavidRoy** [comment]
The best way to check is to query the postgres database, e.g. 
select id, title, description, definition from filters
where defines_permissions is true
and sharing = 'V'
order by id desc

**Comment by MNSmith** [comment]
Could you please check with Mike Fox / BWARS before adding any ant (or other aculeate) verifiers please.  Because at present we can't see who is allowed to verify what through iRecord, the only way the National Recording Scheme knows about things like this is when we see via the download facility that someone who we may not know of at all has been given Verifcation rights.  From the BWARS point of view, we need to know any who any potential new verifiers are so we can confident of the quality of their verifications.

**Comment by kitenetter** [comment]
Have replied to @MNSmith via email.

**Comment by kitenetter** [comment]
@johnvanbreda provided further information via email about the NatureSpot filters, and I have added this to:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Procedures and guidance\PROCEDURE setting up new verifiers for iRecord.docx

Closing.
