### ISSUE TITLE
Does the "title" attribute have to be mandatory in the "people" table?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#537]
I need to edit a surname in the people table, but I find that the "title" attribute is now mandatory. I'm pretty sure it wasn't mandatory previously, and we have plenty of entries in that table without a title.

I don't want to have to choose a title as I don't know which one this person would want to use. The set of titles available to choose from is arguably too restrictive to allow an appropriate choice for all people.

Is there a reason why this has to be mandatory? If so, can we add a null term to the list? Does this attribute get used to populate anything?

**Comment by johnvanbreda** [comment]
Mistake in the UI - fixed in develop branch.
