### ISSUE TITLE
PoMS map report

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#538]
As discussed, I would like to be able to set two columns to be 'not visible':
- grid ref
- recorder name

URL:
https://www.brc.ac.uk/irecord/node/7355/edit

**Comment by kitenetter** [comment]
Hi @BirenRathod would it be possible to make these adjustments before Friday, as I'd like to use the iRecord map page to provide feedback to recorders over the weekend?

**Comment by BirenRathod** [comment]
@kitenetter 

I have added those two columns in report settings and that works fine. you can see here https://www.brc.ac.uk/irecord/node/7355?group_id=1074&implicit=

That means it doesn't require to add flags in xml report file.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - closing.
