### ISSUE TITLE
Elastic Search download files missing location name

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#539]
Using https://www.brc.ac.uk/irecord/elastic/download

To illustrate:
Search term:  id:3069212
all records
all available records

returns a file with Location name field = '-', whereas the original record has a site name
https://www.brc.ac.uk/irecord/record-details?occurrence_id=3069212

Another example from general irecord survey
https://www.brc.ac.uk/irecord/record-details?occurrence_id=2817540

A widespread issue when extracting all iRecord butterfly data, i.e. 100,000+ records missing location name in download file

**Comment by johnvanbreda** [comment]
Fixed. Location name was only included if for an explicitly linked location - now the free text name is included (by switching to use location.verbatim_locality in the index).
