### ISSUE TITLE
Calendar obscured by pick list of previous dates on website data entry

### ISSUE THREAD

**Issue by SK53** [BiologicalRecordsCentre/iRecord#540]
I usually enter data via the android app, but wanted to use the website for a couple of garden records as I can set them to private immediately. In doing so I noticed unwanted behaviour on entering a date, the calendar is precisely obscured by a drop down list of dates for previous records. Browser is Microsoft Edge. Moving away to another tab & back seems to restore the calendar.

**Comment by DavidHepper** [comment]
This also occurs in Chrome, for example with the date fields of the Export (Download) forms. My workaround is to disable to suppress the offering of dates that you've entered recently is to turn off **Save and fill addresses** in the **Autofill > Addresses and more** section in Settings. This is a blunt instrument: you can't control it by field type. Is there a way to control programmatically where the pop-up appears relative to the field?

**Comment by kitenetter** [comment]
I'm fairly sure the calendar behaviour has changed since this issue was raised - closing.
