### ISSUE TITLE
Question: where are "milestones" set up within Indicia/iRecord?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#541]
I want to be able to set up an iRecord "milestone" to send a notification, e.g. when a user contributes X records to a particular survey. I have a vague memory that this used to be done via the warehouse browser interface, but I can't find milestones, only triggers.

Where should I be looking?

@sacrevert I remember you set up a milestone, possibly for bryophytes, can you recall how that was done?

**Comment by sacrevert** [comment]
It was through the warehouse management website (or whatever it is called). I can't remember the detail, sorry!

**Comment by johnvanbreda** [comment]
Log into the warehouse. Go to Admin -> Websites, find and edit your website. Milestones can be added to the Milestones tab.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - closing.
