### ISSUE TITLE
Mouse-wheel zooming odd behaviour?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#542]
Using firefox, to zoom the maps using the mouse I have to click Ctrl + mouse wheel (which I think is what we intended to implement). However, recently the whole page display zooms in and out as well as the map zooming - the Ctrl + mouse wheel seems to be having a double effect.

**Comment by DavidHepper** [comment]
This seems OK to me. Ctrl+WheelMouse over the map zooms the map only whereas over anywhere else on the page zooms the whole page, as shown by the zoom level indicator in the Menu Bar: 
![image](https://user-images.githubusercontent.com/24915271/56116493-d1ebce80-5f5d-11e9-9d6e-ec70f233ea6e.png) - normal functionality for Firefox.

**Comment by kitenetter** [comment]
I've just tested this again using Chrome, and going to the "Enter a casual record" form. When I use ctrl+wheel over the map it is definitely zooming both the page and the map! Maybe I have a setting somewhere that I've managed to trigger without realising it?

(I'll test Firefox again at home, it's possible that I meant Chrome when I previously said Firefox.)

**Comment by DavidHepper** [comment]
Yes, I see the effect you reported in Chrome, not Firefox.

**Comment by kitenetter** [comment]
Does not seem to cause problems for other users - closing.
