### ISSUE TITLE
Update to Earthworm habitat categories

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#544]
From  EBS
Request 1 - Habitat Codes

I think I mentioned to you that there was an issue with the ESB earthworm records form in that the codes for our habitat system and this had led to confusion for our recorders between some of the habitat classifications, particularly the woodland habitats (see below). I never found the time to follow up with the email you requested so apologies for taking so long. Please could the habitat codes be included (this is the updated list, see request 2 to understand the differences from the current list on iRecord):

010 WETLAND
011 fen
012 carr
013 bog
020 HEATHLAND/MOORLAND
021 lowland wet heath
022 lowland dry heath
023 valley mire
024 upland heath/moor
030 GRASSLAND
031 acid grassland
032 neutral grassland
033 calcareous grassland
034 upland grassland
040 URBAN
041 park
042 orchard
043 churchyard
044 garden
045 compost bin
050 FARMLAND
051 arable
052 pasture
060 SCRUBLAND
061 dense scrub
062 scrub with open areas
070 WOODLAND
071 deciduous woodland
072 coniferous woodland
073 mixed deciduous/ coniferous woodland
090 BUILDING
091 glasshouse (heated)
092 glasshouse (heated)
100 CAVE/TUNNEL/WALL
110 WASTE GROUND
120 OTHER (please specify)

**Comment by burkmarr** [comment]
Hi David,

Is this something I could look at? I’m imagining that it’s a pretty simple change to a list on the warehouse or are there other implications?

Rich

**Comment by DavidRoy** [comment]
Good idea, thanks.  I've now assigned this and the related on to you

**Comment by burkmarr** [comment]
Thanks David!

Rich

**Comment by burkmarr** [comment]
This was completed a few weeks ago.
