### ISSUE TITLE
Revision to Earthworm habitat categories for Woodland

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#545]
Request 2 - Changes to Woodland Habitat Codes

The way our Woodland habitats were classified within the recording schemes (and are still categorised on iRecord) was as below:

070 SEMI-NATURAL WOODLAND
071 deciduous
072 coniferous
073 mixed deciduous/coniferous
080 PLANTATION WOODLAND
081 deciduous
082 coniferous
083 mixed deciduous/coniferous

The lack of codes displaying on iRecord means that there was no discernible difference for recorder between 071 and 081, 072 and 082 or 073 and 083. This will have inevitably led to habitats being mis-categorised. Personally, I've never felt there was a big need to distinguish between Plantation and Semi-Natural woodlands for the purposes of our recording scheme, and would actually argue that it makes habitat classification that little bit more complicated (as well as not allowing for those who aren't sure if the woodland they sampled is semi-natural or a plantation). I presented this to the ESB committee and was given permission to proceed with a new simpler Woodland habitat classification system(as in the list above: 070-073)

Is it possible to implement this new classifcation system on iRecord for us?
•	former 070 and 080 >  070 WOODLAND
•	former 071 and 081 > 071 deciduous woodland
•	former 072 and 082 >  072 coniferous woodland
•	former 073 and 083 >  073 mixed deciduous/ coniferous woodland

**Comment by burkmarr** [comment]
Main work on this is done and the new habitat termlist is available in iRecord. Keep the issue open until RB has resolved translation of samples which previously referenced plantation woodland categories (which have been deleted) to new general woodland categories. (This should only affect reporting of existing records.) There is a block on this at the moment which is that I am sorting out remote access to Warehouse DB from Lancaster.

**Comment by burkmarr** [comment]
Done.
