### ISSUE TITLE
Recorder league table: add number of taxa column

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#546]
Report from iRecord forum: https://www.brc.ac.uk/irecord/node/7590
Well half of it has been fixed. There is now a league table for number of records. What I really want is the one for **number of species**. This is actually very useful as it gives you a figure for how many different species of all taxa you have ever seen (and recorded). So I am hoping that will be restored. Otherwise it seems that irecord is slowly losing functionality.

**Comment by johnvanbreda** [comment]
I've added a number of species column since that was simple. Further enhancements at some point should include filtering, paging, a position column, highlighting the current user and sorting by clicked on column title.

**Comment by DavidRoy** [comment]
Thanks.  Closing for the time being.  I agree that a fuller overhaul at some point is a good idea
