### ISSUE TITLE
Problem with adding taxa to master list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#548]
In March I added seven new UKSI species names to the warehouse master list (list id 15). The new species are appearing as options when adding data, but records linked to them do not appear in reports, e.g. for the relevant verification and Explore pages.

Looking at cache_taxa_taxon_lists it appears that these new names have not been linked to the higher taxonomy - is that why they are not appearing in reports? These attributes are empty:
- kingdom_taxa_taxon_list_id
- order_taxa_taxon_list_id
- family_taxa_taxon_list_id
- kingdom_taxon
- order_taxon
- family_taxon

I added the new species via the warehouse interface, linking each name to its parent genus (all genera were pre-existing in the master list). I wasn't aware that any further action was required for the hierarchy linking.

**Question**: What else should I have done?

**Action needed**: can you update the taxon hierarchy for these seven species please (and will that resolve the issues with verification and reporting?):
[anthomyiids new species.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/3079788/anthomyiids.new.species.xlsx)

**Action needed**: these five species are currently pointing to preferred_taxa_taxon_list_id 41793, can they be updated to point to preferred_taxa_taxon_list_id 431853
[anthomyiids change preferred.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/3079790/anthomyiids.change.preferred.xlsx)

The above changes are all in line with the UKSI.

**Comment by kitenetter** [comment]
Added to May milestone as the verifier for this group is keen to resolve this to ensure the records are accessible.

**Comment by johnvanbreda** [comment]
I've found and fixed a bug which caused this. It looks like the actual data you setup were correct. I've also added work_queue tasks to reprocess these taxa but will check tomorrow that it actually worked.

Still to do the action regarding swapping the preferred taxa over.

**Comment by kitenetter** [comment]
@johnvanbreda at least one of the new species now does seem to be appearing in the correct place. Would be great if you can update the preferred taxa as well as the verifier is regularly emailing to find out when the records will be displayed!

In the process of checking this I've found a couple more taxa that are not correctly linked to their hierarchy - @kitenetter to check these next week (Alliopsis billbergi and Paregle audacula)

**Comment by johnvanbreda** [comment]
@kitenetter I've fixed the preferred/non-preferred taxa.

**Comment by DavidRoy** [comment]
Review current status of issue

**Comment by kitenetter** [comment]
No further issues, closing.
