### ISSUE TITLE
Elastic Download missing record status

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#549]
Using https://www.brc.ac.uk/irecord/elastic/download

To illustrate:
Search term: id:2514126
all records
all available records

returns a file with Record status field = '-', whereas the original record was accepted
https://www.brc.ac.uk/irecord/record-details?occurrence_id=3069212

A widespread issue when extracting all iRecord butterfly data, i.e. 100,000+ records missing record status in download file

**Comment by kitenetter** [comment]
Further points on the elasticsearch download following the download of dragonfly data today:
- there are a number of attributes that were in the old csv download format but are not in the new, does this need reviewing or is the new csv layout still work in progress?
- there is only a single data column, making it hard to deal with date ranges
- queried records appear not to be flagged
- the "iBRC" prefixed RecordKey is not being generated
- Coordinate uncertainty is not being displayed
