### ISSUE TITLE
Use SSL

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#55]
Since the website uses sensitive user data (login/registration and other) and because it is now almost a general trend towards https and because it is [free](https://letsencrypt.org/), I think the website should move to using **https** by default.

Also, Chrome asks the website to be on https if it uses geolocation and I can't make an iRecord App android install popup as one of the requirements for the page is to use https.

**Comment by kitenetter** [comment]
David asked for Jim to look at this - test on development version first?

**Comment by kazlauskis** [comment]
@JimBacon any thoughts on how long this is going to take? iRecord Dragonflies app has lost its GPS feature because it is not on HTTPS:

[Chrome dropped GPS on HTTP news](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en)

**Comment by JimBacon** [comment]
The brc domain has had an ssl certificate for some time. https://www.brc.ac.uk/irecord/ gets a response albeit ugly. It is way down my list of priorities to make it work any better. For more details of making Drupal use https see https://www.drupal.org/https-information.

Unfortunately the dragonflies app is on another domain and needs its own certificate. 

While there may be free ssl certificates around, our process has been to request them from CCS who I think pass it on to RTS and it certainly goes to Jisc (https://www.jisc.ac.uk/certificate-service) which is not free. While installing the certificates takes seconds, requesting and maintaining them is a drag, not to mention the long term cost. Let's Encrypt looks like it could be a great alternative if the certificates are of adequate quality and we are allowed to use them. That might not be a quick discussion.

For a rapid, free solution, can we use a self-signed certificate?

**Comment by johnvanbreda** [comment]
For what it is worth, the Indicia + Drupal is running on https on a couple of servers I know about. The only issue I came across was that the Yahoo Geoplanet service does not support https but there may be other edge cases.

**Comment by japonicus** [comment]
Chrome is likely to start displaying warnings on non-https sites with password fields soon.

https://developers.google.com/web/updates/2016/10/avoid-not-secure-warn

Firefox is also heading in that direction https://blog.mozilla.org/tanvi/2016/01/28/no-more-passwords-over-http-please/

**Comment by BirenRathod** [comment]
Regarding Jim's question about self-signed certificate, self-signed certificate are good if you want to test browser on the same server, but it is limited only for same server, so giving access of the website of with self-signed certificate will not serve the purpose. 

Also, another concern about Drupal interaction with SSL certificate. as long as site has got right SSL certificate, any drupal site doesn't complain.

If you are interested to see iRecord interaction with the warehouse by using SSL certificate.  I have now configured test iRecord site, which is test.brc.ac.uk/irecord. It this goes fine than I could easily roll out on to the live site.
