### ISSUE TITLE
Elasticsearch verification: add 'redet' button

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#550]
Reinstate a 'redet' button

**Comment by DavidHepper** [comment]
Yes, please!

**Comment by johnvanbreda** [comment]
Fixed in develop branch - requires @allowRedetermination on the [recordDetails] component.

**Comment by johnvanbreda** [comment]
Not yet fixed as need to update Elasticsearch content so the list used for original determination is available.

**Comment by kitenetter** [comment]
The priority is to get the redet button working on the new page in the same way as it does on the old. However, we have also been asked if it is possible to implement redets as a bulk operation for multiple records, in the same way as the verification buttons can be applied to multiple records.

I'm raising this here in case it is something that can be easily done when setting up the redet button, but if it isn't let me know and I will raise this as a separate issue for longer-term consideration.

**Comment by johnvanbreda** [comment]
@kitenetter - separate issue please!

I've implemented the code - needs the @allowRedetermination option set on the [recordDetails] control when deployed.

**Comment by kitenetter** [comment]
Enhancement request transferred to #674
