### ISSUE TITLE
Elasticsearch verification: recorder email display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#552]
Display user email address in details pane wherever possible

**Comment by kitenetter** [comment]
I'm finding that the the attributes don't always show up in the details pane on the right-hand side, at least not for the first record in the grid, and the intial view of that first record. If I click on to the second record the attributes appear, and if I then click back onto the first record they appear there also, but if I only click on the first record they often don't appear.

It's a minor issue but could be misleading for the first record each time you start a new verification session.

**Comment by johnvanbreda** [comment]
Is this still happening? Are you sure they are not just taking a moment to appear?

**Comment by kitenetter** [comment]
I can't reproduce the issue I had with attributes failing to display. Closing.

**Comment by kitenetter** [comment]
Have had this problem again today. Sequence:
- Go to new verification page
- Sort by species
- Filter by species using column-head filter
- Click on first record

The basic details are shown, but not the additional attributes. If I click on the second record the attributes are shown, and I can then click back on the first record and they reappear for that one.

**Comment by kitenetter** [comment]
In fact this is now consistently failing to show the additional attributes for the first record in any verificatiopn grid. E.g. If I have a page of records showing, I can't see the additional attributes for the first record, but I can for the second. If I then verify the first record, so that it disappears and the second one moves up into first place, the second one then stops showing the extra attributes. So it seems to be related to just the first row of the current grid.

**Comment by johnvanbreda** [comment]
Hi @kitenetter I still can't get this to happen. The only thing I do notice is that sometimes it takes a second or two to load the additional attributes. I've masqueraded as you and tried Chrome, Firefox and Safari with both Bee-Fly watch and Stratiomyidae data. 

Any chance you could confirm the browser and maybe send me a video?

**Comment by kitenetter** [comment]
I'm finding that the additional attributes are failing to appear on a regular basis, on the new verification page, using Firefox. Tonight this has mostly been happening following a verification decision - the verified record is removed from view, so the nest record in the grid moves into focus, but its attributes do not get displayed (even if I wait for a long time):

![image](https://user-images.githubusercontent.com/16039111/62977102-068d6b00-be16-11e9-8e04-bab7e2d1979b.png)

If I click on the record below and then move back up the attributes display immediately:

![image](https://user-images.githubusercontent.com/16039111/62977213-4f452400-be16-11e9-8a70-1fc4d29a1641.png)

This doesn't happen with _every_ verification, but it has been happening more than 50% of the time this evening. Same problem with the top record in the grid when I first open it.

**Comment by kitenetter** [comment]
Additional observation: there seems to be some interaction with the thumbnail images. If I click on a record in the grid and the attributes are displaying, and I then click on a thumbnail to look at an image for that observation, when I close the image window the attributes get removed from view.

Not sure if that is happening every time but it is happening a lot.

**Comment by johnvanbreda** [comment]
I've found a possible cause and fixed it, although it only occurred for me after changing context. Please re-open if you see it again.
