### ISSUE TITLE
Elasticsearch verification: bulk verification options

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#554]
Enable bulk verification options:
- Bulk verify similar records (highest priority)
- Review grid (lower priority, given that tick box verification is working well)

**Comment by johnvanbreda** [comment]
Bulk verify (review grid) option now available in develop branch.

**Comment by DavidRoy** [comment]
When verifying a set of records (using the tick box option) and applying the decision, the message box says 'undefined record(s) updated.'.  Would be helpful to report on the number of records

**Comment by johnvanbreda** [comment]
Fixed

**Comment by kitenetter** [comment]
@johnvanbreda it's just been pointed out to me that the bulk verification options for "Apply decision to" do not appear if using Internet Explorer. Is that something within our control?

![image](https://user-images.githubusercontent.com/16039111/67039274-e7160580-f118-11e9-99fa-7ab5dce06074.png)

**Comment by kitenetter** [comment]
Further to the problems with Internet Explorer, the column headings don't format very nicely, and the option to expand the grid to full screen seems unavailable:

![image](https://user-images.githubusercontent.com/16039111/67684999-24d22400-f98c-11e9-8528-33fbade778ed.png)

**Comment by kitenetter** [comment]
Another Internet Explorer problem:
1. Go to new verification page
2. Use the column-head filter boxes to filter out a single record
3. Apply verification decision
4. Record disappears from view as expected, but grid then gets compressed onto far left of screen, making it impossible to remove the column-head filters and continue verifying:

![image](https://user-images.githubusercontent.com/16039111/69365742-db27e100-0c8c-11ea-80a6-c3b7867c7b0d.png)

Are we likely to be able to support IE for the new verification page or do we need to encourage verifiers to use a different browser?

**Comment by BirenRathod** [comment]
@kitenetter 
If you are using IE on CEH laptop then this will be the problem of IE as IE on CEH laptop is old version.

**Comment by kitenetter** [comment]
@BirenRathod I am using IE11 on a CEH laptop, but only to reproduce the issue that was raised by one of our verifiers. They don't know which version of Windows or IE they are using but it's unlikely to be Edge.

I know that moving to Edge (or Chrome/Firefox) would be a solution, but that is not always easy for people to do if they are unused to changing their default computer settings. However, if we can't support IE11 we'll just have to let people know that.

**Comment by BirenRathod** [comment]
@kitenetter 
Actually CEH doesn't support to use IE edge due to version of Windows 10. So we have been forced to use IE 11. Technically IE 11 is not supported by Windows 10. 
I don't know about John intention of supporting styles for IE 11 in regards to iRecord or Indicia. but in terms of responsive theme, IE 11 is way older browser and Microsoft has stopped patching for IE 11. So My recommendation is not use IE 11 and just focus on Chrome/Firefox especially if we only target CEH users.

**Comment by johnvanbreda** [comment]
I've implemented a fix for the IE squashed columns problem, though I agree with Biren - IE is a very old browser which has quite a lot of problems in the way it interprets HTML/CSS and JavaScript, so supporting it properly can make things messier.

**Comment by kitenetter** [comment]
@johnvanbreda can this be closed?
