### ISSUE TITLE
Elasticsearch verification: document search box syntax

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#555]
Provide documentation on use of search box syntax

**Comment by kitenetter** [comment]
@burkmarr can I assign this to you. It will apply to the elastic pages generally I think. There is some documentation here:
https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/document-structure.md

but I have struggled to apply it effectively, in particular when trying to filter on dates and date ranges, and with knowing what data types are used for the various attributes, and if/when text needs to be in quotes. Need a dummies' guide!

**Comment by burkmarr** [comment]
@kitenetter - I know no more than you on this. @johnvanbreda - is there any documentation that can help me look into this? I don't think the stuff on the document structure is much help. For example, is it possible to use the verification searchbox to target searches against particular fields? If so, what's the syntax for doing that?

**Comment by kitenetter** [comment]
@burkmarr there are a few examples of how to target searches to attributes here:
https://www.brc.ac.uk/irecord/elastic/download

but when I've used it I've fallen foul of not knowing how to format dates and not knowing when or if text needs to be in quotes.

**Comment by johnvanbreda** [comment]
The syntax documentation is at https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax. 

We are just using the standard "query_string" in Elasticsearch out of the box. It's also easy to reconfigure to use "simple_query_string" which is simpler, though less powerful.

**Comment by burkmarr** [comment]
Thanks @kitenetter and @johnvanbreda.

**Comment by burkmarr** [comment]
@kitenetter - where do you want this documentation to live?

**Comment by kitenetter** [comment]
@burkmarr it needs to made available via the Help pages (its immediate application is for verifiers but it will apply more widely as the other ES functions become available). But we could link to a document or to another online repository if you have somethign suitable in mind.

**Comment by burkmarr** [comment]
That's great. I'd prefer a Drupal page since it is easiest to edit/update which we will inevitably need to do. I'll create a draft page and start writing it.

**Comment by burkmarr** [comment]
@kitenetter - here it is: https://www.brc.ac.uk/irecord/es-search-box. Feel free to edit or add to it.

**Comment by kitenetter** [comment]
Thanks @burkmarr - have just made some minor edits, and will continue to do so as needed (e.g. I've just found out that using a forward slash in the search box causes it to fail if used in a text string that is not enclosed in double-quotes). We can close this issue.
