### ISSUE TITLE
Elasticsearch verification: refresh page once emptied

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#556]
If you verify all the records on a single page, that page empties, but there doesn't seem to be any way of getting on to the second page, except by refreshing the whole web page. Would be good if the "Next" button worked for this situation.

**Comment by johnvanbreda** [comment]
Once you get 3/4 of the way through the page it will refresh so this won't happen in the upcoming version.

**Comment by kitenetter** [comment]
Today, using Firefox, I'm getting this behaviour:
- Use 'select all' tick box to tick all 30 records on the page
- Use bulk verification to accept all 30 records
- A single record then remains in the grid, and is shown as unverified; fairly certain this is the last of the 30 records, and had previously been part of the 30 ticked boxes

This creates an unnecessary extra lot of clicks to accept this single record before the grid will refresh and display another 30 records.

**Comment by kitenetter** [comment]
Also got to what should have been the last page of a set of pages and it is not refreshing - I bulk accepted a block of 30 records, and now I have an empty grid that says it is showing "1 to 30 of 51 records", but it should be showing me the final 21 records awaiting verification after my previous block of 30.

Clicking on the "Next" button produces no results, so only way forward is to refresh the page, which brings up the 21 records.

**Comment by johnvanbreda** [comment]
Fixed in develop branch.
