### ISSUE TITLE
Elasticsearch verification: columns in grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#557]
Columns to include in grid:
- Restore column order to match old page (e.g. species in third column, recorder in 8th etc.)
- Allow user to choose columns (i.e. restore the ‘plus button’ functionality from old page)
- I expect there will be requests to restore the missing columns for Common name, Site name and Last updated, which may make the grid very congested – the ‘plus button’ may be the best approach to this if it is possible to restore

**Comment by MNSmith** [comment]
I'd be happy without "Common Name", either by default or by being able to drop it from a list of fields to be displayed.  Site Name is a must in the grid please.

**Comment by johnvanbreda** [comment]
@kitenetter I've made some changes to the column order but note that Matt has suggested a different order elsewhere. Given this issue, plus #569, #570 and #571 please can you provide me with a definitive list of columns and the correct titles and ordering you would like to see in the grid. You can assume that the columns picker will be recreated in Elasticsearch at some point so verifiers will be able to tweak those visible.

**Comment by kitenetter** [comment]
@johnvanbreda 

Here are my proposals for the column headings and ordering:
[Verification page column headings proposal.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/3126743/Verification.page.column.headings.proposal.xlsx)

Same thing as an image:
![image](https://user-images.githubusercontent.com/16039111/56887689-2026c480-6a6a-11e9-96fd-d6d0afb28d07.png)

Given the differing requirements of different verifiers I think the addition of a columns picker will be a very welcome addition. In the meantime I suggest we live without the four columns that are flagged above as not being part of the default view.

The wording I've suggested for the column headings is mainly based on trying to keep the short, although several could be abbreviated further if needed.

@MNSmith makes a good point about the desirability of standardising column headings throughout iRecord and I will bear that in mind, but this has to be balanced with the fact that there are sometimes different priorities for these column-heading type labels - sometimes they need to be short, sometimes they need to be more wordy in order to make them understandable to a wider audience.

**Comment by kitenetter** [comment]
@johnvanbreda I've now had second thoughts already, sorry! I had proposed adding a VC number column, but I don't think we need that at all. It can be covered either via the "Create a filter "options (if those are going to be restored) or via the search box parameters (in which case I'll need to write some guidance on how to do that).

**Comment by japonicus** [comment]
I think that VC number can be useful as a way to make sense of a nationwide overview.

e.g. if a verifier has filtered by taxon, but then wants to sort the list by county to broadly cluster records (for which a grid-ref based sort may work less well).

**Comment by MNSmith** [comment]
Re the comment on column widths brough over from #571, I'm not seeing that in action at present, either that or the dynamic column width control commands as a lot of "extra" space to the columns.

![grid](https://user-images.githubusercontent.com/18451743/56893595-207b8b80-6a7b-11e9-98ac-4d15f56f55f4.jpg)

**Comment by johnvanbreda** [comment]
@MNSmith are you sure the extra space in your site name column is not because there is a row further down the grid with a longer site name? We definitely aren't doing anything here other than allow the browser to format the column widths as it sees fit.

I've updated the columns so closing.
