### ISSUE TITLE
Elasticsearch verification: add map options

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#558]
Some verifiers dislike the heat map presentation – personally I think it’s great, but would be good to offer a grid square view as an alternative.

**Comment by johnvanbreda** [comment]
Code in develop branch now ready for this to be added to the map.

**Comment by johnvanbreda** [comment]
You now have options for a grid based version with atlas style circles that are darker for "hotter" spots. Plus another layer for all the records in the current grid.
