### ISSUE TITLE
Elasticsearch verification: 'log' functionality

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#559]
On the old verification page we implemented the “Log” view, but I don’t have a good feel for how many verifiers use this functionality. 

Personally I find it quite hard to use, and in particular I’d like a simpler way of filtering out “all verifications for my group/area that were made by someone other than me”, which is a feature that many verifiers have requested.

Should we reinstate the log view as before, or try an alternative approach that focuses on the 'other verifiers' verifications' , or offer both approaches?

**Comment by MNSmith** [comment]
What is the "Log" function meant to do?

**Comment by johnvanbreda** [comment]
@MNSmith The log is a place where you can keep an eye on activity by any other verifier's whose set of records overlaps with your own. E.g. in your case this might include county recorders.

@kitenetter The simplest solution here is to add a new option to the Status drop down for verification decisions by anyone else. I've added code to the develop branch to enable this. 

Note to self - once deployed, the following option needs to be added to the Status drop down:
```html
<option value="(NOT identification.verifier.id:{{ indicia_user_id }}) AND _exists_:identification.verifier.id">Decisions by verifiers other than me</option>
```

**Comment by johnvanbreda** [comment]
Done
