### ISSUE TITLE
Elasticsearch verification: remove queried records from grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#564]
Is it possible for records, once queried, to be removed from the grid's 'pending' view?

**Comment by johnvanbreda** [comment]
@kitenetter This already happens doesn't it?

**Comment by kitenetter** [comment]
It seemed not to last night, will test again.

**Comment by kitenetter** [comment]
Have just tested this, and yes, the queried record did disappear from the grid. Will keep an eye on it, but closing for now.
