### ISSUE TITLE
User does not appear in search box to enable setup of filter for verification

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#565]
I'm trying to setup a filter for user:
https://www.brc.ac.uk/irecord/user/848

The name 'Hughes, Morgan' does not appear in the search box for 'For who?' on https://www.brc.ac.uk/irecord/filters/admin-edit

Therefore the verification role cannot be setup

**Comment by kitenetter** [comment]
Morgan originally registered with a different surname, and the warehouse retains the original surname even though the iRecord account has changed. I will contact Morgan and ask if it is okay to edit her name in the warehouse.

**Comment by kitenetter** [comment]
Name updated and verification filter set up. Closing.
