### ISSUE TITLE
Elastisearch - Record Details window.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#567]
Apologies if people have seen these already, but I followed a link from an old e-mail and it looks like I added my list of comments to #530, which is already closed.  I've coped them over to new threads, please delete if these are duplicates.

Record Details Pane

Overall this page is working well and is much quicker than the existing grid. If this way we are going with iRecord, could I once again ask if we could have some consistency in the way the details are displayed and the various field names used as they seem to vary greatly between different sources.

Beyond the basic record details of "what, where, when who" there are a lot of other fields being displayed on records and it seems to me that this new page has added even more, adding even more clutter to the page. I'm finding the addition of Vice County and LRC Boundary particularly confusing as they are right next to Location. As a verifier, I don't really need to know the date and time the record was entered and then last updated or the Taxonomy of a record. A fixed, standard basic layout allows for much faster processing of records. I appreciate that certain Schemes may want to see particular specific details on records, but these "extras" should be displayed in a separate frame.

Ideally, I would like to see a "standard" record details pane that displayed the basics needed for verification.

Record Number, Record Status and Passed checks should form a 1 line header, ideally in a slightly larger / bold font, followed by:

Accepted Name.
Common Name
Location
OS Grid Ref - if this has to be generated from a calculated grid ref then so be it, no Lat / Long displayed in this section please.
Date of record
Recorded by
Identified by
Source (Dataset)

**Comment by johnvanbreda** [comment]
@kitenetter one for you to review?

**Comment by kitenetter** [comment]
@johnvanbreda @MNSmith 

Here's my suggestion, let me know what you think.

![image](https://user-images.githubusercontent.com/16039111/58037610-ac864d80-7b25-11e9-8d96-8171b384c004.png)

Notes:
1. I agree that, if possible, it would be good to have ID - Status - Checks all on one line, assuming that doesn't cause problems with variable screen sizes
2. I find it very useful to be able to see which name was used by the person entering the data, as well as the recommended scientific name that iRecord is using and, where available, the English name. So I've suggested that all three of those things are presented separately, although another possible approach would be to have some sort of icon or typolgy that distinguished which name was used for data entry. But to me it seems clearest to show the three different things.
3. Grid ref will show the output grid ref, which will be an OS grid ref for British records, an Irish grid ref for Ireland/Northern Ireland, and presumably a CI grid ref for the Channel Islands?
4. For all the items in Box 1 I propose that the same set of headings always appears, even if the is no data in some of the fields (e.g. for comments or common name). This is to ensure that the Box 1 data is always presented in a standard format that makes it easy to quickly scan and review.
5. For the other boxes the contents can vary depending on the data source.

**Comment by kitenetter** [comment]
Adding in a previous explanation from @johnvanbreda : 

> You mention that the recorded taxon name is not shown and also ask about the (as recorded) tag. My intention was to only show as many taxon names as needed. So, if the recorder uses either the accepted name or the preferred vernacular, then this is shown by adding (as recorded) to the name. We only add an extra field for “given taxon name” if the recorder used a name that wouldn’t otherwise be shown such as a synonym or non-preferred vernacular. So to answer your question “I’m not clear to me what is being presented under “Accepted name (as recorded)” – is it the accepted name, or is it the name that was used for data entry? I think we need both.” - the name given is indeed both the accepted AND the name as recorded.

I can see the argument for minimising the number of names displayed, and one problem with my proposal above to display three names is that on many occasions two of the three would be the same.

So If I am understanding John's proposal correctly, this means:
- We always display two name fields, "Accepted name" and "Common name"
- If the data was entered using one of those two names, then this will be shown by labelling the field as appropriate, either "Accepted name (as entered)" or "Common name (as entered)"
- If the data was entered using a name that is not the current preferred name, then a third name field will appear, "Name entered", which will contain either a scientific name or a common name, depending on what was originally used

Advantage of this is that is means for the majority of cases we will only have to display two names; disadvantage is that it means (for a small proportion of records) we will have a field in Box 1 that only appears when needed, and thus breaks the requirement to have Box 1 displayed identically for each record.

**Comment by MNSmith** [comment]
This looks fine to me provided we can have a maximum of two names displayed at a time, not 3.

**Comment by kitenetter** [comment]
@MNSmith are you referring to the taxon names? If so I can't see how we can avoid displaying three in cases where the original recorder has used a non-current name - I think it is important to see the name originally entered as well as the current scientific name and the preferred English name.

**Comment by MNSmith** [comment]
Fair enough then.
