### ISSUE TITLE
Elastisearch - "Previous & Next" function.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#568]
**Previous and Next Buttons**

Previous / Next buttons only are not sufficient. We need the facility to jump forwars orbackwards across multiple pages as we have at present on the old grid. When you have several 100 records on a grid it takes a long time loading 30 records at a time to get to the other end of the list.

**Comment by kitenetter** [comment]
Why do you need to get to the other end of the list @MNSmith ? And can you not do so using the sort or filter options? I gather that adding the 'previous-next' buttons has a negative impact on performance.

**Comment by MNSmith** [comment]
One example - alphabetic recorder name sort so i get all the records for a recorder in one place.  Sometime I will come across a recorder in the list I want to skip past, so the ability to jump several pages at once is useful.  Jumping to the end of the list via the "Next X pages" option is faster than going back and re-filtering the main list.  In a situation where a list is displayed it is usual, and expected, that you can jump serveral pages at a time rather than one at a time to browse through the list quicker

**Comment by kitenetter** [comment]
I take your point here @MNSmith but if the trade-off of having page-jump functionality is a loss of performance speed then for me it feels like we should prioritise performance speed.

**Comment by kitenetter** [comment]
Closing.
