### ISSUE TITLE
Elastisearch - Verification Grid Columns

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#570]
**Verification Grid columns**

Main grid needs to display location name.
Main grid ideally should display "Identified by" name

Ideally, the grid should allow users to select / order fields displayed in the grid. Preferred order of grid for me would be:

ID - Source - Species - SITE NAME - OS Map Ref - Recorded by - IDENTIFIED By - Date - Media.

**Comment by kitenetter** [comment]
Now covered by #557 - closing.
