### ISSUE TITLE
Elastisearch - Verification Columns II

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#571]
**Verification Grid Columns # 2**

"Checks". As this field is non searchable and also replicated in the "Details" pane of the record, remove it from the grid to save space?

"ID Field" - as left justified, reduce current column width to save space on grid

"Source" - as left justified, reduce current column width to save space on grid as only code numbers are currently displayed. Allow text searches in this field

**Comment by johnvanbreda** [comment]
@kitenetter Please confirm if Checks should be removed? I plan to implement a columns picker popup at some point so this may mean there is no need to remove the column.

Matt - generally we build the data table in HTML and don't actually specify the column widths. The browser should then set the widths dynamically depending on the content in each column, so if there is little space available the ID and Source column fields should compress down to the minimum width possible. If I override this then we lose the nice dynamic handling of the column widths by the browser.

**Comment by kitenetter** [comment]
As ever it is going to be difficult to please everyone with the default display. I find the Checks column to be extremely useful - I can quickly scan down the grid of records and see which ones have failed a check and therefore might need closer attention, before applying bulk verification (where appropriate) to the ones that pass. It's a huge amount quicker and easier to do that via the icons in the Check column than it would be via text in the details pane.

So I think the columns picker will be the best option for this sort of dilemma, but I would argue that Checks should remain in the default selection of columns.

**Comment by kitenetter** [comment]
This is now being taken forward in #557 - closing.
