### ISSUE TITLE
Elastisearch  - Experience Tab II

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#573]
**Experience Tab # 2**

"Experience tab" Clicking on any of the numbers to view records displays records in a refreshed screen. When going "back" to the Verification grid all filters previously entered are cleared and you have to refilter again. Open records in a separate Window for this or make sure previous filters are re-loaded when going "back"?

**Comment by kitenetter** [comment]
It is of course possible to use a right-click option to 'open into a new tab', but personally I would support making that the default behaviour for left-clicks as well.
