### ISSUE TITLE
Elastisearch - Grid Action Buttons

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#574]
**Verification Grid - Action Buttons**

Fixed Action buttons. A t present the Action buttons are contained within the scrolling frame of the grid, which means if I scroll down through the records ticking selection boxes and the like, I then have to scroll all the way back up to the top to carry out an action. Can we have these buttons fixed in place please.

**Comment by kitenetter** [comment]
Transferred to #575 - closing.
