### ISSUE TITLE
Elastisearch - Terminology used on titles

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#579]
Titles and terminology -  these should be consistent with current usage and / or consistent across the system.  Examples: Site Name or Location, Map Reference or Output Map reference, Species or Accepted name

**Comment by kitenetter** [comment]
Will keep this under review, but there are sometimes reason for inconsistency e.g. use of an abbreviated name where space is at a premium. Closing.
