### ISSUE TITLE
Implement photo licensing in iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#580]
To clarify licensing of photos on iRecord.
- Allow licence to be set for incoming photos (either on a per-photo level or as a default in the user account)
- Provide option for users to retrospectively apply licences to photos previously uploaded to iRecord

It may also be helpful to add the photo licence attribute to the standard CSV download reports, in order to make the licence options more visible and filterable etc.

**Comment by DavidRoy** [comment]
links to #15

**Comment by johnvanbreda** [comment]
Also see #638.

**Comment by kitenetter** [comment]
Completed under #638 - closing.
