### ISSUE TITLE
iNaturalist data

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#581]
@johnvanbreda we're getting immediate feedback from verifiers that having iNaturalist records without photos is unhelpful. As far as I can see this results from importing records for which the photos do not have a CC sharing licence.

I think there are two options:
1. restrict the records to only those that have a photo we can import
2. continue importing all records, but add a clickable link to the verification details pane so that verifiers can see the photos on iNaturalist (link should open up in a new tab by default)

Neither of those choices is ideal but personally I would prefer option 2. If that is harder to achieve, then we ought to implement option 1 for now.

**Comment by DavidHepper** [comment]
I support this proposal.

**Comment by johnvanbreda** [comment]
Option 2 done on Elasticsearch verification page.
