### ISSUE TITLE
iNaturalist - "Identified by" names

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#583]
As well as the Recorder name / screen name, records in iNats have one or more "identifier" names associated with them.  Is there any way of brining at least the first of these names over into iRec as the "identifed by" name?

**Comment by kitenetter** [comment]
I think this would be difficult to achieve given the complex ways in which identifiers can interact on iNaturalist. We are not proposing to do development further enhancements to the iNat import in the immediate future but will review the process as a whole later in the year.
