### ISSUE TITLE
User account unlinked from iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#585]
We have a user on iRecord:
https://www.brc.ac.uk/irecord/user/16210

On the iRecord user page, his warehouse ID is given as 81356, but no such user exists in the warehouse user table. It must have existed in the past, because he has added records via iRecord in previous years.

His email address does link to a user account in the warehouse, user ID 131019. That user was linked to BWARS; NFBR; Pantheon, but not to iRecord. I edited the user account to add the link to iRecord, but this has not resolved the problem because the iRecord account is expecting to link to user ID 81356:
http://warehouse1.indicia.org.uk/index.php/user/edit/131019

Is it possible to relink the iRecord and warehouse user accounts?

**Comment by kitenetter** [comment]
@BirenRathod are you able to advise on this one? I need to let the user know what is happening - thanks.

**Comment by BirenRathod** [comment]
@kitenetter 
If 81356 is not available in the warehouse then remove the id 81356 from 16210 and save it. See if that brings 131019. if not then you can update manually to 131019.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - I removed the ID 81356 from the iRecord account page, and that did indeed result in the ID 131019 being added when I saved the account. Closing.

**Comment by kitenetter** [comment]
Unfortunately the re-linking of these accounts has highlighted another problem.

This user (Alex Cropper) must have previously had an account with user ID 81356. No such user exists in the warehouse interface, but if I search via pgAdmin there is a deleted entry for this user in table "users".

Alex's records prior to 2017 are linked to user ID 131019. His records in 2017 and 2018 are linked to user ID 81356. If he enters a record now (following my re-linking of his account) it gets attached to user ID 131019.

I don't understand how this has happened, but ideally he would like to have all his records available under his current account.

If I run this query in pgAdmin:
`SELECT * FROM indicia.cache_occurrences_functional
WHERE created_by_id = 81356`

it selects 200 occurrence records. Similarly, 
`SELECT * FROM indicia.cache_samples_functional
WHERE created_by_id = 81356`

selects 102 sample records.

What I'd like to request is that we run an update query so that all samples and occurrences that are currently linked to user 81356 become linked to user 131019. However, before doing this, are there are other tables that will need to be edited, or is it just occurrences and samples that we would need to update?

@BirenRathod are you happy to carry out this update or should I seek advice from @johnvanbreda before proceeding?

**Comment by BirenRathod** [comment]
@kitenetter 
I'm happy to update those records. 
As long as I'm aware, once updated those two tables should update records for others too. I also, check cache_occurrences_functional & nonfunctional after running scheduled_tasks.

**Comment by kitenetter** [comment]
You'll know this better than me, but I think we need to update both `created_by_id` and `updated_by_id`, in each of two tables: samples and occurrences. So that every appearance of `81356` in those attributes is replaced by `131019`.

**Comment by BirenRathod** [comment]
Indeed, I'm just letting you about possible update might required for other two tables too which is very unlikely.

**Comment by kitenetter** [comment]
Hi @BirenRathod have you been able to progress this one yet? It's not very urgent, but it would be good to tidy it up so I can inform the user.

**Comment by BirenRathod** [comment]
@kitenetter 
156 records of samples have been updated.
217 records of occurrences have been updated. 
Please wait for sometime (about 30 min) to check records on iRecord because it will updated in cache occurrences functional & nonfunctional tables.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - closing.

**Comment by kitenetter** [comment]
@BirenRathod I spoke too soon!

As far as I can see, the records have been updated in tables occurrences and samples, but not in tables cache_occurrences_functional and cache_samples_functional, and the records are not appearing under the correct user account in iRecord.

I haven't checked the nonfunctional cache tables.

**Comment by johnvanbreda** [comment]
@biren you may need to insert entries in the work_queue table. See https://indicia-docs.readthedocs.io/en/latest/administrating/warehouse/scheduled-tasks.html#work-queue

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda. 

@johnvanbreda, the link suggested to use occurrence table only. Do I need to add same for sample table too?

**Comment by johnvanbreda** [comment]
@BirenRathod yes, you should do the same for the sample table. Set the entity to sample, apart from that it is the same.

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda 

@kitenetter , I have inserted rows in the work-queue table, so it should be OK once next task scheduled finished to run.

**Comment by kitenetter** [comment]
I think this is now resolved - closing.
