### ISSUE TITLE
Misleading message when editing records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#586]
As far as I can tell this only applies to records that have been edited via the "Enter a casual record form". If you have a entered a record via this form, and it has not yet been verified, if you click on the button to edit the record you get a warning message "You are editing a record which has already been checked. Please only make changes if they are important, otherwise the record will need to be rechecked."

This is despite the fact that the record has not in fact been checked.

(Reported by a user and replicated in my account as well.)

**Comment by DavidRoy** [comment]
@burkmarr an issue for you to take on to gain wider experience of iRecord?

**Comment by burkmarr** [comment]
The message is generated from dynamic_sample_occurrence.php if a checkedRecordsCount property is set to 1.  Code in data_entry_helper.php increments the checkedRecordsCount property if an occurrence has record_status of  'C'. I suspect that it should be checking for a value of 'V' - but can you clarify for me @johnvanbreda?

Straight after a record is entered, the record_status is set to 'C'. From the Warehouse properties of this field, I see the possible values are: I - in progress, C - completed, V - verified, R - rejected, D - dubious/queried (deprecated), T - test.

So am I right in thinking that this message is only meant to be produced once the record has a status of verified? If so I will make an update and pull request.

**Comment by burkmarr** [comment]
Or perhaps it should be set the message if the code is V, R or D.

**Comment by johnvanbreda** [comment]
@burkmarr your synopsis is correct - the message should appear for record_status V, not C. @kitenetter may have an opinion as to whether you should include not accepted records in this (and amend the message accordingly). I'd ignore D as we aren't using that status and if they do make an edit, it gives the record a chance of being rechecked into a non-deprecated state.

**Comment by burkmarr** [comment]
@kitenetter - any thoughts on this Martin. I can address this quite easily I think either way.

**Comment by kitenetter** [comment]
@burkmarr it should definitely apply to V records. I think it should apply to R records as well. 

I don't think the message wording needs to be amended, as it talks of records that have "already been checked", and that wording applies whether the checking has resulted in an "Accepted" or "Not accepted" decision.

Rationale for including R records:
If someone is editing an R record I would hope that they are doing so in order to correct a mistaken ID, in which case they will see the warning message but still be able to continue to make the edit. But it's possible that someone could try to make a trivial edit to a record that has already been rejected, in which case the warning message might make them think twice, and prevent a previously-rejected record having to be looked at again.

**Comment by burkmarr** [comment]
Pull request: https://github.com/Indicia-Team/client_helpers/pull/89

**Comment by burkmarr** [comment]
Merged to master. https://github.com/Indicia-Team/media/commit/4c46fb9ff4060074db1b25059b023e1c9f908830
