### ISSUE TITLE
Elastisearch - Redet Function I

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#592]
Are there any plans to add the "Redet" feature to the Elstisearch screen.  Currently the only way to do this is to access the entire record via the "Edit this record" button, which is a bit long winded and slow.

**Comment by DavidRoy** [comment]
links to https://github.com/BiologicalRecordsCentre/iRecord/issues/550

**Comment by kitenetter** [comment]
Closing this one as covered in #550
