### ISSUE TITLE
Cannot upload csv for new termlist in development warehouse

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#595]
Wanted to upload a test version of a termlist into the dev warehouse, from a csv file. It gets stuck at the “Preparing to upload” stage. Console messages are:

![image](https://user-images.githubusercontent.com/16039111/57390633-c08c8f80-71b4-11e9-8781-4971373e0054.png)

**Comment by kitenetter** [comment]
I have been able to upload the same csv file into the live warehouse so this appears to be an issue specific to the dev warehouse.

**Comment by BirenRathod** [comment]
@johnvanbreda 
seems like same code hasn't been committed into develop branch.

**Comment by johnvanbreda** [comment]
I can't log in to the dev warehouse at the moment to check as my password has expired, but @BirenRathod please could you ensure that both client_helpers and media are running the feature-bootstrap branch (not the develop branch).

**Comment by BirenRathod** [comment]
@johnvanbreda 

Did you try log in again? if you can't able to log in, I can reset your password. No they are not running from feature-bootstrap branch. do you want me to switch it to feature-bootstrap branch?

**Comment by BirenRathod** [comment]
@johnvanbreda 

Sorry I just checked they are on feature-bootstrap branch but hasn't been pulled code for a while. I just pulled the code in it.
@kitenetter do you want try again to upload?

**Comment by kitenetter** [comment]
Thanks @BirenRathod. I have no files that need to be uploaded at the moment, but will try to test it at some point. Closing for now, will re-open if needed.
