### ISSUE TITLE
Asian Hornet verifcation page & Elastisearch

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#597]
Would it be possible to have the Asian Hornet Watch verification grid accessible via Elastisearch please.  I'm struggling a bit at times because a) we are still seeing geo-locations as Lat Long where OS Grids are wanted and b) the old style verification grid appears to no longer have maps that include the Channel Islands.  I saw Steph had AH records under Elastisearch the other day.

We seem to be getting a spate of the "other" kind of "Asian Hornet" submissions at present, some with photos and some without,  I can just about look at the Lat Longs and see that some of these cannot possibly anywhere near western Europe, but if we have mapping imagery it would be much easier to weed these sorts of things out if the dot on the map is in the middle of Iran when I look at the record.

**Comment by johnvanbreda** [comment]
Just a quick answer for now - have you tried selecting the OpenStreetMap or OpenTopoMap layer using the drop down behind the blue + button?

**Comment by DavidRoy** [comment]
@StephRorke to consider for GBNNSIP

**Comment by MNSmith** [comment]
I'll try using a different map option and see if that works.

**Comment by MNSmith** [comment]
If I could ask about this again please, it would be helpful if AH could be verified via an Elastisearch page.

**Comment by johnvanbreda** [comment]
This is now done. Full precision sensitive records now in the ES index but are filtered from most aliases, so can be selectively enabled (which I've done on the verification filter).
