### ISSUE TITLE
ElasticSearch: verification filter based on grid square not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#598]
Rob Large has a verification role for North Devon. Until recently, our North Devon boundary was excluding Lundy Island, so we had set up a verification filter for grid square SS14 (which covers all of Lundy).

That filter is working correctly when applied to the old verification page, but the same filter when applied to the new verification page is failing to filter geographically.

We don't have many grid square filters (and now that the North Devon VC is fixed we probably no longer need this one for Lundy), but raising this as a general issue: the new verification page is not yet handling all the filtering options that can be set up for verifiers.

**Comment by johnvanbreda** [comment]
Elasticsearch filter conversion supports the searchArea parameter in the latest code.
