### ISSUE TITLE
Add country-level boundary for Isle of Man

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#599]
This is needed to facilitate export of IoM records alongside UK records.

Country boundary can be a copy of the existing VC boundary.

(Issue follows on from #397)

**Comment by kitenetter** [comment]
@burkmarr queried what buffer should be applied. I see no reason why we can't use an exact copy of the existing VC boundary, which I believe has a 3-mile buffer (or at least that is how it is labelled, I'm not sure whether these are nautical miles or statute miles).

The main reason for copying the VC boundary into the set of country layers is to enable IoM to be added to filters where the user wishes to include, for example, Britain and IoM but exclude the island of Ireland. At the moment we can select Wales, England and Scotland as individual countries, but if we do that we have no way of including IoM.

**Comment by burkmarr** [comment]
Imported without problems via the Warehouse interface and now available on live site.
