### ISSUE TITLE
Map display incorrect for some records

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#6]
Maybe specific to Bringsty Common: there is a batch of records that have precise grid refs and are not marked as sensitive but are being drawn on the map with large (10 or 100 km) squares. Example: http://www.brc.ac.uk/irecord/record-details?occurrence_id=2785175 (part of a batch of 90-odd records with recorder given as "1997 Site Management Plan")

**Comment by kitenetter** [comment]
This is still an issue and has led to records being rejected due to the grid ref displaying incorrectly:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=2785175

**Comment by johnvanbreda** [comment]
Hi Martin
I've tidied up these records as well as a few others I found. I could only find 1 way of reproducing this artificially (by forcing a warehouse crash - though don't worry I only did this on my laptop!) so I've closed that loophole.
John
