### ISSUE TITLE
Explore my records - doesn't show all records

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/iRecord#60]
I went onto iRecord to correct a record an expert had noted as incorrect. I was unable to find the offending record in the 'My Records' section as records that are not accepted are hidden. I found this rather frustrating until I figured out what was going on and changed the filter at the top to 'My not accepted or queried records' to reveal it. I was then able to make the changes needed to the determination. I would expect the My records page to show all of my records, regardless of their verification status.

**Comment by kitenetter** [comment]
I suspect this is one of those things where some users would prefer to see all records by default, while others would prefer not to see rejected records by default. Difficult to keep everyone happy. Maybe this type of issue would be more easily resolved by making it easy to search for a record via its ID number, and/or by including a hyperlink to the record in the messages that get sent out?

**Comment by johnvanbreda** [comment]
I'd vote for making the My Records view show all your records. I also wonder if it would be a good idea to add an equivalent tab to the log shown to verifiers, for just your own stuff. 
I agree with the other (separate) sentiments as well.

**Comment by DavidRoy** [comment]
I agree to making the My Record view show all records.

**Comment by johnvanbreda** [comment]
My Records now shows all records.

**Comment by kitenetter** [comment]
Thanks John. In your comment above, what do you mean by "the log shown to verifiers"?

**Comment by johnvanbreda** [comment]
![verifier-log](https://cloud.githubusercontent.com/assets/2392594/16731499/52b44b7c-4770-11e6-84a1-3acfd7b4dd6c.jpg)

**Comment by johnvanbreda** [comment]
We've developed a new tab on the verification page but its not deployed on iRecord yet - it shows the recent verification decisions that match your current filter. See the screenshot above. You can indeed click on rows to set your own decision against the underlying record.

**Comment by johnvanbreda** [comment]
Log tab has been implemented so closing.
