### ISSUE TITLE
Map position and display issues

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#600]
A variety of strange panning and zooming behaviour has been evident since last fix - giving every appearance of some sort of projection problem. @johnvanbreda - could this be a result of recent change to accommodate dynamic map etc?

Here's one way I've found to reliably induce some strange behaviour of this kind. I imagine the root of the problem here is also responsible for the other strange behaviour we've had on zooming and panning (though less easy to reproduce).

- Go to the _Enter a casual record_ form.
- Select OpenStreetMap from the map layer switcher.
- Zoom the map until you're displaying an area in middle of England - similar to image below.

![zoom-issue](https://user-images.githubusercontent.com/9275178/58259770-1e040d00-7d6d-11e9-8727-a7fcb5e4a40a.PNG)

- Refresh your browser - the refreshed form should show OpenStreetMap for the area you zoomed to before. (I'm not sure if the refresh is necessary, but it ensures that internal state is correct for the purpose of this problem reproduction.)
- Use layer switcher to change to OS Leisure - **no map appears** even though OS Leisure should display fine here.
- Change back to OpenStreetMap - all is well.
- Change to Dynamic layer - OS Leisure displays fine.
- Change back to OpenStreetMap - **map is centred in Gulf of Guinea**.

**Comment by johnvanbreda** [comment]
Seems to be fixed by the above commit.
