### ISSUE TITLE
Marine buffer for UK?

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#602]
Investigate the idea of adding a 12 mile buffer around the whole of the UK and Ireland to allow marine filtering. The buffer could have the terrestrial areas removed so that chiefly marine species are retrieved.

**Comment by burkmarr** [comment]
@kitenetter suggests contacting MBA first to discuss.

**Comment by kitenetter** [comment]
Have contacted Matt Arnold at MBA for his views.

**Comment by burkmarr** [comment]
@kitenetter. Any word on this?

**Comment by kitenetter** [comment]
@burkmarr I've had some discussion with Esther Hughes at MBA about this, and we think this is definitely worth pursuing, although it's possible that we may need to go through one or two iterations once verifiers start seeing it in action.

I suggest our starting point should be a set of five boundaries (England territorial sea, Wales territorial sea, Scotland territorial sea, Northern Ireland territorial sea, Republic of Ireland territorial sea), each of which stretches out to 12 nautical miles on the seaward side, and perhaps half a nautical mile on the inland side? These to be added to our layer of 'country' boundaries.

Possible source data is the UK Territorial Sea Limit:
https://data.admiralty.co.uk/portal/apps/sites/#/marine-data-portal/items/2bd3ea1bbdc04e83bb9fb54644723d20?geometry=-17.801%2C52.784%2C9.95%2C57.191

And for Ireland:
https://data.gov.ie/dataset/maritime-limits-irish-baseline

That just leaves the Channel Islands, but our existing country boundaries already include a reasonable amount of sea don't they?

**Comment by burkmarr** [comment]
@kitenetter - what is the thinking behind having these in the country 'layer' rather than having a new type?

Also what about IOM and CIs - I can source the data for these too (I'm getting it all from OSM - oddly enough its more complete than those other sources).

**Comment by kitenetter** [comment]
@burkmarr the thinking was that for some purposes we might want to set up a filter for the terrestrial part of a country and then to add the extended territorial waters to the same filter, I don't think we're able to easily set up filters that include boundaries from two different 'layers'.

Having said that, does it cause problems that the suggested half-mile buffer on the inland side would overlap the existing country boundaries, which already have a three-mile extension seawards don't they?

So if it needs to be in a new 'layer' (is that the right term?) then that's fine. I don't actually have any requests in hand for combining the territorial waters with a terrestrial boundary.

IoM seemed to already be included in the UK Territorial Sea Limit boundary dataset.

The existing country boundaries for the CIs already have quite a wide buffer I think, so no need to do anything for them unless you're aware of a more definitive territorial waters boundary. Also, the inland buffer is less of an issue for islands and probably isn't needed.

**Comment by burkmarr** [comment]
@kitenetter 

I hadn't considered the limitation on combining buffers. If it's possible that people will want to combine these filters as you suggest then I think they will need to go in the same layer. I can't think of any down-sides to doing it. I don't think the overlap will cause a problem - it's not the most efficient of course.  Shall I put in same layer for now then? (I'll do all this on dev first anyway, so you can get a feel for whether or not it's okay.)

If we are to do separate UK countries then IOM will either have to be on its own, excluded or amalgamated with one of the countries. You are right about CIs - the boundary would practically the same. Shall we exclude CI and IoM for now - can always add them in later if asked for?

**Comment by kitenetter** [comment]
I know that overlaps between the VC boundaries have caused problems in the past - is there an issue with indexing across overlapping boundaries?

I have no problem with putting these new territorial sea ones into their own layer if that will avoid potential problems. 

I think it is simplest for now to include IoM in the England territorial sea boundary - I have no requests for filtering IoM records separately, and hopefully this won't offend anyone if we combine it - it make no sense to treat it separately from a biological point of view.

Agree to exclude CI for now.

**Comment by burkmarr** [comment]
@johnvanbreda - what's your view on where to put these new objects for filtering? If there is a problem with overlaps as Martin suggests, then I guess it's best to put them into a new location type.

**Comment by BirenRathod** [comment]
@burkmarr 
put them into a new location type would be an ideal things to do.

**Comment by johnvanbreda** [comment]
Just picking this up so a few points going over the conversation:
* The only reason why you can't combine the boundaries from multiple layers in a filter is because the UI is coded to clear the selection when you switch layer. That seems like a small enough change to the code which would be preferable to muddling up different types of polygons into the countries layer.
* The Channel Islands boundaries already include territorial waters.
* There is no problem with overlaps any more. Indexing is now done into a single array of location_ids which can hold any list of IDs. We had problems before when we tried to pick a single ID for each type so we could store it in an indexed column - a grid square overlapping 2 boundaries could only be in one which was a pain. 
* I have a hunch that combining the IoM into the English territorial sea boundary could be insulting to some - see https://www.gov.im/about-the-government/departments/infrastructure/harbours-information/territorial-seas/. The UK 12 mile territorial waters specifically excludes the IoM waters (https://www.researchgate.net/figure/Map-of-the-UK-territorial-waters-and-continental-shelf_fig2_265153064). 

So, my vote is to have a territorial waters location type which is added to the spatial indexing. This can initially have England, Scotland, Wales, NI. We can add IoM, Jersey & Guernsey (which are separate I think) if needed later.

**Comment by kitenetter** [comment]
I was basing the inclusion of IoM on this 12 mile dataset:
https://data.admiralty.co.uk/portal/apps/sites/#/marine-data-portal/items/2bd3ea1bbdc04e83bb9fb54644723d20?geometry=-11.237%2C53.931%2C2.639%2C56.134

However, I have no problem with keeping it separate, that gives us more options if the issue arises in future. I would like IoM to be available from the start, alongside England, so we can combine them for the MBA verifiers.

**Comment by johnvanbreda** [comment]
I won't get into an argument with the Admiralty but isn't that map wrong?!!
See https://www.gov.im/about-the-government/departments/cabinet-office/external-relations/constitution/

**Comment by burkmarr** [comment]
@johnvanbreda Can't both be right! On dev warehouse I've created a new location type called 'Country territorial waters'. To add that to spatial indexing, do I add it to the $config['location_types'] array in modules\spatial_index_builder\config\spatial_index_builder.php? And what about specifying that it is to appear in the location types drop-down list in filtering - where is that configured?

**Comment by johnvanbreda** [comment]
@burkmarr Yes to the first question about adding to $config['location_types'].
Each page that has a filter builder on it has a configuration for the indexed location types, pointing to an array of location type IDs. It's normally found in the user interface configuration bit - let me know if you can't find it.
We also need to update Elasticsearch's lookup files with all these new spatially indexed locations (see https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/README.md#prepare-the-lookup-for-location-data).

**Comment by burkmarr** [comment]
@kitenetter I've added a new location type (=layer) on the dev warehouse - Country territorial waters - and populated it with the GIS data I created. This is what I did:

- Where possible I took the boundaries of the territorial waters from the two data sources Martin pointed to above.
- Where these were insufficient, e.g. delineation between UK countries, I used, where possible, vector data downloaded from OSM (tags - maritime=yes and boundary=administrative) to guide me.
- Sometimes even these were insufficient, e.g. boundary between England and Wales in the Bristol channel were missing, so I traced the relevant line from the OSM raster coverage (I don't know why these data didn't come with the downloaded vector data - perhaps tagged differently).
- For the landward side, I created a negative half mile buffer of UK - as suggested by Martin - from the Natural Earth layer ne_10m_land_uk (https://www.naturalearthdata.com/downloads/10m-physical-vectors/).

@johnvanbreda I've added this new layer to spatial indexing on the dev warehouse and also added the layer id (15522) to the two iRecord forms 'explore my records' and 'explore all records' so we should be able to use them as filters. However, although I can select the relevant polygons okay, using as filters on 'explore all records' is not returning any results for me (time period set to last 12 months). 

Adding the six polygons (via the Warehouse GUI) created six task_spatial_index_builder rows in the work queue which appeared to run successfully to completion when I ran them manually (index.php/scheduled_tasks?tasks=work_queue). However, the following query returns no results which either means I'm not understanding what the spatial indexing does, or it didn't work:

`select * from cache_occurrences_functional
where location_ids && ARRAY[223800, 223798, 223799, 223797, 223796, 223795]
limit 100`

The array contains the IDs of the six country territorial waters locations.

**Comment by johnvanbreda** [comment]
@burkmarr I think the new country territorial waters layer name is missing from $config['location_types'] in the spatial index builders' config file?

**Comment by burkmarr** [comment]
@johnvanbreda - on dev it's in modules\spatial_index_builder\config\spatial_index_builder.php. Is that the right config file? (I inserted it after country, not at the end.)

**Comment by johnvanbreda** [comment]
Hmm, that's weird, I can't see it and the behaviour I see is consistent with it not being in the config. You do mean the machine with IP address 192.171.199.237, in the file d:\websites\warehouse\modules\spatial_index_builder\config\spatial_index_builder.php, under the setting $config['location_types']?

**Comment by burkmarr** [comment]
@johnvanbreda - I've just noticed that my save failed! Now I've retried as admin and I think it's done it! I'll do the indexing again.

**Comment by burkmarr** [comment]
@johnvanbreda I can't get the spatial indexing tasks in the work queue to complete. Running index.php/scheduled_tasks?tasks=work_queue seemed to do something first time round, but the tasks are still in the work queue. Running the work_queue scheduled tasks again just returns immediately. Is this because the tasks have already be 'claimed'? What is the meaning of the claimed_on and claimed_by columns in the work_queue?

**Comment by johnvanbreda** [comment]
When a scheduled tasks run calls the work_queue, it creates a GUID. Then, before each task type does any actual work on the queued tasks, it fills in the claimed_by field with that GUID and the claimed_on. This means that if you ran multiple work queue processes simultaneously, they would each claim different tasks and not get in each other's way. 
If you run the tasks via the browser, PHP is limited to a 5 minute execution and then times out. Any queries already running will still complete though. The scheduled tasks are normally run via PHP.exe from Windows Scheduler which doesn't have this limit. As it can take an hour or so to re-index a complex spatial boundary, the 5 minute limit is no way near enough. So your tasks were left claimed but not completed and therefore another attempt would skip the already claimed tasks.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - that's very clear. @BirenRathod - can you set up scheduled tasks on the dev warehouse?

**Comment by BirenRathod** [comment]
@burkmarr 
The scheduled task has been already setup. sorry bit late response top this.

**Comment by burkmarr** [comment]
Thanks @BirenRathod. @kitenetter - records have been indexed against these areas now so you can try out the filters on dev when you have time. I'll wait for the nod from you before adding them to the live site.

**Comment by kitenetter** [comment]
@burkmarr have tried this out on the dev iRecord and it is looking good. At the moment Wales appears to be duplicated - there are two apparently identical boundaries labelled "Wales" and "Wales Territorial Waters".

I will forward a screenshot to MBA to see if they have any comments before we go live.

**Comment by burkmarr** [comment]
That was a mistake - 'Wales Territorial Waters' is deleted now. If you prefer the names to have 'Territorial Waters' in them, we can do that when I upload them to live Warehouse.

**Comment by burkmarr** [comment]
@kitenetter - can you remind me where the we are at in our conversation with MBA on this?

**Comment by kitenetter** [comment]
@burkmarr MBA got back to us querying a few points, to which you suggested potential solutions, but we've not heard back since then (emails on 27-28 August). I will chase.

**Comment by burkmarr** [comment]
@kitenetter - no worries. I was only asking because I saw that it was on September milestone.

**Comment by kitenetter** [comment]
MBA are happy to proceed on this basis:
1. We implement the new 12nm boundary for all MBA verifiers
2. We retain the “all marine species in all locations” filters for those who wish to have them (e.g. to pick up records beyond the 12nm limit)
3. If needed taxon-specific filters can be set up to cover particular taxa of interest

Next step is for me to review the current list of marine verifiers and edit their filters accordingly.

**Comment by kitenetter** [comment]
Yes please @burkmarr

**Comment by burkmarr** [comment]
@kitenetter - those are now added to the live warehouse and have been spatially indexed so are available for filtering. I've added the location type id - 17484 - to the  indexedLocationTypeIds parameter on both the 'explore all records' and 'explore my records' forms, so they are available for filtering from those forms. 

```@indexedLocationTypeIds=[15,1370,2188,1103,2187,5702, 17484]```

If you want them to be available for filtering from any other forms, you need to add the id for those too.

@johnvanbreda - in a previous comment, you mentioned about updating the ES logstash config:

> We also need to update Elasticsearch's lookup files with all these new spatially indexed locations

Do you want me to do that or will you? If the former, can you tell me where the logstash is configured?

**Comment by johnvanbreda** [comment]
Hi @burkmarr I'll do this but will make precise notes for you...

**Comment by burkmarr** [comment]
Thanks @johnvanbreda.

**Comment by burkmarr** [comment]
Many thanks @johnvanbreda - very useful.

**Comment by kitenetter** [comment]
Now functioning on live website, thanks. Next part of the task is for me to review and update our marine verifiers' filters. Will transfer that to a new issue - closing this one.
