### ISSUE TITLE
Add seaward extension to Eire and NI and edit NI boundary

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#603]
Both Eire and Northern Ireland need a seaward extension adding (three-mile extension for British countries). Boundary for NI also needs correcting in the Londonderry/Derry region. Northern Ireland boundary has some of the eastern loughs cut out of the boundary - these to be included, along with the seaward extension.

**Comment by burkmarr** [comment]
Linked to closed issue https://github.com/BiologicalRecordsCentre/iRecord/issues/465

**Comment by burkmarr** [comment]
Uploaded new boundaries via Warehouse location upload interface without apparent problems - new boundaries now available for filtering on live iRecord site. Summary below of how the boundaries were created is below.

## Northern Ireland
* buffered existing NI boundary to three nautical miles (to be consistent with GB country boundaries)
* sourced correct Derry/Londonderry boundary from OSNI Largescale County Boundaries dataset and merged with new layer to extend it around Derry/Londonderry
* cut the new layer so that it doesn't overlap Eire boundary
* manually edit buffered boundary to prevent it crossing into Eire international waters as represented on OSM backdrop
## Eire
* buffered existing Eire boundary to three nautical miles
* cut the new layer so that it doesn't overlap with new NI layer (which sorts out both the Derry/Londonderry and international waters issue.

**Comment by kitenetter** [comment]
@burkmarr I've just been setting up a verification filter that needs to include Eire but it isn't appearing in the countries list for the 'Where' filter.

**Comment by burkmarr** [comment]
I'm at a loss to explain this. I'm sure it was there when I closed this issue. The form uses the location type code 2188 to specify country locations. The screenshots below shows that Eire belongs to this type:

![iss-countries-type](https://user-images.githubusercontent.com/9275178/63102817-bb896a00-bf73-11e9-99c2-a5dc9921206e.PNG)
![iss-countries](https://user-images.githubusercontent.com/9275178/63102821-bdebc400-bf73-11e9-92e6-144554e563b6.PNG)

But it isn't being returned by the Ajax query when I type in E to the filter searchbox - only England is returned. @johnvanbreda below is the body of the query and the result - do you have any idea what might be going on? If not, how do I work out which part of the Indicia codebase deals with the services/data/location endpoint?

```
https://warehouse1.indicia.org.uk/index.php/services/data/location?callback=jQuery183032229894864521547_1565879487267&q=e&unsimplified=e&limit=21&timestamp=1565879546605&orderby=name&mode=json&qfield=name&auth_token=f7cf541662cf92c80ade690fc192a93119cf1eca&nonce=374e5b101ed7ff154f8eb2ccf631b380fc9a9ac7&view=list&location_type_id=2188&_=1565879546606
```
```
jQuery183032229894864521547_1565879487267([{"id":"1605","name":"England","code":"E92000001","centroid_sref":"52.62865N 1.46538W","website_id":null,"location_type_id":"2188","parent_id":null}])
```

**Comment by johnvanbreda** [comment]
The Eire location was linked to the ABLE website (ID 118) so not publically available. I removed the appropriate locations_websites join record and it now appears.

**Comment by burkmarr** [comment]
@johnvanbreda - thank you.
