### ISSUE TITLE
General review of Vice County boundaries 

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#604]
Cross-check iRecord VC boundaries against NBN VC boundaries (3-mile extension) to ensure that there are no further discrepancies.

**Comment by burkmarr** [comment]
Flannan Isles are missing the NBN (and iRecord) VC boundaries, and should be included within VC110 Outer Hebrides (https://www.cucaera.co.uk/grp/?refs=NA7246&map=ordnance_1920s&vcs=true&graticule=false&nsgrids=false&zoom=11&lat=58.27773158812952&lon=-7.551040649414063&distinct=false&history=false&bedrock=false&superficial=false&sketches=).

**Comment by burkmarr** [comment]
Other possibly unresolved errors in the NBN VC boundaries have been addressed by Jerry Clough:
https://forums.nbn.org.uk/viewtopic.php?id=4319

**Comment by kitenetter** [comment]
@burkmarr just wanted to flag up that when the VC boundaries do get updated on the live site we need to ensure that they don't trigger a new "date_updated" value on the records, see #612 and #516

**Comment by burkmarr** [comment]
Okay @kitenetter - noted.

**Comment by burkmarr** [comment]
Updated the BRC VC layer repository to include Flannan and Lady Isles - https://github.com/BiologicalRecordsCentre/vice-counties. Next step is to compare the 3 nm buffered layer from the repository with the Wastonian VC location polygons we currently have in the Warehouse and update where they differ.

**Comment by burkmarr** [comment]
The following VC boundary (3 nm buffer) locations need updating in the Warehouse:

- 110 Outer Hebrides to incorporate lots of missing islands.
- 100 Ayrshire to incorporate Ailsa Craig and Lady Island.
- 45 Pembrokeshire to incorporate Grassholm and The Smalls.
- 1 West Cornwall to incorporate the Scilly Isles.

I intend to update these 4 location polygons on the Warehouse, from the updated 3 nm layer in the BRC repository (https://github.com/BiologicalRecordsCentre/vice-counties), using the standard Warehouse upload interface (http://warehouse1.indicia.org.uk/index.php/location). I will do it first on Dev Warehouse when that is updated. If there are no problems I will go ahead and do on the main Warehouse. Let me know if you have any concerns @kitenetter @johnvanbreda.

**Comment by johnvanbreda** [comment]
I've no concerns as long as they are tested on dev first. There will be a small performance hit whilst they are re-scanned (sometime during the half hour period after you update the locations).

**Comment by burkmarr** [comment]
These four location boundaries uploaded on dev Warehouse without problems so also updated live Warehouse, also without problems. So these new location boundaries available for filtering etc.
