### ISSUE TITLE
Seaward extension of Irish VCs

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#605]
A three mile seaward extension of the Irish VCs is required to facilitate inshore filtering.

**Comment by burkmarr** [comment]
Sources:
https://github.com/SK53/Irish-Vice-Counties/tree/master/vice_counties (from Jerry Clough, aka SK53)
Background info at: http://sk53-osm.blogspot.com/search/label/Praeger

**Comment by burkmarr** [comment]
Subject to confirmation of the status of the Dingle Peninsula, these are ready for uploading.
![image](https://user-images.githubusercontent.com/9275178/68753197-83d6a080-05fc-11ea-96c1-d5ce587e8470.png)

**Comment by burkmarr** [comment]
@johnvanbreda - is it safe to update these Irish VC boundaries in one go, or should I do it in small batches to mange the number of large spatial indexing jobs in the work queue?

**Comment by johnvanbreda** [comment]
I think I'd prefer to see them trickled through in a managed way, but you could do this by changing BATCH_SIZE in the task_spatial_index_builder_location.php temporarily to a lower number (e.g. 2) so it only processes a couple at a time?

**Comment by burkmarr** [comment]
Okay John I'll do that. I'll post a comment here when I've changed the batch size and uploaded them and then again when they've (hopefully) finished and I've reset the batch size.

**Comment by burkmarr** [comment]
@johnvanbreda @BirenRathod I've just updated the Irish VC's so there are now task_spatial_index_builder_location entries in the work_queue for these. As John suggested, I've temporarily cofigured the BATCH_SIZE to 2 for the location spatial index builder. I'll keep an eye on the work_queue over the few days to see how these tasks fare.

**Comment by burkmarr** [comment]
@johnvanbreda @BirenRathod The work_queue tasks for this have cleared without problem and I've reset the BATCH_SIZE to 100 for the location spatial index builder.

**Comment by BirenRathod** [comment]
@burkmarr 
Well done, Thanks for the info.
