### ISSUE TITLE
Investigate implications of removing Yorkshire & Sussex composite VCs

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#606]
Every record that falls within one of the Yorks or Sussex VCs gets linked to both the individual VC and the aggregated VC, so the the “VC” column in the data download becomes  messy and enforces a data-cleaning operation that costs more than it is worth.

Possibly linked to some record display problems, e.g. BiologicalRecordsCentre/iRecord: Issue #444

Need to investigate whether these aggregated VCs have been used for anything critical within other Indicia-linked systems. They seem to have been purged from our verification filters.

**Comment by burkmarr** [comment]
Possible linked issue which was previously closed: BiologicalRecordsCentre/iRecord: Issue #242

**Comment by johnvanbreda** [comment]
I think #242 got closed because one of the 2 underlying issues was fixed, but not this one so it is good that it is being picked up. Just for your background info - originally we could not support a report filter that had multiple locations, so verifiers which worked on Sussex and Yorkshire needed a single polygon that combined the constituents into 1. This is no longer needed.
As well as removing the 2 locations, there are a few things to make sure of:
1. cache_occurrences_functional.location_ids is an array of IDs which may contain references to these IDs which can be stripped out.
2. as above, but for cache_samples_functional.location_ids.
3. Elasticsearch should self-update if you do the above.
4. Any report filters which contain these IDs in their definition's indexed_location_list will need to be handled (e.g. by replacing with the ID with the list of constituent IDs). Note that older filter definitions may call this parameter indexed_location_list.
5. In quite a few reports there is code which excludes the combined vice counties. This is normally done by an SQK filter such as `l.code not like '%+%'` because the location code was a combination of the VC numbers joined by +. This code can all be simplified as these filters are not required anymore, but won't break anything if left alone.

**Comment by kitenetter** [comment]
On the new verification page I'm currently seeing records that appear to be allocated to "Yorkshire" but not to any single Yorks VC:

![image](https://user-images.githubusercontent.com/16039111/58767583-54b7ff80-8585-11e9-8b5e-2196f1a6eff2.png)

Not sure if that is just a display issue - needless to say I would prefer to see the correct single vice-county rather than the aggregated version.

**Comment by DavidHepper** [comment]
BDS have different recorders for most Yorkshire VCs.
Also odd that 63 is duplicated in the screenshot above, whereas 64 (Mid-W Yorks) is absent.

**Comment by johnvanbreda** [comment]
This issue will tidy the Elasticsearch data when it is fixed. I've added a temporary fix so the new verification page doesn't use any vice county with a + in the code.

@DavidHepper The duplication of 63 is a typo somewhere along the line, just in the code, not the actual boundary. As these are set to be removed there is no additional action required.

**Comment by burkmarr** [comment]
The query below can be used on the Warehouse to list filters that have reference a specific location boundary. Running it against Yorkshire (16218) and Sussex (16217) shows only a small handful of users with filters referencing those boundaries. So if we do remove these boundaries, we could easily individually email these people to let them know that those filters would no longer work.
`
set search_path=indicia;
select p.first_name, p.surname, p.email_address, definition::jsonb->'indexed_location_list' as filter_indexed_location_list
from filters f
join filters_users fu on f.id = fu.filter_id
join users u on fu.user_id = u.id
join people p on u.person_id = p.id
where definition ~* '"indexed_location_list":"([0-9]+,)*16218(,[0-9]+)*"'
`

**Comment by burkmarr** [comment]
The query below can be used on the iRecord Drupal DB to list users that have listed a specific location in their user preferences. Running it against Yorkshire (16218) and Sussex (16217) gives 297 and 129 users respectively.
`SELECT l.field_location_value, fn.field_first_name_value, sn.field_last_name_value, u.mail 
FROM users u 
LEFT JOIN field_data_field_first_name fn ON u.uid = fn.entity_id 
LEFT JOIN field_data_field_last_name sn ON u.uid = sn.entity_id 
LEFT JOIN field_data_field_location l ON u.uid = l.entity_id 
WHERE l.field_location_value = 16217`

**Comment by burkmarr** [comment]
With reference the previous comment on filters that reference these boundaries, I've just realised that @johnvanbreda already proposed a way of dealing with filters that reference these boundaries in indexed_location_list.

**Comment by burkmarr** [comment]
@kitenetter @DavidRoy @johnvanbreda. I am proposing to move this forward by using the dev warehouse to test the workflow and impact of deleting the two aggregate vice counties (I'll just do one to start with). This is what I propose:

1. Delete the 'Sussex' location (ID 16217) via the dev warehouse interface.
2. Insert a 'task_spatial_index_builder_location_delete' task in the work queue against the deleted feature to update the cache_occurrences_functional and cache_samples_functional table.
3. Run the work queue scheduled task.
4. Use Pgadmin to manually update the few filters that reference the location 16217, replacing with the two Sussex VCs (replace '16217' with '735,736' in the filters.definition JSON.
5. In dev iRecord clear the Indicia cache (see below).

Then I can check that there is no serious impact on users who referenced Sussex (16217) in iRecord either with filters or as their default recording location. Whilst there are only seem to be a few using it in filters, many more have it as their defaut recording location. I already carried out a test on dev to explore the impact where that is the case:

- Created a new VC, spatially indexing it.
- Used this as my default recording location in iRecord.
- Deleted the VC on Warehouse and ran cache update via work queue as described above.
- Logged back into iRecord.

When I did this, going into 'My account' was fine - my preferred recording location had been removed and there were no ill effects. But in explore records, the boundary of the deleted VC was shown on the map and iRecord was 'hanging' apparently trying to retrieve records from the Warehouse (the location by now not being indexed of course). However, I was able to fix this by clearing the Indicia cache on iRecord. After I did that the boundary was not shown when I went into explore records and all seemed well.

Let me know if you have any concerns about this proposal.

**Comment by johnvanbreda** [comment]
@burkmarr Point 2 should not be needed if you do the delete via the warehouse UI.

Technically I think this is fine, there is just the "political" consideration that users who use Sussex as their default boundary will no longer be able to.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I did wonder about the need to manually add to work_queue.

This is one for you I think @kitenetter:
> there is just the "political" consideration that users who use Sussex as their default boundary will no longer be able to.

**Comment by kitenetter** [comment]
Re the politics, what we are proposing just means that users in Sussex will now be in the same position as users in, say, Hampshire - i.e. they will not be able to choose something that matches the modern county boundary.

The only way of avoiding that is to extend the user account functionality so that users can choose from a wider range of boundary types, just as they can when setting up filters in "Explore". If it is simple to give some additional choices (probably just adding the LERC boundary and BC Branch boundary options) to the user account page then I would support that, but if this is very time-consuming to do it can't be a priority. (Or to allow users to select multiple VCs.)

Otherwise, I think we have to go ahead. For those uses with "Sussex" as their default recording location, can we swap that to just "East Sussex" (or West Sussex!) so that they don't lose a geographical focus altogether?

How many users are we talking about whose user account settings would be affected?

**Comment by johnvanbreda** [comment]
@kitenetter you are correct, this just relegates Sussex users to the same as everyone else. I would argue actually for dropping the selection of preferences in the user's account in the current fashion and instead advocate for a move to allowing a user to save a "favourite" filter (which perhaps could be set in the edit profile page but would also be available in the normal Explore pages). That would allow much more fine grained control than the setup, e.g. you might only be interested in a local SSSI boundary. Appreciate this is just an idea for the future though, but it means I'd be a bit reticent about doing too much work on the existing profile page, especially as it is Drupal 7.

**Comment by burkmarr** [comment]
@kitenetter 
> How many users are we talking about whose user account settings would be affected?

I haven't got SQL access to the live Drupal DB, but on dev the figures are Sussex 97 users and Yorkshire 196 users.

If we update the Drupal MySQL DBs so that users reference a different VC, what Yorkshire VC would you like to switch them too?

@BirenRathod - is it okay for me to install SQLyog on the MySQL server for the live iRecord site?

**Comment by kitenetter** [comment]
@burkmarr for Yorkshire I'm going to dictate VC64, Mid-west Yorkshire, on the grounds that it is (kinda) in the middle. We could email all the affected users, but I think my preference is to put a notice in the forums and then to respond to any enquiries we get following the change, with the long-term aim of moving towards John's suggestion of allowing a "favourite" filter to be used for this purpose.

**Comment by burkmarr** [comment]
@kitenetter. Thanks to some help from @BirenRathod I just looked at this on live iRecord Drupal DB. Just limiting searches to users who have logged in in 2019, there are 59 who use Sussex and 136 who use Yorkshire.

@johnvanbreda - I'm hoping that I can use SQLyog to directly swap the values acccording the Martin's preferences in the `field_data_field_location` table (Sussex to East Sussex, i.e. 16217 to 736 and Yorkshire to Mid-west Yorkshire, i.e. 16218 to 684) when the time comes. Do you see any issue with that? Would it be necessary to enter rows in the `field_revision_field_location` table?

**Comment by johnvanbreda** [comment]
Hmm, I'm not entirely confident, but I think you don't need to make multiple revisions. However, you should update both the field_data_* table value and the equivalent in field_revision_*.

**Comment by burkmarr** [comment]
Thanks John - seems right to me.

**Comment by burkmarr** [comment]
Here's a revision to my proposed plan for testing this on the Dev Warehouse in light of subsequent comments. Let me know if you have any concerns or further comments @kitenetter, @johnvanbreda, @BirenRathod & @DavidRoy:

1. Delete the 'Sussex' location (ID 16217) via the dev warehouse interface.
2. Run the work queue scheduled task.
3. Use Pgadmin on the dev warehouse DB to manually update the few filters that reference the location 16217, replacing with the two Sussex VCs (replace '16217' with '735,736' in the filters.definition JSON.
4. In dev iRecord clear the Indicia cache.
5. Use SQLyog on the iRecord_dev Drupal DB to manually update user's location prevereces so that those that referenced VC 'Sussex' (16217) now reference 'East Sussex' (736)  by updating the records in the field_data_field_location and field_revision_field_location tables for those users.

Then I will check that the modified filters work and that all is well for users with modified location preferences. If all is good repeat for Yorkshire. If all is well for that, touch base with everyone to schedule a time to do on live warehouse and irecord.

**Comment by DavidRoy** [comment]
Sounds good to me, thanks

**Comment by burkmarr** [comment]
@kitenetter, @johnvanbreda, @BirenRathod & @DavidRoy. I've carried out the above steps on dev for both Sussex and Yorkshire and all appears well - filters and user preferred locations updated okay.

I'll aim to repeat on the live warehouse and iRecord website DB tomorrow PM. Let me know before then if you have any concerns.

**Comment by johnvanbreda** [comment]
Sounds good to me as well, thanks @burkmarr.

**Comment by burkmarr** [comment]
I'll go ahead with this on the live warehouse & iRecord today then.

**Comment by burkmarr** [comment]
@kitenetter - fake VC's Yorkshire and Sussex are now gone on live Warehouse and iRecord. I'll leave the issue open for a while in case there are unforseen repercussions.

**Comment by DavidHepper** [comment]
An export from Martin around 20/11 still contains Yorkshire and Sussex composites. These are causing me grief when trying to filter by VC using SQL. Would now be a good time to remove them, please?
Example: ID = 1015054 contains 'VC number' = "61; 61+62+63+63+65"

**Comment by burkmarr** [comment]
I thought I had deleted the composite VCs via the ORM and that this would take care of the re-indexing. Either I didn't do it that way, or it doesn't do it. I'll enter jobs in the work_queue to take care of it. It might take a short while to update the occurrences/samples.

**Comment by burkmarr** [comment]
It looks like I did it for Sussex, but not Yorkshire. The task for Yorkshire is now in the work queue, so it should be sorted soon.

**Comment by burkmarr** [comment]
That looks to be fixed now @DavidHepper.

**Comment by burkmarr** [comment]
Can we close this issue now @kitenetter?

**Comment by kitenetter** [comment]
This seems to be resolved thanks. Closing.

**Comment by kitenetter** [comment]
@burkmarr I thought the Yorkshire problem was resolved, and it is true that the aggregated county is no longer being displayed in verification view on the website. However, people downloading records for Yorkshire are still getting a VC column that includes the unhelpful "61+62+63+63+65". Is there another piece of the jigsaw that needs to be sorted out to prevent this ending up in the downloads?

As far as I can the aggregate county is not being included in the new ES downloads, so maybe we don't need to spend time fixing the problem for the existing downloads, but if it is easy to fix it is probably worth doing. If it is complicated then please close this issue again and we'll focus on the ES download instead.

**Comment by kitenetter** [comment]
I haven't seen any recent examples of the aggregated "61+62+63+63+65" numbering for Yorkshire. However, Yorkshire is still offered as an option in the vice-county picker as part of the "Where" filter on the Explore and Download pages. Can it be removed from that list? If chosen, no records are displayed/downloaded.

**Comment by burkmarr** [comment]
http://warehouse1.indicia.org.uk/index.php/location/edit/16218

@johnvanbreda - I thought that if I unchecked the box which makes this a publicly accessible location (and left the iRecord website unchecked) then this location would not appear in the VC lists e.g. on the explore page. However I didn that and it still appears in the VC dropdown on the iRecord explore page - even after I've cleared the Indicia cache. 

Is the only option to remove this pseudo-VC from the list to delete it?

**Comment by johnvanbreda** [comment]
I guess the filter being used to select the locations is just "all locations of type x", so one option might be to change the location type?

**Comment by burkmarr** [comment]
Good idea @johnvanbreda - I changed it to the type 'unknown'. @kitenetter - this is no longer a VC so will not appear in lists of vice counties. In the unlikely event that there is an outcry (or some other unforeseen consequence), I can change it back.

**Comment by kitenetter** [comment]
Thanks - closing.
