### ISSUE TITLE
Query over taxon filtering on xylem insects form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#608]
The form for the xylem-feeding insects survey is:
https://www.brc.ac.uk/irecord/xylem-feeding-insects

That form uses taxon filter items to restrict the taxa that can be added to the survey:

![image](https://user-images.githubusercontent.com/16039111/58484490-0e643a00-815a-11e9-960c-72ac3ff44eb8.png)

However, we are receiving records via that form of additional taxa that are not in the above list. Two examples:
- https://www.brc.ac.uk/irecord/record-details?occurrence_id=10228873
- https://www.brc.ac.uk/irecord/record-details?occurrence_id=10230358

I cannot find any way of adding these taxa to the form myself.

**Comment by johnvanbreda** [comment]
I've managed to reproduce this by entering a name from the list, then editing it in the grid cell. The editing search does not seem to pick up the correct filter so I'll look into that now.

**Comment by johnvanbreda** [comment]
Fixed.
