### ISSUE TITLE
Remove unhelpful vernacular name

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#609]
More fallout from the xylem insects survey. If you type in the word "spittle" to our recording forms, all you are offered is the non-UK species _Aphrophora gelida_ = Boreal Spittlebug. We are currently getting a lot of records for that species.

Can we mark the vernacular name "Boreal Spittlebug" as unavailable for data entry, or does that cause any problems elsewhere in the system?

**Comment by kitenetter** [comment]
The unwanted name "Boreal Spittlebug" has cache_taxa_taxon_lists.id = 59025

That points to the preferred name _Aphrophora gelida_ which has cache_taxa_taxon_lists.id = 59024

**Comment by johnvanbreda** [comment]
I've done this as a temporary measure. The first query below changes the core taxonomy data held in the warehouse. The second query just forces through removal of this name from the search cache table so the effect is instant (this would happen shortly anyway via the scheduled tasks):
```sql
update taxa_taxon_lists set allow_data_entry=false, updated_on=now(), updated_by_id=3 where id=59025;
delete from cache_taxon_searchterms where taxa_taxon_list_id=59025;
```

BUT, this is a temporary fix. Any future update from UKSI will overwrite this change as Boreal Spittlebug is a valid common name in UKSI. 

@kitenetter have you changed the form recently though? I can't even select Aphrophora gelida so it looks to me like the list of species you can select from has changed? Wasn't the correct solution here to just alter the list of taxa_taxon_list_ids in the filter on the form?

Another thought is that we might consider adding the common name Spittlebug for family Aphrophoridae (which I think the UK species of interest all are in). Chris may not like this as technically spittlebugs are a wider group of families.

**Comment by kitenetter** [comment]
I think there is probably a bigger issue here to do with how recording forms for public participation surveys are set up. For this type of survey we really need a more customised taxon list that matches the names that people are likely to use (including the ones given on the survey ID guides), and then subsequently links them back to UKSI.

I think we are able to do that within the existing species dictionary functionality aren't we? (Although I'm not sure of the steps involved.) However, it depends on public participation surveys being given adequate time and resources to set up, which hasn't been the case here.

I'll close this issue.

**Comment by johnvanbreda** [comment]
Several possibilities here:
* As you've found, you can limit the existing names in UKSI using a taxa_taxon_list_id filter (or one of the other filters). That means you should be able to reduce the list available to a short list of target species and could exclude an unwanted common name if required.
* You can create your own lists on the warehouse and import a CSV file containing exactly the names you want. If the external keys are set to preferred name TVK, then the links to UKSI should be OK. Ideally you also need the correct taxon group for verification filtering. This approach lets you completely control the exact names available for selection.
* I could envisage being able to limit a search against UKSI to the species on a scratchpad. That's an enhancement, but maybe not too tricky to implement. Then setting up lists of names would be easy.

**Comment by johnvanbreda** [comment]
See https://indicia-docs.readthedocs.io/en/latest/site-building/warehouse/taxon-lists.html for guidance on creating your own lists.
