### ISSUE TITLE
Records with non-functional location coordinates

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#611]
This has been reported by the RHS slug survey verifier, but applies across the board to records originating from several of our survey forms. Quite a lot of these come from the xylem-insects form, but also from iRecord general.

The slug survey has received a number of records that have the coordinates 89.996N, 15.952W. Here is one example:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=10126081

On the new verification page, clicking on one of these records causes the page to generate an error message:

![image](https://user-images.githubusercontent.com/16039111/58639106-35537500-82ee-11e9-88f1-696f6d35d119.png)

The location is displayed on the verification page as being at the top border of the global map:

![image](https://user-images.githubusercontent.com/16039111/58639169-561bca80-82ee-11e9-82f2-1de213991af5.png)

However, on the record page linked to above, the location map is showing part of southern Scotland.

My guess is that because the location is 'off the map' it is causing elasticsearch to fail. But why are we getting so many records from so many different sources at this exact same nonsensical location? (These can be found from Explore - All records, and then adding "89" in the filter box at the top of the grid ref column.)

Is this a problem that arises if the map display fails to update quickly enough before the records get saved?

**Comment by johnvanbreda** [comment]
This is likely to be related to the new map layer switching code I think. It is going to be much easier to fix if we can work out a way of reproducing it. Tagging @burkmarr.

**Comment by johnvanbreda** [comment]
I've not managed to reproduce it here.

**Comment by kitenetter** [comment]
So far I can't reproduce it either.

**Comment by burkmarr** [comment]
I'll give it a go.

**Comment by kitenetter** [comment]
The earliest example I can find is of a bumblebee that looks like it was seen in California, entered on 25 April 2019:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=9868735

There are then somewhere between 500 and 600 records from early May onwards, using a variety of entry forms.

**Comment by johnvanbreda** [comment]
I think the 25th April example is a different issue. The ones from early May onwards seem much more likely to be caused by the new dynamic map layer code.

**Comment by burkmarr** [comment]
I got it to go once - I was positioned over UK bu the lat/lng shown in the map's task bar was 89 north etc and when I clicked on map, that was the recorded position. Can't do it a second time though. I'll keep trying.

**Comment by johnvanbreda** [comment]
@kitenetter has discovered this issue is incorrect behaviour of the FindMe button when using the dynamic layer.
