### ISSUE TITLE
Odd map display on activity recording form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#613]
This form is used for a Natural England National Nature Reserve:
https://www.brc.ac.uk/irecord/ne-list-records?group_id=1143&implicit=

(you may need to join the activity to be able to see that page)

On the second tab of the form, the map is getting squeezed over to the left, and is zoomed out a long way from the reserve boundary:

![image](https://user-images.githubusercontent.com/16039111/58716193-600dfe00-83c0-11e9-9f1c-e5348e412f41.png)

Any suggestions for what might be causing this?

**Comment by burkmarr** [comment]
What is the name of the activity @kitenetter?

**Comment by kitenetter** [comment]
It's under the NE organisation, so you have to go to Activities - Organisations offering activities, then find Natural England and click on View centres, then find National Nature Reserves and click on View centre activities, then find "NNR: Fenn's, Whixall & Bettisfield Mosses" and click on Add a list of records.

Alternatively, just go to the "Browse all activities" tab and use the search box to look for "Whixall" or similar.

**Comment by kitenetter** [comment]
P.S. this form started off as a clone of the standard iRecord add a records form, and as far as I know has not been edited recently. I don't know when the map display went wrong, I've only spotted it today while using that activity as a demo.

**Comment by burkmarr** [comment]
Somehow it had been edited ad that tab was turned into a three column display (by using | twice) so I removed one of the '|' characters to make it two columns. Now map and overall comment are together in the right-hand column and all looks okay. I don't know if that comment is where you want it though - you might prefer it in the left-hand column.

**Comment by burkmarr** [comment]
P.s. it looked weird because it couldn't all fit in a three column display.

**Comment by kitenetter** [comment]
Thanks @burkmarr - as usual I'm a little mystified as to why this form had changed, but it's fine again now (I've moved the comment box to the left as you suggested).
