### ISSUE TITLE
Make iRecord content list searchable

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#614]
This is an issue for admins only. The list of content at https://www.brc.ac.uk/irecord/admin/content can be filtered by content status and type but that has limited effect on what has become a very long list.

Can we add a search box of some sort to allow for filtering by the page title wording? For example, I need to check which data entry forms we currently have set up for bat recording, but I can't see any simple way of doing this.

Searching by date of creation/editing, and by author, would also be useful but the title search would be my priority.

**Comment by johnvanbreda** [comment]
I've enabled the Administration Views module on iRecord which does exactly this. It als makes the standard "People" page much more easily searched.
