### ISSUE TITLE
iRecord user apparently has no warehouse account

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#615]
iRecord user CathyT has an account page on iRecord:
https://www.brc.ac.uk/irecord/user/54601

That account gives no link to a warehouse ID, and I cannot find her in the warehouse - there is no match for real name, username nor email.

When she tries to log on to iRecord she is getting an error message:

![image](https://user-images.githubusercontent.com/16039111/59193593-18386500-8b7e-11e9-8d05-4d011462db92.png)

That error message seems to be saying that the email already exists in the warehouse, but as stated above I cannot find it. However, if I search for her email the warehouse does find two other similar emails - it appears to be treating the underscore character as a wildcard.

Should I delete the iRecord account and start again?

**Comment by johnvanbreda** [comment]
The underscores were being treated as wildcards, so other email addresses were being found when it double checked uniqueness. This is because _ is a wildcard in SQL LIKE statements.
I've escaped the underscore and other wildcard characters and re-saved the account to fix this.
