### ISSUE TITLE
How to import lat/long coordinates from a CSV file

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#616]
A user wishes to import records from a CSV file, for which the location is given in two columns for latitude and longitude. My understanding was that this was possible to do, by combining the lat/long into a single column and importing that column into the Indicia sample attribute "Grid ref or other spatial ref".

However, I've just tried to test an import with the coordinates given in a single column as:
51.84678765 -2.269961956

(that is, with just a space to separate lat and long).

The import is failing ("The spatial reference is not recognised"). What am I doing wrong?

**Comment by BirenRathod** [comment]
@kitenetter 
Did you select spatial ref system WGS84? if you have try with other one too. Also, worth to try coordinates separated with comma instead.

**Comment by kitenetter** [comment]
@BirenRathod How do I select a spatial ref system when doing a CSV import? I can't see any attribute listed in the import fields that would accept a spatial ref system.

Is this something that we can do via the warehouse but that isn't available to iRecord users?

**Comment by BirenRathod** [comment]
@kitenetter 
Yes, spatial ref system is available to use from warehouse while importing CSV. On iRecord website the default is British grid ref and changing that to WGS84 might impact to other survey. 

I'm not sure about particular download form should allow to select spatial ref system.

**Comment by kitenetter** [comment]
Okay, in that case I will let the user know that he cannot upload data with lat/long coordinates. He may wish to convert his coords to grid refs. Closing.

**Comment by johnvanbreda** [comment]
@kitenetter to clarify this, the iRecord importer is configured with the following in the Preset Settings parameter:
```
sample:entered_sref_system=OSGB
```
This forces the spatial reference system to OSGB. If it is removed, then you get an extra drop down on the first page of the importer allowing you to choose from any of the available systems. The only problem with doing this is that it means existing documentation needs updating and it can be confusing picking the right system.
