### ISSUE TITLE
User's records are failing to display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#617]
This applies to user:
https://www.brc.ac.uk/irecord/user/2061

who has warehouse user ID 18104. In the warehouse, there are 53 records created_by this user ID. However, if I masquerade as the user on iRecord and go to Explore - My records, I can only see 15 records (which all happen to be of Rooks, and have been added via the "iRecord | Oxfordshire Rooks" survey).

I am completely bewildered by the apparently missing records! Here are a couple of examples of the ones that do not appear in the user's "My records" view:
- https://www.brc.ac.uk/irecord/record-details?occurrence_id=6204646
- https://www.brc.ac.uk/irecord/record-details?occurrence_id=9800880 (this is one that I have verified, so it must have come through to my verification view without problem)

If the user goes to their "Explore - My photo gallery" page, the photos are displaying correctly for records that do not appear in the "My records" view.

Possibly related: while masquerading, if I go to "Explore - All records" I can only see records for North and South Hampshire.

It appears that some filters are being applied to the Explore pages, but I cannot find where these filters may be stored. This user first registered over 6 years ago so I'm wondering if there may be some hangover from earlier functionality in iRecord.

Tagging @johnvanbreda in case this is a known issue that has a simple explanation, and tagging @burkmarr to do some investigation if this isn't a known issue.

Apologies in advance if there is an obvious explanation that I'm not seeing!

**Comment by burkmarr** [comment]
I masqueraded as the user and used Chrome Dev tools to intercept and copy the request made to the Warehouse to load the records. By experimentally removing parameters from the URL and pasting into the address bar of the browser I found that this bit is responsible from filtering the 53 records to 15:

&taxon_group_list_context=73

Removing this from the query causes all 53 records to be returned.

Do either of you know what this parameter is or where it's value is being set?

**Comment by johnvanbreda** [comment]
Ok, found it. Filters can either be normal ones (i.e. ones you create yourself) or "defines permissions" (i.e. ones the administrator set for you to give you a set of permissions). For reporting purposes, the former normally applies. For download and verification rights, the latter normally applies.

When you access a screen (reporting, download, verification) the default is to adopt the widest set of records allowed by the page. Unless you have a "defines permissions" filter, then this narrows down the set of records it is possible to access. This user had a filter id 7807 which defined permissions for reporting, thus limiting their total reportable set of records. I've reset this by changing filters.defines_permissions to false for this row.

Potentially we should review any other reporting filters that have defines_permissions=true.

**Comment by burkmarr** [comment]
@johnvanbreda - how is a filter marked as a 'reporting filter' or otherwise. Is it in the actual definition of the filter in filters.definition? I can't spot it in filter 7807.

**Comment by johnvanbreda** [comment]
```
filters.sharing='R'
```
The comment on the column explains the different values..

**Comment by kitenetter** [comment]
It was me who set up this user as a verifier in 2018, so the filter was defined at that point. Could I have mistakenly set it up as a reporting filter rather than a verification filter?

I can't see the filter listed in our filters admin page though - I would have thought it should be there?:
https://www.brc.ac.uk/irecord/filters/admin-list

The user had the "verifier" box ticked in his user profile, but since the verification filter seems to have gone missing it was exposing **all** records in his verification page, so I've now unticked the verifier role. I will set up a new verification filter and recreate the role for this user.

@burkmarr please can you continue to investigate the point that John made: "Potentially we should review any other reporting filters that have defines_permissions=true."

For  info, I am in the process of reviewing the verification filters (partly in order to get an up-to-date email list of our verifiers).

**Comment by burkmarr** [comment]
@kitenetter looking into it now. Could it have disappeared from the admin page because @johnvanbreda changed the defines permission flag?

**Comment by kitenetter** [comment]
Possibly! I should have checked for it when the user first raised the issue, don't think I had realised at that point that he was a verifier.

**Comment by burkmarr** [comment]
@kitenetter - you can check on dev_irecord where John hasn't reset the flag.

**Comment by burkmarr** [comment]
@kitenetter - this query lists all the reporting filters that have 'defines_permissions' flag set and the users they are set for. There are only 39 so doesn't look like this is a widespread problem. I ran this on dev, but should reflect live site since the DB was recently brought in line. Do you want me to do anything else on this?

set search_path=indicia;
select f.id as filter_id, f.title, f.description, u.username
from filters_users fu  
join filters f on f.id = fu.filter_id
join users u on fu.user_id = u.id
where f.sharing = 'R' and f.defines_permissions = True
order by username;

**Comment by kitenetter** [comment]
No further action require on this one.
