### ISSUE TITLE
Enable 'cancel' after bulk verification

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#62]
If a verifier initiates a bulk verification, after this action a pop-up window appears, informing the verifier of how many records have been affected:
![image](https://cloud.githubusercontent.com/assets/16039111/15945466/9ad89bd2-2e8a-11e6-8d39-5f0d0e4f09ee.png)

Two verifiers have requested the addition of a 'cancel' option to this pop-up window, as a final chance for them to reverse the bulk verification if they realise that it has affected more records than they were intending.

Is this feasible? Presumably the pop-up only appears after changes have been committed to the database?

**Comment by johnvanbreda** [comment]
A cancel after the event is not practical for the reasons you have mentioned. However we could implement a call to the reporting web service which doesn't actually change any data, just reports the count of records that match the filter. This would mean the bulk verify will be a 2 step process in all cases - you'd click the Verify button and the system will do report count to get the number of records affected, then you are asked to confirm it is OK to proceed. 
Is that extra step for verifiers OK?

**Comment by kitenetter** [comment]
That would be a desirable enhancement, yes please.

**Comment by DavidHepper** [comment]
I also support this.
