### ISSUE TITLE
Problem with incorrect date format

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#620]
A user has saved a record with the date "04/2019 to 12/2017". That record saved without any warning message, and is displayed in iRecord, but the date is shown as "invalid". When the user tries to edit or delete the record it is not possible to do so.

I've replicated this with another record for the same back-to-front date, and had the same result. Not only am I unable to delete this record in iRecord, I cannot access it via the warehouse interface either:

![image](https://user-images.githubusercontent.com/16039111/60263427-87c98680-98d8-11e9-8706-e41cd0aa594d.png)

Actions needed:
- Can we prevent iRecord from saving records that have incorrect (back-to-front) date ranges?
- Please can you delete my test record with occurrence_id=10521711

The other user's record, occurrence_id=10460466, may also need to be deleted, but I am awaiting confirmation from the user (he may wish it to be edited rather than deleted).

**Comment by burkmarr** [comment]
@kitenetter what input form was used?

**Comment by kitenetter** [comment]
For mine it was the normal Enter a casual record form:
https://www.brc.ac.uk/irecord/enter-casual-record?occurrence_id=10521711

I think it was the same for the other user, but I will check when I hear back from him.

**Comment by burkmarr** [comment]
@kitenetter I've fixed the user's record - can you let them know? They can now edit or delete it if they so wish. I'll sort your record out and then look into the bug.

**Comment by burkmarr** [comment]
@kitenetter  - I've sorted out yours too, so you can delete that too if you want.

**Comment by kitenetter** [comment]
Thanks @burkmarr - both those records are now dealt with, so it just leaves the issue of whether we can prevent invalid date formats from being saved in the first place.

**Comment by johnvanbreda** [comment]
@burkmarr thanks for taking this on. In case you are not aware, date handling is done by application/helpers/vague_date.php. There is a class application/tests/vague_dateTest.php which contains a number of test functions. I would advocate adding a function to this file to test the above date, then either test it locally with PHP Unit, or commit it and push to GitHub (perhaps in a branch). You should then be able to see the results of the test from Travis CI, which hopefully will be a failure. Then you can fix the code and push up again, hopefully this time to see the tests pass.

**Comment by burkmarr** [comment]
Many thanks @johnvanbreda - I'll do that.

**Comment by burkmarr** [comment]
Added checks to vague dates to ensure that end date after start date (except here end date is null). Created merge request on develop branch. https://github.com/Indicia-Team/warehouse/pull/326
