### ISSUE TITLE
Enhancement to notification emails

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#622]
NatureSpot users have requested that we make it clearer that you have to be logged in to iRecord in order to add a comment in response to a notification email. Currently our notification emails include a hyperlink to the observation page (under the "Record ID" heading), but if you go to that page while not being logged in you cannot see nor add to a comment box, nor do you have an option to log in.

**Short-term solution**: can we edit the standard notification text for both "Comments on your records" and "Verification results" so that this current text:

> If you wish to reply to this comment, please click on the blue “Record ID” link below, which will take you to your record on iRecord, You can add your reply in the “Add new comments” box at the foot of that page.

is replaced with:

> If you wish to reply to this comment, please click on the blue “Record ID” link below, which will take you to your record on iRecord. You can add your reply in the “Add new comments” box at the foot of that page (note that to do this you will need to be logged in to iRecord).

**Useful enhancement**: is it possible to add a "log-in here" type option to an observation page if it is being viewed by a non-logged in user?

@burkmarr are you okay to investigate this one? There is some background info in closed issue #209

And see also the related open issue #483

**Comment by burkmarr** [comment]
@kitenetter - the configuration file added by John to address #209 is here on the live Warehouse: warehouse\modules\notification_emails\config\notification_emails.php. I've updated the text in that to include the amendments you asked for. I'll investigate the login option.

**Comment by burkmarr** [comment]
@kitenetter We can configure the Drupal login block so that it appears on the record details page (it will only appear if user not logged in). I've done this for irecord_dev. You can test it following the link below. If you are not logged in, you will see the login block, but it you are logged in, you won't:

http://test.brc.ac.uk/irecord_dev/record-details?occurrence_id=10190925

Let me know if you want to implement this on the live site. 

@johnvanbreda - just checking with you that there are no implications of doing this that I've overlooked?

**Comment by johnvanbreda** [comment]
@burkmarr I'm happy with this - my only concern was to make sure it stays on the same page rather than redirects somewhere else when you log in but I can see that it already does.

**Comment by burkmarr** [comment]
@kitenetter - this issue seems to have dropped off the radar. Do you want me to configure the live iRecord site so that the login block appears for record details when user is logged out?

**Comment by kitenetter** [comment]
@burkmarr yes please, looks to be working well on the dev site

**Comment by burkmarr** [comment]
Okay that's done @kitenetter . I'm closing this, but feel free to reopen if you feel that there is still work to do.
