### ISSUE TITLE
Elasticsearch verification: deleted records remaining in grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#625]
A verifier queried why there were records in his "verification - new" view that were not in his "verification" view. The examples he's given are all of records that have been deleted, and they have an updated_on value of 25 June 2019, but they are still showing in the verification grid today (5 July 2019).

I know there can be a short delay before the elasticsearch tables get updated, but this seems like a long delay. Is there an underlying problem?

Record ID examples:
10509392
10509391
10509390
10509345
10509344

**Comment by kitenetter** [comment]
This bug continues to cause problems. Another example is a batch of records from 11480179 to 11480522 that were entered on 14 Aug and deleted on 20 Aug (I think) but which are still displaying as records to be verified in the new verification page.

**Comment by johnvanbreda** [comment]
Have added an index that should help performance of the deletion extraction report since it was timing out. It will take a few hours to catch up.
