### ISSUE TITLE
Request permission to delete filters that were set up by other admin roles

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#626]
Is it possible to give the "iRecord support" user account (user ID 102855) the ability to delete filters that were created by other admin accounts (usually David Roy or admin) from the iRecord "Filters Admin" page, in order to avoid me having to ask someone else to delete via the database?

**Comment by BirenRathod** [comment]
@kitenetter 
"iRecord support" has already assigned as admin. In order to check this, can I have a page URL please?

**Comment by kitenetter** [comment]
@BirenRathod my starting point is the list of filters here:
https://www.brc.ac.uk/irecord/filters/admin-list

If I edit a filter that I have previously created, I am able to delete it via a delete icon (rubbish bin) next to the Save icon.

If I edit a filter created by another admin, then I cannot delete it - the delete icon is not displayed.

Here is an example of a filter I cannot delete:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=98

**Comment by BirenRathod** [comment]
@burkmarr 
This requires to implement the code.

**Comment by kitenetter** [comment]
Assigning to current milestone as @johnvanbreda has highlighted a potential performance issue arising from the verification filters that are awaiting deletion.

**Comment by burkmarr** [comment]
@kitenetter @johnvanbreda the relevant code is in \iform\media\js\reportFilters.js. There is code to only show the delete button if the user_id of current user matches the user_id of the filter creator. (There also code that filters records to be deleted based on current user ID.)

Some options are:

- Alter code so that users with admin privilege can delete any filter. (Is this consistent with the rest of the site?)
- Alter code so that main Admin user (user 1) can delete any filter.
- Leave code as it is and instead masquerade as relevant user to delete filters when required. An option if this is an infrequent requirement.

Any thoughts?

**Comment by BirenRathod** [comment]
@burkmarr 
Ideally it should be the first one which is user with admin privilege should able to amend or delete filter. There are only handful of people have got assigned with admin role.

**Comment by johnvanbreda** [comment]
* Add a "can delete any filter" permission parameter to the standard parameters control. Set this parameters' value to "indicia data admin"

**Comment by burkmarr** [comment]
@johnvanbreda - there's an admin option parameter in report_filters.php that indicates if user is admin. I could pass this to JS via indiciaData and then enable the delete button if it is set. Does that sound like a reasonable approach?

**Comment by johnvanbreda** [comment]
@burkmarr Yes, that does sound reasonable.

**Comment by burkmarr** [comment]
Okay this is good to go then. Merge requests created against dev for media and client_helpers:
https://github.com/Indicia-Team/media/pull/19
https://github.com/Indicia-Team/client_helpers/pull/90

**Comment by kitenetter** [comment]
I'm not sure how close we are to being able to resolve this on the live site, but in the meantime please can I request the deletion of this reporting filter:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=2131

I assigned it to the "iRecord support" account in order to remove it from someone else's account, but having done that it is restricting my view of records when I'm logged on as iRecord support - would be very grateful if it can be deleted altogether!

**Comment by burkmarr** [comment]
I've deleted the troublesome filter @kitenetter.

**Comment by johnvanbreda** [comment]
@burkmarr I've applied this to live - does it need any configuration before this can be closed?

**Comment by burkmarr** [comment]
No I think it should be ready to use. Can you confirm that you can now do what you need @kitenetter ?

**Comment by kitenetter** [comment]
@burkmarr yes, the delete option is now available to me - thanks.
