### ISSUE TITLE
Issues with the new dynamic map layer

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#629]
With the new dynamic map layer selected in iRecord, the code does not seem to handle zooming across the entire zoom range of the middle (OS) layer very well. Symptoms of this include:
* Start zoomed out so viewing OSM for the British Isles. Now, click on the topmost rung of the zoom bar. You are switched to Ordnance Survey at its top zoom level, which is 1 higher than the point at which we should switch to Google Satellite. Because you are at the top of the zoom scale you cannot zoom further so cannot get satellite data to appear, unless you zoom out a step and in again. 
* When viewing areas outside OSGB (including Ireland), zooming in never activates OS Leisure (which is correct) but this means it never allows a switch to satellite, because the middle layer cannot be skipped.

**Comment by burkmarr** [comment]
I'm happy to take a look at this John.

**Comment by burkmarr** [comment]
Fixed and merge request on dev branch made.
