### ISSUE TITLE
Organisational account grouping

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#63]
This might not be of highest priority, but I thought it is worth having this idea logged. Some groups share same iRecord account for recording, which is most likely not the best recording practice, so it might be a good idea to have some sort of organisational management, e.g. like on GitHub your personal account can belong to multiple organisations giving you different set of permissions and functionality.

**Comment by johnvanbreda** [comment]
Can't this already be achieved through the activities system? This is actually already being extended to support organisations by the FSC (http://www.brc.ac.uk/irecord/organisations/list).
