### ISSUE TITLE
ES Explore my records - missing fields in download

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#632]
https://www.brc.ac.uk/irecord/elastic/explore/my

Download file is currently missing data from the following columns:
Higher geography | Vice County | Vice County number

**Comment by kitenetter** [comment]
Attached is a comparison between old download and new.

- There are 13 columns in the old format that are not in the new (at least one of these is probably not needed)
- There are 8 columns in the new that were not in the old (at least one of these is probably not needed)
- The majority of columns that are in both formats have had their column heading names changed; in some cases the new name is arguably an improvement, but by changing so many names we are making life difficult for those who have an established routine for downloading and incorporating into other datasets
- The order of columns is very different, and again I think we should stick as closely as possible to the order that people are used to from the old format
- It is not yet clear to me how we are handling the differences and translations between the entered spatial coordinates and the output grid references, and what happens to non-UK records.

[Elastic download headings.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/3398536/Elastic.download.headings.xlsx)

**Comment by johnvanbreda** [comment]
@kitenetter I think this can be closed now that the ES My Records download uses the configured columns in the data grid to define the columns in the download?
