### ISSUE TITLE
iNaturalist import has stopped

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#633]
Records haven't been imported from iNaturalist for ~40 days.  

Here is the plot of incoming data
![inat](https://user-images.githubusercontent.com/2699478/61532749-c4455980-aa22-11e9-9e87-5efcf947b6ed.png)

@BirenRathod is the scheduled task running? see #581

**Comment by BirenRathod** [comment]
Yes, I can confirmed that it is running fine. Here is the screen shot.
![image](https://user-images.githubusercontent.com/5941255/61533854-e9879700-aa25-11e9-88a9-03cbe465083f.png)

**Comment by johnvanbreda** [comment]
@BirenRathod I think that is the schedule for the main scheduled tasks process, not the rest API sync (called Indicia Import in Task Scheduler). The Indicia Import task is running every night but immediately failing. If I run it manually, either from this link: /index.php/services/rest_api_sync, or via the warehouse Admin menu, Rest API Sync menu item, then it works. So I suspect a permissions issue in the task?

@DavidRoy I've run the backlog through using the tool in the warehouse UI.

**Comment by BirenRathod** [comment]
@johnvanbreda & @BirenRathod 
Sorry it was my mistake. Due to last PHP update, I missed to change the path of the PHP in task scheduler. I just done it for indicia import, so should be fine.

**Comment by DavidRoy** [comment]
Thanks for resolving.  Import now working.

**Comment by BirenRathod** [comment]
I can confirm that this morning scheduled task ran successfully. So you could expect to see data if there is any in last two days. As I can see from above picture warehouse doesn't receive every day. 
![image](https://user-images.githubusercontent.com/5941255/61708050-c3bf0280-ad43-11e9-908a-97b59de8840f.png)

**Comment by DavidRoy** [comment]
@BirenRathod There have been no records since John ran the process manually.  Can you look again at the scheduled task please

**Comment by BirenRathod** [comment]
@DavidRoy 
I can't see any errors or problem of having any difficulty.
Here is the screenshot.
![image](https://user-images.githubusercontent.com/5941255/62040352-5d2d5f00-b1f1-11e9-8383-c77cc8308506.png)

**Comment by kitenetter** [comment]
Suggest parking this until we complete a review of the iNaturalist process, see #684

**Comment by DavidRoy** [comment]
Agreed.  Closing this issue
