### ISSUE TITLE
Data missing from user's my-records report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#635]
relates to: https://www.brc.ac.uk/irecord/node/7792

The record was submitted via the iRecord app but warehouse view of the record shows no obvious issues.
http://warehouse1.indicia.org.uk/index.php/occurrence/edit/10641696

**Comment by kitenetter** [comment]
Possibly related to #624 although in this case there is no sign of the "Your preferred locality for recording is ." problem.

**Comment by DavidRoy** [comment]
Follow up request from recorder:
https://www.brc.ac.uk/irecord/node/7817#comment-5022

To investigate the issue, as admin I tried to re-save the user account, but then got an error message:
Error: unknown warehouse_user_id (138837)

@burkmarr can you pick this one up as the user can't see their records.

**Comment by burkmarr** [comment]
As the error suggested, the Warehouse ID stored against the user's account in iRecord - 138837 - did not correspond to a user in the Warehouse. 

I searched on the user's name in the Warehouse (http://warehouse1.indicia.org.uk/index.php/user). A different number was registered against the user - 71832. (By checking the linked Person account and looking at the email I could see this was the right person.)

This user was only registered for the websites British Dragonfly Society and UKBMS, so I edited (using Warehouse UI) and added in iRecord. Then I edited the user's iRecord account (as admin) and changed their Warehouse ID to 71832.

Now when I masquerade as the user, I see plenty of records - especially recent butterfly records - but I cannot find the missing red veined darter record. I will contact the user via forum and  ask for more details.

Does anyone have any ideas about how the user's Warehouse ID in iRecord might have been set to this value which didn't correspond to anything in the Warehouse?

**Comment by burkmarr** [comment]
@DavidRoy - can you throw any light on the record referenced above and in the forum thread: 
http://warehouse1.indicia.org.uk/index.php/occurrence/edit/10641696
https://www.brc.ac.uk/irecord/record-details?occurrence_id=10641696
It's not the record in question. Was that just a mistake or is something very odd going on?

**Comment by DavidRoy** [comment]
@burkmarr thanks for resolving this.  I can't remember how I ended up at that record ID.  I can't locate the right record either - possibly 
https://www.brc.ac.uk/irecord/record-details?occurrence_id=11014888

I suspect it will be hard to track down the source of the original issue (problem with the EasyLogin module?) and is not worth too much effort.

**Comment by burkmarr** [comment]
I don't think that's the record either @DavidRoy. Anyway, I have asked for more information via the iRecord forum. Will leave this open for now.

In the meantime, can anyone help me with the following conundrum?

On Warehouse:
- I log into the live warehouse
- I go to occurrences and filter on 'Sympetrum fonscolombii'
- I sort by date
- I can see **four records** dated 03/07/2019

On iRecord:
- I go to Explore All Records
- I create a filter on 'Sympetrum fonscolombii' and '03/07/2019' (field record date).
- I can see **nine records**

The nine records visible on iRecord include all those listed on the Warehouse. I tried all the different date types in my iRecord filter in case the date listed on the Warehouse wasn't the field record date, but I never got a set of records which matched. (Input date listed four records but only three of them were the same as the four records listed in the Warehouse.)

It seems like I'm not seeing all the records when I list them in the Warehouse - why would that be?

**Comment by johnvanbreda** [comment]
@burkmarr the views on the warehouse are pretty basic, i.e. picking up only the taxon name as recorded, not the accepted name. In this case, 5 of the records were put in as Red-veined Darter so won't appear.
The occurrences view in the Warehouse would ideally be replaced by an "Explore" style page with filter, but I'm not sure it's a priority.

**Comment by burkmarr** [comment]
Thanks John it's good to understand why the discrepancy.

**Comment by burkmarr** [comment]
Closing issue after discussion with user on Forum. Will open a new issue if there are further problems submitting records.
