### ISSUE TITLE
Species list entry - dynamic system occurrence attributes

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#637]
Follow on from #222

Species list entry - swap system attributes to dynamic occurrence attributes where available for selected taxon (e.g. moths)

**Comment by johnvanbreda** [comment]
@kitenetter to specify some test scenarios to set up on test version of iRecord.

**Comment by kitenetter** [comment]
@johnvanbreda are we aiming to set this up as multiple termlists, e.g. a list for birds, a list for plants, etc.? Or one longer termlist that includes a attribute that will link to a species group at sone level?

And do you want me to send you a suitable set of terms in a spreadsheet, or to set them up as a new termlist in the warehouse?

And this is going off-issue a little, but thinking ahead to whether we may one day be able to address #282, do we want to enhance our list of stage terms with an additional attribute that makes it obvious which terms refer to the adult stage, and which to pre-adult? This might make it easier to adapt the rule sets to only deal with records that are not pre-adult?

**Comment by kitenetter** [comment]
Documentation is now in:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Recording form development\Review of dynamic occurrence attributes.docx

and attached:
[Review of dynamic occurrence attributes.docx](https://github.com/BiologicalRecordsCentre/iRecord/files/3750773/Review.of.dynamic.occurrence.attributes.docx)

Proposed termlists are in the first two worksheets of:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Recording form development\system termlists review.xlsx

and attached:

[system termlists review.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/3750775/system.termlists.review.xlsx)

Actions copied from the above documentation:
1. We implement dynamic attributes on a limited basis, to enable use of termlists for sex and stage that are relevant to the taxon being recorded
2. Initial proposals for suitable terms are given in a separate spreadsheet (linked above)
3. As part of this, we ensure that stage terms are mandatory (and for invertebrates have to be specified by the user, even if this is to say “not recorded” – can invertebrates be treated differently to other groups?)
4. Can we have an dynamically added “record status” termlist for plants only? To include native, introduced etc. Ideally as an extra attribute, but if needed this could be in place of the “sex” or “recorder confidence” termlists (if not possible in short-term should be developed in future)
5. We implement clearer signposting to the taxon-specific forms, which remain the best option for those recording schemes that use them
6. Over time we work with other recording schemes to build consensus on adding further terms if required (current requests for “method” and “status” see below), and on further taxon-specific forms

Note that at present there does not appear to be any need for the sex termlist to be dynamic, only the stage.

@johnvanbreda let me know if you want me to set up the proposed stage termlists as new termlists in the warehouse.

@DavidRoy @burkmarr @kazlauskis (and others) let me know if you have any comments on the above.

**Comment by kazlauskis** [comment]
> @johnvanbreda are we aiming to set this up as multiple termlists, e.g. a list for birds, a list for plants, etc.? Or one longer termlist that includes a attribute that will link to a species group at sone level?

@kitenetter I think it would be multiple termlists attached to different sex/stage attributes. These attributes could then be assigned to different taxa groups.

**Comment by johnvanbreda** [comment]
I agree with @kazlauskis.

**Comment by kitenetter** [comment]
Add termlists
Editing form for app records
Generic recording forms

**Comment by kitenetter** [comment]
Remaining issues now added as separate items - closing this one.
