### ISSUE TITLE
Cheshire VC boundary not appearing in filter list

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#642]
I'm trying to set up a verification filter for Cheshire (VC58) but can't find it in the vice-county list via the filter settings.

**Comment by johnvanbreda** [comment]
I'd seen this error a couple of days ago so I've looked into it in case it was the same. It appears a handful of vice counties got moved into the ABLE website, possibly relating to the migration of data for ABLE. I've cleaned this up.

**Comment by kitenetter** [comment]
@johnvanbreda thanks for that - no doubt you've already looked into this, but are there any implications for indexing of records against these boundaries during the period they went missing?

**Comment by johnvanbreda** [comment]
@kitenetter, no, the indexer works for website-linked locations and public locations in the same way.
