### ISSUE TITLE
Adding taxa outside the scope of a taxon-specific form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#643]
I'm adding a list of moth records to the moth recording form:
https://www.brc.ac.uk/irecord/enter-moth-sightings

I want to include a few beetles and flies from the moth trap, alngside the moths. It looks like I ought to be able to do this via the filter button above the "Species" column, but even if I specifically choose beetles the beetle species name is not recognised:

![image](https://user-images.githubusercontent.com/16039111/62577709-67a5c380-b897-11e9-96f8-9d57d085c2b6.png)

Has this filter feature stopped working? Is there any other way of adding a non-moth to the moth recording form, or is that not allowed?

**Comment by johnvanbreda** [comment]
I'm not sure this would ever have worked - the filter applied is additional to the filter configured for the page (i.e. moths) so you can't add different species.

**Comment by kitenetter** [comment]
Is there any way in which the moth filter could be over-ridden for this form? One of the barriers for people filling in the moth form is that they may wish to record the occasional non-moth that arrives in the light-trap, and it would be great if this could be done via a single form.

I suppose the introduction of dynamic attributes may provide a more general solution, but if there was an easy way of allowing the filter to be over-ridden in some way for the existing taxon-specific forms that might be worth doing.

I'm going to close this for now, but if you think it is worth pursuing further please re-open.

**Comment by johnvanbreda** [comment]
Yes, I'm sure that we could override the configured filter if the grid filter is used. I'll re-open and leave it to you to allocate to a milestone if a priority.

**Comment by kitenetter** [comment]
Not a priority at the moment - closing.
