### ISSUE TITLE
Question about photo upload process and re-sizing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#649]
We have an enquiry about the size of photo that can be uploaded without triggering any automated re-sizing. Is there any existing documentation about file sizes and how the re-sizing process works?

**Comment by johnvanbreda** [comment]
@kitenetter - it's just a configuration option for the max width and height. Search for resize on this page: https://indicia-docs.readthedocs.io/en/stable/site-building/instant-indicia/example-setups/irecord-walkthrough/form-structure.html. 

Most (or all) forms are set to 1500x1500 I think.
