### ISSUE TITLE
Question: marking a taxon as not for data entry

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#650]
An issue has arisen over a leafhopper species that is marked as a good name in the UKSI but is not a UK species, and is being used erroneously to record leafhoppers.

I will liaise with Chris to have the species status changed in UKSI, but in the meantime I think I can deal with this situation in iRecord by simply marking this taxon as "not for data entry".

Is that all I need to do or are there any other implications?

**Comment by kitenetter** [comment]
I see that the vernacular name for this same taxon (Aphrophora gelida) came up before in #609 and the solution to that involved running an update SQL on the warehouse.

Is the update SQL approach required, or can I do this through the online warehouse interface?

**Comment by johnvanbreda** [comment]
@kitenetter Just unsetting allow_data_entry via the user interface should work fine - it will take a short while to ripple through before it is removed from the search index.

**Comment by kitenetter** [comment]
Done, closing.
