### ISSUE TITLE
Records not appearing on user's my-records report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#651]
https://www.brc.ac.uk/irecord/node/7820

may be the same issue as reported elsewhere? #639.

I've asked for more details to hopefully track down the source of the issue

**Comment by burkmarr** [comment]
I can't see what's going on here. User's Warehouse ID looks okay but there are only records from 2017 linked to that user.

I re-ran query from @johnvanbreda (https://github.com/BiologicalRecordsCentre/iRecord/issues/634) to see if this might be a user affected by import issue, but that doesn't appear to be it (besides I think we know about all of these now and the cause of that problem has been addressed).

We need more details from the user about how records were entered, so need to wait for them to respond to the question posed on the forum.

**Comment by DavidRoy** [comment]
It looks like the recorder has been entering data when not logged in?  See:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=11479578

I'll ask via the forum

**Comment by burkmarr** [comment]
I'd forgotten that was a possibility.

**Comment by burkmarr** [comment]
@kitenetter @johnvanbreda  Presumably this must be something that happens from time to time? Does the following SQL look okay to sort this out on the occurrences and cache_occurrences_functional tables?

```sql
update <table> set created_by_id=<user_id> 
where id in 
(select cof.id from cache_occurrences_functional cof 
join cache_samples_nonfunctional csn on csn.id = cof.sample_id 
where csn.recorders ='<recorder name>' and cof.created_by_id = 1); 
```

**Comment by johnvanbreda** [comment]
Yes, the SQL looks good, but I would write a similar SELECT query to eyeball the data first just to make sure, e.g. if there are any that are not from a similar region or date range they might be from a different user.

**Comment by burkmarr** [comment]
I've run the queries and all appears okay. Have informed the user by the iRecord forum thread.
