### ISSUE TITLE
Elastisearch - Verification Column selection

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#654]

**Comment by MNSmith** [comment]
When using Elastisearch and selection what columns to view, the default setting Column 1 (Icon showing record verification status and sensitivity) does not display.  Deselection this column from the "display list" has no effect on the view of the grid - they is still just a "blank colum" displayed in its place occupying space in the grid.   Could this be down to this column having "no heading" rather than a column title?

The map and record details occupy more space on the page than the old version, thus leaving less space for the records grid.  Could we have them resized back to the old size please or better still, allow the user to choose a size?

![Image1](https://user-images.githubusercontent.com/18451743/63586452-3caab780-c599-11e9-9cb1-1f1a9be9c276.jpg)

**Comment by MNSmith** [comment]
A small update to this bug.  If this Column 1 is not selected then the ability to use "tick boxes" for multiple verifications doers not appear, presumeably because this feature is attached to "Column 1".  Needs to be separated.

**Comment by johnvanbreda** [comment]
The first column seems to work OK now.
I've tidied the code up and separated the multi-select tool from the first column. It will be deployed next time I do a full code update.
