### ISSUE TITLE
Activities not linking correctly to locations

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#655]
This was reported to me in relation to two activities, "Berkshire moths" and "Upper Thames Butterflies". The former was originally set up with a VC22 boundary as part of its filter, the latter probably used the appropriate BC branch boundary. However, if you try to add a record to either of these activities, the map box is initially completely blank. If you click on the blank map it does show a background, in each case at the far north-west corner of the boundary. But it fills in a lat/lomg rather than a grid ref.

If you try to zoom the map it goes blank again, at least while it is set to the "Dynamic" layer - if you swith to Open Street Map it seems to be more stable.

But I thought it used to display the whole county when you first went into it, and the switch to lat/long is very unhelpful. 

And in fact it seems impossible to move the map to any area other than the north-west corner - it seems to have got 'stuck' there.

The user who reported it has found it impossible to move the map to the areas he needs and has given up using the activities.

I've now found a similar problem with another BC branch activity. The problem seems to relate to VC and BC branch boundaries, activities with custom boundaries appear to be working as expected.

**Comment by burkmarr** [comment]
I spent some time on this today @kitenetter without making much headway. One thing making it hard to investigate is that there is a delay between changing activities, e.g. adding/removing a location filter, and it being reflected in input form - presumably due to some sort of caching or indexing.

Adding a location seems to completely fubar the mapping - not just the initial zoom - the map behaviour completely unpredictable. I've noticed an aerial layer seems to be displayed behind the OS/OSM layers. This seems to be a widespread problem on activities linked to any location so I will carry on looking at it.

**Comment by johnvanbreda** [comment]
@burkmarr this seems to be a consequence of the new dynamic layer. To test this, I put a breakpoint in the JS and altered settings.presetLayers in the map code to remove the dynamic layer and the page then loads fine. So, the thing that is different about this layer is the way it reacts on the map's moveend event. This event can be temporarily disabled by setting a flag `indiciaData.recetenteringAfterBaseLayerSwitch` to true. If you put a breakpoint in the start of the moveend handler where it checks this flag, then force it to true to make sure the rest of the event code doesn't run, then it works.
So, either we need to work out why the moveend handler causes it to mess up, or we need to set this flag when the location loads to prevent it from running.

**Comment by burkmarr** [comment]
@johnvanbreda @kitenetter The combination of our complex layer switching code and the opaque workings of OpenLayers 2 have made this very hard to unravel. Although I haven't gotten to the bottom of it, I have, I think, found a reasonable workaround. We currently have a line of code that restricts the operation of OpenLayers 2 to the extent of the specified location in the activity:

```
mapdiv.map.setOptions({restrictedExtent: bounds});
```
If we take that out, it works. The view is still centred on the area of interest and the location boundary drawn. It just means that the user can pan away outside the area if required. Personally I don't think this is a big disadvantage. What do you think?

**Comment by johnvanbreda** [comment]
I agree, this is not a big disadvantage so I'm happy for that to be removed.

**Comment by kitenetter** [comment]
Agreed - thanks @burkmarr

**Comment by burkmarr** [comment]
How best to manage this @johnvanbreda - is this a candidate for a hotfix? I think it's probably rednered a lot of activity forms unusable.

**Comment by johnvanbreda** [comment]
@burkmarr Yes. If you would prefer that I check it, why don't you create a branch called hotfix-activities, fix it, then publish it to GitHub. I can then check the change and merge to master/develop when releasing it. Or, if you feel comfortable with the change, you could do the hotfix yourself?

**Comment by burkmarr** [comment]
I've taken the first option John - created branch and merge request on client_helpers.

**Comment by burkmarr** [comment]
I've done it @johnvanbreda! The changes look sensible and good to me. Sorry about basing on wrong branch - that's because I didn't really understand the hotfix workflow properly, but I think I see it now.

**Comment by johnvanbreda** [comment]
No problem. Here's a document that describes how our Git process works: https://nvie.com/posts/a-successful-git-branching-model/ which is referred to from https://indicia-docs.readthedocs.io/en/latest/developing/github.html. It's more or less based on the Git Flow standard.

**Comment by burkmarr** [comment]
@johnvanbreda - this looks okay now on iRecord live so I guess you did the client_helpers pull? If so, can we close this?

**Comment by johnvanbreda** [comment]
Yes - thanks. Closing
