### ISSUE TITLE
Record cleaner rules not getting updated when taxonomy changes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#658]
Following a query about how butterfly rules are applied, it appears that the rules are not always being applied where a species name has changed since the rules where defined. This has implications for recorders and verifiers, and since the examples so far found are for butterflies it also has implications for auto-verification of UKBMS records.

The example is Small Pearl-bordered Fritillary, _Boloria selene_. The ID difficulty rule was set up for TVK NHMSYS0000516240:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NHMSYS0000516240

That is now a not-recommended name, and the preferred TVK is NHMSYS0021143547:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021143547

_Boloria selene_ is currently not being flagged as hard-to-identify, and will therefore be more likely to be auto-accepted for UKBMS records.

We should ideally link the TVKs as originally defined in the Record Cleaner rulesets to the currently preferred TVKs.

**Comment by johnvanbreda** [comment]
I think the best way to handle this is a script which finds rules linked to non-preferred TVKs, then converts them to use the preferred TVKs. This could be run on an ad-hoc basis (e.g. after a UKSI import).

**Comment by kitenetter** [comment]
I don't think we've implemented this, and I think we ought to. Adding to September milestone for review.

**Comment by kitenetter** [comment]
Following the UKSI update this week we are likely to need to run a script as suggested by John above.

**Comment by JimBacon** [comment]
Relates to https://github.com/Indicia-Team/warehouse/issues/414

Is it okay if it takes me a few weeks to get on to this, @kitenetter?

**Comment by robin-hutchinson** [comment]
I think this is related - a rule based on a junior synonym is being applied to records of the recommended name:

The following message was attached to your record of Common Wainscot (Mythimna pallens) at SK45257263 on 10/08/2023 when it was checked using the [NBN Record Cleaner](http://www.nbn.org.uk/Tools-Resources/Recording-Resources/NBN-Record-Cleaner.aspx). This does not mean the record is incorrect or is being disputed; the information below is merely a flag against the record that might provide useful information for recording and verification purposes.
Coordinate outside known range for Mythimna favicolor

**Comment by kitenetter** [comment]
This is due to be addressed through NCEA in 2024. Leaving it open for now.

**Comment by kitenetter** [comment]
Now being addressed via https://github.com/BiologicalRecordsCentre/record-cleaner-service - closing
