### ISSUE TITLE
Record cleaner distribution rules duplicated for butterflies

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#659]
For at least some butterflies, two sets of distribution rules are being applied, e.g.:

![image](https://user-images.githubusercontent.com/16039111/63862152-03f94c80-c9a4-11e9-913b-beac8bd114e2.png)

This appears to stem from the fact that iRecord contains a set of distribution rules for butterflies, and another set for "moths", but the moths set includes all Lepidoptera. The list of 10km squares is not identical between the two sources.

I'm not aware that this is causing any problems but it is potentially confusing and maybe inefficient.

Should I investigate this further to work out which set of rules is the most up-to-date?

**Comment by johnvanbreda** [comment]
@kitenetter Yes, I would vote for comparing the rulesets to determine which is most up to date and removing the other.

**Comment by kitenetter** [comment]
Okay, so the situation is:
- The "moths" distribution ruleset includes a wider range of butterfly species, but all the 'extras' are migratory species that don't have a relevant native range
- The "butterflies" distribution ruleset has fewer species, but curiously does include a number of resident and regular migrant species that are missed out of the "moths" ruleset (e.g. Red Admiral and Painted Lady)
- In the NBN Record Cleaner software itself, the "butterflies" distribution ruleset is used, and the butterfly species are not included in the "moths" distribution ruleset

So it appears that the best solution is to remove the **distribution** rules for **butterfly species** that are linked to source_url "http://data.nbn.org.uk/recordcleaner/rules/BC/**NMRS Moth rules.zip**" in table verification_rules, and to retain the distribution rules for butterfly species that are linked to source_url "http://data.nbn.org.uk/recordcleaner/rules/BC/**BC Butterfly rules.zip**".

However, the "NMRS Moth rules.zip" do contain legitimate rules for phenology, time period and ID difficulty, so it is only the distribution rules that are not needed.

I've spent quite a lot of time trying to get my head round the structure of the three tables verification_rules, verification_rule_data and verification_rule_metadata, but as yet I don't feel confident in trying to define the SQL needed to select all the elements relating to butterfly distributions within the NMRS Moth rules.zip source, so that they can be marked as deleted.

Given that the duplicated rulesets don't seem to be causing any great problems at the moment it's hard to see this as a priority for further work.

**Comment by kitenetter** [comment]
This is probably best tackled by a review/update of the rules more generally. Closing.

**Comment by JimBacon** [comment]
As an aside, it looks like the moth rules were last updated on the warehouse on 25/09/2015 whereas the version available from the NBN is dated 13/12/2016. Since a new set of rules is imminent I'm not investigating but just logging the fact in case this does come back again.
