### ISSUE TITLE
Request to edit uploaded records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#660]
A number of users are uploading csv files as part of a BENHS project to assist with identifying bycatch from the Rothamsted Light-trap Network, but there have been some inconsistencies in how this has been done that they would like to iron out.

There are three updates requested, and I think the first of these is reasonably straightforward:

**Assign 24 records uploaded by Jon Cole to activity "Rothamsted Insect Survey Light-trap Network"**

```sql
update occurrences set group_id=1060 where import_guid in ('1526129771239');
update cache_occurrences_functional set group_id=1060 where import_guid in ('1526129771239');
```

The second request is more complex, and I can't see any way of identifying the correct set of records except by listing the sample ids:

**Update 135 Tristan Bantock samples (160 records) to recorder name "Ian Sims"**

```sql
update sample_attribute_values set text_value='Ian Sims' where sample_id in (4997877,4997878,4997879,4997880,4997881,4997882,4997883,4997884,4997885,4997886,4997887,4997888,4997889,4997890,4997891,4997892,4997893,4997894,4997895,4997896,4997897,4997898,4997899,4997900,4997901,4997902,4997903,4997904,4997905,4997906,4997907,4997908,4997909,4997910,4997911,4997912,4997913,4997914,4997915,4997916,4997917,4997918,4997919,4997920,4997921,4997922,4997923,4997924,4997926,4997927,4997928,4997929,4997930,4997931,4997932,4997933,4997934,4997942,4997976,4997977,4997978,4997979,4997980,4997981,4997982,4997983,4997984,4997985,4997986,4997987,4997988,4997989,4997990,4997991,4997992,4997993,4997994,4997995,4997996,4997997,4997998,4997999,4998000,4998001,4998002,4998003,4998004,4998005,4998006,4998007,4998008,4998009,4998010,4998011,4998012,4998013,4998014,4998015,4998016,4998017,4998018,4998019,4998020,4998021,4998027,4998028,4998029,4998030,4998031,4998032,4998033,4998034,4998035,4998036,4998037,4998038,4998039,4998045,4998046,4998047,4998048,4998049,4998050,4998051,4998053,4998054,4998055,4998056,4998057,4998058,4998059,4998060,4998061,4998062,4998063) and sample_attribute_id=127;
```

The associated cache update is:

```sql
update cache_samples_nonfunctional set recorders='Ian Sims' where attr_cms_user_id=238 AND group_title='Rothamsted Insect Survey Light-trap Network';
```

The third request is to change a sample method:

**Update 135 Tristan Bantock samples (160 records) to sample method "Light Trap"**

```sql
update samples set sample_method_id=25 where created_by_id=22 and group_id=1060;
```

The associated cache update is:

```sql
update cache_samples_nonfunctional set attr_sample_method='Light Trap' where attr_cms_user_id=238 AND group_title='Rothamsted Insect Survey Light-trap Network';
```

@burkmarr please can you check my proposed update SQLs and implement them if they are correct.

**Comment by burkmarr** [comment]
@kitenetter - my understanding of the data model is still 'evolving' but the updates look okay to me. I think it would be wise for @johnvanbreda to cast his eye over them in case he spots some implications we've missed.

I'll go ahead and run when he's had a look. 

Based on the logic in the fifth update, I think this would work for the third rather than listing the sample IDs in the query? A similar select query retrieves 135 records.
```sql
update sample_attribute_values set text_value='Ian Sims' 
where sample_attribute_id=127 and created_by_id=22
and sample_id in (select id from samples where group_id = 1060)
```

**Comment by johnvanbreda** [comment]
Rather than worry about getting all the correct cache fields updated (including attrs_json which is missed), you can get the work queue to do the updates for you. When there are occurrences to update you can:
```sql
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
from occurrences where ...;
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_attrs_occurrence', 'occurrence', id, null, 100, 2, now()
from occurrences where ...;
```
Or, for samples:
```sql
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'sample', id, null, 100, 2, now()
from samples where ...;
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_attrs_sample', 'sample', id, null, 100, 2, now()
from samples where ...;
```

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - that's useful. Shall I go ahead with this then @kitenetter, using John's suggestion to update the cache tables via work queue?

**Comment by kitenetter** [comment]
Sounds good to me @burkmarr - thanks.

**Comment by johnvanbreda** [comment]
Just bear in mind that due to switching on a new summary builder for UKBMS, the work queue is way behind today, so it might take a day or two to come through.

**Comment by burkmarr** [comment]
@kitenetter. Here's a summary of the SQL. In fact the first query was wrong because group_id is in the samples table, not occurrences, so I had to update the corresponding sample records. The corresponding cache builder inserts to the work queue for these samples will also update the associated occurrences.

In fact the samples affected by the last two updates were the same, so I only had to enter the relevant samples tasks into the work queue once for those.

```SQL
update samples set group_id=1060 where id in 
(select sample_id from occurrences where import_guid = '1526129771239'); 

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on) 
select 'task_cache_builder_update', 'sample', id, 100, 2, now() 
from samples where id in (select sample_id from occurrences where import_guid = '1526129771239'); 

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on) 
select 'task_cache_builder_attrs_sample', 'sample', id, 100, 2, now()  
from samples where id in (select sample_id from occurrences where import_guid = '1526129771239'); 

update sample_attribute_values set text_value='Ian Sims' 
where sample_attribute_id=127 and created_by_id=22 and sample_id in 
(select id from samples where group_id = 1060); 

update samples set sample_method_id=25 where created_by_id=22 and group_id=1060; 

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on) 
select 'task_cache_builder_update', 'sample', id, 100, 2, now()  
from samples where created_by_id=22 and group_id=1060; 

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on) 
select 'task_cache_builder_attrs_sample', 'sample', id, 100, 2, now()  
from samples where created_by_id=22 and group_id=1060; 
```
