### ISSUE TITLE
Help needed with PoMS data entry form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#661]
We have a form set up to allow entry of data from the PoMS 1km square surveys - this form is only available to members of the activity "1km square survey - pan-traps":
https://www.brc.ac.uk/irecord/poms-1km-pan?group_id=1073&implicit=f

Edit version of same form:
https://www.brc.ac.uk/irecord/node/7107/edit

The form allows locations to be selected, from a list held in the locations table with location_type_id 13870 ("PoMS 1km squares").

A couple of weeks ago I added two new locations to the list of "PoMS 1km squares", with location ids 219858 and 219859. However, these two new locations are not appearing in the autocomplete box for the PoMS data entry on the above form.

The location parameters from the form are copied below. I can't see why the two new locations are not being made available. Help please!

[location autocomplete]
@label=1km square
@helpText=Start typing the 1km grid square and select from the list.
@class=control-width-4
@lockable=true
@validation=["required"]
@report=library/locations/locations_autocomplete_for_groups_by_name
@valueField=location_id
@captionField=name
@extraParams={"location_type_id":13870}
@formatFunction="function(item) { return item.name + ' (' + item.code + ')'; }"

**Comment by burkmarr** [comment]
@kitenetter - I've found the root of the problem, but not the answer.  The SQL query which populates that list will only return locations that have an entry in Warehouse groups_locations table that associates the locations to groups (in this case groups 1071 - PoMS targeted surveys or 1073 - 1km square survey - pan-traps).

The two locations you created are not listed in the groups_locations table.

But I don't see how, via the Warehouse website, locations are associated with groups.

Any clue?

**Comment by kitenetter** [comment]
Thanks @burkmarr - that has done the trick in that it has triggered my lousy memory to recall that there is an option to "Manage 1km squares" with the hierarchy for the PoMS activities. I've now added the two missing squares via that route and they are appearing correctly. Should have been able to sort that out for myself but thanks for getting me there in the end! Closing.
