### ISSUE TITLE
Small correction to verification rules

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#667]
In table verification_rule_metadata, the row with id 36653 has an incorrect taxon version key.

Update query to be run:
```sql
update verification_rule_metadata set value='NBNSYS0000173330' where id=36653;
```

(The table currently gives the tvk value incorrectly as 'NHMSYS00173330')

Do we also need to run update sql for the attributes updated_on and updated_by or does the system do that anyway?

**Comment by burkmarr** [comment]
Hi Martin. I think you can do it through the Warehouse - in which case the updated_on etc attributes are done for you. I got the species name and rule type from the DB using your verification_rule_metadata id and then just went to admin > verification rules on the warehouse, filtered on the taxon name and clicked edit on the relevant rule. That takes you here:

http://warehouse1.indicia.org.uk/index.php/verification_rule/edit/15686

I didn't actually do the edit.

**Comment by kitenetter** [comment]
Edit now done - closing.
