### ISSUE TITLE
iRecord search not useful?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#668]
Further to a forum post:
https://www.brc.ac.uk/irecord/node/7831

Options are either:
1. remove the search option
2. put some work into making the search work

**Comment by burkmarr** [comment]
I think there's a few things going on here. 

The search box is a Drupal feature to look for Drual pages (nodes) that include the search text. But from some of the searches the user describes, I wonder if they are are under the impression that they can search for taxon records using it, which they can't.

I don't know why the search on 'iSpot' returns the result it does. The 'not logged in' message is clearly spurious. There are no JS errors reported in Google Chrome. I wondered if search results were somehow cached by Drupal and perhaps this was a result of an earlier cache, but I can't figure it out.

On lots of other searches, JS errors are reported in Google Chrome's development console (e.g. try a search on 'BRC'). In a search on 'Lasius', the message on the page itself - 'Control ID downloadData is duplicated in the page configuration' - is interesting and might give a clue about some of these errors.

A Drupal search results page consists of a compilation of 'teasers' for each of the pages that matches the search request - in other words a portion of the actual page. It looks like teasers for two download pages appearing in the search results page are both incorporating the same control. I don't understand the mechanism of Drupal modules well enough to know if this is something that we can easily sort out in the iForm module. We need @johnvanbreda's input on that.

**Comment by johnvanbreda** [comment]
@burkmarr I suspect the issue here is actually similar for both errors. Drupal is trying to request the teaser and Indicia is just handling this as a standard page build request, so doing too much work. It may, for example, trigger the permissions check for a group related form (hence access denied errors), or render controls (hence the JS).
Fixing in iRecord may not be too hard - there is a method iform_view in iform.module which takes a $view_mode parameter but ignores it. I suspect that this could be used to avoid rendering the form if loading the teaser.

**Comment by burkmarr** [comment]
@johnvanbreda - you are right. We could just put the following at the head of the iform_view method:
```
if ($view_mode == 'search_result') {
    return $node;
  }
```
The search results for most iForm pages would return very little - just their title and first line or so of the body field if used. But this is probably what we want. Do you agree?

**Comment by johnvanbreda** [comment]
I agree.

**Comment by burkmarr** [comment]
Pull request made against develop branch.
