### ISSUE TITLE
Taxonomic filters in Explore become unresponsive

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#67]
In "Explore", when using the filter for "What", the species- or family-level filters can be applied once, but then become unresponsive if you try to use them a second time. I first noticed that problem on Friday 8 July, but a user on the forum suggests it has been there for longer:
http://www.brc.ac.uk/irecord/node/3860

**Comment by johnvanbreda** [comment]
I couldn't reproduce this exactly this morning, though have seen something similar and I could see some areas of code that might be the source of the problem. I've fixed the code - can you let me know if it's OK now please?

**Comment by kitenetter** [comment]
Seems to be working correctly now for me at least - thanks.
