### ISSUE TITLE
BWARS Website - dedicated Indicia recording forms now "missing".

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#672]
I'm not sure if this has been raised already, but since the server upgrade it would appear that all of the dedicated "single species" recording forms on the BWARS website such as those for the Ivy Bee and the Hornet appear to be "missing".  The various website pages say "report a sighting here" but when clicking on what should be the link on the page nothing happens and no form is displayed.

**Comment by johnvanbreda** [comment]
@BirenRathod do you know what has happened here?

**Comment by BirenRathod** [comment]
@MNSmith 
I have restored all forms now, Could you please check if any forms missing?

**Comment by MNSmith** [comment]
All the forms now appear to be back in place.  Thanks.

**Comment by DavidRoy** [comment]
Thanks
