### ISSUE TITLE
Add ability to redet records in bulk

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#674]
Request from verifier to implement redets as a bulk operation for multiple records, in the same way as the verification buttons can be applied to multiple records.

**Comment by MNSmith** [comment]
This would be a useful feature.

**Comment by kitenetter** [comment]
Maybe useful to consider #744 alongside this one?

**Comment by johnvanbreda** [comment]
I wonder if this should be delayed to a later milestone as it's quite a big change and not a current feature?

**Comment by kitenetter** [comment]
No problem. I tried to sneak it in as I think it would be very useful (for me at least!), but if it is larger-scale then it shouldn't take priority over the other issues.

**Comment by sacrevert** [comment]
Just noting that this would also be useful for the NPMS, as mentioned to @kitenetter via email.

**Comment by johnvanbreda** [comment]
Coding done.
