### ISSUE TITLE
Enable verifiers to filter by other verifiers' names

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#675]
We have a very helpful pre-defined filter in the elastic verification page that allows display of all records that have been verified but not by the current verifier, see #559 

What's missing is the ability to add in a column to the grid showing the names of these 'other' verifiers. Can this be added to the options available using the "Column configuration" tool?

**Comment by johnvanbreda** [comment]
Small and looking at related code, so moving to Sept milestone.

**Comment by kitenetter** [comment]
That's great, but we've lost the ability to filter or sort on most columns - I was hoping to use the verifier name column to filter by particular verifier names:

![image](https://user-images.githubusercontent.com/16039111/65884602-0b3fbb80-e391-11e9-9a1d-3757c875972a.png)

**Comment by johnvanbreda** [comment]
Should be restored - I hadn't been through testing the deployment by the point you noticed this.
