### ISSUE TITLE
Grid 'full screen mode' sizing incorrectly

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#676]
In ElasticSearch verify, when Full Screen Mode is enabled on a grid of more than 30 records, the vertical scroll bar fails to show the down-arrow at the bottom and the last row of the grid is not shown completely or not at all. 
The screen size calculation isn't working correctly, whereas it is good in normal mode.
See the two comparative screenshots in which all available scroll bars are dragged down as far as possible.
![Normal Window Mode](https://user-images.githubusercontent.com/24915271/65623627-22ad2c00-dfc0-11e9-8c4e-9496f3526fbe.jpg)
![Full Screen Mode](https://user-images.githubusercontent.com/24915271/65623630-2345c280-dfc0-11e9-9896-30bb879c443c.jpg)

Full Screen Mode also adversely affects other browser windows (accessed using Alt+Tab, for example), preventing the Windows task bar from being shown. The overlapping area of the grid in the ElasticSearch window is shown instead. In the example screenshot my task bar is on the left of the screen. 
![Hidden Taskbar](https://user-images.githubusercontent.com/24915271/65624242-53da2c00-dfc1-11e9-82f5-a588964031e2.jpg)

**Comment by johnvanbreda** [comment]
@kitenetter can you reproduce this? I've not managed to.

Some of this may be beyond our control though as Full Screen behaviour is a browser thing which we just request, not actually our code.

**Comment by DavidHepper** [comment]
Another oddity: in full screen mode there is now no vertical scroll bar. I'm seeing 29 rows (of 500) but cannot even wheelie-mouse scroll the list. The screenshot in my original post that shows such a scroll bar suggests that this is due to a recent code change.

**Comment by DavidRoy** [comment]
which browser?

**Comment by DavidRoy** [comment]
I can replicate in Chrome.  We'll schedule some time to investigate.  The icon design for ticklist, column-select and full screen is a recent change

**Comment by johnvanbreda** [comment]
I've fixed the scroll bar issue in the code ready for the next full release.
