### ISSUE TITLE
Transfer set of records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#677]
A user has set up a new account, having previously used a shared account, and wishes to transfer records from the old account (where they are linked to the wrong recorder name) to the new account. The SQL below is what I think is needed, and I've based the work_queue statement on the models given in #660 

I don't think we should update the created_on field, as there is no need to trigger re-verification of these records, and I'm hoping that the SQL below achieves this - but I have some questions to resolve **before we proceed**.

Question 1: the user also wishes to ensure that the recorder name displayed against the records is their own name, not the name associated with the shared account that they were originally entered under. The records to which this applies are all records added via the iRecord app. My understanding is that the app does not store a separate recorder name, it picks up on the name associated with the account to which the app is linked. If we change the account to which these records are linked, will the app records automatically get updated to the name associated with the new account, or do we need to run a further update query to sort that out?

Question 2: I still need to find out from the recorder if they are still using the UKBMS system - if they do this adds further complication.

DRAFT sql - not for actioning yet:

```sql
update occurrences set created_by_id=233476 AND set updated_by_id=233476 where created_by_id=105432;

insert into work_queue(task, entity, record_id, params, cost_estimate, priority)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2
from occurrences where created_by_id=105432;
```

**Comment by johnvanbreda** [comment]
Here's a query that illustrates there are attribute value records which will need to be updated:
```sql
select o.id, v.text_value, attr.system_function
from occurrences o
join sample_attribute_values v on v.sample_id=o.sample_id
join sample_attributes attr on attr.id=v.sample_attribute_id and coalesce(attr.system_function, '') <> ''
where o.created_by_id=105432
order by o.id;
```

In your SQL, the syntax is slightly wrong because you separate fields to update with a simple comma rather than `AND SET`. The first line should be:
```sql
update occurrences set created_by_id=233476, updated_by_id=233476 where created_by_id=105432;
sql

Once you have updated the attributes, you should also insert tasks for the attrs_json update in the cache table. The task would be 'task_cache_builder_attrs_sample', the entity would be 'sample' and the id to insert should be the distinct list of updated sample IDs. So, something like (not tested!):
```sql
insert into work_queue(task, entity, record_id, params, cost_estimate, priority)
select 'task_cache_builder_attrs_sample', 'sample', id, null, 100, 2
from samples where created_by_id=105432;
```

**Comment by kitenetter** [comment]
Thanks for the additional info @johnvanbreda. However, I think I'm getting out of my depth here. Are you saying that the attributes all need to be updated (e.g. to change the created_by value)?

The problem arises because user Isabel Carter originally inherited an account that was set up for Heather Hathaway, and although she has edited the Drupal account to Isabel Carter, and has been giving Isabel Carter as the recorder name in her records, the app records don't ask for a recorder name, they link to the underlying user identity in the warehouse, which remains as Heather Hathaway. Isabel got frustrated with this and created a new account, and has asked if we can move the app records from the old account into her new account.

(She also has some UKBMS records in the old account but they can stay as they are, she is no longer involved with UKBMS and I'm not sure of the implications of changing the user identity for records linked to UKBMS.)

This is taking a long time to sort out for a small number of records, so I'm seeking the easiest solution. I can see these options:
1. We update the records as I tried to outline above, so that they move from Isabel's old account to her new one - that is what Isabel would ideally like but if it is going to be complex it may not be possible
2. I edit the user name in the warehouse so that the name Heather Hathaway is no longer associated with these records - but if I do that, how do we ensure that the recorder name shown against the app records also changes?
3. We could delete the records from the old account and reimport them into the new, but that would mean that verifiers have to deal with them for a second time, which I would rather avoid.

Would be grateful for advice on the best way forward.

**Comment by johnvanbreda** [comment]
Ok - mistakenly assumed Isabel Carter was the old name were were changing away from. Since all the attribute values are already for Isabel Carter the attr data seems correct. So, it should indeed be possible to follow your original suggestion and just update the created_by_id and updated_by_id values - no need to update the attribute values at all.

**Comment by burkmarr** [comment]
@kitenetter - do you want me to run the SQL?

**Comment by burkmarr** [comment]
@kitenetter - shall I go ahead and do this update?

**Comment by kitenetter** [comment]
@burkmarr give me a few minutes to double-check, will confirm ASAP

**Comment by kitenetter** [comment]
@burkmarr well that took me quite a lot of minutes! The update is good to go, but needs an additional WHERE restriction to limit it to records added via iRecord:

```sql
update occurrences set created_by_id=233476 AND set updated_by_id=233476 
where created_by_id=105432  AND website_id = 23
```

**Comment by burkmarr** [comment]
@kitenetter - that's down now and the cache has been updated from the work queue.
