### ISSUE TITLE
Elasticsearch verification: display external weblinks as clickable links

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#678]
This arises from a request regarding the iSpot data that was imported some years ago. On the old verification page there is a clickable URL that takes you to the observation on iSpot so that any photos can be seen.

On the new page the link is given but is not clickable:

![image](https://user-images.githubusercontent.com/16039111/65698102-eb985280-e073-11e9-9948-dc3b1d793fc0.png)

Can the new page give any such links as clickable, and opening into a new tab.

**Comment by johnvanbreda** [comment]
Small issue so moved to Sept 2019 milestone and fixed in develop branch as working on ES code for other issues.
