### ISSUE TITLE
NBN exports stuck?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#680]
For the last 24 hours or so the NBN export process seems to have got stuck on the "National Trust - full dataset" export, see:
https://www.brc.ac.uk/irecord/exports

Maybe this is just the normal batching process taking its time, but I'm getting worried as I have some NBN Atlas exports that I need to do in the next day or two, please can we check that the process is working as it should.

**Comment by johnvanbreda** [comment]
I had to remove the National Trust export as there was something causing it to keep trying to run. Not sure why. It wouldn't have worked anyway since the location type filter is too slow on PostgreSQL - needs Elasticsearch for reasonable performance.

**Comment by kitenetter** [comment]
@johnvanbreda the NT export process is showing as inactive, but everything else is still queued. Do we need to do some sort of reset? Should I trigger the exports again?

**Comment by johnvanbreda** [comment]
@kitenetter Looks like the NT export had got stuck in such a way it was queued multiple times, preventing anything else getting through. I cleared the queue and reset everything and it seems to be working now.
We should probably schedule in some time to review this process and make it more robust, along with combining it with Elasticsearch.

**Comment by johnvanbreda** [comment]
Fixed the underlying problem that caused the re-queueing so closing.
