### ISSUE TITLE
Elastisearch grid column selection not saving changes.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#681]
Using the Elsatisearch verification grid, I have selected the columns I wish to see on my screen and saved my choices.  However, if I leave iRecord and come back at a later time, certain columns habitually reappear in the grid despite being deselected on a previous visit.

The columns that "reappear" are "Common Name", "VC No.", "Checks" and "Last Updated".

**Comment by kitenetter** [comment]
@MNSmith is this still a problem for you? As far as I can tell my own choices on the verification grid are getting saved between sessions.

**Comment by MNSmith** [comment]
It seems to be keeping the requested changes / layout at present
