### ISSUE TITLE
Species map page - allow users to save a set of selected species

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#687]
User request for enhancement to the species maps (https://www.brc.ac.uk/irecord/species-maps): it can take some time to build up a set of species to map in one go, and there is no way of saving the chosen set. The user wishes to be able to "save this as a personalised "mini-atlas" that I could then load up again in future, rather than having to create it from scratch again".

Maybe a link here with the scratchpads functions discussed elsewhere, e.g. #673 

Maybe needs consideration as part of a wider review of the UI for querying, analysing and mapping records.

**Comment by MNSmith** [comment]
This would be useful.

**Comment by kitenetter** [comment]
This doesn't seem to have been requested again, Deferring.
