### ISSUE TITLE
Problem with user email

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#688]
User Rachel Bicker has recently updated her email address on the iRecord website. The email address seems to have saved okay, but she got an error message:

![image](https://user-images.githubusercontent.com/16039111/66217872-fed49f00-e6bf-11e9-9759-461536b1491c.png)

Subsequently she is continuing to receive iRecord notifications to her old email address. In the warehouse she is user_id 700, which lists three email address identifiers (including the new one that she has recently moved to).

I would have expected that if a user edits their email address via the iRecord website, the newly edited address should be the one that we use to send notifications. Is that what usually happens, and are the problems in this case the result of the above error message?

**Comment by johnvanbreda** [comment]
There was another account for BeeWalk which had that email address associated. I've moved the records to the main account for Rachel and deleted the BeeWalk account (the user ID link to the warehouse will update next time she logs in) using this script:
```sql
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
from occurrences where deleted=false and created_by_id=90269 and website_id=48 order by id;

update occurrences set created_by_id=700 where created_by_id=90269 and website_id=48;
update occurrences set updated_by_id=700 where updated_by_id=90269 and website_id=48;
update cache_occurrences_functional set created_by_id=700 where created_by_id=90269;
update users set deleted=true, updated_on=now(), updated_by_id=3 where id=90269;
update people set deleted=true, updated_on=now(), updated_by_id=3 where id=90610;
update people set email_address='r....com' where id=705;
```
