### ISSUE TITLE
Records missing from LERC indexing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#689]
We appear to have an issue with some records not having been assigned to their LERC boundary, that may be linked to the changes that took place in Feb 2019. This has been reported by South West Scotland Environmental Information Centre. Their LERC boundary was one of the ones that changed significantly when we had the updated boundaries from ALERC, in fact it may even have come in as a new boundary at that time. Previously we had given them a custom download for the range of vice-counties that overlap their LERC region.

It appears that the new LERC boundary is correctly retrieving all records added since approx. 22 Feb 2019, but records added before that time are not all being included - oddly some of them are, but a large chunk that fall within vice-county Ayrshire are not being included in the LERC boundary filtering.

This is urgent for the South West Scotland LERC as they need to be able to access the iRecord data for a report they are working on.

Not sure if this is an issue with the map boundaries themselves, or (more likely?) with the indexing against those boundaries.

**Comment by burkmarr** [comment]
> changes that took place in Feb 2019

@kitenetter - what changes are those? The major LERC boundary changes I carried out were in June 2019 - are you referring to something else here?

**Comment by burkmarr** [comment]
@kitenetter. If I go to Explore all records, filter on South West Scotland Environmental Information Centre boundary and ask for all records for the last five years, I get some 26,000 records going right back to 2014. I don't seem to be able to reproduce the problem.

**Comment by kitenetter** [comment]
@burkmarr sorry, I was getting muddled. The date of 22 Feb is when the ERC thinks records started getting indexed properly. I had a feeling that date coincided with some problems we had with indexing due to the performance issues that hit us around that time, but that's just from my unreliable memory.

I will forward you the LERC email which gives screenshots of the problem - I was able to reproduce them last week.

**Comment by burkmarr** [comment]
Thanks @kitenetter - I can see the problem now (including the images below for clarity). I've had a look at the task_spatial_indiex_builder_location.php code and I can see no reason why the re-indexing would not have picked up all overlapping samples/occurrences when this particular location - South West Scotland Environmental Information Centre (id 1437) - was updated in June this year.

The update was done through the Warehouse ORM from a shapefile - the location 1437 changed both its name and extent (the previous extent is show in the third image below).

@johnvanbreda I guess the first thing to try is reindexing the location, would you agree? If so, can you cast your eye over it the work_queue insert below before I run it?

```sql
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
values('task_spatial_index_builder_location', 'location', 1437, 70, 2, now()) 
```
Image below shows August 2018 records for South West Scotland Environmental Information Centre:
![search1](https://user-images.githubusercontent.com/9275178/66303275-9b7e8300-e8f2-11e9-93fa-c65016fcedf7.png)

Image below shows August 2018 records for VC75 - many of these records also overlap the LERC boundary but were not picked up on the previous query:
![search2](https://user-images.githubusercontent.com/9275178/66303325-b3ee9d80-e8f2-11e9-8a3e-4cd961af8785.png)

Extent of location 1437 before change in June (at which time it was called the Dumfries and Galloway Environmental Resources Centre):
![x](https://user-images.githubusercontent.com/9275178/66304536-560f8500-e8f5-11e9-9451-5ad8e5de74da.JPG)

**Comment by johnvanbreda** [comment]
@burkmarr I agree - re-indexing this location is a sensible next step and your query looks fine. We did fix some performance issues and issues relating to indexing large locations early in the year, so what Martin says makes sense. Therefore I'm hopeful that after re-indexing it should be fine.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda. @kitenetter - it's now in the work_queue (id 31987127). If this fixes the problem I guess we'll need to talk about rerunning the spatial index builder on many, if not all, locations in this layer (and maybe one or two other layers)?

**Comment by kitenetter** [comment]
@burkmarr do you know when this indexing will be complete? I need to let SWSEIC know when they will be able to access a complete dataset.

**Comment by burkmarr** [comment]
Looks like it already run @kitenetter and it appears to have worked.

![x](https://user-images.githubusercontent.com/9275178/66323566-e5c82a00-e91b-11e9-8bcb-b9e975c73d1b.JPG)

**Comment by kitenetter** [comment]
Excellent! But can I just double-check: do you know for sure that there are not any records still waiting to be indexed that might fill in that gap in the middle of Ayrshire? Don't want to give SWSEIC the go-ahead until we know that everything is up-to-date! @burkmarr

**Comment by burkmarr** [comment]
That map is only for a single month - August 2018 - so bound to be a bit gappy. As far as I am aware, the fact that the job has vanished from the work_queue means that it is completed - I don't think they go until the job has completed or failed. Is that right @johnvanbreda?

**Comment by johnvanbreda** [comment]
That's correct @burkmarr. If the task fails it gets left in the queue with the claimed_by field still set (and hopefully some info in error_detail).

**Comment by burkmarr** [comment]
Are you happy to close this now @kitenetter?

**Comment by kitenetter** [comment]
As far as I'm aware this is all resolved now, thanks. Closing.
