### ISSUE TITLE
Better distinction between pop-ups for accepting or rejecting records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#69]
This request arose when a verifier appeared to reject a record without providing any reason for doing so. It turned out that the rejection was made in error, when the verifier clicked on the wrong button. 

Can the pop-up dialogs that appears after clicking on the verification buttons be distinguished more clearly, e.g. by the dialog boxes being different colours for Accepted vs Not accepted?

**Comment by johnvanbreda** [comment]
Now done and will be deployed on the next code release.
