### ISSUE TITLE
User birth date

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#690]
This may be a bug in my brain rather than in the system, but a user wants to edit the date of birth that is shown on their iRecord account page. I can't find anywhere on the iRecord website or in the User and People parts of the warehouse interface that would allow me (or the user themselves) to make the change.

Am I overlooking something obvious?

**Comment by johnvanbreda** [comment]
The account edit form control ordering had gone wrong and it was right at the bottom of the page. I've fixed that.

Note though that the DOB field only appears when the Under 16 box is ticked (as we consider it irrelevant otherwise) so if they want to change it and are now over 16 they have to tick this box at least temporarily.

**Comment by kitenetter** [comment]
I've had some more requests for dates of birth to be removed, and it appears that users are being assigned dates of birth without ticking the under-16 box. I've checked half a dozen recently registered users and four have been given dates of birth that seem unlikely to be genuine.

Can we prevent dates of birth being added where not needed?

**Comment by kitenetter** [comment]
Also, I can't find any way of removing an incorrect date of birth from the drupal account page. I can only see the date of birth if I tick the under-16 box, and of course once that box is ticked I cannot save the form with a blank date of birth.

**Comment by johnvanbreda** [comment]
Issues with date of birth defaulting to today's date even if box unticked and then saving a date of birth when box unticked both fixed. I've also cleaned up the existing user accounts where they were not under 16 but had a DOB this year. I've also cleaned up the existing accounts where under 16 was unticked but DOB was recent.
