### ISSUE TITLE
Update records where auto-verification has been wrongly applied

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#692]
This issue should be tackled once #486 is closed.

As described in that issue, there are some records to which auto-verification has been applied inappropriately, mostly related to the records of taxa other than butterflies that get added to the UKBMS dataset. Such records are shown as accepted, with verifier "admin, core" and with record_decision_source given as "machine".

The set of records to be updated are all those records in the UKBMS dataset that are not of butterflies and that are currently shown as having been verified by admin core. I think there are 39,609 records in total (predominantly moths and dragonflies). These records can be found via:

```sql
SELECT o.id, o.verified_by_id, t.taxon_group_id
FROM occurrences o
JOIN taxa_taxon_lists ttl ON o.taxa_taxon_list_id = ttl.id
JOIN taxa t ON ttl.taxon_id = t.id
WHERE o.verified_by_id=1 AND o.training=false AND o.website_id=27 AND t.taxon_group_id<>104
```

For each of the records defined in the above query, we need to:
- set o.record_status to 'C'
- set o.verified_by_id to Null
- set o.verified_on to Null
- set o.record_substatus to Null
- set o.record_decision_source to Null

(and then ensure these updates feed through to the cache tables as usual)

@johnvanbreda do we also need to update o.last_verification_check_date (I don't know what that does)?

@burkmarr do you need any more information?

**Comment by kitenetter** [comment]
P.S. please let me know when we get to the point of being ready to implement this, so that we can forewarn the moth and dragonfly verifiers.

**Comment by burkmarr** [comment]
@kitenetter - I think that's probably all I need.

**Comment by johnvanbreda** [comment]
> do we also need to update o.last_verification_check_date (I don't know what that does)?

No - that relates to when the Record Cleaner rules were last applied to the record.

**Comment by burkmarr** [comment]
@kitenetter and @johnvanbreda - looking at the auto-verifier code raised a couple of questions in my mind re this issue.

1. As well as the fields listed by Martin above, the auto-verifier also sets ```occurrences.release_status``` to 'R', but looking at newly added unverified records, this is also the default value for that field, so presumably okay to leave as is. Is that correct?

2. The auto-verifier also inserts records into the ```occurrence_comments``` table. These have their ```created_on``` field set with the same timestamp used to set the ```verified_on``` field of the ```occurrences``` table. That means we could find thse and set their ```deleted``` attribute to true by matching their ```occurrence_id``` and ```created_on``` fields to the records we are going to modify in the ```occurrences``` table before we modify them. Is that something we should do to avoid a confusing verification history or should that be left untouched?

(I know that we don't want to do any of this until the auto-verification taxon filter is implemented on the UKBMS surveys - at this stage I'm just trying to understand what needs to be done.)

**Comment by johnvanbreda** [comment]
1. I'm not sure why the auto-verifier would set release status. Records might be unreleased for a few reasons, e.g. they belong to a Consultants Portal project where the data cannot be released till the end, or a project where the data are low quality so need to be held back until someone sanity checks them. Or an Asian Hornet record that is not supposed to be seen until checked. I don't think the auto verifier should change these records?
2. Yes, I can see why you might want to clean these comments up when you undo any auto-verifications.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I'll incorporate the comments cleanup then. Sounds like the release flag might be something for another issue.

**Comment by burkmarr** [comment]
@kitenetter - given the state of play with the related issue https://github.com/BiologicalRecordsCentre/iRecord/issues/486 - do you want me to tackle this now or wait for a while to see how things go with that?

**Comment by burkmarr** [comment]
@kitenetter. I'm getting the SQL ready for this now, but I won't run until you give me the okay. Here are the number of records against each of the taxonomic groups so that you can give the scheme organisers notice in cases where totals are big:

![image](https://user-images.githubusercontent.com/9275178/69947240-28098400-14e5-11ea-9ae8-c42a7b331978.png)

Let me know when it's okay for me to go ahead.

**Comment by kitenetter** [comment]
I am currently drafting a newsletter for verifiers that will forewarn of the reinstatement of the above records, so we need to hang on for a short while longer before proceeding.

**Comment by kitenetter** [comment]
The newsletter has gone out, and no-one has objected, so I think we can go ahead with reinstating these records.

**Comment by burkmarr** [comment]
@kitenetter - the occurrence records and the associated occurrence_comments are updated and cache_builder_update tasks inserted into the work queue - they will take a bit of time to work through.

**Comment by burkmarr** [comment]
@kitenetter - all those work queue tasks have completed, now. So I think that this is done.
