### ISSUE TITLE
Add human/machine verification source to cache table?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#693]
I think it would be useful to have occurrence.record_decision_source as a column in one of the cache tables (presumably cache_occurrences_nonfunctional?).

**Comment by johnvanbreda** [comment]
When doing this, also consider #694 which also needs an extra field.

**Comment by kitenetter** [comment]
Do we also need to consider adding these fields to the elasticsearch table as well, in order to make it available for downloads and analysis?

**Comment by kitenetter** [comment]
This is now available in the ES data. Closing.
