### ISSUE TITLE
Elastic verification: record not updated in grid following redet

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#695]
I redetermined this record during the evening of 8 October:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=10936473

24 hours later it is still displaying in the new verification grid under its original determination, not the new one. I'm nervous of verifying it while the incorrect name is still displayed.

Same issue with this redetermined record:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=8736574

While verifying last night I did get a couple of error messages about the elastic search query having failed, although the grid remained active and it appeared that I could carry on. But perhaps some update failed to work? But I'm speculating.

**Comment by DavidRoy** [comment]
I have the same issue with redeterminations I've made:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=7078877

I've added to the October milestone given the effect on verifiers

**Comment by kitenetter** [comment]
I wanted to clear these records from my gird, so I verified them using the old verification page (where they were correctly displayed with the redetermined taxon name). However, even after verification they are still showing as 'pending' on the new verification page, as well as remining under their original identification. It seems that the redet process has somehow caused them to get stuck in the elastic dataset.

Example record IDs:
- 10936473
- 8736574
- 5330636
- 10316897

**Comment by johnvanbreda** [comment]
I've fixed the bug so the record disappears from the grid (it's actually flagged as "dirty" so disappears from the Elasticsearch alias temporarily until Logstash updates the record properly). 

Some of the above issues are probably due to delays caused when doing a full ES update - I've now set this up so when required, the full refresh can run simultaneously to the recent updates.
