### ISSUE TITLE
Feature Request - Complete "identified by" field on Re-det.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#696]
Possibly an associated addition / feature to #694 .  I am currently re-deting a lot of records.  It would seem sensible that the name of the Verifier doing the re-det is added to the record in the "Identified by" field, as essentially that is what a re-det means, the ID had not been provided by the original Recorder.  This would be useful for other team members to see when looking at the record and could be used in part to give more information on the "experience" level of the Recorder over time.

**Comment by kitenetter** [comment]
@MNSmith I'm pretty sure that this is what is already being done. It wasn't done on the older records but for some time now the redets should show update the determiner field as well as the species name.

If that's not worknig for you could you let us have a record ID example.

**Comment by kitenetter** [comment]
Actually I have now found an anomaly here:

https://www.brc.ac.uk/irecord/record-details?occurrence_id=10521688
This is one that I redetermined, and it is now showing "Identified by" as being me.

https://www.brc.ac.uk/irecord/record-details?occurrence_id=10743334
Another that I redetermined, but there is apparently no "Identified by" attribute.

Both these records originate from the "iRecord general" survey. It's possilbe that one was redetted via the new verification page and one via the old, but I don't know.

**Comment by MNSmith** [comment]
A couple of issues are preventing me from checking if the process of putting the re-determiner name into the "Determiner / identified by" field.

1) Inconsistent display of record details.  Depending on the source of the record, different fields are displayed at different places in the Record Details pane.  The "identified by" field appears in the record attribute box in Elastisearch.  In some records from particular sources the field (e.g. iRecord app) the appears to be "missing" .  In others the presence or absence of this field in the record pane appears to be dependant on whether or not the field is populated with data.  If there is a name the field is displayed, if there is no data then it is "missing.

Examples:
9411790 - iRecord App - no "identified by" field shown.
10483303 - iRecord General data - no "identified by" field shown
11258436 - iRecord General data - "identified by" populated and visible.

When verifying records on a grid from multiple sources it is one of the biggest irritations of iRecord that key fields for from all sources are not displayed in a standardised manner, and that one has to search the record details pane for the information required.  I have asked multiple times for some standardisation in the display of records for the key fields.  If there is no name present in the identifier field then the field title should still be displayed on all occasions, regardless of whether the field is populated or not.  A fixed, standardised display of the key record details is essential to quick verification.

2)  The records I am currently re-detting are those submitted via the Asian Hornet Watch app.  The record details pane does not apparently display an "identified by" field even for re-detted records so i cannot tell if my name is being put in the identifier field.  See 11937500.

**Comment by MNSmith** [comment]
As an addition to my original comment, would it be possilbe to add an icon or change the colour of the record background in the grid so that re-detted record are more obvious?

**Comment by kitenetter** [comment]
@MNSmith one option here is that on the new verification page it is possible to add a "determiner" column to the grid of records, which would then enable you to filter by determiner, and to see more easily when a record has been determined by someone other than the recorder.

**Comment by kitenetter** [comment]
But that still leaves an issue with records that do not display a determiner following a redet. Example: both of these records were redetermined by me, but only one now shows a determiner (I think the determiner name is only being updated is the original recorder gave a determiner name):

![image](https://user-images.githubusercontent.com/16039111/72109870-bc5dd680-332e-11ea-8570-9524fb6d3f2a.png)

**Comment by MNSmith** [comment]
Just a note to avoid confusion over record fields here.  When entering a record there is the option to complete the "Identified by" field on the input screen.  This information is displayed on the grid in the "Determiner" field.  I'm ok with this terminology but there may be some potential for confusion over the use of this word and / or column headers.  It would seem sensible to be consistent with terminology across pages, so should we consider renaming the "Determiner" column to "Identified by"?

**Comment by kitenetter** [comment]
Issue clarified under #899 - closing this one.
