### ISSUE TITLE
Verification anomalies

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#698]
One of our verifiers has reported another mismatch between the new and the old verification pages, which may relate to previous issues such as #671, but some additional odd things seem to be happening.

The initial discrepancy was reported as:
> The first record that now shows on verify new is ID 744278. 
> If I switch to verify I can see a lot more records the first on the list is ID 119711285.

I can replicate that via a masquerade.

I tried to check a few records in more detail, and found this for record id 11746908:
- on the main record display page it is showing as "Awaiting review": https://www.brc.ac.uk/irecord/record-details?occurrence_id=11746908
- on the old verification page it is showing as "Not reviewed"
- on the new verification page, if I filter to show all records, it is showing as "Accepted as considered correct" (and if I revert to the list of pending records it is not visible)

I can find other examples of records that are unreviewed on the old page, and apparently accepted on the new page. I can also find records on the old page that are just not visible at all on the new page.

So far I'm only aware of this in relation to this particular verifier: Warehouse User ID 196426

**Comment by kitenetter** [comment]
I've just set up a new verifier and on his new verification page there are no records showing as having been added since 7 October, while on the old page it runs up till today. I can't see any indication of verification status mismatches though.

**Comment by johnvanbreda** [comment]
Note to self - review this after the current re-index (which fixes several issues) has been processed, probably around 23rd Oct.

**Comment by kitenetter** [comment]
Have had an update from the user who originally reported this issue:

> Last week you sorted out a problem for me in as much as the records when I go to verify them are in the old system (verify). If I go to verify new there are several pages of records that do not appear. This was sorted a week or so ago but now appears to be happening again:
> The first record that I have in Verify new is ID 7432916 Clowes Elizabeth.
> The first record that I have in Verify is ID 12023814  Smailing Pipa.

If I masquerade as that user I can replicate this issue. Record id 12023814 was added at 13:28 on 23 October 2019, and correctly shows as awaiting review on the old page, but does not appear on the new page even if filtering for all records.

Record id 7432916 was submitted on 29/07/2018 13:21, and last updated on 13/02/2019 18:31 (UKBMS record).

There are about 307 pending records visible on the old verification page that have not appeared on the new verification page.

Record id 11746908 is still showing as awaiting review on the old page, but on the new page shows as considered correct.

**Comment by kitenetter** [comment]
I don't know if this is related, but documenting in case it is. Earlier this week I managed to bulk verify c. 9,000 records by mistake. I asked @burkmarr to run an update query to reset the verication status to pending. This appears to have worked as intended in the data warehouse, and all records are as expected in the old verification page, but in the new page only about 2,500 of the 9,000 have reappeared as pending.

**Comment by kitenetter** [comment]
The records that were missing from my own verification grid have now reappeared (22:52, Sat 26 Oct). Will check the other user tomorrow.

**Comment by johnvanbreda** [comment]
I think my own verification grids look pretty much in sync now so can this be closed @kitenetter?

**Comment by kitenetter** [comment]
@johnvanbreda verifier user id 196426 still has a very large mismatch between what he is seeing on the old and new pages, and for that user we still have an unexplained issues around records such as id 11746908 which is showing as unverified on the old page (and on the individual record's details page) but showing as verified on the new.

As previously mentioned this seems to be specific to this one verifier, I've not had similar reports from others.

See also #705

**Comment by johnvanbreda** [comment]
This should all clear up after the latest refresh (about 1 day to completion).

**Comment by kitenetter** [comment]
Review to check all is okay

**Comment by kitenetter** [comment]
@johnvanbreda for this particular verifier (user id 196426) there are still some niggling discrepancies. At the moment I can see:
- Old verification page, pending records = 6,017
- New verification page, pending records = 5,866
- Old verification page, accepted records = 48,028
- New verification page, accepted records = 48,157

This is a lot closer than it was when this issue was first reported, but understandably the verifier concerned is still worried that records are getting lost.

**Comment by kitenetter** [comment]
Update at 7 January 2020:

- Old verification page, pending records = 3,645
- New verification page, pending records = 3,645
- Old verification page, accepted records = can't get a total to come up at the moment
- New verification page, accepted records = 50,356

Record ID 11746908 is now consistent on the old and new pages as well, so it looks like this is resolved. Closing.
