### ISSUE TITLE
Verify - new: date ranges not working in filters

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#699]
The field help (mouseover popup) for filter fields of type Date indicates that they support Ranges but give an inappropriate example "123-456". Unsurprisingly, entering a date range as "2015-01-01-2018-12-31" doesn't work. Entering a single year "2010" doesn't select all records within that year. Is there or will there be a range option? Supporting conditions like ">2014" would be most useful.

**Comment by kitenetter** [comment]
This is one of a number of issues relating to the column-head filter boxes and the syntax they can recognise.

David H has pointed out that there are currently two different "Date" columns within the elastic verification grid layout options, and it appears that the column-haed filters behave differently in the two different versions - certainly the mouse-over text is different.

**Comment by johnvanbreda** [comment]
The 2 date fields have been fixed. The remaining date field has been updated in the code to support the following formats:
* dd/mm/yyyy
* yyyy-mm-dd
* yyyy
* yyyy-yyyy
The hint has been updated to reflect this.
