### ISSUE TITLE
NBN data exports - date type error

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#70]
This arises from exporting data to the NBN Gateway using the data flow filters.

Where we have records that have been assigned to a vague date for a whole year (e.g. 01-01-2015 to 31-12-2015), at least some are being given a DateType of "YY". They should instead have a DateType of "Y".

Examples - occurrence numbers:
- 571000
- 572662
- 570898

Not sure if this error also occurs in user and LRC downloads when the "NBN Exchange" format is chosen.

**Comment by johnvanbreda** [comment]
I've fixed the records using the following one off script:

```sql
update samples set date_type='Y' where date_type='YY' and extract('year' from date_start) = extract('year' from date_end);
update cache_samples_functional set date_type='Y' where date_type='YY' and extract('year' from date_start) = extract('year' from date_end);
update cache_occurrences_functional set date_type='Y' where date_type='YY' and extract('year' from date_start) = extract('year' from date_end);
```
