### ISSUE TITLE
Revise stage terms for bryophyte form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#701]
Following discussions with @sacrevert we agreed to remove the tick box for "fruiting" and instead to add a dropdown for "stage" on the bryophyte recording form:
https://www.brc.ac.uk/irecord/enter_bryophyte_records

This is to bring the taxon-specific bryophyte form into line with the proposals for stage terms in #637

Terms to be used:
- not recorded
- gametophyte (not fruiting)
- sporophyte present (fruiting)

**Comment by kitenetter** [comment]
@kazlauskis this has implications for the app. Currently, the app has a set of dynamic attributes for mosses that includes "Fruit" as a boolean attribute (occurrence attribute id 471).

Following the above change, the website form no longer has that boolean attribute, and instead has a text (termlist) attribute called "Stage (bryophyte)", occurrence attribute id 807.

When the main website moves to dynamic attributes for #637 the standard forms will include the "Stage (bryophyte)" occurrence attribute. So it would be ideal if the app followed the same change.

**Comment by kazlauskis** [comment]
Yeah, I wondered about the existing bryophyte attributes. There shouldn't be a problem to phase the old attributes out. Each record from the app has an edit form attached to it, so any old ones will point to the old form and newer ones with new attributes should point to this new form.

**Comment by kitenetter** [comment]
Form on iRecord now updated, closing.
