### ISSUE TITLE
Tidy up plant record status termlist on BSBI recording form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#702]
Following discussions with @japonicus @sacrevert and Kevin Walker we agreed to revise the status termlist used in the BSBI form:
https://www.brc.ac.uk/irecord/enter-vascular-plants

so that it matches the one currently used by BSBI, as provided by Kevin.

Note that we agreed that where the BSBI list had "unknown" we will use "not recorded" - this change may need to be reflected in the DDb?

Issue derives from #637

**Comment by kitenetter** [comment]
@johnvanbreda I see that the BSBI plant record status termlist:
http://warehouse1.indicia.org.uk/index.php/termlist/edit/460

has also been used by the National Trust. Should I consult them before making changes?

The proposal is to mark most of the existing terms as 'not for data entry' and to replace them with a new set of terms:

![image](https://user-images.githubusercontent.com/16039111/67207741-10ca7780-f40c-11e9-94f6-d846daeaa555.png)

**Comment by johnvanbreda** [comment]
Yes please if that's OK. If necessary I could move them to a different termlist but it might need a bit of fiddling in the data.

**Comment by kitenetter** [comment]
No problem from NT perspective

**Comment by kitenetter** [comment]
Plant status term list now updated as per the tables shown above, see:
http://warehouse1.indicia.org.uk/index.php/termlist/edit/460

Closing.

**Comment by japonicus** [comment]
@kitenetter is the update live yet, as at present the status list on the vascular plant form is showing a slightly odd mixture of codes:

![screenshot 2020-01-07 12 47 35](https://user-images.githubusercontent.com/207360/71897133-92998980-314d-11ea-86bd-eae0c23ca99e.png)

**Comment by kitenetter** [comment]
@japonicus something odd happened with the caching I think - I've freshed the cache and it's okay for me now, has it updated for you?

**Comment by japonicus** [comment]
Yes, it's fine now. Thanks.
