### ISSUE TITLE
Elasticsearch: records discrepancy with old page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#705]
These six records are currently showing on the old verification page for Berkshire moths, but not on the new. Not a problem while both pages are available, but of course will become a problem when we switch entirely to the new page. I can't see anything they have in common that might provide an explanation.

Record IDs:
942546
10519952
10585250
10585258
10585277
11092327

**Comment by johnvanbreda** [comment]
I'm hopeful I've just fixed the underlying bug that could cause records to get indexed without their linked locations. I've started a refresh of the Elasticsearch data to tidy up any records that were affected.
This can be closed if the records appear in the next day or 2.

**Comment by kitenetter** [comment]
This is no longer a problem - closing.
