### ISSUE TITLE
LRCs cannot see Dragonfly abundances in their downloads

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#708]
Dragonfly abundance values on most forms (including the generic iRecord App) are stored in custom attributes, not the standard Stage/Count fields. I'm informed (but cannot confirm) that LRCs have their own download system from iRecord and are unable to collect custom attributes because they cannot specify a Survey code. If true, this makes most downloaded records of dragonflies uselessly incomplete.
Although I can think of several possible ways to overcome this they are too involved to list here and could have undesirable side-effects. Could we discuss please? 
I would expect that this issue applies similarly to other groups than Dragonflies.
The more general related issue (helpfully suggested by GitHub whilst entering this) around downloading custom fields is #75 from three years' ago.

**Comment by kitenetter** [comment]
Needs to be considered as part of the wider issue of how to deal with custom attributes for downloads.

Single abundance attributes per record should be dealt with by the 'system function' feature. Multiple abundance attributes per record are more problematic.

**Comment by kitenetter** [comment]
It is possible to download the custom attributes on a single survey basis, but it remains problematic to deal with for multiple surveys. Under review elsewhere, although no immediate solutions are currently available. Closing this one.
