### ISSUE TITLE
NBN export process not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#709]
This month all of the zip files produced by the NBN export process have resulted in invalid files. Previously it was only the larger datasets that were invalid, this time it is all of them.

**Comment by kitenetter** [comment]
Try regenerating at another time.

**Comment by kitenetter** [comment]
@johnvanbreda is there an existing XML file or similar that we use to create the NBN export files (Darwin core format)? If so, does it contain the SQL that I could adapt in order to do a manual export from pgAdmin?

**Comment by johnvanbreda** [comment]
@kitenetter the intention was that failed exports would create a readme inside the zip file with instructions on how to run the query manually and repair the file. There was however a bug preventing this happening so I've fixed the bug. The ladybirds file generated this morning shows this process in action.

**Comment by kitenetter** [comment]
The larger files are mostly failing to generate but the manual query operation will suffice until we are able to move to a more automated system. Closing.
