### ISSUE TITLE
json attributes missing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#710]
I've been extracting sample data from the PoMS surveys using the attrs_json attribute In table cache_samples_nonfunctional. In a small number of cases attrs_json is null, even though the full set of attributes were recorded.

How is attrs_json created, is that done during the creation of cache_samples_nonfunctional? Is it possible that this process fails sometimes (I guess it must be?). Can we do anything to guard against this?

**Comment by kitenetter** [comment]
record ID examples to follow

**Comment by johnvanbreda** [comment]
I've not managed to find a reason, but I've ran the following script which reschedules these records in the work queue so the attrs_json gets populated:

```sql
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_attrs_occurrence', 'occurrence', o.id, 100, 3, now()
from cache_occurrences_nonfunctional o
join occurrence_attribute_values v on v.occurrence_id=o.id and v.deleted=false
where o.attrs_json is null
and o.id < (select max(id) from occurrences where created_on<now() - '1 hour'::interval);

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_attrs_sample', 'sample', s.id, 100, 3, now()
from cache_samples_nonfunctional s
join sample_attribute_values v on v.sample_id=s.id and v.deleted=false
where s.attrs_json is null
and s.id < (select max(id) from samples where created_on<now() - '1 hour'::interval);
```
