### ISSUE TITLE
user message when nominatim placename search not working on casual/list entry forms

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#711]
We use nominatim for place-name searches.  It seems like the service is having problems:
https://nominatim.openstreetmap.org/

One quick solution is giving a message to the user when the search does not work.  Currently, nothing happens when the search button is selected

**Comment by burkmarr** [comment]
@DavidRoy - the Nominatim service appears to be back up now. We could have switched individual iRecord forms over to Google georeferencer service, but it would be a pain to do that individually and then to change them back if/when service was restored. I've done some work to enable us to override the georeferencer service on a site-wide basis. This is in the two pull requests referenced above.

**Comment by burkmarr** [comment]
I've put a sample file (georeferencing.json.example) in ```irecord\sites\default\files\iform_user_ui_options``` on the iRecord website server. If we ever need to override the goereferencing for the whole site (e.g. loss of service) then simply rename file, removing '.example' so that the file has a 'json' extension and then edit to select the georeferencing service to set.
```json
{
  "georeferencing_override": {
    "title": "Georeferencing services override",
    "description": "Presents a single option so it won't be presented to user and just applied across pages",
    "choices": {
      "default": {
        "title": "",
        "description": "Set to one of google_places, nominatim, geoportal_lu, indicia_locations",
        "params": {
          "georefDriver": "nominatim"
        }
      }
    }
  }
}
```
