### ISSUE TITLE
New verification page unavailable

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#712]
Error message currently being displayed on new verification page:

Page load failed: An error occurred whilst connecting to Elasticsearch. Elasticsearch request _mapping (GET) disallowed by Warehouse REST API proxy configuration.

**Comment by johnvanbreda** [comment]
Fixed. I'd just done an upgrade to new code which supports Elasticsearch 6 & 7, so needed to select v6 in the Indicia settings.
