### ISSUE TITLE
Wrong taxon names assigned to records from iSpot in iRecord (may be iSpot bug)

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#714]
[Andy Amphlett has noticed](https://database.bsbi.org/forum/viewtopic.php?f=3&t=439&p=1214#p1214) that records of _Sagina procumbens_ imported from iSpot appear in iRecord as _Sagina maritima_.

e.g. https://www.brc.ac.uk/irecord/record-details?occurrence_id=206470
=> https://www.ispotnature.org/communities/uk-and-ireland/view/observation/26974/procumbent-pearlwort

**Comment by japonicus** [comment]
Also the same issue for _Geranium pratense_ as _himalayense_

e.g.
https://www.brc.ac.uk/irecord/record-details/?occurrence_id=194714
=> https://www.ispotnature.org/communities/uk-and-ireland/view/observation/8136/meadow-cranes-bill-geranium-pratense

**Comment by japonicus** [comment]
Also some but not all Matthiola incana transformed to Matthiola fruticulosa
Oxalis corniculata transformed to dillenii 

Possibly a related issue with Lysimachia punctata on ispot transformed to Lysimachia ciliata on iRecord. In this case there may be taxonomic confusion as while punctata and ciliata are accepted distinct names, there is a non-accepted name Lysimachia ciliata **auct., non L.** which is a synonym of punctata

**Comment by japonicus** [comment]
I've realised this is probably an iSpot bug, as there is something odd with the related links on the iSpot pages using the mismatched taxon, e.g.

https://www.ispotnature.org/communities/uk-and-ireland/view/observation/8136/meadow-cranes-bill-geranium-pratense
![image](https://user-images.githubusercontent.com/207360/68861199-f752dd80-06e2-11ea-8873-d5c83a3baacf.png)

and similar for the other mismatches identified above.

**Comment by kitenetter** [comment]
As far as I can see there have been no changes or updates to these records recently, not at the iRecord end nor at the iSpot end. Which presumably means the error has always been there.

I don't know how names were matched when importing the iSpot data, i.e. whether we used scientific name or TVK. There are 34 iRecord occurrences for Geranium himalayense, all but one of which originate from iSpot (the single exception is from another imported dataset).

If these were imported based on matching the taxon name string perhaps they got linked to the wrong recommended taxon? However, I've just imported a single records of "Geranium pratense" and it has correctly linked to the 'real' Geranium pratense.

Not sure if there is any particular action we can take, or whether we need to leave it to verifiers to reject/redetermine these records as appropriate?

**Comment by japonicus** [comment]
Is there anyone at iSpot who could pick this up - from the screenshot I eventually posted of their website it looks as though this is a bug at their end rather than with the iRecord import process (which had been what I'd suspected initially). A cursory look suggests 4 or 5 vascular plants affected, but that's from just a quick review of quite a small data sample and this problem could also be more widespread than just plants.

If it is just the few plants that I've spotted then bulk re-determination in iRecord might solve the problem. I'm not sure that one could rely of verifiers noticing and understanding the issue. It wouldn't be the type of error that they are looking for routinely - checking the source record v's the iRecord copy. Records might just be rejected rather than corrected.

**Comment by kitenetter** [comment]
I've checked the raw data file supplied by iSpot in 2013 and that contains the himalayense mismatch, so it is not an error that has been introduced within iRecord. I will check that raw data file to see if any other mismatches stand out, and then we can decide whether to update them within iRecord, and of course we can let iSpot know. Note that there have been no further imports from iSpot since 2013 so this is not an ongoing issue.

**Comment by kitenetter** [comment]
Reported to iSpot - closing.
