### ISSUE TITLE
PoMS sample to be reinstated

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#716]
A user has deleted a PoMS sample by mistake. This is for sample id 6824809.

Please can this sample have its "deleted" attribute set to false.

And there are seven occurences that have sample_id 6824809 - these also need to be set to deleted = false.

Is any other action needed to update the cache tables?

**Comment by burkmarr** [comment]
@johnvanbreda - I'm unsure about what tasks to enter into the work_queue once I've reset the delete flags for this sample and related occurrences. Is it enough to insert a single ```task_cache_builder_update``` for the sample?

**Comment by johnvanbreda** [comment]
No, cache_occurrences deletion are handled directly at the point of deletion and the task doesn't check for deletions I think. So I'd delete the relevant records from cache_occurrences_functional,  cache_occurrences_nonfunctional, cache_samples_functional and cache_samples_nonfunctional manually.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda.

**Comment by burkmarr** [comment]
Sorry @johnvanbreda - I've just come back to this and I think there might have been a misunderstanding. The question was about _resetting_ delete flags to false for a sample that had already been deleted by mistake. The deletion removed all the cache entries. 

So I've now updated both the sample and related occurrences to set their delete flag back to false. I've also run ```task_cache_builder_update``` tasks through the work queue for both the sample and associated occurrences and this has regenerated relevant entries in the four cache tables you mentioned.

**Comment by burkmarr** [comment]
I think that this can be closed now @kitenetter?

**Comment by kitenetter** [comment]
@burkmarr I fear that I have once again underestimated the complexity of this. The sample itself is now reappearing as expected, but it has lost all the attributes that were previously attached to it.

Is there a further step required to regain the attributes? Do individual attributes get marked as deleted when a sample is deleted?

**Comment by kitenetter** [comment]
Or am I just being impatient again and I need to wait a bit longer for caches to update? I will check in the morning.

**Comment by burkmarr** [comment]
Good question. I will investigate.

**Comment by kitenetter** [comment]
@burkmarr sample attributes now visible, so either you've done something or else the caches have caught up - either way thanks for resolving this! Will do a final check in the morning and hopefully can be closed then.

**Comment by burkmarr** [comment]
Yes I just unset the deleted flags on the sample and associated occurrences. I've also put tasks into the work queue - task_cache_builder_attrs_sample and task_cache_builder_attrs_occurrence - which I think are probably required to update the cache.

**Comment by burkmarr** [comment]
They've gone through already. Should be fine now.

**Comment by kitenetter** [comment]
All looks good, thanks, closing.
