### ISSUE TITLE
Import function is losing some BDS custom fields

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#717]
Something has changed recently such that records imported with survey 'DRN dragonfly imports' are scrambling the following fields, without generating any import process errors:
- **Comment** (text) 
- **'Recorded all species?'** (flag)
The flag value (e.g. 1) is being transposed into the Comment field.
The Comment is lost completely.
Other BDS custom fields 'Ad', 'Co' and 'Ov' are being imported successfully, though I haven't exhaustively checked them all.

An **example** record that shows this problem has ID = 12205060 (visible only in Training Mode). This should have Comment = "WDG Card no.: 7635; " and 'Recorded all species?' = 1.
The test spreadsheet from which this was imported (only 3 rows; .CSV but uploaded as .TXT) is attached: 
[Peter's iRecordUploadFileTest2019.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/3858601/Peter.s.iRecordUploadFileTest2019.txt)

I'm speculating that this issue could be related to #704 or perhaps to recent changes to do with giving some fields the 'system' attribute.

This is most urgent, please. We are now into peak import season.

**Comment by DavidHepper** [comment]
This really is urgent @kitenetter because several people have imported recently and more are pending. I'll be requesting some bulk deletions, e.g. the batch on 11/11/2019 for Worcestershire. Do you want the requests in GitHub or offline?

**Comment by kitenetter** [comment]
@DavidHepper probably best if you send deletion requests directly to me and I will then allocate them into github.

**Comment by johnvanbreda** [comment]
@DavidHepper I'm looking at the code now.

**Comment by johnvanbreda** [comment]
@DavidHepper as a temporary workaround, can you try a spreadsheet with the ? removed from the end of the Recorded all species column title please.

**Comment by johnvanbreda** [comment]
This should now be fixed - no need to remove the ?.

**Comment by DavidHepper** [comment]
Thanks. That has worked. We religiously select 'Field observation' for the 'Sample Method' during the import but is this ignored by our data source? I don't see it when the record is edited or exported.

**Comment by johnvanbreda** [comment]
@kitenetter have you seen this behaviour before - selecting Sample Method = Field Observation but the data value not being saved? It's worked OK on my local tests.

**Comment by kitenetter** [comment]
@johnvanbreda is it a question of what gets included in the download files? I don't think we include a sample method within the standard outputs. Would you expect sample attributes to be shown on record edit pages?

@DavidHepper are you choosing a sample method from the dropdown options given during the import process, or is it part of the csv file? If the former that's not something I've ever tried to do.

**Comment by johnvanbreda** [comment]
@kitenetter No, I think this is an issue where the value is not actually saved in the first place.

**Comment by DavidHepper** [comment]
This issue was closed when John fixed the only underlying column import issue. I'll now do the following for the remainder:
- Raise a separate issue about failing to import the Sample Method = Field Observation.
- Send @kitenetter by email (as requested above) the record ranges of the corrupted imports that need to be deleted.
