### ISSUE TITLE
Defining filters takes 5x longer due to refresh

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#718]
Defining a filter in Verify (classic version) used to be quick because each filter criterion could be applied without waiting for a refresh. But with the newish pearl-circle refresh the Apply button is often obscured by the semi-transparent refresh pane. We have to wait for an incomplete filter to refresh the grid before Apply can be clicked. This is annoying and has no benefit. I'm yet again asking for a manual Refresh rather than these pointless requeries.
In this example screenshot a Source selection filter, which would greatly reduce the number of records in the grid, cannot be applied:
![Apply button obscured](https://user-images.githubusercontent.com/24915271/69065766-25ecf300-0a18-11ea-8a6d-c6d9642f9e88.jpg)

**Comment by kitenetter** [comment]
At some point we will be switching off the old verification page but this issues applies to the use of filters elsewhere of course, and I agree that the auto-refreshes can be frustrating. I've edited the name of this issue to make it more generic.

**Comment by kitenetter** [comment]
Will hopefully be improved as we move to ES explore pages, see #811 - closing.
