### ISSUE TITLE
Echeveria derenbergii (Plant - 'Painted Lady')

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#719]
There are ~ 374 records of the plant _Echeveria derenbergii_ "Painted Lady". These are all likely to be intended to be _Vanessa cardui_ (insect) - many have photos.

There doesn't appear to be a way for me to bulk re-determine all of these in one go.

Would it be possible to remove or deprecate the vernacular plant name on iRecord (which is unlikely to ever be used validly), or to re-arrange the drop-down list so that the butterfly appears first if people type 'Painted Lady'.

If the name confusion remains, could the validation rules for _Echeveria derenbergii_ be changed - currently on the verifier's screen all the records appear with a marker saying 'all automatic rules passed' - which is misleading. Probably there are no automatic rules set for _Echeveria derenbergii_ - it's an alien succulent that probably shouldn't be automatically accepted anywhere in the British Isles.

**Comment by kitenetter** [comment]
As a short-term solution I have set the "Painted-lady" vernacular name to be unavailable for data entry within iRecord.

We could run a bulk update to change the determination, but my preference would be for a bulk rejection of the records, assigning a comment to explain why, and allowing the original recorders to edit their records to confirm they did mean the butterfly.

**Comment by kitenetter** [comment]
This appears to be resolved but let me know if not - closing.
