### ISSUE TITLE
Verifiers report not displaying last page of grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#72]
This has been reported by Oli, and I can reproduce it if I masquerade as him. Oli has three verification filters, and this bug appears to only apply to one of the three, namely "Flowering plants; Oxfordshire; Pescott, Oli". At the time of writing the grid says there are 278 records, and they are spread over 10 pages of the grid. If Oli clicks on the button at the bottom of the grid to go to "last", the grid moves to a blank page, with no records and no navigation buttons. Oli has found that if he clicks into one of the empthy column-head-filter boxes and then presses Enter, he is taken back to page 1 of the grid and records are displaying again.

Similarly, if Oli navigates through the grid one page at a time, and then tries to go to the final page (currently page 10), he's back at a blank page.

This hasn't been reported by anyone else. Is there anything about this specific verification filter that could be causing trouble?

**Comment by johnvanbreda** [comment]
Pretty sure this has been fixed a while ago. It seems to work at the moment.
