### ISSUE TITLE
Can only add taxa to survey auto-verfication filters in batches of two

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#721]
You can only add two taxa at a time to the taxon restrictions on a survey in the Warehouse, but if you add them in batches of two, saving the survey each time, you can add more. This could be a problem with the taxon list control or just its implementation on the survey form.

(See also https://github.com/BiologicalRecordsCentre/iRecord/issues/486)

**Comment by kitenetter** [comment]
Not aware of any recent issue with this, closing
