### ISSUE TITLE
Warehouse data import: taxon dictionary missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#725]
I'm trying to import a csv file via the warehouse importer (http://warehouse1.indicia.org.uk/index.php/occurrence/importer/1). I was expecting to be able to choose "UK Master List" as my species dictionary, but the dropdown for "Species list" is blank:

![image](https://user-images.githubusercontent.com/16039111/69736743-0138ff80-112b-11ea-9e01-db5a654ed27c.png)

Is there anything I need to do during the import, or is there a problem with the warehouse set-up?

Should I try importing via the iRecord import interface instead?

(Marking as urgent because this is data that we are trying to mobilise in time for the BSBI Atlas deadline at the end of the year.)

**Comment by BirenRathod** [comment]
@kitenetter 
Do we use UK master list for non-native species? also if your import file has got species name or external key, you don't need to select that list.

**Comment by kitenetter** [comment]
@BirenRathod the csv file has the UKSI TVKs which I normally import into the "Species or taxon external key" attribute, and which are intended to link the the UK master list.

So does that mean I don't have to specify a Species list on the first page?

**Comment by BirenRathod** [comment]
@kitenetter 
yes, that's right. basically it links to your survey. if survey hasn't got one than use the external_key or species name (scientific name or common name)

**Comment by BirenRathod** [comment]
@kitenetter 
it should ask at next level of mapping all fields.

**Comment by kitenetter** [comment]
Okay, but does this guarantee that the species names will be linked to the UK Master List? If it is only using the TVKs to do the linking isn't there a risk that some species will get linked to other species dictionaries instead of UK Master?

**Comment by BirenRathod** [comment]
@kitenetter 
the species list filter through by survey, default is always UK master list (that is the default setting, if that hasn't change).

**Comment by kitenetter** [comment]
Thanks - closing.
