### ISSUE TITLE
Unable to Redetermine a misidentified photo

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#726]
Record ID 5643615 is of a Southern Damselfly. The photo shows a Common Blue Damselfly. I tried to Redetermine this record but received an error. Edit allowed me to change the Occurrence Comment but not the species. Redet did nothing.
The survey is the old BDS mobile app: *iRecord :: iRecord Dragonflies :: British Dragonfly Society recording*
Since it has a photo I'd rather Redet than Reject it. Is there a reason I can't do so?

**Comment by johnvanbreda** [comment]
David, the redet does seem to have saved OK. Was this on the new or old verification page?

**Comment by DavidHepper** [comment]
Sorry, but I don't remember which. Maybe the Redet worked but there was delay before a refresh? Would this suggest I was using ES Verify, with its reindexing delays?

**Comment by kitenetter** [comment]
@DavidHepper what currently happens for me when I redetermine is that the record more or less instantly gets removed from the pending grid, and then reappears under its new name after c.15 minutes. I'm going to close this issue for now but let us know if you get similar problems recurring.
