### ISSUE TITLE
Imports: Record Type field is not being set from selection at Upload page

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#729]
_Peter Reeve reports:_ 
I have just uploaded three records to iRecord and it appears to be successful. The only query I have is the  "Record type" field. This is blank. Should it be "Field observation". I set the "Sample method" to that on the upload page.
Example ID: 12326284

**Comment by kitenetter** [comment]
As described in #731 "Sample method" is not available for DRN imports. DRN imports does have an attribute "Record type" that is a free text field. Users could import a method into that field but I'm not sure what BDS had in mind for it. This would seem to be a matter for BDS guidance, but let me know if you wish to change anything in the survey structure itself.

Closing.
