### ISSUE TITLE
Implement csv upload while in training mode

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#73]
Set up import from csv files so that if you are in training mode the records uploaded end up in your training dataset, and are not treated as 'real' records.

This is to allow users to carry out trial uploads and test that species names are accepted etc. before committing to the real thing.

(As things stand, if you upload while in training mode your records are treated as real - or at least they were last time I tested it, which was at least a year ago.)

Questions: 
- If this was to lead to large numbers of records being added to training mode datasets would that cause any problems? 
- Do we need to provide people with a way of periodically emptying their training mode dataset?

**Comment by johnvanbreda** [comment]
Fixed in develop branch and will be deployed at the next feature release.
