### ISSUE TITLE
In ES Verify, Column Configuration does not offer some useful fields

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#733]
The facility to take a spanner to the columns is a great step forward. I make the following comments: 

**Dates**
- 'Date' is offered twice, with inadequate explanation. These both display the Observation Date, the first in YYYY-MM-DD format, the second DD/MM/YYYY format. Is there a reason in mind?
- 'Verified on' and 'Last updated on' are offered and work correctly.
- 'Submitted on' is not offered. This would be useful for finding rogue imports, for example.

**Comments**
- 'Sample comment(s)' is offered.
- 'Occurrence comments' is not offered but would be useful.

**Comment by kitenetter** [comment]
Thanks for spotting the duplicate Date column! I suggest that we remove the YYYY-MM-DD format, which currently seems to be the default and which has caused problems for verifiers.

Agree with the other suggestions.
