### ISSUE TITLE
Record cleaner rule-sets misapplied to non-accepted names

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#734]
I'm trying to make sense of some peculiar auto-verification of some NPMS records that are well out of range.

Records of _Cirsium dissectum_ should not be treated as valid in  West Sutherland (e.g. in hectad NC75), but there is inconsistent treatment of these data, depending on whether they were recorded as Cirsium anglicum (which iRecord treats as a synonym of Cirsium dissectum) - in which the record is wrongly accepted v's records recorded as _Cirsium dissectum_ which do not pass.

I assume that the verification ruleset is being applied before the synonym is resolved and that there is no rule set for Cirsium anglicum.

![image](https://user-images.githubusercontent.com/207360/70527543-1575f700-1b44-11ea-81da-b3250be101c4.png)

In the above screenshot of Cirsium dissectum records from NC75 all the validations are automatic ones - the two accepted records were recorded as Cirsium anglicum.

(If my understanding of this is correct, then possibly a further problem is that records should not pass validation just because no rules at all have been set for the taxon.)

**Comment by kitenetter** [comment]
@japonicus you are correct in assuming that the record cleaner rules are hard-coded to a particular taxon name, and do not update when the name changes. See #658.

And I agree that we should not be showing records as havng passed all the checks if there are in fact no checks being applied, but that is not straightforward to resolve, see #746.

We will progress those two issues when we can - closing this one.
