### ISSUE TITLE
Displaying unreleased records on the new verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#736]
In nearly all cases we do not expose unreleased records to verifiers. However, for PoMS (which has all its data as unreleased) we had set up a couple of specific verification roles to allow verification of the PoMS unreleased records, i.e. the verification filter had been set up to include unreleased records.

With the addition of the "Create a filter" options to the new verification page, we seem to have lost the ability to display unreleased records. I assume that the default settings for the "Create a filter" block are disallowing unreleased records.

Is there a way of allowing unreleased records to be shown on the new verification page, without risking the wider exposure of unreleased records? (The standard verification filters should exclude unreleased records, but I'm not sure if the "Create a filter" settings would override the standard filters.)

**Comment by johnvanbreda** [comment]
Currently the Elasticsearch alias used for verification always excluded unreleased records. Because of this the code which converts a filter to an Elasticsearch request doesn't do the release status filter. So to fix this, we need to change the filter conversion code and also change the alias. This just needs to be prioritised - I've classed it as small.

**Comment by kitenetter** [comment]
Not a priority while the old verification page is still available, but would be useful for PoMS next season. As long as our verification filters allow control over visibility of unreleased records then I don't see a need to exclude them from the elasticsearch verification alias.

**Comment by kitenetter** [comment]
Need to check if this is still a problem.

**Comment by johnvanbreda** [comment]
@kitenetter this has been done, as Asian Hornet records are available. Closing.
