### ISSUE TITLE
Problem with uploading records via the warehouse

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#738]
I just did a large upload of data from RSPB into Indicia, using the warehouse interface. This takes an hour or two to run, and normally produces a downloadable file of import errors at the end.

However, in this case I had been automatically logged off from the warehouse interface before I could download the errors file. I'm fairly certain that the main import did complete, but I need to obtain the errors file.

Do those files get stored somewhere, and if so how can they be accessed?

**Comment by johnvanbreda** [comment]
Link sent to @kitenetter
