### ISSUE TITLE
Images missing from Help page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#739]
This applies to the Help page for setting up an activity:

Most (but not all) of the images are failing to display. If I edit the page, it appears that all the non-displaying images have changed their links to a non-working URL, that includes a suffix (starting with "?itok=") that I don't recognise. For example, one of the non-displaying images links to:
http://irecord.com/sites/default/files/styles/full-width/public/help-images/ActivityS2.png?itok=UJhfY8_v

What it should link to is:
http://irecord.com/sites/default/files/styles/full-width/public/help-images/ActivityS2.png

I can correct all the incorrect URLs of course, but I'm raising it here because I don't understand why this has happened.

**Comment by kitenetter** [comment]
This is still a problem on some Help pages, e.g.:
https://www.brc.ac.uk/irecord/join_activity

@BirenRathod is there a solution to this or do I need to do manual edits?

**Comment by BirenRathod** [comment]
@kitenetter 
The path uses for all images are not correct one. it should be something like... this -> files/help-images/Activity1.JPG 
Above mentioned path is not exists, so it won't find any images.

**Comment by kitenetter** [comment]
Check that images are back

**Comment by kitenetter** [comment]
All seems fine, closing.
