### ISSUE TITLE
Make system function apply retrospectively

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#743]
When we mark an attribute with a system function, it only gets included in downloads for records added from that point in time onwards. We have to run database updates to apply the system function to older records.

Is it possible to make any change in system function apply to all records, retrospectively as well as newly-added?

**Comment by johnvanbreda** [comment]
This should probably be handled by a new type of work_queue task so that timeouts don't occur in the user interface.

**Comment by kitenetter** [comment]
Have not needed to alter system functions recently, closing for now.
