### ISSUE TITLE
Manual refresh button on the redet dialogue box

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#745]
The species lookup dialogue that appears when a verifier uses the redet button sometimes freezes, and at the moment the only solution is to refresh the whole page, see #697 

A mitigation for this would be to add a manual refresh to the redet dialogue box itself, so the the species lookup can be refreshed without having to refresh the whole page and thus lose any filter settings.

Relates to the more general issue of auto-refresh problems #718

**Comment by johnvanbreda** [comment]
I'm not sure this is a real solution as without the answer to #697 we don't really know what to refresh. So I'd concentrate on that issue instead.

**Comment by kitenetter** [comment]
@johnvanbreda I thought your comment here:
https://github.com/BiologicalRecordsCentre/iRecord/issues/697#issuecomment-544867122

was suggesting that this manual refresh was a potential solution? If that's not the case I'll close this issue and we can stick with #697 for now.

**Comment by johnvanbreda** [comment]
David's comment about a refresh button was actually about a "Go" button to apply filter changes, to avoid multiple refreshes when setting up a complex filter. So, I'll close this one.
