### ISSUE TITLE
Data downloads – suggested actions part 2

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#75]
These are less urgent and/or more problematic than the actions in #74 .

**Limit to number of records**
There is a limit on how many records can be downloaded, and that is understandable, but it would be good if some help could be given so that people know whether their proposed download does in fact exceed the limit, and if it does what would be a sensible way of chunking it up (e.g. maybe some info could be given prior to download on how many records per year, or what the range of unique IDs is, so that a choice can be made if the entire dataset needs to be downloaded in several chunks).

**Making custom attributes available**
We still need to think about how best to deal with the multiple custom attributes, and the system function approach will help for some. Could either of these options be useful:
- Make it possible for users to see which surveys include records that are of interest to them (i.e. if they are downloading their own records, or if they are downloading as a verifier, the list that appears in the dropdown for “Survey to include” would be filtered to only contain those surveys that have relevant data).
- Where a user does need to download data from multiple surveys with different attributes, is it possible to set up a batch download that would download each survey in turn for all surveys that had relevant data, and supply that perhaps as a zipped file containing a separate csv for each survey?

**Species**
Is there an argument for having two columns, one for the name actually used for data entry, and a second for the current recommended name?

**Taxon group**
It would be very helpful if the non-standard (i.e. non-UKSI) group names could be transleted in the standard ones, e.g. so that “Flies, Gnats and Midges” was displayed as “insect - true fly (Diptera)”

**New attribute/s**
It would be useful if the results of the record cleaner checks could be included in the download, to allow for additional analysis. Presumably would need three columns:
- ID difficulty (number)
- Within known range? (yes/no)
- Within known phenology? (yes/no)

**Zero abundance**
There is an argument for excluding zero abundance records from downloads unless the user specifically asks for them to be included, to avoid zero abundance records being treated as presence records in error.

**Map filter for download**
British Dragonfly Society have requested the ability to filter downloads by location via the map interface.

**Comment by DavidRoy** [comment]
An additional potential requirement - to add activity/entry form to download.  See
http://www.brc.ac.uk/irecord/node/4137

**Comment by kitenetter** [comment]
Review the above and transfer to elastic download issues where appropriate.

**Comment by kitenetter** [comment]
The above issues have either been addressed via the ES download page, or are covered elsewhere. Closing.
