### ISSUE TITLE
ElasticSearch error message

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#750]
I am repeatedly seeing this message while verifying:

![image](https://user-images.githubusercontent.com/16039111/72111413-9e927080-3332-11ea-9c40-9b1b56f70c45.png)

As far as I can tell it does not actually prevent me from continuing, but it does require me to repeatedly click on the OK button to clear the message before I can proceed.

(It looks like the error is associated with drawing dots on the map but I can't be certain of that.)

**Comment by johnvanbreda** [comment]
I'd be interested in seeing the contents of your Network tab (developer tools) when this happens. You need the developer tools running first, then on the Network tab, the HAR option allows you to save a HAR file which I can inspect.

**Comment by kitenetter** [comment]
I think this HAR file may contain an example of the error.

[www.brc.ac.uk_Archive [20-01-10 22-11-10].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4048433/www.brc.ac.uk_Archive.20-01-10.22-11-10.zip)

**Comment by kitenetter** [comment]
Another example:

[www.brc.ac.uk_Archive [20-01-10 23-51-37].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4048666/www.brc.ac.uk_Archive.20-01-10.23-51-37.zip)

**Comment by johnvanbreda** [comment]
@kitenetter do you remember what you were actually doing when the 2nd example happened?

**Comment by kitenetter** [comment]
No I don't, but the error message seems to pop up at random. Usually it only starts happening after I have been verifying for a while (and does not seem to be associated with any change in filter settings or similar). But sometimes it kicks in quite quickly.

**Comment by johnvanbreda** [comment]
Ok, it's hard for me to spot the problem in the HAR files. I've added some logging data though to help. Next time you get the error, please can you do the following immediately after closing the error message.
1) Save the HAR file.
2) Go to the Console tab. Ensure all the types of information shown (Errors, Warnings, Logs, Info and Debug should all be activated). 
3) Right click in the log, save the file and send it to me.
Thanks.

**Comment by kitenetter** [comment]
It's just happened again. HAR file:

[www.brc.ac.uk_Archive [20-01-16 23-34-08].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4074281/www.brc.ac.uk_Archive.20-01-16.23-34-08.zip)

Console info:

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. verification
window.controllers/Controllers is deprecated. Do not use it for UA detection. js_s5n9e3KrTQz_lMZLJeHcebsvOaeE0-M-8aBehgZorRk.js:13657:417
XML Parsing Error: not well-formed
Location: https://www.brc.ac.uk/irecord/ajaxproxy?node=7614&index=occ-comment&user_id=50&sharing=verification
Line Number 1, Column 1: 2 ajaxproxy:1:1
TypeError: jQuery18308034897135726179_1579212269059 is not a function taxa_search:1:41
XML Parsing Error: not well-formed
Location: https://www.brc.ac.uk/irecord/ajaxproxy?node=&index=occurrence&user_id=50&sharing=editing
Line Number 1, Column 1: ajaxproxy:1:1

**Comment by johnvanbreda** [comment]
I think the Elasticsearch Query Failed issue was fixed on Friday. Please re-open if not.

**Comment by kitenetter** [comment]
I hadn't been seeing the error messages recently, but they've just started again. I was masquerading as another verifier, and using the ES verification page. Initially there were no problems. I had to go out for a while and the computer had gone on standby. When I went back to the page about an hour later, the error messages started up immediately.

Refreshing the page seems to have no effect and the error messages are currently very numerous.

I can understand that leaving the machine on standby might cause problems, but I would have hoped that a page refresh would reset things.

HAR file:
[www.brc.ac.uk_Archive [20-01-30 17-17-18].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4135322/www.brc.ac.uk_Archive.20-01-30.17-17-18.zip)

Possibly related information:
I was trying to use the top level search box to search for a species aggregate: "Littorina obtusata/fabalis". The inclusion of the forward slash appears to be triggering the error messages - if I just search for Littorina obtusata it seems fine, and if I use the double-quotes it seems fine.

So perhaps this is the result of me using the search box incorrectly rather than a problem linked to the standby and page refresh?

**Comment by DavidHepper** [comment]
I get this message if:
- I've logged out (or somehow been logged out) in another tab.
- I try to include both date and time in a column filter on **Last updated**, **Submitted on** or **Verified on**, although each of these columns shows a date and time.

**Comment by DavidHepper** [comment]
I find now that I'm unable to filter at all by any of these date-time fields using the column header. Even entering today's date as "31/01/2020" results in 'Elasticsearch query failed'.

**Comment by kitenetter** [comment]
I've just tried to replicate that and the date filtering seems to be working for me, using the column-head filter box, and using Firefox, and typing in a date without using double-quotes:

![image](https://user-images.githubusercontent.com/16039111/73544735-bd67bc80-4431-11ea-95f6-49cfb6331865.png)

**Comment by DavidHepper** [comment]
That's the ordinary (Occurrence) Date box, which has always worked. The others are dd/mm/yyyy hh:mm format fields. I didn't enter the double-quotes.

**Comment by kitenetter** [comment]
Ah, I'd forgotten that the other date columns were formatted differently. So it looks like the error messages are now resulting from search terms that the system rejects, rather than from general use (which was the situation when this issue was opened).

**Comment by johnvanbreda** [comment]
See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_regular_expressions for an explanation regarding forward slashes - these are special characters indicating you are doing a regular expression search. Wrapping in quotes should work.

The dates are handled differently since the main date field is a vague date. I agree they should be fixed to work in the same way though.
