### ISSUE TITLE
Unhelpful scrolling on verification grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#752]
The new page verification grid selects 30 records at a time, but depending on how may photos etc. only a proportion if the 30 records fit into the display, which means that there is always some scrolling to do within the grid itself. This becomes very tedious and confusing since the whole page also scrolls, and it adds a significnat extra amount of time to deal with each page of 30 records.

Is it possible to set the grid so that it grows to accommodate all 30 records with no grid scrolling (but more page scrolling)?

Related to this, is it possible to have the grid display 50 records at a time rather than 30?

I can see a problem with making the grid deeper, in that the record details would likely move off-screen as you move down the grid. Is it possible to have the map and details panes float so that they move down the page as you move down the (non-0scrolling) grid?

**Comment by johnvanbreda** [comment]
I've done 2 things here:
1) Write new code in the ES data grid so it can be anchored to the bottom of the page and the body will take up all available space. This needs turning on when deployed (scrollY=-8px for example).
2) There is also page specific script to make the map and details pane occupy approx half the available space each. The details pane has internal scroll bars. 

When combined with the grid scroll code to be deployed, it means you won't ever scroll the whole page up and down, just the grid. Everything else (including the grid heading and filters) stays locked on the page. We can then increase the record count in the grid as it will no longer cause problems.

**Comment by DavidHepper** [comment]
I support this change and have a suggestion and an enhancement: 
- Do test carefully with a low-res. screen e.g. 1366 x 768 px to make sure it works at all.
- Give the user the ability to choose (within limits) the number of records to show per page of the grid.

**Comment by johnvanbreda** [comment]
Thanks @DavidHepper - I've checked the new code and it's OK on small screens (accepting that the verification page is not optimised for any screen that's too small). @kitenetter please raise the issue about choosing the number of rows in a page if you think it's a good idea.

**Comment by kitenetter** [comment]
@johnvanbreda I haven't yet seen any change in scrolling behaviour, is this awaiting a code release?

**Comment by johnvanbreda** [comment]
It's been applied. Does your records grid align itself to the bottom of the browser window, with a scrollbar in the table body when necessary?

**Comment by kitenetter** [comment]
Using Firefox, there is a scrollbar within the grid of records, and the amount of scrolling on the main page is much reduced, but there is still a little scrolling on the main page. 

When I first go to the page the previous and next buttons are hidden unless I scroll the main page down a little:

![image](https://user-images.githubusercontent.com/16039111/75330901-bdfd4280-5879-11ea-9698-48f203aa09e7.png)

So it has changed, and is definitely greatly improved (e.g. I can now scroll to the bottom of the grid while keeping the verification buttons within view, when using the tick boxes). Ideally it would be good to have the main page not scrolling at all, but that's a tiny difference from what I'm currently seeing.

Maybe re-open this issue if you think it's worth doing more to address that tiny difference, but otherwise I'm happy to leave it closed. (Also I do intend to remove, or at least shorten, the "We welcome feedback ..." message at the top of the page, so that might change the behaviour in any case).
