### ISSUE TITLE
Repeat verification buttons at bottom of grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#753]
When using the tick boxes for verification, I often work my way down the page checking the records, and then have to scroll all the way back up to the top to apply the verification choice.

Can the verification buttons be repeated at the bottom of the screen as well as the top, when the tick boxes are in use?

**Comment by johnvanbreda** [comment]
Though may relate to solution for #752?

**Comment by kitenetter** [comment]
I think buttons at the bottom of the page would still be useful regardless of solution to #752 - however many records are in the grid, the most likely workflow (for the tick-box option) is to scroll down the page to check them and then apply a verification status once the end of the page has been reached, and the extra buttons at the foot of the page would avoid one more lot of scrolling up again.

Unless one set of buttons can be made to float down the page as you scroll down.

**Comment by johnvanbreda** [comment]
When #752 is fully deployed, only the table body will need to be scrolled. The headings and buttons above will therefore be locked on the page and you'll never have to scroll back up. Having just tested the behaviour on small screens for David Hepper, I am of the opinion that duplicating the verification buttons under the table will only further impact the screen space even further. So I'll close this but please re-open if you disagree when you've seen #752 deployed.
