### ISSUE TITLE
Make it more obvious when bulk verification is selected for "all" records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#754]
I have managed to verify several thousand records in one go by mistake on one occasion, and very nearly done similar on other occasions, as a result of using the "Apply decision to all" option:

![image](https://user-images.githubusercontent.com/16039111/72112183-c256b600-3334-11ea-810e-033269cbbd3b.png)

This has been a result of using the "Apply to all" correctly to verify a batch of records, and then forgetting that the "all" option was still selected when I go on to the next lot of ticked records.

Can we make it more obvious when the "all" option has been selected, e.g. by adding a VERY prominent warning to the "Set status to ..." window (or changing that window's colour to bright red):

![image](https://user-images.githubusercontent.com/16039111/72112312-25e0e380-3335-11ea-8df3-1c892ffb12cc.png)

**Comment by DavidHepper** [comment]
... or unset the All option after each use, so that it has to be reselected?

**Comment by kitenetter** [comment]
I think that suggestion is a very good one, thanks @DavidHepper
