### ISSUE TITLE
Editing of iNaturalist records and error showing images

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#755]
The 'Edit' link is available for imported iNaturalist records. Is this appropriate if changes may be overwritten? (See also #641.)

When 'Edit' is clicked, the record is loaded but the presence of specimen images causes error "An error occurred trying to link to that resource. ..." once for each Photo field. Conversely, in the grid, the thumbnail images are shown and can be expanded without error.
Example ID: 12563571

**Comment by kitenetter** [comment]
Closing, but may need to revisit if we are able to develop further links with iNaturalist.
