### ISSUE TITLE
Condense notifications following a redetermination

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#756]
Notification summary emails sent to users following redetermination of record sometimes have many separate (and duplicated) entries relating to the same occurrence, obscuring what has been done to the record. My most recent notification, triggered by the re-determination of 4 records contains 14 entries (two of the records have six notes each). The emailed list appears to be unsorted.

It would be far easier to understand the notification if it were sorted by record number and then by date. Could duplicate and super-ceded entries be hidden or merged, e.g. for [2371386](http://www.brc.ac.uk/irecord/record-details?occurrence_id=2371836) I received:

Martin Townsend | 2371836 | A comment was added to your record of Orange Swift at SU61689186 on 21/08/2015.This record's verification status needs to be rechecked as it has been edited. | Awaiting review
-- | -- | -- | --

and five repetitions of

Martin Townsend | 2371836 | Your record of Orange Swift at SU61689186 on 21/08/2015 was examined by an expert.This record's verification status needs to be rechecked as it has been edited. | Accepted as considered correct
-- | -- | -- | --

The phrasing used is also confusing: "Your record of Orange Swift" is misleading, as I entered the record as a Common Swift.

Although more complicated to implement it would be very much more user-friendly to have a single summary line that said.

"Your record of Common Swift has been redetermined by Martin Townsend and accepted as an Orange Swift"

![image](https://user-images.githubusercontent.com/207360/72145945-6c652b00-3393-11ea-82a7-a202b67c6759.png)

**Comment by kitenetter** [comment]
We have had a few other emails recently from people who are confused by, or compaining about, records being redetermined. I think we need to find a better way of handling this so that it is clear to people when their records have been redetermined, and if possible to address the multiple message issues that Tom describes above. See also #662 

I will review and suggest a way forward.

**Comment by kitenetter** [comment]
Info copied from #662 :

Currently, if a verifier redetermines a record, the original recorder will be sent a notification of the comment associated with the redet, but there is nothing to make it clear that a redetermination has taken place, and that therefore no further response is required from the original recorder.

Not sure how best this would be done, but it would be good to let people know that a redet has taken place.

**Comment by kitenetter** [comment]
We do now have pre-populated text for notifications about redeterminations, so hopefully this is now clearer. Closing.
