### ISSUE TITLE
Allow verifiers to opt in or out to iNaturalist and other non-standard datasets

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#759]
The first step for this issue is for @johnvanbreda to assess whether this can be achieved without spending a unreasonable amount of time on it.

Based on today's discussion we are aiming to:
- Add a flag to the warehouse website tables that allows 'non-standard' datasets to be identified
- Provide a dropdown/tick box option on the verification page that contains just the non-standard datasets, and allows verifiers to straightforwardly switch from 'standard' data to one (or more) non-standard datasets; this needs to function as a sub-filter within the overall data access permissions that result from the main verification filter currently in play
- Provide and link to a Help page that lists the (relatively few) non-standard datasets, and provides contextual information on them, highlighting where verifiers may have to apply particular approaches to these datasets

An additional complication is that if we go down this route we will ideally need to provide an option with the verifiers' download to include or exclude non-standard datasets (@burkmarr to bear this in mind for the explore/download scoping exercise).

**Comment by DavidHepper** [comment]
BDS are sympathetic to this proposal but I'm concerned that it may add complexity in areas that are of lower priority than better handling of the iNat records on the way in. See other iNaturalist issues.

**Comment by kitenetter** [comment]
Closing, but may need to revisit if we are able to develop further links with iNaturalist.
