### ISSUE TITLE
Photos not loading in verification system

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#76]
Urgent bug as affects verification:

As reported by Matt Smith via the iRecord forum - http://www.brc.ac.uk/irecord/node/3874

When verifying records, photos accompanying records are either loading very slowly or not loading at all, I just see the "loading" symbol spinning.  This has been noticeable over the past few days and is causing records to start backing up.  Can you take a look please as it is impossible to verify records at present.

**Comment by johnvanbreda** [comment]
Cannot reproduce - tried masquerading as Matt and selected the Hymenoptera - Aculeates filter under Firefox. I could click on images in the grid as well as under the Media tab of the details pane and it worked OK, quite quickly in fact, for all the records I tried.

**Comment by DavidRoy** [comment]
I’ll ask for more details so we can track down the issue

**Comment by kitenetter** [comment]
I have been finding the verification grid rather slow to reload following a filter change, or a redet, but I've not noticed any problem with the photos.

**Comment by johnvanbreda** [comment]
What's the status of Jim's review of infrastructure? Looking at the queries running when Martin filters (e.g on Berkshire Moths) there isn't a huge amount wrong with them.

**Comment by JimBacon** [comment]
I've got some finishing off to do with the continuous integration testing and some outstanding security issues to close which will probably keep me going all next week. My next task will be to try out a Linux-based warehouse, probably in a Docker container which I can move around and test in various places

**Comment by JimBacon** [comment]
Whoops. didn't mean to hit the close button.

**Comment by kitenetter** [comment]
I checked some timings on 19 July 2016 at 10.26 pm:

- At home page, logged in
- Go to verify, wait for moths to show in grid: 6 seconds
- Change to soldierflies, wait for grid to refresh: 20 seconds
- Apply filter to see queried records: 15 seconds
- Reset: 21 seconds
- Filtered by recorder name (column heading): 49 seconds
- Redet: time to refresh: 53 seconds
- Clear recorder name: 17 seconds
- Refresh page to moths: 16 seconds
- Change to soldierflies, wait for grid to refresh: 21 seconds
- Added a query (via commenting) to a record (with recorder name filter in place), time to refresh grid: 60 seconds fist time, 46 second time

Most of those are quite small delays, but they all add up, and make for quite a lot of time spent waiting for things to refresh, especially when filtering by recorder name, which I do a lot. This was on my home computer with slow rural broadband.

**Comment by johnvanbreda** [comment]
Hi Martin
Your soldierflies verification filter was set up using the Species and lower taxa tab, rather than the Families and higher taxa tab despite being based on a list of families. Therefore your filter did not use the optimisations I've put in place for family based filters. Having hacked your filter to do this and retested the above timings I found things are much snappier, though not perfect admittedly.
Cheers
John

**Comment by kitenetter** [comment]
That's a great improvement, may thanks John, much appreciated.
