### ISSUE TITLE
iNaturalist: blurring of map ref for 'threatened' species causes issues

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#761]
Most imports to iRecord from iNaturalist seem good but those for 'threatened' species such as Southern Damselfly cause issues for BDS verifiers.
The map reference received from iNat appears to be ready-blurred to 10km, with the detailed map reference being unavailable. This causes the usual problems when assigning the record to the appropriate verifier. To get more detailed info the verifier has to be registered with iNat and either be accepted by the appropriate survey group or contact the recorder. These records, even when accepted, are of limited use in iRecord and are probably ineligible for NBN Atlas and GBIF.

Ideally, the Sensitive flag and the detailed map reference should propagate into and through iRecord, with details visible only to Admins and Verifiers.
Alternatively, should threatened species not be imported to iRecord?

**Comment by MNSmith** [comment]
I think the "blurring" of the record is down to the individual recorder / geo-location preference combination for each record.  iNats uses can "blur" the record at their end and presumeably this value is what gets imported inti iRecord.

**Comment by kitenetter** [comment]
Not a live issue unless we reinstate iNat imports - closing for now.
