### ISSUE TITLE
iRecord system on a go-slow?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#762]
The system seems to be have been slow all day today, with these symptoms: 
- Refresh of classic Verify is slow.
- My user Profile is slow to open.
- An import (in Training mode) of 1,300 records has hung after reporting "600 records uploaded...".
- After importing a single record (ID 12580216, Training mode) the background checks took about an hour before the 'P' icon appeared.

**Comment by johnvanbreda** [comment]
Looking at today's performance data, the 2 most significant impacts are areas of the system which have both already been improved significantly for the next release. I've done a quick patch of one of these (a report that could simply be swapped).

**Comment by DavidHepper** [comment]
Thank you, John. Much better today.
