### ISSUE TITLE
Records missing, possibly due to deleted vernacular name?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#763]
**Action required**
If my assumption is correct that this record is failing to display because it is linked to a deleted taxon (see below):
- For taxa_taxon_lists.id = 297639, set "deleted" to false

**Background**
A user has been in touch to say that some of her records are missing from iRecord. They were added direct to iRecord as far as I know. The only one for which they have a record ID is 11197236. That record is of the "Banded General" soldierfly, and I cannot see anything in the record itself that would prevent it from being displayed.

However, it appears that we have two instances of "Banded General" in the UK Master List. One of those instances is marked as deleted in the taxon table, but both are marked as deleted in table taxa_taxon_lists. 

If I run this query:
`select tl.title, ttl.id AS "ttl_id", ttl.deleted AS "ttl_deleted", t.id AS "t_id", t.deleted AS "t_deleted", t.taxon, t.authority, ttl.taxon_meaning_id, ttl.preferred, t.language_id, tg.title as taxon_group_id
from taxon_lists tl
join taxa_taxon_lists ttl on ttl.taxon_list_id=tl.id
join taxa t on t.id=ttl.taxon_id
join taxon_groups tg on tg.id=t.taxon_group_id
where t.taxon='Banded General'`

I get this result:

![image](https://user-images.githubusercontent.com/16039111/72346893-be2cee80-36ce-11ea-9bc7-e8937b2b2317.png)

I'm not sure why we have two versions of this vernacular name (there is only one in UKSI), and I don't know why they have both been deleted.

The same user reports that some dragonfly records have gone missing, but they do not have record IDs for these, so I will see if I can find them.

**Comment by kitenetter** [comment]
I can find no evidence of missing dragonfly records for this user so it appears to be just the one problem with this particular English name.

**Comment by burkmarr** [comment]
@kitenetter. I don't know why the vernacular name was marked as deleted - the last updated field indicated that the ttl record was last updated years ago (2014 I think). Hopefully this is a one-off. I reset the deleted flag to false and stuck a task in the work_queue to put an entry in the catche_taxon_taxon_lists table. That task has been run and I can now filter on Banded General in Explore all Records and see a bunch of records (which I couldn't do before). I don't know the name of your recorder though, so I can't say whether or not the record in question appears.

**Comment by kitenetter** [comment]
Thanks @burkmarr. The record is now visisble again (and presumably there are now a bunch of additional soldierflies waiting for me to verify them!):
https://www.brc.ac.uk/irecord/record-details?occurrence_id=11197236

However, the above page shows that links to the higher taxonomic hierarchy are missing, and the user's "My records" page is still not displaying a common name (despite the common name being used to enter the record):

![image](https://user-images.githubusercontent.com/16039111/72423392-166dfa00-377c-11ea-835e-2ab61c335c77.png)

So unless there are still some cache updates waiting to happen it looks like there are still some missing links somewhere in the various taxon-related tables.

But having said that, the taxonomic hierarchy is shown if I look at this record from my verification page:

![image](https://user-images.githubusercontent.com/16039111/72423715-a4e27b80-377c-11ea-9ec4-661593d5fc63.png)

So the immediate issue is resolved, but it worries me that I can't explain the above discrepancies.

**Comment by burkmarr** [comment]
@kitenetter - the preferred taxon _Stratiomys potamida_ (taxa_taxon_lists.id=100317) has no value for default_common_name - I wonder if that's why 'Common name' is blank? However, I can't explain the missing taxonomy from https://www.brc.ac.uk/irecord/record-details?occurrence_id=11197236. I entered a task_cache_builder_path_occurrence task into the work queue to rebuilt the taxon_path for record, but that didn't make any difference. The taxon meaning values stored in the taxon_path field for the record (in cache_occurrences_functional) appear to resolve to the correct values. Perhaps we should leave this open.

**Comment by burkmarr** [comment]
@kitenetter - I just checked this link again - https://www.brc.ac.uk/irecord/record-details?occurrence_id=11197236 - and now the taxonomy *is* showing. I can't explain why I thought it wasn't unless I was looking at a cached page or something, so I think that we can probably close this issue now.

**Comment by kitenetter** [comment]
@burkmarr the taxonomy definitely wasn't showing as of 15 Jan, so perhaps there is some caching going on or it takes time for the links to rebuild. Anyway, all looks well now. Closing.
