### ISSUE TITLE
Elastisearch "Query" filter not working

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#764]
If I build a filter on the ES screen using only "Quality = Queried Records Only" the filter returns no records.  If I look at the same group using the old Verification grid I see several hundred records that have a "queried" status.

**Comment by DavidHepper** [comment]
Are you sure you've set the **Status** field at the top to 'All records'? There is a clash between the permanent config line of [ Search | Context | Status | Photos ] fields and the filter definition block that is shared with classic Verify. It's convenient to have the Status field at the top but the interaction is unhelpful.

**Comment by MNSmith** [comment]
Just reloaded the grid and rechecked the function.  The "Records Status" box (which I admit I had never noticed) is set to "All Records" and using the saved filter to pull up "Queried" records returns no records.  Similarly, making new filter to show only "Queried" records returns no records.

The filter only containing the selection of "Queried"  records is the only filter that does not seem to work.  All the other filters (default or made by me) seem to work as expected.   Other filters that include "Queried records" as part of the selection criteria (eg select Species / Last 6 months / Queried records) appear to work as expected.

However, if I set the "Records Status" box to "Queried" then all the records I expect to see appear in the grid.   While this "solves" my problem it does not explain why the one particular selection command is not working.   Something odd going on here.

**Comment by johnvanbreda** [comment]
@MNSmith I just masqueraded as you and if I set Status=All records in the toolbar, then choose the saved Queried records filter and press Apply it seems to work OK. Can you explain exactly what settings you used please (e.g. which context).

**Comment by MNSmith** [comment]
Old Verification Page + "Queried" Filter - Returns 132 records.

![image 1](https://user-images.githubusercontent.com/18451743/72729919-393b4c80-3b88-11ea-938a-d5bbfce2ed87.jpg)

New ES Verification Page with "Status" = "Queried" - Returns 123 records

![Image2](https://user-images.githubusercontent.com/18451743/72729748-d9dd3c80-3b87-11ea-82c5-57ef69508683.jpg)

New ES Verification Page with "Status" = "Pending" (default setting) plus "Queried Filter" - Returns 0 records.

![Image1](https://user-images.githubusercontent.com/18451743/72729889-29bc0380-3b88-11ea-9e34-f6863686f390.jpg)

I'm not sure what internal filtering was used to original display records on the original Verification grid but it did allow searching directly from that page for "Queried" records.  The new ES page would seem to have a different internal filter setup as the default for the grid appears to be "Status = Pending".  This appears to be having the effect of "blocking" access to queried records as presumeably there are no queried records in the pending list, which means applying the "Queried" filters to this list will correctly return no records.  Whatever is going on, the two pages are sorting records in slightly different manners. 

For those used to working on the old grid, perhaps some revised help text / information about the additions "Status" box and filtering might be useful.  As I said, I never really noticed the "Status" box on the ES Grid.  Having discovred this, I can now do what I need to on the ES page.

**Comment by kitenetter** [comment]
This needs to be addressed through the revised Help documentation, see #785. Closing.
