### ISSUE TITLE
Filter for "Symphyta" produces an error

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#765]
I need to set up a filter for "Symphyta" (= sawflies). Our sawfly verifiers have filters based on a list of families, which means that records assigned to the suborder Symphyta are getting overlooked.

However, I've tried setting up a verification filter for Symphyta and I got a timeout message. I tried filtering for Symphyta via Explore - All records, and although the map swiftly got populated with blue dots, the grid did not get populated, and eventually a timeout error appeared again (copied below).

@johnvanbreda is this just a sympton of performance difficulties, or could there be a more fundamental problem with the Symphyta filter?

Error:

The data did not load successfully. The reason given was: 
There was an SQL error: ERROR:  canceling statement due to statement timeout - 
  SELECT o.id as "occurrence_id",
snf.website_title || ' | ' || case when substring(snf.survey_title from 1 for length(snf.website_title)) = snf.website_title then trim(substring(snf.survey_title from length(snf.website_title)+1)) else snf.survey_title end as "source",
o.website_id::varchar || '|' || o.survey_id::varchar as "source_id",
o.sample_id as "sample_id",
cttl.preferred_taxon as "taxon",
cttl.default_common_name as "common",
cttl.taxon_group as "taxon_group",
o.taxon_group_id as "taxon_group_id",
o.taxa_taxon_list_id as "taxa_taxon_list_id",
o.location_name as "location_name",
coalesce(regexp_replace(snf.public_entered_sref, ',[^ ]', ', ', 'g'), snf.public_entered_sref, onf.output_sref) as "entered_sref",
onf.output_sref as "output_sref",
o.date_start as "date_start",
o.date_end as "date_end",
o.date_type as "date_type",
null as date,
to_char(o.created_on,'DD/MM/YYYY') as "cache_created_on",
o.created_on as "cache_created_on_raw",
to_char(o.updated_on,'DD/MM/YYYY HH24:MI') as "cache_updated_on",
o.updated_on as "cache_updated_on_raw",
CASE WHEN (TRIM(snf.recorders) !~ ' ' AND LENGTH(snf.recorders)>30) THEN 'Recorder' ELSE snf.recorders END as "recorder",
o.zero_abundance as "zero_abundance",
o.created_by_id as "created_by_id",
o.record_status as "record_status",
o.record_substatus as "record_substatus",
o.release_status as "release_status",
o.certainty as "certainty",
CASE WHEN CAST(o.created_by_id AS character varying) = '102855' AND o.website_id IN (23) THEN true ELSE false END as "belongs_to_user",
CASE WHEN o.website_id IN (23) THEN true ELSE false END as "belongs_to_site",
onf.media as "images",
case     when canEdit.id is null then null     when o.input_form is null or o.website_id not in (23) or 0=1 then 'edit-generic-record'     else o.input_form end as "input_form",
CASE       WHEN o.data_cleaner_result='t' THEN '<div class="pass-icon" title="Passes all auto-checks."></div>'       WHEN true and o.verification_checks_enabled='f' THEN '<div class="auto-check-disabled-icon" title="Auto-check disabled.">-</div>'       WHEN o.verification_checks_enabled='t' AND o.data_cleaner_result IS NULL THEN '<div class="pending-icon" title="Pending auto-check.">...</div>'     END as "pass",
case when o.data_cleaner_result='f' then             replace(replace(replace(replace(onf.data_cleaner_info, '[', '<div class="fail-icon '), ']', '" '), '{', 'title="'), '}', '"></div>')         end as "fails",
o.query as "query",
case o.record_status when 'V' then 'Accepted' when 'R' then 'Not accepted' when 'T' then 'Test'               when 'C' then case when record_substatus=3 then 'Plausible' when o.certainty='C' then 'Recorder considered this certain' when o.certainty='L' then 'Recorder considered this likely' when o.certainty='U' then 'Recorder considered this uncertain' else 'Not reviewed' end             end ||             case o.record_substatus when 1 then ' as correct' when 2 then ' as considered correct' when 4 then ' as unable to verify' when 5 then ' as incorrect' else '' end ||             case o.query when 'A' then ', query raised and answered' when 'Q' then ', query raised' else '' end as "status_hint"
  FROM cache_occurrences_functional o
  JOIN cache_occurrences_nonfunctional onf on onf.id=o.id
  JOIN cache_samples_nonfunctional snf on snf.id=o.sample_id
  JOIN cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id
  LEFT JOIN index_websites_website_agreements canEdit on canEdit.from_website_id=o.website_id
    and canEdit.to_website_id in (23) and canEdit.provide_for_editing=true
  JOIN system sys ON sys.id=1
  

  WHERE o.training=false AND (o.website_id in (23) OR o.created_by_id=1 OR o.blocked_sharing_tasks IS NULL OR NOT o.blocked_sharing_tasks @> ARRAY['R'::character ])
 AND o.website_id in (101,108,43,13,97,33,29,44,87,12,24,14,17,6,8,25,11,7,30,5,34,40,32,42,51,49,65,68,73,75,9,71,88,10,23,69,116,98,115,27,112,94,95,123)
  
  AND o.release_status='R'
AND o.confidential='f'
AND o.record_status<>'R'
AND o.taxon_path && ARRAY[182397,22366]
 ORDER BY o.id DESC LIMIT 21

**Comment by kitenetter** [comment]
Likely to be a result of the way that postgres tackles searches for records that form a small proportion of the recent data. ES may resolve this.

@johnvanbreda I can't remember whether you said you wanted to do some testing on this, and if so whether I need to take any further actions?

**Comment by johnvanbreda** [comment]
Our discussion was along the right lines - Symphyta are rarely recorded so it takes longer to trawl the dataset to fill the grid. The query did actually work when I tried it so it's probably a case of a slow query combined with heavy server load at the time.

**Comment by johnvanbreda** [comment]
I'll close this now as the Elasticsearch version of this report is fast.
