### ISSUE TITLE
Elasticsearch verification page date filter problems

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#768]
I've been trying to locate record [5280017](https://www.brc.ac.uk/irecord/record-details/?occurrence_id=5280017) (a record of Gymnadenia conopsea, recorded 7/7/2017) on the verification page.

There appear to problems with the handling of typed in dates, with the new elasticsearch page requiring rigid formatting.

On the old verification page: a typed-in date filter using `7/7/2017` to `7/7/2017` (no zero-prefix) exposes the record; a typed or date-picker selected date range of `07/07/2017` to `07/07/2017` also works; a typed-in year only `2017` to `2017` fails, but `1/1/2017` to `31/12/2017` does work.

On the elastic search page: typed-in dates without a zero prefix do not work nor does a year only date work. I get a pop-up error message, `elastic search query failed`. `07/07/2017` to `07/07/2017` does work.

It would be useful for typed in dates at various precision levels and with varying formats to be acceptable e.g. `7/7/2017`, `7/2017` or `2017` should be valid

**Comment by kitenetter** [comment]
A single date, or a year, work in the column head filter. More complex date ranges can be filtered via "Create a filter". Closing.
