### ISSUE TITLE
Verify all by grid view frequently fails

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#771]
Using the "all" selection on the new verification page frequently seems to fail. In this case, specifically, I have a grid filtered by recorder name, I choose the grid option, select "all", and choose "considered correct". I have done this a few times and quite often nothing happens.

**Comment by DavidHepper** [comment]
None of my dragonfly verifiers has reported this and it's likely they would. Could it be specific to your group(s)?

**Comment by sacrevert** [comment]
Bug is based on applying the above steps on a context limited to bryophytes.

**Comment by kitenetter** [comment]
I've just tried doing a "verify all" for a grid of two records, and similar to the above, the records have not been marked as accepted and do not get removed from the "pending" grid.

HAR file:

[www.brc.ac.uk_Archive [20-01-23 19-16-02].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4104989/www.brc.ac.uk_Archive.20-01-23.19-16-02.zip)

Screenshot:

![image](https://user-images.githubusercontent.com/16039111/73015714-6ef46580-3e14-11ea-900a-7d22cee269c4.png)

**Comment by sacrevert** [comment]
@kitenetter @johnvanbreda A bryophyte verifier (user: zygodon) has reported the same bug in the last few days. I have asked them for browser details. Do you require any other information?

**Comment by johnvanbreda** [comment]
@sacrevert can you find out what filter I would need to apply to see the same records and what status they were trying to set so I can try this out please?

**Comment by sacrevert** [comment]
@johnvanbreda Overarching filter would be bryophytes for the whole of Wales I believe

**Comment by sacrevert** [comment]
User reponse " I selected records 12834980 to 12835012 which necessitated me choosing a next page in the layout in case that's important.  Then I made comments (same for all of them since using New Verify - along the lines of 'recorder should know this taxon' and then I applied the one-tick verify.  It seemed to do something but I noticed that they were (and still are) in the pending list.  "

**Comment by kitenetter** [comment]
@sacrevert @johnvanbreda there's something odd going on here. Within the range of records 12834980 to 12835012 I can only see a comment attached to record 12834980 (from the sample that I've checked).

As far as I'm aware it's not possible to add a comment first and then apply a "one-tick verify". And on the new page there is no way of adding comments at all except by choosing the verification status first and then adding a comment.

However, on the old page it is possible to directly add a comment to an individual record without verifying it, which on the face of it looks like it might be what has happened with record 12834980.

So I think there may still be some confusion over old vs new and over how the commenting system works. If needed I'm happy to talk to zygodon on the phone.

**Comment by sacrevert** [comment]
It may just be that he is misremembering the process, and is just indicating that he was trying to bulk-verify the records with a single comment? The other single comment might have come after the failure.

**Comment by sacrevert** [comment]
@johnvanbreda @kitenetter 
Update from recorder: "I didn't state the problem quite precisely enough - I applied the one-tick verify and then had to fill in the message box that appears.  If it only gets put against one record then that is part of the bug."

**Comment by johnvanbreda** [comment]
I think what has happened here is the user has used the ticklist mode to select a range of records, then paged to the next page (losing the previously ticked list) and ticked another record. Then when they applied the verification comment, only the last record was actually verified.
Unless using Verify All, the verification only applies to records on the current page.

**Comment by sacrevert** [comment]
OK, thanks @johnvanbreda . I will let the user know, and suggest using filters etc. instead.
