### ISSUE TITLE
New custom habitat field on bryophyte form

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#772]
The https://www.brc.ac.uk/irecord/enter_bryophyte_records page has a (broad) habitat field on the "Where Was It?" page. However, it would also be good to have a fine-scale microhabitat field underneath this that is free text. This would be labelled "Microhabitat".

This would also appear as a custom field for bryophyte recording on the app (not sure whether this would be a dynamic attribute that would be of use for other species groups?)

Flagging @DavidRoy and @kitenetter in case they wish to comment
Links to https://github.com/NERC-CEH/irecord-app/issues/177

**Comment by kazlauskis** [comment]
I am happy to add this in to the app once it is available for editing on the website.

**Comment by DavidRoy** [comment]
This is created on the warehouse as sample_id = 1460

**Comment by sacrevert** [comment]
@DavidRoy 
This is now appearing on the bryophyte form, however, it is appearing at the sample level (Where was it?) rather than where is needs to be, which is at the records level (What Did You See?).
It's also duplicated under the "Other Information" tab.

To avoid congestion at the record level, we could move some of the fields so that they are hidden unless one expands the record. (The vascular plant form does this).

**Comment by sacrevert** [comment]
Do you want to close this issue? Or shall we rename to ref the expandable field addition?

**Comment by DavidRoy** [comment]
I suggest we close as the primary aim was to have microhabitat available via the app and for records to be editable via the website form.  Raise a new issue if the expandable fields is important
