### ISSUE TITLE
ES Verify - is it time to drop the "We welcome feedback... " banner?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#773]
This would give back to the verifiers about 60 much-need pixels vertically.

**Comment by kitenetter** [comment]
Hi @DavidHepper I am desperately trying to find time to update all the guidance associated with the new page (once we've finished changing things, which is very close now) and to clarify the situation with the new vs old page. There will be a verifiers' newsletter going out shortly as well. As part of this I will sort out the banners. Hopefully very soon! 

Closing as a separate issue.

**Comment by DavidHepper** [comment]
Thanks!
