### ISSUE TITLE
CSV import getting columns scrambled

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#774]
Phil Brighton reports problems relating to column-matching from a csv import, which has some similarity to #704 and #717 

I will ask for a copy of the csv file. Adding to the current milestone as this could have knock-on effects for other imports.

I will also try to define which records now need to be deleted.

Phil says:
"I had a problem uploading two Anthomyiidae spreadsheets over the last couple of weeks.   They both contained leading columns relating to order or family.   Although I matched the species field to taxon during the import process, I still ended up with the leading column showing the original contents of column A.   In one case this was Anthomyiidae and they appeared in my verification window so I marked them as not accepted and reloaded the data after deleting the first column.   Another file had "Order" in column A, so I have ended up with a whole load of records just of "Diptera" on my account, which do not of course do not appear in my verification window [which filters at family level] – these are records around No 12549413.

"I have found the page for matching the fields to be rather tempramental – you think you’ve clicked on something from a drop-down menu but then you notice something else has actually appeared there. Perhaps this is why I’m getting this transfer of column A, but I was careful to check with Paul Cobb’s data the second time I tried it."

**Comment by kitenetter** [comment]
@kitenetter to chase Phil for csv file

**Comment by kitenetter** [comment]
I still need to check where Phil's file has got to, but I've now encountered a similar problem myself. The file I was trying to import had an external key in column A, followed by the taxon in column B. The system tried to match column A to the taxon:

![image](https://user-images.githubusercontent.com/16039111/77261235-0e9f6a00-6c85-11ea-8b4f-4ce67b5b56dc.png)

The file I was trying to import is:

[All records for iRecord_edited.zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4366402/All.records.for.iRecord_edited.zip)

This was uploading into the iRecord Import survey, using UK Master List.

I've now re-saved the file with the taxon in column A and the external key in column B and it seems to be importing successfully.

**Comment by johnvanbreda** [comment]
Hi @kitenetter, did you map the MapMate GUK field to the Occurrence > External Key field, or Occurrence > Species or taxon external key field?

**Comment by kitenetter** [comment]
I'm 99.9% certain I matched it to Occurrence > External Key.

**Comment by johnvanbreda** [comment]
Thanks Martin - I managed to reproduce this and traced it to an old bug which is now fixed.
