### ISSUE TITLE
Info boxes for headers in new verification view

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#778]
Some "hover-over" info for the column headers in the new verification view would be useful. For example, it's not immediately obvious to a new user that filtering on ID orders records by date, and is more efficient than the pagination that was available in the old verification view.
![Picture1](https://user-images.githubusercontent.com/5985134/72793988-1f0a7880-3c33-11ea-998e-17fd2115b595.png)

**Comment by kitenetter** [comment]
I've not seen any similar requests from other users. The date column is more reliable for sorting by date than the ID column. Closing.
