### ISSUE TITLE
ES Verify and ES report have not updated after bulk deletions

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#781]
ES has not updated correctly since the deletion of large record ID ranges yesterday.

Example: filter by dragonflies in Bedfordshire VC:
- classic Verify shows 364 pending. I think this is correct.
- ES Verify and the Stats report 'counts_by_vc' shows 5,111 pending, including many that have recently been deleted e.g. 12090496.

These counts are wildly different over 8 hours after any significant changes were made. 12090496 is in the second of the ranges in #707 deleted by @burkmarr yesterday. In classic Verify it is unfindable but in ES Verify it can be examined as if it was never deleted.

**Comment by johnvanbreda** [comment]
Looking at this now.

**Comment by johnvanbreda** [comment]
Fixed. There was a blockage due to a large number of deletions on the 10th, which I've now cleared through.

**Comment by DavidHepper** [comment]
Thank you, John. The report makes much better reading now.
