### ISSUE TITLE
Notification email too large to open

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#784]
Last week and again today I received a 3.5 MB notification email. My (admittedly old) mail client reports "Too many paragraphs" and won't open it. I doubt it conforms to the MIME limits. 
How about a limit, which wouldn't have to be policed accurately, of 1,000 rows per message? Anything more to report and a new message should be started.
It's a particularly busy time for my verifiers and I've done some large imports so my email is the one to be notified.

**Comment by DavidHepper** [comment]
A new record: a 5 MB notification email today. Someone's been busy.

**Comment by kitenetter** [comment]
@DavidHepper since 2020 we've made some changes to the handling of notifications - are you still seeing these excessively large emails?

**Comment by DavidHepper** [comment]
They occur after very large spreadsheet imports because all the corresponding verifications treat the record as belonging to the CMS User. I've not done one for a long time and this is a low priority so I suggest you can close the ticket.
