### ISSUE TITLE
ES Verify: Redet causes removal of record from the grid

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#787]
One of my verifiers reports "when I redetermine a record, it disappears from view before I can accept it".
I've not checked this myself but it doesn't sound intentional. "Redetermined" isn't a status in the drop-down selector at the top.

**Comment by kitenetter** [comment]
A redetermination causes the record to drop from the verification grid, and reappear c. 10-15 minutes later when ES refreshes. This needs to be made clear in the documentation, still to do under #785. Closing.

**Comment by DavidHepper** [comment]
!

**Comment by johnvanbreda** [comment]
Just for clarity - when a record is imported into Elasticsearch, it does so via a tool called Logstash which sits elsewhere in the system and is inaccessible to iRecord. This tool augments the taxonomic information held for each record (e.g. to make hierarchical searches on taxonomic parents fast). Therefore, when iRecord changes a determination of a record, the taxonomic data held against the record needs to be updated properly by Logstash before the record becomes "valid" again. So, we simply mark the record with an invalid website ID temporarily so it drops out of view until Logstash rebuilds the Elasticsearch copy of the record later.

A better, but more complex solution, would be to replicate the augmentation process performed by Logstash in the iRecord verification tool. This is quite a tricky task though.
