### ISSUE TITLE
ES Verification grid - "Determiner" field incorrectly displayed.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#789]
Looking at the "Hymenoptera - all" Verification grid today and noticed that the "Determiner" field shown when the page is first displayed is very oversized and is squeezing a lot of the other fields.

This problem goes away and the Determiner field reverts to the expected size if I select a particular species to display in the Species column.  If I clear my search text from the Species column the Determiner field reverts back to this large size.

![Image1](https://user-images.githubusercontent.com/18451743/73704022-bd91e180-46e9-11ea-8e63-452ce88770b7.jpg)

As far as I can see, a "one off" glitch linked to this page, this does not happen on any of the other ES Verification pages I have access to.

**Comment by kitenetter** [comment]
Size of columns depends on what they contain, and the likelihood is that in the example above someone had put in a very long determiner name (e.g. a book title which people sometimes do in error). Closing.
