### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#79]
This is a non essential, but at some point it would be nice to enhance the website look. Use some more modern theme (say from google [flat design](https://design.google.com/) set).

**Comment by MNSmith** [comment]
At the risk of sounding petty, I would much rather see time spent sorting out all the minor little inconsistencies and formatting issues within the current iRecord system than "making it look prettier".  As an example, on the verification screen, depending on where the record has come from, the layout of the fields on record data tab is different in nearly every case.  A similar point can be made about the "Record" page.  If iRecord/Indicia is going to be used as the basis for multiple systems (eg the new Natural England ISIS replacement) then there should be a standard layout of things like Record Number and basic "what when who where" data in the first part of the record.  Consistent layout makes for easier and faster working.

I have a small "gripe list" which I have discussed with David and Martin previously.  I could use Github to raise new issues to cover all these if that might be the best way to get these gripes "on record" but I don't want to flood the system with lots of issues.  They may all be minor but they all add up and it would be very useful to get these cleared before any "cosmetic" progress.  What would be the best way to proceed?

**Comment by kazlauskis** [comment]
I think this is for @kitenetter to answer this one, but my personal opinion is that an issue tracker is a perfect place to log feature requests, especially, when they are tiny ones. I think so because when coding you tick-off small issues one by one by submitting relevant commits or otherwise have to break a large problem into something manageable.

**Comment by kitenetter** [comment]
@MNSmith as Karolis says there is no reason for you not to add issues here, but if you prefer I'm happy to add them on your behalf - the only benefit of doing that is that I may be aware of whether the issue has already been raised under another heading. If you do want to send issues to me then best thing is to send an email to irecord@brc.ac.uk and I'll pick them up from there.

**Comment by johnvanbreda** [comment]
A note on the issue of theme - the AdaptiveTheme which iRecord is based on does not seem to be getting support under Drupal 8 and I've recently switched to Bootstrap as a base theme with good results.

**Comment by BirenRathod** [comment]
@johnvanbreda, good choice. I had done some work on Darwin project using Bootstrap theme. So far so good for simple form. Not yet done for multiple species entry. So haven't found any issue yet.

**Comment by kitenetter** [comment]
Closing for now.
