### ISSUE TITLE
Concern over reliability of iNaturalist photo

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#791]
From Ingrid, VC33: " in one email I received I became concerned about the photos attached to the [iNaturalist] records. I'm not sure whether these are actually taken by the person who has sent in the record, but have come from other sources. One person has admitted to using a photo from elsewhere representing the species he has seen, when submitting his record."

**Comment by kitenetter** [comment]
Thanks @DavidHepper. We've had a few similar conserbs raised, and it is good to know about this one (if it's possible to give one or two specific examples that would be very useful).

This is one of the things that has led to the iNat import being paused. The iNat data does need treating a bit differently to the 'normal' iRecord data and we hope to make that clearer before we switch it back on. If verifiers wish not to see the iNat data I'm happy to remove it from their view, or put it into a separate filter.

**Comment by kitenetter** [comment]
Closing, but may need to revisit if we are able to develop further links with iNaturalist.
