### ISSUE TITLE
Update taxa and verification status for Xylella project

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#793]
This refers to a spreadsheet "Redetermine_list for Martin_from Claire Harkin 2020_01_27_edited.xlsx" in:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Projects\Xylella

The spreadsheet contains a set of data relating to leafhoppers covered by the Xylella project, which has been verified offline. 

The first worksheet contains some metadata.

We need to update the taxon name AND the two verifiation status attributes for all the records listed on the second worksheet, and to update just the two verification status attributes for all the records listed on the third worksheet. In both cases records should only be updated if their current record_status = "C".

@burkmarr this is needed as soon as we can do it please, hence adding to the Feb milestone. Let me know if you want me to list the relevant IDs for the taxon names.

**Comment by burkmarr** [comment]
@kitenetter - the proper taxon_taxon_list_ids would be very useful if you have them.

**Comment by kitenetter** [comment]
@burkmarr I've added the taxa_taxon_lists_id to each of the taxa that we need to **change to**. I don't think you need them for the taxa we are **changing from**? But if you do let me know.

**Comment by burkmarr** [comment]
Thanks @kitenetter. I only need the new ones.

**Comment by burkmarr** [comment]
@kitenetter - the records are updated and task_cache_builder_update tasks in the work_queue (a little under 12,000 of them so will tak a little while to work through).

**Comment by burkmarr** [comment]
Ongoing to account for additional changes to occurrences and concomitant additions to determinations and aoccurrence_comments tables. Some problems with update to determinations table which is in the process of being sorted out.

**Comment by burkmarr** [comment]
@kitenetter - the update of this is now completed as documented in the Word document in W:\_BRC_projects\iRecord\Projects\Xylella\. Work_queue tasks are entered to build the cache table entries for all the affected records. The work_queue is quite long at the moment, so give it a chance to work through. I will keep an eye on it and update when the tasks have all run.

**Comment by burkmarr** [comment]
@kitenetter - the cache builder tasks all successfully completed.

**Comment by kitenetter** [comment]
@burkmarr @johnvanbreda @BirenRathod many thanks to all involved in what turned out to be a much more complex task than I originally envisaged. Closing.
