### ISSUE TITLE
Where does the "marine" flag for taxa get stored?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#794]
We've been asked to remove the "marine" flag from the Garden Snail, Cornu aspersum. In the long term this needs to be done within the UKSI. But in the short term I'd like to make this change within iRecord.

Which table is the marine flag stored in?

Can you foresee any undesireable consequences of removing the marine flag?

**Comment by johnvanbreda** [comment]
The raw data for this is in the taxa table and it is copied into the cache_occurrences_functional table, plus cache_taxa_taxon_lists and cache_taxon_searchterms. Just updating the flag in the taxa table along with the updated_on flag, then inserting a work_queue task for the relevant occurrences, should do the trick.

I can't see any undesirable consequences other than it will disappear from some filters.

**Comment by kitenetter** [comment]
@burkmarr please can you do an update along these lines:

Update taxa
Set marine_flag = FALSE
Set updated_on = now()
WHERE id IN (61952,61953,61954,61955)

I'm not quite sure what the work_queue task needs to do, is it to update the three cache tables that John lists? If so the updates are:
- In table cache_occurrences_functional, set marine_flag to FALSE for all rows with preferred_taxa_taxon_list_id = 61952
- In table cache_taxa_taxon_lists, set marine_flag to FALSE for all rows with preferred_taxa_taxon_list_id = 61952
- In table cache_taxon_searchterms, set marine_flag to FALSE for all rows with preferred_taxa_taxon_list_id = 61952

**Comment by johnvanbreda** [comment]
Probably easiest to just set updated_on=now() for the taxa_taxon_list entries, then for occurrences with the right pref_taxa_taxon_list_id do a manual update of the maring_flag.

**Comment by burkmarr** [comment]
The taxon_meaning_id is 26933. This is the SQL I ran:

```
Update taxa set marine_flag=false, updated_on=now()
where id in
(select taxon_id from taxa_taxon_lists where taxon_meaning_id=26933)

update taxa_taxon_lists set updated_on=now()
where taxon_meaning_id=26933

Update cache_taxa_taxon_lists set marine_flag=false, cache_updated_on=now()
where taxon_meaning_id=26933

Update cache_taxon_searchterms set marine_flag=false
where taxon_meaning_id=26933

update cache_occurrences_functional set marine_flag=false
where taxon_meaning_id=2693
```

I think that should do the trick - let me know if not.

**Comment by kitenetter** [comment]
@burkmarr your final SQL statement is missing the last numeral "3", I'm guessing that is just a copy-and-paste anomaly but thought I should highlight in case it was actually in the query!

**Comment by burkmarr** [comment]
@kitenetter - Ha ha - I certainly hope so!! (I can confirm it was a copy and paste error - the SQL was correct!)

**Comment by kitenetter** [comment]
That seems to have worked in that our marine mollusc verifier is no longer seeing garden snail records on his old verification page. They are still there on the new verification page, but I'm assuming that will feed through the caches in due course. Will check tomorrow.

**Comment by kitenetter** [comment]
Resolved for now, will presumably need re-visiting when we next do a full UKSI update. Closing.
