### ISSUE TITLE
ES Verification - possible problem with verify being applied to unselected rows?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#795]
A new but trusted CDR has been using ES Verify in Multiple Selection mode and reports that some records he either rejected or hadn't previously reviewed became accepted unexpectedly. Is it possible that the system is keeping some previously-processed records selected without showing them, such that they are inadvertently subject to the next operation to Accept **selected**?
- ID: 12697042 - unexpected Accept from status Rejected is stamped: "Cham, Steve 2020-02-13 20:02:04"
- ID: 64505 - unexpected Accept from status Pending is stamped: "Cham, Steve 2020-02-13 20:02:06"
He says he didn't accidentally click the **all** button for 'Apply decision to' but this remains a possibility. Given that these two examples are different species but the timestamps are within 3 s it seems unlikely, given his description of the way he works.
I realise that this is a bit vague and I don't have time to try it in Training mode but neither do I want to lose the report as, if true, it would be serious.

**Comment by johnvanbreda** [comment]
@DavidHepper between 20:02:04 and 20:02:06, 245 records were set to accepted as considered correct by the same user, so it does very much look like the Accept All feature was used. We don't have a concept of hidden rows or remembering previously checked rows in the code and rebuild the list of IDs to accept from those rows which have the checkbox checked each time you do a verification when applying the decision to selected rows.

@kitenetter although I'm fairly confident of the above, it wouldn't hurt to try and reproduce this at some point just in case.

**Comment by DavidHepper** [comment]
No further reports. Happy to close this.
