### ISSUE TITLE
Improve handling of absence records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#796]
This is to flag an issue that needs further thought. It is apparent that some recorders are using the quantity "0" to indicate "Present but not counted", probably because this is the convention in MapMate.

iRecord interprets a count of "0" as indicating absence, and flags the record as zero abundance = true.

We need a better way of handling this, either by treating zero abundance as a separate attribute in its own right, or by making it VERY clear to people entering records that a zero will be interpreted as an absence record.

**Comment by DavidHepper** [comment]
I support this review. On BDS forms or imports, where several life stage abundance values are entered for a single species, if only a non-adult life stage is recorded the Adults value may be left blank or set to zero. A record with zero or blank across *all* stages could be considered a Record of Absence but we have never explicitly said so and currently instead advise recorders to use the iRecord Generic form where the Absence flag can be actively selected.

**Comment by kitenetter** [comment]
Being dealt with under #968 - closing this one.
