### ISSUE TITLE
Add hyperlink to view record in email sent by verifiers

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#8]
In emails sent to verifiers notifying them of recorder responses to queries, it would be good to include a hyperlink to the record itself (from Alan Stewart)

**Comment by kitenetter** [comment]
Similarly, in auto-emails notifying recorders of comments on their records a hyperlink would facilitate responses to the comments

**Comment by johnvanbreda** [comment]
Duplicate of https://github.com/Indicia-Team/warehouse/issues/186.

**Comment by johnvanbreda** [comment]
This issue now coded in the development branch and tagged so that it will get released in the next version of the warehouse.
