### ISSUE TITLE
"What" filter on milestones broken?

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#804]
The "what" filter appears to be the only filter that doesn't work. I tried created a new milestone, and editing an existing one, and in both cases clicking the "what" in the filter options doesn't do anything.

e.g. http://warehouse1.indicia.org.uk/index.php/milestone/edit/12?filter_id=5982#controls-filter_what

(in Chrome Version 79.0.3945.130 (Official Build) (64-bit))

**Comment by johnvanbreda** [comment]
Now fixed.

**Comment by sacrevert** [comment]
@johnvanbreda Thanks John. Glad that it needing fixing, and wasn't just me being an eejit.
