### ISSUE TITLE
Duplication of records from iRecord App

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#806]
Record ID 11572458 and ...59 were submitted by iRecord App version 4.0.2.3. They appear to be identical in every respect, even down to the 'ID in source system' = 92c9d39c-557c-4089-95e6-299dac7094e4
Would it be useful for the system to reject or update records with the same 'ID in source system' to prevent duplication? 
I've not investigated whether this is a systemic problem but came across it when looking for duplicates in general.

**Comment by kitenetter** [comment]
To be investigated alongside similar issue with butterflies app. Ideal solution is to develop apps to have more robust synchronisation.

**Comment by kitenetter** [comment]
I haven't seen any recent reports of this issue. Closing.
