### ISSUE TITLE
Notifications from dev irecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#807]
At 4.53 this afternoon I received a very long list of notifications saying that my butterfly records have been verified by iRecord. If I click on one of the links I can see that these refer to http://test.brc.ac.uk/irecord_dev but that isn't at all obvious from the email itself.

Have similar notifications gone out to a lot of recorders? Am worried that this will have caused confusion.

**Comment by kitenetter** [comment]
I've just received another very lengthy email containing notifications from the dev site.

**Comment by burkmarr** [comment]
@kitenetter - for some reason, the Warehouse email configuration on dev was changed (application/config/email.php). The following option which should be there on dev, was missing, so I've just added it in:

$config['do_not_send'] = true;

That should stop them (I've had some too).

**Comment by burkmarr** [comment]
@kitenetter - I've realised that this problem arose because another one got fixed. That was the repeated failure of scheduled tasks on dev. That is now fixed which lead to the completion of scheduled tasks which had not run for many months. Still the email option should also have been set.
