### ISSUE TITLE
ES verification: display not updating for edited records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#809]
A recorder added some records (via the new "Moth Survey" function on the app). The app assigned tetrad grid refs to them. On the ES verification page the tetrad refs were displayed as 10km refs.

The user then edited the records to give 100m grid refs. However, the ES verification page is still displaying the records as 10km records, both in the grid and in the Details pane.

**Comment by johnvanbreda** [comment]
Can I have some example record IDs please?

**Comment by kitenetter** [comment]
IDs:
- 12835134
- 12835133
- 12835132
... and back as far as:
- 12835110

For the first of those, the verification page shows:

![image](https://user-images.githubusercontent.com/16039111/76977701-90159600-692d-11ea-9d88-3e8ff4537028.png)

And the more detailed grid ref is on the record page at:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=12835134

**Comment by johnvanbreda** [comment]
@kitenetter I can see that when they updated the sample spatial reference, the change was applied to the sample in such a way that the system did not detect it as a change which applied to the occurrences. But, if I use the normal method of editing one of my records, this does not happen so ES gets updated properly. Do you know exactly what they did to update the grid reference?

**Comment by kitenetter** [comment]
@johnvanbreda the recorder in this case was Marc Botham, who says "I just went into website, picked a record from the survey, went to edit it, then chose to see all records from that survey and changed the gridreference and submitted."

So perhaps this was a one-off glitch? I think Karolis has fixed the bug in the app that caused the incorrect grid ref in the first place, so if you can't see anything wrong at the iRecord end we can close this issue.

**Comment by kitenetter** [comment]
The records in question have the correct 100m grid reference in the sample and ocurrence entries in the warehouse, but are still displaying a 10km grid ref via ES verification.

However, I'm not aware of this causing any wider problems. Closing.
