### ISSUE TITLE
Dynamic terms - termlists

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#812]
This follows on from #637 

**Sex**
For all taxon groups, use:
- termlist ID 126: Sex

**Stage**
New termlists have been created in the warehouse as follows:
- termlist ID 888: Stage - vascular plants (not ferns)
- termlist ID 889: Stage - ferns
- termlist ID 890: Stage - bryophytes
- termlist ID 891: Stage - invertebrates
- termlist ID 892: Stage - birds
- termlist ID 893: Stage - mammals
- termlist ID 894: Stage - herptiles

All other taxa should use:
- termlist ID 127: iRecord Stage

If possible, we should make the stage attribute mandatory for all taxa.

If possible, we chould set the stage term to be pre-populated with the default of "not recorded", EXCEPT for invertebrates, where there should not be a pre-populated default (the "not recorded" option is still available but should be chosen deliberately).

Is any further preparation required in order to implement these in the app and in the website generic recording forms?

**Comment by kazlauskis** [comment]
> stage attribute mandatory

What if you don't know the stage, do all the termlists have an option for that? I personally very much like that we don't currently force the user to add much information to a record.

**Comment by kitenetter** [comment]
@kazlauskis all termlists include "not recorded" as a stage, and my proposal is that all taxon groups EXCEPT invertebrates should default to "not recorded" if the user does not do anything. However, for invertebrates it is critical that we know the correct stage for phenology purposes, and we really do need the recorder to specify what it is they are recording. They can choose "not recorded" but we don't want that to be the default option.

As always there is a balance between making it easy for the user vs producing records that have enough detail to be meaningful.

**Comment by kitenetter** [comment]
I've just been trying to use the new stage termlists but I cannot find them anywhere in the warehouse, which either means I did something stupid when I thought I had set them up, or they've been somehow deleted since I added them.

It does seem odd that I used ids in the range 888 to 894, but when I look at the table of occurrence attributes now there is no ID higher than 828.

I will re-create them, but can @johnvanbreda let me know if there is anything odd going on here, other than error on my part.

**Comment by kitenetter** [comment]
Just realised which particular stupid thing it was that I was doing! I created termlists, not occurrence attributes - doh!

@johnvanbreda ignore me.

@kazlauskis for the app, do you need occurrence attributes to be set up for all these termlists, or can you work directly with the termlists?

**Comment by kazlauskis** [comment]
@kitenetter yes, we need to set up occurrence attributes with whatever termlists to be used in the app. You would probably want to set these new attributes only to the applicable species groups instead of how we used to do it before (which was creating a mega survey).

**Comment by kitenetter** [comment]
I'm not aware of how to link occurrence attributes to species groups as suggested above. They are linked to surveys. Should I set them up for just these surveys?:
- iRecord app
- iRecord App General Survey
- iRecord General data

(iRecord import already has a longer combined list of stage terms, which seems a better way to deal with imported data.)

**Comment by johnvanbreda** [comment]
@kitenetter on the warehouse go to Observations Data > Survey datasets, find the survey, click the setup attributes link. Select Display Attributes For=Occurrences and click Go. Click Survey Settings for an attribute. Taxon restrictions can be set at the bottom of the form.

**Comment by johnvanbreda** [comment]
@kitenetter is there anything I do to help you get going with this, as it is on my current list of sub-projects. For example, would you like me to configure the generic iRecord recording forms to use the correct stage attribute for one of the example groups, e.g. Vascular plants?

We also need to think about how to collect bird breeding status terms. After the discussions with BTO the agreement is to set these to map to the Darwin Core reproductiveCondition term. The warehouse now allows you to flag an occurrence attribute with the system function Reproductive Condition (there is also a new Behaviour system function). If we are going to allow reproductive condition to be recorded, which seems sensible, then we need a column in the grid on the enter a list of records forms. This column might be shared with behaviour type attributes - e.g. if selecting a bird, you get the breeding status terms, if you select a bee we could have a behaviour termlist with terms such as basking, collecting pollen etc. For other taxa this would be an unused attribute so I suggest that we make this attribute only appear when the user clicks the + button in the right of the grid that appears when you enter a species name. If you want to see how this works then try the standard enter a list of records form, but resize your browser so the form is quite narrow.

**Comment by kitenetter** [comment]
@johnvanbreda Last time I looked at this (which was a while ago) I think I was tasked with setting up the occurrence attributes that would make use of the new termlists. I never managed to do that, and I think we were hoping that you could pick this up as part of the current work but @DavidRoy can confirm priorities if needed.

For the new Reproductive Condition and Behaviour attributes I think your suggested approach is sensible. I wonder how many recorders will make use of this if it is 'hidden' behind the plus button, but I agree that it would be unhelpful to make these attributes appear for all the taxa that don't use them.

An alternative or additional option is to set up new taxon-specific recording forms for the taxa that use these additional attributes. Having a separate form won't suit multi-taxa recorders but may be useful for taxon-specific recorders.

Note to self: is Reproductive Condition a suitable attribute to store information on queen/worker castes for aculeates? Need to check DwC definitions.

**Comment by johnvanbreda** [comment]
@kitenetter I can pick this up as part of current work. Good question about castes, not sure if they count as a life stage, behaviour or reproductive condition (or perhaps a bit of all 3!).

**Comment by johnvanbreda** [comment]
@kitenetter I've set up the dynamic attributes now, using just Bryophytes as an example so we can make sure it is working correctly before adding other attributes. Here are the steps I performed to enable this:

1. As there was already an attribute id 807 for Stage - Bryophytes with the same terms in its termlists, I removed the termlist you had added and used this attribute instead. Otherwise I would have added a new custom attribute for Stage - bryophytes and linked it to you termlist.
2. I added attribute ID 807 to both the iRecord general records (42) and multi-site records (100) surveys.
3. From the edit attribute pages (after saving, then reloading) I clicked the button to load the survey specific settings in a new tab for each of these surveys.
4. On the survey specific settings page, I entered "Bryophyta" in the taxon restrictions and saved it (for both surveys)
5. I then entered some configuration on the single record, list of records and multiple places entry forms in iRecord to enable the dynamic attributes functionality. You don't need to re-do this, but note that the configuration for the 2 list forms did include an option to turn this functionality on only for taxon_group_id 133 (moss) to reduce the number of hits on the survey. As more taxon groups are included we will need to extend this setting.

Please can you let me know if it looks OK and, if so, I can add the other attributes.

@BirenRathod I am not sure if when I make changes to iRecord7, you need to know about the changes so that you can update iRecord9? Or will you remigrate at some point? I made a few notes just so we know what I changed:

> Updated iform structure for node 6 - added [species dynamic attributes] with some parameters, and div around [species attributes]. Node 6 CSS changed to use div to set controls to 50% width, rather than explicit list of control IDs.
> 
> Node 5 - general enter a list of records form, added to [species] control:
> @enableDynamicAttrs=true
> @limitDynamicAttrsTaxonGroupIds=[133]
> 
> Same for node 217 (multiple places form), added to [speciesmap] control:
> @enableDynamicAttrs=true
> @limitDynamicAttrsTaxonGroupIds=[133]

**Comment by kitenetter** [comment]
@johnvanbreda that seems to be working well for bryophyte stages.

I note that if you are adding a list of records and include a bryophyte, the width of the "Stage" column increases (and other columns reduce). I don't think that is a problem unless we get to the point where some columns become hard to read/write.

I note also that if I add an "Adult" butterfly, the next line defaults to "Adult" for the next species, but if that next species is a moss the Stage box is emptied (which I think is correct).

Having added a moss, if I then go back to another butterfly it defaults back to "Adult" (which I think is correct).

But if I add a moss then another moss the Stage box is emptied each time, i.e. it doesn't default to the choice on the previous row. Ideally it should default to the choice on the previous row **IF** you enter another taxon from within the same taxon group, but not sure how complex that is to achieve.

The other requirement for this issue was:
- If possible, we should make the stage attribute mandatory for all taxa.
- If possible, we chould set the stage term to be pre-populated with the default of "not recorded", EXCEPT for invertebrates, where there should not be a pre-populated default (the "not recorded" option is still available but should be chosen deliberately).

Maybe that needs to be put into a new issue for subsequent work after we have the dynamic termlists working? But it would be really helpful if we can implement these two bullet points.

**Comment by johnvanbreda** [comment]
@kitenetter I've just added the ferns and made the attribute mandatory - I'll add the others later and it should be OK for it to work as you suggest. One thing though - the ferns and bryophytes termlists are more or less identical, apart from the addition of (fruiting) etc for clarification. Couldn't they be the same attribute? 

Also, for the fern attribute, will it just be for Pteridophyta?

**Comment by johnvanbreda** [comment]
@kitenetter for the Invertebrate termlist, I'd suggest that we actually link this to Arthopoda for a couple of reasons. There is no concept in the current UKSI hierarchy for Invertebrata so it would need to be linked to a long list of Phyla. Also, I wonder if this list of terms is really useful across all invertebrates (tardigrades, rotifers etc)?

**Comment by johnvanbreda** [comment]
Just the questions in the 2 comments above to do - everything else done.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 

For ferns/bryophytes I'm awaiting advice from @sacrevert 

For invertebrates I agree that Arthropoda is a good choice, at least for now.

**Comment by johnvanbreda** [comment]
I've setup the Arthopoda dynamic terms as well now.

**Comment by kitenetter** [comment]
@johnvanbreda I have a report of the new terms not working on the enter a casual record page. This is from a user with firefox, who says: "It comes up with the old options, then switches to the new options and then bombs out", and he is unable to save a record. Rather fuzzy screenshot:

![image](https://user-images.githubusercontent.com/16039111/113026718-43d87500-9181-11eb-971d-ae6ffa0476de.png)

I can't reproduce this on my firefox.

**Comment by kitenetter** [comment]
Botanical advice from @sacrevert is that we do need to retain separate termlists for bryophytes vs ferns (the wording and ordering are both different, and the differences are useful).

My interpretation is that for ferns, the terms can be applied to all taxa under Pteridophyta.

The bryo terms need to be applied to three phyla:
- Bryophyta
- Anthocerotophyta
- Marchantiophyta

**Comment by johnvanbreda** [comment]
I've set up bryophytes as requested (note the 2nd taxon was Anthocerophyta, I think there was a typo in the above).

I think this can be closed now?

**Comment by kitenetter** [comment]
I *think* it is UKSI that has the typo: they have Anthocerophyta for hornworts, but Bryological Society sources use Anthocerotophyta.

@sacrevert should we ask UKSI to change this?

Great to have the dynamic terms feature available. There are still some things listed in various bullet points above that we have not yet achieved, but I will add those as new issues. Closing this one.

**Comment by sacrevert** [comment]
Thanks all. Yes, it is just a UKSI typo. I can ask them. Cheers
