### ISSUE TITLE
Vernacular name missing from display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#814]
The vernacular name "Red Mason Bee" applies to species Osmia bicornis. If you enter "Osmia bicornis" into iRecord, "Red Mason Bee" is displayed alongside the scientific name. However, it is not possible to enter the name "Red Mason Bee" - only the related "Red-tailed Mason Bee" is offered.

In table "taxa" Red Mason Bee exists with id = 197250 and id = 258899. The second of those two entries appears to be an incomplete entry (values are missing for "search_code" and "scientific"), but both names appear to be available for use.

In table "taxa_taxon_lists" Red Mason Bee appears three times, once linked to taxon_list_id = 8 (NatureSpot Leicestershire and Rutland) and twice to taxon_list_id = 74 (Garden Bioblitz Ticklist 2013).

So I'm guessing that the reason it is not possible to enter "Red Mason Bee" into iRecord is because it is not linked to taxon_list_id = 15 (UK Master List). However, I don't fully understand how the various taxa and taxon list tables function.

Can we make "Red Mason Bee" available for use in iRecord?

**Comment by johnvanbreda** [comment]
Red Mason Bee is available in iRecord, presumably after a UKSI update.

Data model documentation at https://indicia-docs.readthedocs.io/en/latest/developing/data-model.html#taxon-lists-taxa-taxon-lists-taxa explains the taxon_list and taxa tables etc.

Closing.
