### ISSUE TITLE
ES verification: add text or icon to show whether recorder was logged in or not

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#817]
As far as I can tell the only way to check whether a recorder was logged in when they added their record is to look at the Experience tab. If they are not logged in there is no point querying records or providing feedback, so it would be a great time-saver if we could easily see who was logged in and who not.

**Comment by MNSmith** [comment]
Can we please not insist that recorders have to be logged in to submit records?  If they are not, then even if they are a "known" recorder, there are no stats available or visible.  I'm seeing a lot of these recently, with sometimes multiple records from a recorder.

**Comment by johnvanbreda** [comment]
@kitenetter I've fixed the underlying request by adding an anonymous user icon to the status icons column (develop branch so will be deployed soon). 
I think the request about disallowing anonymous records, or at least making them less easy to do accidentally, is worthy of further discussion in a separate issue?

**Comment by kitenetter** [comment]
@MNSmith we are not able to enforce registration on all recording forms, as registration has been shown to be a significant barrier to participation. We could alter the BWARS-specific forms to exclude non-logged-in users but since those forms (e.g. spring bees) are designed to draw in beginners it would arguably be counter-productive to impose registration.

You should be able to contact non-logged-in recorders via email if needed, but you won't be able to see experience stats.

**Comment by johnvanbreda** [comment]
This has now been deployed.
