### ISSUE TITLE
ES verification: verification status of queried records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#818]
I've just been tidying up some queried records. If I set a queried record to "Accepted" or "Not accepted" it gets removed from the list of queried records. However, if I set a queried record to "Plausible" it stays in the queried grid. But I am not able to take any further action on the record, so I think records that are flagged as "Plausible" should also be removed from the queried list.

**Comment by kitenetter** [comment]
Further to this, our handling of the "queried" status seems inconsistent, or at least is unhelpful. Within the Berkshire moths dataset I have some records that are shown as both "Accepted" AND "queried", as well as the expected "Unconfirmed" and "queried".

This makes it very hard to filter the records that I actually want to be able to work with - I usually want everything that has been accepted, but I want to exclude anything that remains in a queried state, and at the moment I have to do some quite complex filtering to achieve that.

So I think there is a more generic requirement to ensure that a record is only flagged as queried until such time as a verification decision is added, and in this context a "verification decision" is any one of Accepted, Not accepted, or Plausible.

Questions:
1. Are we currently allowing records to be both "Accepted" and "queried", or is this a hang-over from previous procedures?
2. If we are currently handling things correctly, presumably I need to specify a database update to clean up the records that are wrongly categorised?

**Comment by johnvanbreda** [comment]
I think there is an underlying logic problem here. If a pending record is queried, then either a reply OR a verification event should reset the queried status. The only way to have accepted and queried records would be to accept first, then add a query comment. This might be applicable if, for example, you accepted as considered correct but, being an important record, you added a query requesting a specimen or clarification with the aim of moving the record to accepted as correct.

**Comment by kitenetter** [comment]
To me the logic should be that a record can only be marked as queried if it is the "unconfirmed" state. In the example you suggest, adding a query to a "considered correct" record should, in my view, reset that record to the pending/unconfirmed state.

Although there may be a theoretical argument for allowing records to be both accepted and queried, the pragmatic outcome is that it becomes very hard to work with the data that is downloaded from iRecord - it either requires complex filtering, or it is likely to result in record being included or excluded on false premises.

**Comment by MNSmith** [comment]
I've run into the same problems with records appearing to have more than one status attached to it, particularly those records which have been queried at some point.  To enable the management of large volumes of records, I would bery much like to see records only holding and displaying one status at a time.  It's very binary, it either is queried, or it it has been replied to and verified as a result of the answer, that query should be cleared.  One status per record please..

**Comment by kitenetter** [comment]
Need to check whether this is still a problem.
