### ISSUE TITLE
Download page - downloading in NBN format

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#82]
Matt Smith raised this issue:
"It would be very useful if the "NBN Exchange" format report actually produced a file which is suitable for immediate upload to the NBN Gateway - ie it follows the format requirements produced by the NBN. At the moment is does not and requires a lot of manual intervention to make it so."

MH to investigate what the shortcomings of the current format are and suggest improvements.

**Comment by kitenetter** [comment]
Needs review as NBN Exchange format is likely to be replaced by a Darwin Core format for the NBN Atlas.

**Comment by johnvanbreda** [comment]
Superceded by #304
