### ISSUE TITLE
ES verification: edited record not being presented for re-verification

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#820]
A few days ago I accepted this record:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=13102424

At the time the field date was shown as 2 March 2020. It subsequently emerged that this was a typo and it should have been 27 March 2020. The recorder has edited the record and the date is now the correct one, but the record is still showing as accepted, and did not get shown to me as a pending record after it had been edited.

So the record is now correct and is fine to stay as accepted, but edits to records ought to trigger a return to the pending status.

**Comment by johnvanbreda** [comment]
Now fixed - this occurred because the only thing that changed was in the sample, so the occurrence update didn't trigger re-verification.
