### ISSUE TITLE
Controlling user log-in requirement?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#822]
@johnvanbreda please can you remind me where the controls are for determining whether a user has to be logged in to use an iRecord form.

This is for PoMS - we currently require users to be logged in to iRecord before they can add their FIT Counts, but we are probably going to remove this requirement. How do I make the form available to non-logged in users (so that they just have to enter their email instead)?

**Comment by johnvanbreda** [comment]
@kitenetter if you edit the form, there is a section Other IForm Parameters, untick "View access control" and clear the setting from "Permission name for view access control".

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - got that sorted now. Closing.
