### ISSUE TITLE
ES verification: inconsistent updating of grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#823]
I've been verifying bee-fly records. Most of the time they are behaving as expected, but I've started seeing the occasional record remain in the grid despite it being verified. Usually, possibly always, this has been after I have selected multiple records using tick boxes - most of the records get taken out of the grid as expected, but not all of them.

Examples of record IDs that did not get removed are:
13109898
13126159
13109632
13147089

Will turn the HAR file option back on again!

**Comment by johnvanbreda** [comment]
@kitenetter Am I right in thinking the records that are failing are sensitive?

**Comment by kitenetter** [comment]
@johnvanbreda I didn't notice yesterday, but it's possible and it's just happened again to a single record today (ID 13151406) that is marked as sensitive. HAR:

[www.brc.ac.uk_Archive [20-04-05 20-36-25].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4434637/www.brc.ac.uk_Archive.20-04-05.20-36-25.zip)

**Comment by johnvanbreda** [comment]
Ok, I've changed a couple of things but it's hard to be sure. I think the problem only occurs if you verify a list of records where some are sensitive. However in my simulations of this I've not been able to reproduce it so can only guess at what's required. I've changed the code to more explicitly update both the blurred and full precision copies of each record. I've also changed the code to tolerate any update conflicts so all records should be updated.

Please can you check if verifying a list containing one or more sensitive records now works @kitenetter ?

**Comment by johnvanbreda** [comment]
Should now be fixed.
