### ISSUE TITLE
App abundance codes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#825]
I'm now seeing bee-fly records with an abundance shown as a code:

![image](https://user-images.githubusercontent.com/16039111/79055486-72de9980-7c45-11ea-96d3-69bab0b52578.png)

This is an unhelpful backwards step and makes the data more untidy and difficult to use. Please can we stop doing this?

**Comment by DavidRoy** [comment]
@kazlauskis is this same bug as for bird records through the app?

**Comment by kazlauskis** [comment]
Yes, it's same as #187 and it has been fixed in v5.1.2 so if you see any more of these with this version then please let me know.

**Comment by kitenetter** [comment]
@kazlauskis @DavidRoy thanks for fixing this immediate issue. As far as I can see the number ranges are still available in the app, but I assume that they no longer link to the butterfly code letters?

I have a more fundamental question though, which is whether the app should be allowing/encouraging the use of number ranges at all. To me they are always an problem - if the abundance data is to be analysed at all (which I know it often isn't) it is much easier to do so on the basis of a recorder's estimate of the actual integer number, rather than the recorder's estimate of a range, which the analyser then has to find a way of interpreting. Often this has to to mean that the lower number of the range is the only one that can be used for analysis, at least within the context of recording scheme, rather than academic, analysis.

So any use of number ranges imposes an additional task on recording schemes if they want to make use of the abundance data. I appreciate that ranges are well-established within some schemes e.g. butterflies, but personally I wish we could avoid using them outside such contexts.

**Comment by DavidRoy** [comment]
I tend to agree, but the answer is that we defer to the relevant national scheme to set the attributes to be captured.  See recent forum post on this: https://www.brc.ac.uk/irecord/node/7957

Are we using abundance categories for surveys other than butterflies?

**Comment by kitenetter** [comment]
The categories seem to be available for all taxa including plants. They are not enforced, there is an option to add an integer via a sliding scale or the incremental plus button, but I suspect many recorders will find it easier to click on a range, and it makes it look as if this is an option we want them to use.

I entirely agree that we should defer to schemes on this, and my schemes would prefer ranges not to be available!

**Comment by kazlauskis** [comment]
> As far as I can see the number ranges are still available in the app, but I assume that they no longer link to the butterfly code letters?

Yes, the ranges will be there, only it won't be linked to butterfly codes. If you see any coming from the latest version (v5.1.2) then please let me know.

> I entirely agree that we should defer to schemes on this, and my schemes would prefer ranges not to be available!

The app is flexible on this now and I'm happy to change it either way.

**Comment by DavidRoy** [comment]
> I entirely agree that we should defer to schemes on this, and my schemes would prefer ranges not to be available!
> 
> The app is flexible on this now and I'm happy to change it either way.

I agree that we should not have this as a default.  @kitenetter can you advise on the changes needed.  Is it only butterflies (and odonata?) that want the number ranges?  Did Mark Gurney request this for NT?
