### ISSUE TITLE
ES verification: Mammal Mapper records missing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#826]
The mammal verifier for Wiltshire (username "garethoharris") has 14 records of North Wilts mammals in the ES verification grid, but 350 in the old grid. At least some of this discrepancy arises from the Mammal Mapper record source - records from that source do not seem to be available under ES.

**Comment by johnvanbreda** [comment]
Fixed by updated the ES alias for verification to include website 120.
