### ISSUE TITLE
Records being incorrectly flagged as needing re-verification?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#828]
A verifier has reported that an edit to one moth record in a list has caused all other occurrences in the same list to be reset to pending, despite having previously been accepted.

This is for a set of records entered via the moth survey on the app.

The record that was edited (a change in species name) is ID 13205423. As far as we can tell no edit was made to the sample as a whole (sample ID 7940675).

I have only had one report of this so far, but have a suspicion I've seen similar behaviour in some of the records I've been verifiying recently - will look out for it and document further if I can.

**Comment by kitenetter** [comment]
I'm beginning to get reports from other users about records getting flagged up as requiring re-verification following an edit, when no edit has in fact been made. As yet I can't see a common pattern to the reports, but will continue to look out for it.

**Comment by kitenetter** [comment]
Here's an example of notifications I've had. I don't know for certain whether these records have in face been edited or not, but I can't see any obvious things that have changed.

![image](https://user-images.githubusercontent.com/16039111/79642505-c6953980-8195-11ea-8842-8056af10c57a.png)

**Comment by kitenetter** [comment]
Hmm, on further investigation at least one of these reports appears to be based on a misunderstanding - a record had been redetermined by a verifier, which triggered a notification to the recorder that their "record's verification status needs to be rechecked as it has been edited", which confused them because they weren't aware of the redetermination.

It would be good if we could improve our handling of redets, see #662 

I think there is still something odd happening with records getting shown as needing to be reverified, e.g. in the list example at the start of this thread, but I'll continue to monitor things.

**Comment by kitenetter** [comment]
Next piece of the puzzle backs up the issue being connected to editing a single occurrence and then the whole sample being set back to the pending state. This report is from verifiers Andy Banthorpe and Keith Balmer:

"I think it is a quirk of the new verifier on iRecord. I found one of Stephen’s records needed the stage amending as it was adult which was incorrect. It let me amend it but it appears it then updated all records associated with that record group on that date."

**Comment by kitenetter** [comment]
I just added a photo to an existing (unverified) record, ID 12833593, and that has caused all the previously verified records in sample ID 6120893 to be flagged as having been edited, and therefore in need of reverification. So this seems to be a general issue with editing records.

**Comment by johnvanbreda** [comment]
@kitenetter I've found the bug and this will be fixed first thing tomorrow.

**Comment by kitenetter** [comment]
Not sure if this is a reoccurrence of the same bug or something different. We're getting further reports of records being presented for re-verification but with no obvious edit having taken place.

This started from occurrence ID 13289806, a bee-fly that I had verified. I got a notification email saying that I needed to re-verify it, as verifier Dave Wilton had edited the record, but it was not entered by him and he says he didn't edit it, nor any other occurrence in the same sample, although he did **verify** one other occurrence in the same sample (ID 13289811).

Further occurrences from the same sample are now being similarly flagged as having been edited by Dave Wilton, including a couple of butterfly records verified by @DavidRoy 

The sample ID for these occurrences is 8026470.

I guess it is possible that Dave W somehow edited the sample part of a single record in this list without realising it, but he doesn't think that is the case.

Maybe this is a one-off but documenting it in case of further examples.

**Comment by johnvanbreda** [comment]
I've managed to work out what's happened using the audit.logged_actions table. During verification, Dave W did access the Edit Generic Records form and saved it. This caused the sample's updated_on to change, as well as the input_form. Although not substantive changes, the warehouse does not know the difference so considers these changes to the sample data to be worthy of firing a re-verification of the contained occurrences. 

I'll look into making the warehouse more intelligent so not all fields trigger re-verification.

**Comment by johnvanbreda** [comment]
I've updated the code so the input_form doesn't update when editing using edit-generic-record. This itself caused the updated_on to change as well as the need to re-verify the contained occurrences. So, hopefully fixed.
