### ISSUE TITLE
Potential duplication of records from iRecord butterflies app

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#829]
Not urgent, but I am adding this just to capture some preliminary investigation.  Originates from an iRecord forum post:
https://www.brc.ac.uk/irecord/node/7914

This query revealed a lot of records (2746 ), which suggests it could be a widespread issue.  But there may be a better way of assessing this:
select website_id, survey_id, public_geom, location_name, date_start, created_by_id, taxa_taxon_list_id, attr_sref_precision, count(cof.id)
from cache_occurrences_functional cof, cache_samples_nonfunctional snf
where website_id = 23
and cof.sample_id = snf.id
and attr_sref_precision is not null
and survey_id = 101
group by website_id, survey_id, public_geom, location_name, date_start, created_by_id, taxa_taxon_list_id, attr_sref_precision
having count(cof.id) > 1

**Comment by kitenetter** [comment]
As far as I'm aware this problem has not been reported recently. Closing.
