### ISSUE TITLE
Records not available to verifier - maybe missing vice-county indexing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#830]
Peter Hall is moth verifier for Herefordshire, He has imported a set of his own moth records that from a location in that county. They have been verified by the national recorder, but they have never appeared in Peter's own verification view.

I'm guessing that they have not been indexed against the vice-county.

Two examples are records IDs 13059255 and 13059276.

Can we resolve this and check whether this is a more widespread problem?

**Comment by johnvanbreda** [comment]
Looking over the last few million records, there are about 0.5% where the location_ids are not indexed. Some of these of course may be outside the boundaries of any polygons that we cover. However there was a batch of a few thousand at around the same time of data entry on the 19th March which may indicate a one off problem. Unfortunately the warehouse logs seem to have been cleaned up so I can't see them before the start of April. I've rescheduled spatial indexing though so they should be sorted shortly.
