### ISSUE TITLE
Record location inconsistency following an edit

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#834]
This applies to occurrence ID 13255185:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=13255185

On the record details page, the grid ref is showing as "SD513332", and there is a sample comment that says "Grid ref SD513332 was initially entered by accident as SU513332 - the record has since been edited to the correct grid".

However, the map display on that record details page is still showing the record as being at SU513332, and the records details as shown on my verification page also give the grid ref as SU513332.

The record was entered over 24 hours ago so I'm assuming this isn't just a caching issue.

**Comment by johnvanbreda** [comment]
Closing as now correct and there is lots of backlog in the system at the moment, but one to watch out for.
