### ISSUE TITLE
Full update of UKSI needs scheduling

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#836]
There have been a number of updates to UKSI recently, and more will come through the focus on the Darwin Tree of Life project. As well as taxonomic changes the marine/freshwater flags have been reviewed for at least some taxa, as requested by Conchological Society among others.

We need to schedule in the next full update, aiming for a balance between not falling too far behind the updates that have already been made, while being aware that more updates are in the pipeline.

**Comment by kitenetter** [comment]
Aim for an update in June. Possiblility of updating marine/terrestrial flags before then.

**Comment by kitenetter** [comment]
I'll check the marine, terrestrial and freshwater flags that are in the copy of the UKSI I had from Chris Raper last week.

**Comment by kitenetter** [comment]
UKSI now has flags for:
- marine
- terrestrial/freshwater
- freshwater

The third of those is a new attribute, and needs to be added to the Indicia data model and made available in our taxon filters on iRecord.

**Comment by kitenetter** [comment]
After further discussion we think that all four flags within the UKSI should be brought in to Indicia:
- marine [already in the Indicia taxa table, so just needs updating]
- terrestrial_freshwater
- freshwater
- non-native

This presumably needs additional attributes adding to the taxa table, but does it also mean changes to the scripts used for the updating process?

**Comment by johnvanbreda** [comment]
Yes the scripts will need updating, but I don't think it will be a big job. We'll also need to update the following:
* cache tables and the cache_builder scripts
* Elasticsearch and the Logstash config
* The filter builder

**Comment by johnvanbreda** [comment]
FYI - the develop branch of the warehouse now has additional flags:
* freshwater_flag
* terrestrial_flag (=terrestrial_freshwater_flag as the freshwater stuff will be removed from this set by Chris)
* non_native_flag
I've updated the UKSI scripts and Logstash scripts but obviously not deployed anything yet.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda.

**Comment by johnvanbreda** [comment]
@burkmarr can this be closed now?
