### ISSUE TITLE
Google maps unavailable for bat recording forms

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#840]
We have two recording forms for bat records:
https://www.brc.ac.uk/irecord/enter-bat-record
https://www.brc.ac.uk/irecord/enter-bat-list

The map panel in each of these is displaying the message "This page can't load Google Maps correctly". Can we update these to use maps in the same way as the standard iRecord forms.

**Comment by burkmarr** [comment]
This is happening on the other forms too. It looks like a licensing problem. @DavidRoy as you zoom in on any map (e.g. https://www.brc.ac.uk/irecord/enter-casual-record) and Google satellite kicks in, it displays the 'for development only banner'.

**Comment by BirenRathod** [comment]
@burkmarr Is it possible to switch on to opentopomap layer after it got zoom in?

**Comment by burkmarr** [comment]
@BirenRathod - to change the behaviour of that dynamic layer would require a code change. But it any case I suspect that we don't need to change anything just now - everything still functions, you just get the anoying banner and dialog. Whent he licensing is sorted out, I think this will go away.

**Comment by BirenRathod** [comment]
@burkmarr , Actually it doesn't require licensing bit. 
@DavidRoy , it is problem to do with billing. Are you going to enable the billing on Google? it is not enable at present.

**Comment by DavidRoy** [comment]
@BirenRathod please email me the credentials to login to the Google account

**Comment by burkmarr** [comment]
@BirenRathod licensing/billing - same difference!

**Comment by BirenRathod** [comment]
@burkmarr Google only charge when number of access go up every month. it needs to enabled billing if that is needed for that month.

**Comment by DavidRoy** [comment]
I've updated the payment method.  Please close if the issue is now resolved.
