### ISSUE TITLE
Enable some functions from verification page to open in a new tab

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#841]
We have previously implemented an option for recorder experience links to open into a new tab #573 which is enormously helpful. Can we also enable new tab opening for:
- edit record
- view record details

Where photos exist, we currently have a choice of left-click to open up to medium size, or right-click and open into a new tab at full size. Both of those options are useful at different times, so I wouldn't want to enforce the new tab every time you click on a photo. However, a nice-to-have would be if you could left-click on the photo in the way that currently happens, and then for there to be a button on the photo to open into a new tab at full size.

**Comment by johnvanbreda** [comment]
For edit record and view record details you can right click to view in a new tab. Personally I prefer this to enforcing new tabs as it remains in my control when this happens.

**Comment by kitenetter** [comment]
The strong preference of all the verifiers who have expressed a preference to me is that these buttons should open into a new tab by default.

**Comment by kitenetter** [comment]
Further to this, the [W3C guidance](https://www.w3.org/WAI/WCAG21/Techniques/general/G200) does indeed suggest that the use of open-into-new-tab should be avoided where possible, but one of the exceptions they give is this:

> However there are some situations where it is preferable from an accessibility perspective to open a new window or tab:
> 1. Opening a page containing context-sensitive information, such as help instructions, or an alternate means of completing a form, such as a calendar-based date picker, will significantly disrupt a multi-step workflow, such as filling in and submitting a form, if the page is opened in the same window or tab. 

I would argue that the verification page is a situation where the use of left-click on the the edit and view buttons does "significantly disrupt a multi-step workflow", because if you navigate away from a filtered verification grid the filter settings are lost if you then go back to it.

**Comment by johnvanbreda** [comment]
Ok, fair enough - I would argue that we should add a small arrow pointing away from the link to the right of links which load into another tab - this is a convention used on some sites which helps explain what happened.

**Comment by kitenetter** [comment]
This was implemented - closing.
