### ISSUE TITLE
OS Grid References not being displayed - repeat issue

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#843]
Once again, the Map Reference field on "Asian Hornet Watch" verifcation grid appears to have reverted to displaying Lat Long only, with the OS Grid reference disappearing.

Please can we have this field reverted to showing UK OS Grid references by default (again).  As a result of the excitement of "Murder Hornets" in the US we are getting a trickle of US records sent in via the app, and having an OS grid ref displayed by default helps with spotting these.  If we do actually have an AH reported then a UK grid reference is much more user friendly to read and understand.

**Comment by MNSmith** [comment]
Apologies for "bumping", but this is causing difficulties at present.  Thanks.

**Comment by MNSmith** [comment]
Seems to be displaying grid refs for all newly arriving records now.

**Comment by kitenetter** [comment]
Looks like this one can be closed.
