### ISSUE TITLE
Verification filter admin is becoming impossibly slow

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#848]
I'm having to wait for minutes at a time every time I make a change to any of the filter settings when setting up new filters, and then attaching the user name to the filter is even slower. Is there anything that can be done about this?

**Comment by kitenetter** [comment]
Switch to ES?

**Comment by johnvanbreda** [comment]
Switched over to ES so much faster.

**Comment by kitenetter** [comment]
Thanks John, look forward to trying it out!
