### ISSUE TITLE
Territorial waters layer and Channel Islands

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#849]
Our selection of "Country territorial waters" does not include the Channel Islands:

![image](https://user-images.githubusercontent.com/16039111/82234143-ecdefe00-9928-11ea-91fc-35bb9396250d.png)

Channel Islands are included in the set of "Country" polygons, and do have a territorial waters type buffer, but when creating verification filters I can't combine "Country" polygons with "Country territorial waters" polygons. This is needed for marine verifiers.

Can we copy the Channel Islands polygons so that they are available in both "Country" polygons and "Country territorial waters" polygons?

Does that have any implications for indexing the records?

**Comment by burkmarr** [comment]
@kitenetter - I've just been looking into this. I can copy the CI country boundary to the territorial waters layer. However that would result in both the country and territorial waters boundaries for CI being defined to different standards compared to the 'countries'. 

Currently for the others we have:
- country boundary extending 3 nautical miles out to sea and
- country territorial waters overlapping the land by 0.5 mile. 

1. Do you want me to fix the current CI country boundary to conform to the same standards as the others, or would that risk upsetting current users of that boundary?

2. When I create the new territorial waters polygon, shall I remove the land (except for the 0.5 mile overlap) to keep it in line with the others?

**Comment by kitenetter** [comment]
This issue has arisen again today, and made me realise that I didn't respond to the questions from last August.

I think the best action for now is to simply copy the same boundaries from the country layer to the territorial waters layer (including all the land).

I realise that introduces an inconsistent approach, but given the small land area of the islands, and the complications of being so close to non-UK waters, the most pragmatic option is to retain the boundaries we have. We can revisit if this become an issue for our users.

**Comment by burkmarr** [comment]
Okay - that's done now @kitenetter.

**Comment by kitenetter** [comment]
Thanks - closing.
