### ISSUE TITLE
Show allocated vice-county in details pane for verification grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#85]
This (i.e. displaying iRecord's automatically calculated vice-county) is requested by David Hepper of BDS and would be useful more widely for many verifiers. In fact there is an argument for showing it on the main pages for individual records as well as in the verification grid.

**Comment by johnvanbreda** [comment]
I've added a field called Localities to the Key Facts for the next feature release. This will show the vice county of the record. Its named localities simply because the verification page is used outside the UK so we've kept it non-specific.
