### ISSUE TITLE
ES Verify quick to display but slow to Accept records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#851]
Verifier Pam Taylor in Norfolk is on slow 8/0.8 Mbit broadband and can select records using filters quickly enough but iRecord is very slow or fails when she tries to accept or reject them, even in ones and twos. This seems to be a new issue yesterday and today.
Example record IDs: 13641134 and 13641111

**Comment by johnvanbreda** [comment]
Hi @DavidHepper I'm not sure why this would be the case as not much data is transferred during the verification. However in testing I discovered and fixed a bug which made it look like the verification stuck (only on some browsers). So it would be interesting to know if this happens again?

**Comment by DavidHepper** [comment]
Thanks, John. 
"I'm happy to report that iRecord new Verify is working well this morning! Pam"
