### ISSUE TITLE
Registration process failing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#853]
We've got a number of reports in the inbox at the moment of people who've received their registration email but have been unable to successfully complete the process - one example is shown below. Can we check if there is anything going wrong here, or is ti likely to be specific to the users concerned?

> Hi - I get a message saying the account has either been activated or the link is wrong. Any thoughts? 
________________________________________
From: noreply@brc.ac.uk <noreply@brc.ac.uk>
Sent: 20 May 2020 09:48
Subject: Welcome to iRecord

Activate your account by clicking on the following link:
https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.brc.ac.uk%2Firecord%2Fuser%2Fmobile%2Factivate%2F86124%2FcaARUXOvZ7PDyoTp6d51&amp;data=02%7C01%7C%7C4e19e6e0f14c4c936a8008d7fc9a95fa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637255613193928177&amp;sdata=G0h8j51AP2B7RQyZXrXpJBGdSVBGRy1JaMDdV6LoOng%3D&amp;reserved=0

If the link fails to work please copy and paste it directly into your phone's
browser.
If you have problems registering, please contact us via email -
irecord@ceh.ac.uk

**Comment by johnvanbreda** [comment]
I've not changed anything in this area recently. I just created a new account and successfully registered and got in OK.

The link in the example email seems to have been modified by something else - the https://apc01.safelinks.protection.outlook.com bit is not generated by irecord. I wonder if that broke it?

**Comment by kitenetter** [comment]
Okay, I'll keep it under review if we get further similar messages. Closing for now.
