### ISSUE TITLE
Verification no longer available in Internet Explorer?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#854]
I've just started receiving complaints that the ES verification page is no longer displaying records if viewed using Internet Explorer. This seems to be a change that's happened in the last day or two. (Haven't checked if this also affects the ES explore pages.)

Is there anything specific that we've changed that might have caused this?

I know that IE is no longer being supported in general, but if there is any simple option that would allow the ES page to remain visible in IE that would be welcomed by some.

**Comment by kitenetter** [comment]
Apparently the change kicked in sometime last weekend.

**Comment by johnvanbreda** [comment]
Fixed - related to recent ES updated.
