### ISSUE TITLE
Wording change required for emailed queries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#858]
If a verifier queries a record and chooses to send the query as an email, rather than as a notification, the recorder receives an email similar to this:

![image](https://user-images.githubusercontent.com/16039111/83499679-a5727900-a4b5-11ea-8b62-a22b61847088.png)

If the recorder chooses to reply to the email (i.e. by clicking the normal email reply button), their reply will be sent as an email to the verifier. But the "no-reply" email address puts recorders off from trying that approach.

They are more likely to click on the link to "Reply to this query". However, we don't make it clear that by doing so their reply will become a publicly shared comment added to the record, and this has led to recorders sharing phone numbers and email addresses in a public way.

I would like us to make two changes:
At the foot of the email that is sent, replace "Reply to this query" with this text:
- Click on your email's reply button to send an email direct to the verifier
- Click on **this link** to add a comment to the record on iRecord (comments are publicly visible)

And on the window that opens up when you click on the link to add a comment (see image below), add a reminder that "Comments will be added to the record on iRecord, and are publicly visible - please do not include personal information such as addresses or phone numbers"

![image](https://user-images.githubusercontent.com/16039111/83499995-203b9400-a4b6-11ea-867e-3b2146b9259b.png)

Marking as urgent to prevent further instances of personal data being added to the comments.

**Comment by johnvanbreda** [comment]
Comment reply page has new wording and has been tidied. Still doing the email link wording.

**Comment by johnvanbreda** [comment]
Done
