### ISSUE TITLE
Some accepted records are missing Verifier Name

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#859]
I've found some records that are correctly accepted but have no verifier name and no comment. This looks like a glitch. Examples are 3099497 and 809120, accepted on 17/02/2020 almost certainly by "Cham, Steve" while working specifically on VC41. He was probably using one of the bulk-verify tools in ES Verify at the time. There may be others at other times and other VCs but I've not looked. Could these records be updated, please?

**Comment by kitenetter** [comment]
Not sure if this is significant, but both of those example IDs are from the SEWBReCord website.

**Comment by johnvanbreda** [comment]
I've fixed a block of records verified between December 19 and April 20 which had this problem - presumably a bug in the new verification tool existed at that time.
