### ISSUE TITLE
Can we change name of "admin, core" user?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#860]
We get regular enquiries wanting to know what "admin, core" means, either when it appears as a verifier name (for auto-verified records), or when it appears as having entered data (e.g. for non-logged-in users).

Ideally it might be best to use two different names, so that the verification role can be assigned to "auto-verified", and non-logged in records to "Admin, iRecord".

Assuming that is not easy to do, and we need to use just one name, I think it would be a slight improvement to use "admin, iRecord" in preference to "admin, core".

Would that cause problems for records originating from sources external to iRecord? In which case we might have to think about "admin, Indicia" (which I'm not sure is much of an improvement)?

Or can anyone think of a better solution?

Once we've agreed a name, do we just need to edit the user account in iRecord, or in the warehouse, or both?

**Comment by DavidHepper** [comment]
Please let me (and others?) know when you do rename 'admin, core' because I use this magic name in other systems to filter out unwanted records and suspect others may do the same.

**Comment by kitenetter** [comment]
I suspect that the 'admin, core' name has now been in use for so long that any change would cause as much confusion as it might resolve. Closing.
