### ISSUE TITLE
Interim download page based on Elasticsearch

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#862]
As a temporary measure whilst new download features are being perfected, implement an irecord download page as follows:
* Elasticsearch based
* Match the columns template as closely as possible to the existing download tool
* Filter builder
* Apply permissions, so verifiers, activity admins and LRCs can access their records.

**Comment by kitenetter** [comment]
Not sure if this is still needed? - @burkmarr please close if not

**Comment by johnvanbreda** [comment]
I had actually started exploring this before getting caught up with the ABLE download code - see https://www.brc.ac.uk/irecord/elastic/test-download.

**Comment by kitenetter** [comment]
Probably not needed as an interim page, will be picked up under #800. Closing.
