### ISSUE TITLE
Odd behaviour with redeterminations

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#865]
Record ID 12933466 is shown here with three previous determinations plus my latest redetermination, added this evening:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=12933466

![image](https://user-images.githubusercontent.com/16039111/83817469-c22ccd80-a6bc-11ea-9ba3-feb76799d0c9.png)

In my verification grid, several additional duplicate determinations are being displayed, and I'm 99% certain that the ones assigned to me for dates prior to today were only generated when I made a redetermination today:

![image](https://user-images.githubusercontent.com/16039111/83817621-26e82800-a6bd-11ea-8f17-05ed1b55d602.png)
![image](https://user-images.githubusercontent.com/16039111/83817646-349dad80-a6bd-11ea-8adf-2d0a7210e8fa.png)

Since the main record page is displaying correctly this may not be anything to worry about, but it is disconcerting to see the additional entries on the verification page.

**Comment by johnvanbreda** [comment]
Is this a one off or are there others?

**Comment by kitenetter** [comment]
I saw it on multiple records at the time, but have not noticed it recently.
