### ISSUE TITLE
Unexpected changes to Import > 'Survey dataset' field name

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#866]
For many years the name of the recorder in the 'DRN dragonfly imports' form has been stored in the 'Recorder Name' field in iRecord. My template import spreadsheet has a column header of this name so that the field is automatically matched. Recently the iRecord field name appears to have been changed to 'Recorders'.
- Is this a permanent change and has anything else changed? If so I'll have to reissue the template. I can't find any discussion of the renaming here.
- Does it affect anything else?

**Comment by kitenetter** [comment]
@DavidHepper I have no idea why or when this was changed, but I've now changed it back to "Recorder Name". Either way the data was still being stored in the same database attribute, it was just the label being applied to that attribute that presumably must have changed.

I will close this issue but let me know if any problems remain.
