### ISSUE TITLE
App map references inconsistent between Sample and Occurrence

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#867]
A new recorder has used the iOS App to record several species of dragonflies at UEA in Norfolk but didn't enter his sightings until he had travelled home to Northumberland. The geolocation has gone wrong, though he says he used the map when entering them to override the default GPS entry. Is this user error or a fault in the App?

Example:
- Record IDs: 14006581 .. 7
- Survey: iRecord App General Survey
- Parent sample > Gridref_calculated: TG19690703    [this is correct]
- Sample > Gridref_calculated: NZ2084    [this is incorrect - Northumberland]
- Location source: gps   [this is incorrect if he adjusted the map]

I have asked those concerned not to make corrections until after diagnosis!

**Comment by kitenetter** [comment]
Copying in @kazlauskis - let me know if you need any further info Karolis, or if we should transfer this issue to the app repository.

**Comment by kazlauskis** [comment]
Yes, this should be moved to the app repo. In the iRecord App for the General Survey we haven't developed the functionality to automatically update all child samples when manually changing the parent sample location. This has been done to the Plant Survey which is in the app though so we could follow the same approach here as well.

**Comment by kitenetter** [comment]
Transferred to [app issues list](https://github.com/NERC-CEH/irecord-app/issues/196). Closing.
