### ISSUE TITLE
ES verification: redet using custom species dictionaries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#868]
This may relate to the (not yet raised) issue of how to deal with redets for NatureSpot. I need to redet some PoMS FIT Count occurrences, and on the ES page I can't access the PoMS list of taxa. On the old verification page I can do this:

![image](https://user-images.githubusercontent.com/16039111/84180817-0be03400-aa80-11ea-986a-2ea0a10f51db.png)

Do we need to resintate a similar interface on the ES page or is a new approach needed?

**Comment by kitenetter** [comment]
I think that for NatureSpot at least we don't really want the choice of dictionary to be over-ridden.

**Comment by kitenetter** [comment]
Adding this to the October milestone for consideration then. We do need to enable redets to the species list that is appropriate for the source of the record.

**Comment by johnvanbreda** [comment]
I've added taxon list ID and title to the index and started a refresh of the taxonomy data to populate it into Elasticsearch. Once that is done I'll need to do the sensitive taxa, then we can improve the functionality on the redetermination tool using the new info.

**Comment by johnvanbreda** [comment]
Done
