### ISSUE TITLE
Odd behaviour for some app records, and how to delete them

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#870]
Not sure if this is an Indicia issue or an app issue, or a bit of both.

I've been contacted by a recorder who added four records but was not logged in. They want me to delete the four records so that they can add them under their own account.

It appears that the four records were added via the app - at any rate they are all within the "iRecord App" survey dataset.

**Question 1**
I didn't think it was possible to upload records from the app if you weren't logged in, so how did these records get in to the system? They are shown as having been created by Admin.

**Question 2**
I now need to delete the records, but when I try to do so via the warehouse, I get the message "The record could not be saved", and two empty but apparently mandatory attributes are highlighted: "Identified By" and "Stage". If these are mandatory, how did the record get saved without them? And how do I delete them do I need to add dummy values to those two attributes?

The four record IDs in question are:
14194522
14194512
14194509
14194480

Marking as urgent because I would prefer to delete these records before they are processed by the verifiers.

**Comment by BirenRathod** [comment]
@kitenetter

If it is urgent, please fill those values and saved those records. After saving, delete those records. If user don't want those records, it is not going to harm anybody by deleting those records.

**Comment by kitenetter** [comment]
Okay, will do

**Comment by kitenetter** [comment]
The four records are now deleted, which removes the urgency.

The user says they added them "online" and not via the app - I'm trying to find out which form they used.

**Comment by kitenetter** [comment]
Apparently they used the casual records form on iRecord (without logging in). If that is the case, I don't understand how the records ended up in the "iRecord App" survey, nor do I understand why in at least one of these records the number range has been used for abundance (see screenshot below).

So maybe there is some confusion over what the user actually did, but I can't see an explanation for this. I'm hoping that it is a one-off oddity so will close for now.

![image](https://user-images.githubusercontent.com/16039111/84647861-f2197380-aefb-11ea-816c-cad24be20e0b.png)
