### ISSUE TITLE
Formatting of recorder name in the app

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#871]
When adding records using one or the app's survey functions, the recorder name is pre-populated with the user's name in this format:
Martin C. Harvey

On the iRecord website, recorder names are populated with:
Harvey, Martin C.

This makes our data unnecessarily messy.

Personally I would prefer to adjust the website so that it uses the app's format, but if that is deemed undesirable then we should adjust the app. Of course there are substantially more existing records that use the website format than there are using the app format, so perhaps we ought to adjust the app (in which case I'll move this issue into the app repository).

Does anyone else have a preference @DavidRoy @kazlauskis ?

**Comment by DavidRoy** [comment]
@sacrevert do you have a view on recorder name convention?

**Comment by sacrevert** [comment]
Not really. Presumably either format is permissable for DDb data exchange given that it doesn't seem to have been an issue to date (both records from the app and the website seem to display fine in the DDb).

**Comment by sacrevert** [comment]
I suppose there are things in favour of `Harvey, Martin C. in that less sophisticated users can easily sort by surname in Excel, and you could separate our surname and firstname in the same software using the split to columns function.

**Comment by DavidRoy** [comment]
Yes, that was the original rationale for BRC adopting the surname, forename convention.  Interesting to hear the use-cases for persisting with this.  What is the default format for the DDB?

**Comment by sacrevert** [comment]
I don't think it has a default. Different record views display differently, suggesting that it knows how to parse name components and can generally reconsitute them however. Not always perfect obviously, but seems to have worked perfectly well with all the iRecord data that I have looked at from different surveys, including the app.

**Comment by DavidRoy** [comment]
That's good to know.  The critical thing for iRecord is being consistent between the app and website.  I think we should stick with the 'Surname, Forename' convention unless someone gives me a strong argument not to

**Comment by kitenetter** [comment]
My main argument for "Forename Surname" is that it is (arguably) more user-friendly and easier to read. But that's probably not a very strong argument, and I agree that sorting by surname has its benefits.

I think most of the moth recording community uses "Forename Surname" in the MapMate context, but BSBI always recommended "Surname, Forename" in their MapMate guidance.

Regardless of guidance users will enter all sorts of permutations, so we'll always have some messiness, but it would be good to have the app following the website guidance. So I'll raise this as an app issue to change to "Surname, Forename".

Closing this issue.
