### ISSUE TITLE
Question - URL change for verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#874]
We discussed this recently, but I just want to check before proceeding, in advance of work on the new verification guidance.

Currently the 'old' verification page is at:
- https://www.brc.ac.uk/irecord/verification

and the current ('new') page is at:
- https://www.brc.ac.uk/irecord/elastic/verification

I'm proposing to change the old page to:
- https://www.brc.ac.uk/irecord/verification-v1

And then to apply the original URL to the new page:
- https://www.brc.ac.uk/irecord/verification

Can anyone foresee any problems if I make that change?

@johnvanbreda @burkmarr @BirenRathod @sacrevert @DavidRoy

**Comment by BirenRathod** [comment]
@kitenetter 
Sounds like a good plan and do not forget to put old verification page link on new page if somebody find any problem.

**Comment by kitenetter** [comment]
I meant to add that part of the reason for making this change is so that our "you have new records to verify" email notifications link to the new page rather than the old.

**Comment by sacrevert** [comment]
To my mind having a "version 1" URL and another unlabelled one is confusing. Version 1 doesn't clearly indicate whether older or newer than unlabelled. Wouldn't "old" or "legacy" be clearer?

**Comment by kitenetter** [comment]
Happy to go with "old" - I suppose I was thinking that we might one day have a third version and might need to track them, but I sincerely hope we won't need to move to another version any time soon! I'll go with:
- https://www.brc.ac.uk/irecord/verification-old

which matches what we've called it in the menu heading. (This page will be removed at some point in any case.)

**Comment by johnvanbreda** [comment]
Makes sense to me. The only possible issue is if people kept direct links to the new page, but I suspect this is very unlikely as it's easily accessible via the menu.

**Comment by kitenetter** [comment]
URLs updated. Closing.

**Comment by kitenetter** [comment]
Adding a reminder from @BirenRathod that when making changes such as this we need to ensure that redundant URLs get redirected (which Biren has done for this one).

**Comment by BirenRathod** [comment]
Thanks @kitenetter
