### ISSUE TITLE
ES verification page: make column head sorting easier to click on

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#877]
Some verifiers have requested that we make it easier to sort the columns in the grid. Currently this is done by clicking on up or down arrows next to the column heading text, but these arrows are small, and difficult to see and click on.

Can we set it so that clicking on the heading text sorts the column (and thus do away with the need for the arrows), or if not make the arrows larger?

**Comment by johnvanbreda** [comment]
Clicking the heading sounds fine - perhaps a nice small update for @burkmarr?

**Comment by burkmarr** [comment]
Created pull request: https://github.com/Indicia-Team/media/pull/27

**Comment by burkmarr** [comment]
@kitenetter - can this be closed?

**Comment by kitenetter** [comment]
@burkmarr I hadn't realised this had been fixed! Clicking the columnhead titles does now enable sorting, but I think the reason I hadn't realised is because it is not very obvious - it still looks like you need to click on the arrows.

Is there a simple way of changing the behaviour of the column heads so that they get highlighted in some way when the mouse is over them, or so that an underline appears to indicate that they are clickable?

If there's no simple solution then I suggest we close this issue.

**Comment by johnvanbreda** [comment]
We could do that I'm sure, but I've just had a look at a few off-the-shelf data grid components (e.g. https://examples.bootstrap-table.com/) and mostly they seem to behave just like ours currently does, without changing the format to indicate grid column titles are clickable. Some examples have larger sort icons but we are often a bit tight on space so this may not be an option.

**Comment by kitenetter** [comment]
Okay, I may be worrying unnecessarily anyway. Once you realise how it works it quickly becomes intuitive. Let's close this one.

**Comment by DavidHepper** [comment]
I think the issue is that the pointer doesn't change when hovering over the text of the column header, even though it is clickable and works well. Only when hovering over the up/down triangle icons does anything change, so I've always thought I had to click the tiny triangles. 
Is it possible to have a mouseover action for the column header that changes the pointer to a hand, for example?
