### ISSUE TITLE
ES verification page: disable full-screen for grid?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#878]
The option to view the grid in full-screen mode is currently not very useable, because (unless I am missing something) in full screen it is not possible to verify the records (and of course the map and record details are not visible). I can imagine a full-screen display in which clicking on a single record would cause a details + verification pop-up to open, but as it stands this full-screen option feels unnecessary.

I would suggest we remove this option, and thus remove the button that gives access to it?

**Comment by johnvanbreda** [comment]
This has now been deployed.

**Comment by kitenetter** [comment]
@johnvanbreda I've now had a couple of requests from verifiers to reinstate the full-screen option. I'm still not sure what practical benefit it provides, but if it is easy to switch it back on again please can we do so!

**Comment by johnvanbreda** [comment]
Done
