### ISSUE TITLE
Review csv import process

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#879]
This is an initial placeholder to gather together the outstanding issues around the csv importer.

To add: there are a number of issues already in github that need to be included.

New issue today: if a csv file has column headings that iRecord thinks it understands, it skips over the field mapping page. This is unhelpful, e.g. a user was importing using TVKs, but had the TVKs in a column headed "Species". Because iRecord thought it understood all the column names it imported in one go without offering and mapping, and the import then fails because the Species column did not in fact contain species names.

**Comment by johnvanbreda** [comment]
The behaviour where it skips the mappings page if all mappings are done is an option which can be turned off. It was deliberately requested though at one point!

**Comment by kitenetter** [comment]
See also points raised in #16 (now closed).

**Comment by kitenetter** [comment]
Now being considered under #999
