### ISSUE TITLE
Add activity name to source column for app

### ISSUE THREAD

**Issue by charlesroper** [BiologicalRecordsCentre/iRecord#88]
When adding records associated with an activity and using the app, the source column should display "**iRecord | App | _Activity Name_**". Currently, it only displays "**iRecord | App**".

/cc @kazlauskis

**Comment by johnvanbreda** [comment]
I don't think this is an app specific thing - the source column doesn't show the activity name for any records entered via the web interface either.

**Comment by DavidRoy** [comment]
In principle this is a good idea but given that activities can have long names, i have concerns about the length of the text string - being unwieldy in 'Explore' reports for example.  For the iRecord - explore reports, perhaps we should adopt the coding (+ hover-over) approach that is used for the verification grid?  I suspect the general user is not that interested in sources of records

**Comment by charlesroper** [comment]
I'd say it's more helpful to activity administrators (and participants) where the records come from a number of sources. Having the data in the grid means we can filter and sort. Point taken about the length. Could we truncate if over a given limit? Or use an activity code?

Example screenshot of FSC Cuckoos activity: ![2016-09-06_10h25_27](https://cloud.githubusercontent.com/assets/176/18269949/755f8c84-7422-11e6-9fca-e472f8ed8a41.png)

**Comment by DavidRoy** [comment]
Having the information coded in the grid would allow filtering (via filter setup) and sorting but perhaps not so easily.  Truncation might be difficult to automate and ensure that source text is unique.  Here is how the codes are implemented in the verification grid, and what I propose should be replicated in other explore reports:
![image](https://cloud.githubusercontent.com/assets/2699478/18270165/8543b296-7423-11e6-929a-526e7fdc34c3.png)

**Comment by charlesroper** [comment]
Ah, I've not looked at verification for a while and didn't realise it did that. That looks like a good compromise to me (with the hover tooltip).

**Comment by DavidRoy** [comment]
Great.  Is that ok for you John?

**Comment by JimBacon** [comment]
A possible alternative that crossed my mind is whether you might use the responsive tables capability to include extra information for which there is not sufficient screen width to display.
![capture](https://cloud.githubusercontent.com/assets/2545390/18271866/7456d298-742c-11e6-8a97-c3eda995cf08.jpg)

**Comment by kazlauskis** [comment]
As an idea for long table cell entries you can easily trim the text with a bit of CSS:
```css
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

You can see that in blue here (I have placed it on a new line though):
![screen shot 2016-09-07 at 09 35 30](https://cloud.githubusercontent.com/assets/7383162/18305253/9683c3dc-74de-11e6-966c-437141d8a789.png)

**Comment by johnvanbreda** [comment]
Hi @kazlauskis, thanks for the idea. I'm not sure how this works in terns of interaction with the way the browser resizes the cells though. If I try it on my own laptop in both Chrome and Safari, then when I resize the window to the point where the data will no longer fit in the cells, the browser prefers to allow the table to overflow its container rather than shrink the cell causing an overlap. This even occurs when the table is max-width 100%.

**Comment by kazlauskis** [comment]
![screen shot 2016-09-07 at 11 33 28](https://cloud.githubusercontent.com/assets/7383162/18309865/5fed77a4-74f3-11e6-9ce2-4e39ed153ad6.png)

Like that? I am not sure how the percent works in this case, but you can use specific width with **td**'s
```css
td {
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
max-width: 50px;
}
```
![screen shot 2016-09-07 at 12 03 28](https://cloud.githubusercontent.com/assets/7383162/18309926/b7a16866-74f3-11e6-9e35-9ef63587601b.png)

**Comment by johnvanbreda** [comment]
Yes, I've now realised that max-width works, though there are still 2 problems:

- The ellipsis really needs a tooltip if you hover over it. There are scripts around that can fix this, e.g. http://stackoverflow.com/questions/5474871/html-how-can-i-show-tooltip-only-when-ellipsis-is-activated.
- We want to allow flow onto 2 lines, but ideally not more. If I put nowrap on td, then examples like the iRecord | general records source values above which currently display nicely on 2 lines now use ellipsis unnecessarily. There are solutions to this discussed at https://css-tricks.com/line-clampin/.

**Comment by kitenetter** [comment]
Activity names now included in downloads and are coded on the verify page. Closing.
