### ISSUE TITLE
VC37 records not being assigned to verifier?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#880]
A batch of direct-entered records that are unambiguously in VC37 (Worcestershire) are not appearing when filtered, either to me or to the verifier. They have been through the automated checks but something has gone awry with the assignment to a VC and possibly also to LRC, which is '-'.
e.g. IDs 14394923 to 14395152

**Comment by Mike-Averill** [comment]
This issue has occurred again with 11 Odonata records submitted by 'Warr, Andy' for the 08/07/2020

**Comment by Mike-Averill** [comment]
This issue has occurred again with 10 Odonata records submitted by 'Warr, Andy' for the 20/07/2020

**Comment by kitenetter** [comment]
Have checked one occurrence (id = 15253062) and in the cache_occurrences table the location_ids attribute is null. @johnvanbreda  does this mean the indexing is failing in some cases?

**Comment by johnvanbreda** [comment]
As a temporary fix I've requeued any records from the last 2 months that don't have location IDs filled in for indexing. Still need to find the underlying reason though.

**Comment by kitenetter** [comment]
Have not had further reports of this behaviour, so will close for now.
