### ISSUE TITLE
Exporting email addresses from Indicia

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#881]
I need to provide a list of email addresses to the Bloomin Algae project, for all recorders who have contributed a record via the Bloomin Algae app (the terms for that app allow for this to happen).

When I do a similar job for PoMS, I use attr_email in the cache_samples_nonfunctional table. However, in the Bloomin Alage dataset attr_email is not populated.

Recorder emails are shown to Bloomin Algae verifiers in the Record Details pane within the iRecord verification page, but I'm not sure where that information comes from, nor how attr_email is normally populated.

What do I need to do to get the current email address for the Bloomin Algae recorders?

I know that we store email addresses in table people and table users_identifiers, but I'm not sure what the best option is to ensure that that I extract the current email address for the user.

**Comment by kazlauskis** [comment]
The app uses standard Indicia API mechanism to upload the records to the indicia warehouse. Each records gets an indicia user id attached to it. I think @johnvanbreda is the best person to answer how to get the right information back from the database.

**Comment by kitenetter** [comment]
Following advice from @DavidRoy (thanks!) I've used the following query:

```
SELECT s.title, p.first_name, p.surname, p.email_address, Count(o.id) AS records
FROM cache_occurrences_functional o 
JOIN surveys s ON o.survey_id = s.id
JOIN users u ON o.created_by_id = u.id
JOIN people p ON u.person_id = p.id
WHERE o.survey_id = 445
GROUP BY s.title, p.first_name, p.surname, p.email_address
ORDER BY p.surname;
```

This seems to work, so unless there is any danger that I'm picking up non-current email addresses from the people table I will go ahead and use this.

Would be interested to know why attr_email is not being populated in the cache_samples_nonfunctional table but that is not an urgent request.

**Comment by kitenetter** [comment]
Just checked and attr_email is also not populated in the cache_samples_nonfunctional table for the main iRecord app, so this seems to be a general behaviour for app records.

I'm not aware of this causing any other problems, it just seems inconsistent.

**Comment by johnvanbreda** [comment]
Attr_email is only populated in our iRecord general surveys because they have a specific custom attribute to capture the email address. This is in part a legacy from the very early days when we didn't link user accounts to the warehouse, but also because the forms allow anonymous users to post records and we ask them for their email address. Since the attribute is required for anonymous records, it gets filled in automatically by the code even for logged in users.

**Comment by kitenetter** [comment]
Thanks for the explanation @johnvanbreda that makes sense. Closing.
