### ISSUE TITLE
Unable to edit species name for lists of records within "Urban Flora of Scotland" Activity

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#883]
A user linked to the "Urban Flora of Scotland" Activity wishes to edit some records. They are able to get to the edit page via the Activity's "Explore activity data" button, but when they arrive at the edit form the species name only gives the option to delete it, not to edit it:

![image](https://user-images.githubusercontent.com/16039111/86368583-40a56c80-bc75-11ea-846e-cd66c6de9d5f.png)

The above page is at:
https://www.brc.ac.uk/irecord/enter-bss-urban_flora?occurrence_id=13388287&group_id=150

I recall that we have had issues before with edit buttons being lost from list forms but I can't recall what the solution was.

**Comment by johnvanbreda** [comment]
I've fix this - Edit tab, User Interface, tick the option "Include option to edit entered taxa".
