### ISSUE TITLE
Redetermined records disappearing from Verify

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#885]
There appears to be a problem with ES Verify after pending records are redetermined or the redetermination fails. Pat Batty says she redetermined a block of _Sympetrum nigrescens_ records from Heather Watkin to _S. striolatum_ recently but they have not been changed and have vanished from her ES Verify queue, though they are still visible in both Explore and Verify-old, where they are still pending and can be found by filtering on map ref = NR7385. They include the following record ID examples:
14731963
14731964
14731973
14731975
14731988
14731989
14731990
A problem with the ES indexer?

**Comment by johnvanbreda** [comment]
Almost certainly caused by delays in the indexer due to the UKSI update combining with UKBMS uploads.

**Comment by DavidHepper** [comment]
Sorry @johnvanbreda but we're not quite there yet. Pat Batty reports that she tried to redet. record 16895466 from Brown Hawker to Common Darter but the record disappeared. I can confirm that the record is still visible via **Explore all records** and **Verify - old** at https://www.brc.ac.uk/irecord/record-details?occurrence_id=16895466 but it cannot be found in **Verify** by any means. Clearly the redet. didn't stick (still Brown Hawker) but either the record is in a funny state or the indexer has glitched again.

**Comment by DavidHepper** [comment]
It is tempting to think that Pat's most recent issue may be related to the problem with _Sympetrum striolatum_ losing its common name **Common Hawker** but the redet. was made around 25/08 whereas the missing name was reinstated earlier, on 19/08.
