### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#887]
Time to update PHP 7.4, so warehouse and iRecord code needed compatibility of this version of PHP. 
As this https://www.drupal.org/docs/7/system-requirements/php-requirements link suggests Drupal 7 is already supported 7.4.

**Comment by DavidRoy** [comment]
@BirenRathod can we close this issue?

**Comment by BirenRathod** [comment]
@johnvanbreda & @DavidRoy Not needed, I have closed it.
