### ISSUE TITLE
Moth input form - should we switch to UKSI for species lists?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#888]
Currently the moth form - https://www.brc.ac.uk/irecord/enter-moth-sightings

uses it own moth list.  This can get out of date and adds work to maintain.
https://www.brc.ac.uk/irecord/comment/5563#comment-5563

Can we switch form to UKSI moth list once the latest UKSI update is completed

**Comment by kitenetter** [comment]
As far as I can tell the moth recording form already uses the UKSI list.

I think the problem with the import as described in the forum post is that the user has tried to import records into the "iRecord Moths" survey (which is probably fine to do) but has also chosen the "iRecord Moths" species list (which is problematic and is an option I would prefer we didn't make available to users). I will suggest that he uses the UK Master list instead.

This highlights the need to improve the user-friendliness of the import process (#879). Ideally we ought also to have way of reviewing which taxon lists are still in use and which could be retired, or replaced with a filered UKSI list. Not sure how to go about doing that.

@DavidRoy if you're happy that this addresses the issue please close this one.

**Comment by DavidRoy** [comment]
Thanks for clarifying.  Can you reply to forum post with suggested action on this.  Closing this issue.
https://www.brc.ac.uk/irecord/comment/5563#comment-5563
