### ISSUE TITLE
ES verification: unhelpful query behaviour for non-logged in users

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#894]
If a verifier queries a record that has been entered by a user who was not logged in, the window that opens up tries to persuade the verifier to add a comment rather than sending an email:

![image](https://user-images.githubusercontent.com/16039111/89055100-c76f6700-d351-11ea-93e2-0b2f82bb4961.png)

![image](https://user-images.githubusercontent.com/16039111/89055173-e4a43580-d351-11ea-8376-78d7439b51fb.png)

This is very unhelpful, because the recorder is highly unlikely to ever see the comment, and it is definitely better to send an email for non-logged-in users.

Can we change the behaviour for non-logged-in users so that (ideally) the query button offers the email option only, or if that is not possible so that the email option becomes the recommended one.

And can we also correct the text of the email message so that it says "recorde**r**" rather than "recorde**d**" in "this recorded does check notifications"

Relates to #817

**Comment by johnvanbreda** [comment]
Fixed.
