### ISSUE TITLE
Add feedback form to iRecord website

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#895]
Proposal is to add a feedback form to the iRecord website, that will allow users to contact us (without directly exposing the iRecord email address) and to categorise their feedback (bug reports, feature requests etc.). The form should forward such feedback to the iRecord inbox.

Is there a Drupal module that would enable this? If so let me know what we need to do to set it up.

**Comment by johnvanbreda** [comment]
The standard Drupal contact form will do this but is not easily customised in Drupal 7 (better in Drupal 8)! We could use the webform module to create custom forms in Drupal 7, which I think @BirenRathod has some experience of.

**Comment by kitenetter** [comment]
Not an immediate priority, review when we move to Drupal 8. Closing for now.
