### ISSUE TITLE
Question: use of multiple system function attributes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#896]
On the glow-worm survey form:
https://www.brc.ac.uk/irecord/glow-worm

there are three custom attributes to allow the recording of numbers of males, females and larvae as part of a single occurrence. All three sex/stage terms are flagged as system function = "Count or abundance of a sex or life stage". My understanding from @johnvanbreda is that where there are multiple system functions in place, one will be chosen at random as the one to be used.

Verifiers for the glow-worm records find it annoying that, in the record details pane, they can only see one of the three sex/stage terms, and have to click through to the full record page to see all of them.

If I was to remove the system function from all three sex/stage terms, one downside would be that the standard reports would no longer display an abundance for these records.

However, if I do remove the system function, would that result in all three stages being displayed as custom attributes in the record details pane?

**Comment by DavidHepper** [comment]
BDS forms have even more named life stage counts per record. The standard reports don't work for us but it's a trade-off that we're happy with. (I recommend NBN Atlas for reporting.) You could look at the design of our forms to see whether they shed light on those of the glow-worms.

**Comment by kitenetter** [comment]
I have removed the system function settings from the three glow-worm custom sex/stage attributes, and now all attributes are being displayed in the records detail pane.

@BirenRathod asked if there were any implications for the glow-worm app, and I don't think there are. The app uses the same three sex/stage attributes (IDs 509, 510, 511), and the system function is a global setting that (as far as I'm aware) only has an effect on how the data is displayed. So there should be no change in how these attributes are used in the app.

Closing.

**Comment by BirenRathod** [comment]
Thanks, @kitenetter. So far no changes needed, which is good.

**Comment by johnvanbreda** [comment]
@kitenetter A point for future consideration, maybe if there are duplicates, then a text representation of the different values could be shown as the abundance value. E.g. adults=2, juv=3. This would involve changing the code which constructs our reporting caches.
