### ISSUE TITLE
Records not appearing in ES

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#897]
Several verifiers have contacted us to say that new records are not appearing in the ES verification page. Is this just a delay in them getting indexed and cached, or is there an underlying problem?

I suspect it is a delay (some of my own records for verification seem to be taking a day or so to appear) - if so, is it possible to prioritise the appearance of records for verification above any of the other tasks being processed?

**Comment by kitenetter** [comment]
From @johnvanbreda via email: "The system is catching up after yesterdays’ UKSI update. It has a few million records to change the taxonomy details for."

Closing.

**Comment by kitenetter** [comment]
@johnvanbreda we've had further complaints from verifiers today that records are not appearing in the ES verification page. I assume that this is still due to catch-ups from UKSI updating (and have let the verifiers know that), but let me know if there's anything else we need to investigate.

**Comment by DavidRoy** [comment]
Is the ongoing loading of UKBMS historic data causing the lag?  We could either slow down on UKBMS loading or make verification work-queue items higher priority?

**Comment by johnvanbreda** [comment]
Yes, the system can cope with the UKBMS loading, but it takes about half of the "bandwidth" for loading to ES, so has doubled the expected time. I'm looking at ways of improving the ES load performance though as it would be nice to have some spare capacity in this respect.

I don't have an easy mechanism for prioritising verification data though - it's not the work queue, but the extraction of updated records into ES that is the issue here.

**Comment by kitenetter** [comment]
Is it possible to estimate when the UKBMS load will subside? There have been more verifier emails this afternoon querying what is going on, and it would be good to be able to give people an idea of when things might get back back to normal (if such a state exists!).

We have a number of admirably enthusiastic verifiers who are unhappy that people are having to wait for their records to be verified, and consequently are going back to the old verification page to deal with them there (which does mean that we have a workaround of course).

**Comment by DavidRoy** [comment]
@johnvanbreda is it the UKBMS loading that causes the hold-up or the resulting work-queue jobs?

I can spread the ukbms data loading out to reduce the impact

**Comment by johnvanbreda** [comment]
It's not the work queue specifically. It's simply the transfer of the latest copies of any of the cached records from the warehouse to Elasticsearch. I'm looking at the performance at the moment to see if I can optimise it. Holding off on further UKBMS uploads for about 1 day would help though I think.
