### ISSUE TITLE
Ensure that a redetermination always results in a determiner name being stored

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#899]
At the moment, when a verifier redetermines a record, there are two different outcomes:
1. If the occurrence originally had a populated determiner attribute, the verifier's name is given as the determiner for the newly added determination
2. If the occurrence did not originally have a populated determiner attribute, the new determination is added but no determiner name is given

It would be preferable for all redeterminations to be stored with a determiner name stored, i.e. the name of the verifier who has made the redetermination.

(Previously raised under #696)

**Comment by johnvanbreda** [comment]
The problem here was that the attr_det* fields in the reporting cache tables were only being filled in if there was a custom attribute value stored for the det name. If the determination was updated by a verifier for a record without this attribute value the occurrence.determiner_id field is updated but was not being stored in the cache data. This has now been fixed so the cache data table stores the name pointed to by occurrence.determiner_id.

**Comment by kitenetter** [comment]
This does not seem to be working consistently. For example, this record was redetermined by Nick Bowles on 18 Feb but does not have a determiner attribute:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=17793292

That is a record from the iRecord app - are we able to add determiners to app records? I thought this was possible, but I could be wrong.

**Comment by kitenetter** [comment]
Came across another example of the determiner name not being filled in following a redetermination:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=21023459

**Comment by kitenetter** [comment]
Record ID 23176299 was redetermined today (on the D9 site) and no determiner name has been stored.

**Comment by kitenetter** [comment]
Record ID 23176299 was redetermined today (on the D9 site) and no determiner name has been stored.

**Comment by kitenetter** [comment]
This is very apparent in the rederminations being applied to the iNaturalist dataset. Most redetermined occurrences are lacking a dterminer for the redetermination, but it does get added in some cases. I don't understand the inconsistency, and in any case we want a determiner name to be added for every redetermination. Examples:
- https://irecord.org.uk/record-details?occurrence_id=22833719 (no determiner shown)
- https://irecord.org.uk/record-details?occurrence_id=22835919 (determiner is shown)

**Comment by kitenetter** [comment]
Came across another example today, redetermined but no determiner shown:
https://irecord.org.uk/record-details?occurrence_id=27291977

**Comment by kitenetter** [comment]
This has been raised again recently by several verifiers.

**Comment by kitenetter** [comment]
Ideally we do want to be able to store an "Identified by" value for any record, in order to properly capture the source of a redetermination. The attribute is not mandatory, and we work on the assumption that the recorder is the identifier unless explicitly stated otherwise.

So I would support making the "Identified by" attribute available to as many surveys as possible, although it makes sense to prioritise the ones that provide the greater bulk of the records. Dealing with iNat and the iRecord app would be a good start to this.

**Comment by cubitmg** [comment]
Recent redeterminations have been setting the Determiner field correctly to my name for my moth redeterminations at least. :-)

**Comment by johnvanbreda** [comment]
I've added the Identified By attribute to the iNat dataset. It was already present for the iRecord app so I may have missed it.

**Comment by kitenetter** [comment]
@johnvanbreda if this now fixed for iNat and iRecord app I suggest we close for now (can reopen if the issue arises for other data sources)

**Comment by kitenetter** [comment]
Still seeing some inconsistency. This record was added via the standard iRecord website forms, and I have redetermined it, but no value is shown for "Identified by":
https://irecord.org.uk/record-details?occurrence_id=31281218

**Comment by johnvanbreda** [comment]
I think this occurred if the identified by was missing in the first place. Now sorted in the develop branch and will be deployed soon.
