### ISSUE TITLE
Organisation hierarchies - should be possible to administer an entire branch

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#90]
If you are the creator or administrator of an organisation (http://www.brc.ac.uk/irecord/organisations/list) then it should be possible to automatically administer any centres or activities contained within.

Suggested by Charles Roper, FSC.

**Comment by johnvanbreda** [comment]
So far I've coded the change to allow editing of a group if you are admin of a parent group (a new option in the group edit form config). Still need to update the groups list report to provide option to treat you as admin when admin of a group parent - otherwise the links to edit the group will not appear (even if the links would actually work).

**Comment by charlesroper** [comment]
@johnvanbreda Just checking something with this: so does that mean if I add someone as an administrator of the Field Studies Council group (i.e. at the organisation level) they will be an admin of all the sub-groups?

**Comment by johnvanbreda** [comment]
Yes, that's right @charlesroper. In fact I should have closed this as the report does now give you the links to the relevant admin pages in the subgroups.
