### ISSUE TITLE
Batch updates from UKSI

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#901]
Investigate options for tracking changes to UKSI and importing these in small batches, as an alternative to manual updates plus periodic full replacement.

Initial action is for @johnvanbreda and @burkmarr to meet with Chris Raper.

**Comment by burkmarr** [comment]
A meeting is scheduled for 3rd Sept.

**Comment by kitenetter** [comment]
@johnvanbreda to review files from Chris and develop process

**Comment by kitenetter** [comment]
Progress when possible but full updates still needed

**Comment by kitenetter** [comment]
@johnvanbreda there are one or two new species that people are requesting we make available in iRecord. Is it still okay for me to add these manually via the warehouse (using the TVK and other details that Chris has supplied), or will that mess up the batch update process once we're able to implement that?

**Comment by johnvanbreda** [comment]
@kitenetter it might be better to ask Chris for the update log spreadsheet and we can start trying that approach. The point of the last update a few weeks back was so that we could start using the update log from now on.

**Comment by ChrisRaper** [comment]
Hi everyone, yes I can send over a sheet of the Update History. I haven't really gone into the detail of how John's code protects itself but I'd like to hold back a block of beetle updates and send in stuff before and after it, if that's possible?

**Comment by ChrisRaper** [comment]
It's an interesting question - I'd have to check as I've never amended an autonumbering field. I'd also have to think about how it would affect the sequence but I see what you mean about keeping the order in which the rows were processed to prevent paradoxes.

**Comment by ChrisRaper** [comment]
@johnvanbreda - have been thinking about this and I think reallocating the ID will potentially be as risky as just skipping blocks of the rows. As least with the numbers in their original sequence, if a paradox is revealed later, then we'd be able to track back the original order that the rows had been created, If we reallocate them then we lose that sequence and we might still have created a paradox.

**Comment by johnvanbreda** [comment]
OK -  looking at the way the code works I think this is fine, you can just remove a set of rows from the operations spreadsheet and we can then upload and process them later.

**Comment by kitenetter** [comment]
The number of species added since the last full UKSI update is increasing, and some schemes are requesting that we make these names available in iRecord.

@ChrisRaper did you send an Update History spreadsheet, and if not are you in a position to do so now?

**Comment by ChrisRaper** [comment]
Hi Martin - I can certainly send one but I am a bit lost as to where we are with this, it's been such a long time and I have been working on other things. The last issue I remember was between John & Mike and they discussed implementing some changes to the way that Mike handles updates, to make it easier for John to bring them into iRecord. I'm led to believe that Mike has done these and they were imported to the UKSI a few months ago(?) but I'm not sure now if John would like to have a major update and then get me to send a UKSI History file from that point OR if he wants to try a copy of the UKSI_History table from an earlier point. We need to discuss this so we're all on the same page because I thought data prior to Mike's changes might cause John problems and if this is true then we need to get the iRecord DB up to a stable point after Mike's updates before we continue testing.

**Comment by kitenetter** [comment]
Thanks Chris.

@johnvanbreda please can you advise on how best to progress this - let me know if we need to set up a zoom meeting.

**Comment by johnvanbreda** [comment]
Hi both - yes, this is on my radar, but I've had a flurry of other urgent bits of work. I'll try and refresh myself on where we'd got to and will get back to you.

**Comment by kitenetter** [comment]
I'm about to add some new names via the warehouse, as there are several that we are being asked to make available. Hope that doesn't cause problems but let me know if it does. I guess we may need to do another full update in the new year.

**Comment by johnvanbreda** [comment]
@kitenetter I am due to get the new process working but have been caught up with other priorities as you know. I'd prefer to do that than another full update though.

**Comment by kitenetter** [comment]
Additional work done by John in December 2022 to progress this, and we are close to being able to do another full update followed by (monthly?) incremental updates. Closing this issue, and will add a new one to plan the next full update.
