### ISSUE TITLE
Menu at foot of web pages

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#902]
For consistency, in the menu links that appear at the foot of the iRecord pages, we should change from:
"Terms & Conditions"

to:
"Terms of use"

@BirenRathod please can you make this edit, or let me know where I need to go to edit the menu links myself.

**Comment by BirenRathod** [comment]
@kitenetter Amended the text.

**Comment by kitenetter** [comment]
Thanks - closing.
