### ISSUE TITLE
Question - linking external forms to iRecord accounts

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#903]
Please can I check what options we have, if any, for allowing users to link to their existing iRecord accounts when using the following forms.

**1 - BWARS species surveys**
There are a number of single-species forms embedded in the BWARS website, for example:
https://www.bwars.com/content/submit-sighting-colletes-hederae-ivy-bee

These ask for a recorder name and require an email. My understanding is that a recorder who uses one of these forms will be treated as not being logged in to iRecord, even if they have an account that uses the same email address. And that therefore records added via this route will not appear in the recorder's "My records" view.

Is my understanding correct? Is there any option that would allow records entered on the BWARS forms to be linked to iRecord accounts? If not, would an alternative be to host the same forms within iRecord and just provide a link to those forms on the BWARS site?

**2 - BCT Sunset/Sunrise survey**
This survey is promoted and initially accessed via the BCT website;
https://www.bats.org.uk/our-work/national-bat-monitoring-programme/surveys/sunset-sunrise-survey

But the link to add records goes to a form hosted directly within iRecord:
https://www.brc.ac.uk/irecord/external/bct-sunset-sunrise

As with BWARS, these ask for a recorder name and require an email but do not link to existing iRecord accounts.

Is the situation in this case any different because the form is directly witin iRecord - could we make this form link to existing user accounts where the recorder has an account?

**Comment by BirenRathod** [comment]
@kitenetter 
About BWARS - The form has created separately on BWARS site. If users have submitted the same email address as irecord one, they should not appear in record's "My records". There is an option on warehouse and it is called agreement. So somebody needs to setup the agreement on warehouse. The agreement is basically to grant permission to see records submitted from BWARS site.

Where this sunset-sunrise-survey created in iRecord website, so if users have got account in iRecord, they can able to see records in "My records".

**Comment by johnvanbreda** [comment]
1. Your understanding is correct and yes, cloning the forms is an option. Another option is to write a simple script which repatriates the records using the attached email address - I've done similar things before after imports.
2. The situation is the same for this form, with the slight difference that if the user goes to iRecord directly first, then via the BCT iframe, they will be treated as logged in. This is unlikely to happen in reality.

**Comment by burkmarr** [comment]
@kitenetter @johnvanbreda - I wondered if the EasyLogin module was a possible solution for this since it would enable a link between BWARs Drupal accounts and Indicia, but I think the BWARs forms don't require users to login to submit records, so presumably it isn't an option.

**Comment by BirenRathod** [comment]
@burkmarr , you are right that none of the form of BWARS are required to login to submit record. 

As @johnvanbreda suggested a simple script would be a possible solution to repatriate user's records.

**Comment by kitenetter** [comment]
This hasn't been raised recently - closing.
