### ISSUE TITLE
Remove display, and probably underlying data, of date of birth

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#906]
User profiles may display a date of birth:

![image](https://user-images.githubusercontent.com/16039111/90283322-ed276080-de67-11ea-868e-f48f842db273.png)

This information is not needed, and is often incorrect, causing users to worry that it needs changing.

We should remove this element from the profile page, and ideally delete it from the data warehouse, since it is personal data that we no longer require.

Adding to September milestone as it is important that we action this when we can.

**Comment by johnvanbreda** [comment]
This was a simple change: https://www.brc.ac.uk/irecord/admin/config/people/accounts/display
Done.
