### ISSUE TITLE
Question - PoMS map not working?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#912]
This is the map of PoMS FIT Counts for 2020:
https://www.brc.ac.uk/irecord/node/7355?group_id=1074&implicit

Just over a week ago it was showing around 1,500 counts for the year, but it is now showing only the most recent 22 counts.

Can anyone suggest what might have caused the change? I'm not aware of any edits to the map page, and the data is present in the warehouse.

**Comment by johnvanbreda** [comment]
I've found that this relates to a recent change to add a training flag to the samples table which wasn't being filtered correctly. I've fixed this but it will take a while to apply the updates required to the cache table.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda all is working as expected now. Closing.
