### ISSUE TITLE
Verification error message

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#914]
Reported just now:
"I am having problems today with verification of moth record online. When using the multiple selection mode keep getting Ealscticsearch fail box and though it does update the status of the records I have to log out and back in to clear and continue. Using Firefox v79.0"

**Comment by kitenetter** [comment]
I'm getting similar results on my verification page. HAR file:

[www.brc.ac.uk_Archive [20-08-25 14-45-21].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/5124073/www.brc.ac.uk_Archive.20-08-25.14-45-21.zip)

**Comment by johnvanbreda** [comment]
@kitenetter I can see from the HAR file this might relate to the sort applied to the grid. Do you know if you had sorted the grid first? It didn't happen when I tried it using FireFox so if you can explain the steps you took it might be helpful.

**Comment by kitenetter** [comment]
Sequence:
1. Go to verify
2. Switch context to Soldierflies
3. Use "Recorder" column-head filter to select records with recorder name "Jones, Nigel P."
4. Enable multiple selection mode
5. Manually tick five records
6. Set status to "Considered correct" for five records

Outcome: records are correctly removed from the grid.

7. Sort by "Species"
8. Manually tick five records
9. Set status to "Considered correct" for five records

Outcome: records are correctly removed from the grid.

10. Add a second column-head filter to select species 
11. Use tick box at top of page to select all 30 records

Outcome: error message "Elasticsearch query failed"

12. Click ok on the error message
13. Set status to "Considered correct" for 30 records

Outcome: records remain in grid, although the status has been applied and can be seen in the Comments tab

HAR file:
[www.brc.ac.uk_Archive [20-08-26 10-32-07].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/5128918/www.brc.ac.uk_Archive.20-08-26.10-32-07.zip)

**Comment by kitenetter** [comment]
As far as I can tell, where it goes wrong is if I am in multiple selection mode AND I tick the box at the top of the grid to select all currently displaying records. Doesn't seem to matter if they are sorted or not.

If I manually tick individal records there is no problem, but as soon as I use the box to select all I get the "Elasticsearch query failed" message.

**Comment by kitenetter** [comment]
@johnvanbreda I think this one ought to be a priority - what scale of work is needed?

**Comment by johnvanbreda** [comment]
Small I think - I'll do it now @kitenetter
