### ISSUE TITLE
Simplify password reset email

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#919]
We regularly get messages from users who are struggling to reset their password. I suspect there may be technical issues in some cases, but at least a few cases users are finding our email confusing. The email that we send out says:

![image](https://user-images.githubusercontent.com/16039111/93322036-c9f72480-f80a-11ea-982f-7ae77505f39a.png)

There are three hyperlinks in that email, and it is the second of those that users need to click on. In the first sentence where it says "clicking on this link" there is some ambiguity as to which hyperlink is intended.

Do we need to include the first and third hyperlinks?

Can we re-word this as:

A request to reset the password for your account has been made at iRecord.

You may now log in by clicking on this link (or copying and pasting it in your browser):

[reset hyperlink]

This is a one-time login, so it can be used only once. It expires after one
day and nothing will happen if it's not used.

After logging in, you will be redirected to your user account page so that you can change the password to one of your choice (don't forget to scroll down the page and click on the Save button).

@BirenRathod can you let me know where this email text is stored - can I edit it?

**Comment by BirenRathod** [comment]
@kitenetter It is in the account settings. But be careful to use those Drupal default variables to reset link.
the "Accpunt settings" link found in Configuration -> People.

**Comment by johnvanbreda** [comment]
@kitenetter it is here - https://www.brc.ac.uk/irecord/admin/config/people/accounts, under Password Recovery.

**Comment by kitenetter** [comment]
Thanks @BirenRathod and @johnvanbreda - I have updated the password recovery text and tested it. Closing.
