### ISSUE TITLE
Review use of authentification tokens

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#920]
A user reports that they were in the process of adding a list of records when they arrived at a species iRecord wouldn't recognise (although it is in our species dictionary), and they then lost the set of records and got this error message:

![image](https://user-images.githubusercontent.com/16039111/93329652-6c1c0a00-f815-11ea-8ecb-d6b85925b17b.png)

That screenshot shows that they appear to have been logged out of iRecord, although they say they were definitely logged in when they started adding the list.

They are using Firefox on a Linux system.

What might cause the above error message to appear?

**Comment by johnvanbreda** [comment]
Might they have spent a particularly long time entering the list, i.e. more than about 2 hours?

**Comment by kitenetter** [comment]
What they said was:
"I entered about 7 or 8 species with photos, no problem but when I tried to enter a Bryozoan (Schizoporella unicornis) It couldn't find it. Text was in red and I couldn't progress.
I was using the site around 20.20 this evening (28th August) when it happened. I use Firefox on Linux.
Prior to entering these records, I had successfully entered another set of records for the same site.
I was logged in as myself and this error occurred just after I had sent in the other records. I did not log out in between but just followed on."

This followed a previous problem for the same user back in July:
"I just spent 4 hours plus, entering marine records from a survey we (Coastwise North Devon) conducted on Thursday. I entered around 20 or more records and then your iRecord site wouldn't find common species at all. It seemed to freeze. My records were all lost! 4 hours wasted!
Do you know of any problems on the site? I'm reluctant to start again. I might waste another 4 hours."

So on that first occasion at least the length of time may have been a factor.

Is the issue with the length of time spent on a single list, or the length of time spent on the site alotogether?

When verifying I find that the species lookup for the redet function quite often fails if I have been on the site for a period of time, but I think that usually happens when I've been verifying, then left the computer unattended for a while, and tried to carry on verifying without refrshing the page.

**Comment by johnvanbreda** [comment]
The authentication tokens are refreshed on page load but do expire after 2 hours (from memory). 

I think we should revisit these in light of the new JWT based authentication developed for Karolis' apps and the REST API to get round this limit.

**Comment by kitenetter** [comment]
@johnvanbreda the user confirms that they may have had iRecord open on their computer for over two hours, having left it running while they did other things. I've suggested that they try to remember to refresh the page occasionally if using the system for long periods of time.

It sounds like there is a wider issue about the authentification tokens so I will rename this issue and keep it open.

**Comment by kitenetter** [comment]
Not aware of reoccurrences of this recently. Closing.
