### ISSUE TITLE
ES verification page not loading correctly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#922]
This afternoon and this evening I'm finding that if I open the ES verification page I get an egg-timer for the records grid, which never goes away. If I change one of the dropdown filters at the top of the page it seems to sort itself out and then remains stable, but on first going to the page it is not loading up properly.

**Comment by johnvanbreda** [comment]
Fixed - I'd tidied a class name and missed changing it in some custom layout code we have on the verification page.
