### ISSUE TITLE
Dynamically update warehouse filters when website agreements change, so that data is included in the ES dataset

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#925]
This arose from #923 where an existing website changed its sharing agreement so that its data became available for reporting, having previously not shared for reporting. The data became immediately visible on iRecord but did not feed through to the ES dataset until manual edits were made to specify the inclusion of the additional website.

In the current code, we rely on a pre-configured Elasticsearch alias to ensure the correct records are returned for each task - John has suggested that it would be a good idea to explore dynamically adding the appropriate filter in the Warehouse API, rather than relying on the alias, so this change would happen automatically.

**Comment by johnvanbreda** [comment]
I've implemented the following ready for this:
1. The warehouse supports JWT access token authorisation for Elasticsearch requests. These tokens contain the user ID and website information.
2. If we configure it to do this, the JWT access to Elasticsearch will automatically get filtered to the reporting sharing websites for that website.
3. Full support for the above is in the Drupal 8 iform module.

Still need to do:
1. Full support for JWT authentication in the Drupal 7 iform module.
2. Support for JWT claims that are for different sharing modes.
3. Testing the filters are correctly applied (as this is quite a significant change of authentication approach).

**Comment by kitenetter** [comment]
@johnvanbreda did this work reach completion or do we need to come back to it?

**Comment by johnvanbreda** [comment]
Sort of - we use this for the Explore reporting, but the verification page still uses a custom alias because iRecord's verification tool includes confidential records (if allowed in a verification filter) whereas the default behaviour excludes confidential records.

**Comment by kitenetter** [comment]
Okay, will close for now.
