### ISSUE TITLE
Develop recording form for Garden Moth Scheme

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#928]
The [Garden Moth Scheme](http://www.gardenmoths.org.uk/) wishes to trial using iRecord to collect records, for a number of reasons including the desire to make GMS records available to county moth recorders.

At a meeting on 6 August these actions were agreed:
1. BRC to review GMS recording forms and set up a suitable data structure that could be used for importing GMS data.
2. BRC to set up trial recording form for the winter GMS, due to start in November
3. GMS to alert its participants to the planned winter trial
4. GMS and BRC to continue discussions to review progress and liaise with the wider moth recording community

I'm currently looking at step 1.

**Comment by kitenetter** [comment]
@DavidRoy this is going to need some developer support if we are to replicate the GMS recording form at all closely, so it's another prioritisation issue - the work will need to be donw by the end of October.

The GMS form currently uses a grid approach, consisting of 81 taxa by 17 weeks. We may not need to replicate the grid approach but we will need to find a way of handling the weeks.

**Comment by DavidRoy** [comment]
@kitenetter understood.  This is strategically important so will need to be a priority.  
@johnvanbreda. There may be commonality with the UKBMS recording form?  Which has a species by week grid

**Comment by johnvanbreda** [comment]
@DavidRoy @kitenetter the actual UKBMS input forms are using sections as columns rather than weeks, so I don't think they could be used here. The calendar picker used to pick a date before you start could though. 

I would imagine given the timescales that a recording form based on "enter a list of records" is the easiest way to do this. The users would have to enter data 1 column at a time (i.e. 1 week at a time) rather than on a single sheet for the year. The form could have a custom control for picking the week number, plus an ability to set the exact date (both of which could be pre-populated if they use the calendar to pick the date first). We could preload the list of species (perhaps using a scratchpad list for each region). 

How important is it that we use the codes available for species? Or is just species name good enough?

**Comment by kitenetter** [comment]
@johnvanbreda I agree that the "enter a list" option is the most practical, at least for this initial trial, unless you can see a straightforward route to setting up a grid that is more similar to the single-sheet view that GMS participants are used to.

If a grid view for data entry isn't possible then it would be nice to set up a reporting option for particiapnts so that they could see and download their data in a similar single-sheet view, but that isn't an immediate requirement for this trial.

For dates, the ideal solution is:
1. User picks week
2. Date is filled in with the default "planned date" for that week
3. User needs to be able to edit that default date if they have to trap on a different night, and ideally they should only be offered the three days either side of the default date (i.e. 7 dates in total, centred on the default date)

For the winter survey there are no regional variations in the species list, although this will be required if the trial is successful and they wish to extend it to the summer period as well.

I imagine that one reason why people like to use the single-sheet grid is that they can easily see which species the GMS is interested in, whereas the enter-a-list option relies on participants either remembering or looking up which species they need to record, or else recording everything and letting GMS admin filter out the species they are interested in. Part of the reason for GMS having a defined list was to exclude some of the tricky species that beginners struggle with, and ideally it would be good to retain some filtering or guidance that makes it easy for people to see what they should be recording.

The existing GMS survey does allow people to add species at the bottom of the spreadsheet that are additional to the list of target species, and if we can replicate that it would be ideal, but this is not a requirement for the initial trial.

The species codes are not essential for data entry in my view, and we don't provide species codes for moths elsewhere in iRecord, although if we were able to do this it would be popular with some county recorders at least. Not part of the initial requirement though.

The form must allow a zero count to be entered, which I guess means that we will end up with samples for which there are no occurrences, and these will need to be included in any reporting/downloading. Alternatively, we could include "nothing" as a taxon, which is the approach currently taken by GMS and MapMate.

**Comment by DavidRoy** [comment]
I agree that we should go with the simplest short-term solutions but there do seem to be parallels with the UKBMS entry forms and reporting forms.

The UKBMS input form enables users to select their list for the data entry grid (e.g. species known at this site, common species, all species etc) and add any extras using a lookup.

The annual summary report form gives a table of species x week with the ability to estimate counts for missed weeks and plot the results.

**Comment by johnvanbreda** [comment]
My comment in relation to the scratchpad lists was intended to cover the pre-loading of the species list. The user would first pick a predefined list for their region then the list would appear in the species input grid. This is built in functionality in the enter a species list code, we just don't use it on iRecord. Each species would have a tickbox that can be ticked if present. Any extras can then be added using the lookup as now.

We could definitely build a custom form with columns for weeks, but it might take a few days. There is an existing weekly counts input form I built for a small project a few years ago but it's not been maintained so would require some effort to get it going again. Also the user may expect to use it like a spreadsheet, i.e. enter each week's data as they go along, then submit at the end of the year. So there are some complexities around this.

**Comment by kitenetter** [comment]
The prepopulated species grid sounds like it would work well for this project.

Regarding the columns for weeks, I think there is a trade-off between replicating what GMS recorders are currently familiar with, and what is going to be most effective within iRecord going forwards. Replicating the spreadsheet as closely as possible would of course make it easier for existing GMS users to transfer over, and perhaps more likely that they would be willing to give it a try.

But not all existing GMS users use the spreadsheet, some send in data via MapMate, and those people are just entering records one at a time as usual.

Given that this is a trial, and the GMS people are expecting to have to deal with multiple different dataflows for the immediate future at least, I would suggest:
1. We set up an "enter a list" form that uses the scratchpad functionality to prepopulate the standard GMS species list
2. We scope out options for developing a reporting page that enables users to see their data in weekly columns for the current season. Ideally there would be a report for each individual GMS contributor to see their own records, and a combined report for GMS coordinators to see the records for their region - but those are 'nice-to-haves' for the future and needn't be implemented for the start of winter GMS

**Comment by DavidRoy** [comment]
Related to #2, I've been discussing with @burkmarr about implementing the FSC moth bar charts within a Drupal/Indicia module.  https://www.fscbiodiversity.uk/fscmoths

**Comment by kitenetter** [comment]
GMS have changed their minds and do not wish to proceed with the trial use of iRecord at present, so I'll close this for now and we can pick it up again if the opportunity arises.
