### ISSUE TITLE
Verify Tick List checkboxes disappear

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#93]
Reported by Dave Slade at http://forums.nbn.org.uk/viewtopic.php?id=6581 and copied here.

"When using the verification features on iRecord, I often use the 'Verify tick List' option. This usually works well, but occasionally when refreshing a page of records you have to turn the feature off and on again for the tick boxes to appear. I reported this some time ago, and had thought it was fixed, however there are still occasions when this process has to be repeated. As this is an intermittent bug it was very hard to replicate, but I think I have finally found the trigger.

If you select a record (with the Verify Tick List' enabled), and click on the 'Query' button, then sends the query, the next time that the grid refreshes the tick boxes will have been lost. To get them back, you have to click the 'Review Single Records' button, then 'Verify Tick List'. The user has to repeat this process each time the grid refreshes, but can be resolved if they reload the page."

**Comment by johnvanbreda** [comment]
Fixed in develop branch and will be deployed with the next feature release.

**Comment by JimBacon** [comment]
Dave Slade says at https://forums.nbn.org.uk/viewtopic.php?pid=27352#p27352

"Did this 'fix' ever go live? If so, it didn't work as I still experience the same problem when using the the verify tick list. I now try to save up the records that require queries and reload the form to go back to tick list verification. This does slow the process down a bit!"

**Comment by johnvanbreda** [comment]
I've committed a tidy up of this code to the develop branch, so this will be fixed in the next feature release.
