### ISSUE TITLE
Add 'Date type' field to the ES index and backward-compatibility download format

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#933]
This issue is branched from https://github.com/BiologicalRecordsCentre/iRecord/issues/800#issuecomment-693405948. The 'Date type' field is required in the ES index for the backward-compatibility format. @johnvanbreda wrote:
> This was left out because I was trying to map to Darwin Core as closely as possible in the ES index design. I think that if it is useful though we should add it to the index rather than reverse engineer it from the dates.

I suggest @johnvanbreda adds to the index and then @burkmarr updates the download format.

**Comment by johnvanbreda** [comment]
@burkmarr the event.date_type field is now in the index. It will be populated for any new records added from now and I've started a refresh to fill it in for other records over the next few days.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda -I've added into the backward compatibility format and pushed to the branch that is the subject of the pull request.
