### ISSUE TITLE
Where to find details of user notifications?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#937]
Laurence Carvalho needs to check how many users of the Bloomin Algae app have signed up to receive notifications for records in their local area - apparently the Scottish local authorities were being encouraged to do this and Laurence needs to track how successful it has been.

I'm not familiar with the notification process. Can anyone give me some pointers, e.g.
- Where do users go to set up such notifications?
- Where in the data warehouse are the notifications stored - what tables do I need to look at to work out who is being notified for the Bloomin Algae project?

**Comment by kitenetter** [comment]
I've found the answer to the first of those questions - users can set up notifications here:
https://www.brc.ac.uk/irecord/species-alert-notifications

I don't think we include that page in any of the iRecord menus, and for Bloomin Algae people are given a link to it from the Bloomin Algae website.

**Comment by kitenetter** [comment]
And I think I've answered question two as well - having actually looked at the data tables I see there is one called "notifications", so I will see if I can make sense of that. (And apologies for any stresses on the system from my having mistakenly tried to view the whole table.)

Closing.

**Comment by kitenetter** [comment]
I've managed to get some useful information from the notifications table, but that shows each individual notification. Is there a way to query what definitions users have specified when they set up their species alert notification, i.e. showing taxon name and geographical area? I can't see where the definitions are stored.

**Comment by johnvanbreda** [comment]
I think you want the species_alerts table @kitenetter.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - closing.
