### ISSUE TITLE
Change Elasticsearch document _id prefixes

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#938]
Download reports on iRecord from PostgreSQL have traditionally prefixed record IDs with iBRC to make a "globally unique identifier".

The Elasticsearch instance setup by BRC refers to the warehouse as "brc1" and uses this as a prefix, with a pipe then the ID used to construct a record unique identifier, e.g. brc1|123.

Documenting the steps here in case they are useful in future.

The proposal is to change Elasticsearch so that the unique identifiers generated match those used by the old PostgreSQL download report formats. Here are the proposed steps:
1. Stop logstash
2. In the logstash config files, search for brc1| and replace with iBRC (in the document ID).
3. Also change the logstash config so the stored warehouse is actually the domain, not just a simple code as this would be more useful:
```
add_field => { "warehouse" => "brc1" }
```
to 
```
add_field => { "warehouse" => "warehouse1.indicia.org.uk" }
```
4. Create a logstash config file called "update_id.conf" and populate it with the following:
```
input {
  elasticsearch {
   hosts => ["localhost:9200"]
   index => "occurrence_brc1_index"
   query => '{ "query": { "match": { "warehouse": "brc1" } } }'
  }
}
filter {
 mutate {
  replace => [ "warehouse", "warehouse1.indicia.org.uk" ]
 }
}
output {
 elasticsearch {
   hosts => ["localhost:9200"]
   manage_template => false
   index => "occurrence_brc1_index"
   document_id => "brc1|%{id}"
   workers => 1
   action => "delete"
 }
 elasticsearch {
   hosts => ["localhost:9200"]
   manage_template => false
   index => "occurrence_brc1_index"
   document_id => "iBRC%{id}"
   workers => 1
 }
}
```
5. Run this config file: `$ logstash.bat -f update_id.conf` (maybe try first 100000 records first?).
6. Edit iRecord and ABLE verification so that they have the correct iBRC prefix specified in the Elasticsearch configuration.
7. The logstash configuration templates will need to be modified so that the warehouse field value is not the same as the ID prefix.

**Comment by kitenetter** [comment]
I think this was for documentation rather than action? Closing.

**Comment by johnvanbreda** [comment]
This has indeed been done.
