### ISSUE TITLE
Ensure that verifiers continue to receive notifications of records awaiting verification

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#939]
This arises from a feature within iRecord that seems to be having unhelpful consequences. There is some extensive background discussion, including some documentation from Jim Bacon, at https://github.com/BiologicalRecordsCentre/iRecord/issues/384#issuecomment-405546023

If I have understood correctly, the current situation is that we send out notifications to verifiers to alert them to the fact that new records have come in and are awaiting verification. However, if the verifier does not acknowledge that notification, and does not log on to iRecord, we prevent any further notifications being sent.

Some verifiers have complained that since they weren't receiving notifications, they didn't realise records were coming in, and have been somewhat shocked to discover a backlog waiting for them when they do log in, perhaps after a long gap.

Can we change the notification behaviour so that verifiers continue to receive notification of pending records regardless of whether they have acknowledged the previous notification?

**Comment by kitenetter** [comment]
@burkmarr is verifying regularly but not receiving notifications, despite setting for daiyl notification

**Comment by johnvanbreda** [comment]
I've handled this by automatically acknowledging any verifier notifications sent out more than 24 hours ago. This means that if there are still records to verify, a new verification notification will get sent out.
