### ISSUE TITLE
New system function for "behaviour"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#940]
At least two projects have a need to handle attributes that store data on "behaviour". The one that I know about is NatureSpot, which is using the BTO list of terms for "breeding evidence" for bird records within the NatureSpot app (a customisation of the iRecord app). In that case the data is being stored in custom occ_attr 823 "Breeding evidence (birds)".

Strictly speaking, not all of the terms in the "breeding evidence" termlist relate to behaviour, so it's worth thinking about what to call this system function, and what other termlists might get included within it.

@johnvanbreda can you let me know what sort of terms are being used in the other project you mentioned?

Currently we have about 9 custom occurrence attributes that are labelled with "behaviour" as part of the caption - these are a mix of lookup lists and free text.

@johnvanbreda when we to assigning attributes to the system function, is it advisable to limit it to the lookup lists, or can the system cope with free text alongside lookups?

We also have about 10 custom occurrence attributes that are labelled with "evidence" (about half of which refer to breeding evidence) and about 14 that are labelled with "breeding", mostly for bird breeding evidence.

So the question arises as to whether we should call this system function "breeding evidence" and limit it to attributes that address that, or whether we have a broaded system function called "behaviour" that takes in a more diverse set of terms.

For reference, in an email at Dec 2019 John provided a summary of the approach to the NatureSpot app:

> 1. As well as the generic attribute for Sex, the app needs a dynamic "breeding evidence" attribute for all bird records, for whichever activity, with the full list of terms from the BTO guidance.
> 2. Make sure the edit form on iRecord handles this dynamic attribute.
> 3. I’ll add a “NatureSpot” activity to iRecord enabled for use in the app. The description will make it clear that this will result in records being sent to NatureSpot.
> 4. I’ll write some background code that changes the website ID for records from the NatureSpot activity so they belong to the NatureSpot site. Otherwise I’d have to do some more complex filtering in the reports on NatureSpot which will be slower.
>

**Comment by johnvanbreda** [comment]
@kitenetter I had hoped to just use the term behaviour as it maps directly to Darwin Core, which feels the right thing to do for any standard attributes going forward. However, looking at the Breeding Evidence terms list in use, it's a mish-mash of things including behaviour, habitat suitability, life stage, sex and evidence of presence therefore hard to pigeon hole into any single term. In NatureSpot, the column used for breeding evidence is very generically called "Attribute" and if you select an insect, you get a simple list of insect related stage terms such as larvae, pupae etc. Luxembourg museum have exactly the same requirement as iRecord and I'm sure will adopt whatever strategy we use for iRecord.

The other case where I've seen behaviour used a lot is cetacean data but I think in that scenario the terms used do fit into the category of behavioural terms nicely, e.g. breaching, bow-riding. 

Free text and lookups should both be fine BTW.

So, I think the options are:
1. Add a behaviour system function.
    * Pros - maps nicely to Darwin Core. Simple.
    * Cons - some breeding evidence terms aren't really behaviour terms (e.g. recently fledged), some aren't really behaviour but do indicate a behaviour occurred (faecal sac).
2. Add a breeding evidence system function.
  * Pros - all the terms used for birds will be a logical fit.
  * Cons - very specific to bird recording, unlikely to be used for anything else.
3. Don't add a new system function at all, but instead show any attributes that are taxon specific which don't fit into the existing columns in a second row in the grid (like when viewing the grid on a narrow screen, some attributes get hidden under a + button). 
  * Pros - very flexible, can support more attributes.
  * Cons - quite a bit more work to implement.

Any thoughts?

**Comment by johnvanbreda** [comment]
@kitenetter can you let me know if you have any thoughts on this before I proceed please? I thought of a 4th option, to add a system function called "attribute" or similar, which we'd use to capture lists of terms which don't neatly fit the sex/stage categorisation or contain mixtures of term types. This could be added as well as the behaviour type.

**Comment by johnvanbreda** [comment]
There is now a Reproductive Condition system function and a Behaviour system function. @kitenetter I think this can be closed?

**Comment by kitenetter** [comment]
Suspect we will need to come back to discussions around how best to deal with dynamic attributes, but agree we can close this one.
