### ISSUE TITLE
Sensitive species blurring

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#941]
We currently blur most badger records to a 1km square. However, this blur is not being applied to records from Mammal Tracker.

Are we able to apply the blur via our normal mechanisms or is this an issue that is specific to Mammal Tracker?

**Comment by kitenetter** [comment]
This is for Mammal **Mapper**, website ID 120. @johnvanbreda to add this website to the list for the grid ref blurring task for new incoming records, and ensure that records already in the system are also blurred.

**Comment by johnvanbreda** [comment]
Done:
* Website 120 added to the member_website_ids list in the SENSITIVE group (modules/workflow/config/workflow_groups.php). 
* Following script applied for existing data:
```sql  
update occurrences set sensitivity_precision=1000 where id in (select id from cache_occurrences_functional where website_id=120 and taxa_taxon_list_external_key='NHMSYS0000080191')

insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
from cache_occurrences_functional where website_id=120 and taxa_taxon_list_external_key='NHMSYS0000080191';
```
