### ISSUE TITLE
Edit ID difficulty rules

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#942]
I need to edit the text for the ID diificulty rule for Southern Damselfly. Am I able to do that within the warehouse interface, or does it requite a database edit? 

I can see the rules for range and phenology within the warehouse interface, but I can't find the ID difficulty ones.

**Comment by johnvanbreda** [comment]
If you filter for test type=IdentificationDifficulty you'll find that there is a single rule per scheme, with a long list of TVK/difficulty value pairs in the data. At the bottom of the Other Data text box is an [ini] section with the rule texts. The one you want is https://warehouse1.indicia.org.uk/index.php/verification_rule/edit/2886.

I haven't edited via the warehouse UI for a little while so if you prefer I could update the rule text directly.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 

I hadn't appreciated that the text associated with rule nos. 1 to 5 applies to *all* taxa that are linked to those numbers. What I need is a custom piece of text that only applies to Southern Damselfly. Do you foresee any problem with creating a rule no. 6 and then editing so that:
NBNSYS0000005603=6

**Comment by johnvanbreda** [comment]
Possibly - the system was definitely designed with values 1-5 in the requirements so there may be problems with using 6. What about making a completely new rule just for Southern Damselfly?

**Comment by kitenetter** [comment]
Good idea - will try that.

**Comment by kitenetter** [comment]
Have created a new rule just for Southern Damselfly, and have removed this taxon from the list of species to which the generic rules apply. This seems to have worked.

Still to do: inform NBN so that they can adjust the record cleaner rulesets if needed.

**Comment by JimBacon** [comment]
Proposed changes to Record cleaner rules at https://github.com/BiologicalRecordsCentre/record-cleaner-rules/pull/1/files

**Comment by kitenetter** [comment]
Closing.
