### ISSUE TITLE
Upate VCs to reflect name changes and changes to Sules

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#945]
Update the Vice Counties in Warehouse 1 to reflect the name standardisation (https://github.com/BiologicalRecordsCentre/vice-counties/issues/3) and the re-assignment of Sule Skerry and Sule Stack to Orkneys from Outer Hebrides.

**Comment by burkmarr** [comment]
@kitenetter VC names on live Warehouse now updated as are boundaries for 110 and 111. New names and boundaries now available on iRecord.

**Comment by kitenetter** [comment]
Another anomaly has been reported:

> I was just checking the VC boundaries and noted that Ailsa Craig (off the Ayrshire coast) appears to be listed in VC75 (Ayrshire) on the MLWM map but is listed in VC110 on the 3km and 12km maps.

Ailsa Craig should be included within VC75 in all three versions of the boundaries.

**Comment by burkmarr** [comment]
VC repository is updated and the VC boundary for Ayrshire (which is the 3 mile limit dataset) has been updated in the Warehouse (and hence iRecord). The 3 mile and 12 mile boundaries in the repo had Ailsa Craig assigned to VC100 (not 110). However I didn't need to update the 3 mile boundary on the Warehouse for VC100 since, for some reason, Ailsa Craig was not included in the Warehouse geom.
