### ISSUE TITLE
Question: what does 'pre-authorised' mean?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#946]
As part of a query over user accounts I've found an account that has been given the 'pre-authorised' role. What does this mean?:

![image](https://user-images.githubusercontent.com/16039111/98155807-c1e46880-1ece-11eb-9418-ab7ff3f8f868.png)

**Comment by johnvanbreda** [comment]
The explanation for this is on the Login Toboggan settings page - https://www.brc.ac.uk/irecord/admin/config/system/logintoboggan.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - if I'm understanding this correctly the person in question must have started setting up an account and never completed it (they already had an existing account from some years ago).

I'm assuming that no further action is needed. Closing.
