### ISSUE TITLE
Filtering by Map Ref: wildcard OS grid references

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#949]
_Enhancement request:_ 
In **Explore** and **Verify** allow wildcard searches for anything within a larger map square. Currently the **Map ref.** field in iRecord allows simple string wildcarding e.g. **TF*** but not single-char wildcarding such as **TF3?2?** nor the much more useful gridref-aware wildcarding such as **TF3+2+**, where the two pluses indicate any easting within TF 3 and any northing within TF 2 respectively.

This request has been brewing for a while and I've submitted it now after seeing Martin's issue on wildcards #947 .

(To optimise this, we could compute and store all enclosing squares within the record whenever the primary Map ref is set or edited. For example, if the record has a 100m map ref of TF31972458 the additional enclosing squares are TF, TF32, TF3124 and TF319245, with the 10m and 1m map refs being Null.)

**Comment by japonicus** [comment]
Simple wildcards probably aren't feasible for this, e.g. TF3+2+ also matches TF31219999, which is not intended. As with sorting grid-references, searching probably needs to use a custom method.

This feature request regarding grid-ref sorting may be related: https://github.com/BiologicalRecordsCentre/iRecord/issues/136

**Comment by DavidHepper** [comment]
I withdraw this request. It is more important to fix #1561 and improve the popup help for the column header filter on **Map ref.**
