### ISSUE TITLE
"elasticsearch query failed" in Verify

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#953]
Rosie Ray and I are getting the above message in a pop-up in Verify (but not in Explore) even with no filter set other than the default. The grid is updating underneath but I'm not sure other things are happening correctly as selecting a row in the grid causes more pop-ups.

**Comment by johnvanbreda** [comment]
@DavidHepper does this happen immediately when you open the page? Or are you doing something else first?

**Comment by johnvanbreda** [comment]
Ah - just found it's immediate, but it happens in Chrome but not Edge. I'm looking into it now.

**Comment by johnvanbreda** [comment]
That should be sorted now.
