### ISSUE TITLE
Bulk deletion request: sub-standard duplicate imported HBRG Odonata

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#959]
Please delete a block of sub-standard imports with incorrect values (my fault) that were later reimported successfully on 14/01/2020, so are currently duff duplicates. There are too many to delete manually. 

Filter criteria:
- Source: **iRecord | DRN dragonfly imports**
- Input date: **22/02/2019**
- CMS Username: **David Hepper** - if selectable
- Where: **Country > Scotland** - this is necessary because others on the same day were from IoW
- Record ID: **is at least 9231358** - this is necessary because other Scottish records were recorded earlier in the day

The ID of the last record is **9232686** and the total number thus selected should be **1,323**.

With apologies. This correction was first requested informally on 25/02/2020 but has been overlooked.

**Comment by burkmarr** [comment]
@kitenetter & @DavidHepper - this is done. It might take a little while to propograte to Elasticsearch.
