### ISSUE TITLE
NBN record export process - new files not getting saved?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#960]
On 1 and 2 December I have triggered about five dataset exports for NBN. On the page here:
https://www.brc.ac.uk/irecord/exports?order=field_indicia_ae_last_date&sort=desc

It is telling me that the export process has run, but the files on the "exports" server are not getting updated.

Marking as urgent because the updated file are needed by Friday 4 December in order to correct erroneous records that havebeen queried on the NBN Atlas.

**Comment by BirenRathod** [comment]
@kitenetter I can see file has been created on the server. How do you access the file from the website generally?

**Comment by kitenetter** [comment]
The example I'm trying to update is for the "NBN_Sawfly_records_from_iRecord". The export page on iRecord is telling me that it was exported earlier today (3 December):

![image](https://user-images.githubusercontent.com/16039111/100990964-64355180-354a-11eb-832c-67bd9f7fd29f.png)

However, the file on the "exports" server (192.171.199.203) is still dated 26 November 2020:

![image](https://user-images.githubusercontent.com/16039111/100991155-9941a400-354a-11eb-861f-9e0799e35b9e.png)

**Comment by BirenRathod** [comment]
@kitenetter Yes, it has. I put here.

[NBN - Sawfly records from iRecord.zip](https://github.com/BiologicalRecordsCentre/iRecord/files/5635109/NBN.-.Sawfly.records.from.iRecord.zip)

**Comment by johnvanbreda** [comment]
@kitenetter I've found the files, in D:\websites\irecord\sites\default\files\private\indicia\exports.

@BirenRathod did the iRecord private file system path get changed on the 1st of December? Since then, it seems the exports and Indicia cache files are now in the above path, rather than the old location (D:\Drupal_backup).

**Comment by BirenRathod** [comment]
@johnvanbreda May be changed by mistake. It should be on my local machine not on live site.

**Comment by BirenRathod** [comment]
@johnvanbreda & @kitenetter I have reverted back.

**Comment by johnvanbreda** [comment]
@kitenetter What is the "exports" server? The Drupal live server (IP address ending 201) generates the files.

**Comment by BirenRathod** [comment]
@johnvanbreda Don't worry about 201 IP address. It is used to give access only for you.

**Comment by BirenRathod** [comment]
@johnvanbreda Also, I have created the map drive from the brc server for @kitenetter to get those export files,

**Comment by kitenetter** [comment]
The newly triggered exports are now resulting in new zip files being added to the location that I normally get them from, so this seems to be fixed, thanks. Closing.
