### ISSUE TITLE
Request to reinstate a deleted record

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#961]
During data entry for PoMS a sample has been deleted by mistake. This is for sample ID 11593919.

Can this be set back to deleted = false?

And if that is done, will the associated custom attributes also be reinstated or are additional steps needed to achieve that?

**Comment by burkmarr** [comment]
@kitenetter - I'm pretty sure that I've done this now: records look fine in the two cache_occurrences tables. I reset delete flags on the sample, occurrence and attribute tables and rebuilt the cache entries.

**Comment by kitenetter** [comment]
Thanks @burkmarr. I think this has resolved things. The report page that lists all the PoMS samples is displaying a bit oddly (the pan-trap number is missing) but on the sample page itself all seems to be well. Closing.
