### ISSUE TITLE
Error message preventing data entry

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#962]
A user has reported a problem while entering data onto one of the PoMS forms on iRecord:

> It has thrown me out with an error message part way through entering PoMS data. Not sure what has been saved.
> 
> Message is 
> PDOException:
> SQLSTATE[HY000] [1040] Too many connections in lock_may_be_available() (line 167 of D:\websites\irecord\includes\lock.inc).

Does this need further investigation?

**Comment by BirenRathod** [comment]
@kitenetter  Is it for survey id 420 or 480?

**Comment by kitenetter** [comment]
It is for survey ID 481.

The user has been in touch to say that he has now gone back in to the recording form and it seems to be working fine again.

**Comment by BirenRathod** [comment]
@kitenetter Ok, thanks. Seems like that was temporary glitch. I don't see any errors in the log files.

**Comment by kitenetter** [comment]
This seems to have been a one-off. Closing.
