### ISSUE TITLE
Odd behaviour for records from NatureSpot

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#964]
The verifier for the Agromyzidae recording scheme receives records from a number of NatureSpot users. For most of these users the data is appearing as expected. For one particular user it is not. The user is Graham Calow, warehouse user ID 449.

All Graham's records up to 13 November 2019 were appearing on the old verification page, on the new verification page, and in the downloads the scheme takes out of iRecord. They also appear on both old and new Explore pages.

All Graham's records after 13 November 2019 are still appearing on the new verification page, but are no longer showing on the old verification page, and are not included in the downloads the scheme takes out of iRecord. They appear on the new Explore page but not the old.

I can't see any reason for this.

As examples, here are two recent occurrence IDs for records that are not appearing where they should:
18354939
18203361

The verifier also reports that there are other NatureSpot users whose records only appear on the new verification page, not the old, but these other users' records do get included in his downloads.

**Comment by johnvanbreda** [comment]
These records were marked as not for sharing due to user preferences. It appears that Graham may have selected a little used option to disable sharing of his records for a period of time. As his account no longer has this preference set, I've removed the flags so they should reappear.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda. We probably ought to check whether there are other recorders who have ended up in this position. Can I query this via pgAdmin - where is the user preference information stored?

**Comment by johnvanbreda** [comment]
In the users table, allow_share_for_* fields.
