### ISSUE TITLE
Records imported from a text file cannot be edited

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#965]
Records that have been imported into the "iRecord import" survey cannot be edited by users. The edit button appears against the records in the "Explore my records" view, but clicking on that button results in a redirect to the iRecord home page.

I'm fairly sure that it used to be possible to edit imported records, so I'm not sure why this has changed (unless I'm misremembering things).

If I view the records as a verifier I can edit them, but if I view them as the person who imported them I can't.

For example, as a verifier I can edit here:
https://www.brc.ac.uk/irecord/edit-generic-record?occurrence_id=17752327

But as the user who uploaded the record the edit link sends me to:
https://www.brc.ac.uk/irecord/?occurrence_id=17752327

Marking as a priority since this is now causing requests for us to carry out database edits.

**Comment by johnvanbreda** [comment]
Fixed
