### ISSUE TITLE
Incorrect behaviour when adding records by scientific name

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#97]
If you try to add a bumblebee record by typing in the scientific name, iRecord is failing to find the species, e.g. if you go to add a record and type in "Bombus terrestris" you are not being offered the correct option of "Bombus (Bombus) terrestris".

English names are working okay, and the abbreviation "boter" is working, but not the full name option. I'm 99% certain this was working previously, and does still work for other species, but is erratic (e.g. typing in "Andrena flavipes" does correctly find "Andrena (Zonandrena) flavipes", but typing in "Andrena fulva" fails to find "Andrena (Andrena) fulva").

Has something happened following the UKSI update?

**Comment by kazlauskis** [comment]
Is there a need to keep the old name in the brackets or could we just remove it?

**Comment by kitenetter** [comment]
@kazlauskis the name is brackets is not an older synonym, it is the current subgenus. Many recorders that I speak to find the subgenera unhelpful, but the UKSI insists on using them so I think we have to stick with that.

**Comment by kitenetter** [comment]
Another user has just reported that they are unable to enter a record for dung beetle "Aphodius contaminatus", because the full name is "Aphodius (Nimbus) contaminatus", so this problem isn't just confined to bees, it must be something more general in the way we are now interacting with UKSI.
