### ISSUE TITLE
Minor issue with notifications

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#970]
The names displayed in the notification emails are currently being shown as first_name followed by last_name, but with a comma in between:

![image](https://user-images.githubusercontent.com/16039111/103149877-cf4b0000-4765-11eb-9a21-9644e7d3170f.png)

The comma is not needed.

**Comment by DavidHepper** [comment]
This is still confusing. Especially for names such as "Paul, David".
