### ISSUE TITLE
Request to delete a duff imported block

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#971]
Apologies but there's been an erroneous import. Please delete the following:
- Src: 32|346 = iRecord | DRN dragonfly imports
- Date Entered: 29/12/2020
- CMS Username: David Clarke = davidclarke6970@gmail.com
- ID range: 18494900 - 18495833
- Number of records to delete: 754

**Comment by burkmarr** [comment]
@kitenetter  & @DavidHepper - this is done now.

**Comment by DavidHepper** [comment]
Thank you! Much appreciated.
