### ISSUE TITLE
UKSI update - redundant names have reappeared

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#975]
Congratulations on today's UKSI upgrade!

Two names that are marked as "deprecated" in the UKSI have now got reset to being allowed for data entry in the iRecord dictionary. We had previously flagged them as being "not for data entry", and I realise that such flags get over-written when we update, but I was not expecting deprecated vernacular names to come back into the system.

Does this mean that something went wrong, or does it mean that we need to extend the scripts so that they exclude deprecated names?

I will reset the two names so that they are again flagged as "not for data entry". They are:
- taxa_taxon_list_id = 235876, UKSI = http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000169053
- taxa_taxon_list_id = 473338, UKSI = http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000169054

**Comment by johnvanbreda** [comment]
Now sorted.
