### ISSUE TITLE
New records not appearing on ES verification page?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#977]
No new records have appeared on my ES verification page since the day before we did the UKSI update. Is this just a result of the re-indexing process?

**Comment by kitenetter** [comment]
Records have now appeared, so I guess it was the re-indexing. Closing.

**Comment by johnvanbreda** [comment]
Yes, there were some high level taxonomic name changes which meant lots of records needed their cached data updated, so the queue of stuff to transfer to Elasticsearch is still processing.
