### ISSUE TITLE
Vice County picklist is failing to match in Verify > Create a filter

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#978]
The vice counties sometimes fails to match, e.g. not showing 'Surrey' on typing Su. It shows the chasing-arrows icon at the end of the input field. The only workaround I've found is to do a full refresh on the Verify page and try again.

**Comment by kitenetter** [comment]
A similar issue arises with the look-up box for redetermining species. If one has been verifying for a longish period of them the look-up stops working, and as @DavidHepper says the only solution is a page refresh.
