### ISSUE TITLE
Transfer records between accounts

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#98]
Hi, is there a way to transfer records between accounts? Say a person has created two accounts by mistake and would like to transfer the records between them.

Thanks

**Comment by BirenRathod** [comment]
Just replace the userid with the one you want to keep.

**Comment by kazlauskis** [comment]
OK, thanks. Messing directly with the database.. I'm not a fan of it.

**Comment by johnvanbreda** [comment]
There is a module on the warehouse called people_tidier, which does exactly this. I don't think it has been used much though since it was first written and could therefore do with testing before using in a live environment.

**Comment by kazlauskis** [comment]
OK, thank you both.
