### ISSUE TITLE
VC assignments missed for some imports on 15/01/2021

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#981]
The assignment of a VC to records imported last Friday around 15:00 has failed. 
The 543 dragonfly records affected are all for East or West Norfolk, with IDs from 18651387 to 18651930. The map references look good.
The flight period, geo range and ID difficulty rules have been processed correctly. (Is this unexpected, when the VC assignment fails?)
Please kick the background process. We have just avoided reimporting them all!

**Comment by kitenetter** [comment]
@johnvanbreda is this just awaiting on the indexing following the UKSI upgrade? Would be good to avoid multiple uploads if we can.

**Comment by johnvanbreda** [comment]
These were indeed stuck due to overload when re-indexing all the UKSI data. I've "kicked" the background process so they will re-index shortly.

**Comment by DavidHepper** [comment]
I'm not sure that closing this issue is appropriate until it is confirmed that the records have been updated. Is there a 'Pending closed' status available?

**Comment by DavidHepper** [comment]
The missing records have now appeared. Happy to close.
