### ISSUE TITLE
Unable to upload records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#982]
Earlier to day I was able to upload from a csv file into iRecord, but I've just tried again and got an error message:
"The upload destination folder, D:\websites\warehouse\import/, does not appear to be writable."

**Comment by johnvanbreda** [comment]
The version deployed today puts uploaded CSV files in the /import folder, rather than /upload. Permissions must have been incorrect but they look OK now so maybe @BirenRathod has already done this?

**Comment by BirenRathod** [comment]
@kitenetter It had been deleted when last time warehouse updated, so permission reverted it back. I reinstated now.

**Comment by BirenRathod** [comment]
@johnvanbreda  Yes, I just did while you have posted your comment.

**Comment by kitenetter** [comment]
I've just tried it out and all seems to be well again, thanks. Closing.
