### ISSUE TITLE
Blue expansion cross symbol missing on vascular plant card

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#985]
Under https://www.brc.ac.uk/irecord/enter-vascular-plants the blue/white plus symbol is missing from a species row, so that additional option availability is not obvious. See red arrow below.

![image](https://user-images.githubusercontent.com/5985134/105503550-a5322280-5cbe-11eb-9c23-87de87fa8fd2.png)

**Comment by johnvanbreda** [comment]
Closing as behaves as designed - the + button appears when a species name has been added.
