### ISSUE TITLE
Move all old-format download roles into the new format

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#987]
First priority is to set up all the LERC download roles with new filters so that the new download process can be applied.

- [x] Contact ALERC to ask them to send out information about the changes
- [x] Review which accounts have LERC download roles
- [x] Set up new filters for those accounts

Also, there are a large number of specific download links in the menus, and I don't understnad how these work or where they are defined:
![image](https://user-images.githubusercontent.com/16039111/105513605-6f933680-5cca-11eb-8286-e5a6261b7722.png)

Question for @DavidRoy or @johnvanbreda  - do we know how many of the above roles are still needed? For those that are, is it possible to move them into the new page, e.g. by ensuring that the people who need them have a suitable download filter set up?

**Comment by johnvanbreda** [comment]
We'll have to tackle them on a case by case basis, but most of them should be OK to move over. Some have custom downloads, e.g. the transects for Moors for the Future.

**Comment by kitenetter** [comment]
Update at 6 April 2021: 38 of the 69 'regional collator' roles have now been updated to the new filters.

**Comment by kitenetter** [comment]
@johnvanbreda I have to set up a filter for Paul Stevens at the ERIC records centre, but there are so many other Paul Stevens that I cannot get the ERIC one to appear in the auto-complete list of names. Is there a way round this?

**Comment by kitenetter** [comment]
All of the regional collator roles have now been moved over (except for the one mentioned in the previous comment). Need to resolve whether any further action is required for the other 'non-standard' filters shown in the screenshot above.

**Comment by johnvanbreda** [comment]
@kitenetter it's because Paul has taken over Katherine Pinnock's account at some point - if you search for her, then you will find the correct email.

**Comment by kitenetter** [comment]
Tidy up menu list and unpublish pages

**Comment by kitenetter** [comment]
Now being picked up under #1238 - closing.
