### ISSUE TITLE
Yahoo search API for place and postcode search

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#99]
Hello John

Yahoo search API for place and postcode search has stopped working. I have implemented settings for forms like "Enter a casual record" and "Enter a list of records" on iRecord and used the "Google Places API text search." option for georeferencing. 

There are number of forms still require this implement. 

One possibility is to change the default option in data_entry_helper.php. 

Second possibility is to create the account on Yahoo for iRecord. I'm not sure about how useful this option at present.

**Comment by johnvanbreda** [comment]
I don't think "creating the account on Yahoo" will do anything useful - the API has been completely removed. See http://stackoverflow.com/questions/15780064/yahoo-api-is-geo-api-closed-formerly-where-yahooapis-com.
Given that the Google search API works, I'm not sure what the priority of this is. At some point a full review of latest APIs available for place searches and appropriate updates to support them would be good.

**Comment by BirenRathod** [comment]
Thanks, John about finding out the Yahoo bit. I was not so ken about it. Also, It is not my concern about the priority. it is about the people complain the difficulty experiencing with search place on the map. This may be not huge requirement, but they need a some attention to implement. Which I did for some forms on iRecord and ladybird site. 

Also, you have mentioned about the appropriate support, it will be good if you get a chance to implement code and set the default to "Google places API text search" and remove the yahoo option from the list.

In the meantime, I'm going to create key on google map API, so other websites will get support for search facility.

**Comment by BirenRathod** [comment]
I have created the BRC account on Google, so all we could keep all Google API keys at one place. I have created some in there.
