### ISSUE TITLE
Activities: summary map

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#990]
For Activities that map out small area, the default map display gets obscured by 100km and 10km grid refs (example shown is for [Bringsty Common](https://www.brc.ac.uk/irecord/activities/summary?group_id=374&implicit=)):
![image](https://user-images.githubusercontent.com/16039111/105527298-6c547680-5cdb-11eb-9bcb-9d216da406a8.png)

The Bringsty Common example no longer has a problem with 100km square records, but the 10km square records mask all other records as well as the site boundary.

**Comment by kitenetter** [comment]
This issue has been raised again following the recent changes to map appearance for #421 and #1045. The summary page for the Bringsty Common activity still displays as above, with solid blue obscuring the detail. The record details page is a bit clearer but still has large areas of solid blue that do not change as you zoom in:

![image](https://user-images.githubusercontent.com/16039111/114842027-5cc36600-9dd0-11eb-9fa1-d6b0ef146d6f.png)

Reducing the opacity would help, and I still wonder if we can find a better way of handling the records only recorded to 10 km square precision - can they be excluded from view when zoomed in?

**Comment by johnvanbreda** [comment]
Now significantly reduces the build-up of opacity when multiple records on same grid square.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda that seems much improved on the activity summary, but there's still some odd behaviour on the explore page:

![image](https://user-images.githubusercontent.com/16039111/115030130-aa1e0100-9ebe-11eb-9a38-4d53c4267511.png)

As you zoom in the coarser resolution records seem to be removed from viw, which is desirable I think, but at the moment it is being slow to update, and doesn't always seem to update consistently, as shown above. Worth re-opening if there is a quick fix but otherwise we may need to have a wider review of map behaviour at some point.

**Comment by johnvanbreda** [comment]
@kitenetter if you can provide a way of consistently reproducing these sort of errors I can have a look.

**Comment by kitenetter** [comment]
In firefox, I go to the activity explore page:
https://www.brc.ac.uk/irecord/activities/explore?group_id=374&implicit=

When it first opens up it is zoomed out and the site boundary is obscured by two solid blue 10km squares.

If I click on the + button once to zoom in, all I can see is solid blue across the entire map window.

If I click on the + button a second time to zoom in further, and then wait for 5-10 seconds, the map ends up looking as it does in the [screenshot above](https://github.com/BiologicalRecordsCentre/iRecord/issues/990#issuecomment-821169862). The left-hand 10km square has vanished, the right-hand one remains and obscures most of the display.

If I click on the + button a third time to zoom in further, and then wait for a few seconds, the 10km squares are no longer displayed, and the more precise grid squares can be seen.

If I zoom back out the 10km squares reappear - the right-hand square reappears on the first click out, the left-hand ones joins it on the second click out.

Is that the information you needed, or would it help to generate a HAR file?

**Comment by johnvanbreda** [comment]
@kitenetter I've applied the same algorithm to the Explore page for all records, my records and activities - is that better?

**Comment by kitenetter** [comment]
I think that is better, thanks. But I still find it erratic. This is the view I get when I first go to the page - it displays 10km squares and 1km squares as well as the more precise records:

![image](https://user-images.githubusercontent.com/16039111/115269321-19039000-a133-11eb-89e0-5f0821110b1e.png)

If I zoom in once, the 10km and 1km squares are still filled in, although they are less opaque than before:

![image](https://user-images.githubusercontent.com/16039111/115269525-523c0000-a133-11eb-8fcf-beb854720c91.png)

If I zoom in a second time, the 1km squares disappear from view, and the left-hand 10km square disappears, but the right-hand one remains shaded:

![image](https://user-images.githubusercontent.com/16039111/115269761-87485280-a133-11eb-90ad-51f77b52ff64.png)

Is that something to do with whether the centroid for the square falls inside the site polygon? Otherwise it seems a bit random.

I think the display as it stands is workable even though I don't understand why it is behaving the way it does. However, I'm unsure what the best option would be. I'm tempted to say that 10km squares should always be removed from view once you zoom in to a certain point, and maybe 1km squares should also disappear beyong a certain point, but since individual users are likely to have varying views on this I wonder if the ultimate solution would be to give people a set of controls so they can specify what level of precison they wish to include in their maps. This could either be a map control, or a control availabel to activity admins, but I guess a map control would be more generally applicable.

We can probably close this issue, but let me know if a map control solution is realistic, and if so I'll open it as a new feature request.

**Comment by johnvanbreda** [comment]
OK, I think I understand. As well as the grid squares being dropped if the centroid is outside the viewport, there is a limit of 10,000 geometries in the web-request that is issued when the map is zoomed in showing full detail. This would normally be enough, but for this particular activity there is a very high density of records. We are not controlling which records get dropped off in any way, so as you change the view of the map different combinations of squares are shown or dropped. We could increase the limit, but that's not very sustainable as the web responses are already very large for the above map. 

A better approach might be to explore using aggregations to only return a single copy of each grid square variation, with a count of records. The code for clicking on the map will need to change in this case as the grid squares won't know which record IDs they are for. This will take a few hours so I'll leave it for now until it's prioritised.

**Comment by kitenetter** [comment]
@johnvanbreda this issue has been raised again by the Bringsty Common people - it seems that the D9 update has taken us back to an older version of the grid square handling. I know that we haven't yet addressed the long-term solution to use aggregations, but can we reinstate the algorithm that you applied when this arose before?

**Comment by johnvanbreda** [comment]
Fixed. The new version of iRecord's activity summary didn't have the configuration changed I applied when this issue was initially tackled for some reason.

**Comment by kitenetter** [comment]
This is still causing problems, e.g. for the South Stoke activity:
https://irecord.org.uk/activities/summary?group_id=1893&implicit=

where a number of irrelevant 10 km records are obscuring the map. Not sure if the above aggregations proposal would address this, or if we need to explore #856 or #5 further.

**Comment by johnvanbreda** [comment]
Improvements made to ensure big squares do not dominate the map, also clicking when zoomed in finds all squares under the click point not just the first one. Done in develop branch.

**Comment by johnvanbreda** [comment]
Code deployed.

**Comment by kitenetter** [comment]
This problem is re-occurring since the server move.

**Comment by johnvanbreda** [comment]
@kitenetter is this still an issue? My feeling is that the opacity is much better now, but that when showing the data for a smallish site, it doesn't make sense to include any 10km precision grid squares which are highly likely to be outside the site boundary.

**Comment by kitenetter** [comment]
@johnvanbreda the 10 km square records are still an issue for the smaller sites. I thought we had managed to exclude them at one point, but they are currently visible, so if there is a way of excluding them when zoomed in I think that is still desirable. Or we could consider giving users the option of specifying what level of precision they wish to see when setting up an activity.

**Comment by johnvanbreda** [comment]
Added code to the develop branch to filter out very imprecise data that are much bigger than the reporting polygon.
