### ISSUE TITLE
ES download failing for large download

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#992]
I'm trying to download a large set of data for Butterfly Conservation, consisting of 599663 moth records. The progress wheel reaches 550000 and then displays "An error occurred with the request to download data."

There is some slightly complicated filtering:
- insect - moth
- Exclude confidential records
- Exclude unreleased records
- Records input between 24/02/2017 and 31/12/2019
- Exclude not accepted records
- Exclude UKBMS WCBS-BBS, UKBMS WCBS-BC

A previous download of 655881 butterfly records completed with no error message, but that was with simpler filtering:
- insect - butterfly
- Exclude confidential records
- Exclude unreleased records
- Records recorded between 01/01/2020 and 31/12/2020
- Exclude not accepted records

Marked as urgent because BC are waiting on this data, but it can wait till Monday! And I will try the download again at some point.

**Comment by kitenetter** [comment]
Tried a smaller download and am getting the same error message. This time it got as far as 115000 records out of the total 233675.

Relatively simple filtering:
- insect - moth
- Exclude confidential records
- Exclude unreleased records
- Records recorded between 01/01/2020 and 31/12/2020
- Exclude not accepted records

**Comment by kitenetter** [comment]
This morning the smaller (233675 records) download went through smoothly. I then tried the larger (599663 records) one and it again failed having reached 550000, with the same message "An error occurred with the request to download data."

**Comment by johnvanbreda** [comment]
@kitenetter if I masquerade as you are these downloads available for me to test - if so, what settings?

**Comment by kitenetter** [comment]
@johnvanbreda you need to masquerade as "iRecord support" and in the "Records to access" set it to:
Data-flow - BC download; moths 2017-19 excl WCBS; support, iRecord

It is the simple format that I am trying to download.

**Comment by johnvanbreda** [comment]
Thanks @kitenetter. This should now be sorted.

There were a handful of records in Elasticsearch that had a group ID (activity ID) but no group title which caused the download code to fail. I've re-indexed them and that fixed the problem.
