### ISSUE TITLE
Question: how do filters created in different places interact?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#994]
It is possible to create custom filters on these pages:
- Explore - My records
- Explore - All records
- Verify
- Download records

However, the range of saved filters that are subsequently available from different places on these four pages is a bit mystifying.

Filters that I create in My records and All records seem to become available in both those places, along with a long list of filters I've created previously. But these filters are not available on my Verify page, nor on my Download page.

Filters that I create on the Verify page are not available anywhere else.

Filters that I create on the Download page are not available anywhere else.

This behaviour seems to have varied over the years, e.g. some of the filters that I can now see on the Download page were created a long time ago on the Explore or Verify pages.

On the Download page, the list of filters I can see under "Custom filters" is different from the list of filters I can see in the Filter dropdown that appears next to the Create a filter button.

Also, when I create a filter on the Download records page just now I got an error message that simply said "undefined", but the filter appears to have saved anyway, although it doesn't appear in the "Custom filters" dropdown. However, I cannot now delete it. And in addition when I created a filter for another verifier on the Download page at the weekend, it did save correctly and it also appeared in the "Custom filters" dropdown.

It's hard for me to understand what is supposed to happen in order to provide guidance to other users. Are we able to document what should be happening so we can investigate whether it is behaving as intended?

**Comment by johnvanbreda** [comment]
At the moment there are 2 fields which "classify" filters:
1. Sharing - defines the mode used for sharing records with other websites.
2. Defines_permissions - false if the user creates their own, true if this filter defines a set of records the user has permission to access (e.g. for verification).

At the moment, when you visit any page, the sharing mode is defined by the type of page. So, all records and my records are reporting, download is "data flow" and verification is obviously verification. The filters assigned to each sharing type are therefore restricted to other pages of the same type. 

The defines_permissions filters will act to provide a "context" for verification, or an additional set of records you are allowed to download.

Now that this tool is being widely used, I think there is some merit to removing the sharing limitation on which filters are used where - at least for the user created ones, not the defines_permissions ones. So if you create a download filter for example, you can then use it on verification and reporting pages. A couple of concerns here though:
1. A filter that works on the All Records page might not be useful when applied to a limited set of records in your verification context (this is the reason why it was originally designed this way).
2. As the user may have created multiple versions of the same filter in the current setup, removing this limitation might mean they will see duplicates in their list.
