### ISSUE TITLE
Save button only works some of the time when creating new filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#995]
I've been setting up new filters for the LERC downloads this morning, and so far the Save button has only worked 50% of the time. When it doesn't work I have to close the page and re-create the filter from scratch. This is a bit frustrating when I've got about 70 new filters to set up!

**Comment by kitenetter** [comment]
Found the problem - I was trying to set up filters for an LERC that has download roles for two accounts, and I have given both filters an identical name. This causes the second filter to fail to save, without generating any error message. All filter names need to be unique.

Closing.

**Comment by johnvanbreda** [comment]
@kitenetter Feel free to re-open with the requirement being to correctly display a warning if a duplicate name is saved.
