### ISSUE TITLE
Review and enhance the import from spreadsheets process

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#999]
Use of this facility is growing, and the number of enquiries about it, how to use it, and how to undo things when they go wrong is increasing. We need to find some resource to put into this. For now I'm just going to list things as they arise so that we can break down into smaller issues and prioritise.

- Set defaults so that users are always offered the "iRecord Import" survey and the "UK Master List" species list. For the latter it should not be too easy to choose anything else!
- The current tick boxes to remember the field mapping are not working
- Some verifiers would like to be able to import datasets as verified
- We need an undo button! Or a data management tool that allows whole sets of imported records to be deleted.
- It would be good to be able to associate some metadata with an imported dataset, to make it clear what the source of ther records is
- It would be good for verifiers at least to be able to filter records by import guid - not sure if this would also be a useful addition to the Explore pages, but for verifiers it would be very useful
- Remove the 'non-recommended' attributes from the very long list of attributes to match when using the "iRecord Import" survey (in a similar way to the attribute contols applied to the DRN survey)
- Add some more Help text to the import pages themselves (it's all in the guide, but some hints on the pages would help - I don't know how to edit these pages)
- Implement the existing option for importing direct from an Excel file

**Comment by DavidHepper** [comment]
The undocumented* feature in the section 'Lookup of existing records' can only be used if the column headings are deliberately mismatched. If the headings all match this option is unavailable cannot be used!

* in PDF v3.2

**Comment by DavidHepper** [comment]
It would be useful if the import process would drop any record matching the External Key value (if specified), so that duplicates are not imported.

**Comment by DavidHepper** [comment]
Should issue #879 be merged into this one?

**Comment by DavidHepper** [comment]
The documentation doesn't say that XLS and XLSX are valid formats but the warning if a TXT file is selected says they are valid. Are they fully tested? They are more convenient for data manipulation (though I prefer ODS).

**Comment by johnvanbreda** [comment]
XLS and XLSX files are both in experimental support at the moment - the code is done but not thoroughly tested. Supporting other formats is definitely possible as the library used to parse Excel files supports quite a few formats.

**Comment by johnvanbreda** [comment]
The develop branch of the v2 importer code has now been updated to support existing record updates (and potentially deletion).

**Comment by cubitmg** [comment]
Taking Martin's "verifiers would like to be able to import datasets as verified" requirement a bit further, the ability to update existing records with a verification value would be very helpful. (There are more sophisticated verification checking capabilities used by some verifiers outwith iRecord and so even if records are 'provisionally' verified within iRecord there are likely to be updates to some of these based on this external verification. I should raise a ticket about extending the verification rules within iRecord!)
PS is there a ticket for the "v2 Importer"? This presumably includes the RecordKey as an input field?

**Comment by kitenetter** [comment]
Issues around the new importer are now being dealt with in #1405 so I will close this one.

@DavidHepper I have imported from an Excel file using the current importer, and all went well, but I've only done it once so far and for a fairly small file. Further testing will be done with the new importer.

@cubitmg I don't understand what you mean by "includes the RecordKey as an input field"? Are you talking about downloading records from iRecord, verifying offline, and then uploading the verification decisions? If so that is a different feature and one that we aren't prioritising at the moment. With the new importer we are intending to allow verifiers to upload new records with a verification decision already attached. If there is still a need for a download-verify-upload process we can reconsider that in future.

**Comment by cubitmg** [comment]
Thanks @kitenetter. Yes, I was considering a download-verify-upload process, but the need for that would be very much reduced if [Enable the use of local record cleaner rules #1403](https://github.com/BiologicalRecordsCentre/iRecord/issues/1403) might enable some of the Validator functions we have been discussing (https://butterfly-conservation.org/in-your-area/east-scotland-branch/moth-spreadsheet-validator).
